import {useCallback,useEffect,useId,useMemo,useRef,useState} from "react";
import {useLocale} from "../../../i18n/hooks";
import {ENTERPRISE_MEMBER_LINKING_COPY,ENTERPRISE_MEMBER_LINKING_LOCALES,type EnterpriseMemberLinkingLocale} from "../../../i18n/partner/enterpriseMemberLinking";
import {ENTERPRISE_AUTHORITY_COPY} from "../../../i18n/partner/enterpriseAuthority";
import {organizationAuthorityService} from "../enterprise/organizationAuthorityService";
import {EnterpriseMemberLinkingService,enterpriseMemberLinkingService} from "../enterprise/memberLinkingService";
import type {EnterpriseAuthorityProjection,StaffMembershipProjection} from "../enterprise/organizationAuthorityModel";
import type {MemberLinkingContext,MemberLinkingProjection} from "../enterprise/memberLinkingModel";

export default function EnterpriseMemberLinking({service=enterpriseMemberLinkingService}:{service?:EnterpriseMemberLinkingService}){
 const locale=useLocale() as EnterpriseMemberLinkingLocale,resolvedLocale=ENTERPRISE_MEMBER_LINKING_LOCALES.includes(locale)?locale:"en",copy=ENTERPRISE_MEMBER_LINKING_COPY[resolvedLocale],scopeCopy=ENTERPRISE_AUTHORITY_COPY[resolvedLocale],id=useId();
 const [authority,setAuthority]=useState<EnterpriseAuthorityProjection|null>(null),[projection,setProjection]=useState<MemberLinkingProjection|null>(null),[organizationId,setOrganizationId]=useState(""),[propertyId,setPropertyId]=useState(""),[courseId,setCourseId]=useState(""),[knownGolferId,setKnownGolferId]=useState(""),[busy,setBusy]=useState(true);
 const inviteCommandId=useRef(crypto.randomUUID()),unlinkCommandIds=useRef(new Map<string,string>());
 const organizations=authority?.organizations.filter(o=>authority.actorMembershipIds.some(mid=>authority.memberships.some(m=>m.membershipId===mid&&m.organizationId===o.organizationId&&m.status==="active")))||[];
 const organization=organizations.find(o=>o.organizationId===organizationId),properties=organization?.properties||[],property=properties.find(p=>p.propertyId===propertyId),courses=property?.courses||[];
 const membership:StaffMembershipProjection|undefined=authority?.memberships.find(m=>authority.actorMembershipIds.includes(m.membershipId)&&m.status==="active"&&m.organizationId===organizationId&&m.scope.kind==="course"&&m.scope.propertyId===propertyId&&m.scope.courseId===courseId&&m.role==="course_manager");
 const course=courses.find(item=>item.courseId===courseId);
 const context=useMemo<MemberLinkingContext|null>(()=>membership?{actorMembershipId:membership.membershipId,organizationId,propertyId,courseId,role:membership.role,scope:membership.scope,organizationStatus:organization?.status||"unavailable",courseStatus:course?.status||"unavailable"}:null,[membership,organizationId,propertyId,courseId,organization?.status,course?.status]);
 useEffect(()=>{void(async()=>{setBusy(true);const a=await organizationAuthorityService.load();setAuthority(a);const o=a.organizations.find(item=>a.actorMembershipIds.some(mid=>a.memberships.some(m=>m.membershipId===mid&&m.organizationId===item.organizationId&&m.status==="active")));setOrganizationId(o?.organizationId||"");setBusy(false)})()},[]);
 useEffect(()=>{if(!properties.some(p=>p.propertyId===propertyId))setPropertyId(properties[0]?.propertyId||"")},[properties,propertyId]); useEffect(()=>{if(!courses.some(c=>c.courseId===courseId))setCourseId(courses[0]?.courseId||"")},[courses,courseId]);
 const read=useCallback(async()=>{if(!context){setProjection(null);return}setBusy(true);try{setProjection(await service.read(context))}finally{setBusy(false)}},[context,service]); useEffect(()=>{void read()},[read]);
 const invite=async()=>{if(!context||!knownGolferId.trim())return;setBusy(true);try{const next=await service.inviteKnownGolfer(context,{commandId:inviteCommandId.current,organizationId,propertyId,courseId,knownGolferId:knownGolferId.trim(),consentVersion:1});setProjection(next);if(next.state!=="unavailable"){inviteCommandId.current=crypto.randomUUID();setKnownGolferId("")}}finally{setBusy(false)}};
 const unlink=async(linkId:string,consentVersion:number)=>{if(!context)return;const stable=unlinkCommandIds.current.get(linkId)||crypto.randomUUID();unlinkCommandIds.current.set(linkId,stable);setBusy(true);try{const next=await service.unlink(context,{commandId:stable,organizationId,propertyId,courseId,linkId,consentVersion});setProjection(next);if(next.state!=="unavailable")unlinkCommandIds.current.delete(linkId)}finally{setBusy(false)}};
 return <section aria-labelledby={`${id}-title`} style={{display:"grid",gap:16}}><header><h2 id={`${id}-title`}>{copy.title}</h2><p>{copy.intro}</p></header><p role="note">{copy.scope}</p><p role="note">{copy.privacy}</p><p role="note">{copy.consent}</p>
 <fieldset><legend>{copy.scope}</legend><label>{scopeCopy.organization}<select value={organizationId} onChange={e=>{setOrganizationId(e.target.value);setPropertyId("");setCourseId("")}}><option value="">—</option>{organizations.map(o=><option key={o.organizationId} value={o.organizationId}>{o.displayName} · {o.organizationId}</option>)}</select></label><label>{scopeCopy.property}<select value={propertyId} onChange={e=>{setPropertyId(e.target.value);setCourseId("")}}><option value="">—</option>{properties.map(p=><option key={p.propertyId} value={p.propertyId}>{p.displayName} · {p.propertyId}</option>)}</select></label><label>{scopeCopy.course}<select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">—</option>{courses.map(c=><option key={c.courseId} value={c.courseId}>{c.displayName} · {c.courseId}</option>)}</select></label></fieldset>
 <form onSubmit={e=>{e.preventDefault();void invite()}}><label htmlFor={`${id}-golfer`}>{copy.knownId}</label><input id={`${id}-golfer`} value={knownGolferId} onChange={e=>setKnownGolferId(e.target.value)} autoComplete="off" required/><button type="submit" disabled={!context||busy}>{copy.invite}</button></form>
 {busy?<p role="status" aria-live="polite">{copy.loading}</p>:projection?.state==="suspended"?<p role="alert">{copy.suspended}</p>:projection?.state==="stale"?<p role="status">{copy.stale} <button type="button" onClick={()=>void read()}>{copy.retry}</button></p>:!projection||projection.state==="unavailable"?<div role="alert"><p>{copy.unavailable}</p><code>{projection?.supportReference||"GF-EN-006:MEMBER_LINKING_PRODUCER_UNAVAILABLE"}</code><button type="button" disabled={!context} onClick={()=>void read()}>{copy.retry}</button></div>:projection.state==="empty"?<p>{copy.empty}</p>:<div style={{overflowX:"auto"}}><table><caption>{copy.title}</caption><thead><tr><th>{copy.member}</th><th>{copy.status}</th><th>{copy.expiry}</th><th><span className="sr-only">{scopeCopy.action}</span></th></tr></thead><tbody>{projection.links.map(link=><tr key={link.linkId}><td>{link.golferDisplayLabel}<br/><code>{link.memberReference}</code></td><td>{link.state}</td><td>{link.expiresAt?<time dateTime={link.expiresAt}>{link.expiresAt}</time>:"—"}</td><td><button type="button" disabled={busy||!["invited","accepted"].includes(link.state)} onClick={()=>void unlink(link.linkId,link.consentVersion)}>{copy.unlink}</button></td></tr>)}</tbody></table></div>}
 {!!projection?.receipts.length&&<section aria-labelledby={`${id}-receipts`}><h3 id={`${id}-receipts`}>{copy.receipts}</h3><ol>{projection.receipts.map(r=><li key={r.receiptId}><code>{r.receiptId}</code> · {r.action} · {r.actorKind} · v{r.consentVersion} · <time dateTime={r.occurredAt}>{r.occurredAt}</time></li>)}</ol></section>}<aside><strong>{copy.support}</strong><br/><code>{projection?.supportReference||"GF-EN-006:MEMBER_LINKING_PRODUCER_UNAVAILABLE"}</code></aside></section>;
}
