import type {EnterpriseAuthorityLocale} from "./enterpriseAuthority";
const en={title:"Course intake",intro:"Provider records remain candidates until scoped staff review and a separate server-confirmed publication.",loading:"Loading course intake…",unavailable:"Course intake authority is unavailable. No provider call or catalogue write was made.",budget:"Monthly request budget",remaining:"Remaining usable budget",country:"Country",canonical:"Canonical",active:"Active",fresh:"Fresh",missing:"Missing coordinates",planner:"Zero-call intake plan",manual:"Manual country request",manualHint:"Adds only a planning request.",plan:"Build zero-call plan",queue:"Candidate review queue",empty:"No candidates await review.",review:"Review",approve:"Approve publication",reject:"Reject",confirm:"Confirm server mutation",cancel:"Cancel",success:"Server confirmed the mutation.",notAllowed:"Your scoped enterprise role cannot mutate course intake.",retry:"Retry"};
export const COURSE_INTAKE_COPY:Record<EnterpriseAuthorityLocale,typeof en>={
en,
th:{...en,title:"การรับข้อมูลสนาม",intro:"ข้อมูลผู้ให้บริการยังเป็นรายการเสนอชื่อจนกว่าเจ้าหน้าที่ตามขอบเขตจะตรวจสอบและเซิร์ฟเวอร์ยืนยันการเผยแพร่แยกต่างหาก",loading:"กำลังโหลดการรับข้อมูลสนาม…",unavailable:"สิทธิ์การรับข้อมูลสนามใช้ไม่ได้ ไม่มีการเรียกผู้ให้บริการหรือเขียนแค็ตตาล็อก",budget:"งบคำขอรายเดือน",remaining:"งบที่ใช้ได้คงเหลือ",country:"ประเทศ",canonical:"รายการมาตรฐาน",active:"ใช้งาน",fresh:"ข้อมูลใหม่",missing:"พิกัดขาดหาย",planner:"แผนรับข้อมูลแบบไม่เรียก API",manual:"คำขอประเทศด้วยตนเอง",manualHint:"เพิ่มเฉพาะคำขอในแผน",plan:"สร้างแผนแบบไม่เรียก API",queue:"คิวตรวจสอบรายการเสนอชื่อ",empty:"ไม่มีรายการรอตรวจสอบ",review:"ตรวจสอบ",approve:"อนุมัติการเผยแพร่",reject:"ปฏิเสธ",confirm:"ยืนยันการเปลี่ยนแปลงกับเซิร์ฟเวอร์",cancel:"ยกเลิก",success:"เซิร์ฟเวอร์ยืนยันการดำเนินการแล้ว",notAllowed:"บทบาทองค์กรตามขอบเขตของคุณเปลี่ยนการรับข้อมูลสนามไม่ได้",retry:"ลองอีกครั้ง"},
ko:{...en,title:"코스 인테이크",intro:"공급자 레코드는 범위가 지정된 직원의 검토와 별도 서버 확인 게시 전까지 후보로 유지됩니다.",loading:"코스 인테이크 불러오는 중…",unavailable:"코스 인테이크 권한을 사용할 수 없습니다. 공급자 호출이나 카탈로그 쓰기는 없었습니다.",budget:"월간 요청 예산",remaining:"사용 가능 잔여량",country:"국가",canonical:"정규",active:"활성",fresh:"최신",missing:"좌표 누락",planner:"무호출 인테이크 계획",manual:"수동 국가 요청",manualHint:"계획 요청만 추가합니다.",plan:"무호출 계획 만들기",queue:"후보 검토 대기열",empty:"검토할 후보가 없습니다.",review:"검토",approve:"게시 승인",reject:"거부",confirm:"서버 변경 확인",cancel:"취소",success:"서버가 변경을 확인했습니다.",notAllowed:"범위가 지정된 엔터프라이즈 역할로는 코스 인테이크를 변경할 수 없습니다.",retry:"다시 시도"},
ja:{...en,title:"コース受入れ",intro:"プロバイダーレコードは、範囲指定された担当者の確認と別のサーバー確定公開まで候補のままです。",loading:"コース受入れを読み込み中…",unavailable:"受入れ権限を利用できません。プロバイダー呼出しやカタログ書込みはありません。",budget:"月間リクエスト予算",remaining:"利用可能残数",country:"国",canonical:"正規",active:"有効",fresh:"最新",missing:"座標不足",planner:"ゼロ呼出し受入れ計画",manual:"手動の国リクエスト",manualHint:"計画依頼のみ追加します。",plan:"ゼロ呼出し計画を作成",queue:"候補確認キュー",empty:"確認待ち候補はありません。",review:"確認",approve:"公開を承認",reject:"却下",confirm:"サーバー変更を確認",cancel:"キャンセル",success:"サーバーが変更を確定しました。",notAllowed:"範囲指定された企業ロールではコース受入れを変更できません。",retry:"再試行"},
zh:{...en,title:"球场接收",intro:"服务商记录在限定范围的员工审核并由服务器另行确认发布前始终是候选项。",loading:"正在加载球场接收…",unavailable:"球场接收权限不可用，未调用服务商，也未写入目录。",budget:"每月请求预算",remaining:"可用余额",country:"国家",canonical:"权威记录",active:"有效",fresh:"新鲜",missing:"缺少坐标",planner:"零调用接收计划",manual:"手动国家请求",manualHint:"仅添加规划请求。",plan:"生成零调用计划",queue:"候选审核队列",empty:"没有待审核候选项。",review:"审核",approve:"批准发布",reject:"拒绝",confirm:"确认服务器变更",cancel:"取消",success:"服务器已确认变更。",notAllowed:"您限定范围的企业角色无权变更球场接收。",retry:"重试"},
es:{...en,title:"Ingreso de campos",intro:"Los registros del proveedor siguen como candidatos hasta la revisión del personal con ámbito y una publicación confirmada por separado en el servidor.",loading:"Cargando ingreso de campos…",unavailable:"La autoridad de ingreso no está disponible. No se llamó al proveedor ni se escribió el catálogo.",budget:"Presupuesto mensual",remaining:"Saldo utilizable",country:"País",canonical:"Canónicos",active:"Activos",fresh:"Recientes",missing:"Sin coordenadas",planner:"Plan de ingreso sin llamadas",manual:"Solicitud manual de país",manualHint:"Solo añade una solicitud al plan.",plan:"Crear plan sin llamadas",queue:"Cola de revisión",empty:"No hay candidatos pendientes.",review:"Revisar",approve:"Aprobar publicación",reject:"Rechazar",confirm:"Confirmar cambio del servidor",cancel:"Cancelar",success:"El servidor confirmó el cambio.",notAllowed:"Tu rol empresarial con ámbito no puede modificar el ingreso de campos.",retry:"Reintentar"},
fr:{...en,title:"Admission des parcours",intro:"Les données fournisseur restent candidates jusqu’au contrôle du personnel habilité et à une publication distincte confirmée par le serveur.",loading:"Chargement de l’admission…",unavailable:"Autorité d’admission indisponible. Aucun appel fournisseur ni écriture catalogue.",budget:"Budget mensuel",remaining:"Solde utilisable",country:"Pays",canonical:"Références",active:"Actifs",fresh:"Récents",missing:"Coordonnées absentes",planner:"Plan d’admission sans appel",manual:"Demande manuelle de pays",manualHint:"Ajoute seulement une demande au plan.",plan:"Créer un plan sans appel",queue:"File de contrôle",empty:"Aucun candidat à contrôler.",review:"Contrôler",approve:"Approuver la publication",reject:"Rejeter",confirm:"Confirmer la mutation serveur",cancel:"Annuler",success:"Le serveur a confirmé la mutation.",notAllowed:"Votre rôle d’entreprise limité ne permet pas de modifier l’admission.",retry:"Réessayer"},
de:{...en,title:"Golfplatzaufnahme",intro:"Anbieterdatensätze bleiben Kandidaten, bis berechtigte Mitarbeiter sie prüfen und der Server die Veröffentlichung getrennt bestätigt.",loading:"Golfplatzaufnahme wird geladen…",unavailable:"Aufnahmeberechtigung nicht verfügbar. Kein Anbieteraufruf und keine Katalogänderung.",budget:"Monatliches Anfragebudget",remaining:"Nutzbarer Rest",country:"Land",canonical:"Verbindlich",active:"Aktiv",fresh:"Aktuell",missing:"Koordinaten fehlen",planner:"Aufnahmeplan ohne Aufruf",manual:"Manuelle Länderanfrage",manualHint:"Fügt nur eine Plananfrage hinzu.",plan:"Plan ohne Aufruf erstellen",queue:"Prüfwarteschlange",empty:"Keine Kandidaten zur Prüfung.",review:"Prüfen",approve:"Veröffentlichung freigeben",reject:"Ablehnen",confirm:"Servermutation bestätigen",cancel:"Abbrechen",success:"Der Server hat die Mutation bestätigt.",notAllowed:"Ihre bereichsgebundene Unternehmensrolle darf die Aufnahme nicht ändern.",retry:"Erneut versuchen"}
};
