export const ENTERPRISE_ONBOARDING_LOCALES=["en","th","ko","ja","zh","es","fr","de"]as const;export type EnterpriseOnboardingLocale=typeof ENTERPRISE_ONBOARDING_LOCALES[number];
const common={steps:"Application steps",stepLabels:["Organization","Course","Disclosures","Agreement","Review"],scope:"Server-owned scope",organizationId:"Organization ID",propertyId:"Property ID",courseId:"Course ID",organization:"Organization request",legalName:"Legal name",displayName:"Display name",registration:"Registration number",jurisdiction:"Jurisdiction",propertyCourse:"Property and course",property:"Property name",course:"Course name",canonicalCourseId:"Canonical course ID (assigned by Golfriend)",address:"Address",website:"Website",representative:"Authorized representative",fullName:"Full name",jobTitle:"Job title",email:"Business email",phone:"Phone",authorityDeclaration:"I declare that I am authorized to represent this organization. This declaration does not verify authority.",profile:"Course profile",description:"Description",holes:"Holes",timezone:"Time zone",facilities:"Facilities",accessibility:"Accessibility information",disclosures:"Purpose disclosures",dataUse:"I reviewed the data-use disclosure.",memberManagement:"I reviewed member-management purposes and golfer-consent duties.",tournamentManagement:"I reviewed tournament-management purposes.",bookingCommission:"I reviewed booking coordination and commission boundaries.",trial:"Free trial offer",days:"days",trialNotice:"The selected offer requires Admin authorization and starts only at verified activation. It does not create a subscription.",agreement:"Enterprise agreement",version:"Version",digest:"Canonical digest",commission:"Central booking commission policy",unavailableRate:"Rate unavailable",legalReview:"Jurisdiction-specific legal review is required before production launch.",explicitAccept:"I have read the complete agreement and explicitly accept this exact version and scope.",accepted:"Acceptance receipt",agreementUnavailable:"The authoritative agreement is unavailable. Acceptance and submission remain disabled.",save:"Save draft",saving:"Saving…",submit:"Submit for Admin review",withdraw:"Withdraw application",adminReview:"Admin review",adminHandoff:"Portal cannot approve, activate a trial, or grant partner status. Contact Golfriend Admin using this reference.",activationPending:"Awaiting authoritative activation",receipts:"Immutable references",returnDashboard:"Return to Portal dashboard",retry:"Retry",stale:"This projection is stale. Refresh before changing it.",statuses:{draft:"Draft",submitted:"Submitted",under_review:"Under review",changes_requested:"Changes requested",approved_for_trial:"Approved for trial",trial_active:"Trial active",trial_expiring:"Trial expiring",trial_expired:"Trial expired",conversion_review:"Conversion review",active_partner:"Active partner",declined:"Declined",suspended:"Suspended",withdrawn:"Withdrawn",unavailable:"Unavailable"}};
const localized={
 en:{title:"Join Golfriend",intro:"Apply for an Enterprise golf-course relationship.",status:"Application status",truth:"An unsigned or unactivated course is not a partner, cannot be invoiced, and has no live availability or provider access.",loading:"Loading authoritative application…",unavailable:"Onboarding is unavailable. Nothing was submitted.",retryNotice:"The command was not confirmed. Retry safely with the same command."},
 th:{title:"เข้าร่วม Golfriend",intro:"สมัครความสัมพันธ์องค์กรสำหรับสนามกอล์ฟ",status:"สถานะใบสมัคร",truth:"สนามที่ยังไม่ลงนามหรือยังไม่เปิดใช้งานไม่ใช่พันธมิตร ไม่สามารถออกใบแจ้งหนี้ และไม่มีสถานะว่างสดหรือสิทธิ์ผู้ให้บริการ",loading:"กำลังโหลดใบสมัครจากระบบหลัก…",unavailable:"ระบบสมัครยังไม่พร้อม ไม่มีข้อมูลถูกส่ง",retryNotice:"คำสั่งยังไม่ได้รับการยืนยัน โปรดลองซ้ำอย่างปลอดภัย"},
 ko:{title:"Golfriend 가입",intro:"기업 골프장 관계를 신청하세요.",status:"신청 상태",truth:"서명 또는 활성화되지 않은 코스는 파트너가 아니며 청구, 실시간 예약 가능 여부 또는 공급자 접근 권한이 없습니다.",loading:"권한 있는 신청서를 불러오는 중…",unavailable:"온보딩을 사용할 수 없습니다. 제출된 내용이 없습니다.",retryNotice:"명령이 확인되지 않았습니다. 같은 명령으로 안전하게 다시 시도하세요."},
 ja:{title:"Golfriendに参加",intro:"ゴルフ場向けEnterprise契約を申請します。",status:"申請状況",truth:"未署名または未有効化のコースはパートナーではなく、請求、リアルタイム空き状況、プロバイダーアクセスはありません。",loading:"正規の申請を読み込み中…",unavailable:"オンボーディングは利用できません。送信されていません。",retryNotice:"コマンドは確認されていません。同じコマンドで安全に再試行してください。"},
 zh:{title:"加入 Golfriend",intro:"申请企业高尔夫球场合作关系。",status:"申请状态",truth:"未签署或未激活的球场不是合作伙伴，不能开具账单，也没有实时空位或供应商访问权限。",loading:"正在加载权威申请…",unavailable:"入驻暂不可用，未提交任何内容。",retryNotice:"命令尚未确认，请使用同一命令安全重试。"},
 es:{title:"Únete a Golfriend",intro:"Solicita una relación Enterprise para un campo de golf.",status:"Estado de la solicitud",truth:"Un campo sin firma o activación no es socio, no puede facturarse ni tiene disponibilidad en vivo o acceso al proveedor.",loading:"Cargando la solicitud autoritativa…",unavailable:"La incorporación no está disponible. No se envió nada.",retryNotice:"El comando no fue confirmado. Reinténtalo de forma segura."},
 fr:{title:"Rejoindre Golfriend",intro:"Demandez une relation Enterprise pour un parcours.",status:"État de la demande",truth:"Un parcours non signé ou non activé n’est pas partenaire, ne peut être facturé et n’a ni disponibilité en direct ni accès fournisseur.",loading:"Chargement de la demande officielle…",unavailable:"L’intégration est indisponible. Rien n’a été envoyé.",retryNotice:"La commande n’est pas confirmée. Réessayez en toute sécurité."},
 de:{title:"Golfriend beitreten",intro:"Enterprise-Beziehung für einen Golfplatz beantragen.",status:"Antragsstatus",truth:"Ein nicht unterzeichneter oder nicht aktivierter Platz ist kein Partner, darf nicht abgerechnet werden und hat keine Live-Verfügbarkeit oder Anbieterzugriff.",loading:"Verbindlichen Antrag laden…",unavailable:"Onboarding ist nicht verfügbar. Nichts wurde übermittelt.",retryNotice:"Der Befehl wurde nicht bestätigt. Sicher erneut versuchen."}}
export const ENTERPRISE_ONBOARDING_COPY=Object.fromEntries(ENTERPRISE_ONBOARDING_LOCALES.map(locale=>[locale,{...common,...localized[locale],saved:locale==="th"?"บันทึกแล้ว":locale==="ko"?"저장됨":locale==="ja"?"保存しました":locale==="zh"?"已保存":locale==="es"?"Guardado":locale==="fr"?"Enregistré":locale==="de"?"Gespeichert":"Saved"}]))as Record<EnterpriseOnboardingLocale,typeof common&typeof localized.en&{saved:string}>;
