export const ENTERPRISE_SUPPORT_LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export type EnterpriseSupportLocale=typeof ENTERPRISE_SUPPORT_LOCALES[number];
const en={title:"Partner Support and Request Center",intro:"Requests are bound to your verified representative authority and exact course. Golfriend Admin decisions remain external.",language:"Language",scope:"Authorized course",selectScope:"Select a course",newRequest:"Create request",type:"Request type",subject:"Subject",details:"Details",preferences:"Notification preferences",preferenceNotice:"Preferences are recorded only. This Portal does not send email, SMS or push notifications.",email:"Email",sms:"SMS",push:"Push",saveDraft:"Save draft",submit:"Submit",reply:"Reply",withdraw:"Withdraw",reopen:"Reopen",close:"Close after resolution",attach:"Attach evidence reference",evidenceType:"Evidence type",referenceId:"Reference ID",label:"Label",status:"Status",requests:"Your course requests",empty:"No requests exist for this course.",loading:"Loading authoritative support requests…",offline:"The Support Center appears offline. Nothing was changed.",unavailable:"Support commands are unavailable. Retry after authority is restored.",suspended:"Operational authority is suspended. Support requests are read-only.",retry:"Retry",adminBoundary:"Admin assignment, internal notes, replies and status decisions are unavailable until the Admin-owned command boundary is integrated.",receipt:"Immutable receipt",success:"Command confirmed",canonicalFallback:"Canonical English fallback is shown for missing translated server content.",notAvailable:"Not available",representative:"Representative",admin:"Admin",requestTypes:{onboarding_help:"Onboarding help",course_profile_correction:"Course-profile correction",trial_question:"Trial question",member_management_help:"Member-management help",tournament_support:"Tournament support",booking_coordination:"Booking coordination",commission_clarification:"Commission clarification",technical_issue:"Technical issue",general_support:"General support"},statuses:{draft:"Draft",submitted:"Submitted",acknowledged:"Acknowledged",needs_information:"Needs information",under_review:"Under review",resolved:"Resolved",closed:"Closed",withdrawn:"Withdrawn"},evidenceTypes:{document:"Document",image:"Image",log:"Technical log",receipt:"Receipt"}};
const translated:Record<Exclude<EnterpriseSupportLocale,"en">,Partial<typeof en>>={
 th:{title:"ศูนย์ช่วยเหลือและคำขอสำหรับพันธมิตร",intro:"คำขอผูกกับอำนาจผู้แทนที่ยืนยันแล้วและสนามที่ระบุอย่างชัดเจน การตัดสินใจของ Admin ยังเป็นอำนาจภายนอก",scope:"สนามที่ได้รับอำนาจ",selectScope:"เลือกสนาม",newRequest:"สร้างคำขอ",subject:"หัวข้อ",details:"รายละเอียด",preferences:"การตั้งค่าการแจ้งเตือน",saveDraft:"บันทึกร่าง",submit:"ส่งคำขอ",reply:"ตอบกลับ",withdraw:"ถอนคำขอ",reopen:"เปิดอีกครั้ง",close:"ปิดหลังแก้ไขแล้ว",requests:"คำขอของสนาม",empty:"ยังไม่มีคำขอสำหรับสนามนี้",loading:"กำลังโหลดคำขอจากระบบหลัก…",unavailable:"คำสั่งช่วยเหลือยังไม่พร้อม โปรดลองอีกครั้งเมื่อกู้คืนอำนาจแล้ว",retry:"ลองอีกครั้ง",adminBoundary:"การมอบหมาย Admin บันทึกภายใน คำตอบ และการตัดสินใจสถานะยังไม่พร้อมจนกว่าจะเชื่อมต่อคำสั่งฝั่ง Admin"},
 ko:{title:"파트너 지원 및 요청 센터",scope:"승인된 코스",selectScope:"코스 선택",newRequest:"요청 만들기",subject:"제목",details:"세부 정보",saveDraft:"초안 저장",submit:"제출",reply:"답장",withdraw:"철회",reopen:"다시 열기",close:"해결 후 닫기",requests:"코스 요청",empty:"이 코스에 요청이 없습니다.",loading:"권한 있는 지원 요청을 불러오는 중…",retry:"다시 시도"},
 ja:{title:"パートナーサポート・リクエストセンター",scope:"承認済みコース",selectScope:"コースを選択",newRequest:"リクエストを作成",subject:"件名",details:"詳細",saveDraft:"下書きを保存",submit:"送信",reply:"返信",withdraw:"取り下げ",reopen:"再開",close:"解決後に閉じる",requests:"コースのリクエスト",empty:"このコースのリクエストはありません。",loading:"正規のサポートリクエストを読み込み中…",retry:"再試行"},
 zh:{title:"合作伙伴支持与请求中心",scope:"授权球场",selectScope:"选择球场",newRequest:"创建请求",subject:"主题",details:"详情",saveDraft:"保存草稿",submit:"提交",reply:"回复",withdraw:"撤回",reopen:"重新打开",close:"解决后关闭",requests:"球场请求",empty:"此球场没有请求。",loading:"正在加载权威支持请求…",retry:"重试"},
 es:{title:"Centro de soporte y solicitudes para socios",scope:"Campo autorizado",selectScope:"Seleccionar campo",newRequest:"Crear solicitud",subject:"Asunto",details:"Detalles",saveDraft:"Guardar borrador",submit:"Enviar",reply:"Responder",withdraw:"Retirar",reopen:"Reabrir",close:"Cerrar tras la resolución",requests:"Solicitudes del campo",empty:"No hay solicitudes para este campo.",loading:"Cargando solicitudes autorizadas…",retry:"Reintentar"},
 fr:{title:"Centre d’assistance et de demandes partenaires",scope:"Parcours autorisé",selectScope:"Sélectionner un parcours",newRequest:"Créer une demande",subject:"Objet",details:"Détails",saveDraft:"Enregistrer le brouillon",submit:"Envoyer",reply:"Répondre",withdraw:"Retirer",reopen:"Rouvrir",close:"Fermer après résolution",requests:"Demandes du parcours",empty:"Aucune demande pour ce parcours.",loading:"Chargement des demandes officielles…",retry:"Réessayer"},
 de:{title:"Partner-Support- und Anfragezentrum",scope:"Autorisierter Platz",selectScope:"Platz auswählen",newRequest:"Anfrage erstellen",subject:"Betreff",details:"Details",saveDraft:"Entwurf speichern",submit:"Senden",reply:"Antworten",withdraw:"Zurückziehen",reopen:"Wieder öffnen",close:"Nach Lösung schließen",requests:"Platzanfragen",empty:"Für diesen Platz gibt es keine Anfragen.",loading:"Verbindliche Supportanfragen werden geladen…",retry:"Erneut versuchen"}
};
const structured={
 th:{language:"ภาษา",notAvailable:"ไม่มีข้อมูล",representative:"ผู้แทน",admin:"ผู้ดูแลระบบ",requestTypes:{onboarding_help:"ความช่วยเหลือการเริ่มต้น",course_profile_correction:"แก้ไขโปรไฟล์สนาม",trial_question:"คำถามเกี่ยวกับช่วงทดลอง",member_management_help:"ความช่วยเหลือการจัดการสมาชิก",tournament_support:"สนับสนุนการแข่งขัน",booking_coordination:"ประสานงานการจอง",commission_clarification:"ชี้แจงค่าคอมมิชชัน",technical_issue:"ปัญหาทางเทคนิค",general_support:"ความช่วยเหลือทั่วไป"},statuses:{draft:"ร่าง",submitted:"ส่งแล้ว",acknowledged:"รับทราบแล้ว",needs_information:"ต้องการข้อมูล",under_review:"กำลังตรวจสอบ",resolved:"แก้ไขแล้ว",closed:"ปิดแล้ว",withdrawn:"ถอนแล้ว"},evidenceTypes:{document:"เอกสาร",image:"รูปภาพ",log:"บันทึกทางเทคนิค",receipt:"ใบรับรอง"}},
 ko:{language:"언어",notAvailable:"없음",representative:"담당자",admin:"관리자",requestTypes:{onboarding_help:"온보딩 도움",course_profile_correction:"코스 프로필 수정",trial_question:"체험 관련 질문",member_management_help:"회원 관리 도움",tournament_support:"토너먼트 지원",booking_coordination:"예약 조정",commission_clarification:"수수료 설명",technical_issue:"기술 문제",general_support:"일반 지원"},statuses:{draft:"초안",submitted:"제출됨",acknowledged:"접수됨",needs_information:"정보 필요",under_review:"검토 중",resolved:"해결됨",closed:"종료됨",withdrawn:"철회됨"},evidenceTypes:{document:"문서",image:"이미지",log:"기술 로그",receipt:"영수증"}},
 ja:{language:"言語",notAvailable:"利用不可",representative:"担当者",admin:"管理者",requestTypes:{onboarding_help:"オンボーディング支援",course_profile_correction:"コースプロフィール修正",trial_question:"トライアルの質問",member_management_help:"会員管理支援",tournament_support:"トーナメント支援",booking_coordination:"予約調整",commission_clarification:"手数料の確認",technical_issue:"技術的な問題",general_support:"一般サポート"},statuses:{draft:"下書き",submitted:"送信済み",acknowledged:"受領済み",needs_information:"情報が必要",under_review:"確認中",resolved:"解決済み",closed:"終了",withdrawn:"取り下げ済み"},evidenceTypes:{document:"文書",image:"画像",log:"技術ログ",receipt:"受領書"}},
 zh:{language:"语言",notAvailable:"不可用",representative:"代表",admin:"管理员",requestTypes:{onboarding_help:"入驻帮助",course_profile_correction:"球场资料更正",trial_question:"试用问题",member_management_help:"会员管理帮助",tournament_support:"赛事支持",booking_coordination:"预订协调",commission_clarification:"佣金说明",technical_issue:"技术问题",general_support:"一般支持"},statuses:{draft:"草稿",submitted:"已提交",acknowledged:"已确认",needs_information:"需要信息",under_review:"审核中",resolved:"已解决",closed:"已关闭",withdrawn:"已撤回"},evidenceTypes:{document:"文档",image:"图片",log:"技术日志",receipt:"回执"}},
 es:{language:"Idioma",notAvailable:"No disponible",representative:"Representante",admin:"Administración",requestTypes:{onboarding_help:"Ayuda de incorporación",course_profile_correction:"Corrección del perfil del campo",trial_question:"Pregunta sobre la prueba",member_management_help:"Ayuda de gestión de socios",tournament_support:"Soporte de torneos",booking_coordination:"Coordinación de reservas",commission_clarification:"Aclaración de comisiones",technical_issue:"Problema técnico",general_support:"Soporte general"},statuses:{draft:"Borrador",submitted:"Enviada",acknowledged:"Confirmada",needs_information:"Necesita información",under_review:"En revisión",resolved:"Resuelta",closed:"Cerrada",withdrawn:"Retirada"},evidenceTypes:{document:"Documento",image:"Imagen",log:"Registro técnico",receipt:"Recibo"}},
 fr:{language:"Langue",notAvailable:"Indisponible",representative:"Représentant",admin:"Administration",requestTypes:{onboarding_help:"Aide à l’intégration",course_profile_correction:"Correction du profil du parcours",trial_question:"Question sur l’essai",member_management_help:"Aide à la gestion des membres",tournament_support:"Assistance tournoi",booking_coordination:"Coordination des réservations",commission_clarification:"Clarification de commission",technical_issue:"Problème technique",general_support:"Assistance générale"},statuses:{draft:"Brouillon",submitted:"Envoyée",acknowledged:"Reçue",needs_information:"Informations requises",under_review:"En cours d’examen",resolved:"Résolue",closed:"Fermée",withdrawn:"Retirée"},evidenceTypes:{document:"Document",image:"Image",log:"Journal technique",receipt:"Reçu"}},
 de:{language:"Sprache",notAvailable:"Nicht verfügbar",representative:"Vertretung",admin:"Administration",requestTypes:{onboarding_help:"Hilfe beim Onboarding",course_profile_correction:"Korrektur des Platzprofils",trial_question:"Frage zur Testphase",member_management_help:"Hilfe zur Mitgliederverwaltung",tournament_support:"Turnier-Support",booking_coordination:"Buchungskoordination",commission_clarification:"Klärung der Provision",technical_issue:"Technisches Problem",general_support:"Allgemeiner Support"},statuses:{draft:"Entwurf",submitted:"Eingereicht",acknowledged:"Bestätigt",needs_information:"Informationen erforderlich",under_review:"In Prüfung",resolved:"Gelöst",closed:"Geschlossen",withdrawn:"Zurückgezogen"},evidenceTypes:{document:"Dokument",image:"Bild",log:"Technisches Protokoll",receipt:"Beleg"}}
} as const;
const complete=(locale:Exclude<EnterpriseSupportLocale,"en">,value:Partial<typeof en>)=>({...en,...value,...structured[locale],locale}) as typeof en&{locale:EnterpriseSupportLocale};
export const ENTERPRISE_SUPPORT_COPY={en:{...en,locale:"en" as const},...Object.fromEntries((ENTERPRISE_SUPPORT_LOCALES.filter(x=>x!=="en") as Exclude<EnterpriseSupportLocale,"en">[]).map(locale=>[locale,complete(locale,translated[locale])]))} as Record<EnterpriseSupportLocale,typeof en&{locale:EnterpriseSupportLocale}>;
