export const COURSE_MEMBER_LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export type CourseMemberLocale=typeof COURSE_MEMBER_LOCALES[number];
const en={title:"Course Member Management",intro:"Search only this course’s Enterprise member records. This is not Golfriend user discovery.",scope:"Authorized course",search:"Search course member reference",filter:"Status filter",all:"All states",directory:"Course member directory",detail:"Member detail",close:"Close",next:"Next page",empty:"No course members match this filter.",loading:"Loading authoritative course members…",offline:"Member Management appears offline. Nothing was changed.",unavailable:"Unavailable",suspended:"Course authority is suspended. Member operations fail closed.",retry:"Retry",member:"Member reference",displayName:"Display name",contactReference:"Known contact reference",role:"Course role",status:"Status",updated:"Updated",invite:"Prepare invitation",reference:"Known intended member reference",locale:"Locale",purpose:"Purpose",saveDraft:"Save invitation draft",delivery:"Invitations and reminders remain awaiting delivery provider. This Portal sends no notification and creates no Auth account.",change:"Request member change",resend:"Prepare resend request",deactivate:"Request deactivation",reactivate:"Request reactivation",roleChange:"Request role change",requestedRole:"Requested course role",csv:"CSV import preview",csvSchema:"Schema: memberReference,displayName,contactReference,locale,purpose. Maximum 100 rows and 64 KiB. Preview creates no accounts or invitations.",preview:"Preview CSV",confirm:"Confirm preview requests",confirmWarning:"Confirm creation of drafts only. Nothing will be delivered or activated.",bulkAcknowledge:"I confirm this bounded preview and request drafts only.",duplicates:"Duplicate and conflict review",receipts:"Immutable receipts",success:"Server accepted the request",valid:"Valid",results:{valid:"Valid",duplicate:"Duplicate",conflict:"Conflict",rejected:"Rejected"},states:{invitation_draft:"Invitation draft",awaiting_delivery_provider:"Awaiting delivery provider",invited:"Invited",joined:"Joined",active:"Active",inactive:"Inactive",change_requested:"Change requested",conflict_review:"Conflict review",unavailable:"Unavailable"}};
const translations={
 th:{title:"การจัดการสมาชิกสนาม",intro:"ค้นหาเฉพาะระเบียนสมาชิก Enterprise ของสนามนี้ ไม่ใช่การค้นหาผู้ใช้ Golfriend",search:"ค้นหารหัสอ้างอิงสมาชิกสนาม",directory:"รายชื่อสมาชิกสนาม",invite:"เตรียมคำเชิญ",delivery:"คำเชิญและการเตือนจะรอผู้ให้บริการจัดส่ง พอร์ทัลนี้ไม่ส่งการแจ้งเตือนหรือสร้างบัญชี Auth",csv:"ตัวอย่างนำเข้า CSV",retry:"ลองอีกครั้ง"},
 ko:{title:"코스 회원 관리",intro:"이 코스의 Enterprise 회원 기록만 검색합니다. Golfriend 사용자 검색이 아닙니다.",search:"코스 회원 참조 검색",directory:"코스 회원 목록",invite:"초대 초안 준비",delivery:"초대와 알림은 전송 제공자를 기다립니다. 이 포털은 알림이나 Auth 계정을 만들지 않습니다.",csv:"CSV 가져오기 미리보기",retry:"다시 시도"},
 ja:{title:"コース会員管理",intro:"このコースのEnterprise会員レコードのみ検索します。Golfriendユーザー検索ではありません。",search:"コース会員参照を検索",directory:"コース会員一覧",invite:"招待下書きを作成",delivery:"招待と再送は配信事業者待ちです。このポータルは通知やAuthアカウントを作成しません。",csv:"CSVインポートプレビュー",retry:"再試行"},
 zh:{title:"球场会员管理",intro:"仅搜索本球场的企业会员记录，并非搜索Golfriend用户。",search:"搜索球场会员引用",directory:"球场会员目录",invite:"准备邀请草稿",delivery:"邀请和提醒等待发送服务商。本门户不会发送通知或创建Auth账户。",csv:"CSV导入预览",retry:"重试"},
 es:{title:"Gestión de miembros del campo",intro:"Busca solo registros de miembros Enterprise de este campo; no descubre usuarios de Golfriend.",search:"Buscar referencia de miembro",directory:"Directorio de miembros del campo",invite:"Preparar invitación",delivery:"Las invitaciones esperan al proveedor. El Portal no envía avisos ni crea cuentas Auth.",csv:"Vista previa de CSV",retry:"Reintentar"},
 fr:{title:"Gestion des membres du parcours",intro:"Recherche uniquement les membres Enterprise de ce parcours, jamais les utilisateurs Golfriend.",search:"Rechercher une référence membre",directory:"Répertoire des membres",invite:"Préparer une invitation",delivery:"Les invitations attendent le fournisseur. Le portail n’envoie rien et ne crée aucun compte Auth.",csv:"Aperçu CSV",retry:"Réessayer"},
 de:{title:"Platz-Mitgliederverwaltung",intro:"Durchsucht nur Enterprise-Mitglieder dieses Platzes, keine Golfriend-Benutzersuche.",search:"Mitgliedsreferenz suchen",directory:"Platz-Mitgliederverzeichnis",invite:"Einladung vorbereiten",delivery:"Einladungen warten auf den Zustelldienst. Das Portal sendet nichts und erstellt keine Auth-Konten.",csv:"CSV-Vorschau",retry:"Erneut versuchen"}
} as const;
export const COURSE_MEMBER_COPY=Object.fromEntries(COURSE_MEMBER_LOCALES.map(locale=>[locale,{...en,...(locale==="en"?{}:translations[locale]),locale}])) as Record<CourseMemberLocale,typeof en&{locale:CourseMemberLocale}>;
