export const PLAY_BOOKING_COMMUNICATION_LOCALES=['en','th','ko','ja','zh','es','fr','de']as const;
export const PLAY_BOOKING_COMMUNICATION_TYPES=['request_received','alternative_proposed','booking_confirmed','booking_declined','booking_changed','booking_cancelled','booking_expired','tee_time_reminder','course_message']as const;
export type PlayBookingCommunicationLocale=typeof PLAY_BOOKING_COMMUNICATION_LOCALES[number];
export type PlayBookingCommunicationType=typeof PLAY_BOOKING_COMMUNICATION_TYPES[number];
export type PlayBookingCommunicationCopy=Readonly<{recipientFallback:string;draftOnly:string;awaitingDeliveryProvider:string;messages:Readonly<Record<PlayBookingCommunicationType,string>>}>;
export const PLAY_BOOKING_COMMUNICATION:Readonly<Record<PlayBookingCommunicationLocale,PlayBookingCommunicationCopy>>={
 en:{recipientFallback:'Golfer',draftOnly:'Draft only. Nothing has been sent.',awaitingDeliveryProvider:'Awaiting an approved delivery provider.',messages:{request_received:'We have prepared an update that the booking request is awaiting course review.',alternative_proposed:'We have prepared an update about a different tee time for review.',booking_confirmed:'We have prepared an update based on the course’s verified confirmation.',booking_declined:'We have prepared an update that the request was declined and is not booked.',booking_changed:'We have prepared an update about a verified change to the booking.',booking_cancelled:'We have prepared an update that the booking was cancelled.',booking_expired:'We have prepared an update that the request expired and is not booked.',tee_time_reminder:'We have prepared a tee-time reminder for review.',course_message:'We have prepared a course message for review.'}},
 th:{recipientFallback:'นักกอล์ฟ',draftOnly:'เป็นเพียงฉบับร่าง ยังไม่ได้ส่งข้อความ',awaitingDeliveryProvider:'กำลังรอผู้ให้บริการจัดส่งที่ได้รับอนุมัติ',messages:{request_received:'เราเตรียมข้อความแจ้งว่าคำขอจองกำลังรอสนามตรวจสอบ',alternative_proposed:'เราเตรียมข้อความเกี่ยวกับเวลาออกรอบอื่นเพื่อให้ตรวจสอบ',booking_confirmed:'เราเตรียมข้อความตามการยืนยันที่ตรวจสอบแล้วจากสนาม',booking_declined:'เราเตรียมข้อความแจ้งว่าคำขอถูกปฏิเสธและยังไม่ได้จอง',booking_changed:'เราเตรียมข้อความเกี่ยวกับการเปลี่ยนแปลงการจองที่ตรวจสอบแล้ว',booking_cancelled:'เราเตรียมข้อความแจ้งว่าการจองถูกยกเลิกแล้ว',booking_expired:'เราเตรียมข้อความแจ้งว่าคำขอหมดอายุและยังไม่ได้จอง',tee_time_reminder:'เราเตรียมข้อความเตือนเวลาออกรอบเพื่อให้ตรวจสอบ',course_message:'เราเตรียมข้อความจากสนามเพื่อให้ตรวจสอบ'}},
 ko:{recipientFallback:'골퍼',draftOnly:'초안일 뿐이며 아직 전송되지 않았습니다.',awaitingDeliveryProvider:'승인된 전송 제공자를 기다리는 중입니다.',messages:{request_received:'예약 요청이 코스 검토를 기다리고 있다는 안내를 준비했습니다.',alternative_proposed:'검토할 다른 티타임 안내를 준비했습니다.',booking_confirmed:'코스의 검증된 확인을 바탕으로 안내를 준비했습니다.',booking_declined:'요청이 거절되어 예약되지 않았다는 안내를 준비했습니다.',booking_changed:'검증된 예약 변경 안내를 준비했습니다.',booking_cancelled:'예약이 취소되었다는 안내를 준비했습니다.',booking_expired:'요청이 만료되어 예약되지 않았다는 안내를 준비했습니다.',tee_time_reminder:'검토할 티타임 알림을 준비했습니다.',course_message:'검토할 코스 메시지를 준비했습니다.'}},
 ja:{recipientFallback:'ゴルファー',draftOnly:'下書きのみで、まだ送信されていません。',awaitingDeliveryProvider:'承認済み配信プロバイダーを待っています。',messages:{request_received:'予約依頼がコースの確認待ちである旨の案内を用意しました。',alternative_proposed:'確認用に別のティータイムの案内を用意しました。',booking_confirmed:'コースの検証済み確認に基づく案内を用意しました。',booking_declined:'依頼が拒否され予約されていない旨の案内を用意しました。',booking_changed:'検証済みの予約変更について案内を用意しました。',booking_cancelled:'予約がキャンセルされた旨の案内を用意しました。',booking_expired:'依頼が期限切れで予約されていない旨の案内を用意しました。',tee_time_reminder:'確認用のティータイム通知を用意しました。',course_message:'確認用のコースメッセージを用意しました。'}},
 zh:{recipientFallback:'球友',draftOnly:'仅为草稿，尚未发送。',awaitingDeliveryProvider:'正在等待获准的发送服务。',messages:{request_received:'已准备一则更新，说明预订请求正等待球场审核。',alternative_proposed:'已准备一则关于其他开球时间的更新，供你审核。',booking_confirmed:'已根据球场经验证的确认准备更新。',booking_declined:'已准备一则更新，说明请求被拒绝且尚未预订。',booking_changed:'已准备一则关于经验证预订变更的更新。',booking_cancelled:'已准备一则更新，说明预订已取消。',booking_expired:'已准备一则更新，说明请求已过期且尚未预订。',tee_time_reminder:'已准备开球时间提醒，供你审核。',course_message:'已准备球场消息，供你审核。'}},
 es:{recipientFallback:'Golfista',draftOnly:'Solo es un borrador. No se ha enviado nada.',awaitingDeliveryProvider:'A la espera de un proveedor de entrega aprobado.',messages:{request_received:'Hemos preparado un aviso de que la solicitud espera la revisión del campo.',alternative_proposed:'Hemos preparado un aviso sobre otra hora de salida para revisión.',booking_confirmed:'Hemos preparado un aviso basado en la confirmación verificada del campo.',booking_declined:'Hemos preparado un aviso de que la solicitud fue rechazada y no está reservada.',booking_changed:'Hemos preparado un aviso sobre un cambio verificado en la reserva.',booking_cancelled:'Hemos preparado un aviso de que la reserva fue cancelada.',booking_expired:'Hemos preparado un aviso de que la solicitud caducó y no está reservada.',tee_time_reminder:'Hemos preparado un recordatorio de la hora de salida para revisión.',course_message:'Hemos preparado un mensaje del campo para revisión.'}},
 fr:{recipientFallback:'Golfeur',draftOnly:'Brouillon uniquement. Aucun message n’a été envoyé.',awaitingDeliveryProvider:'En attente d’un prestataire d’envoi approuvé.',messages:{request_received:'Nous avons préparé une information indiquant que la demande attend l’examen du parcours.',alternative_proposed:'Nous avons préparé une information sur un autre départ à vérifier.',booking_confirmed:'Nous avons préparé une information fondée sur la confirmation vérifiée du parcours.',booking_declined:'Nous avons préparé une information indiquant que la demande est refusée et non réservée.',booking_changed:'Nous avons préparé une information sur une modification vérifiée de la réservation.',booking_cancelled:'Nous avons préparé une information indiquant que la réservation est annulée.',booking_expired:'Nous avons préparé une information indiquant que la demande a expiré et n’est pas réservée.',tee_time_reminder:'Nous avons préparé un rappel de départ à vérifier.',course_message:'Nous avons préparé un message du parcours à vérifier.'}},
 de:{recipientFallback:'Golfspieler',draftOnly:'Nur ein Entwurf. Es wurde nichts gesendet.',awaitingDeliveryProvider:'Ein genehmigter Zustelldienst ist noch ausstehend.',messages:{request_received:'Wir haben einen Hinweis vorbereitet, dass die Anfrage auf die Prüfung des Platzes wartet.',alternative_proposed:'Wir haben einen Hinweis zu einer anderen Startzeit zur Prüfung vorbereitet.',booking_confirmed:'Wir haben einen Hinweis auf Grundlage der verifizierten Platzbestätigung vorbereitet.',booking_declined:'Wir haben einen Hinweis vorbereitet, dass die Anfrage abgelehnt und nicht gebucht wurde.',booking_changed:'Wir haben einen Hinweis zu einer verifizierten Buchungsänderung vorbereitet.',booking_cancelled:'Wir haben einen Hinweis vorbereitet, dass die Buchung storniert wurde.',booking_expired:'Wir haben einen Hinweis vorbereitet, dass die Anfrage abgelaufen und nicht gebucht ist.',tee_time_reminder:'Wir haben eine Startzeiterinnerung zur Prüfung vorbereitet.',course_message:'Wir haben eine Platznachricht zur Prüfung vorbereitet.'}}
};
export function playBookingCommunicationT(locale:string,type:PlayBookingCommunicationType){const selected=(PLAY_BOOKING_COMMUNICATION_LOCALES.includes(locale as PlayBookingCommunicationLocale)?locale:'en')as PlayBookingCommunicationLocale;return Object.freeze({recipient:PLAY_BOOKING_COMMUNICATION[selected].recipientFallback,message:PLAY_BOOKING_COMMUNICATION[selected].messages[type],draftOnly:PLAY_BOOKING_COMMUNICATION[selected].draftOnly,delivery:PLAY_BOOKING_COMMUNICATION[selected].awaitingDeliveryProvider})}
