import {LOCALE_CODES,type CanonicalLocale} from '../locales.ts';
export const PLAY_BOOKING_COMMUNICATION_LOCALES=LOCALE_CODES;
export const PLAY_BOOKING_COMMUNICATION_TYPES=['request_received','information_needed','alternative_proposed','confirmed','declined','cancellation_received','cancellation_accepted','cancellation_declined','manual_support_required']as const;
export type PlayBookingCommunicationLocale=CanonicalLocale;
export type PlayBookingCommunicationType=typeof PLAY_BOOKING_COMMUNICATION_TYPES[number];
export type PlayBookingCommunicationCopy=Readonly<{recipientFallback:string;draftOnly:string;awaitingDeliveryProvider:string;messages:Readonly<Record<PlayBookingCommunicationType,string>>}>;
export const PLAY_BOOKING_COMMUNICATION:Readonly<Record<PlayBookingCommunicationLocale,PlayBookingCommunicationCopy>>={
 en:{recipientFallback:'Golfer',draftOnly:'Draft only. Nothing has been sent.',awaitingDeliveryProvider:'Awaiting an approved transmitter.',messages:{request_received:'We have prepared an update that the booking request is awaiting course review.',information_needed:'We have prepared a request for more booking information.',alternative_proposed:'We have prepared an update about a different tee time for review.',confirmed:'We have prepared an update based on the course’s verified confirmation.',declined:'We have prepared an update that the request was declined and is not booked.',cancellation_received:'We have prepared an update that the cancellation request is awaiting review.',cancellation_accepted:'We have prepared an update that the cancellation was accepted.',cancellation_declined:'We have prepared an update that the cancellation request was declined.',manual_support_required:'We have prepared an update that manual support is required.'}},
 th:{recipientFallback:'นักกอล์ฟ',draftOnly:'เป็นเพียงฉบับร่าง ยังไม่ได้ส่งข้อความ',awaitingDeliveryProvider:'กำลังรอผู้ส่งข้อความที่ได้รับอนุมัติ',messages:{request_received:'เราเตรียมข้อความแจ้งว่าคำขอจองกำลังรอสนามตรวจสอบ',information_needed:'เราเตรียมข้อความขอข้อมูลการจองเพิ่มเติม',alternative_proposed:'เราเตรียมข้อความเกี่ยวกับเวลาออกรอบอื่นเพื่อให้ตรวจสอบ',confirmed:'เราเตรียมข้อความตามการยืนยันที่ตรวจสอบแล้วจากสนาม',declined:'เราเตรียมข้อความแจ้งว่าคำขอถูกปฏิเสธและยังไม่ได้จอง',cancellation_received:'เราเตรียมข้อความแจ้งว่าคำขอยกเลิกกำลังรอการตรวจสอบ',cancellation_accepted:'เราเตรียมข้อความแจ้งว่าคำขอยกเลิกได้รับการยอมรับแล้ว',cancellation_declined:'เราเตรียมข้อความแจ้งว่าคำขอยกเลิกถูกปฏิเสธ',manual_support_required:'เราเตรียมข้อความแจ้งว่าต้องได้รับความช่วยเหลือจากเจ้าหน้าที่'}},
 ko:{recipientFallback:'골퍼',draftOnly:'초안일 뿐이며 아직 전송되지 않았습니다.',awaitingDeliveryProvider:'승인된 전송 수단을 기다리는 중입니다.',messages:{request_received:'예약 요청이 코스 검토를 기다리고 있다는 안내를 준비했습니다.',information_needed:'추가 예약 정보를 요청하는 안내를 준비했습니다.',alternative_proposed:'검토할 다른 티타임 안내를 준비했습니다.',confirmed:'코스의 검증된 확인을 바탕으로 안내를 준비했습니다.',declined:'요청이 거절되어 예약되지 않았다는 안내를 준비했습니다.',cancellation_received:'취소 요청이 검토를 기다리고 있다는 안내를 준비했습니다.',cancellation_accepted:'취소 요청이 승인되었다는 안내를 준비했습니다.',cancellation_declined:'취소 요청이 거절되었다는 안내를 준비했습니다.',manual_support_required:'직원의 수동 지원이 필요하다는 안내를 준비했습니다.'}},
 ja:{recipientFallback:'ゴルファー',draftOnly:'下書きのみで、まだ送信されていません。',awaitingDeliveryProvider:'承認済みの送信手段を待っています。',messages:{request_received:'予約依頼がコースの確認待ちである旨の案内を用意しました。',information_needed:'予約に関する追加情報を求める案内を用意しました。',alternative_proposed:'確認用に別のティータイムの案内を用意しました。',confirmed:'コースの検証済み確認に基づく案内を用意しました。',declined:'依頼が拒否され予約されていない旨の案内を用意しました。',cancellation_received:'キャンセル依頼が確認待ちである旨の案内を用意しました。',cancellation_accepted:'キャンセル依頼が承認された旨の案内を用意しました。',cancellation_declined:'キャンセル依頼が拒否された旨の案内を用意しました。',manual_support_required:'担当者による対応が必要である旨の案内を用意しました。'}},
 zh:{recipientFallback:'球友',draftOnly:'仅为草稿，尚未发送。',awaitingDeliveryProvider:'正在等待获准的发送方式。',messages:{request_received:'已准备一则更新，说明预订请求正等待球场审核。',information_needed:'已准备一则请求补充预订信息的消息。',alternative_proposed:'已准备一则关于其他开球时间的更新，供你审核。',confirmed:'已根据球场经验证的确认准备更新。',declined:'已准备一则更新，说明请求被拒绝且尚未预订。',cancellation_received:'已准备一则更新，说明取消请求正在等待审核。',cancellation_accepted:'已准备一则更新，说明取消请求已获接受。',cancellation_declined:'已准备一则更新，说明取消请求被拒绝。',manual_support_required:'已准备一则更新，说明需要人工支持。'}},
 es:{recipientFallback:'Golfista',draftOnly:'Solo es un borrador. No se ha enviado nada.',awaitingDeliveryProvider:'A la espera de un transmisor aprobado.',messages:{request_received:'Hemos preparado un aviso de que la solicitud espera la revisión del campo.',information_needed:'Hemos preparado una solicitud de información adicional de la reserva.',alternative_proposed:'Hemos preparado un aviso sobre otra hora de salida para revisión.',confirmed:'Hemos preparado un aviso basado en la confirmación verificada del campo.',declined:'Hemos preparado un aviso de que la solicitud fue rechazada y no está reservada.',cancellation_received:'Hemos preparado un aviso de que la cancelación espera revisión.',cancellation_accepted:'Hemos preparado un aviso de que la cancelación fue aceptada.',cancellation_declined:'Hemos preparado un aviso de que la cancelación fue rechazada.',manual_support_required:'Hemos preparado un aviso de que se necesita asistencia manual.'}},
 fr:{recipientFallback:'Golfeur',draftOnly:'Brouillon uniquement. Aucun message n’a été envoyé.',awaitingDeliveryProvider:'En attente d’un transmetteur approuvé.',messages:{request_received:'Nous avons préparé une information indiquant que la demande attend l’examen du parcours.',information_needed:'Nous avons préparé une demande d’informations supplémentaires sur la réservation.',alternative_proposed:'Nous avons préparé une information sur un autre départ à vérifier.',confirmed:'Nous avons préparé une information fondée sur la confirmation vérifiée du parcours.',declined:'Nous avons préparé une information indiquant que la demande est refusée et non réservée.',cancellation_received:'Nous avons préparé une information indiquant que l’annulation attend un examen.',cancellation_accepted:'Nous avons préparé une information indiquant que l’annulation est acceptée.',cancellation_declined:'Nous avons préparé une information indiquant que l’annulation est refusée.',manual_support_required:'Nous avons préparé une information indiquant qu’une assistance manuelle est nécessaire.'}},
 de:{recipientFallback:'Golfspieler',draftOnly:'Nur ein Entwurf. Es wurde nichts gesendet.',awaitingDeliveryProvider:'Ein genehmigter Übermittler ist noch ausstehend.',messages:{request_received:'Wir haben einen Hinweis vorbereitet, dass die Anfrage auf die Prüfung des Platzes wartet.',information_needed:'Wir haben eine Anfrage nach weiteren Buchungsinformationen vorbereitet.',alternative_proposed:'Wir haben einen Hinweis zu einer anderen Startzeit zur Prüfung vorbereitet.',confirmed:'Wir haben einen Hinweis auf Grundlage der verifizierten Platzbestätigung vorbereitet.',declined:'Wir haben einen Hinweis vorbereitet, dass die Anfrage abgelehnt und nicht gebucht wurde.',cancellation_received:'Wir haben einen Hinweis vorbereitet, dass die Stornierungsanfrage geprüft wird.',cancellation_accepted:'Wir haben einen Hinweis vorbereitet, dass die Stornierung angenommen wurde.',cancellation_declined:'Wir haben einen Hinweis vorbereitet, dass die Stornierung abgelehnt wurde.',manual_support_required:'Wir haben einen Hinweis vorbereitet, dass manuelle Unterstützung erforderlich ist.'}}
};
export function playBookingCommunicationT(locale:string,type:PlayBookingCommunicationType){const selected=(PLAY_BOOKING_COMMUNICATION_LOCALES.includes(locale as PlayBookingCommunicationLocale)?locale:'en')as PlayBookingCommunicationLocale;return Object.freeze({recipient:PLAY_BOOKING_COMMUNICATION[selected].recipientFallback,message:PLAY_BOOKING_COMMUNICATION[selected].messages[type],draftOnly:PLAY_BOOKING_COMMUNICATION[selected].draftOnly,delivery:PLAY_BOOKING_COMMUNICATION[selected].awaitingDeliveryProvider})}
