import type { LocaleDict } from '../dict.ts';

export type PlayBookingDeskKey =
  | 'title' | 'subtitle' | 'sectionLabel' | 'loading' | 'refreshing' | 'empty'
  | 'reload' | 'retry' | 'retryHint' | 'courseLabel' | 'dateLabel' | 'timeLabel'
  | 'memberLabel' | 'versionLabel' | 'referenceLabel' | 'statusPending'
  | 'statusAlternative' | 'statusConfirmed' | 'statusRejected' | 'statusChanged'
  | 'statusCancelled' | 'statusExpired' | 'statusCompleted'
  | 'statusUnknown' | 'actionsLabel' | 'confirm' | 'proposeAlternative' | 'cancel'
  | 'complete' | 'messageMember' | 'close' | 'submit' | 'busy'
  | 'alternativeTitle' | 'alternativeSlotLabel' | 'alternativeMessageLabel'
  | 'messageTitle' | 'messageLabel' | 'cancelReviewTitle' | 'cancelReviewBody'
  | 'completeReviewTitle' | 'completeReviewBody' | 'loadError' | 'operationError'
  | 'staleError' | 'invalidDataError' | 'notificationUnavailable'
  | 'privacyBoundary' | 'providerBoundary' | 'acknowledged' | 'noChange'
  | 'outcomeLabel' | 'dialogCloseLabel' | 'queueTitle' | 'detailsTitle'
  | 'providerLabel' | 'termsLabel' | 'contactLabel' | 'unavailableValue'
  | 'delegatedScopeUnavailable' | 'conflictError' | 'receiptsTitle'
  | 'recoveryTitle' | 'authorizedAcknowledgement' | 'actionSucceeded';

export const PLAY_BOOKING_DESK: LocaleDict<PlayBookingDeskKey> = {
  en: {
    queueTitle: 'Booking queue', detailsTitle: 'Verified booking details', providerLabel: 'Provider', termsLabel: 'Provider terms', contactLabel: 'Authorized contact', unavailableValue: 'Not provided by the verified booking record', delegatedScopeUnavailable: 'Your delegated course scope could not be verified. No bookings are shown.', conflictError: 'Another authorized change was recorded first. Reload the verified booking before continuing.', receiptsTitle: 'Operation references', recoveryTitle: 'Recovery and retry', authorizedAcknowledgement: 'I am authorized for this course and have reviewed the verified booking details.', actionSucceeded: 'The server verified the action.', statusRejected: 'Rejected', statusChanged: 'Changed', statusExpired: 'Expired',
    title: 'Booking desk', subtitle: 'Review and coordinate verified requests for your authorized courses.', sectionLabel: 'Course booking operations', loading: 'Loading booking requests…', refreshing: 'Refreshing verified booking status…', empty: 'No booking requests are available.', reload: 'Reload bookings', retry: 'Try again', retryHint: 'Reload the verified status before trying the action again.', courseLabel: 'Course', dateLabel: 'Date', timeLabel: 'Time', memberLabel: 'Member', versionLabel: 'Version', referenceLabel: 'Reference', statusPending: 'Pending', statusAlternative: 'Alternative proposed', statusConfirmed: 'Confirmed', statusCancelled: 'Cancelled', statusCompleted: 'Completed', statusUnknown: 'Status unavailable', actionsLabel: 'Booking actions', confirm: 'Confirm request', proposeAlternative: 'Propose alternative', cancel: 'Cancel booking', complete: 'Mark completed', messageMember: 'Message member', close: 'Close', submit: 'Submit', busy: 'Saving verified change…', alternativeTitle: 'Propose another tee time', alternativeSlotLabel: 'Verified alternative slot ID', alternativeMessageLabel: 'Message explaining the alternative', messageTitle: 'Message the member', messageLabel: 'Message', cancelReviewTitle: 'Review cancellation', cancelReviewBody: 'Confirm that you intend to cancel this booking. The latest verified status will be checked first.', completeReviewTitle: 'Review completion', completeReviewBody: 'Confirm completion only when the course has authoritative evidence that play occurred.', loadError: 'Booking coordination is unavailable. No change was made.', operationError: 'The action could not be verified. No success is claimed.', staleError: 'This booking changed. Reload its verified status before trying again.', invalidDataError: 'The booking response could not be verified and was not displayed.', notificationUnavailable: 'Automatic notifications are not configured. Verified status remains available in Golfriend.', privacyBoundary: 'Only the minimum booking details needed by authorized course staff are shown.', providerBoundary: 'Golfriend coordinates provider-neutral booking status and does not process payment or settlement here.', acknowledged: 'Verified action acknowledged.', noChange: 'No verified change was made.', outcomeLabel: 'Booking action result', dialogCloseLabel: 'Close booking action dialog',
  },
  th: {
    queueTitle: 'คิวการจอง', detailsTitle: 'รายละเอียดการจองที่ยืนยันแล้ว', providerLabel: 'ผู้ให้บริการ', termsLabel: 'เงื่อนไขของผู้ให้บริการ', contactLabel: 'ช่องทางติดต่อที่ได้รับอนุญาต', unavailableValue: 'ไม่มีข้อมูลในบันทึกการจองที่ยืนยันแล้ว', delegatedScopeUnavailable: 'ไม่สามารถยืนยันขอบเขตสนามที่มอบหมายให้คุณได้ จึงไม่แสดงรายการจอง', conflictError: 'มีการบันทึกการเปลี่ยนแปลงโดยผู้มีอำนาจก่อนแล้ว โหลดการจองที่ยืนยันแล้วใหม่ก่อนดำเนินการต่อ', receiptsTitle: 'เลขอ้างอิงการดำเนินการ', recoveryTitle: 'การกู้คืนและลองใหม่', authorizedAcknowledgement: 'ฉันได้รับอนุญาตสำหรับสนามนี้และได้ตรวจสอบรายละเอียดการจองที่ยืนยันแล้ว', actionSucceeded: 'เซิร์ฟเวอร์ยืนยันการดำเนินการแล้ว', statusRejected: 'ปฏิเสธแล้ว', statusChanged: 'เปลี่ยนแปลงแล้ว', statusExpired: 'หมดอายุแล้ว',
    title: 'โต๊ะจัดการการจอง', subtitle: 'ตรวจสอบและประสานคำขอที่ยืนยันแล้วสำหรับสนามที่คุณได้รับอนุญาต', sectionLabel: 'การดำเนินงานจองสนาม', loading: 'กำลังโหลดคำขอจอง…', refreshing: 'กำลังรีเฟรชสถานะการจองที่ยืนยันแล้ว…', empty: 'ไม่มีคำขอจองที่พร้อมแสดง', reload: 'โหลดรายการจองใหม่', retry: 'ลองอีกครั้ง', retryHint: 'โหลดสถานะที่ยืนยันแล้วใหม่ก่อนลองดำเนินการอีกครั้ง', courseLabel: 'สนาม', dateLabel: 'วันที่', timeLabel: 'เวลา', memberLabel: 'สมาชิก', versionLabel: 'เวอร์ชัน', referenceLabel: 'เลขอ้างอิง', statusPending: 'รอดำเนินการ', statusAlternative: 'เสนอเวลาอื่นแล้ว', statusConfirmed: 'ยืนยันแล้ว', statusCancelled: 'ยกเลิกแล้ว', statusCompleted: 'เสร็จสิ้นแล้ว', statusUnknown: 'ไม่มีสถานะ', actionsLabel: 'การดำเนินการจอง', confirm: 'ยืนยันคำขอ', proposeAlternative: 'เสนอเวลาอื่น', cancel: 'ยกเลิกการจอง', complete: 'ทำเครื่องหมายว่าเสร็จสิ้น', messageMember: 'ส่งข้อความถึงสมาชิก', close: 'ปิด', submit: 'ส่ง', busy: 'กำลังบันทึกการเปลี่ยนแปลงที่ยืนยันแล้ว…', alternativeTitle: 'เสนอเวลาออกรอบอื่น', alternativeSlotLabel: 'รหัสช่วงเวลาอื่นที่ยืนยันแล้ว', alternativeMessageLabel: 'ข้อความอธิบายเวลาอื่น', messageTitle: 'ส่งข้อความถึงสมาชิก', messageLabel: 'ข้อความ', cancelReviewTitle: 'ตรวจสอบการยกเลิก', cancelReviewBody: 'ยืนยันว่าคุณต้องการยกเลิกการจองนี้ ระบบจะตรวจสอบสถานะล่าสุดที่ยืนยันแล้วก่อน', completeReviewTitle: 'ตรวจสอบการเสร็จสิ้น', completeReviewBody: 'ยืนยันการเสร็จสิ้นเฉพาะเมื่อสนามมีหลักฐานที่เชื่อถือได้ว่าได้เล่นจริง', loadError: 'ระบบประสานการจองไม่พร้อมใช้งาน ไม่มีการเปลี่ยนแปลง', operationError: 'ไม่สามารถยืนยันการดำเนินการได้ จึงไม่อ้างว่าสำเร็จ', staleError: 'การจองนี้มีการเปลี่ยนแปลง โหลดสถานะที่ยืนยันแล้วใหม่ก่อนลองอีกครั้ง', invalidDataError: 'ไม่สามารถยืนยันข้อมูลตอบกลับการจองได้ จึงไม่แสดงข้อมูล', notificationUnavailable: 'ยังไม่ได้ตั้งค่าการแจ้งเตือนอัตโนมัติ สถานะที่ยืนยันแล้วยังคงดูได้ใน Golfriend', privacyBoundary: 'แสดงเฉพาะรายละเอียดการจองขั้นต่ำที่พนักงานสนามผู้ได้รับอนุญาตต้องใช้', providerBoundary: 'Golfriend ประสานสถานะการจองแบบเป็นกลางต่อผู้ให้บริการ และไม่รับชำระเงินหรือชำระบัญชีที่นี่', acknowledged: 'รับทราบการดำเนินการที่ยืนยันแล้ว', noChange: 'ไม่มีการเปลี่ยนแปลงที่ยืนยันแล้ว', outcomeLabel: 'ผลการดำเนินการจอง', dialogCloseLabel: 'ปิดกล่องการดำเนินการจอง',
  },
  ko: {
    queueTitle: '예약 대기열', detailsTitle: '검증된 예약 세부 정보', providerLabel: '제공자', termsLabel: '제공자 약관', contactLabel: '승인된 연락처', unavailableValue: '검증된 예약 기록에 제공되지 않음', delegatedScopeUnavailable: '위임된 코스 범위를 검증할 수 없어 예약을 표시하지 않습니다.', conflictError: '다른 승인된 변경이 먼저 기록되었습니다. 계속하기 전에 검증된 예약을 새로 불러오세요.', receiptsTitle: '작업 참조 번호', recoveryTitle: '복구 및 재시도', authorizedAcknowledgement: '이 코스에 대한 권한이 있으며 검증된 예약 세부 정보를 확인했습니다.', actionSucceeded: '서버에서 작업을 검증했습니다.', statusRejected: '거절됨', statusChanged: '변경됨', statusExpired: '만료됨',
    title: '예약 데스크', subtitle: '권한이 있는 코스의 검증된 요청을 확인하고 조정합니다.', sectionLabel: '코스 예약 운영', loading: '예약 요청을 불러오는 중…', refreshing: '검증된 예약 상태를 새로 고치는 중…', empty: '표시할 예약 요청이 없습니다.', reload: '예약 다시 불러오기', retry: '다시 시도', retryHint: '작업을 다시 시도하기 전에 검증된 상태를 새로 불러오세요.', courseLabel: '코스', dateLabel: '날짜', timeLabel: '시간', memberLabel: '회원', versionLabel: '버전', referenceLabel: '참조 번호', statusPending: '대기 중', statusAlternative: '대체 시간 제안됨', statusConfirmed: '확정됨', statusCancelled: '취소됨', statusCompleted: '완료됨', statusUnknown: '상태 확인 불가', actionsLabel: '예약 작업', confirm: '요청 확정', proposeAlternative: '대체 시간 제안', cancel: '예약 취소', complete: '완료로 표시', messageMember: '회원에게 메시지', close: '닫기', submit: '제출', busy: '검증된 변경 사항을 저장하는 중…', alternativeTitle: '다른 티타임 제안', alternativeSlotLabel: '검증된 대체 슬롯 ID', alternativeMessageLabel: '대체 시간을 설명하는 메시지', messageTitle: '회원에게 메시지 보내기', messageLabel: '메시지', cancelReviewTitle: '취소 검토', cancelReviewBody: '이 예약을 취소하려는지 확인하세요. 먼저 최신 검증 상태를 확인합니다.', completeReviewTitle: '완료 검토', completeReviewBody: '코스에 실제 플레이를 입증하는 권위 있는 근거가 있을 때만 완료를 확인하세요.', loadError: '예약 조정을 사용할 수 없습니다. 변경되지 않았습니다.', operationError: '작업을 검증할 수 없어 성공으로 표시하지 않았습니다.', staleError: '이 예약이 변경되었습니다. 다시 시도하기 전에 검증된 상태를 새로 불러오세요.', invalidDataError: '예약 응답을 검증할 수 없어 표시하지 않았습니다.', notificationUnavailable: '자동 알림이 구성되지 않았습니다. Golfriend에서 검증된 상태를 계속 확인할 수 있습니다.', privacyBoundary: '권한이 있는 코스 직원에게 필요한 최소 예약 정보만 표시됩니다.', providerBoundary: 'Golfriend는 제공자 중립적인 예약 상태만 조정하며 여기에서 결제나 정산을 처리하지 않습니다.', acknowledged: '검증된 작업이 확인되었습니다.', noChange: '검증된 변경 사항이 없습니다.', outcomeLabel: '예약 작업 결과', dialogCloseLabel: '예약 작업 대화상자 닫기',
  },
  ja: {
    queueTitle: '予約キュー', detailsTitle: '確認済み予約の詳細', providerLabel: '提供者', termsLabel: '提供者の条件', contactLabel: '承認済み連絡先', unavailableValue: '確認済み予約記録には提供されていません', delegatedScopeUnavailable: '委任されたコース範囲を確認できないため、予約は表示されません。', conflictError: '別の承認済み変更が先に記録されました。続行前に確認済み予約を再読み込みしてください。', receiptsTitle: '操作参照番号', recoveryTitle: '復旧と再試行', authorizedAcknowledgement: 'このコースの権限を持ち、確認済みの予約詳細を確認しました。', actionSucceeded: 'サーバーが操作を確認しました。', statusRejected: '拒否済み', statusChanged: '変更済み', statusExpired: '期限切れ',
    title: '予約デスク', subtitle: '権限のあるコースの確認済みリクエストを審査し、調整します。', sectionLabel: 'コース予約業務', loading: '予約リクエストを読み込み中…', refreshing: '確認済みの予約状態を更新中…', empty: '表示できる予約リクエストはありません。', reload: '予約を再読み込み', retry: 'もう一度試す', retryHint: '操作を再試行する前に、確認済みの状態を再読み込みしてください。', courseLabel: 'コース', dateLabel: '日付', timeLabel: '時間', memberLabel: 'メンバー', versionLabel: 'バージョン', referenceLabel: '参照番号', statusPending: '保留中', statusAlternative: '代替案を提示済み', statusConfirmed: '確定', statusCancelled: 'キャンセル済み', statusCompleted: '完了', statusUnknown: '状態を確認できません', actionsLabel: '予約操作', confirm: 'リクエストを確定', proposeAlternative: '代替案を提示', cancel: '予約をキャンセル', complete: '完了として記録', messageMember: 'メンバーへ連絡', close: '閉じる', submit: '送信', busy: '確認済みの変更を保存中…', alternativeTitle: '別のスタート時間を提示', alternativeSlotLabel: '確認済み代替枠ID', alternativeMessageLabel: '代替案の説明メッセージ', messageTitle: 'メンバーへメッセージ', messageLabel: 'メッセージ', cancelReviewTitle: 'キャンセル内容の確認', cancelReviewBody: 'この予約をキャンセルする意思を確認してください。先に最新の確認済み状態を照合します。', completeReviewTitle: '完了内容の確認', completeReviewBody: '実際にプレーしたことを示す権威ある証拠をコースが保有する場合のみ完了を確定してください。', loadError: '予約調整を利用できません。変更は行われていません。', operationError: '操作を確認できないため、成功とは表示しません。', staleError: 'この予約は変更されています。再試行する前に確認済み状態を再読み込みしてください。', invalidDataError: '予約応答を確認できないため表示しませんでした。', notificationUnavailable: '自動通知は設定されていません。確認済み状態はGolfriendで引き続き確認できます。', privacyBoundary: '権限のあるコーススタッフに必要な最小限の予約情報のみ表示します。', providerBoundary: 'Golfriendは提供者中立の予約状態を調整し、ここで支払いや精算を処理しません。', acknowledged: '確認済みの操作を受け付けました。', noChange: '確認済みの変更はありません。', outcomeLabel: '予約操作の結果', dialogCloseLabel: '予約操作ダイアログを閉じる',
  },
  zh: {
    queueTitle: '预订队列', detailsTitle: '已验证的预订详情', providerLabel: '提供商', termsLabel: '提供商条款', contactLabel: '获授权的联系方式', unavailableValue: '已验证的预订记录未提供此信息', delegatedScopeUnavailable: '无法验证委派给您的球场范围，因此不显示预订。', conflictError: '另一项获授权的更改已先记录。请重新加载已验证预订后继续。', receiptsTitle: '操作参考编号', recoveryTitle: '恢复与重试', authorizedAcknowledgement: '我已获此球场授权，并已审核已验证的预订详情。', actionSucceeded: '服务器已验证此操作。', statusRejected: '已拒绝', statusChanged: '已变更', statusExpired: '已过期',
    title: '预订工作台', subtitle: '审核并协调您获授权球场的已验证请求。', sectionLabel: '球场预订运营', loading: '正在加载预订请求…', refreshing: '正在刷新已验证的预订状态…', empty: '没有可显示的预订请求。', reload: '重新加载预订', retry: '重试', retryHint: '再次操作前，请重新加载已验证状态。', courseLabel: '球场', dateLabel: '日期', timeLabel: '时间', memberLabel: '会员', versionLabel: '版本', referenceLabel: '参考编号', statusPending: '待处理', statusAlternative: '已提出替代时间', statusConfirmed: '已确认', statusCancelled: '已取消', statusCompleted: '已完成', statusUnknown: '状态不可用', actionsLabel: '预订操作', confirm: '确认请求', proposeAlternative: '提出替代时间', cancel: '取消预订', complete: '标记为已完成', messageMember: '给会员发消息', close: '关闭', submit: '提交', busy: '正在保存已验证的更改…', alternativeTitle: '提出其他开球时间', alternativeSlotLabel: '已验证的替代时段ID', alternativeMessageLabel: '说明替代时间的消息', messageTitle: '给会员发消息', messageLabel: '消息', cancelReviewTitle: '审核取消操作', cancelReviewBody: '请确认您要取消此预订。系统会先核对最新的已验证状态。', completeReviewTitle: '审核完成操作', completeReviewBody: '仅当球场拥有证明实际打球的权威证据时，才确认完成。', loadError: '预订协调暂不可用，未进行任何更改。', operationError: '无法验证此操作，因此不宣称操作成功。', staleError: '此预订已发生变化。请重新加载已验证状态后再试。', invalidDataError: '无法验证预订响应，因此未显示。', notificationUnavailable: '尚未配置自动通知。仍可在Golfriend中查看已验证状态。', privacyBoundary: '仅显示获授权球场员工所需的最少预订信息。', providerBoundary: 'Golfriend仅协调中立于提供商的预订状态，不在此处理付款或结算。', acknowledged: '已确认接收经验证的操作。', noChange: '没有已验证的更改。', outcomeLabel: '预订操作结果', dialogCloseLabel: '关闭预订操作对话框',
  },
  es: {
    queueTitle: 'Cola de reservas', detailsTitle: 'Detalles verificados de la reserva', providerLabel: 'Proveedor', termsLabel: 'Condiciones del proveedor', contactLabel: 'Contacto autorizado', unavailableValue: 'No consta en el registro verificado de la reserva', delegatedScopeUnavailable: 'No se pudo verificar el ámbito de campos que tienes delegado. No se muestran reservas.', conflictError: 'Se registró primero otro cambio autorizado. Vuelve a cargar la reserva verificada antes de continuar.', receiptsTitle: 'Referencias de operaciones', recoveryTitle: 'Recuperación y reintento', authorizedAcknowledgement: 'Tengo autorización para este campo y he revisado los detalles verificados de la reserva.', actionSucceeded: 'El servidor verificó la acción.', statusRejected: 'Rechazada', statusChanged: 'Modificada', statusExpired: 'Caducada',
    title: 'Mesa de reservas', subtitle: 'Revisa y coordina solicitudes verificadas de los campos que tienes autorizados.', sectionLabel: 'Operaciones de reservas del campo', loading: 'Cargando solicitudes de reserva…', refreshing: 'Actualizando el estado verificado de la reserva…', empty: 'No hay solicitudes de reserva disponibles.', reload: 'Volver a cargar reservas', retry: 'Intentar de nuevo', retryHint: 'Vuelve a cargar el estado verificado antes de intentar otra vez la acción.', courseLabel: 'Campo', dateLabel: 'Fecha', timeLabel: 'Hora', memberLabel: 'Miembro', versionLabel: 'Versión', referenceLabel: 'Referencia', statusPending: 'Pendiente', statusAlternative: 'Alternativa propuesta', statusConfirmed: 'Confirmada', statusCancelled: 'Cancelada', statusCompleted: 'Completada', statusUnknown: 'Estado no disponible', actionsLabel: 'Acciones de reserva', confirm: 'Confirmar solicitud', proposeAlternative: 'Proponer alternativa', cancel: 'Cancelar reserva', complete: 'Marcar como completada', messageMember: 'Enviar mensaje al miembro', close: 'Cerrar', submit: 'Enviar', busy: 'Guardando el cambio verificado…', alternativeTitle: 'Proponer otra hora de salida', alternativeSlotLabel: 'ID verificado de la franja alternativa', alternativeMessageLabel: 'Mensaje que explica la alternativa', messageTitle: 'Enviar mensaje al miembro', messageLabel: 'Mensaje', cancelReviewTitle: 'Revisar cancelación', cancelReviewBody: 'Confirma que deseas cancelar esta reserva. Primero se comprobará el último estado verificado.', completeReviewTitle: 'Revisar finalización', completeReviewBody: 'Confirma la finalización solo cuando el campo tenga pruebas autorizadas de que se jugó.', loadError: 'La coordinación de reservas no está disponible. No se realizó ningún cambio.', operationError: 'No se pudo verificar la acción. No se indica que haya tenido éxito.', staleError: 'Esta reserva ha cambiado. Vuelve a cargar su estado verificado antes de intentarlo de nuevo.', invalidDataError: 'No se pudo verificar la respuesta de reserva y no se mostró.', notificationUnavailable: 'Las notificaciones automáticas no están configuradas. El estado verificado sigue disponible en Golfriend.', privacyBoundary: 'Solo se muestran los datos mínimos de reserva que necesita el personal autorizado del campo.', providerBoundary: 'Golfriend coordina un estado de reserva neutral respecto al proveedor y no procesa pagos ni liquidaciones aquí.', acknowledged: 'Acción verificada reconocida.', noChange: 'No se realizó ningún cambio verificado.', outcomeLabel: 'Resultado de la acción de reserva', dialogCloseLabel: 'Cerrar el diálogo de acción de reserva',
  },
  fr: {
    queueTitle: 'File des réservations', detailsTitle: 'Détails vérifiés de la réservation', providerLabel: 'Prestataire', termsLabel: 'Conditions du prestataire', contactLabel: 'Contact autorisé', unavailableValue: 'Non fourni dans le dossier de réservation vérifié', delegatedScopeUnavailable: 'Le périmètre de parcours qui vous est délégué n’a pas pu être vérifié. Aucune réservation n’est affichée.', conflictError: 'Une autre modification autorisée a été enregistrée en premier. Rechargez la réservation vérifiée avant de continuer.', receiptsTitle: 'Références des opérations', recoveryTitle: 'Récupération et nouvelle tentative', authorizedAcknowledgement: 'Je suis autorisé pour ce parcours et j’ai examiné les détails vérifiés de la réservation.', actionSucceeded: 'Le serveur a vérifié l’action.', statusRejected: 'Refusée', statusChanged: 'Modifiée', statusExpired: 'Expirée',
    title: 'Bureau des réservations', subtitle: 'Examinez et coordonnez les demandes vérifiées pour les parcours qui vous sont autorisés.', sectionLabel: 'Opérations de réservation du parcours', loading: 'Chargement des demandes de réservation…', refreshing: 'Actualisation du statut vérifié de la réservation…', empty: 'Aucune demande de réservation disponible.', reload: 'Recharger les réservations', retry: 'Réessayer', retryHint: 'Rechargez le statut vérifié avant de réessayer cette action.', courseLabel: 'Parcours', dateLabel: 'Date', timeLabel: 'Heure', memberLabel: 'Membre', versionLabel: 'Version', referenceLabel: 'Référence', statusPending: 'En attente', statusAlternative: 'Alternative proposée', statusConfirmed: 'Confirmée', statusCancelled: 'Annulée', statusCompleted: 'Terminée', statusUnknown: 'Statut indisponible', actionsLabel: 'Actions de réservation', confirm: 'Confirmer la demande', proposeAlternative: 'Proposer une alternative', cancel: 'Annuler la réservation', complete: 'Marquer comme terminée', messageMember: 'Envoyer un message au membre', close: 'Fermer', submit: 'Envoyer', busy: 'Enregistrement de la modification vérifiée…', alternativeTitle: 'Proposer une autre heure de départ', alternativeSlotLabel: 'Identifiant vérifié du créneau alternatif', alternativeMessageLabel: 'Message expliquant la proposition', messageTitle: 'Envoyer un message au membre', messageLabel: 'Message', cancelReviewTitle: 'Vérifier l’annulation', cancelReviewBody: 'Confirmez votre intention d’annuler cette réservation. Le dernier statut vérifié sera contrôlé auparavant.', completeReviewTitle: 'Vérifier la fin de partie', completeReviewBody: 'Confirmez la fin uniquement lorsque le parcours possède une preuve faisant autorité que la partie a été jouée.', loadError: 'La coordination des réservations est indisponible. Aucune modification n’a été effectuée.', operationError: 'L’action n’a pas pu être vérifiée. Aucun succès n’est annoncé.', staleError: 'Cette réservation a changé. Rechargez son statut vérifié avant de réessayer.', invalidDataError: 'La réponse de réservation n’a pas pu être vérifiée et n’a pas été affichée.', notificationUnavailable: 'Les notifications automatiques ne sont pas configurées. Le statut vérifié reste disponible dans Golfriend.', privacyBoundary: 'Seules les informations minimales nécessaires au personnel autorisé du parcours sont affichées.', providerBoundary: 'Golfriend coordonne un statut de réservation neutre vis-à-vis du prestataire et ne traite ici ni paiement ni règlement.', acknowledged: 'Action vérifiée prise en compte.', noChange: 'Aucune modification vérifiée n’a été effectuée.', outcomeLabel: 'Résultat de l’action de réservation', dialogCloseLabel: 'Fermer la boîte de dialogue de réservation',
  },
  de: {
    queueTitle: 'Buchungswarteschlange', detailsTitle: 'Verifizierte Buchungsdetails', providerLabel: 'Anbieter', termsLabel: 'Anbieterbedingungen', contactLabel: 'Autorisierter Kontakt', unavailableValue: 'Im verifizierten Buchungsdatensatz nicht angegeben', delegatedScopeUnavailable: 'Ihr delegierter Platzumfang konnte nicht verifiziert werden. Es werden keine Buchungen angezeigt.', conflictError: 'Eine andere autorisierte Änderung wurde zuerst erfasst. Laden Sie die verifizierte Buchung neu, bevor Sie fortfahren.', receiptsTitle: 'Vorgangsreferenzen', recoveryTitle: 'Wiederherstellung und erneuter Versuch', authorizedAcknowledgement: 'Ich bin für diesen Platz autorisiert und habe die verifizierten Buchungsdetails geprüft.', actionSucceeded: 'Der Server hat die Aktion verifiziert.', statusRejected: 'Abgelehnt', statusChanged: 'Geändert', statusExpired: 'Abgelaufen',
    title: 'Buchungsdesk', subtitle: 'Prüfen und koordinieren Sie verifizierte Anfragen für Ihre berechtigten Plätze.', sectionLabel: 'Buchungsbetrieb des Golfplatzes', loading: 'Buchungsanfragen werden geladen…', refreshing: 'Der verifizierte Buchungsstatus wird aktualisiert…', empty: 'Keine Buchungsanfragen verfügbar.', reload: 'Buchungen neu laden', retry: 'Erneut versuchen', retryHint: 'Laden Sie den verifizierten Status neu, bevor Sie die Aktion wiederholen.', courseLabel: 'Golfplatz', dateLabel: 'Datum', timeLabel: 'Uhrzeit', memberLabel: 'Mitglied', versionLabel: 'Version', referenceLabel: 'Referenz', statusPending: 'Ausstehend', statusAlternative: 'Alternative vorgeschlagen', statusConfirmed: 'Bestätigt', statusCancelled: 'Storniert', statusCompleted: 'Abgeschlossen', statusUnknown: 'Status nicht verfügbar', actionsLabel: 'Buchungsaktionen', confirm: 'Anfrage bestätigen', proposeAlternative: 'Alternative vorschlagen', cancel: 'Buchung stornieren', complete: 'Als abgeschlossen markieren', messageMember: 'Mitglied benachrichtigen', close: 'Schließen', submit: 'Absenden', busy: 'Verifizierte Änderung wird gespeichert…', alternativeTitle: 'Andere Abschlagszeit vorschlagen', alternativeSlotLabel: 'Verifizierte ID des alternativen Zeitfensters', alternativeMessageLabel: 'Nachricht zur Erklärung der Alternative', messageTitle: 'Nachricht an das Mitglied', messageLabel: 'Nachricht', cancelReviewTitle: 'Stornierung prüfen', cancelReviewBody: 'Bestätigen Sie, dass Sie diese Buchung stornieren möchten. Zuerst wird der neueste verifizierte Status geprüft.', completeReviewTitle: 'Abschluss prüfen', completeReviewBody: 'Bestätigen Sie den Abschluss nur, wenn der Golfplatz einen maßgeblichen Nachweis für das gespielte Golf besitzt.', loadError: 'Die Buchungskoordination ist nicht verfügbar. Es wurde nichts geändert.', operationError: 'Die Aktion konnte nicht verifiziert werden. Ein Erfolg wird nicht behauptet.', staleError: 'Diese Buchung wurde geändert. Laden Sie den verifizierten Status vor einem erneuten Versuch neu.', invalidDataError: 'Die Buchungsantwort konnte nicht verifiziert werden und wurde nicht angezeigt.', notificationUnavailable: 'Automatische Benachrichtigungen sind nicht eingerichtet. Der verifizierte Status bleibt in Golfriend verfügbar.', privacyBoundary: 'Es werden nur die minimal erforderlichen Buchungsdaten für berechtigtes Platzpersonal angezeigt.', providerBoundary: 'Golfriend koordiniert einen anbieterneutralen Buchungsstatus und verarbeitet hier weder Zahlung noch Abrechnung.', acknowledged: 'Verifizierte Aktion bestätigt.', noChange: 'Es wurde keine verifizierte Änderung vorgenommen.', outcomeLabel: 'Ergebnis der Buchungsaktion', dialogCloseLabel: 'Dialog für Buchungsaktion schließen',
  },
};
