import type {CanonicalLocale} from './locales';

const codes=['draft','submitted','changes_requested','approved','active','suspended','expired','rejected','closed','golf_cafe','restaurant','coach','fitter','repair_shop','retailer','other','request_changes','approve','reject','suspend','reactivate','expire','close','retire','publish','impression','engagement','subscription_intent','provider_confirmed_subscription','golfriend_revenue','external_commission','promotion_zero_revenue','legalName','publicName','registrationReference','serviceDescription','locationId','locationName','address','city','countryCode','operatingHours','day','opens','closes','isClosed','evidenceId','evidenceKind','objectReference','contentDigest','promotionId','promotionVersion','reporting','jhccBatchId','unavailableState'] as const;
const values:Record<CanonicalLocale,string[]>={
en:['Draft','Submitted','Changes requested','Approved','Active','Suspended','Expired','Rejected','Closed','Golf café','Restaurant','Coach','Club fitter','Repair shop','Retailer','Other','Request changes','Approve','Reject','Suspend','Reactivate','Expire','Close','Retire','Publish','Impressions','Engagements','Subscription intents','Provider-confirmed subscriptions','Golfriend revenue','External business commissions','Zero-revenue promotions','Legal business name','Public business name','Registration reference','Service description','Location ID','Location name','Address','City','Country code','Operating hours','Day','Opens','Closes','Closed','Evidence ID','Evidence type','Evidence object reference','Content digest','Promotion ID','Promotion version','Operational reporting','JHCC batch ID','Unavailable'],
th:['ร่าง','ส่งแล้ว','ขอให้แก้ไข','อนุมัติแล้ว','ใช้งานอยู่','ระงับ','หมดอายุ','ปฏิเสธ','ปิดแล้ว','คาเฟ่กอล์ฟ','ร้านอาหาร','โค้ช','ช่างฟิตอุปกรณ์','ร้านซ่อม','ผู้ค้าปลีก','อื่น ๆ','ขอให้แก้ไข','อนุมัติ','ปฏิเสธ','ระงับ','เปิดใช้งานอีกครั้ง','ทำให้หมดอายุ','ปิด','ยุติการใช้','เผยแพร่','การแสดงผล','การมีส่วนร่วม','ความประสงค์สมัคร','การสมัครที่ผู้ให้บริการยืนยัน','รายได้ Golfriend','ค่าคอมมิชชันธุรกิจภายนอก','โปรโมชันรายได้ศูนย์','ชื่อนิติบุคคล','ชื่อธุรกิจที่แสดง','เลขอ้างอิงการจดทะเบียน','คำอธิบายบริการ','รหัสสถานที่','ชื่อสถานที่','ที่อยู่','เมือง','รหัสประเทศ','เวลาทำการ','วัน','เปิด','ปิด','หยุดทำการ','รหัสหลักฐาน','ประเภทหลักฐาน','เลขอ้างอิงวัตถุหลักฐาน','ไดเจสต์เนื้อหา','รหัสโปรโมชัน','เวอร์ชันโปรโมชัน','รายงานการดำเนินงาน','รหัสชุด JHCC','ไม่พร้อมใช้งาน'],
ko:['초안','제출됨','수정 요청','승인됨','활성','정지됨','만료됨','거절됨','종료됨','골프 카페','레스토랑','코치','피팅 전문가','수리점','소매점','기타','수정 요청','승인','거절','정지','재활성화','만료 처리','종료','폐기','게시','노출','참여','구독 의향','제공업체 확인 구독','Golfriend 수익','외부 사업 수수료','수익 없는 프로모션','법적 사업체명','공개 사업체명','등록 참조','서비스 설명','위치 ID','위치명','주소','도시','국가 코드','영업시간','요일','영업 시작','영업 종료','휴무','증거 ID','증거 유형','증거 객체 참조','콘텐츠 다이제스트','프로모션 ID','프로모션 버전','운영 보고','JHCC 배치 ID','사용 불가'],
ja:['下書き','提出済み','修正依頼','承認済み','有効','停止中','期限切れ','却下','終了','ゴルフカフェ','レストラン','コーチ','クラブフィッター','修理店','小売店','その他','修正を依頼','承認','却下','停止','再有効化','期限切れにする','終了','廃止','公開','表示回数','エンゲージメント','購読意向','プロバイダー確認済み購読','Golfriend 収益','外部事業手数料','収益ゼロのプロモーション','法人名','公開事業者名','登録参照','サービス説明','所在地 ID','所在地名','住所','市区町村','国コード','営業時間','曜日','開店','閉店','休業','証拠 ID','証拠種別','証拠オブジェクト参照','コンテンツダイジェスト','プロモーション ID','プロモーション版','運用レポート','JHCC バッチ ID','利用不可'],
zh:['草稿','已提交','要求更正','已批准','有效','已暂停','已过期','已拒绝','已关闭','高尔夫咖啡馆','餐厅','教练','球杆适配师','维修店','零售商','其他','要求更正','批准','拒绝','暂停','重新启用','设为过期','关闭','停用','发布','展示次数','互动次数','订阅意向','服务商确认的订阅','Golfriend 收入','外部商业佣金','零收入促销','法定企业名称','公开企业名称','注册编号','服务说明','地点 ID','地点名称','地址','城市','国家代码','营业时间','星期','开始营业','结束营业','休息','证据 ID','证据类型','证据对象编号','内容摘要','促销 ID','促销版本','运营报告','JHCC 批次 ID','不可用'],
es:['Borrador','Enviada','Cambios solicitados','Aprobada','Activa','Suspendida','Vencida','Rechazada','Cerrada','Café de golf','Restaurante','Entrenador','Especialista en fitting','Taller de reparación','Minorista','Otro','Solicitar cambios','Aprobar','Rechazar','Suspender','Reactivar','Marcar vencida','Cerrar','Retirar','Publicar','Impresiones','Interacciones','Intenciones de suscripción','Suscripciones confirmadas por proveedor','Ingresos de Golfriend','Comisiones externas del negocio','Promociones sin ingresos','Razón social','Nombre público del negocio','Referencia de registro','Descripción del servicio','ID de ubicación','Nombre de ubicación','Dirección','Ciudad','Código de país','Horario de atención','Día','Apertura','Cierre','Cerrado','ID de evidencia','Tipo de evidencia','Referencia del objeto de evidencia','Resumen del contenido','ID de promoción','Versión de promoción','Informes operativos','ID de lote JHCC','No disponible'],
fr:['Brouillon','Soumise','Modifications demandées','Approuvée','Active','Suspendue','Expirée','Rejetée','Fermée','Café de golf','Restaurant','Entraîneur','Spécialiste du fitting','Atelier de réparation','Détaillant','Autre','Demander des modifications','Approuver','Rejeter','Suspendre','Réactiver','Faire expirer','Fermer','Retirer','Publier','Impressions','Engagements','Intentions d’abonnement','Abonnements confirmés par le prestataire','Revenus Golfriend','Commissions externes de l’entreprise','Promotions sans revenu','Raison sociale','Nom public de l’entreprise','Référence d’enregistrement','Description du service','ID du site','Nom du site','Adresse','Ville','Code pays','Horaires d’ouverture','Jour','Ouverture','Fermeture','Fermé','ID de preuve','Type de preuve','Référence de l’objet de preuve','Empreinte du contenu','ID de promotion','Version de promotion','Rapports opérationnels','ID de lot JHCC','Indisponible'],
de:['Entwurf','Eingereicht','Änderungen angefordert','Genehmigt','Aktiv','Gesperrt','Abgelaufen','Abgelehnt','Geschlossen','Golfcafé','Restaurant','Trainer','Clubfitter','Reparaturbetrieb','Händler','Sonstiges','Änderungen anfordern','Genehmigen','Ablehnen','Sperren','Reaktivieren','Ablaufen lassen','Schließen','Stilllegen','Veröffentlichen','Impressionen','Interaktionen','Abonnementabsichten','Anbieterbestätigte Abonnements','Golfriend-Umsatz','Externe Geschäftsprovisionen','Umsatzfreie Aktionen','Rechtlicher Unternehmensname','Öffentlicher Unternehmensname','Registrierungsreferenz','Leistungsbeschreibung','Standort-ID','Standortname','Adresse','Stadt','Ländercode','Öffnungszeiten','Tag','Öffnet','Schließt','Geschlossen','Nachweis-ID','Nachweistyp','Nachweisobjekt-Referenz','Inhalts-Digest','Aktions-ID','Aktionsversion','Betriebsbericht','JHCC-Stapel-ID','Nicht verfügbar']};
const weekdays:Record<CanonicalLocale,string[]>={en:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],th:['วันอาทิตย์','วันจันทร์','วันอังคาร','วันพุธ','วันพฤหัสบดี','วันศุกร์','วันเสาร์'],ko:['일요일','월요일','화요일','수요일','목요일','금요일','토요일'],ja:['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],zh:['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],es:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],fr:['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],de:['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag']};
export function smallBusinessLabel(locale:CanonicalLocale,code:string){const i=codes.indexOf(code as typeof codes[number]);return i<0?code:values[locale][i]}
export function smallBusinessWeekday(locale:CanonicalLocale,day:number){return weekdays[locale][day]??String(day)}
export const SMALL_BUSINESS_LABEL_CODES=codes;
