import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {organizationAuthorityService} from "../enterprise/organizationAuthorityService";
import type {EnterpriseAuthorityProjection} from "../enterprise/organizationAuthorityModel";
import {ENTERPRISE_SUPPORT_COPY,ENTERPRISE_SUPPORT_LOCALES,type EnterpriseSupportLocale} from "../../../i18n/partner/enterprisePartnerSupport";
import {newSupportCommandId,partnerSupportService,validSupportProjection,type SupportContext,type SupportProjection,type SupportRequest,type SupportType} from "./enterprisePartnerSupportService";

const TYPES:SupportType[]=["onboarding_help","course_profile_correction","trial_question","member_management_help","tournament_support","booking_coordination","commission_clarification","technical_issue","general_support"];
const buttonStyle={minHeight:48,padding:"10px 16px",borderRadius:6,border:"1px solid #8b7a3f",background:"#171717",color:"#fff",cursor:"pointer"} as const;
const fieldStyle={display:"grid",gap:6,marginBottom:14} as const;
export default function EnterprisePartnerSupport(){
 const initial=(localStorage.getItem("golfriend.locale")||"en") as EnterpriseSupportLocale;
 const [locale,setLocale]=useState<EnterpriseSupportLocale>(ENTERPRISE_SUPPORT_LOCALES.includes(initial)?initial:"en"),copy=ENTERPRISE_SUPPORT_COPY[locale];
 const [authority,setAuthority]=useState<EnterpriseAuthorityProjection|null>(null),[scopeKey,setScopeKey]=useState(""),[projection,setProjection]=useState<SupportProjection|null>(null),[phase,setPhase]=useState<"loading"|"ready"|"offline"|"unavailable">("loading"),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [draft,setDraft]=useState({type:"general_support" as SupportType,subject:"",body:"",email:false,sms:false,push:false}),[reply,setReply]=useState<Record<string,string>>({}),[evidence,setEvidence]=useState<Record<string,{type:"document"|"image"|"log"|"receipt";referenceId:string;label:string}>>({});
 const commands=useRef(new Map<string,string>()),loadSequence=useRef(0);
 const scopes=useMemo(()=>authority?.memberships.flatMap(m=>{if(!authority.actorMembershipIds.includes(m.membershipId)||m.status!=="active"||m.scope.kind!=="course")return[];const scope=m.scope,o=authority.organizations.find(x=>x.organizationId===m.organizationId),property=o?.properties.find(x=>x.propertyId===scope.propertyId),course=property?.courses.find(x=>x.courseId===scope.courseId);return o&&property&&course?[{context:{actorMembershipId:m.membershipId,organizationId:o.organizationId,propertyId:property.propertyId,courseId:course.courseId},label:`${o.displayName} / ${property.displayName} / ${course.displayName}`}]:[]})||[],[authority]);
 const context=scopes.find(s=>JSON.stringify(s.context)===scopeKey)?.context||null;
 const stable=(key:string)=>{let id=commands.current.get(key);if(!id){id=newSupportCommandId();commands.current.set(key,id)}return id};
 const load=useCallback(async(ctx?:SupportContext|null)=>{const sequence=++loadSequence.current;setPhase("loading");setNotice("");try{let selected=ctx;if(!authority){const a=await organizationAuthorityService.load();if(sequence!==loadSequence.current)return;setAuthority(a);const first=a.memberships.find(m=>a.actorMembershipIds.includes(m.membershipId)&&m.status==="active"&&m.scope.kind==="course");if(first?.scope.kind==="course"){selected={actorMembershipId:first.membershipId,organizationId:first.organizationId,propertyId:first.scope.propertyId,courseId:first.scope.courseId};setScopeKey(JSON.stringify(selected))}}if(!selected){setPhase("unavailable");return}const next=await partnerSupportService.read(selected);if(sequence!==loadSequence.current)return;if(!validSupportProjection(next,selected)){setPhase("unavailable");return}setProjection(next);setPhase("ready")}catch{if(sequence===loadSequence.current)setPhase(navigator.onLine?"unavailable":"offline")}},[authority]);
 useEffect(()=>{void load()},[]);// authority bootstrap only
 useEffect(()=>{if(context)void load(context)},[scopeKey]);// exact selected scope refresh
 const run=async(key:string,task:(commandId:string)=>Promise<SupportProjection>)=>{setBusy(true);setNotice("");try{const next=await task(stable(key));if(!context||!validSupportProjection(next,context))throw new Error("projection");setProjection(next);commands.current.delete(key);setNotice(copy.success)}catch{setNotice(navigator.onLine?copy.unavailable:copy.offline)}finally{setBusy(false)}};
 const mutate=(action:"submit"|"withdraw"|"reopen"|"close",r:SupportRequest)=>void run(`${action}:${r.requestId}`,id=>partnerSupportService[action](context!,{commandId:id,requestId:r.requestId,expectedVersion:r.version}));
 if(phase==="loading")return <section aria-labelledby="support-title"><h2 id="support-title">{copy.title}</h2><p role="status" aria-live="polite">{copy.loading}</p></section>;
 if(phase!=="ready"||!context)return <section aria-labelledby="support-title"><h2 id="support-title">{copy.title}</h2><p role="alert">{phase==="offline"?copy.offline:copy.unavailable}</p><button style={buttonStyle} onClick={()=>void load(context)}>{copy.retry}</button></section>;
 const readOnly=projection?.state==="suspended";
 return <section aria-labelledby="support-title" style={{maxWidth:1000,margin:"0 auto",padding:24,color:"#fff"}}><header><h2 id="support-title">{copy.title}</h2><p>{copy.intro}</p><label style={fieldStyle}>{copy.language}<select aria-label={copy.language} value={locale} onChange={e=>{const value=e.target.value as EnterpriseSupportLocale;setLocale(value);localStorage.setItem("golfriend.locale",value)}}>{ENTERPRISE_SUPPORT_LOCALES.map(x=><option key={x}>{x}</option>)}</select></label><label style={fieldStyle}>{copy.scope}<select aria-label={copy.scope} value={scopeKey} onChange={e=>setScopeKey(e.target.value)}><option value="">{copy.selectScope}</option>{scopes.map(s=><option key={JSON.stringify(s.context)} value={JSON.stringify(s.context)}>{s.label}</option>)}</select></label></header>
 <p role="status">{readOnly?copy.suspended:copy.adminBoundary}</p>
 <form aria-label={copy.newRequest} onSubmit={e=>{e.preventDefault();void run("create",id=>partnerSupportService.create(context,{commandId:id,type:draft.type,subject:draft.subject.trim(),body:draft.body.trim(),locale,notificationPreferences:{locale,email:draft.email,sms:draft.sms,push:draft.push}}))}}><fieldset disabled={busy||readOnly}><legend>{copy.newRequest}</legend><label style={fieldStyle}>{copy.type}<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as SupportType})}>{TYPES.map(type=><option key={type} value={type}>{copy.requestTypes[type]}</option>)}</select></label><label style={fieldStyle}>{copy.subject}<input required maxLength={160} value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></label><label style={fieldStyle}>{copy.details}<textarea required maxLength={4000} rows={5} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><fieldset><legend>{copy.preferences}</legend><p>{copy.preferenceNotice}</p>{(["email","sms","push"] as const).map(k=><label key={k} style={{marginRight:18}}><input type="checkbox" checked={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.checked})}/>{copy[k]}</label>)}</fieldset><button style={buttonStyle} disabled={!draft.subject.trim()||!draft.body.trim()}>{copy.saveDraft}</button></fieldset></form>
 <section aria-labelledby="support-requests"><h3 id="support-requests">{copy.requests}</h3>{!projection?.requests.length?<p>{copy.empty}</p>:projection.requests.map(r=><article key={r.requestId} aria-labelledby={`request-${r.requestId}`} style={{border:"1px solid #444",borderRadius:8,padding:16,marginBottom:16}}><h4 id={`request-${r.requestId}`}>{r.subject}</h4><p><strong>{copy.status}:</strong> {copy.statuses[r.status]} · v{r.version}</p><p>{copy.requestTypes[r.type]} · {r.applicationState} · {r.trialState??copy.notAvailable}</p><ol aria-label={copy.receipt}>{r.messages.map(m=><li key={m.messageId}><strong>{m.author==="admin"?copy.admin:copy.representative}</strong>: {m.body}</li>)}</ol><ul>{r.receipts.map(x=><li key={x.receiptId}><code>{x.receiptId}</code> · {x.action} · <time dateTime={x.occurredAt}>{x.occurredAt}</time></li>)}</ul>
 {r.status==="draft"&&<button style={buttonStyle} disabled={busy||readOnly} onClick={()=>mutate("submit",r)}>{copy.submit}</button>}{["submitted","acknowledged","needs_information","under_review"].includes(r.status)&&<button style={buttonStyle} disabled={busy||readOnly} onClick={()=>{if(window.confirm(copy.withdraw))mutate("withdraw",r)}}>{copy.withdraw}</button>}{["resolved","closed"].includes(r.status)&&<button style={buttonStyle} disabled={busy||readOnly} onClick={()=>mutate("reopen",r)}>{copy.reopen}</button>}{r.status==="resolved"&&<button style={buttonStyle} disabled={busy||readOnly} onClick={()=>{if(window.confirm(copy.close))mutate("close",r)}}>{copy.close}</button>}
 {r.status==="needs_information"&&<form onSubmit={e=>{e.preventDefault();void run(`reply:${r.requestId}`,id=>partnerSupportService.reply(context,{commandId:id,requestId:r.requestId,expectedVersion:r.version,body:(reply[r.requestId]||"").trim()}))}}><label style={fieldStyle}>{copy.reply}<textarea maxLength={2000} required value={reply[r.requestId]||""} onChange={e=>setReply({...reply,[r.requestId]:e.target.value})}/></label><button style={buttonStyle} disabled={busy||readOnly||!(reply[r.requestId]||"").trim()}>{copy.reply}</button></form>}
 {r.status==="draft"&&<form onSubmit={e=>{e.preventDefault();const item=evidence[r.requestId]||{type:"document" as const,referenceId:"",label:""};void run(`evidence:${r.requestId}`,id=>partnerSupportService.attach(context,{commandId:id,requestId:r.requestId,expectedVersion:r.version,evidence:item}))}}><fieldset disabled={busy||readOnly}><legend>{copy.attach}</legend><label>{copy.evidenceType}<select value={evidence[r.requestId]?.type||"document"} onChange={e=>setEvidence({...evidence,[r.requestId]:{...(evidence[r.requestId]||{referenceId:"",label:""}),type:e.target.value as "document"|"image"|"log"|"receipt"}})}>{(["document","image","log","receipt"] as const).map(x=><option key={x} value={x}>{copy.evidenceTypes[x]}</option>)}</select></label><label>{copy.referenceId}<input required maxLength={180} value={evidence[r.requestId]?.referenceId||""} onChange={e=>setEvidence({...evidence,[r.requestId]:{...(evidence[r.requestId]||{type:"document",label:""}),referenceId:e.target.value}})}/></label><label>{copy.label}<input required maxLength={120} value={evidence[r.requestId]?.label||""} onChange={e=>setEvidence({...evidence,[r.requestId]:{...(evidence[r.requestId]||{type:"document",referenceId:""}),label:e.target.value}})}/></label><button style={buttonStyle}>{copy.attach}</button></fieldset></form>}</article>)}</section>{notice&&<p role={notice===copy.success?"status":"alert"} aria-live={notice===copy.success?"polite":"assertive"}>{notice}</p>}</section>;
}
