import { functions } from '../../../firebaseConfig';
import {httpsCallable} from "firebase/functions";
export const ENTERPRISE_SUPPORT_SCHEMA="golfriend.enterprise-partner-support.v1" as const;
export type SupportType="onboarding_help"|"course_profile_correction"|"trial_question"|"member_management_help"|"tournament_support"|"booking_coordination"|"commission_clarification"|"technical_issue"|"general_support";
export type SupportStatus="draft"|"submitted"|"acknowledged"|"needs_information"|"under_review"|"resolved"|"closed"|"withdrawn";
export interface SupportContext{actorMembershipId:string;organizationId:string;propertyId:string;courseId:string}
export interface SupportRequest{requestId:string;scope:SupportContext&{applicationId:string|null};type:SupportType;subject:string;status:SupportStatus;version:number;locale:string;applicationState:string;trialState:string|null;createdAt:string;updatedAt:string;messages:{messageId:string;author:"representative"|"admin";body:string;createdAt:string;receiptId?:string}[];evidence:{type:"document"|"image"|"log"|"receipt";referenceId:string;label:string}[];receipts:{receiptId:string;action:string;occurredAt:string;immutable:true}[];notificationPreferences:{locale:string;email:boolean;sms:boolean;push:boolean}}
export interface SupportProjection{schema:typeof ENTERPRISE_SUPPORT_SCHEMA;context:SupportContext;state:"current"|"empty"|"unavailable"|"suspended";adminCommandStatus:"unavailable";requests:SupportRequest[];replayed?:boolean}
const call=async(name:string,payload:Record<string,unknown>)=>(await httpsCallable(functions,name)(payload)).data as SupportProjection;
export const newSupportCommandId=()=>crypto.randomUUID().replaceAll("-","_");
export const partnerSupportService={read:(context:SupportContext)=>call("getEnterprisePartnerSupportV1",{context}),create:(context:SupportContext,command:Record<string,unknown>)=>call("createEnterpriseSupportDraftV1",{context,...command}),attach:(context:SupportContext,command:Record<string,unknown>)=>call("attachEnterpriseSupportEvidenceV1",{context,...command}),submit:(context:SupportContext,command:Record<string,unknown>)=>call("submitEnterpriseSupportRequestV1",{context,...command}),reply:(context:SupportContext,command:Record<string,unknown>)=>call("replyEnterpriseSupportRequestV1",{context,...command}),withdraw:(context:SupportContext,command:Record<string,unknown>)=>call("withdrawEnterpriseSupportRequestV1",{context,...command}),reopen:(context:SupportContext,command:Record<string,unknown>)=>call("reopenEnterpriseSupportRequestV1",{context,...command}),close:(context:SupportContext,command:Record<string,unknown>)=>call("closeEnterpriseSupportRequestV1",{context,...command})};
const STATUSES=new Set(["draft","submitted","acknowledged","needs_information","under_review","resolved","closed","withdrawn"]),TYPES=new Set(["onboarding_help","course_profile_correction","trial_question","member_management_help","tournament_support","booking_coordination","commission_clarification","technical_issue","general_support"]),LOCALES=new Set(["en","th","ko","ja","zh","es","fr","de"]),STATES=new Set(["current","empty","unavailable","suspended"]),EVIDENCE=new Set(["document","image","log","receipt"]);
const bounded=(v:unknown,n:number)=>typeof v==="string"&&v.length>0&&v.length<=n;
const sameScope=(a:SupportContext|undefined,b:SupportContext)=>!!a&&a.actorMembershipId===b.actorMembershipId&&a.organizationId===b.organizationId&&a.propertyId===b.propertyId&&a.courseId===b.courseId;
export function validSupportProjection(value:unknown,context:SupportContext):value is SupportProjection{
 if(!value||typeof value!=="object")return false;const p=value as SupportProjection;
 return p.schema===ENTERPRISE_SUPPORT_SCHEMA&&sameScope(p.context,context)&&STATES.has(p.state)&&p.adminCommandStatus==="unavailable"&&Array.isArray(p.requests)&&p.requests.every(r=>sameScope(r.scope,context)&&(r.scope.applicationId===null||bounded(r.scope.applicationId,180))&&bounded(r.requestId,180)&&TYPES.has(r.type)&&bounded(r.subject,160)&&STATUSES.has(r.status)&&Number.isInteger(r.version)&&r.version>0&&LOCALES.has(r.locale)&&bounded(r.applicationState,80)&&(r.trialState===null||bounded(r.trialState,80))&&!Number.isNaN(Date.parse(r.createdAt))&&!Number.isNaN(Date.parse(r.updatedAt))&&Array.isArray(r.messages)&&r.messages.every(m=>bounded(m.messageId,180)&&(m.author==="representative"||m.author==="admin")&&bounded(m.body,4000)&&!Number.isNaN(Date.parse(m.createdAt))&&(m.receiptId===undefined||bounded(m.receiptId,180)))&&Array.isArray(r.evidence)&&r.evidence.every(e=>EVIDENCE.has(e.type)&&bounded(e.referenceId,180)&&bounded(e.label,120))&&Array.isArray(r.receipts)&&r.receipts.every(x=>bounded(x.receiptId,180)&&bounded(x.action,80)&&!Number.isNaN(Date.parse(x.occurredAt))&&x.immutable===true)&&!!r.notificationPreferences&&LOCALES.has(r.notificationPreferences.locale)&&typeof r.notificationPreferences.email==="boolean"&&typeof r.notificationPreferences.sms==="boolean"&&typeof r.notificationPreferences.push==="boolean");
}
