import { useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../../../firebaseConfig';
import { useAdminLocale } from './AdminLocaleContext';

type Copy = { title:string; lead:string; search:string; searchHint:string; find:string; loading:string; unavailable:string; director:string; activation:string; profile:string; rounds:string; membership:string; moderation:string; moderationUnavailable:string; ledger:string; lots:string; journal:string; balance:string; openModeration:string; none:string; };
const copy: Record<string, Copy> = {
  en:{title:'Member & Tee ledger',lead:'Director-only, server-projected member support view.',search:'Member lookup',searchHint:'Email, E.164 phone, UID, or exact nickname',find:'Find member',loading:'Loading authoritative member data…',unavailable:'Member data is unavailable. Nothing was changed.',director:'Director access is required.',activation:'Activation checks',profile:'Profile',rounds:'Rounds',membership:'Membership',moderation:'Moderation history',moderationUnavailable:'Moderation audit history is not available until its canonical reader is merged.',ledger:'Canonical Tee ledger',lots:'Lots',journal:'Journal timeline',balance:'Available balance by provenance',openModeration:'Open Moderation',none:'No canonical Tee activity.'},
  th:{title:'สมาชิกและบัญชี Tee',lead:'มุมมองช่วยเหลือสมาชิกจากเซิร์ฟเวอร์สำหรับผู้อำนวยการเท่านั้น',search:'ค้นหาสมาชิก',searchHint:'อีเมล โทรศัพท์ E.164 UID หรือชื่อเล่นตรงกัน',find:'ค้นหาสมาชิก',loading:'กำลังโหลดข้อมูลสมาชิกจากแหล่งอ้างอิง…',unavailable:'ไม่สามารถใช้ข้อมูลสมาชิกได้ และไม่มีการเปลี่ยนแปลงข้อมูล',director:'ต้องมีสิทธิ์ผู้อำนวยการ',activation:'การตรวจสอบการเปิดใช้งาน',profile:'โปรไฟล์',rounds:'รอบเล่น',membership:'สมาชิกภาพ',moderation:'ประวัติการดูแล',moderationUnavailable:'ประวัติการดูแลจะใช้ได้เมื่อรวมตัวอ่านข้อมูลมาตรฐานแล้ว',ledger:'บัญชี Tee มาตรฐาน',lots:'ล็อต',journal:'ไทม์ไลน์สมุดรายวัน',balance:'ยอดคงเหลือตามที่มา',openModeration:'เปิดการดูแล',none:'ไม่มีกิจกรรม Tee มาตรฐาน'},
  ko:{title:'회원 및 Tee 원장',lead:'디렉터 전용 서버 투영 회원 지원 화면입니다.',search:'회원 조회',searchHint:'이메일, E.164 전화, UID 또는 정확한 닉네임',find:'회원 찾기',loading:'권한 있는 회원 데이터를 불러오는 중…',unavailable:'회원 데이터를 사용할 수 없습니다. 변경된 내용은 없습니다.',director:'디렉터 권한이 필요합니다.',activation:'활성화 확인',profile:'프로필',rounds:'라운드',membership:'멤버십',moderation:'관리 이력',moderationUnavailable:'표준 감사 리더가 병합되면 관리 이력을 사용할 수 있습니다.',ledger:'표준 Tee 원장',lots:'로트',journal:'분개 타임라인',balance:'출처별 사용 가능 잔액',openModeration:'관리 열기',none:'표준 Tee 활동이 없습니다.'},
  ja:{title:'会員とTee台帳',lead:'ディレクター専用のサーバー投影会員サポート画面です。',search:'会員検索',searchHint:'メール、E.164電話、UID、または完全一致のニックネーム',find:'会員を検索',loading:'権限のある会員データを読み込み中…',unavailable:'会員データを利用できません。変更はありません。',director:'ディレクター権限が必要です。',activation:'有効化確認',profile:'プロフィール',rounds:'ラウンド',membership:'会員資格',moderation:'モデレーション履歴',moderationUnavailable:'正規の監査リーダーが統合されるまで履歴は利用できません。',ledger:'正規Tee台帳',lots:'ロット',journal:'仕訳タイムライン',balance:'出所別利用可能残高',openModeration:'モデレーションを開く',none:'正規のTee活動はありません。'},
  zh:{title:'会员与 Tee 台账',lead:'仅限总监的服务器投影会员支持视图。',search:'查找会员',searchHint:'电子邮件、E.164 电话、UID 或精确昵称',find:'查找会员',loading:'正在加载权威会员数据…',unavailable:'会员数据不可用，未作任何更改。',director:'需要总监权限。',activation:'激活检查',profile:'档案',rounds:'轮次',membership:'会员资格',moderation:'审核历史',moderationUnavailable:'待合并规范审核读取器后方可查看审核历史。',ledger:'规范 Tee 台账',lots:'批次',journal:'日记账时间线',balance:'按来源的可用余额',openModeration:'打开审核',none:'没有规范 Tee 活动。'},
  es:{title:'Miembro y libro Tee',lead:'Vista de soporte de miembros proyectada por servidor, solo para Dirección.',search:'Buscar miembro',searchHint:'Correo, teléfono E.164, UID o apodo exacto',find:'Buscar',loading:'Cargando datos autorizados del miembro…',unavailable:'Los datos no están disponibles. No se cambió nada.',director:'Se requiere acceso de Dirección.',activation:'Comprobaciones de activación',profile:'Perfil',rounds:'Rondas',membership:'Membresía',moderation:'Historial de moderación',moderationUnavailable:'El historial estará disponible cuando se fusione su lector canónico.',ledger:'Libro Tee canónico',lots:'Lotes',journal:'Cronología del diario',balance:'Saldo disponible por procedencia',openModeration:'Abrir moderación',none:'No hay actividad Tee canónica.'},
  fr:{title:'Membre et grand livre Tee',lead:'Vue d’assistance membre projetée par le serveur, réservée aux directeurs.',search:'Rechercher un membre',searchHint:'E-mail, téléphone E.164, UID ou pseudo exact',find:'Rechercher',loading:'Chargement des données membre faisant autorité…',unavailable:'Les données sont indisponibles. Rien n’a été modifié.',director:'Accès Directeur requis.',activation:'Contrôles d’activation',profile:'Profil',rounds:'Parties',membership:'Adhésion',moderation:'Historique de modération',moderationUnavailable:'Disponible après l’intégration du lecteur d’audit canonique.',ledger:'Grand livre Tee canonique',lots:'Lots',journal:'Chronologie du journal',balance:'Solde disponible par provenance',openModeration:'Ouvrir la modération',none:'Aucune activité Tee canonique.'},
  de:{title:'Mitglied & Tee-Kontobuch',lead:'Server-projizierte Mitgliederansicht nur für Direktoren.',search:'Mitglied suchen',searchHint:'E-Mail, E.164-Telefon, UID oder exakter Spitzname',find:'Mitglied suchen',loading:'Autorisierte Mitgliedsdaten werden geladen…',unavailable:'Mitgliedsdaten nicht verfügbar. Nichts wurde geändert.',director:'Direktorzugriff erforderlich.',activation:'Aktivierungsprüfungen',profile:'Profil',rounds:'Runden',membership:'Mitgliedschaft',moderation:'Moderationsverlauf',moderationUnavailable:'Verfügbar, sobald der kanonische Audit-Leser zusammengeführt ist.',ledger:'Kanonisches Tee-Kontobuch',lots:'Lose',journal:'Journal-Zeitleiste',balance:'Verfügbares Guthaben nach Herkunft',openModeration:'Moderation öffnen',none:'Keine kanonische Tee-Aktivität.'},
};
type Member = { memberId:string; email:string|null; phone:string|null; nickname:string|null; accountState:string|null; activation:Record<string, unknown>; profile:Record<string, unknown> };
type Lookup = { member:Member; roundsCount:number; membership:Record<string,unknown>; moderationHistory:{state:string} };
type Ledger = { lots:Array<Record<string,unknown>>; journal:Array<Record<string,unknown>>; balanceByProvenance:Record<string,number>; truncated?:boolean };
const render = (value: unknown) => value === null || value === undefined || value === '' ? '—' : String(value);
const tees = (atoms: unknown) => Number.isFinite(atoms) ? `${Number(atoms) / 1_000_000} Tees` : '—';
const errorMessage = (code: unknown) => code === 'permission-denied' ? 'Director access was refused.' : code === 'not-found' ? 'Member not found.' : 'Authoritative member data is unavailable. Nothing was changed.';

export default function AdminMemberLedger({isDirector,onOpenModeration}:{isDirector:boolean;onOpenModeration:()=>void}) {
  const locale=useAdminLocale(), t=copy[locale]||copy.en;
  const [query,setQuery]=useState(''),[lookup,setLookup]=useState<Lookup|null>(null),[ledger,setLedger]=useState<Ledger|null>(null),[state,setState]=useState<'idle'|'loading'|'error'>('idle'),[failure,setFailure]=useState(t.unavailable);
  const find=async()=>{if(!query.trim())return;setState('loading');try{const value=(await httpsCallable<{query:string},Lookup>(functions,'v2AdminMemberLookup')({query:query.trim()})).data;setLookup(value);setLedger((await httpsCallable<{memberId:string},Ledger>(functions,'v2AdminMemberLedger')({memberId:value.member.memberId})).data);setState('idle')}catch(error:any){setLookup(null);setLedger(null);setFailure(errorMessage(error?.code));setState('error')}};
  if(!isDirector)return <section className="v2-admin-panel" role="alert"><h2>{t.title}</h2><p>{t.director}</p></section>;
  return <section className="v2-admin-panel" aria-labelledby="admin-member-ledger-title"><h2 id="admin-member-ledger-title">{t.title}</h2><p>{t.lead}</p><form onSubmit={event=>{event.preventDefault();void find()}}><label>{t.search}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.searchHint}/></label><button type="submit" disabled={state==='loading'}>{t.find}</button></form>{state==='loading'&&<p role="status">{t.loading}</p>}{state==='error'&&<p role="alert">{failure}</p>}{lookup&&<><h3>{t.profile}</h3><dl><div><dt>UID</dt><dd>{lookup.member.memberId}</dd></div><div><dt>Email</dt><dd>{render(lookup.member.email)}</dd></div><div><dt>Phone</dt><dd>{render(lookup.member.phone)}</dd></div><div><dt>Nickname</dt><dd>{render(lookup.member.nickname)}</dd></div><div><dt>Account state</dt><dd>{render(lookup.member.accountState)}</dd></div><div><dt>{t.rounds}</dt><dd>{lookup.roundsCount}</dd></div></dl><h3>{t.activation}</h3><dl>{Object.entries(lookup.member.activation).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{render(value)}</dd></div>)}</dl><h3>{t.membership}</h3><dl>{Object.entries(lookup.membership).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{render(value)}</dd></div>)}</dl><h3>{t.moderation}</h3><p>{lookup.moderationHistory.state==='unavailable'&&t.moderationUnavailable}</p><button type="button" onClick={onOpenModeration}>{t.openModeration}</button>{ledger&&<><h3>{t.ledger}</h3>{ledger.truncated&&<p role="status">List truncated. Load more is not available until the server supplies a cursor.</p>}<h4>{t.balance}</h4><dl>{Object.entries(ledger.balanceByProvenance).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{tees(value)}</dd></div>)}</dl><h4>{t.lots}</h4>{ledger.lots.length?<ul>{ledger.lots.map((row,index)=><li key={String(row.lotId||index)}>{render(row.lotId)} · {render(row.liabilityClass)} · {tees(row.availableTeeAtoms)}</li>)}</ul>:<p>{t.none}</p>}<h4>{t.journal}</h4>{ledger.journal.length?<ol>{ledger.journal.slice().sort((a,b)=>String(b.occurredAt||'').localeCompare(String(a.occurredAt||''))).map((row,index)=><li key={String(row.entryId||index)}>{render(row.occurredAt)} · {render(row.actionId)} · {tees(row.amountTeeAtoms)} · provenance: {render(row.liabilityClass)}</li>)}</ol>:<p>{t.none}</p>}</>}</>}</section>;
}
