const text=(value,max=512)=>typeof value==='string'&&value.length<=max?value.trim():'';
const number=value=>typeof value==='number'&&Number.isFinite(value)?value:null;
const bool=value=>typeof value==='boolean'?value:null;
const row=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const validId=value=>/^[A-Za-z0-9_-]{1,160}$/.test(value);
const curated=value=>{const item=row(value);return {clubHouseId:text(item.clubHouseId,160),clubHouseName:text(item.clubHouseName),identityProvenance:text(item.identityProvenance,80),coordinateVerified:item.coordinateVerified===true,coordinateProvenance:text(item.coordinateProvenance,160),latitude:number(item.latitude),longitude:number(item.longitude),providerClubId:text(item.providerClubId,160)||null,providerRelationship:item.providerRelationship===null?null:text(item.providerRelationship,32),providerSupplied:item.providerSupplied===false?false:null,propertyHoleCount:number(item.propertyHoleCount),roundHoleCount:number(item.roundHoleCount)};};
export const SIAM_CURATED_AUTHORITIES=Object.freeze([
  {clubHouseId:'siam-country-club-old-course',clubHouseName:'Siam Country Club Old Course',identityProvenance:'golfriend_founder_ruling',coordinateVerified:true,coordinateProvenance:'venue_official_map_link',latitude:12.9179814,longitude:100.9877539,providerClubId:'141519520199806521',providerRelationship:'unresolved',providerSupplied:false,propertyHoleCount:18,roundHoleCount:18},
  {clubHouseId:'siam-country-club-plantation',clubHouseName:'Siam Country Club Plantation',identityProvenance:'golfriend_founder_ruling',coordinateVerified:true,coordinateProvenance:'venue_official_map_link',latitude:12.9093302,longitude:101.0085683,providerClubId:'141519520199806521',providerRelationship:'unresolved',providerSupplied:false,propertyHoleCount:27,roundHoleCount:18},
  {clubHouseId:'siam-country-club-waterside',clubHouseName:'Siam Country Club Waterside',identityProvenance:'golfriend_founder_ruling',coordinateVerified:true,coordinateProvenance:'venue_official_map_link',latitude:12.9140585,longitude:100.9971897,providerClubId:'141519520199806521',providerRelationship:'unresolved',providerSupplied:false,propertyHoleCount:18,roundHoleCount:18},
  {clubHouseId:'siam-country-club-rolling-hills',clubHouseName:'Siam Country Club Rolling Hills',identityProvenance:'golfriend_founder_ruling',coordinateVerified:true,coordinateProvenance:'venue_official_map_link',latitude:12.8954185,longitude:100.9815867,providerClubId:'141519520199806521',providerRelationship:'unresolved',providerSupplied:false,propertyHoleCount:18,roundHoleCount:18},
]);
export function parseOperatorInput(providerIdsText,curatedText){const providerClubIds=[...new Set(String(providerIdsText||'').split(/[\s,]+/).map(value=>value.trim()).filter(Boolean))];if(providerClubIds.length>25||providerClubIds.some(value=>!validId(value)))throw new Error('Enter at most 25 valid provider club IDs.');let raw=[];if(String(curatedText||'').trim())try{raw=JSON.parse(curatedText);}catch{throw new Error('Curated authority JSON is invalid.');}if(!Array.isArray(raw)||raw.length>25)throw new Error('Curated authority set must contain at most 25 rows.');const curatedAuthorities=raw.map(curated);if(curatedAuthorities.some(item=>!validId(item.clubHouseId)||!item.clubHouseName||!['golfriend_founder_ruling','golfriend_operational_verification'].includes(item.identityProvenance)||item.coordinateVerified!==true||!item.coordinateProvenance||item.latitude===null||item.longitude===null||item.latitude<-90||item.latitude>90||item.longitude<-180||item.longitude>180||item.providerSupplied!==false||!['unresolved',null].includes(item.providerRelationship)||!Number.isInteger(item.propertyHoleCount)||item.propertyHoleCount<1||item.roundHoleCount!==18))throw new Error('Every curated authority needs explicit provenance, verified coordinates, and property/round-hole facts.');if(new Set(curatedAuthorities.map(item=>item.clubHouseId)).size!==curatedAuthorities.length)throw new Error('Curated clubhouse IDs must be unique.');if(providerClubIds.length===0&&curatedAuthorities.length===0)throw new Error('Supply provider club IDs, curated authorities, or both.');return {providerClubIds,curatedAuthorities};}
const clubhouses=value=>(Array.isArray(value)?value:[]).map(item=>{const source=row(item),patch=row(source.patch),location=row(patch.location);return {clubHouseId:text(source.id,160),clubHouseName:text(patch.displayName),latitude:number(location.latitude),longitude:number(location.longitude),identityProvenance:text(patch.identityProvenance,80),coordinateProvenance:text(patch.coordinateProvenance,160),coordinateVerified:patch.coordinateVerified===true,providerClubId:text(patch.providerClubId,160),providerRelationship:text(patch.providerRelationship,32),providerSupplied:bool(patch.providerSupplied),propertyHoleCount:number(patch.propertyHoleCount),roundHoleCount:number(patch.roundHoleCount)};}).filter(item=>item.clubHouseId&&item.clubHouseName);
const layouts=value=>(Array.isArray(value)?value:[]).map(item=>{const source=row(item),patch=row(source.patch);return {courseId:text(source.id,160),providerCourseId:text(patch.providerCourseId,160),providerClubId:text(patch.providerClubId,160),clubHouseId:text(patch.clubhouseId,160),courseName:text(patch.name)};}).filter(item=>item.courseId||item.providerCourseId);
export function normalizeReconciliationPreview(value){const source=row(value),summary=row(source.summary);return {planHash:text(source.planHash,64),sourceStateHash:text(source.sourceStateHash,64),clubhouses:clubhouses(source.clubhouseUpserts),linkedLayouts:layouts(source.coursePatches),unmatchedLayouts:(Array.isArray(source.unmatchedProviderLayouts)?source.unmatchedProviderLayouts:[]).map(item=>{const x=row(item);return {providerClubId:text(x.providerClubId,160),providerCourseId:text(x.providerCourseId,160)};}).filter(item=>item.providerClubId||item.providerCourseId),ambiguities:(Array.isArray(source.unresolvedProviderClubhouses)?source.unresolvedProviderClubhouses:[]).map(item=>{const x=row(item);return {providerClubId:text(x.providerClubId,160),reason:text(x.reason,160)};}).filter(item=>item.providerClubId),providerFacts:(Array.isArray(source.providerFacts)?source.providerFacts:[]).map(item=>{const x=row(item);return {providerClubId:text(x.providerClubId,160),fetchedAtMs:number(x.fetchedAtMs),cacheHit:bool(x.cacheHit),freshAtPreview:bool(x.freshAtPreview)};}).filter(item=>item.providerClubId),summary:{providerCallsUsed:number(summary.providerCallsUsed),providerCallsSavedByTtl:number(summary.providerCallsSavedByTtl),sourceReadAtMs:number(summary.sourceReadAtMs),productionWrites:number(summary.productionWrites)}};}
export function normalizeExecutionReceipt(value){const source=row(value),receipt=row(source.receipt),result=row(source.result);return {receiptId:text(source.receiptId,160)||text(receipt.receiptId,160),replayed:source.replayed===true,approvedBy:text(receipt.approvedBy,256),createdBy:text(receipt.createdBy,256),createdAtMs:number(receipt.createdAtMs),writes:number(result.writes),deletes:number(result.deletes),clubhouseUpserts:number(result.clubhouseUpserts),coursePatches:number(result.coursePatches)};}
