// Localized outreach drafts + privacy-safe opportunity evidence for UNSIGNED courses.
// Pure model: no I/O, no network, no transport. Drafts are generated, never delivered.
//
// Invariants:
//   - An opportunity report carries evidence, never an invoice or a price.
//   - A booking, played round or revenue figure is never claimed without authoritative attribution.
//   - No member identity, internal note or precise personal movement may appear in a draft or report.
//   - Aggregates below MIN_AGGREGATE_COUNT are suppressed rather than rounded or estimated.
import{discloseMetric,invoiceEligibility,MIN_AGGREGATE_COUNT,normalizeProspect,shareableProspect}from'./courseAcquisitionModel.mjs';

export const OPPORTUNITY_SCHEMA='golfriend.admin.course-opportunity-evidence.v1';
export const OPPORTUNITY_VERSION=1;
export const OUTREACH_TEMPLATE_KINDS=Object.freeze(['invitation','follow_up','opportunity_summary','pilot_proposal','meeting_recap']);
/** Interest signals may be shared when aggregated; transaction claims require authoritative attribution. */
export const INTEREST_METRICS=Object.freeze(['search_interest','saved_course','booking_interest']);
export const TRANSACTION_METRICS=Object.freeze(['confirmed_bookings','played_rounds']);
export const DELIVERY_NOTICE='Draft only. Nothing has been transmitted and no delivery channel is available.';

// Eight-locale outreach copy. The locale set itself is owned by `src/i18n/locales.ts`;
// these are the per-locale entries, verified against the canonical set by the gate.
export const OUTREACH_COPY=Object.freeze({
en:{disclaimer:'Golfriend provides booking assistance only. It does not sell tee times, does not process payments, and does not guarantee bookings, revenue or exclusivity.',evidenceHeading:'Recorded golfer interest',suppressed:'Withheld — below the minimum aggregate for safe reporting.',notAttributed:'Not claimed — no authoritative source.',invitation:{subject:'An invitation to join the Golfriend team',body:'Dear {contactRole} at {courseName}, Golfriend helps golfers in {country} discover and reach courses like yours. We would like to introduce how Golfriend can support {courseName} with booking assistance.'},follow_up:{subject:'Following up on our Golfriend introduction',body:'Dear {contactRole} at {courseName}, we wrote recently about Golfriend and wanted to ask whether it would help if we shared the interest recorded for {courseName}.'},opportunity_summary:{subject:'Golfriend interest summary for {courseName}',body:'Dear {contactRole} at {courseName}, this is the golfer-interest evidence Golfriend recorded for {period}. The figures are aggregated and contain no personal data.'},pilot_proposal:{subject:'A Golfriend pilot for {courseName}',body:'Dear {contactRole} at {courseName}, we would like to propose a pilot. A pilot begins only after verified activation, and any commission applies only from the effective date of a signed agreement.'},meeting_recap:{subject:'Summary of our meeting about Golfriend',body:'Dear {contactRole} at {courseName}, thank you for meeting us. This note records what we discussed; nothing is agreed until a signed agreement is in place.'}},
th:{disclaimer:'Golfriend ให้บริการช่วยเหลือด้านการจองเท่านั้น ไม่ได้ขายเวลาออกรอบ ไม่ได้ประมวลผลการชำระเงิน และไม่รับประกันการจอง รายได้ หรือสิทธิ์พิเศษเฉพาะราย',evidenceHeading:'ความสนใจของนักกอล์ฟที่บันทึกไว้',suppressed:'ไม่เปิดเผย — ต่ำกว่าเกณฑ์ขั้นต่ำของการรายงานแบบปลอดภัย',notAttributed:'ไม่กล่าวอ้าง — ไม่มีแหล่งข้อมูลที่เชื่อถือได้',invitation:{subject:'คำเชิญเข้าร่วมทีม Golfriend',body:'เรียน {contactRole} แห่ง {courseName} Golfriend ช่วยให้นักกอล์ฟใน {country} ค้นพบและติดต่อสนามอย่างสนามของท่าน เราอยากแนะนำว่า Golfriend สามารถสนับสนุน {courseName} ด้านการช่วยเหลือการจองได้อย่างไร'},follow_up:{subject:'ติดตามผลจากการแนะนำ Golfriend',body:'เรียน {contactRole} แห่ง {courseName} เราได้ติดต่อไปก่อนหน้านี้เกี่ยวกับ Golfriend และอยากทราบว่าจะเป็นประโยชน์หรือไม่หากเราแบ่งปันข้อมูลความสนใจที่บันทึกไว้สำหรับ {courseName}'},opportunity_summary:{subject:'สรุปความสนใจจาก Golfriend สำหรับ {courseName}',body:'เรียน {contactRole} แห่ง {courseName} นี่คือหลักฐานความสนใจของนักกอล์ฟที่ Golfriend บันทึกไว้สำหรับช่วง {period} ตัวเลขเป็นข้อมูลรวมและไม่มีข้อมูลส่วนบุคคล'},pilot_proposal:{subject:'ข้อเสนอโครงการนำร่อง Golfriend สำหรับ {courseName}',body:'เรียน {contactRole} แห่ง {courseName} เราขอเสนอโครงการนำร่อง โครงการจะเริ่มต่อเมื่อมีการยืนยันการเปิดใช้งานแล้วเท่านั้น และค่าคอมมิชชันจะมีผลนับจากวันที่มีผลของข้อตกลงที่ลงนามแล้วเท่านั้น'},meeting_recap:{subject:'สรุปการประชุมเกี่ยวกับ Golfriend',body:'เรียน {contactRole} แห่ง {courseName} ขอบคุณที่ให้เวลาพบเรา บันทึกนี้สรุปสิ่งที่หารือกัน ยังไม่มีข้อตกลงใดจนกว่าจะมีข้อตกลงที่ลงนามแล้ว'}},
ko:{disclaimer:'Golfriend는 예약 지원만 제공합니다. 티타임을 판매하지 않으며 결제를 처리하지 않고 예약, 수익 또는 독점권을 보장하지 않습니다.',evidenceHeading:'기록된 골퍼 관심도',suppressed:'비공개 — 안전한 보고를 위한 최소 집계 기준 미만입니다.',notAttributed:'주장하지 않음 — 신뢰할 수 있는 출처가 없습니다.',invitation:{subject:'Golfriend 팀에 참여하시라는 초대',body:'{courseName}의 {contactRole}께, Golfriend는 {country}의 골퍼들이 귀하의 골프장과 같은 코스를 발견하고 연결되도록 돕습니다. Golfriend가 {courseName}의 예약 지원을 어떻게 도울 수 있는지 소개드리고자 합니다.'},follow_up:{subject:'Golfriend 소개에 대한 후속 연락',body:'{courseName}의 {contactRole}께, 최근 Golfriend에 대해 연락드렸습니다. {courseName}에 대해 기록된 관심 정보를 공유해 드리는 것이 도움이 될지 여쭙고자 합니다.'},opportunity_summary:{subject:'{courseName}에 대한 Golfriend 관심 요약',body:'{courseName}의 {contactRole}께, {period} 기간 동안 Golfriend가 기록한 골퍼 관심 증거입니다. 수치는 집계된 값이며 개인 정보를 포함하지 않습니다.'},pilot_proposal:{subject:'{courseName}을 위한 Golfriend 파일럿 제안',body:'{courseName}의 {contactRole}께, 파일럿을 제안드립니다. 파일럿은 활성화가 확인된 후에만 시작되며, 커미션은 서명된 계약의 발효일부터만 적용됩니다.'},meeting_recap:{subject:'Golfriend 관련 회의 요약',body:'{courseName}의 {contactRole}께, 만나 주셔서 감사합니다. 이 메모는 논의 내용을 기록한 것이며, 서명된 계약이 체결되기 전까지는 어떤 것도 합의되지 않았습니다.'}},
ja:{disclaimer:'Golfriend は予約支援のみを提供します。ティータイムを販売せず、決済を処理せず、予約・収益・独占権を保証しません。',evidenceHeading:'記録されたゴルファーの関心',suppressed:'非開示 — 安全な報告に必要な最小集計値を下回っています。',notAttributed:'主張しません — 信頼できる情報源がありません。',invitation:{subject:'Golfriend チームへのご招待',body:'{courseName} の {contactRole} 様、Golfriend は {country} のゴルファーが貴コースのような施設を見つけ、連絡できるよう支援しています。Golfriend が {courseName} の予約支援にどのように役立つかをご紹介させてください。'},follow_up:{subject:'Golfriend のご紹介に関するフォローアップ',body:'{courseName} の {contactRole} 様、先日 Golfriend についてご連絡いたしました。{courseName} について記録された関心状況を共有することがお役に立つかどうか、お伺いしたく存じます。'},opportunity_summary:{subject:'{courseName} に関する Golfriend 関心サマリー',body:'{courseName} の {contactRole} 様、{period} の期間に Golfriend が記録したゴルファーの関心に関する証拠です。数値は集計値であり、個人情報を含みません。'},pilot_proposal:{subject:'{courseName} 向け Golfriend パイロットのご提案',body:'{courseName} の {contactRole} 様、パイロットをご提案いたします。パイロットは有効化が確認された後にのみ開始し、手数料は署名済み契約の発効日からのみ適用されます。'},meeting_recap:{subject:'Golfriend に関する打ち合わせの要約',body:'{courseName} の {contactRole} 様、お時間をいただきありがとうございました。本メモは協議内容の記録であり、署名済みの契約が締結されるまで何も合意されていません。'}},
zh:{disclaimer:'Golfriend 仅提供预订协助。我们不销售开球时段，不处理付款，也不保证预订、收入或独家权利。',evidenceHeading:'已记录的球手关注度',suppressed:'不予披露 — 低于安全报告所需的最小汇总值。',notAttributed:'不作声明 — 没有权威来源。',invitation:{subject:'诚邀加入 Golfriend 团队',body:'{courseName} 的 {contactRole} 您好：Golfriend 帮助 {country} 的高尔夫球手发现并联系像贵球场这样的场地。我们希望介绍 Golfriend 如何为 {courseName} 提供预订协助。'},follow_up:{subject:'关于 Golfriend 介绍的后续跟进',body:'{courseName} 的 {contactRole} 您好：我们此前就 Golfriend 与您联系过，想了解分享我们为 {courseName} 记录的关注情况是否会有帮助。'},opportunity_summary:{subject:'{courseName} 的 Golfriend 关注度摘要',body:'{courseName} 的 {contactRole} 您好：以下是 Golfriend 在 {period} 期间记录的球手关注度证据。数据为汇总值，不包含任何个人信息。'},pilot_proposal:{subject:'面向 {courseName} 的 Golfriend 试点提案',body:'{courseName} 的 {contactRole} 您好：我们希望提出一项试点。试点仅在完成激活验证后开始，佣金仅自已签署协议的生效日起适用。'},meeting_recap:{subject:'关于 Golfriend 会议的纪要',body:'{courseName} 的 {contactRole} 您好：感谢您与我们会面。本纪要记录了讨论内容；在签署协议之前，任何事项均未达成一致。'}},
es:{disclaimer:'Golfriend solo ofrece asistencia para reservas. No vende salidas, no procesa pagos y no garantiza reservas, ingresos ni exclusividad.',evidenceHeading:'Interés de golfistas registrado',suppressed:'Retenido: por debajo del agregado mínimo para un informe seguro.',notAttributed:'No se afirma: no hay una fuente autorizada.',invitation:{subject:'Una invitación para unirse al equipo de Golfriend',body:'Estimado/a {contactRole} de {courseName}: Golfriend ayuda a los golfistas de {country} a descubrir y contactar campos como el suyo. Nos gustaría presentarle cómo Golfriend puede apoyar a {courseName} con asistencia para reservas.'},follow_up:{subject:'Seguimiento de nuestra presentación de Golfriend',body:'Estimado/a {contactRole} de {courseName}: le escribimos recientemente sobre Golfriend y queríamos saber si le resultaría útil que compartiéramos el interés registrado para {courseName}.'},opportunity_summary:{subject:'Resumen de interés de Golfriend para {courseName}',body:'Estimado/a {contactRole} de {courseName}: esta es la evidencia de interés de golfistas que Golfriend registró durante {period}. Las cifras son agregadas y no contienen datos personales.'},pilot_proposal:{subject:'Una prueba piloto de Golfriend para {courseName}',body:'Estimado/a {contactRole} de {courseName}: nos gustaría proponer una prueba piloto. El piloto comienza solo tras la activación verificada y cualquier comisión se aplica únicamente desde la fecha de entrada en vigor de un acuerdo firmado.'},meeting_recap:{subject:'Resumen de nuestra reunión sobre Golfriend',body:'Estimado/a {contactRole} de {courseName}: gracias por reunirse con nosotros. Esta nota recoge lo tratado; nada queda acordado hasta que exista un acuerdo firmado.'}},
fr:{disclaimer:"Golfriend fournit uniquement une assistance à la réservation. Golfriend ne vend pas de départs, ne traite pas de paiements et ne garantit ni réservations, ni revenus, ni exclusivité.",evidenceHeading:"Intérêt des golfeurs enregistré",suppressed:"Non communiqué : en dessous de l'agrégat minimal pour un rapport sûr.",notAttributed:"Non affirmé : aucune source faisant autorité.",invitation:{subject:"Une invitation à rejoindre l'équipe Golfriend",body:"Madame, Monsieur, {contactRole} de {courseName} : Golfriend aide les golfeurs de {country} à découvrir et à contacter des parcours comme le vôtre. Nous souhaiterions vous présenter comment Golfriend peut accompagner {courseName} en assistance à la réservation."},follow_up:{subject:"Suite à notre présentation de Golfriend",body:"Madame, Monsieur, {contactRole} de {courseName} : nous vous avons écrit récemment au sujet de Golfriend et souhaitions savoir s'il serait utile de partager l'intérêt enregistré pour {courseName}."},opportunity_summary:{subject:"Synthèse de l'intérêt Golfriend pour {courseName}",body:"Madame, Monsieur, {contactRole} de {courseName} : voici les éléments d'intérêt des golfeurs enregistrés par Golfriend sur la période {period}. Les chiffres sont agrégés et ne contiennent aucune donnée personnelle."},pilot_proposal:{subject:"Une phase pilote Golfriend pour {courseName}",body:"Madame, Monsieur, {contactRole} de {courseName} : nous souhaitons proposer une phase pilote. Le pilote ne commence qu'après activation vérifiée et toute commission ne s'applique qu'à compter de la date d'effet d'un accord signé."},meeting_recap:{subject:"Compte rendu de notre réunion sur Golfriend",body:"Madame, Monsieur, {contactRole} de {courseName} : merci de nous avoir rencontrés. Cette note consigne nos échanges ; rien n'est convenu tant qu'un accord signé n'est pas en place."}},
de:{disclaimer:'Golfriend bietet ausschließlich Buchungsunterstützung. Golfriend verkauft keine Startzeiten, wickelt keine Zahlungen ab und garantiert weder Buchungen noch Umsätze oder Exklusivität.',evidenceHeading:'Erfasstes Interesse von Golfern',suppressed:'Zurückgehalten — unterhalb des Mindestaggregats für eine sichere Berichterstattung.',notAttributed:'Nicht behauptet — keine belastbare Quelle.',invitation:{subject:'Eine Einladung, dem Golfriend-Team beizutreten',body:'Sehr geehrte/r {contactRole} von {courseName}: Golfriend hilft Golfern in {country}, Plätze wie Ihren zu finden und zu kontaktieren. Wir möchten Ihnen vorstellen, wie Golfriend {courseName} bei der Buchungsunterstützung begleiten kann.'},follow_up:{subject:'Nachfassen zu unserer Golfriend-Vorstellung',body:'Sehr geehrte/r {contactRole} von {courseName}: wir haben Ihnen kürzlich zu Golfriend geschrieben und möchten fragen, ob es hilfreich wäre, das für {courseName} erfasste Interesse zu teilen.'},opportunity_summary:{subject:'Golfriend-Interessenübersicht für {courseName}',body:'Sehr geehrte/r {contactRole} von {courseName}: dies sind die von Golfriend im Zeitraum {period} erfassten Interessensnachweise von Golfern. Die Zahlen sind aggregiert und enthalten keine personenbezogenen Daten.'},pilot_proposal:{subject:'Ein Golfriend-Pilotprojekt für {courseName}',body:'Sehr geehrte/r {contactRole} von {courseName}: wir möchten ein Pilotprojekt vorschlagen. Das Pilotprojekt beginnt erst nach verifizierter Aktivierung, und eine Provision gilt ausschließlich ab dem Wirksamkeitsdatum einer unterzeichneten Vereinbarung.'},meeting_recap:{subject:'Zusammenfassung unseres Gesprächs über Golfriend',body:'Sehr geehrte/r {contactRole} von {courseName}: vielen Dank für das Gespräch. Diese Notiz hält das Besprochene fest; nichts ist vereinbart, solange keine unterzeichnete Vereinbarung vorliegt.'}},
});

const fill=(text,tokens)=>text.replace(/\{(\w+)\}/g,(_,key)=>tokens[key]??`{${key}}`);
const periodLabel=(demand)=>demand.observedFrom&&demand.observedUntil?`${demand.observedFrom} – ${demand.observedUntil}`:'an unstated period';

/**
 * Build the privacy-safe opportunity evidence for one course.
 * Every metric passes through aggregate suppression; transaction metrics additionally
 * require authoritative attribution. The result never contains a price or an invoice.
 */
export function buildOpportunityReport({prospect,generatedAt,evaluationDate}){
  const p=normalizeProspect(prospect),share=shareableProspect(prospect),eligibility=invoiceEligibility(prospect,evaluationDate),d=p.demand;
  const raw={search_interest:d.searchInterest,saved_course:d.savedCourse,booking_interest:d.bookingInterest,confirmed_bookings:d.confirmedBookings,played_rounds:d.playedRounds};
  const metrics=[...INTEREST_METRICS,...TRANSACTION_METRICS].map((id)=>{const requireAuthoritative=TRANSACTION_METRICS.includes(id);const disclosure=discloseMetric(raw[id],d.attribution,{requireAuthoritative});return{id,claimType:requireAuthoritative?'transaction':'interest',requiresAuthoritativeAttribution:requireAuthoritative,...disclosure};});
  return Object.freeze({schema:OPPORTUNITY_SCHEMA,version:OPPORTUNITY_VERSION,generatedAt,course:{id:share.id,name:share.courseName,courseId:share.courseId,country:share.country,region:share.region},contractState:share.contract.state,period:{from:d.observedFrom,until:d.observedUntil,label:periodLabel(d)},attribution:{level:d.attribution,source:d.source},metrics,claims:metrics.filter((m)=>m.disclosed).map((m)=>m.id),withheld:metrics.filter((m)=>!m.disclosed).map((m)=>({id:m.id,reason:m.reason})),invoice:{included:false,permitted:eligibility.invoiceAllowed,entitlement:eligibility.entitlement,notice:eligibility.notice},privacy:{memberIdentityIncluded:false,preciseMovementIncluded:false,internalNotesIncluded:false,minimumAggregate:MIN_AGGREGATE_COUNT},delivery:{status:'unavailable',notice:DELIVERY_NOTICE}});
}

/**
 * Render one localized outreach draft. Generation only — there is no send path.
 * When a report is supplied its disclosed evidence is appended; withheld metrics are
 * stated as withheld rather than omitted silently.
 */
export function renderOutreachTemplate({kind,locale,prospect,report=null}){
  if(!OUTREACH_TEMPLATE_KINDS.includes(kind))throw new Error('Unknown outreach template kind.');
  const copy=OUTREACH_COPY[locale];
  if(!copy)throw new Error('Outreach copy is not available for that locale.');
  const share=shareableProspect(prospect),template=copy[kind];
  const tokens={courseName:share.courseName,country:share.country,contactRole:share.contactRole,period:report?report.period.label:'the recorded period'};
  const lines=[fill(template.body,tokens)];
  if(report){lines.push('',copy.evidenceHeading);for(const metric of report.metrics)lines.push(`- ${metric.id}: ${metric.disclosed?metric.value:metric.reason==='not_authoritatively_attributed'?copy.notAttributed:copy.suppressed}`);}
  lines.push('',copy.disclaimer);
  return Object.freeze({kind,locale,subject:fill(template.subject,tokens),body:lines.join('\n'),disclaimer:copy.disclaimer,evidenceIncluded:Boolean(report),deliveryAvailable:false,notice:DELIVERY_NOTICE});
}

export function opportunityToJson(report){return JSON.stringify(report,null,2);}
export function opportunityToText(report){return[`Schema: ${report.schema} (version ${report.version})`,`Course: ${report.course.name} — ${report.course.country} · ${report.course.region}`,`Period: ${report.period.label}`,`Attribution: ${report.attribution.level} — ${report.attribution.source}`,'',...report.metrics.map((m)=>`${m.id} [${m.claimType}]: ${m.disclosed?m.value:`withheld (${m.reason})`}`),'',`Invoice included: ${report.invoice.included}`,report.invoice.notice,report.delivery.notice].join('\n');}
