import type { CountryCoverage } from './courseOperationsService';
export type DashboardItem = { id: string; title: string; detail: string; action: string };
export type CourseOperationsDashboard = { usable: number | null; total: number | null; lastSuccessfulUpdate: string | number | null; nextScheduledRun: string | number | null; changed24h: number | null; changed7d: number | null; memberRequests: DashboardItem[] | null; reviewItems: DashboardItem[] | null; problems: DashboardItem[] | null; action: { kind: 'clear' | 'attention' | 'unavailable'; message: string; detail: string }; countries: Array<{ country: string; usable: number | null; latestRefresh: string | null; status: { kind: 'clear' | 'attention' | 'unavailable'; label: string } }>; launchMarkets: Array<{ country: string; usable: number | null; latestRefresh: string | null; status: { kind: 'clear' | 'attention' | 'unavailable'; label: string } }>; changeFeed: string[]; technicalDetails: Record<string, unknown> };
const launch = new Set(['THAILAND', 'KOREA', 'JAPAN', 'SINGAPORE', 'MALAYSIA']); const object = (value: unknown): Record<string, unknown> => value && typeof value === 'object' ? value as Record<string, unknown> : {}; const finite = (value: unknown): number | null => typeof value === 'number' && Number.isFinite(value) ? value : null; const timestamp = (value: unknown): string | number | null => typeof value === 'string' || typeof value === 'number' ? value : null; const count = (value: unknown, key: string) => finite(object(value)[key]);
export function buildCourseOperationsDashboard({ coverage, status }: { coverage: CountryCoverage[]; status: Record<string, unknown> }): CourseOperationsDashboard {
  const counts = object(status.counts); const configuration = object(status.configuration); const checkpoint = object(status.checkpoint); const lastRun = object(status.lastRun); const total = count(counts, 'canonical'); const usable = count(counts, 'usable');
  const countryRows = coverage.map((row) => { const job = row.job; const failed = job?.state === 'failed' || job?.state === 'paused'; const unavailable = !job || job.state === 'unavailable'; return { country: row.country, usable: finite(row.coursesWithCoordinates), latestRefresh: row.latestGolfriendFetchTime, status: failed ? { kind: 'attention' as const, label: job?.state === 'paused' ? 'Paused — review needed' : 'Failed — review needed' } : unavailable ? { kind: 'unavailable' as const, label: 'Not scheduled' } : { kind: 'clear' as const, label: job.state === 'running' ? 'Refreshing' : 'Scheduled' } }; });
  const problems: DashboardItem[] = []; if (configuration.enabled !== true) problems.push({ id: 'configuration', title: 'Background refresh is unavailable', detail: String(configuration.blockedReason || 'The service is not enabled.'), action: 'Review service status' }); for (const row of coverage.filter((item) => item.job?.state === 'failed' || item.job?.state === 'paused')) problems.push({ id: `job-${row.country}`, title: `${row.country} refresh ${row.job?.state}`, detail: String(row.job?.pauseReason || 'A scheduled refresh needs review.'), action: row.job?.retryAtMs ? `Retry scheduled ${new Date(row.job.retryAtMs).toLocaleString()}` : 'Review scheduled refresh' });
  const reviewCount = (count(counts, 'quarantined') || 0) + (count(counts, 'deadLetters') || 0); const reviewItems = reviewCount > 0 ? [{ id: 'review-count', title: `${reviewCount} imported record${reviewCount === 1 ? '' : 's'} need review`, detail: 'The trusted status source reports an actionable exception count, not record details.', action: 'Open technical details' }] : []; const action = problems.length ? { kind: 'attention' as const, message: problems[0].title, detail: problems[0].action } : { kind: 'clear' as const, message: 'No action needed', detail: 'No provider or scheduler problem is reported.' };
  const requestRows = Array.isArray(status.memberRequests) ? status.memberRequests.map((value, index) => { const request = object(value); return { id: String(request.id || `request-${index}`), title: String(request.requestedCourse || 'Requested course'), detail: String(request.location || 'Location unavailable'), action: String(request.action || request.status || 'Review request') }; }) : null;
  return { usable, total, lastSuccessfulUpdate: timestamp(lastRun.completedAt) || timestamp(checkpoint.lastRunAt), nextScheduledRun: timestamp(checkpoint.nextRunAt), changed24h: null, changed7d: null, memberRequests: requestRows, reviewItems, problems, action, countries: countryRows, launchMarkets: countryRows.filter((row) => launch.has(row.country)), changeFeed: [], technicalDetails: { status, coverage } };
}
