// Canonical locale type is imported, never redeclared — `src/i18n/locales.ts` owns the set.
import type{CanonicalLocale}from'../../../i18n/locales';
export type AcquisitionLocale=CanonicalLocale;
export interface ContactEntry{at:string|null;channel:string;stageAfter:string;visibility:'internal'|'shareable';summary:string;recordedBy:string}
export interface ContractRecord{[key:string]:any;state:string;signed:boolean;effectiveFrom:string|null;activatedAt:string|null;commissionBps:number|null;authority:string}
export interface DemandEvidence{[key:string]:any;attribution:'authoritative'|'unverified'|'unavailable';source:string}
export interface Prospect{[key:string]:any;id:string;courseName:string;courseId:string|null;country:string;region:string;stage:string;contactLocale:AcquisitionLocale|null;contract:ContractRecord;history:ContactEntry[];demand:DemandEvidence}
export interface Disclosure{disclosed:boolean;value:number|null;reason:string}
export interface CommissionState{effective:boolean;commissionBps:number|null;reason:string;authority:string}
export const PROSPECT_STAGES:readonly string[];export const CONTRACT_STATES:readonly string[];export const OUTREACH_CHANNELS:readonly string[];export const NOTE_VISIBILITIES:readonly string[];export const ATTRIBUTION_LEVELS:readonly string[];export const MIN_AGGREGATE_COUNT:number;export const INTERNAL_ONLY_FIELDS:readonly string[];export const HANDOFF_READY_STAGES:readonly string[];
export function normalizeContactEntry(row:Record<string,unknown>):ContactEntry;export function normalizeContract(row:Record<string,unknown>):ContractRecord;export function normalizeProspect(row:Record<string,unknown>):Prospect;export function normalizeDemandEvidence(row:Record<string,unknown>):DemandEvidence;export function discloseMetric(value:unknown,attribution:string,options?:{requireAuthoritative?:boolean}):Disclosure;export function commissionState(contract:Record<string,unknown>,at:string):CommissionState;export function invoiceEligibility(prospect:Record<string,unknown>,at:string):{invoiceAllowed:boolean;commissionBps:number|null;reason:string;entitlement:string;notice:string};export function shareableProspect(prospect:Record<string,unknown>):any;export function filterProspects(rows:Prospect[],filters?:Record<string,string>):Prospect[];export function acquisitionSummary(rows:Prospect[],at:string):any;export function conversionHandoff(prospect:Record<string,unknown>):any;
