import{normalizeProspect,type Prospect}from'./courseAcquisitionModel.mjs';
export interface AcquisitionSnapshot{source:'local-preview';prospects:Prospect[];outreachService:null;handoffService:null}
export interface AcquisitionProvider{load():Promise<AcquisitionSnapshot>}
// Local preview fixtures only. Excluded from production totals. No approved acquisition source exists.
const rows=[
{id:'preview-prospect-01',courseName:'Riverbend Golf Club',courseId:'preview-course-riverbend',country:'Thailand',region:'Chonburi',stage:'contacted',contactRole:'Course operations manager',contactLocale:'th',source:'Local preview fixture',identifiedAt:'2026-07-02',lastContactedAt:'2026-08-04',nextFollowUpAt:'2026-08-18',contract:{state:'none',signed:false},history:[{at:'2026-07-02',channel:'inbound_enquiry',stageAfter:'identified',visibility:'shareable',summary:'Course listed in the public catalogue; no agreement discussed.',recordedBy:'Admin acquisition desk'},{at:'2026-08-04',channel:'email_draft',stageAfter:'contacted',visibility:'internal',summary:'Internal qualification note',recordedBy:'Admin acquisition desk'}],demand:{attribution:'unverified',source:'Local preview fixture — not an authoritative booking source',observedFrom:'2026-07-01',observedUntil:'2026-07-31',searchInterest:41,savedCourse:12,bookingInterest:7}},
{id:'preview-prospect-02',courseName:'Highland Pines Country Club',courseId:'preview-course-highland',country:'Japan',region:'Nagano',stage:'pilot_discussion',contactRole:'General manager',contactLocale:'ja',source:'Local preview fixture',identifiedAt:'2026-06-11',lastContactedAt:'2026-08-09',nextFollowUpAt:'2026-08-20',contract:{state:'pilot_proposed',signed:false},history:[{at:'2026-08-09',channel:'meeting_note',stageAfter:'pilot_discussion',visibility:'shareable',summary:'Introductory meeting held; pilot terms not agreed.',recordedBy:'Admin acquisition desk'}],demand:{attribution:'unverified',source:'Local preview fixture — not an authoritative booking source',observedFrom:'2026-07-01',observedUntil:'2026-07-31',searchInterest:18,savedCourse:3,bookingInterest:2}},
{id:'preview-prospect-03',courseName:'Coastal Links Resort',courseId:'preview-course-coastal',country:'Thailand',region:'Phuket',stage:'signed',contactRole:'Commercial director',contactLocale:'en',source:'Local preview fixture',identifiedAt:'2026-04-08',lastContactedAt:'2026-08-01',contract:{state:'effective',signed:true,signedAt:'2026-06-20',effectiveFrom:'2026-07-01',activatedAt:'2026-07-05',pilotEndsAt:'2026-10-03',commissionBps:300,agreementVersion:'golfriend.course-partner.v1',reference:'preview-agreement-0003'},history:[{at:'2026-06-20',channel:'meeting_note',stageAfter:'signed',visibility:'shareable',summary:'Agreement signed; effective date recorded by the onboarding domain.',recordedBy:'Admin acquisition desk'}],demand:{attribution:'unavailable',source:'No attributed booking source approved for Admin acquisition reporting'}},
{id:'preview-prospect-unavailable',courseName:'Source unavailable',stage:'source_unavailable',source:'Acquisition source not approved',contract:{state:'source_unavailable'},demand:{attribution:'unavailable'}},
];
export const localPreviewAcquisitionProvider:AcquisitionProvider={async load(){return{source:'local-preview',prospects:rows.map(normalizeProspect),outreachService:null,handoffService:null};}};
