import {useEffect,useState} from 'react';
import {useAdminLocale} from './AdminLocaleContext';
import {adminCommandId,adminControlProvider} from './adminControlProvider';
import './AdminControlSurface.css';
const title={en:'Economy master controls',th:'การควบคุมเศรษฐกิจหลัก',ko:'경제 마스터 제어',ja:'エコノミーマスター管理',zh:'经济主控',es:'Controles maestros de economía',fr:'Contrôles maîtres de l’économie',de:'Zentrale Wirtschaftssteuerung'}as const;
const initial={teeActionCosts:{booking_request:1,priority_match:5,round_join:2},teeRewards:{completed_round:3,verified_review:1,referral:5},businessRates:{booking_commission_bps:300,small_business_promotion_bps:0,enterprise_service_bps:0}};
export default function EconomyMasterControl(){
 const locale=useAdminLocale(),[snapshot,setSnapshot]=useState<any>(null),[values,setValues]=useState<any>(initial),[preview,setPreview]=useState<any>(null),[notice,setNotice]=useState('');
 const load=()=>{void adminControlProvider.load().then(setSnapshot).catch(()=>setSnapshot(false))};useEffect(load,[]);
 const change=(group:string,key:string,value:string)=>setValues((x:any)=>({...x,[group]:{...x[group],[key]:Number(value)}}));
 const previewNow=async()=>{try{setPreview(await adminControlProvider.preview(values));setNotice('Preview ready — no activation yet.')}catch{setNotice('Configuration preview unavailable.')}};
 const activate=async()=>{if(!preview)return;try{const r=await adminControlProvider.activate({values,previewDigest:preview.valuesDigest,confirmed:true,expectedVersion:Number(snapshot?.economy?.pointer?.version||0),commandId:adminCommandId('economy_activate')});setNotice(`Activated v${r.version} · ${r.receiptId}`);setPreview(null);load()}catch{setNotice('Activation denied or stale.')}};
 const rollback=async(id:string)=>{try{const r=await adminControlProvider.rollback({targetConfigurationId:id,expectedVersion:Number(snapshot?.economy?.pointer?.version||0),commandId:adminCommandId('economy_rollback')});setNotice(`Rollback activated as v${r.version} · ${r.receiptId}`);load()}catch{setNotice('Rollback denied or stale.')}};
 return <section className="admin-control" aria-labelledby="economy-control-title"><h2 id="economy-control-title">{title[locale]}</h2><p>Canonical EconomyConfig only. No ledger, payment, settlement or revenue authority.</p>{Object.entries(values).map(([group,entries])=><fieldset key={group}><legend>{group.replaceAll('_',' ')}</legend>{Object.entries(entries as any).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')}<input type="number" min="0" max="10000" step="1" value={String(value)} onChange={e=>change(group,key,e.target.value)}/></label>)}</fieldset>)}<div><button onClick={previewNow}>Preview configuration</button><button disabled={!preview} onClick={activate}>Activate preview</button></div>{preview&&<output>Digest {preview.valuesDigest}</output>}<h3>Approved versions</h3>{snapshot===false?<p role="alert">Economy authority unavailable.</p>:snapshot?.economy?.versions?.map((x:any)=><article key={x.configurationId}><strong>v{x.version} · {x.configurationId}</strong><button disabled={x.configurationId===snapshot.economy.pointer?.configurationId} onClick={()=>rollback(x.configurationId)}>Rollback to this approved version</button></article>)}{notice&&<p role="status" aria-live="polite">{notice}</p>}</section>
}
