import { normalizeMarketingAsset, type MarketingAsset } from './marketingLibraryModel.mjs';
export interface MarketingLibrarySnapshot { source:'local-preview'|'trusted-production'; assets:MarketingAsset[]; uploadApproved:boolean; downloadAdapter:null|((asset:MarketingAsset)=>Promise<void>) }
export interface MarketingLibraryProvider { load():Promise<MarketingLibrarySnapshot> }
const previewRows:Record<string,unknown>[]=[
  {id:'local-hero',title:'Golfriend landing hero',category:'brand_assets',locales:['en'],format:'PNG',status:'ready',version:'local',updatedAt:'2026-08-12',owner:'Admin repository',channel:'Web reference',provenance:'src/assets/hero.png',approval:'Unverified',previewKind:'image',sourceUrl:'/src/assets/hero.png',available:true},
  {id:'local-favicon',title:'Golfriend web favicon',category:'brand_assets',locales:['en'],format:'SVG',status:'ready',version:'local',updatedAt:'2026-08-12',owner:'Admin repository',channel:'Web reference',provenance:'public/favicon.svg',approval:'Unverified',previewKind:'image',sourceUrl:'/favicon.svg',available:true},
  {id:'local-icons',title:'Admin interface icon sprite',category:'brand_assets',locales:['en'],format:'SVG',status:'draft',version:'local',updatedAt:'2026-08-12',owner:'Admin repository',channel:'Admin interface',provenance:'public/icons.svg',approval:'Unverified',previewKind:'unsupported',sourceUrl:'/icons.svg',available:true},
  {id:'course-letter',title:'Golf-course introduction letter',category:'golf_course_letters',locales:[],format:'DOC/PDF',status:'unavailable',owner:'Unassigned',channel:'Course outreach',provenance:'Storage contract not approved',approval:'Unverified',previewKind:'unsupported',requiredLaunch:true},
  {id:'partner-letter',title:'Strategic-partner introduction letter',category:'strategic_partner_letters',locales:[],format:'DOC/PDF',status:'unavailable',owner:'Unassigned',channel:'Partner outreach',provenance:'No trusted file found',approval:'Unverified',previewKind:'unsupported'},
  {id:'sponsor-intro',title:'Sponsor and advertiser introduction',category:'sponsor_introductions',locales:[],format:'PDF',status:'unavailable',owner:'Unassigned',channel:'Sponsor outreach',provenance:'No trusted file found',approval:'Unverified',previewKind:'unsupported'},
  {id:'community-intro',title:'Community and media introduction',category:'community_media_introductions',locales:[],format:'PDF',status:'outdated',owner:'Unassigned',channel:'Media outreach',provenance:'Current source not verified',approval:'Unverified',previewKind:'unsupported'},
  {id:'store-screens',title:'App store screenshot set',category:'app_screenshots',locales:[],format:'PNG/JPG',status:'unavailable',owner:'Unassigned',channel:'App stores',provenance:'No trusted capture set found',approval:'Unverified',previewKind:'unsupported',requiredLaunch:true,readinessKey:'screenshots'},
  {id:'store-copy',title:'Store short and full descriptions',category:'store_listing',locales:[],format:'Text',status:'unavailable',owner:'Unassigned',channel:'App stores',provenance:'No approved copy found',approval:'Unverified',previewKind:'unsupported',requiredLaunch:true},
  {id:'social',title:'Social content library',category:'social_content',locales:[],format:'Mixed',status:'unavailable',owner:'Unassigned',channel:'Social',provenance:'No trusted catalogue found',approval:'Unverified',previewKind:'unsupported'},
  {id:'campaign',title:'Campaign materials',category:'campaign_materials',locales:[],format:'Mixed',status:'unavailable',owner:'Unassigned',channel:'Campaigns',provenance:'No trusted catalogue found',approval:'Unverified',previewKind:'unsupported'},
  {id:'privacy',title:'Privacy policy route',category:'legal_disclosures',locales:['en'],format:'Link',status:'ready',version:'route',updatedAt:'2026-08-12',owner:'Admin repository',channel:'Web',provenance:'/legal route',approval:'Unverified',previewKind:'text',previewText:'The application exposes a privacy-policy route. Legal approval and locale completeness are not asserted.',sourceUrl:'/legal',available:true,readinessKey:'privacy_link'},
  {id:'support',title:'Support route',category:'legal_disclosures',locales:['en'],format:'Link',status:'ready',version:'route',updatedAt:'2026-08-12',owner:'Admin repository',channel:'Web',provenance:'/support route',approval:'Unverified',previewKind:'text',previewText:'The application exposes a support route. This confirms route availability only.',sourceUrl:'/support',available:true,readinessKey:'support_link'},
];
export const localPreviewMarketingProvider:MarketingLibraryProvider={async load(){return {source:'local-preview',assets:previewRows.map(normalizeMarketingAsset),uploadApproved:false,downloadAdapter:null};}};
