export const MARKETING_LOCALES = Object.freeze(['en','th','ko','ja','zh','es','fr','de']);
export const MARKETING_CATEGORIES = Object.freeze(['golf_course_letters','strategic_partner_letters','sponsor_introductions','community_media_introductions','app_screenshots','store_listing','brand_assets','social_content','campaign_materials','legal_disclosures']);
export const MARKETING_STATUSES = Object.freeze(['draft','ready','approved','outdated','unavailable']);

export function normalizeMarketingAsset(asset) {
  const locales = Array.isArray(asset.locales) ? [...new Set(asset.locales.filter((locale)=>MARKETING_LOCALES.includes(locale)))] : [];
  const available = asset.available === true && typeof asset.sourceUrl === 'string';
  return { id:String(asset.id), title:String(asset.title||'Untitled resource'), category:MARKETING_CATEGORIES.includes(asset.category)?asset.category:'campaign_materials', locales,
    format:String(asset.format||'unknown'), status:MARKETING_STATUSES.includes(asset.status)?asset.status:'unavailable', version:String(asset.version||'Unversioned'), updatedAt:asset.updatedAt||null,
    owner:String(asset.owner||'Unknown source'), channel:String(asset.channel||'Unassigned'), provenance:String(asset.provenance||'Not recorded'), approval:String(asset.approval||'Unverified'),
    disclosures:Array.isArray(asset.disclosures)?asset.disclosures.map(String):[], previewKind:['image','text'].includes(asset.previewKind)?asset.previewKind:'unsupported', previewText:asset.previewText?String(asset.previewText):null,
    sourceUrl:available?asset.sourceUrl:null, available, requiredLaunch:asset.requiredLaunch===true, downloadApproved:asset.downloadApproved===true && available, readinessKey:asset.readinessKey?String(asset.readinessKey):undefined };
}
export const filterMarketingAssets=(assets,{query='',category='all',status='all',locale='all'}={})=>{const needle=query.trim().toLowerCase();return assets.filter((asset)=>(!needle||[asset.title,asset.owner,asset.channel].some((v)=>v.toLowerCase().includes(needle)))&&(category==='all'||asset.category===category)&&(status==='all'||asset.status===status)&&(locale==='all'||asset.locales.includes(locale)));};
export function marketingSummary(assets){const byStatus=Object.fromEntries(MARKETING_STATUSES.map((status)=>[status,assets.filter((asset)=>asset.status===status).length]));const coverage=Object.fromEntries(MARKETING_LOCALES.map((locale)=>[locale,assets.filter((asset)=>asset.available&&asset.locales.includes(locale)).length]));return {total:assets.length,byStatus,coverage,missingLaunch:assets.filter((asset)=>asset.requiredLaunch&&!asset.available),recent:[...assets].filter((asset)=>asset.updatedAt).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,4)};}
export function storeReadiness(assets){const checks=[['app_icon','App icon','brand_assets'],['screenshots','Screenshots','app_screenshots'],['short_description','Short description','store_listing'],['full_description','Full description','store_listing'],['privacy_link','Privacy-policy link','legal_disclosures'],['support_link','Support link','legal_disclosures'],['deletion_link','Account-deletion link','legal_disclosures'],['booking_disclosure','Booking/payment disclosure','legal_disclosures']];return checks.map(([key,label,category])=>{const evidence=assets.find((asset)=>asset.readinessKey===key&&asset.available);return {key,label,category,ready:Boolean(evidence),evidence:evidence?.title||null};});}
export const localeCoverageComplete=(assets,category)=>MARKETING_LOCALES.every((locale)=>assets.some((asset)=>asset.category===category&&asset.available&&asset.locales.includes(locale)));
