import { useEffect, useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../../../firebaseConfig';
import { useAdminLocale } from './AdminLocaleContext';

const locales = ['en', 'th', 'ko', 'ja', 'zh', 'es', 'fr', 'de'] as const;
type Product = { productId: string; sku: string; names: Record<string, string>; descriptions: Record<string, string>; imageMediaIds: string[]; variants: Array<{ variantId: string; label: string; stock: number }>; prices: { THB: number; USD?: number }; active: boolean };
type Order = { orderId: string; state: string; grossAmount: number; currency: string; receiptId?: string; trackingNumber?: string; refundedAmount?: number };
const blank = (): Product => ({ productId: '', sku: '', names: Object.fromEntries(locales.map((locale) => [locale, ''])), descriptions: Object.fromEntries(locales.map((locale) => [locale, ''])), imageMediaIds: [], variants: [{ variantId: 'standard', label: 'Standard', stock: 0 }], prices: { THB: 0 }, active: false });

export default function OemShopAdmin({ isDirector }: { isDirector: boolean }) {
  const locale = useAdminLocale();
  const [products, setProducts] = useState<Product[]>([]), [orders, setOrders] = useState<Order[]>([]), [product, setProduct] = useState(blank), [notice, setNotice] = useState(''), [filter, setFilter] = useState(''), [cursor, setCursor] = useState<string | null>(null), [refundAttempts, setRefundAttempts] = useState<Record<string, string>>({}), [receipt, setReceipt] = useState<unknown>(null);
  const call = <T,>(name: string, data: object = {}) => httpsCallable<object, T>(functions, name)(data).then((result) => result.data);
  const refresh = async (more = false) => { try { const catalogue = await call<{ products: Product[] }>('v2OemShopAdminProducts'); const result = await call<{ orders: Order[]; nextCursor?: string | null }>('v2OemShopAdminOrders', { ...(filter ? { status: filter } : {}), ...(more && cursor ? { cursor } : {}) }); setProducts(catalogue.products); setOrders(existing => more ? [...existing, ...result.orders] : result.orders); setCursor(result.nextCursor || null); } catch { setNotice(`Shop data is unavailable (${locale}). Check the server deployment and your Director access.`); } };
  useEffect(() => { if (isDirector) void refresh(); }, [isDirector, filter]);
  if (!isDirector) return <section className="v2-admin-panel" role="alert"><h2>OEM shop</h2><p>Director access is required. No shop data or actions are available to this account.</p></section>;
  const save = async () => { try { await call('v2OemShopAdminUpsertProduct', { product }); setNotice('Product saved by the server.'); setProduct(blank()); await refresh(); } catch { setNotice('Product was not saved. Complete all eight locales, THB price, variants, and Master Album media IDs.'); } };
  const fulfill = async (orderId: string) => { try { await call('v2OemShopAdminFulfill', { orderId }); setNotice('Order is now fulfilling.'); await refresh(); } catch { setNotice('Fulfilment was not accepted.'); } };
  const ship = async (orderId: string) => { const trackingNumber = window.prompt('Tracking number'); if (!trackingNumber) return; try { await call('v2OemShopAdminShip', { orderId, trackingNumber }); setNotice('Shipping was recorded.'); await refresh(); } catch { setNotice('Shipping was not accepted.'); } };
  const refund = async (order: Order) => { const refundRequestId = refundAttempts[order.orderId] || crypto.randomUUID(); if (!refundAttempts[order.orderId]) setRefundAttempts(existing => ({ ...existing, [order.orderId]: refundRequestId })); const amount = Number(window.prompt(`Refund amount in minor ${order.currency} units`, String(order.grossAmount - (order.refundedAmount || 0)))); if (!Number.isSafeInteger(amount) || amount < 1) return; try { await call('v2OemShopAdminRefund', { orderId: order.orderId, amount, refundRequestId }); setRefundAttempts(existing => { const next = { ...existing }; delete next[order.orderId]; return next; }); setNotice('Refund was recorded.'); await refresh(); } catch { setNotice('Refund failed. Retry uses the same refund request.'); } };
  return <section className="v2-admin-panel"><h2>OEM shop</h2><p>Director-only. Catalogue, orders, shipping, refunds and receipts are decided by server callables; this screen never writes Firestore.</p>{notice && <p role="status">{notice}</p>}
    <h3>Products</h3><label>Product ID <input value={product.productId} onChange={(event) => setProduct({ ...product, productId: event.target.value })} /></label><label>SKU <input value={product.sku} onChange={(event) => setProduct({ ...product, sku: event.target.value })} /></label><label>Master Album media IDs (comma-separated)<input value={product.imageMediaIds.join(',')} onChange={(event) => setProduct({ ...product, imageMediaIds: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} /></label><label>THB minor units<input type="number" value={product.prices.THB} onChange={(event) => setProduct({ ...product, prices: { ...product.prices, THB: Number(event.target.value) } })} /></label><label>USD minor units (optional)<input type="number" value={product.prices.USD || ''} onChange={(event) => setProduct({ ...product, prices: { ...product.prices, USD: event.target.value ? Number(event.target.value) : undefined } })} /></label><label><input type="checkbox" checked={product.active} onChange={(event) => setProduct({ ...product, active: event.target.checked })} /> Active</label>
    {locales.map((locale) => <fieldset key={locale}><legend>{locale.toUpperCase()}</legend><input aria-label={`${locale} name`} placeholder="Name" value={product.names[locale]} onChange={(event) => setProduct({ ...product, names: { ...product.names, [locale]: event.target.value } })} /><textarea aria-label={`${locale} description`} placeholder="Description" value={product.descriptions[locale]} onChange={(event) => setProduct({ ...product, descriptions: { ...product.descriptions, [locale]: event.target.value } })} /></fieldset>)}
    <button type="button" onClick={save}>Save product</button><ul>{products.map((item) => <li key={item.productId}><button type="button" onClick={() => setProduct(item)}>{item.sku} · {item.names.en}</button>{item.variants.map((variant, index) => <label key={variant.variantId}> Stock {variant.label}<input type="number" value={variant.stock} onChange={event => setProduct({ ...item, variants: item.variants.map((row, current) => current === index ? { ...row, stock: Number(event.target.value) } : row) })} /></label>)}</li>)}</ul>
    <h3>Orders</h3><label>Status <select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">All</option>{['awaiting_payment','paid','fulfilling','shipped','delivered','cancelled','refunded'].map((value) => <option key={value}>{value}</option>)}</select></label><ul>{orders.map((order) => <li key={order.orderId}><strong>{order.orderId}</strong> · {order.state} · {order.grossAmount} {order.currency} {order.trackingNumber ? `· ${order.trackingNumber}` : ''} {order.receiptId && <button type="button" onClick={() => void call('v2OemShopAdminReceipt', { orderId: order.orderId }).then(value => { setReceipt(value); setNotice(`Receipt ${order.receiptId} is available.`); }).catch(() => setNotice('Receipt is unavailable.'))}>Receipt</button>} {order.state === 'paid' && <button type="button" onClick={() => void fulfill(order.orderId)}>Fulfill</button>} {order.state === 'fulfilling' && <button type="button" onClick={() => void ship(order.orderId)}>Ship</button>} {['paid','fulfilling','shipped','delivered'].includes(order.state) && <button type="button" onClick={() => void refund(order)}>Refund</button>}</li>)}</ul>{cursor && <button type="button" onClick={() => void refresh(true)}>Load more</button>}{receipt && <pre aria-label="Receipt">{JSON.stringify(receipt, null, 2)}</pre>}</section>;
}
