import { useAdminLocale } from './AdminLocaleContext';
import type { AdminLocale } from './adminNavigation';
import { courseOperationsService, type CourseOperationsService } from './courseOperationsService';
import './V2CourseOperations.css';
import V2CourseOperationsMonitor from './V2CourseOperationsMonitor';
import V2KoreaDownloadControl from './V2KoreaDownloadControl';

const EN = { title:'Golf courses and Golf API', sub:'Authoritative catalogue review and controlled provider reconciliation.', total:'Total courses', regions:'Countries / regions', coordinates:'With coordinates', missing:'Missing coordinates', quality:'Incomplete or stale', duplicates:'Potential duplicates', lastSync:'Last successful synchronization', search:'Search courses', all:'All records', incomplete:'Incomplete', stale:'Stale', healthy:'Healthy', name:'Name', location:'Country / region', coordStatus:'Coordinates', source:'Data source', updated:'Last updated', health:'Health', details:'Course details', canonical:'Canonical identifiers', contact:'Contact / booking', provenance:'Provenance', lastResult:'Last synchronization result', unavailable:'Not available', pipeline:'Golf API pipeline', quota:'Configured quota', quotaUnknown:'Unavailable — trusted service does not return quota totals.', growthBlocked:'Catalogue growth is unavailable: the approved callable reconciles existing course coordinates only.', warning:'Preview consumes provider quota. It writes nothing. Continue only with a bounded batch.', preview:'Preview dry-run', confirmPreview:'Confirm quota-consuming preview', cancel:'Cancel', apply:'Apply validated updates', confirmApply:'Confirm authorized apply', retry:'Retry', loading:'Loading course catalogue…', empty:'No courses match this view.', loadError:'Course catalogue could not be loaded.', runError:'Synchronization failed. Existing catalogue data was not changed.', noResult:'Preview completed with no results.', success:'Preview completed safely.', partial:'Preview completed with rejected or failed records.', used:'Requests used', remaining:'Requests remaining', added:'Added', changed:'Updated', unchanged:'Unchanged', rejected:'Rejected', duplicateCount:'Duplicates', coordinatesYes:'Coordinates present', coordinatesNo:'Coordinates missing', readOnly:'Catalogue review is read-only. Writes are available only through the existing staff-authorized callable.', batch:'Batch limit', close:'Close details' };
const COURSE_COPY: Record<AdminLocale, typeof EN> = {
  en: EN,
  th: {...EN,title:'สนามกอล์ฟและ Golf API',sub:'ตรวจสอบแค็ตตาล็อกและการซิงค์ผู้ให้บริการอย่างควบคุม',total:'สนามทั้งหมด',regions:'ประเทศ / ภูมิภาค',coordinates:'มีพิกัด',missing:'ไม่มีพิกัด',quality:'ไม่สมบูรณ์หรือล้าสมัย',duplicates:'รายการซ้ำที่อาจเกิดขึ้น',lastSync:'ซิงค์สำเร็จล่าสุด',search:'ค้นหาสนาม',all:'ทั้งหมด',incomplete:'ไม่สมบูรณ์',stale:'ล้าสมัย',healthy:'สมบูรณ์',details:'รายละเอียดสนาม',pipeline:'สถานะ Golf API',warning:'การแสดงตัวอย่างใช้โควตาผู้ให้บริการ แต่ไม่เขียนข้อมูล',preview:'ดูตัวอย่างแบบ dry-run',confirmPreview:'ยืนยันการแสดงตัวอย่าง',cancel:'ยกเลิก',apply:'ใช้การอัปเดตที่ตรวจสอบแล้ว',confirmApply:'ยืนยันการอัปเดต',retry:'ลองอีกครั้ง',loading:'กำลังโหลดสนาม…',empty:'ไม่พบสนาม',unavailable:'ไม่มีข้อมูล'},
  ko: {...EN,title:'골프 코스 및 Golf API',sub:'권위 있는 카탈로그 검토와 통제된 공급자 동기화',total:'전체 코스',regions:'국가 / 지역',coordinates:'좌표 있음',missing:'좌표 없음',quality:'불완전 또는 오래됨',duplicates:'잠재적 중복',lastSync:'마지막 성공 동기화',search:'코스 검색',all:'전체',incomplete:'불완전',stale:'오래됨',healthy:'정상',details:'코스 상세',pipeline:'Golf API 상태',warning:'미리보기는 공급자 할당량을 사용하지만 쓰지는 않습니다.',preview:'Dry-run 미리보기',confirmPreview:'미리보기 확인',cancel:'취소',apply:'검증된 업데이트 적용',confirmApply:'적용 확인',retry:'다시 시도',loading:'코스 로딩 중…',empty:'일치하는 코스 없음',unavailable:'사용 불가'},
  ja: {...EN,title:'ゴルフコースと Golf API',sub:'正規カタログの確認と制御されたプロバイダー同期',total:'総コース数',regions:'国 / 地域',coordinates:'座標あり',missing:'座標なし',quality:'不完全または古い',duplicates:'重複候補',lastSync:'最終同期成功',search:'コースを検索',all:'すべて',incomplete:'不完全',stale:'古い',healthy:'正常',details:'コース詳細',pipeline:'Golf API 状態',warning:'プレビューはプロバイダー枠を消費しますが書き込みません。',preview:'Dry-run プレビュー',confirmPreview:'プレビューを確認',cancel:'キャンセル',apply:'検証済み更新を適用',confirmApply:'適用を確認',retry:'再試行',loading:'コースを読み込み中…',empty:'一致するコースはありません',unavailable:'利用不可'},
  zh: {...EN,title:'高尔夫球场与 Golf API',sub:'权威目录审查与受控提供商同步',total:'球场总数',regions:'国家 / 地区',coordinates:'有坐标',missing:'缺少坐标',quality:'不完整或过期',duplicates:'潜在重复',lastSync:'最近成功同步',search:'搜索球场',all:'全部',incomplete:'不完整',stale:'过期',healthy:'健康',details:'球场详情',pipeline:'Golf API 状态',warning:'预览会消耗提供商配额，但不会写入数据。',preview:'Dry-run 预览',confirmPreview:'确认预览',cancel:'取消',apply:'应用已验证更新',confirmApply:'确认应用',retry:'重试',loading:'正在加载球场…',empty:'没有匹配的球场',unavailable:'不可用'},
  es: {...EN,title:'Campos y Golf API',sub:'Revisión del catálogo autorizado y sincronización controlada',total:'Total de campos',regions:'Países / regiones',coordinates:'Con coordenadas',missing:'Sin coordenadas',quality:'Incompletos o antiguos',duplicates:'Posibles duplicados',lastSync:'Última sincronización correcta',search:'Buscar campos',all:'Todos',incomplete:'Incompletos',stale:'Antiguos',healthy:'Correctos',details:'Detalle del campo',pipeline:'Estado de Golf API',warning:'La vista previa consume cuota, pero no escribe datos.',preview:'Vista previa dry-run',confirmPreview:'Confirmar vista previa',cancel:'Cancelar',apply:'Aplicar cambios validados',confirmApply:'Confirmar aplicación',retry:'Reintentar',loading:'Cargando campos…',empty:'No hay campos coincidentes',unavailable:'No disponible'},
  fr: {...EN,title:'Parcours et Golf API',sub:'Contrôle du catalogue de référence et synchronisation maîtrisée',total:'Total des parcours',regions:'Pays / régions',coordinates:'Avec coordonnées',missing:'Coordonnées absentes',quality:'Incomplets ou anciens',duplicates:'Doublons potentiels',lastSync:'Dernière synchronisation réussie',search:'Rechercher',all:'Tous',incomplete:'Incomplets',stale:'Anciens',healthy:'Sains',details:'Détail du parcours',pipeline:'État Golf API',warning:'L’aperçu consomme le quota fournisseur mais n’écrit aucune donnée.',preview:'Aperçu dry-run',confirmPreview:'Confirmer l’aperçu',cancel:'Annuler',apply:'Appliquer les mises à jour validées',confirmApply:'Confirmer l’application',retry:'Réessayer',loading:'Chargement des parcours…',empty:'Aucun parcours correspondant',unavailable:'Indisponible'},
  de: {...EN,title:'Golfplätze und Golf API',sub:'Verbindliche Katalogprüfung und kontrollierter Anbieterabgleich',total:'Golfplätze gesamt',regions:'Länder / Regionen',coordinates:'Mit Koordinaten',missing:'Koordinaten fehlen',quality:'Unvollständig oder veraltet',duplicates:'Mögliche Duplikate',lastSync:'Letzte erfolgreiche Synchronisierung',search:'Golfplätze suchen',all:'Alle',incomplete:'Unvollständig',stale:'Veraltet',healthy:'Gesund',details:'Golfplatzdetails',pipeline:'Golf-API-Status',warning:'Die Vorschau verbraucht Anbieterquote, schreibt aber keine Daten.',preview:'Dry-run Vorschau',confirmPreview:'Vorschau bestätigen',cancel:'Abbrechen',apply:'Geprüfte Updates anwenden',confirmApply:'Anwendung bestätigen',retry:'Erneut versuchen',loading:'Golfplätze werden geladen…',empty:'Keine passenden Golfplätze',unavailable:'Nicht verfügbar'},
};
const GROWTH_STATE:Record<AdminLocale,string>={
  en:'Course growth is server-authoritative and remains unavailable until provider credentials and an authoritative quota limit are configured.',
  th:'การเพิ่มสนามควบคุมโดยเซิร์ฟเวอร์และจะยังใช้ไม่ได้จนกว่าจะตั้งค่าผู้ให้บริการและขีดจำกัดโควตาที่เชื่อถือได้',
  ko:'코스 성장은 서버 권한으로 처리되며 제공자 자격 증명과 권한 있는 할당량 한도가 설정될 때까지 사용할 수 없습니다.',
  ja:'コース拡充はサーバー権限で処理され、プロバイダー資格情報と正規のクォータ上限が設定されるまで利用できません。',
  zh:'球场增长由服务器授权控制，在配置服务商凭据和权威配额上限前保持不可用。',
  es:'El crecimiento de campos es responsabilidad del servidor y permanece no disponible hasta configurar credenciales y un límite de cuota autorizado.',
  fr:'La croissance des parcours relève du serveur et reste indisponible tant que les identifiants fournisseur et une limite de quota de référence ne sont pas configurés.',
  de:'Das Platzwachstum ist serverautoritativ und bleibt ohne Anbieterzugang sowie verbindliches Kontingentlimit nicht verfügbar.',
};

export default function V2CourseOperations({ service = courseOperationsService }: { service?: CourseOperationsService }) {
  const locale=useAdminLocale(); const copy = {...COURSE_COPY[locale],growthBlocked:GROWTH_STATE[locale]};
  return <div className="course-ops">
    <header className="course-ops-intro"><div><span>COURSE AUTHORITY</span><h2>{copy.title}</h2><p>{copy.sub}</p></div><aside><strong>{copy.readOnly}</strong></aside></header>
    <V2KoreaDownloadControl service={service}/>
    <section className="course-ops-grid"><aside className="course-pipeline"><span>SERVER-AUTHORIZED CALLABLE</span><h3>{copy.pipeline}</h3><p className="course-growth">{copy.growthBlocked}</p></aside></section>
    <V2CourseOperationsMonitor service={service}/>
  </div>;
}
