import {useCallback, useEffect, useState} from 'react';
import {loadCountryUserAnalytics} from './countryUserAnalyticsService';
type Row={country:string;verifiedMembers:number;newMembers:number;activeMembers:number|null;courseCoverage:{clubhouses:number;playableLayouts:number};memberCourseRequests:number;currentNeed:string};
const display=(value:number|null|undefined)=>value===null||value===undefined?'Not collected yet':String(value);
export default function V2CountryUserAnalytics(){
  const [period,setPeriod]=useState<7|30>(30),[state,setState]=useState<'loading'|'ready'|'error'>('loading'),[data,setData]=useState<Record<string,any>>({});
  const load=useCallback(async()=>{setState('loading');try{setData(await loadCountryUserAnalytics(period));setState('ready')}catch{setState('error')}},[period]);
  useEffect(()=>{void load();},[load]);
  const rows=Array.isArray(data.countries)?data.countries as Row[]:[], totals=data.totals||{}, newMemberCompleteness=data.sourceCompleteness?.newMembers||{};
  return <section className="country-user-analytics" aria-labelledby="country-user-title"><header><h2 id="country-user-title">Country user analytics</h2><p>Trusted Firebase operational aggregates only. Countries come from explicitly stored country fields; missing country is UNKNOWN.</p></header><p><label>Period <select value={period} onChange={event=>setPeriod(Number(event.target.value) as 7|30)}><option value={7}>7 days</option><option value={30}>30 days</option></select></label></p>{state==='loading'&&<p role="status">Loading country analytics…</p>}{state==='error'&&<p role="alert">Country analytics could not be loaded. <button onClick={()=>void load()}>Retry</button></p>}{state==='ready'&&<><div className="course-ops-metrics"><article><span>Verified members</span><strong>{display(totals.verifiedMembers)}</strong></article><article><span>New members in selected period</span><strong>{display(totals.newMembers)}</strong></article><article><span>Active members in selected period</span><strong>{display(totals.activeMembers)}</strong></article><article><span>Generated at</span><strong>{data.generatedAt?new Date(String(data.generatedAt)).toLocaleString():'—'}</strong></article></div><p>Activity, Match demand, and Clubhouse demand: Not collected yet.</p>{Number.isInteger(newMemberCompleteness.recordsWithCreatedAt)&&Number.isInteger(newMemberCompleteness.memberRecords)&&<p>New-member source completeness: {newMemberCompleteness.recordsWithCreatedAt}/{newMemberCompleteness.memberRecords} member records have created_at.</p>}<div className="course-table-wrap"><table><thead><tr><th>Country</th><th>Verified members</th><th>New members</th><th>Active members</th><th>Course coverage</th><th>Member course requests</th><th>Current need</th></tr></thead><tbody>{rows.map(row=><tr key={row.country}><td>{row.country}</td><td>{row.verifiedMembers}</td><td>{row.newMembers}</td><td>{display(row.activeMembers)}</td><td>{row.courseCoverage.clubhouses} clubhouses · {row.courseCoverage.playableLayouts} playable layouts</td><td>{row.memberCourseRequests}</td><td>{row.currentNeed}</td></tr>)}</tbody></table></div></>}</section>;
}
