import { useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../../../firebaseConfig';
import { useAdminLocale } from './AdminLocaleContext';
import type { AdminLocale } from './adminNavigation';
import { courseOperationsService, type CountryCoverage, type CourseOperationsService } from './courseOperationsService';
import { buildCourseOperationsDashboard, type CourseOperationsDashboard } from './courseOperationsDashboard';
import './V2CourseOperations.css';
import { AdminIdentityContext } from './AdminIdentityContext';

const EN = {
  title: 'Course Operations', sub: 'The catalogue is read from Firebase. Provider work stays in the scheduled service.', health: 'Catalogue health', usable: 'Usable courses', total: 'Total courses', lastUpdate: 'Last successful Admin update', nextRun: 'Next scheduled run', changes: 'New or changed courses', last24: 'Last 24 hours', last7: 'Last 7 days', action: 'Your action now', noAction: 'No action needed', unavailable: 'Unavailable from the trusted source', loading: 'Loading course operations…', loadError: 'Course operations could not be loaded.', retry: 'Retry', requests: 'Member course requests', review: 'Needs review', problems: 'Provider and scheduler problems', noRequests: 'Member requests are not exposed by the trusted Admin source.', noReview: 'No actionable review items are reported.', noProblems: 'No provider or scheduler problem is reported.', detailsUnavailable: 'Details are not exposed by the trusted Admin source.', countryCoverage: 'Launch-market coverage', allCountries: 'All countries', launchMarkets: 'Launch markets', country: 'Country', added: 'Added', updated: 'Updated', refreshed: 'Last successful refresh', status: 'Status', changeFeed: 'Change feed', noChanges: 'Changes are not exposed by the trusted Admin source.', technical: 'Technical details', technicalHint: 'Canonical identifiers, quota, receipts, and provider evidence.', requestedCourse: 'Requested course', location: 'Location', members: 'Members', age: 'Age', currentStatus: 'Status', nextAction: 'Action',
};
const COPY: Record<AdminLocale, typeof EN> = {
  en: EN,
  th: { ...EN, title: 'การปฏิบัติงานสนามกอล์ฟ', health: 'สุขภาพแค็ตตาล็อก', usable: 'สนามที่ใช้ได้', total: 'สนามทั้งหมด', lastUpdate: 'อัปเดต Admin สำเร็จล่าสุด', nextRun: 'รอบที่กำหนดถัดไป', action: 'สิ่งที่ต้องทำตอนนี้', noAction: 'ไม่ต้องดำเนินการ', requests: 'คำขอสนามจากสมาชิก', review: 'ต้องตรวจสอบ', problems: 'ปัญหาผู้ให้บริการและตัวกำหนดเวลา', countryCoverage: 'ความครอบคลุมตลาดเปิดตัว', allCountries: 'ทุกประเทศ', launchMarkets: 'ตลาดเปิดตัว', changeFeed: 'รายการเปลี่ยนแปลง', technical: 'รายละเอียดทางเทคนิค' },
  ko: { ...EN, title: '코스 운영', health: '카탈로그 상태', usable: '사용 가능한 코스', total: '전체 코스', lastUpdate: '마지막 Admin 업데이트', nextRun: '다음 예약 실행', action: '지금 필요한 조치', noAction: '조치가 필요하지 않습니다', requests: '회원 코스 요청', review: '검토 필요', problems: '공급자 및 스케줄러 문제', countryCoverage: '출시 시장 커버리지', allCountries: '모든 국가', launchMarkets: '출시 시장', changeFeed: '변경 내역', technical: '기술 세부정보' },
  ja: { ...EN, title: 'コース運用', health: 'カタログの状態', usable: '利用可能なコース', total: '総コース数', lastUpdate: '最終 Admin 更新', nextRun: '次回の予定実行', action: '今必要な対応', noAction: '対応は不要です', requests: 'メンバーのコース依頼', review: '要確認', problems: 'プロバイダーとスケジューラの問題', countryCoverage: 'ローンチ市場のカバレッジ', allCountries: 'すべての国', launchMarkets: 'ローンチ市場', changeFeed: '変更フィード', technical: '技術詳細' },
  zh: { ...EN, title: '球场运营', health: '目录健康状态', usable: '可用球场', total: '球场总数', lastUpdate: '最近一次 Admin 更新', nextRun: '下次计划运行', action: '当前操作', noAction: '无需操作', requests: '会员球场请求', review: '需要审核', problems: '供应商和调度问题', countryCoverage: '首发市场覆盖', allCountries: '所有国家', launchMarkets: '首发市场', changeFeed: '变更动态', technical: '技术详情' },
  es: { ...EN, title: 'Operaciones de campos', health: 'Salud del catálogo', usable: 'Campos utilizables', total: 'Total de campos', lastUpdate: 'Última actualización Admin', nextRun: 'Próxima ejecución programada', action: 'Tu acción ahora', noAction: 'No se requiere acción', requests: 'Solicitudes de campos de miembros', review: 'Necesita revisión', problems: 'Problemas de proveedor y programación', countryCoverage: 'Cobertura de mercados de lanzamiento', allCountries: 'Todos los países', launchMarkets: 'Mercados de lanzamiento', changeFeed: 'Cambios', technical: 'Detalles técnicos' },
  fr: { ...EN, title: 'Opérations des parcours', health: 'Santé du catalogue', usable: 'Parcours utilisables', total: 'Total des parcours', lastUpdate: 'Dernière mise à jour Admin', nextRun: 'Prochaine exécution planifiée', action: 'Votre action maintenant', noAction: 'Aucune action requise', requests: 'Demandes de parcours des membres', review: 'À vérifier', problems: 'Problèmes fournisseur et planification', countryCoverage: 'Couverture des marchés de lancement', allCountries: 'Tous les pays', launchMarkets: 'Marchés de lancement', changeFeed: 'Fil des changements', technical: 'Détails techniques' },
  de: { ...EN, title: 'Platzbetrieb', health: 'Katalogstatus', usable: 'Nutzbare Plätze', total: 'Plätze gesamt', lastUpdate: 'Letztes erfolgreiches Admin-Update', nextRun: 'Nächste geplante Ausführung', action: 'Ihre Aufgabe jetzt', noAction: 'Keine Aktion erforderlich', requests: 'Mitgliederanfragen zu Plätzen', review: 'Prüfung erforderlich', problems: 'Anbieter- und Scheduler-Probleme', countryCoverage: 'Abdeckung der Startmärkte', allCountries: 'Alle Länder', launchMarkets: 'Startmärkte', changeFeed: 'Änderungsfeed', technical: 'Technische Details' },
};
type LoadState = 'loading' | 'ready' | 'error'; type Snapshot = { coverage: CountryCoverage[]; status: Record<string, unknown> };
const when = (value: string | number | null | undefined) => { if (value === null || value === undefined || value === '') return '—'; const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toLocaleString() : '—'; };
export default function V2CourseOperations({ service = courseOperationsService }: { service?: CourseOperationsService }) {
  const locale = useAdminLocale(), identity=useContext(AdminIdentityContext), copy = COPY[locale]; const [state, setState] = useState<LoadState>('loading'); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [allCountries, setAllCountries] = useState(false),[enabling,setEnabling]=useState(false),[weeklyNotice,setWeeklyNotice]=useState<Record<string,unknown>|null>(null);
  const load = useCallback(async () => { setState('loading'); try { const [coverage, status] = await Promise.all([service.loadCountryCoverage(), service.loadIngestionOperations()]); setSnapshot({ coverage, status }); setState('ready'); } catch { setState('error'); } }, [service]);
  useEffect(() => { void load(); }, [load]); const dashboard = useMemo<CourseOperationsDashboard | null>(() => snapshot ? buildCourseOperationsDashboard(snapshot) : null, [snapshot]);
  if (state === 'loading') return <section className="course-ops-state"><p role="status">{copy.loading}</p></section>;
  if (state === 'error' || !dashboard) return <section className="course-ops-state"><p role="alert">{copy.loadError}</p><button onClick={() => void load()}>{copy.retry}</button></section>;
  const countries = allCountries ? dashboard.countries : dashboard.launchMarkets; const enableWeekly=async()=>{setEnabling(true);setWeeklyNotice(null);try{const activation=await httpsCallable(functions,'activateCourseCatalogue')({}),weekly=await service.enableWeeklyCourseRefresh();setWeeklyNotice({...weekly,activationReceiptId:(activation.data as {receiptId?:unknown}).receiptId});await load();}catch{setWeeklyNotice({error:'Weekly refresh was not enabled. Provider access remains unchanged.'});}finally{setEnabling(false);}};
  return <main className="course-ops" aria-label={copy.title}>
    <section className="course-ops-summary" aria-label={copy.health}><header><p className="course-eyebrow">ADMIN CATALOGUE</p><h2>{copy.title}</h2><p>{copy.sub}</p></header><div className="course-summary-grid"><article><span>{copy.health}</span><strong>{dashboard.usable ?? copy.unavailable}<small> / {dashboard.total ?? copy.unavailable}</small></strong><em>{copy.usable} / {copy.total}</em></article><article><span>{copy.lastUpdate}</span><strong>{when(dashboard.lastSuccessfulUpdate)}</strong><em>{copy.nextRun}: {when(dashboard.nextScheduledRun)}</em></article><article><span>{copy.changes}</span><strong>{dashboard.changed24h ?? copy.unavailable}<small> / {dashboard.changed7d ?? copy.unavailable}</small></strong><em>{copy.last24} / {copy.last7}</em></article><article className={`course-action is-${dashboard.action.kind}`}><span>{copy.action}</span><strong>{dashboard.action.kind === 'clear' ? copy.noAction : dashboard.action.message}</strong><em>{dashboard.action.detail}</em></article></div></section>
    {identity?.role==='Director'&&identity.status?.trim().toLocaleLowerCase()==='active'&&identity.appCheck&&<section className="course-section" aria-label="Director weekly refresh action"><h3>Enable weekly course refresh</h3><p>This creates an immutable activation receipt and enables the weekly launch-market plan. It makes no Golf API call now.</p><button disabled={enabling} onClick={()=>void enableWeekly()}>{enabling?'Enabling weekly refresh…':'Enable weekly course refresh'}</button>{weeklyNotice&&('error'in weeklyNotice?<p role="alert">{String(weeklyNotice.error)}</p>:<p role="status">Weekly refresh enabled. Activation receipt: {String(weeklyNotice.activationReceiptId)} · Receipt: {String(weeklyNotice.receiptId)} · Next weekly run: {String(weeklyNotice.nextDueAt)}</p>)}</section>}
    <section className="course-queues" aria-label="Action queues"><Queue title={copy.requests} empty={copy.noRequests} unavailable={copy.detailsUnavailable} items={dashboard.memberRequests} /><Queue title={copy.review} empty={copy.noReview} unavailable={copy.detailsUnavailable} items={dashboard.reviewItems} /><Queue title={copy.problems} empty={copy.noProblems} unavailable={copy.detailsUnavailable} items={dashboard.problems} /></section>
    <section className="course-section" aria-labelledby="course-coverage-title"><div className="course-section-heading"><div><p className="course-eyebrow">FIREBASE COVERAGE</p><h3 id="course-coverage-title">{copy.countryCoverage}</h3></div><button className="course-view-toggle" aria-pressed={allCountries} onClick={() => setAllCountries((value) => !value)}>{allCountries ? copy.launchMarkets : copy.allCountries}</button></div><div className="course-table-wrap"><table><thead><tr><th>{copy.country}</th><th>{copy.usable}</th><th>{copy.added}</th><th>{copy.updated}</th><th>{copy.refreshed}</th><th>{copy.status}</th></tr></thead><tbody>{countries.map((row) => <tr key={row.country}><th scope="row">{row.country}</th><td>{row.usable ?? '—'}</td><td>—</td><td>—</td><td>{when(row.latestRefresh)}</td><td><span className={`course-status is-${row.status.kind}`}>{row.status.label}</span></td></tr>)}</tbody></table></div></section>
    <section className="course-section course-change-feed" aria-labelledby="course-change-title"><div className="course-section-heading"><div><p className="course-eyebrow">CATALOGUE HISTORY</p><h3 id="course-change-title">{copy.changeFeed}</h3></div></div><p>{dashboard.changeFeed.length ? dashboard.changeFeed.join(' ') : copy.noChanges}</p></section>
    <details className="course-technical"><summary>{copy.technical}<small>{copy.technicalHint}</small></summary><pre>{JSON.stringify(dashboard.technicalDetails, null, 2)}</pre></details>
  </main>;
}
function Queue({ title, empty, unavailable, items }: { title: string; empty: string; unavailable: string; items: CourseOperationsDashboard['memberRequests'] }) { return <section className="course-queue" aria-label={title}><h3>{title}</h3>{items === null ? <p>{unavailable}</p> : items.length === 0 ? <p>{empty}</p> : <ul>{items.map((item) => <li key={item.id}><strong>{item.title}</strong><span>{item.detail}</span><span>{item.action}</span></li>)}</ul>}</section>; }
