import {useState} from 'react';
import {useAdminLocale} from './AdminLocaleContext';
import type {AdminLocale} from './adminNavigation';
import type {CourseOperationsService} from './courseOperationsService';

const COPY:Record<AdminLocale,{title:string;latitude:string;longitude:string;radius:string;preview:string;confirm:string;cancel:string;commit:string;working:string;failed:string;ready:string;done:string;warning:string}>={
  en:{title:'Grow course catalogue',latitude:'Latitude',longitude:'Longitude',radius:'Radius (km)',preview:'Preview region',confirm:'Confirm provider preview',cancel:'Cancel',commit:'Commit previewed courses',working:'Working…',failed:'Ingestion is unavailable. Configuration, authority, quota, or provider readiness may be missing.',ready:'Preview ready',done:'Ingestion completed',warning:'Preview consumes provider quota. Commit writes only the exact server preview.'},
  th:{title:'เพิ่มแค็ตตาล็อกสนาม',latitude:'ละติจูด',longitude:'ลองจิจูด',radius:'รัศมี (กม.)',preview:'ดูตัวอย่างพื้นที่',confirm:'ยืนยันการดูตัวอย่างจากผู้ให้บริการ',cancel:'ยกเลิก',commit:'บันทึกสนามที่ดูตัวอย่างแล้ว',working:'กำลังทำงาน…',failed:'ใช้งานการนำเข้าไม่ได้ อาจยังไม่มีการตั้งค่า สิทธิ์ โควตา หรือความพร้อมของผู้ให้บริการ',ready:'ตัวอย่างพร้อมแล้ว',done:'นำเข้าเสร็จแล้ว',warning:'การดูตัวอย่างใช้โควตาผู้ให้บริการ การบันทึกจะใช้เฉพาะตัวอย่างจากเซิร์ฟเวอร์เท่านั้น'},
  ko:{title:'코스 카탈로그 확장',latitude:'위도',longitude:'경도',radius:'반경(km)',preview:'지역 미리보기',confirm:'제공자 미리보기 확인',cancel:'취소',commit:'미리 본 코스 반영',working:'처리 중…',failed:'설정, 권한, 할당량 또는 제공자 준비가 없어 수집을 사용할 수 없습니다.',ready:'미리보기 준비됨',done:'수집 완료',warning:'미리보기는 제공자 할당량을 사용합니다. 반영은 서버 미리보기의 정확한 항목만 기록합니다.'},
  ja:{title:'コースカタログを拡張',latitude:'緯度',longitude:'経度',radius:'半径（km）',preview:'地域をプレビュー',confirm:'プロバイダーのプレビューを確認',cancel:'キャンセル',commit:'プレビュー済みコースを登録',working:'処理中…',failed:'設定、権限、クォータ、またはプロバイダー準備が不足しているため利用できません。',ready:'プレビュー準備完了',done:'取り込み完了',warning:'プレビューはプロバイダーのクォータを使用します。登録対象はサーバープレビューと完全に一致します。'},
  zh:{title:'扩展球场目录',latitude:'纬度',longitude:'经度',radius:'半径（公里）',preview:'预览区域',confirm:'确认服务商预览',cancel:'取消',commit:'提交已预览球场',working:'处理中…',failed:'配置、权限、配额或服务商尚未就绪，无法执行导入。',ready:'预览已就绪',done:'导入完成',warning:'预览会消耗服务商配额。提交只写入服务器预览中的确切球场。'},
  es:{title:'Ampliar catálogo de campos',latitude:'Latitud',longitude:'Longitud',radius:'Radio (km)',preview:'Previsualizar región',confirm:'Confirmar vista del proveedor',cancel:'Cancelar',commit:'Incorporar campos previsualizados',working:'Procesando…',failed:'La ingesta no está disponible: puede faltar configuración, autoridad, cuota o proveedor.',ready:'Vista previa lista',done:'Ingesta completada',warning:'La vista previa consume cuota. La incorporación solo escribe la vista exacta del servidor.'},
  fr:{title:'Étendre le catalogue des parcours',latitude:'Latitude',longitude:'Longitude',radius:'Rayon (km)',preview:'Prévisualiser la région',confirm:'Confirmer l’aperçu fournisseur',cancel:'Annuler',commit:'Intégrer les parcours prévisualisés',working:'Traitement…',failed:'Ingestion indisponible : configuration, autorisation, quota ou fournisseur absent.',ready:'Aperçu prêt',done:'Ingestion terminée',warning:'L’aperçu consomme du quota. Seul l’aperçu exact du serveur peut être intégré.'},
  de:{title:'Platzkatalog erweitern',latitude:'Breitengrad',longitude:'Längengrad',radius:'Radius (km)',preview:'Region vorschauen',confirm:'Anbietervorschau bestätigen',cancel:'Abbrechen',commit:'Vorgemerkte Plätze übernehmen',working:'Wird verarbeitet…',failed:'Import nicht verfügbar: Konfiguration, Berechtigung, Kontingent oder Anbieter fehlt möglicherweise.',ready:'Vorschau bereit',done:'Import abgeschlossen',warning:'Die Vorschau verbraucht Anbieterquote. Übernommen wird nur die exakte Servervorschau.'},
};

type State='idle'|'confirm'|'previewing'|'ready'|'committing'|'done'|'error';
export default function V2CourseIngestionControl({service}:{service:CourseOperationsService}){
  const copy=COPY[useAdminLocale()]; const[state,setState]=useState<State>('idle');
  const[latitude,setLatitude]=useState('');const[longitude,setLongitude]=useState('');const[radius,setRadius]=useState('50');
  const[preview,setPreview]=useState<Record<string,unknown>|null>(null);const[result,setResult]=useState<Record<string,unknown>|null>(null);
  const valid=Number.isFinite(Number(latitude))&&Number(latitude)>=-90&&Number(latitude)<=90&&Number.isFinite(Number(longitude))&&Number(longitude)>=-180&&Number(longitude)<=180&&Number(radius)>=1&&Number(radius)<=200;
  const runPreview=async()=>{setState('previewing');try{setPreview(await service.previewRegion({latitude:Number(latitude),longitude:Number(longitude),radiusKm:Number(radius)}));setState('ready');}catch{setState('error');}};
  const commit=async()=>{const jobId=String(preview?.jobId||'');if(!jobId){setState('error');return;}setState('committing');try{setResult(await service.commitRegion(jobId));setState('done');}catch{setState('error');}};
  return <section className="course-ingestion" aria-labelledby="course-ingestion-title"><h3 id="course-ingestion-title">{copy.title}</h3><p>{copy.warning}</p><div className="course-ingestion-fields"><label>{copy.latitude}<input inputMode="decimal" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label>{copy.longitude}<input inputMode="decimal" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label><label>{copy.radius}<input type="number" min="1" max="200" value={radius} onChange={e=>setRadius(e.target.value)}/></label></div>
    {state==='idle'&&<button disabled={!valid} onClick={()=>setState('confirm')}>{copy.preview}</button>}{state==='confirm'&&<div role="group" aria-label={copy.confirm}><strong>{copy.confirm}</strong><button onClick={()=>void runPreview()}>{copy.confirm}</button><button onClick={()=>setState('idle')}>{copy.cancel}</button></div>}{(state==='previewing'||state==='committing')&&<p role="status">{copy.working}</p>}{state==='ready'&&<div role="status"><p>{copy.ready}: {String(preview?.newCoursesReady??0)} · quota {String(preview?.quotaRemainingAfter??'—')}</p><button onClick={()=>void commit()}>{copy.commit}</button><button onClick={()=>{setPreview(null);setState('idle')}}>{copy.cancel}</button></div>}{state==='done'&&<p role="status">{copy.done}: {String(result?.added??0)}</p>}{state==='error'&&<div role="alert"><p>{copy.failed}</p><button onClick={()=>setState('idle')}>{copy.preview}</button></div>}
  </section>;
}
