import{useCallback,useEffect,useState}from'react';import{useAdminLocale}from'./AdminLocaleContext';import type{AdminLocale}from'./adminNavigation';import type{CourseOperationsService}from'./courseOperationsService';
const EN={title:'Golf API catalogue authority',loading:'Loading authoritative catalogue status…',unavailable:'Authoritative catalogue status is unavailable.',retry:'Retry',refresh:'Refresh status',provider:'Provider access',blocked:'Blocked reason',project:'Project',counts:'Canonical / usable',identity:'Unique CourseID / providerCourseId / ClubID',missing:'Missing CourseID / providerCourseId / ClubID',duplicates:'Duplicate providerCourseId',quarantine:'Quarantine',retries:'Retries / dead letters',progress:'Scanned / created / updated',unchanged:'Unchanged / failed',remaining:'Provider remaining',evidence:'Quota evidence time',budget:'Internal budget / reserve',freshness:'Budget-limited incremental freshness',checkpoint:'Checkpoint and exact cursor',runs:'Last / next run',receipt:'Immutable count receipt'};
const COPY:Record<AdminLocale,typeof EN>={en:EN,
th:{...EN,title:'ศูนย์ควบคุมแค็ตตาล็อก Golf API',loading:'กำลังโหลดสถานะแค็ตตาล็อกที่เชื่อถือได้…',unavailable:'ไม่สามารถดูสถานะแค็ตตาล็อกที่เชื่อถือได้',retry:'ลองอีกครั้ง',refresh:'รีเฟรชสถานะ',provider:'การเข้าถึงผู้ให้บริการ',blocked:'เหตุผลที่บล็อก',project:'โปรเจกต์',counts:'มาตรฐาน / ใช้งานได้',identity:'CourseID / providerCourseId / ClubID ที่ไม่ซ้ำ',missing:'CourseID / providerCourseId / ClubID ที่ขาด',duplicates:'providerCourseId ซ้ำ',quarantine:'กักกัน',retries:'ลองใหม่ / จดหมายตาย',progress:'สแกน / สร้าง / อัปเดต',unchanged:'ไม่เปลี่ยน / ล้มเหลว',remaining:'โควตาผู้ให้บริการคงเหลือ',evidence:'เวลาอ้างอิงโควตา',budget:'งบภายใน / เงินสำรอง',checkpoint:'เช็กพอยต์และตำแหน่งที่แน่นอน',runs:'รอบล่าสุด / รอบถัดไป',receipt:'ใบรับรองจำนวนที่แก้ไขไม่ได้'},
ko:{...EN,title:'Golf API 카탈로그 권한',loading:'권한 있는 카탈로그 상태를 불러오는 중…',unavailable:'권한 있는 카탈로그 상태를 사용할 수 없습니다.',retry:'다시 시도',refresh:'상태 새로고침',provider:'공급자 접근',blocked:'차단 사유',counts:'정규 / 사용 가능',identity:'고유 CourseID / providerCourseId / ClubID',missing:'누락 CourseID / providerCourseId / ClubID',receipt:'불변 개수 영수증'},
ja:{...EN,title:'Golf API カタログ権限',loading:'権威あるカタログ状態を読み込み中…',unavailable:'権威あるカタログ状態を利用できません。',retry:'再試行',refresh:'状態を更新',provider:'プロバイダーアクセス',blocked:'ブロック理由',counts:'正規 / 利用可能',identity:'一意の CourseID / providerCourseId / ClubID',missing:'欠落 CourseID / providerCourseId / ClubID',receipt:'変更不可の件数レシート'},
zh:{...EN,title:'Golf API 球场目录权限',loading:'正在加载权威目录状态…',unavailable:'权威目录状态不可用。',retry:'重试',refresh:'刷新状态',provider:'供应商访问',blocked:'阻止原因',counts:'规范 / 可用',identity:'唯一 CourseID / providerCourseId / ClubID',missing:'缺少 CourseID / providerCourseId / ClubID',receipt:'不可变计数凭据'},
es:{...EN,title:'Autoridad del catálogo Golf API',loading:'Cargando el estado autoritativo del catálogo…',unavailable:'El estado autoritativo no está disponible.',retry:'Reintentar',refresh:'Actualizar estado',provider:'Acceso al proveedor',blocked:'Motivo del bloqueo',counts:'Canónicos / utilizables',identity:'CourseID / providerCourseId / ClubID únicos',missing:'CourseID / providerCourseId / ClubID ausentes',receipt:'Recibo inmutable de conteo'},
fr:{...EN,title:'Autorité du catalogue Golf API',loading:'Chargement de l’état de référence du catalogue…',unavailable:'L’état de référence est indisponible.',retry:'Réessayer',refresh:'Actualiser l’état',provider:'Accès fournisseur',blocked:'Motif du blocage',counts:'Canoniques / utilisables',identity:'CourseID / providerCourseId / ClubID uniques',missing:'CourseID / providerCourseId / ClubID manquants',receipt:'Reçu de comptage immuable'},
de:{...EN,title:'Golf-API-Katalogautorität',loading:'Verbindlicher Katalogstatus wird geladen…',unavailable:'Der verbindliche Katalogstatus ist nicht verfügbar.',retry:'Erneut versuchen',refresh:'Status aktualisieren',provider:'Anbieterzugriff',blocked:'Sperrgrund',counts:'Kanonisch / nutzbar',identity:'Eindeutige CourseID / providerCourseId / ClubID',missing:'Fehlende CourseID / providerCourseId / ClubID',receipt:'Unveränderlicher Zählbeleg'}};
const FRESHNESS_COPY:Record<AdminLocale,string>={en:'refreshAfterDays prioritizes work; it is not a guaranteed 30-day detail refresh.',th:'refreshAfterDays ใช้จัดลำดับความสำคัญ ไม่ได้รับประกันการรีเฟรชรายละเอียดภายใน 30 วัน',ko:'refreshAfterDays는 작업 우선순위이며 30일 상세 새로고침을 보장하지 않습니다.',ja:'refreshAfterDays は優先順位付けであり、30日間の詳細更新を保証しません。',zh:'refreshAfterDays 仅用于确定优先级，并不保证 30 天内刷新详情。',es:'refreshAfterDays prioriza el trabajo; no garantiza una actualización detallada en 30 días.',fr:'refreshAfterDays priorise le travail; il ne garantit pas une actualisation détaillée sous 30 jours.',de:'refreshAfterDays priorisiert die Arbeit; es garantiert keine Detailaktualisierung innerhalb von 30 Tagen.'};
const object=(value:unknown):Record<string,any>=>value&&typeof value==='object'?value as Record<string,any>:{};const shown=(value:unknown)=>value===null||value===undefined||value===''?'—':String(value);const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():'—';
export default function V2CourseOperationsMonitor({service}:{service:CourseOperationsService}){
  const locale=useAdminLocale(),copy=COPY[locale],[state,setState]=useState<'loading'|'ready'|'error'>('loading'),[data,setData]=useState<Record<string,unknown>>({});
  const load=useCallback(async()=>{setState('loading');try{setData(await service.loadIngestionOperations());setState('ready')}catch{setState('error')}},[service]);
  useEffect(()=>{void load()},[load]);
  if(state==='loading')return <section className="course-operations-monitor"><p role="status">{copy.loading}</p></section>;
  if(state==='error')return <section className="course-operations-monitor"><p role="alert">{copy.unavailable}</p><button onClick={()=>void load()}>{copy.retry}</button></section>;
  const counts=object(data.counts),checkpoint=object(data.checkpoint),configuration=object(data.configuration),lastRun=object(data.lastRun),progress=object(checkpoint.progress),quota=object(data.quota),receipt=object(data.lastCountReceipt),cursor=`${shown(checkpoint.pagePath)} · ${shown(checkpoint.clubOffset)}:${shown(checkpoint.courseOffset)}`;
  return <section className="course-operations-monitor" aria-labelledby="course-catalogue-status">
    <h3 id="course-catalogue-status">{copy.title}</h3>
    <p role="status">{copy.provider}: {configuration.providerRequestsAllowed===true?'enabled':'blocked'} · {copy.blocked}: {shown(configuration.blockedReason)} · {copy.project}: {shown(data.projectId)}</p>
    <dl className="quota">
      <div><dt>{copy.counts}</dt><dd>{shown(counts.canonical)} / {shown(counts.usable)}</dd></div><div><dt>{copy.identity}</dt><dd>{shown(counts.uniqueCourseIDs)} / {shown(counts.uniqueProviderCourseIds)} / {shown(counts.uniqueClubIDs)}</dd></div><div><dt>{copy.missing}</dt><dd>{shown(counts.missingCourseID)} / {shown(counts.missingProviderCourseId)} / {shown(counts.missingClubID)}</dd></div><div><dt>{copy.duplicates}</dt><dd>{shown(counts.duplicateProviderCourseIds)}</dd></div><div><dt>{copy.quarantine}</dt><dd>{shown(counts.quarantined)}</dd></div><div><dt>{copy.retries}</dt><dd>{shown(counts.pendingRetries)} / {shown(counts.deadLetters)}</dd></div><div><dt>{copy.progress}</dt><dd>{shown(progress.scanned)} / {shown(progress.created)} / {shown(progress.updated)}</dd></div><div><dt>{copy.unchanged}</dt><dd>{shown(progress.unchanged)} / {shown(progress.failed)}</dd></div><div><dt>{copy.remaining}</dt><dd>{shown(quota.providerReportedRemaining)}</dd></div><div><dt>{copy.evidence}</dt><dd>{when(quota.providerEvidenceAt)}</dd></div><div><dt>{copy.budget}</dt><dd>{shown(quota.configuredBudget)} / {shown(quota.emergencyReserve)}</dd></div><div><dt>{copy.freshness}</dt><dd>{FRESHNESS_COPY[locale]}</dd></div><div><dt>{copy.checkpoint}</dt><dd>{shown(checkpoint.state)} · {cursor}</dd></div><div><dt>{copy.runs}</dt><dd>{when(checkpoint.lastRunAt??lastRun.completedAt)} / {when(checkpoint.nextRunAt)}</dd></div><div><dt>{copy.receipt}</dt><dd>{shown(receipt.receiptId??receipt.id)} · {shown(receipt.receiptDigest)}</dd></div>
    </dl>
    <button onClick={()=>void load()}>{copy.refresh}</button>
  </section>;
}
