import { useEffect, useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../../../firebaseConfig';
import { DIRECTOR_POLICY_SEED_PREVIEW } from './economyPolicySeedPreview';
import './V2EconomyMaster.css';

type Policy = { id: string; policyVersion: string; state: string; purpose: string; amountTee: number | null; effectiveAt: string | null; effectiveTo: string | null; digest: string | null; createdAt: string | null; activatedAt: string | null };
type Lot = { lotId: string; liabilityClass: string; issuedQuantity: number | null; remainingQuantity: number | null; reservedQuantity: number | null; settledQuantity: number | null; releasedQuantity: number | null; expiredQuantity: number | null; issuedAt: string | null; expiresAt: string | null };
type Entry = { entryId: string; commandType: string; createdAt: string | null; policyVersion: string; debitTee: number | null; creditTee: number | null; balanced: boolean };
type Snapshot = { policies: Policy[]; policyHistory: Policy[]; teeLots: { status: 'available' | 'empty'; totals: { issued: number; remaining: number; reserved: number; settled: number; released: number; expired: number }; rows: Lot[] }; ledger: { entriesReviewed: number; debitTotalTee: number; creditTotalTee: number; balancedEntries: number; unbalancedEntries: number; pendingReconciliationCases: number; recentEntries: Entry[] }; countryUsage: { status: 'available' | 'unavailable'; rows: Array<{ countryCode: string; journalCount: number; teeVolume: number }>; reason?: string }; policyAudit: { status: 'available' | 'unavailable'; entries: Array<{ id: string; policyVersion: string; actionType: string; reason: string | null; createdAt: string | null; diffHash: string | null }>; reason?: string } };
const missing = 'Not recorded';

export default function V2EconomyMaster({ isDirector }: { isDirector: boolean }) {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'denied' | 'unavailable'>('loading');
  useEffect(() => { if (!isDirector) { setState('denied'); return; } void (async () => { try { const result = await httpsCallable<unknown, Snapshot>(functions, 'getV2EconomyMasterSnapshot')({}); setSnapshot(result.data); setState('ready'); } catch (error: unknown) { setState((error as { code?: string }).code === 'functions/permission-denied' ? 'denied' : 'unavailable'); } })(); }, [isDirector]);
  if (state === 'loading') return <section className="economy-master-state" role="status">Loading Director-only Economy data…</section>;
  if (state === 'denied') return <section className="economy-master-state is-denied" role="alert"><h2>Director authority required</h2><p>This read-only Economy Master is server-gated to an active Director.</p></section>;
  if (state === 'unavailable' || !snapshot) return <PolicyPreview sourceUnavailable />;
  return <div className="economy-master">
    <header><div><span>DIRECTOR · SERVER READ-ONLY</span><h2>Economy Master / Ledger</h2><p>Canonical V2 data is read only. This screen cannot create policy, issue Tee, settle, release, or change a price.</p></div></header>
    <PolicyPreview />
    <section className="economy-master-card"><h3>Active policy</h3>{snapshot.policies.length ? <table><thead><tr><th>Version</th><th>Purpose</th><th>Amount</th><th>Effective</th><th>Digest</th></tr></thead><tbody>{snapshot.policies.map((p) => <tr key={p.id}><td><code>{p.policyVersion}</code></td><td>{p.purpose}</td><td>{p.amountTee === null ? missing : `${p.amountTee} Tee`}</td><td>{p.effectiveAt ?? missing} → {p.effectiveTo ?? 'open'}</td><td><code>{p.digest ?? missing}</code></td></tr>)}</tbody></table> : <p className="economy-empty">No active canonical policy record is available.</p>}</section>
    <section className="economy-master-card"><h3>Immutable policy history</h3>{snapshot.policyHistory.length ? <table><thead><tr><th>Version</th><th>State</th><th>Created</th><th>Activated</th><th>Digest</th></tr></thead><tbody>{snapshot.policyHistory.map((p) => <tr key={p.id}><td><code>{p.policyVersion}</code></td><td>{p.state}</td><td>{p.createdAt ?? missing}</td><td>{p.activatedAt ?? missing}</td><td><code>{p.digest ?? missing}</code></td></tr>)}</tbody></table> : <p className="economy-empty">No immutable policy history is available.</p>}</section>
    <section className="economy-master-card"><h3>Action matrix — unapproved proposal</h3><table><thead><tr><th>Action</th><th>Amount</th><th>Lifecycle</th><th>Status</th></tr></thead><tbody>{DIRECTOR_POLICY_SEED_PREVIEW.actions.map((a) => <tr key={a.actionId}><td><code>{a.actionId}</code></td><td>{a.amountTee} Tee</td><td>{a.direction === 'earn' ? 'Earn' : a.direction === 'spend' ? 'Immediate settle' : 'Reserve / settle / release'}</td><td>Unapproved preview</td></tr>)}</tbody></table></section>
    <section className="economy-master-card"><h3>Tee lots</h3>{snapshot.teeLots.status === 'empty' ? <p className="economy-empty">No canonical Tee lots are available. No balances are inferred.</p> : <><div className="economy-ledger-summary">{Object.entries(snapshot.teeLots.totals).map(([k, v]) => <span key={k}>{k} <b>{v}</b></span>)}</div><table><thead><tr><th>Lot</th><th>Class</th><th>Issued</th><th>Reserved</th><th>Settled</th><th>Released</th><th>Expired</th></tr></thead><tbody>{snapshot.teeLots.rows.map((lot) => <tr key={lot.lotId}><td><code>{lot.lotId}</code></td><td>{lot.liabilityClass}</td><td>{lot.issuedQuantity ?? missing}</td><td>{lot.reservedQuantity ?? missing}</td><td>{lot.settledQuantity ?? missing}</td><td>{lot.releasedQuantity ?? missing}</td><td>{lot.expiredQuantity ?? missing}</td></tr>)}</tbody></table></>}</section>
    <section className="economy-master-card"><h3>Ledger reconciliation</h3>{snapshot.ledger.entriesReviewed ? <><div className="economy-ledger-summary"><span>Debit <b>{snapshot.ledger.debitTotalTee}</b></span><span>Credit <b>{snapshot.ledger.creditTotalTee}</b></span><span>Balanced <b>{snapshot.ledger.balancedEntries}</b></span><span>Exceptions <b>{snapshot.ledger.unbalancedEntries}</b></span><span>Pending cases <b>{snapshot.ledger.pendingReconciliationCases}</b></span></div><table><thead><tr><th>Entry</th><th>Action</th><th>Created</th><th>Debit</th><th>Credit</th><th>State</th></tr></thead><tbody>{snapshot.ledger.recentEntries.map((e) => <tr key={e.entryId}><td><code>{e.entryId}</code></td><td>{e.commandType}</td><td>{e.createdAt ?? missing}</td><td>{e.debitTee ?? missing}</td><td>{e.creditTee ?? missing}</td><td>{e.balanced ? 'Balanced' : 'Exception'}</td></tr>)}</tbody></table></> : <p className="economy-empty">No canonical journal entries are available. No ledger balance is fabricated.</p>}</section>
    <section className="economy-master-grid"><article className="economy-master-card"><h3>Country reporting</h3>{snapshot.countryUsage.status === 'available' ? <table><thead><tr><th>Country</th><th>Journals</th><th>Tee volume</th></tr></thead><tbody>{snapshot.countryUsage.rows.map((r) => <tr key={r.countryCode}><td>{r.countryCode}</td><td>{r.journalCount}</td><td>{r.teeVolume}</td></tr>)}</tbody></table> : <p className="economy-empty">Unavailable: {snapshot.countryUsage.reason}</p>}</article><article className="economy-master-card"><h3>Immutable policy-change audit</h3>{snapshot.policyAudit.status === 'available' ? <table><thead><tr><th>Policy</th><th>Action</th><th>Created</th></tr></thead><tbody>{snapshot.policyAudit.entries.map((a) => <tr key={a.id}><td><code>{a.policyVersion}</code></td><td>{a.actionType}</td><td>{a.createdAt ?? missing}</td></tr>)}</tbody></table> : <p className="economy-empty">{snapshot.policyAudit.reason}</p>}</article></section>
  </div>;
}

function PolicyPreview({ sourceUnavailable = false }: { sourceUnavailable?: boolean }) { const p = DIRECTOR_POLICY_SEED_PREVIEW; return <section className="economy-master-card"><h3>Current unapproved policy proposal</h3>{sourceUnavailable && <p className="economy-empty">Canonical read is unavailable; this committed preview makes no claim about financial records.</p>}<p className="economy-empty">$0.10 USD per Tee · <code>{p.policyVersion}</code><br />Digest <code>{p.policyDigestSha256}</code><br />Proposed document <code>{p.documentId}</code></p><p className="economy-empty">Packs: {p.teePacks.map((pack) => `${pack.teeCount} Tee / $${pack.priceUsd}`).join(' · ')}. Promotional Tee expires after {p.lotRules.promotionalTtlDays} days and is consumed first.</p><p className="economy-empty">Director approval is required. This preview creates no policy, balance, lot, journal, settlement, reconciliation, or audit record.</p></section>; }
