import {useCallback,useEffect,useRef,useState} from 'react';
import {useAdminLocale} from './AdminLocaleContext';
import {ENTERPRISE_MEMBER_ADMIN_COPY} from '../../../i18n/admin/enterpriseMemberRequests';
import {firebaseEnterpriseMemberAdminProvider,newAdminCommandId,type AdminMemberDecision,type EnterpriseMemberAdminProvider,type MemberRequestDetail,type MemberRequestProjection} from './enterpriseMemberRequestsProvider';
import './V2EnterpriseMemberRequests.css';
import {useDialogFocus} from './useDialogFocus';

const decisions:AdminMemberDecision[]=['approve_delivery','request_correction','reject','mark_duplicate','link_existing','escalate_identity_consent','cancel_before_delivery'];
const decisionKey:Record<AdminMemberDecision,'approveDelivery'|'requestCorrection'|'reject'|'duplicate'|'linkExisting'|'escalate'|'cancelDelivery'>={approve_delivery:'approveDelivery',request_correction:'requestCorrection',reject:'reject',mark_duplicate:'duplicate',link_existing:'linkExisting',escalate_identity_consent:'escalate',cancel_before_delivery:'cancelDelivery'};
const digest=(request:MemberRequestProjection)=>request.evidenceReferences?.map(item=>item.digest).sort().join('.')||'none';
const FILTER_STATUSES=['awaiting_delivery_provider','change_requested','conflict_review','unavailable','stale','submitted','cancelled','resolved'];
const FILTER_ACTIONS=['invitation','resend','deactivate','reactivate','role_change','csv_import','support'];

export default function V2EnterpriseMemberRequests({provider=firebaseEnterpriseMemberAdminProvider}:{provider?:EnterpriseMemberAdminProvider}){
 const locale=useAdminLocale(),t=ENTERPRISE_MEMBER_ADMIN_COPY[locale],[rows,setRows]=useState<MemberRequestProjection[]>([]),[state,setState]=useState<'loading'|'ready'|'stale'|'offline'|'error'>('loading'),[selected,setSelected]=useState<MemberRequestDetail|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[action,setAction]=useState(''),[cursor,setCursor]=useState<string|undefined>(),[cursors,setCursors]=useState<Array<string|undefined>>([]),[next,setNext]=useState<string|undefined>();
 const load=useCallback(async()=>{setState('loading');try{const filter=Object.fromEntries(Object.entries({status,action,search:query.trim()}).filter(([,v])=>v));const result=await provider.list({filter,limit:25,cursor});setRows(result.requests);setNext(result.nextCursor);setState(result.stale?'stale':'ready')}catch(error){setState(typeof navigator!=='undefined'&&!navigator.onLine?'offline':'error')}},[provider,status,action,query,cursor]);
 useEffect(()=>{void load()},[load]);
 const open=async(row:MemberRequestProjection)=>{setBusy(true);setNotice('');try{setSelected(await provider.detail(row.requestId))}catch{setNotice(t.failed)}finally{setBusy(false)}};
 const run=async(task:()=>Promise<unknown>)=>{setBusy(true);setNotice('');try{await task();if(selected)setSelected(await provider.detail(selected.request.requestId));await load();setNotice(t.announcement)}catch{setNotice(t.failed)}finally{setBusy(false)}};
 return <section className="emr" aria-labelledby="emr-title"><header><div><h2 id="emr-title">{t.title}</h2><p>{t.lead}</p><p className="emr-boundary">{t.noInternal}</p></div><button type="button" onClick={()=>void load()} disabled={state==='loading'}>{t.refresh}</button></header>
  <form className="emr-filters" role="search" onSubmit={event=>{event.preventDefault();setCursor(undefined);setCursors([]);void load()}}><label>{t.search}<input value={query} maxLength={96} onChange={e=>setQuery(e.target.value)}/></label><label>{t.status}<select value={status} onChange={e=>{setStatus(e.target.value);setCursor(undefined)}}><option value="">{t.all}</option>{FILTER_STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><label>{t.action}<select value={action} onChange={e=>{setAction(e.target.value);setCursor(undefined)}}><option value="">{t.all}</option>{FILTER_ACTIONS.map(value=><option key={value}>{value}</option>)}</select></label><button type="submit">{t.search}</button></form>
  <div role="status" aria-live="polite">{state==='loading'&&t.loading}{notice}</div>{['error','offline','stale'].includes(state)&&<div role="alert"><p>{state==='offline'?t.offline:state==='stale'?t.stale:t.unavailable}</p><button onClick={()=>void load()}>{t.retry}</button></div>}{state==='ready'&&rows.length===0&&<p>{t.empty}</p>}
  {state==='ready'&&rows.length>0&&<div className="emr-table-scroll" tabIndex={0} aria-label={t.title}><table><thead><tr><th scope="col">{t.organization}</th><th scope="col">{t.course}</th><th scope="col">{t.action}</th><th scope="col">{t.status}</th><th scope="col">{t.locale}</th><th scope="col"><span className="emr-sr">{t.details}</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.requestId}><td>{row.organizationLabel}<small>{row.organizationId}</small></td><td>{row.courseLabel}<small>{row.courseId}</small></td><td>{row.action}</td><td><span className="emr-pill">{row.status}</span></td><td>{row.locale}</td><td><button type="button" onClick={()=>void open(row)}>{t.select}</button></td></tr>)}</tbody></table></div>}
  <nav className="emr-pages" aria-label="Pagination"><button disabled={!cursors.length} onClick={()=>{const history=[...cursors],prior=history.pop();setCursors(history);setCursor(prior)}}>{t.previous}</button><button disabled={!next} onClick={()=>{setCursors(items=>[...items,cursor]);setCursor(next)}}>{t.next}</button></nav>
  {selected&&<RequestDetail detail={selected} busy={busy} close={()=>setSelected(null)} run={run} provider={provider}/>}</section>
}

function RequestDetail({detail,busy,close,run,provider}:{detail:MemberRequestDetail;busy:boolean;close:()=>void;run:(task:()=>Promise<unknown>)=>Promise<void>;provider:EnterpriseMemberAdminProvider}){
 const request=detail.request;
 const dialogRef=useDialogFocus(true,close);
 const commands=useRef({decision:newAdminCommandId(),delivery:newAdminCommandId()});
 useEffect(()=>{commands.current={decision:newAdminCommandId(),delivery:newAdminCommandId()}},[request.version]);
 const locale=useAdminLocale(),t=ENTERPRISE_MEMBER_ADMIN_COPY[locale],[decision,setDecision]=useState<AdminMemberDecision>('request_correction'),[confirmed,setConfirmed]=useState(false),[deliveryConfirmed,setDeliveryConfirmed]=useState(false),[reason,setReason]=useState(''),[existing,setExisting]=useState(''),[channel,setChannel]=useState<'email'|'sms'|'push'>('email'),[template,setTemplate]=useState('enterprise_member_invitation'),templateVersion='v1',legalBasis='enterprise_member_invitation_v1';
 const submit=(event:React.FormEvent)=>{event.preventDefault();if(!confirmed)return;void run(()=>provider.decide({commandId:commands.current.decision,requestId:request.requestId,expectedVersion:request.version,decision,reason:reason||undefined,existingMemberReference:existing||undefined,policyVersion:'enterprise-member-admin-v1',evidenceDigest:digest(request)}));setConfirmed(false)};
 return <div className="emr-dialog-backdrop"><section ref={dialogRef} className="emr-dialog" role="dialog" aria-modal="true" aria-labelledby="emr-detail-title"><header><h3 id="emr-detail-title">{t.details}: {request.requestId}</h3><button onClick={close} aria-label={t.close}>×</button></header><dl><div><dt>{t.organization}</dt><dd>{request.organizationLabel} · {request.organizationId}</dd></div><div><dt>{t.course}</dt><dd>{request.courseLabel} · {request.courseId}</dd></div><div><dt>{t.status}</dt><dd>{request.status} · v{request.version}</dd></div><div><dt>{t.locale}</dt><dd>{request.locale}</dd></div></dl>
  <section aria-labelledby="emr-history"><h4 id="emr-history">{t.history}</h4><ol>{detail.history.map(item=><li key={item.receiptId}><time>{item.at}</time> — {item.actorType}: {item.action} → {item.status} <code>{item.receiptId}</code></li>)}</ol></section>
  <section aria-labelledby="emr-consent"><h4 id="emr-consent">{t.consent}</h4><p>{detail.consent?.status||'unavailable'} · {detail.lifecycle?.status||'unavailable'}</p></section>
  <form onSubmit={submit}><h4>{t.decision}</h4><label>{t.decision}<select value={decision} onChange={e=>setDecision(e.target.value as AdminMemberDecision)}>{decisions.map(value=><option key={value} value={value}>{t[decisionKey[value]]}</option>)}</select></label><label>{t.reason}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{['mark_duplicate','link_existing'].includes(decision)&&<label>{t.existing}<input required maxLength={128} value={existing} onChange={e=>setExisting(e.target.value)}/></label>}<label className="emr-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t.confirm}</label><button disabled={busy||!confirmed}>{t.submit}</button></form>
  {detail.csv&&<CsvResolution detail={detail} busy={busy} run={run} provider={provider}/>}<form onSubmit={event=>{event.preventDefault();if(!deliveryConfirmed)return;void run(()=>provider.prepareDelivery({commandId:commands.current.delivery,requestId:request.requestId,expectedVersion:request.version,channel,templateId:template,templateVersion,locale:request.locale,legalBasisReference:legalBasis}));setDeliveryConfirmed(false)}}><h4>{t.delivery}</h4><p>{t.providerPending}</p><label>{t.channel}<select value={channel} onChange={e=>setChannel(e.target.value as typeof channel)}><option>email</option><option>sms</option><option>push</option></select></label><label>{t.template}<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="enterprise_member_invitation">enterprise_member_invitation</option><option value="enterprise_member_resend">enterprise_member_resend</option><option value="enterprise_member_correction">enterprise_member_correction</option><option value="enterprise_member_rejected">enterprise_member_rejected</option><option value="enterprise_member_expired">enterprise_member_expired</option><option value="enterprise_member_support_response">enterprise_member_support_response</option></select></label><label>{t.templateVersion}<output>{templateVersion}</output></label><label>{t.legalBasis}<output>{legalBasis}</output></label><label className="emr-confirm"><input type="checkbox" checked={deliveryConfirmed} onChange={e=>setDeliveryConfirmed(e.target.checked)}/>{t.confirm}</label><button disabled={busy||!deliveryConfirmed}>{t.prepare}</button></form>{detail.delivery&&<p>{t.outbox}: {detail.delivery.providerState}, {detail.delivery.attempts}/{detail.delivery.maxAttempts}</p>}</section></div>
}
function CsvResolution({detail,busy,run,provider}:{detail:MemberRequestDetail;busy:boolean;run:(task:()=>Promise<unknown>)=>Promise<void>;provider:EnterpriseMemberAdminProvider}){const t=ENTERPRISE_MEMBER_ADMIN_COPY[useAdminLocale()],csv=detail.csv!,command=useRef(newAdminCommandId()),[confirmed,setConfirmed]=useState(false),[resolutions,setResolutions]=useState<Record<number,'approve_delivery'|'mark_duplicate'|'reject'>>({});useEffect(()=>{command.current=newAdminCommandId()},[detail.request.version]);return <form onSubmit={event=>{event.preventDefault();if(!confirmed)return;void run(()=>provider.resolveCsv({commandId:command.current,requestId:detail.request.requestId,expectedVersion:detail.request.version,previewId:csv.previewId,rowDigest:csv.rowDigest,policyVersion:'enterprise-member-admin-v1',resolutions:Object.entries(resolutions).map(([row,decision])=>({row:Number(row),decision}))}))}}><h4>{t.conflicts}</h4>{csv.rows.map(row=><label key={row.row}>#{row.row} {row.memberReference} · {row.conflict||row.status}<select value={resolutions[row.row]||''} onChange={e=>setResolutions(current=>({...current,[row.row]:e.target.value as typeof resolutions[number]}))}><option value="">—</option><option value="approve_delivery">{t.approveDelivery}</option><option value="mark_duplicate">{t.duplicate}</option><option value="reject">{t.reject}</option></select></label>)}<label className="emr-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t.confirm}</label><button disabled={busy||!confirmed||!Object.keys(resolutions).length}>{t.resolveRows}</button></form>}
