import { useContext, useEffect, useState } from 'react';
import { AdminIdentityContext } from './AdminIdentityContext';
import type { CourseOperationsService } from './courseOperationsService';

const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'?value as Record<string,unknown>:{};
const shown=(value:unknown)=>value===null||value===undefined||value===''?'—':String(value);

export default function V2KoreaDownloadControl({service}:{service:CourseOperationsService}){
  const identity=useContext(AdminIdentityContext),[state,setState]=useState<'idle'|'running'|'error'|'complete'>('idle'),[result,setResult]=useState<Record<string,unknown>>({}),[projection,setProjection]=useState<Record<string,unknown>>({});
  const director=identity.role==='Director'&&identity.status?.trim().toLowerCase()==='active',attested=identity.appCheck===true,online=identity.online!==false,allowed=director&&attested&&online;
  const blocked=!director?'Active Director access is required.':!attested?'V2 App Check attestation is unavailable.':!online?'Connection is unavailable.':null;
  const cutover=object(projection.cutover),cutoverStarted=cutover.state==='active';
  useEffect(()=>{let live=true;void service.loadCountryIngestionProjection().then(value=>{if(!live)return;setProjection(value);const current=object(value.cutover);if(current.state==='active'){setResult({cutoverReceiptId:current.receiptId,currentCountry:'KOREA',nextCountry:'JAPAN',state:'blocked',reason:'PROVIDER_REQUESTS_DISABLED',providerCalls:0,courseWrites:0});setState('complete');}}).catch(()=>{});return()=>{live=false;};},[service]);
  const run=async()=>{if(!allowed||state==='running'||cutoverStarted)return;setState('running');setResult({});try{const command=await service.startGlobalCatalogueCutover();setResult(command);setProjection(await service.loadCountryIngestionProjection());setState('complete');}catch{try{const authoritative=await service.loadCountryIngestionProjection(),current=object(authoritative.cutover);setProjection(authoritative);if(current.state==='active'){setResult({cutoverReceiptId:current.receiptId,currentCountry:'KOREA',nextCountry:'JAPAN',state:'blocked',reason:'PROVIDER_REQUESTS_DISABLED',providerCalls:0,courseWrites:0});setState('complete');return;}}catch{}setState('error');}};
  const counts=object(result.counts),quota=object(projection.quota),receipts=Array.isArray(projection.receipts)?projection.receipts.map(object):[],jobs=Array.isArray(projection.jobs)?projection.jobs.map(object):[],receipt=receipts.find(item=>item.country==='KOREA')||{},next=jobs.filter(item=>item.country!=='KOREA'&&['queued','paused','running'].includes(String(item.state))).sort((left,right)=>Number(left.nextDueAtMs||Number.MAX_SAFE_INTEGER)-Number(right.nextDueAtMs||Number.MAX_SAFE_INTEGER))[0]||{};
  return <section className="course-korea-download" aria-labelledby="korea-download-title"><span>DIRECTOR-ONLY SERVER COMMAND</span><h3 id="korea-download-title">Start global catalogue cutover</h3><p>One V2 App Check-protected command retires legacy jobs, records the immutable cutover receipt, creates the receipt-bound queue, and starts bounded Korea work. The browser never contacts the provider directly.</p><button className="primary" disabled={!allowed||state==='running'||cutoverStarted} onClick={()=>void run()}>{state==='running'?'Starting global catalogue cutover…':cutoverStarted?'Global catalogue cutover active':'Start global catalogue cutover'}</button>{blocked&&<p role="status">{blocked}</p>}{state==='error'&&<p role="alert">The command result is unavailable. No completion is assumed; refresh the authoritative receipt-bound queue before retrying.</p>}{state==='complete'&&<><dl><div><dt>Receipt ID</dt><dd>{shown(result.cutoverReceiptId??receipt.receiptId??receipt.id)}</dd></div><div><dt>Current country</dt><dd>{shown(result.currentCountry??result.country??receipt.country)}</dd></div><div><dt>Added / updated</dt><dd>{shown(counts.added??receipt.added)} / {shown(counts.updated??receipt.updated)}</dd></div><div><dt>Provider calls</dt><dd>{shown(result.providerCalls??receipt.providerCalls)}</dd></div><div><dt>Quota remaining</dt><dd>{shown(quota.providerReportedRemaining)}</dd></div><div><dt>Next country</dt><dd>{shown(result.nextCountry??next.country)}</dd></div></dl>{result.state==='blocked'&&<p role="status">Korea is queued behind the immutable cutover receipt. Provider access remains blocked; no provider call or course write was attempted.</p>}</>}</section>;
}
