import { useEffect, useMemo, useState } from 'react';
import { filterMarketingAssets, marketingSummary, MARKETING_CATEGORIES, MARKETING_LOCALES, MARKETING_STATUSES, storeReadiness, type MarketingAsset } from './marketingLibraryModel.mjs';
import { localPreviewMarketingProvider, type MarketingLibraryProvider, type MarketingLibrarySnapshot } from './marketingLibraryProvider';
import MarketingSections from './MarketingSections';
import './V2MarketingLibrary.css';
import { useDialogFocus } from './useDialogFocus';

const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export default function V2MarketingLibrary({provider=localPreviewMarketingProvider}:{provider?:MarketingLibraryProvider}){
  const [snapshot,setSnapshot]=useState<MarketingLibrarySnapshot|null>(null);const [loadError,setLoadError]=useState(false);const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [status,setStatus]=useState('all');const [locale,setLocale]=useState('all');const [selected,setSelected]=useState<MarketingAsset|null>(null);const [copied,setCopied]=useState(false);
  const detailRef=useDialogFocus(Boolean(selected),()=>setSelected(null));
  useEffect(()=>{void provider.load().then(setSnapshot,()=>setLoadError(true));},[provider]);
  const assets=useMemo(()=>snapshot?.assets||[],[snapshot]);const summary=useMemo(()=>marketingSummary(assets),[assets]);const visible=useMemo(()=>filterMarketingAssets(assets,{query,category,status,locale}),[assets,query,category,status,locale]);const readiness=useMemo(()=>storeReadiness(assets),[assets]);
  const copyText=async(asset:MarketingAsset)=>{if(asset.previewKind!=='text'||!asset.previewText)return;await navigator.clipboard.writeText(asset.previewText);setCopied(true);};
  const printAsset=(asset:MarketingAsset)=>{if(asset.previewKind==='text'&&asset.previewText)window.print();};
  const download=async(asset:MarketingAsset)=>{if(snapshot?.downloadAdapter&&asset.downloadApproved)await snapshot.downloadAdapter(asset);};
  if(loadError)return <div className="marketing-state is-error" role="alert">Marketing catalogue could not be loaded. No inventory claims are available.</div>;
  if(!snapshot)return <div className="marketing-state" role="status">Loading marketing library…</div>;
  return <div className="marketing-library">
    <header className="marketing-hero"><div><span>ADMIN · READ-ONLY LIBRARY</span><h2>Marketing asset operations</h2><p>Central review for launch, outreach, store and partner resources—without publishing or write authority.</p></div><aside><strong>{snapshot.source==='local-preview'?'Local preview catalogue':'Trusted production catalogue'}</strong><small>{snapshot.source==='local-preview'?'Real repository assets plus clearly unavailable placeholders. No production inventory is asserted.':'Catalogue supplied by an injected trusted provider.'}</small></aside></header>
    <MarketingSections assets={assets}/><section className="marketing-metrics" aria-label="Marketing overview"><article><span>Total resources</span><strong>{summary.total}</strong></article>{MARKETING_STATUSES.map((item)=><article key={item}><span>{label(item)}</span><strong>{summary.byStatus[item]}</strong></article>)}<article className={summary.missingLaunch.length?'warn':''}><span>Missing launch materials</span><strong>{summary.missingLaunch.length}</strong></article></section>
    <section className="marketing-coverage"><div><span>LOCALE COVERAGE · AVAILABLE ASSETS ONLY</span><h3>Eight-locale contract</h3></div>{MARKETING_LOCALES.map((item)=><article key={item}><strong>{item}</strong><span>{summary.coverage[item]} available</span></article>)}</section>
    <section className="marketing-layout"><div className="marketing-catalogue"><div className="marketing-toolbar"><input aria-label="Search marketing assets" placeholder="Search title, owner or channel" value={query} onChange={(e)=>setQuery(e.target.value)}/><select aria-label="Category filter" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="all">All categories</option>{MARKETING_CATEGORIES.map((item)=><option key={item} value={item}>{label(item)}</option>)}</select><select aria-label="Status filter" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">All states</option>{MARKETING_STATUSES.map((item)=><option key={item}>{item}</option>)}</select><select aria-label="Locale filter" value={locale} onChange={(e)=>setLocale(e.target.value)}><option value="all">All locales</option>{MARKETING_LOCALES.map((item)=><option key={item}>{item}</option>)}</select></div>
      {visible.length===0?<div className="marketing-state">No resources match these filters.</div>:<div className="marketing-table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>Locale</th><th>Format</th><th>Status</th><th>Version</th><th>Updated</th><th>Owner / source</th><th>Channel</th></tr></thead><tbody>{visible.map((asset)=><tr key={asset.id} onClick={()=>{setSelected(asset);setCopied(false);}} tabIndex={0} onKeyDown={(event)=>{if(event.key==='Enter')setSelected(asset);}}><td><strong>{asset.title}</strong></td><td>{label(asset.category)}</td><td>{asset.locales.length?asset.locales.join(', '):'None verified'}</td><td>{asset.format}</td><td><span className={`asset-status is-${asset.status}`}>{asset.status}</span></td><td>{asset.version}</td><td>{asset.updatedAt||'Unknown'}</td><td>{asset.owner}<small>{asset.provenance}</small></td><td>{asset.channel}</td></tr>)}</tbody></table></div>}</div>
      <aside className="marketing-side"><span>STORE READINESS</span><h3>Actual evidence only</h3>{readiness.map((item)=><div className="readiness-row" key={item.key}><b aria-label={item.ready?'available':'missing'}>{item.ready?'✓':'—'}</b><span>{item.label}<small>{item.evidence||'No verified asset'}</small></span></div>)}<div className="locale-readiness"><strong>Locale coverage</strong><p>{MARKETING_LOCALES.map((item)=>`${item}: ${summary.coverage[item]}`).join(' · ')}</p></div><p className="upload-note">Admin upload coming after storage approval.</p></aside></section>
    <section className="recent-resources"><span>RECENTLY UPDATED · VERIFIED DATES</span>{summary.recent.map((asset)=><button key={asset.id} onClick={()=>setSelected(asset)}><strong>{asset.title}</strong><small>{asset.updatedAt}</small></button>)}</section>
    {selected&&<div ref={detailRef} className="asset-detail" role="dialog" aria-modal="true" aria-label="Marketing asset detail"><button className="asset-close" onClick={()=>setSelected(null)}>Close</button><span>{label(selected.category)}</span><h3>{selected.title}</h3>{selected.previewKind==='image'&&selected.sourceUrl?<img src={selected.sourceUrl} alt={`Preview of ${selected.title}`}/>:selected.previewKind==='text'&&selected.previewText?<div className="text-preview">{selected.previewText}</div>:<div className="unsupported-state"><strong>Preview unavailable</strong><p>{selected.available?'This file format is not supported for safe inline preview.':'The source file or approved storage location is missing.'}</p></div>}<dl><div><dt>Version</dt><dd>{selected.version}</dd></div><div><dt>Provenance</dt><dd>{selected.provenance}</dd></div><div><dt>Locales</dt><dd>{selected.locales.length?selected.locales.join(', '):'None verified'}</dd></div><div><dt>Approval</dt><dd>{selected.approval}</dd></div><div><dt>Disclosure requirements</dt><dd>{selected.disclosures.length?selected.disclosures.join('; '):'None recorded—requires review'}</dd></div></dl><div className="asset-actions"><button disabled={selected.previewKind!=='text'||!selected.previewText} onClick={()=>void copyText(selected)}>{copied?'Copied':'Copy text'}</button><button disabled={selected.previewKind!=='text'||!selected.previewText} onClick={()=>printAsset(selected)}>Print letter</button><button disabled={!snapshot.downloadAdapter||!selected.downloadApproved} onClick={()=>void download(selected)}>Download / export</button></div>{!snapshot.downloadAdapter&&<p className="adapter-note">Download unavailable: no approved export adapter is configured.</p>}</div>}
  </div>;
}
