import {useRef,useState} from 'react';
import {useLocale} from '../../../i18n/hooks';
import {SMALL_BUSINESS_COPY} from '../../../i18n/smallBusiness';
import {smallBusinessLabel} from '../../../i18n/smallBusinessLabels';
import {commandId} from '../../smallBusiness/smallBusinessModel';
import {firebaseSmallBusinessProvider,type SmallBusinessProvider} from '../../smallBusiness/smallBusinessProvider';
import '../../smallBusiness/smallBusiness.css';
const promotionDecisions=['approve','request_changes','retire','publish'] as const;
export default function V2SmallBusinessReadiness({provider=firebaseSmallBusinessProvider}:{provider?:SmallBusinessProvider}){
 const locale=useLocale(),t=SMALL_BUSINESS_COPY[locale],[businessId,setBusinessId]=useState(''),[detail,setDetail]=useState<any>(),[correction,setCorrection]=useState<any>(),[correctionDecision,setCorrectionDecision]=useState<'approve'|'request_changes'|'reject'>('request_changes'),[correctionReason,setCorrectionReason]=useState(''),[promotionId,setPromotionId]=useState(''),[promotionVersion,setPromotionVersion]=useState(0),[promotionDecision,setPromotionDecision]=useState<typeof promotionDecisions[number]>('approve'),[report,setReport]=useState<any>(),[jhcc,setJhcc]=useState<any>(),[batchId,setBatchId]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),detailGeneration=useRef(0),promotionCommand=useRef(commandId('sb_promotion_review')),correctionCommand=useRef(commandId('sb_correction_review'));
 const fail=()=>setMessage(t.unavailable);
 const loadDetail=async()=>{const generation=++detailGeneration.current;try{const [next,nextCorrection]=await Promise.all([provider.adminDetail(businessId),provider.adminCorrection(businessId).catch(()=>null)]);if(generation===detailGeneration.current){setDetail(next);setCorrection(nextCorrection)}}catch{if(generation===detailGeneration.current)fail()}};
 const review=async()=>{if(confirm!=='promotion')return;try{await provider.reviewPromotion({commandId:promotionCommand.current,promotionId,expectedVersion:promotionVersion,decision:promotionDecision});promotionCommand.current=commandId('sb_promotion_review');setConfirm('');setMessage(t.refresh)}catch{fail()}};
 return <section className="sb-card"><h2>{t.adminTitle} · {t.evidence} · {t.promotions}</h2><div role={message===t.unavailable?'alert':'status'} aria-live="polite">{message}</div>
  <form onSubmit={event=>{event.preventDefault();void loadDetail()}}><label>{t.profile}<input required value={businessId} onChange={event=>setBusinessId(event.target.value)}/></label><button>{t.refresh}</button></form>
  {detail&&<article><h3>{detail.business.displayName}</h3><p>{smallBusinessLabel(locale,detail.business.status)} · v{detail.business.version}</p><h4>{t.evidence}</h4><ul>{detail.evidenceReferences.map((item:any)=><li key={item.evidenceId}>{smallBusinessLabel(locale,'evidenceKind')}: {item.kind} · {smallBusinessLabel(locale,'objectReference')}: {item.objectReference} · {smallBusinessLabel(locale,'contentDigest')}: {item.contentDigest}</li>)}</ul><h4>{t.history}</h4><ol>{detail.history.map((item:any)=><li key={item.receiptId}>{item.occurredAt} · {smallBusinessLabel(locale,item.action)} · {smallBusinessLabel(locale,item.status)} · v{item.version}</li>)}</ol><p>{t.noContact} ({detail.representativeRef}).</p></article>}
  {correction&&<form onSubmit={event=>{event.preventDefault();if(confirm!=='correction')return;void provider.decideCorrection({commandId:correctionCommand.current,businessId,expectedVersion:correction.correction.version,decision:correctionDecision,reason:correctionReason}).then(async()=>{correctionCommand.current=commandId('sb_correction_review');setConfirm('');setCorrectionReason('');setMessage(t.refresh);await loadDetail()}).catch(fail)}}><h3>{t.profile} · {smallBusinessLabel(locale,correction.correction.status)}</h3><p>{t.history}: v{correction.canonical.businessVersion}</p><label>{t.decision}<select value={correctionDecision} onChange={event=>{setCorrectionDecision(event.target.value as typeof correctionDecision);setConfirm('')}}><option value="approve">{smallBusinessLabel(locale,'approve')}</option><option value="request_changes">{smallBusinessLabel(locale,'request_changes')}</option><option value="reject">{smallBusinessLabel(locale,'reject')}</option></select></label><label>{t.reason}<textarea required minLength={4} maxLength={1000} value={correctionReason} onChange={event=>setCorrectionReason(event.target.value)}/></label><label className="sb-confirm"><input type="checkbox" checked={confirm==='correction'} onChange={event=>setConfirm(event.target.checked?'correction':'')}/>{t.confirm}</label><button disabled={confirm!=='correction'||correctionReason.trim().length<4}>{t.apply}</button></form>}
  <form onSubmit={event=>{event.preventDefault();void review()}}><h3>{t.promotions}</h3><label>{smallBusinessLabel(locale,'promotionId')}<input required value={promotionId} onChange={event=>setPromotionId(event.target.value)}/></label><label>{smallBusinessLabel(locale,'promotionVersion')}<input type="number" min="0" required value={promotionVersion} onChange={event=>setPromotionVersion(Number(event.target.value))}/></label><label>{t.decision}<select value={promotionDecision} onChange={event=>{setPromotionDecision(event.target.value as typeof promotionDecision);setConfirm('')}}>{promotionDecisions.map(value=><option key={value} value={value}>{smallBusinessLabel(locale,value)}</option>)}</select></label><p>{t.promotionBoundary}</p><label className="sb-confirm"><input type="checkbox" checked={confirm==='promotion'} onChange={event=>setConfirm(event.target.checked?'promotion':'')}/>{t.confirm}</label><button disabled={confirm!=='promotion'}>{t.apply}</button></form>
  <section><h3>{smallBusinessLabel(locale,'reporting')}</h3><button onClick={()=>void provider.reporting().then(setReport).catch(fail)}>{t.refresh}</button>{report&&<dl>{Object.entries(report.totals).map(([key,value])=><div key={key}><dt>{smallBusinessLabel(locale,key)}</dt><dd>{String(value)}</dd></div>)}</dl>}</section>
  <form onSubmit={event=>{event.preventDefault();if(confirm!=='jhcc')return;void provider.prepareJhcc(batchId).then(setJhcc).catch(fail)}}><h3>{smallBusinessLabel(locale,'reporting')}</h3><label>{smallBusinessLabel(locale,'jhccBatchId')}<input required value={batchId} onChange={event=>setBatchId(event.target.value)}/></label><label className="sb-confirm"><input type="checkbox" checked={confirm==='jhcc'} onChange={event=>setConfirm(event.target.checked?'jhcc':'')}/>{t.confirm}</label><button disabled={confirm!=='jhcc'}>{t.prepareDraft}</button>{jhcc&&<p>{smallBusinessLabel(locale,'reporting')} · {jhcc.eventCount} · {smallBusinessLabel(locale,'unavailableState')}</p>}</form>
 </section>
}
