import {useCallback,useEffect,useRef,useState} from 'react';
import {useLocale} from '../../../i18n/hooks';
import {SMALL_BUSINESS_COPY} from '../../../i18n/smallBusiness';
import {commandId,type AdminQueueItem,type BusinessStatus} from '../../smallBusiness/smallBusinessModel';
import {firebaseSmallBusinessProvider,type SmallBusinessProvider} from '../../smallBusiness/smallBusinessProvider';
import '../../smallBusiness/smallBusiness.css';
const decisions=['request_changes','approve','reject','suspend','reactivate','expire','close'] as const;
export default function V2SmallBusinessReview({provider=firebaseSmallBusinessProvider}:{provider?:SmallBusinessProvider}){const locale=useLocale(),t=SMALL_BUSINESS_COPY[locale],[items,setItems]=useState<AdminQueueItem[]>([]),[state,setState]=useState<'loading'|'current'|'empty'|'unavailable'>('loading'),[selected,setSelected]=useState<AdminQueueItem>(),[filter,setFilter]=useState<BusinessStatus|''>(''),[decision,setDecision]=useState<typeof decisions[number]>('request_changes'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),stable=useRef(commandId('small_business_admin'));
 const generation=useRef(0),load=useCallback(async()=>{const request=++generation.current;setState('loading');const result=await provider.adminQueue(filter?{status:filter}:{});if(request!==generation.current)return;setItems(result.items);setState(result.state);setMessage(result.supportReference||'')},[filter,provider]);useEffect(()=>{void load();return()=>{generation.current++}},[load]);
 const apply=async()=>{if(!selected||!confirmed||reason.trim().length<4)return;if(!navigator.onLine){setMessage(t.offline);return}try{await provider.adminDecision({commandId:stable.current,businessId:selected.businessId,expectedVersion:selected.version,decision,reason:reason.trim(),policyVersion:'small-business-review-v1',confirmed:true});stable.current=commandId('small_business_admin');setConfirmed(false);setSelected(undefined);setReason('');setMessage('');await load()}catch(error){setMessage(String(error).includes('STALE')?t.conflict:t.unavailable)}};
 return <section className="sb-card" aria-labelledby="sb-admin-title"><h2 id="sb-admin-title">{t.adminTitle}</h2><p>{t.noContact}</p><div className="sb-live" role="status" aria-live="polite">{message}</div><label>{t.filters}<select value={filter} onChange={e=>setFilter(e.target.value as BusinessStatus|'')}><option value="">—</option>{['draft','submitted','changes_requested','approved','active','suspended','expired','rejected','closed'].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>void load()}>{t.refresh}</button>{state==='loading'&&<p aria-busy="true">{t.loading}</p>}{state==='unavailable'&&<p role="alert">{t.unavailable}</p>}{state==='empty'&&<p>{t.empty}</p>}
 <ul>{items.map(item=><li key={item.businessId}><button onClick={()=>{setSelected(item);setConfirmed(false)}}>{item.displayName} · {item.category} · {item.country} · {item.status}</button></li>)}</ul>{selected&&<form onSubmit={e=>{e.preventDefault();void apply()}}><h3>{selected.displayName}</h3><p>{t.evidence}: {selected.evidenceCount}</p><label>{t.decision}<select value={decision} onChange={e=>{setDecision(e.target.value as typeof decision);setConfirmed(false)}}>{decisions.map(x=><option key={x}>{x}</option>)}</select></label><label>{t.reason}<textarea required minLength={4} maxLength={256} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="sb-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t.confirm}</label><button disabled={!confirmed||reason.trim().length<4}>{t.apply}</button></form>}</section>}
