import {useCallback,useEffect,useRef,useState} from 'react';
import {useLocale} from '../../../i18n/hooks';
import {SMALL_BUSINESS_COPY} from '../../../i18n/smallBusiness';
import {smallBusinessLabel} from '../../../i18n/smallBusinessLabels';
import {commandId,type AdminQueueItem,type BusinessStatus} from '../../smallBusiness/smallBusinessModel';
import {firebaseSmallBusinessProvider,type SmallBusinessProvider} from '../../smallBusiness/smallBusinessProvider';
import '../../smallBusiness/smallBusiness.css';
const decisions=['request_changes','approve','reject','suspend','reactivate','expire','close'] as const;
const statuses=['draft','submitted','changes_requested','approved','active','suspended','expired','rejected','closed'] as const;
export default function V2SmallBusinessReview({provider=firebaseSmallBusinessProvider}:{provider?:SmallBusinessProvider}){
 const locale=useLocale(),t=SMALL_BUSINESS_COPY[locale],[items,setItems]=useState<AdminQueueItem[]>([]),[state,setState]=useState<'loading'|'current'|'empty'|'unavailable'>('loading'),[selected,setSelected]=useState<AdminQueueItem>(),[filter,setFilter]=useState<BusinessStatus|''>(''),[decision,setDecision]=useState<typeof decisions[number]>('request_changes'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),stable=useRef(commandId('small_business_admin'));
 const load=useCallback(async()=>{setState('loading');const result=await provider.adminQueue(filter?{status:filter}:{});setItems(result.items);setState(result.state)},[filter,provider]);useEffect(()=>{void load()},[load]);
 const apply=async()=>{if(!selected||!confirmed||reason.trim().length<4)return;if(!navigator.onLine){setMessage(t.offline);return}try{await provider.adminDecision({commandId:stable.current,businessId:selected.businessId,expectedVersion:selected.version,decision,reason:reason.trim(),policyVersion:'small-business-review-v1',confirmed:true});stable.current=commandId('small_business_admin');setConfirmed(false);setSelected(undefined);setReason('');setMessage(t.refresh);await load()}catch(error){setMessage(String(error).includes('STALE')?t.conflict:t.unavailable)}};
 return <section className="sb-card" aria-busy={state==='loading'}><h2>{t.adminTitle}</h2><label>{t.filters}<select value={filter} onChange={event=>setFilter(event.target.value as BusinessStatus|'')}><option value="">{t.filters}</option>{statuses.map(value=><option key={value} value={value}>{smallBusinessLabel(locale,value)}</option>)}</select></label>{state==='loading'&&<p role="status">{t.loading}</p>}{state==='unavailable'&&<p role="alert">{t.unavailable}</p>}{state==='empty'&&<p>{t.empty}</p>}
  <ul>{items.map(item=><li key={item.businessId}><button onClick={()=>{setSelected(item);setConfirmed(false)}}>{item.displayName} · {smallBusinessLabel(locale,item.category)} · {item.country} · {smallBusinessLabel(locale,item.status)}</button></li>)}</ul>
  {selected&&<form onSubmit={event=>{event.preventDefault();void apply()}}><h3>{selected.displayName}</h3><p>{t.evidence}: {selected.evidenceCount}</p><label>{t.decision}<select value={decision} onChange={event=>{setDecision(event.target.value as typeof decision);setConfirmed(false)}}>{decisions.map(value=><option key={value} value={value}>{smallBusinessLabel(locale,value)}</option>)}</select></label><label>{t.reason}<textarea required minLength={4} maxLength={256} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="sb-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t.confirm}</label><button disabled={!confirmed||reason.trim().length<4}>{t.apply}</button></form>}{message&&<p role={message===t.refresh?'status':'alert'}>{message}</p>}
 </section>
}
