import type {AdminLocale} from '../../components/admin/v2/adminNavigation';

const en={
 title:'Member delivery commissioning readiness',intro:'Review metadata, approval coverage and non-live provider/reporting checks. This surface never stores customer-facing legal text or sends a message.',refresh:'Refresh readiness',loading:'Loading commissioning readiness…',empty:'No template candidates have been proposed.',unavailable:'The authoritative commissioning service is unavailable.',offline:'Network unavailable. No commissioning command was recorded.',retry:'Retry',updated:'Commissioning readiness updated.',failed:'The command was not accepted. Reload authoritative state and retry.',
 coverage:'Locale and jurisdiction coverage',templateId:'Template ID',templateVersion:'Template version',kind:'Template purpose',locale:'Locale',jurisdiction:'Jurisdiction',digest:'Content digest',policyVersion:'Policy version',effective:'Effective date and time',expires:'Expiry date and time',approvalStatus:'Approval status',legalApproval:'Legal approval',customerApproval:'Customer approval',required:'Required',notRequired:'Not required',approved:'Approved externally',awaitingApproval:'Awaiting external approval',active:'Active for non-live preparation',rejected:'Rejected',retired:'Retired',select:'Select candidate',selected:'Selected candidate',
 proposal:'Propose template metadata',metadataOnly:'Enter metadata and a digest only. Do not enter message or legal text.',customerApprovalRequired:'Customer approval is required',propose:'Propose candidate',proposalConfirm:'I confirm that this proposal contains metadata only and grants no approval.',
 approvals:'Record external approval reference',approvalKind:'Approval type',legal:'Legal',customer:'Customer-facing template',externalReceipt:'External approval receipt reference',approvalDigest:'External approval digest',recordApproval:'Record verified reference',approvalConfirm:'I confirm that the referenced approval already exists in the authoritative external registry. I am not making the approval here.',
 actions:'Candidate actions',activate:'Activate complete approval set',activateConfirm:'I confirm activation only after all required external approvals are shown as complete.',rejectAction:'Reject candidate',retireAction:'Retire active candidate',reason:'Administrative reason',stateConfirm:'I confirm this destructive state change.',incompleteApproval:'Activation remains unavailable until every required external approval is recorded.',
 history:'Immutable commissioning history',historyUnavailable:'Receipt history is not included in the current minimum projection. Reload after the authoritative service exposes it.',receipt:'Receipt',created:'Created',lastUpdated:'Last updated',
 providerAudit:'Provider composition dry run',requestId:'Member request ID',compositionId:'Provider composition ID',channel:'Allowed channel',email:'Email',sms:'SMS',push:'Push notification',runDryRun:'Run zero-send dry run',dryRunConfirm:'I confirm this is a provider-neutral validation with no credential read, destination resolution or transmission.',providerNotCommissioned:'Delivery provider is not commissioned. A successful validation remains provider unconfigured and sends nothing.',dryRuns:'Recent provider dry runs',
 jhcc:'JHCC reporting validation',eventIds:'Report-ready event IDs, one per line',validateJhcc:'Validate non-live JHCC port',jhccConfirm:'I confirm validation is privacy-minimized and does not transmit to JHCC.',jhccNotCommissioned:'The JHCC destination is not commissioned. Validation cannot transmit.',reportValidations:'Recent JHCC validations',
 boundaries:'Enforced boundaries',legalTextNotStored:'No legal or customer message text stored',providerNotConfigured:'No provider credentials or calls',jhccNotConfigured:'No JHCC destination or transmission',notificationsNotSent:'No email, SMS or push sent',economyUnchanged:'No Tee balance, price, commission or settlement write',none:'None recorded',
 statusPending:'Awaiting approval',statusActive:'Active',statusRejected:'Rejected',statusRetired:'Retired',statusProviderUnconfigured:'Provider unconfigured — no send',statusValidatedNoTransmission:'Validated — not transmitted',kindInvitation:'Invitation',kindResend:'Resend',kindCorrection:'Correction request',kindRejected:'Rejection',kindExpired:'Expiry',kindSupport:'Support response',confirmationRequired:'Explicit confirmation is required.',
};
export type EnterpriseMemberCommissioningCopy=typeof en;

const th:EnterpriseMemberCommissioningCopy={
 title:'ความพร้อมในการเริ่มใช้งานการส่งข้อมูลสมาชิก',intro:'ตรวจสอบเมทาดาทา ขอบเขตการอนุมัติ และการตรวจผู้ให้บริการ/รายงานแบบไม่ใช้งานจริง หน้านี้ไม่เก็บข้อความกฎหมายสำหรับลูกค้าและไม่ส่งข้อความ',refresh:'รีเฟรชความพร้อม',loading:'กำลังโหลดความพร้อมในการเริ่มใช้งาน…',empty:'ยังไม่มีการเสนอแม่แบบ候选',unavailable:'บริการการเริ่มใช้งานที่เป็นแหล่งอ้างอิงไม่พร้อมใช้งาน',offline:'เครือข่ายไม่พร้อมใช้งาน จึงไม่มีการบันทึกคำสั่ง',retry:'ลองอีกครั้ง',updated:'อัปเดตความพร้อมแล้ว',failed:'ระบบไม่ยอมรับคำสั่ง โปรดโหลดสถานะจากแหล่งอ้างอิงใหม่แล้วลองอีกครั้ง',
 coverage:'ความครอบคลุมของภาษาและเขตอำนาจ',templateId:'รหัสแม่แบบ',templateVersion:'เวอร์ชันแม่แบบ',kind:'วัตถุประสงค์ของแม่แบบ',locale:'ภาษาและภูมิภาค',jurisdiction:'เขตอำนาจ',digest:'ไดเจสต์เนื้อหา',policyVersion:'เวอร์ชันนโยบาย',effective:'วันและเวลาเริ่มมีผล',expires:'วันและเวลาหมดอายุ',approvalStatus:'สถานะการอนุมัติ',legalApproval:'การอนุมัติด้านกฎหมาย',customerApproval:'การอนุมัติข้อความสำหรับลูกค้า',required:'จำเป็น',notRequired:'ไม่จำเป็น',approved:'ได้รับอนุมัติจากภายนอกแล้ว',awaitingApproval:'รอการอนุมัติจากภายนอก',active:'ใช้งานสำหรับการเตรียมแบบไม่ส่งจริง',rejected:'ถูกปฏิเสธ',retired:'ยุติการใช้งาน',select:'เลือกแม่แบบ候选',selected:'แม่แบบที่เลือก',
 proposal:'เสนอเมทาดาทาของแม่แบบ',metadataOnly:'กรอกเฉพาะเมทาดาทาและไดเจสต์ ห้ามกรอกข้อความสื่อสารหรือข้อความกฎหมาย',customerApprovalRequired:'ต้องมีการอนุมัติข้อความสำหรับลูกค้า',propose:'เสนอแม่แบบ候选',proposalConfirm:'ฉันยืนยันว่าข้อเสนอนี้มีเฉพาะเมทาดาทาและไม่ได้ให้การอนุมัติใดๆ',
 approvals:'บันทึกข้อมูลอ้างอิงการอนุมัติภายนอก',approvalKind:'ประเภทการอนุมัติ',legal:'ด้านกฎหมาย',customer:'แม่แบบสำหรับลูกค้า',externalReceipt:'ข้อมูลอ้างอิงใบรับรองการอนุมัติภายนอก',approvalDigest:'ไดเจสต์การอนุมัติภายนอก',recordApproval:'บันทึกข้อมูลอ้างอิงที่ตรวจสอบแล้ว',approvalConfirm:'ฉันยืนยันว่าการอนุมัติที่อ้างถึงมีอยู่แล้วในทะเบียนภายนอกที่เชื่อถือได้ และฉันไม่ได้เป็นผู้อนุมัติในหน้านี้',
 actions:'การดำเนินการกับแม่แบบ',activate:'เปิดใช้ชุดการอนุมัติที่ครบถ้วน',activateConfirm:'ฉันยืนยันให้เปิดใช้เฉพาะเมื่อการอนุมัติภายนอกที่จำเป็นทั้งหมดแสดงว่าครบถ้วนแล้ว',rejectAction:'ปฏิเสธแม่แบบ候选',retireAction:'ยุติแม่แบบที่ใช้งานอยู่',reason:'เหตุผลทางการบริหาร',stateConfirm:'ฉันยืนยันการเปลี่ยนสถานะแบบทำลายนี้',incompleteApproval:'ยังเปิดใช้ไม่ได้จนกว่าจะบันทึกการอนุมัติภายนอกที่จำเป็นครบทั้งหมด',
 history:'ประวัติการเริ่มใช้งานที่แก้ไขไม่ได้',historyUnavailable:'ข้อมูลใบรับรองยังไม่รวมอยู่ในการฉายข้อมูลขั้นต่ำปัจจุบัน โปรดโหลดใหม่เมื่อบริการที่เป็นแหล่งอ้างอิงเปิดเผยข้อมูลดังกล่าว',receipt:'ใบรับรอง',created:'สร้างเมื่อ',lastUpdated:'อัปเดตล่าสุด',
 providerAudit:'การทดสอบองค์ประกอบของผู้ให้บริการ',requestId:'รหัสคำขอสมาชิก',compositionId:'รหัสองค์ประกอบผู้ให้บริการ',channel:'ช่องทางที่อนุญาต',email:'อีเมล',sms:'ข้อความ SMS',push:'การแจ้งเตือนแบบพุช',runDryRun:'ทดสอบแบบไม่ส่งข้อความ',dryRunConfirm:'ฉันยืนยันว่านี่คือการตรวจสอบแบบเป็นกลางต่อผู้ให้บริการ โดยไม่อ่านข้อมูลลับ แก้ปลายทาง หรือส่งข้อมูล',providerNotCommissioned:'ผู้ให้บริการจัดส่งยังไม่เริ่มใช้งาน แม้ตรวจสอบผ่าน สถานะจะยังเป็นผู้ให้บริการไม่พร้อมและไม่มีการส่ง',dryRuns:'การทดสอบผู้ให้บริการล่าสุด',
 jhcc:'การตรวจสอบรายงาน JHCC',eventIds:'รหัสเหตุการณ์พร้อมรายงาน บรรทัดละหนึ่งรหัส',validateJhcc:'ตรวจพอร์ต JHCC แบบไม่ใช้งานจริง',jhccConfirm:'ฉันยืนยันว่าการตรวจสอบลดข้อมูลส่วนบุคคลและไม่ส่งไปยัง JHCC',jhccNotCommissioned:'ปลายทาง JHCC ยังไม่เริ่มใช้งาน การตรวจสอบจึงไม่สามารถส่งข้อมูลได้',reportValidations:'การตรวจสอบ JHCC ล่าสุด',
 boundaries:'ขอบเขตที่บังคับใช้',legalTextNotStored:'ไม่เก็บข้อความกฎหมายหรือข้อความสำหรับลูกค้า',providerNotConfigured:'ไม่มีข้อมูลลับหรือการเรียกผู้ให้บริการ',jhccNotConfigured:'ไม่มีปลายทางหรือการส่งข้อมูลไปยัง JHCC',notificationsNotSent:'ไม่มีการส่งอีเมล SMS หรือพุช',economyUnchanged:'ไม่มีการเขียนยอด Tee ราคา ค่าคอมมิชชัน หรือการชำระบัญชี',none:'ยังไม่มีรายการ',
 statusPending:'รอการอนุมัติ',statusActive:'ใช้งานอยู่',statusRejected:'ถูกปฏิเสธ',statusRetired:'ยุติแล้ว',statusProviderUnconfigured:'ผู้ให้บริการไม่พร้อม — ไม่มีการส่ง',statusValidatedNoTransmission:'ตรวจสอบแล้ว — ไม่ได้ส่ง',kindInvitation:'คำเชิญ',kindResend:'ส่งซ้ำ',kindCorrection:'คำขอแก้ไข',kindRejected:'การปฏิเสธ',kindExpired:'การหมดอายุ',kindSupport:'คำตอบฝ่ายสนับสนุน',confirmationRequired:'ต้องยืนยันอย่างชัดแจ้ง',
};

const ko:EnterpriseMemberCommissioningCopy={
 title:'회원 전달 커미셔닝 준비 상태',intro:'메타데이터, 승인 범위 및 비실시간 제공업체/보고 검사를 검토합니다. 이 화면은 고객용 법률 문구를 저장하거나 메시지를 보내지 않습니다.',refresh:'준비 상태 새로 고침',loading:'커미셔닝 준비 상태를 불러오는 중…',empty:'제안된 템플릿 후보가 없습니다.',unavailable:'권한 있는 커미셔닝 서비스를 사용할 수 없습니다.',offline:'네트워크를 사용할 수 없어 커미셔닝 명령이 기록되지 않았습니다.',retry:'다시 시도',updated:'커미셔닝 준비 상태가 업데이트되었습니다.',failed:'명령이 승인되지 않았습니다. 권한 있는 상태를 다시 불러온 후 재시도하세요.',
 coverage:'언어 및 관할권 적용 범위',templateId:'템플릿 ID',templateVersion:'템플릿 버전',kind:'템플릿 용도',locale:'언어 및 지역',jurisdiction:'관할권',digest:'콘텐츠 다이제스트',policyVersion:'정책 버전',effective:'유효 시작 일시',expires:'만료 일시',approvalStatus:'승인 상태',legalApproval:'법무 승인',customerApproval:'고객용 템플릿 승인',required:'필수',notRequired:'필수 아님',approved:'외부 승인 완료',awaitingApproval:'외부 승인 대기',active:'비실시간 준비에 사용 중',rejected:'거부됨',retired:'사용 종료됨',select:'후보 선택',selected:'선택한 후보',
 proposal:'템플릿 메타데이터 제안',metadataOnly:'메타데이터와 다이제스트만 입력하세요. 메시지나 법률 문구는 입력하지 마세요.',customerApprovalRequired:'고객용 템플릿 승인이 필요함',propose:'후보 제안',proposalConfirm:'이 제안에는 메타데이터만 포함되며 어떠한 승인도 부여하지 않음을 확인합니다.',
 approvals:'외부 승인 참조 기록',approvalKind:'승인 유형',legal:'법무',customer:'고객용 템플릿',externalReceipt:'외부 승인 영수증 참조',approvalDigest:'외부 승인 다이제스트',recordApproval:'검증된 참조 기록',approvalConfirm:'참조한 승인이 권한 있는 외부 레지스트리에 이미 존재하며 이 화면에서 승인 결정을 내리는 것이 아님을 확인합니다.',
 actions:'후보 작업',activate:'완전한 승인 세트 활성화',activateConfirm:'필요한 모든 외부 승인이 완료된 것으로 표시된 경우에만 활성화함을 확인합니다.',rejectAction:'후보 거부',retireAction:'활성 후보 사용 종료',reason:'관리 사유',stateConfirm:'이 파괴적 상태 변경을 확인합니다.',incompleteApproval:'필요한 외부 승인이 모두 기록될 때까지 활성화할 수 없습니다.',
 history:'변경 불가 커미셔닝 이력',historyUnavailable:'현재 최소 정보 화면에는 영수증 이력이 포함되지 않습니다. 권한 있는 서비스에서 제공된 뒤 다시 불러오세요.',receipt:'영수증',created:'생성 일시',lastUpdated:'최근 업데이트',
 providerAudit:'제공업체 구성 시험 실행',requestId:'회원 요청 ID',compositionId:'제공업체 구성 ID',channel:'허용 채널',email:'이메일',sms:'문자 메시지',push:'푸시 알림',runDryRun:'전송 없는 시험 실행',dryRunConfirm:'자격 증명 읽기, 목적지 확인 또는 전송이 없는 제공업체 중립 검증임을 확인합니다.',providerNotCommissioned:'전달 제공업체가 커미셔닝되지 않았습니다. 검증에 성공해도 제공업체 미구성 상태이며 아무것도 전송하지 않습니다.',dryRuns:'최근 제공업체 시험 실행',
 jhcc:'JHCC 보고 검증',eventIds:'보고 준비 이벤트 ID, 한 줄에 하나씩',validateJhcc:'비실시간 JHCC 포트 검증',jhccConfirm:'검증 정보가 최소화되어 있으며 JHCC로 전송되지 않음을 확인합니다.',jhccNotCommissioned:'JHCC 목적지가 커미셔닝되지 않아 검증으로 전송할 수 없습니다.',reportValidations:'최근 JHCC 검증',
 boundaries:'적용되는 경계',legalTextNotStored:'법률 문구 또는 고객 메시지 저장 없음',providerNotConfigured:'제공업체 자격 증명 또는 호출 없음',jhccNotConfigured:'JHCC 목적지 또는 전송 없음',notificationsNotSent:'이메일, 문자 또는 푸시 전송 없음',economyUnchanged:'Tee 잔액, 가격, 수수료 또는 정산 기록 없음',none:'기록 없음',
 statusPending:'승인 대기',statusActive:'활성',statusRejected:'거부됨',statusRetired:'사용 종료됨',statusProviderUnconfigured:'제공업체 미구성 — 전송 없음',statusValidatedNoTransmission:'검증 완료 — 미전송',kindInvitation:'초대',kindResend:'재전송',kindCorrection:'수정 요청',kindRejected:'거부',kindExpired:'만료',kindSupport:'지원 답변',confirmationRequired:'명시적 확인이 필요합니다.',
};

const ja:EnterpriseMemberCommissioningCopy={
 title:'会員配信コミッショニング準備状況',intro:'メタデータ、承認範囲、非稼働のプロバイダー／レポート検証を確認します。この画面は顧客向け法的文面を保存せず、メッセージも送信しません。',refresh:'準備状況を更新',loading:'コミッショニング準備状況を読み込み中…',empty:'提案されたテンプレート候補はありません。',unavailable:'正規のコミッショニングサービスは利用できません。',offline:'ネットワークを利用できないため、コマンドは記録されませんでした。',retry:'再試行',updated:'コミッショニング準備状況を更新しました。',failed:'コマンドは受理されませんでした。正規の状態を再読み込みして再試行してください。',
 coverage:'言語と管轄区域の対応範囲',templateId:'テンプレートID',templateVersion:'テンプレートバージョン',kind:'テンプレート用途',locale:'言語と地域',jurisdiction:'管轄区域',digest:'コンテンツダイジェスト',policyVersion:'ポリシーバージョン',effective:'有効開始日時',expires:'有効期限日時',approvalStatus:'承認状況',legalApproval:'法務承認',customerApproval:'顧客向けテンプレート承認',required:'必須',notRequired:'不要',approved:'外部承認済み',awaitingApproval:'外部承認待ち',active:'非稼働準備で有効',rejected:'却下済み',retired:'廃止済み',select:'候補を選択',selected:'選択中の候補',
 proposal:'テンプレートメタデータを提案',metadataOnly:'メタデータとダイジェストのみ入力してください。メッセージ本文や法的文面は入力しないでください。',customerApprovalRequired:'顧客向けテンプレート承認が必要',propose:'候補を提案',proposalConfirm:'この提案にはメタデータのみが含まれ、承認を付与しないことを確認します。',
 approvals:'外部承認参照を記録',approvalKind:'承認種別',legal:'法務',customer:'顧客向けテンプレート',externalReceipt:'外部承認レシート参照',approvalDigest:'外部承認ダイジェスト',recordApproval:'検証済み参照を記録',approvalConfirm:'参照した承認が正規の外部台帳に既に存在し、この画面では承認判断を行わないことを確認します。',
 actions:'候補の操作',activate:'承認完了セットを有効化',activateConfirm:'必要な外部承認がすべて完了と表示されている場合に限り有効化することを確認します。',rejectAction:'候補を却下',retireAction:'有効な候補を廃止',reason:'管理上の理由',stateConfirm:'この破壊的な状態変更を確認します。',incompleteApproval:'必要な外部承認がすべて記録されるまで有効化できません。',
 history:'変更不可のコミッショニング履歴',historyUnavailable:'現在の最小情報にはレシート履歴が含まれていません。正規サービスが公開した後に再読み込みしてください。',receipt:'レシート',created:'作成日時',lastUpdated:'最終更新',
 providerAudit:'プロバイダー構成のドライラン',requestId:'会員リクエストID',compositionId:'プロバイダー構成ID',channel:'許可チャネル',email:'メール',sms:'SMSメッセージ',push:'プッシュ通知',runDryRun:'送信なしでドライラン',dryRunConfirm:'資格情報の読取り、宛先解決、送信を行わないプロバイダー中立の検証であることを確認します。',providerNotCommissioned:'配信プロバイダーは未開通です。検証に成功しても未構成のままで、何も送信しません。',dryRuns:'最近のプロバイダードライラン',
 jhcc:'JHCCレポート検証',eventIds:'レポート準備済みイベントID（1行に1件）',validateJhcc:'非稼働JHCCポートを検証',jhccConfirm:'プライバシーを最小化した検証であり、JHCCへ送信しないことを確認します。',jhccNotCommissioned:'JHCC宛先は未開通のため、検証では送信できません。',reportValidations:'最近のJHCC検証',
 boundaries:'強制される境界',legalTextNotStored:'法的文面または顧客メッセージを保存しない',providerNotConfigured:'プロバイダー資格情報または呼出しなし',jhccNotConfigured:'JHCC宛先または送信なし',notificationsNotSent:'メール、SMS、プッシュを送信しない',economyUnchanged:'Tee残高、価格、手数料、決済を書き込まない',none:'記録なし',
 statusPending:'承認待ち',statusActive:'有効',statusRejected:'却下済み',statusRetired:'廃止済み',statusProviderUnconfigured:'プロバイダー未構成 — 送信なし',statusValidatedNoTransmission:'検証済み — 未送信',kindInvitation:'招待',kindResend:'再送',kindCorrection:'修正依頼',kindRejected:'却下',kindExpired:'期限切れ',kindSupport:'サポート回答',confirmationRequired:'明示的な確認が必要です。',
};

const zh:EnterpriseMemberCommissioningCopy={
 title:'会员交付上线准备情况',intro:'审核元数据、审批覆盖范围以及非实时的服务商和报告检查。本页面不存储面向客户的法律文本，也不会发送消息。',refresh:'刷新准备情况',loading:'正在加载上线准备情况…',empty:'尚未提交任何模板候选项。',unavailable:'权威上线准备服务当前不可用。',offline:'网络不可用，未记录任何上线准备命令。',retry:'重试',updated:'上线准备情况已更新。',failed:'命令未被接受。请重新加载权威状态后再试。',
 coverage:'语言和管辖区覆盖范围',templateId:'模板 ID',templateVersion:'模板版本',kind:'模板用途',locale:'语言和地区',jurisdiction:'管辖区',digest:'内容摘要',policyVersion:'政策版本',effective:'生效日期和时间',expires:'到期日期和时间',approvalStatus:'审批状态',legalApproval:'法务审批',customerApproval:'客户模板审批',required:'必需',notRequired:'不需要',approved:'外部已批准',awaitingApproval:'等待外部批准',active:'已启用于非实时准备',rejected:'已拒绝',retired:'已停用',select:'选择候选项',selected:'已选候选项',
 proposal:'提交模板元数据',metadataOnly:'只输入元数据和摘要。请勿输入消息正文或法律文本。',customerApprovalRequired:'需要客户模板审批',propose:'提交候选项',proposalConfirm:'我确认此提交仅包含元数据，不授予任何批准。',
 approvals:'记录外部审批参考',approvalKind:'审批类型',legal:'法务',customer:'客户模板',externalReceipt:'外部审批回执参考',approvalDigest:'外部审批摘要',recordApproval:'记录已验证参考',approvalConfirm:'我确认所引用的批准已存在于权威外部登记中，我不会在此作出批准决定。',
 actions:'候选项操作',activate:'启用完整审批集',activateConfirm:'我确认仅在所有必需的外部批准均显示完成后启用。',rejectAction:'拒绝候选项',retireAction:'停用有效候选项',reason:'管理原因',stateConfirm:'我确认此破坏性状态变更。',incompleteApproval:'在记录所有必需的外部批准前无法启用。',
 history:'不可更改的上线准备历史',historyUnavailable:'当前最小投影不包含回执历史。请在权威服务提供该信息后重新加载。',receipt:'回执',created:'创建时间',lastUpdated:'最近更新',
 providerAudit:'服务商组合试运行',requestId:'会员请求 ID',compositionId:'服务商组合 ID',channel:'允许的渠道',email:'电子邮件',sms:'短信',push:'推送通知',runDryRun:'运行零发送试验',dryRunConfirm:'我确认这是服务商中立验证，不读取凭据、不解析目的地，也不传输。',providerNotCommissioned:'交付服务商尚未上线。即使验证成功，也会保持未配置状态且不会发送任何内容。',dryRuns:'最近的服务商试运行',
 jhcc:'JHCC 报告验证',eventIds:'可报告事件 ID，每行一个',validateJhcc:'验证非实时 JHCC 端口',jhccConfirm:'我确认验证数据已最小化，且不会传输到 JHCC。',jhccNotCommissioned:'JHCC 目的地尚未上线，验证不会传输。',reportValidations:'最近的 JHCC 验证',
 boundaries:'强制边界',legalTextNotStored:'不存储法律文本或客户消息',providerNotConfigured:'无服务商凭据或调用',jhccNotConfigured:'无 JHCC 目的地或传输',notificationsNotSent:'不发送邮件、短信或推送',economyUnchanged:'不写入 Tee 余额、价格、佣金或结算',none:'没有记录',
 statusPending:'等待批准',statusActive:'有效',statusRejected:'已拒绝',statusRetired:'已停用',statusProviderUnconfigured:'服务商未配置 — 未发送',statusValidatedNoTransmission:'已验证 — 未传输',kindInvitation:'邀请',kindResend:'重新发送',kindCorrection:'更正请求',kindRejected:'拒绝',kindExpired:'到期',kindSupport:'支持回复',confirmationRequired:'需要明确确认。',
};

const es:EnterpriseMemberCommissioningCopy={
 title:'Preparación de puesta en servicio de entregas a miembros',intro:'Revisa metadatos, cobertura de aprobaciones y comprobaciones no activas del proveedor y de informes. Esta pantalla no almacena texto legal para clientes ni envía mensajes.',refresh:'Actualizar preparación',loading:'Cargando la preparación de puesta en servicio…',empty:'No se ha propuesto ninguna plantilla candidata.',unavailable:'El servicio autorizado de puesta en servicio no está disponible.',offline:'La red no está disponible. No se registró ningún comando.',retry:'Reintentar',updated:'Preparación actualizada.',failed:'El comando no fue aceptado. Vuelve a cargar el estado autorizado e inténtalo de nuevo.',
 coverage:'Cobertura de idioma y jurisdicción',templateId:'ID de plantilla',templateVersion:'Versión de plantilla',kind:'Finalidad de la plantilla',locale:'Idioma y región',jurisdiction:'Jurisdicción',digest:'Resumen criptográfico del contenido',policyVersion:'Versión de la política',effective:'Fecha y hora de entrada en vigor',expires:'Fecha y hora de caducidad',approvalStatus:'Estado de aprobación',legalApproval:'Aprobación jurídica',customerApproval:'Aprobación de plantilla para clientes',required:'Obligatoria',notRequired:'No obligatoria',approved:'Aprobada externamente',awaitingApproval:'Pendiente de aprobación externa',active:'Activa para preparación no operativa',rejected:'Rechazada',retired:'Retirada',select:'Seleccionar candidata',selected:'Candidata seleccionada',
 proposal:'Proponer metadatos de plantilla',metadataOnly:'Introduce solo metadatos y un resumen criptográfico. No introduzcas mensajes ni texto legal.',customerApprovalRequired:'Se requiere aprobación de la plantilla para clientes',propose:'Proponer candidata',proposalConfirm:'Confirmo que esta propuesta solo contiene metadatos y no concede ninguna aprobación.',
 approvals:'Registrar referencia de aprobación externa',approvalKind:'Tipo de aprobación',legal:'Jurídica',customer:'Plantilla para clientes',externalReceipt:'Referencia del comprobante de aprobación externa',approvalDigest:'Resumen criptográfico de la aprobación externa',recordApproval:'Registrar referencia verificada',approvalConfirm:'Confirmo que la aprobación citada ya existe en el registro externo autorizado y que no estoy aprobándola aquí.',
 actions:'Acciones de la candidata',activate:'Activar conjunto completo de aprobaciones',activateConfirm:'Confirmo que solo se activará cuando todas las aprobaciones externas obligatorias figuren como completas.',rejectAction:'Rechazar candidata',retireAction:'Retirar candidata activa',reason:'Motivo administrativo',stateConfirm:'Confirmo este cambio de estado destructivo.',incompleteApproval:'No se puede activar hasta registrar todas las aprobaciones externas obligatorias.',
 history:'Historial inmutable de puesta en servicio',historyUnavailable:'El historial de comprobantes no forma parte de la proyección mínima actual. Actualiza cuando el servicio autorizado lo exponga.',receipt:'Comprobante',created:'Creada',lastUpdated:'Última actualización',
 providerAudit:'Prueba en seco de composición del proveedor',requestId:'ID de solicitud de miembro',compositionId:'ID de composición del proveedor',channel:'Canal permitido',email:'Correo electrónico',sms:'Mensaje SMS',push:'Notificación push',runDryRun:'Ejecutar prueba sin envío',dryRunConfirm:'Confirmo que es una validación neutral sin leer credenciales, resolver el destino ni transmitir.',providerNotCommissioned:'El proveedor de entrega no está puesto en servicio. Una validación correcta sigue sin configurar proveedor y no envía nada.',dryRuns:'Pruebas recientes del proveedor',
 jhcc:'Validación de informes JHCC',eventIds:'ID de eventos listos para informar, uno por línea',validateJhcc:'Validar puerto JHCC no operativo',jhccConfirm:'Confirmo que la validación minimiza los datos y no transmite a JHCC.',jhccNotCommissioned:'El destino JHCC no está puesto en servicio. La validación no puede transmitir.',reportValidations:'Validaciones recientes de JHCC',
 boundaries:'Límites aplicados',legalTextNotStored:'No se almacena texto legal ni mensajes para clientes',providerNotConfigured:'Sin credenciales ni llamadas al proveedor',jhccNotConfigured:'Sin destino ni transmisión a JHCC',notificationsNotSent:'No se envían correos, SMS ni notificaciones push',economyUnchanged:'Sin escrituras de saldo Tee, precio, comisión ni liquidación',none:'Sin registros',
 statusPending:'Pendiente de aprobación',statusActive:'Activa',statusRejected:'Rechazada',statusRetired:'Retirada',statusProviderUnconfigured:'Proveedor sin configurar — sin envío',statusValidatedNoTransmission:'Validado — no transmitido',kindInvitation:'Invitación',kindResend:'Reenvío',kindCorrection:'Solicitud de corrección',kindRejected:'Rechazo',kindExpired:'Caducidad',kindSupport:'Respuesta de soporte',confirmationRequired:'Se requiere confirmación explícita.',
};

const fr:EnterpriseMemberCommissioningCopy={
 title:'Préparation à la mise en service des remises aux membres',intro:'Examinez les métadonnées, la couverture des approbations et les contrôles non actifs du prestataire et des rapports. Cet écran ne conserve aucun texte juridique destiné aux clients et n’envoie aucun message.',refresh:'Actualiser la préparation',loading:'Chargement de la préparation à la mise en service…',empty:'Aucun modèle candidat n’a été proposé.',unavailable:'Le service de référence de mise en service est indisponible.',offline:'Le réseau est indisponible. Aucune commande n’a été enregistrée.',retry:'Réessayer',updated:'Préparation mise à jour.',failed:'La commande n’a pas été acceptée. Rechargez l’état de référence, puis réessayez.',
 coverage:'Couverture des langues et juridictions',templateId:'ID du modèle',templateVersion:'Version du modèle',kind:'Finalité du modèle',locale:'Langue et région',jurisdiction:'Juridiction',digest:'Empreinte du contenu',policyVersion:'Version de la politique',effective:'Date et heure de prise d’effet',expires:'Date et heure d’expiration',approvalStatus:'État d’approbation',legalApproval:'Approbation juridique',customerApproval:'Approbation du modèle client',required:'Obligatoire',notRequired:'Non obligatoire',approved:'Approuvée extérieurement',awaitingApproval:'En attente d’approbation externe',active:'Actif pour la préparation hors production',rejected:'Rejeté',retired:'Retiré',select:'Sélectionner le candidat',selected:'Candidat sélectionné',
 proposal:'Proposer les métadonnées du modèle',metadataOnly:'Saisissez uniquement les métadonnées et une empreinte. Ne saisissez aucun message ni texte juridique.',customerApprovalRequired:'L’approbation du modèle client est obligatoire',propose:'Proposer un candidat',proposalConfirm:'Je confirme que cette proposition ne contient que des métadonnées et n’accorde aucune approbation.',
 approvals:'Enregistrer une référence d’approbation externe',approvalKind:'Type d’approbation',legal:'Juridique',customer:'Modèle destiné aux clients',externalReceipt:'Référence du reçu d’approbation externe',approvalDigest:'Empreinte de l’approbation externe',recordApproval:'Enregistrer la référence vérifiée',approvalConfirm:'Je confirme que l’approbation citée existe déjà dans le registre externe de référence et que je ne l’accorde pas ici.',
 actions:'Actions sur le candidat',activate:'Activer l’ensemble complet d’approbations',activateConfirm:'Je confirme l’activation uniquement lorsque toutes les approbations externes obligatoires sont indiquées comme obtenues.',rejectAction:'Rejeter le candidat',retireAction:'Retirer le candidat actif',reason:'Motif administratif',stateConfirm:'Je confirme ce changement d’état destructif.',incompleteApproval:'L’activation reste impossible tant que toutes les approbations externes obligatoires ne sont pas enregistrées.',
 history:'Historique immuable de mise en service',historyUnavailable:'L’historique des reçus ne figure pas dans la projection minimale actuelle. Actualisez lorsque le service de référence le fournira.',receipt:'Reçu',created:'Créé',lastUpdated:'Dernière mise à jour',
 providerAudit:'Simulation de composition du prestataire',requestId:'ID de la demande de membre',compositionId:'ID de composition du prestataire',channel:'Canal autorisé',email:'Courriel',sms:'Message SMS',push:'Notification push',runDryRun:'Lancer la simulation sans envoi',dryRunConfirm:'Je confirme une validation neutre sans lecture d’identifiants, résolution de destination ni transmission.',providerNotCommissioned:'Le prestataire de remise n’est pas mis en service. Une validation réussie reste non configurée et n’envoie rien.',dryRuns:'Simulations récentes du prestataire',
 jhcc:'Validation des rapports JHCC',eventIds:'ID d’événements prêts à être rapportés, un par ligne',validateJhcc:'Valider le port JHCC non actif',jhccConfirm:'Je confirme que la validation minimise les données et ne transmet rien à JHCC.',jhccNotCommissioned:'La destination JHCC n’est pas mise en service. La validation ne peut rien transmettre.',reportValidations:'Validations JHCC récentes',
 boundaries:'Limites imposées',legalTextNotStored:'Aucun texte juridique ni message client conservé',providerNotConfigured:'Aucun identifiant ni appel au prestataire',jhccNotConfigured:'Aucune destination ni transmission JHCC',notificationsNotSent:'Aucun courriel, SMS ou push envoyé',economyUnchanged:'Aucune écriture de solde Tee, prix, commission ou règlement',none:'Aucun enregistrement',
 statusPending:'En attente d’approbation',statusActive:'Actif',statusRejected:'Rejeté',statusRetired:'Retiré',statusProviderUnconfigured:'Prestataire non configuré — aucun envoi',statusValidatedNoTransmission:'Validé — non transmis',kindInvitation:'Invitation',kindResend:'Renvoi',kindCorrection:'Demande de correction',kindRejected:'Rejet',kindExpired:'Expiration',kindSupport:'Réponse du support',confirmationRequired:'Une confirmation explicite est requise.',
};

const de:EnterpriseMemberCommissioningCopy={
 title:'Inbetriebnahmebereitschaft für Mitgliederzustellung',intro:'Prüfen Sie Metadaten, Freigabeabdeckung und nicht aktive Anbieter- und Berichtsprüfungen. Diese Ansicht speichert keine rechtlichen Kundentexte und sendet keine Nachricht.',refresh:'Bereitschaft aktualisieren',loading:'Inbetriebnahmebereitschaft wird geladen…',empty:'Es wurden keine Vorlagenkandidaten vorgeschlagen.',unavailable:'Der maßgebliche Inbetriebnahmedienst ist nicht verfügbar.',offline:'Das Netzwerk ist nicht verfügbar. Es wurde kein Befehl gespeichert.',retry:'Erneut versuchen',updated:'Inbetriebnahmebereitschaft wurde aktualisiert.',failed:'Der Befehl wurde nicht angenommen. Laden Sie den maßgeblichen Status neu und versuchen Sie es erneut.',
 coverage:'Sprach- und Rechtsgebietsabdeckung',templateId:'Vorlagen-ID',templateVersion:'Vorlagenversion',kind:'Vorlagenzweck',locale:'Sprache und Region',jurisdiction:'Rechtsgebiet',digest:'Inhalts-Digest',policyVersion:'Richtlinienversion',effective:'Datum und Uhrzeit des Inkrafttretens',expires:'Ablaufdatum und -uhrzeit',approvalStatus:'Freigabestatus',legalApproval:'Rechtliche Freigabe',customerApproval:'Freigabe der Kundenvorlage',required:'Erforderlich',notRequired:'Nicht erforderlich',approved:'Extern freigegeben',awaitingApproval:'Externe Freigabe ausstehend',active:'Für nicht aktive Vorbereitung freigeschaltet',rejected:'Abgelehnt',retired:'Stillgelegt',select:'Kandidat auswählen',selected:'Ausgewählter Kandidat',
 proposal:'Vorlagenmetadaten vorschlagen',metadataOnly:'Geben Sie nur Metadaten und einen Digest ein. Geben Sie keinen Nachrichten- oder Rechtstext ein.',customerApprovalRequired:'Freigabe der Kundenvorlage ist erforderlich',propose:'Kandidat vorschlagen',proposalConfirm:'Ich bestätige, dass dieser Vorschlag nur Metadaten enthält und keine Freigabe erteilt.',
 approvals:'Externe Freigabereferenz erfassen',approvalKind:'Freigabeart',legal:'Rechtlich',customer:'Kundenvorlage',externalReceipt:'Referenz des externen Freigabebelegs',approvalDigest:'Digest der externen Freigabe',recordApproval:'Geprüfte Referenz erfassen',approvalConfirm:'Ich bestätige, dass die referenzierte Freigabe bereits im maßgeblichen externen Register besteht und hier nicht von mir erteilt wird.',
 actions:'Kandidatenaktionen',activate:'Vollständigen Freigabesatz aktivieren',activateConfirm:'Ich bestätige die Aktivierung nur, wenn alle erforderlichen externen Freigaben als vollständig angezeigt werden.',rejectAction:'Kandidat ablehnen',retireAction:'Aktiven Kandidaten stilllegen',reason:'Administrativer Grund',stateConfirm:'Ich bestätige diese destruktive Statusänderung.',incompleteApproval:'Die Aktivierung bleibt gesperrt, bis alle erforderlichen externen Freigaben erfasst sind.',
 history:'Unveränderbare Inbetriebnahmehistorie',historyUnavailable:'Die Belegshistorie ist nicht in der aktuellen Minimalansicht enthalten. Aktualisieren Sie, sobald der maßgebliche Dienst sie bereitstellt.',receipt:'Beleg',created:'Erstellt',lastUpdated:'Zuletzt aktualisiert',
 providerAudit:'Probelauf der Anbieterzusammenstellung',requestId:'ID der Mitgliederanfrage',compositionId:'ID der Anbieterzusammenstellung',channel:'Zulässiger Kanal',email:'E-Mail',sms:'SMS-Nachricht',push:'Push-Benachrichtigung',runDryRun:'Probelauf ohne Versand ausführen',dryRunConfirm:'Ich bestätige eine anbieterneutrale Prüfung ohne Lesen von Zugangsdaten, Zielauflösung oder Übertragung.',providerNotCommissioned:'Der Zustellanbieter ist nicht in Betrieb genommen. Eine erfolgreiche Prüfung bleibt unkonfiguriert und sendet nichts.',dryRuns:'Letzte Anbieterprobeläufe',
 jhcc:'JHCC-Berichtsprüfung',eventIds:'IDs berichtsbereiter Ereignisse, eine pro Zeile',validateJhcc:'Nicht aktiven JHCC-Port prüfen',jhccConfirm:'Ich bestätige die datensparsame Prüfung ohne Übertragung an JHCC.',jhccNotCommissioned:'Das JHCC-Ziel ist nicht in Betrieb genommen. Die Prüfung kann nichts übertragen.',reportValidations:'Letzte JHCC-Prüfungen',
 boundaries:'Erzwungene Grenzen',legalTextNotStored:'Kein Rechts- oder Kundennachrichtentext gespeichert',providerNotConfigured:'Keine Anbieterzugangsdaten oder -aufrufe',jhccNotConfigured:'Kein JHCC-Ziel oder -Versand',notificationsNotSent:'Keine E-Mail, SMS oder Push-Nachricht versendet',economyUnchanged:'Keine Buchung von Tee-Guthaben, Preis, Provision oder Abrechnung',none:'Nichts erfasst',
 statusPending:'Freigabe ausstehend',statusActive:'Aktiv',statusRejected:'Abgelehnt',statusRetired:'Stillgelegt',statusProviderUnconfigured:'Anbieter nicht konfiguriert — kein Versand',statusValidatedNoTransmission:'Geprüft — nicht übertragen',kindInvitation:'Einladung',kindResend:'Erneuter Versand',kindCorrection:'Korrekturanfrage',kindRejected:'Ablehnung',kindExpired:'Ablauf',kindSupport:'Supportantwort',confirmationRequired:'Eine ausdrückliche Bestätigung ist erforderlich.',
};

export const ENTERPRISE_MEMBER_COMMISSIONING_COPY:Record<AdminLocale,EnterpriseMemberCommissioningCopy>={en,th,ko,ja,zh,es,fr,de};
