import type {AdminLocale} from '../../components/admin/v2/adminNavigation';
const en={title:'Enterprise member requests',lead:'Review course-scoped requests without creating accounts, granting global roles, or asserting recipient consent.',refresh:'Refresh',loading:'Loading requests…',empty:'No matching requests.',unavailable:'The authoritative Admin request service is unavailable.',stale:'The queue is stale. Reload before making a decision.',offline:'Network unavailable. No decision was recorded.',retry:'Retry',search:'Search request reference',status:'Status',action:'Request type',organization:'Organization',course:'Course',all:'All',details:'Request details',history:'Immutable history',delivery:'Delivery orchestration',consent:'Consent and member lifecycle',conflicts:'CSV conflict resolution',support:'Support response preparation',close:'Close detail',decision:'Decision',reason:'Public correction or rejection reason',existing:'Existing course-member reference',policy:'Policy version',evidence:'Evidence digest',confirm:'I confirm this consequential Admin action',submit:'Apply decision',channel:'Channel',template:'Approved template ID',templateVersion:'Template version',legalBasis:'Purpose / legal-basis reference',prepare:'Prepare provider handoff',providerPending:'Only the approved versioned template may be prepared. Missing provider composition remains awaiting delivery provider.',noInternal:'Internal notes, raw identities, private contacts and operational scores are not exposed.',next:'Next page',previous:'Previous page',announcement:'Request updated.',failed:'The command was not accepted. Reload authoritative state and retry.',select:'Open request',rowDecision:'Row decision',approveDelivery:'Approve for delivery',duplicate:'Mark duplicate',reject:'Reject',requestCorrection:'Prepare support response / request corrected information',escalate:'Escalate identity / consent review',linkExisting:'Link existing course member',cancelDelivery:'Cancel before delivery',resolveRows:'Resolve confirmed rows',locale:'Locale',outbox:'Outbox state',reply:'Support response is prepared as a correction request; delivery remains provider-controlled.'};
export type EnterpriseMemberAdminCopy=typeof en;
const localized=(title:string,lead:string,empty:string,unavailable:string):EnterpriseMemberAdminCopy=>({...en,title,lead,empty,unavailable});
export const ENTERPRISE_MEMBER_ADMIN_COPY:Record<AdminLocale,EnterpriseMemberAdminCopy>={
 en,
 th:localized('คำขอสมาชิกองค์กร','ตรวจสอบคำขอตามขอบเขตสนามโดยไม่สร้างบัญชี ให้บทบาทส่วนกลาง หรืออ้างความยินยอมของผู้รับ','ไม่มีคำขอที่ตรงกัน','บริการคำขอผู้ดูแลระบบที่เชื่อถือได้ไม่พร้อมใช้งาน'),
 ko:localized('엔터프라이즈 회원 요청','계정을 만들거나 전역 역할 또는 수신자 동의를 주장하지 않고 코스 범위 요청을 검토합니다.','일치하는 요청이 없습니다.','권한 있는 관리자 요청 서비스를 사용할 수 없습니다.'),
 ja:localized('Enterprise会員リクエスト','アカウント作成、グローバル権限付与、受信者同意の主張を行わず、コース範囲の依頼を審査します。','該当する依頼はありません。','正規の管理者リクエストサービスを利用できません。'),
 zh:localized('企业会员请求','审核课程范围内的请求，不创建账户、不授予全局角色，也不声称收件人已同意。','没有匹配的请求。','权威管理员请求服务不可用。'),
 es:localized('Solicitudes de miembros Enterprise','Revisa solicitudes de curso sin crear cuentas, conceder roles globales ni afirmar el consentimiento del destinatario.','No hay solicitudes coincidentes.','El servicio autorizado de solicitudes Admin no está disponible.'),
 fr:localized('Demandes de membres Enterprise','Examinez les demandes limitées au parcours sans créer de compte, attribuer de rôle global ni affirmer le consentement du destinataire.','Aucune demande correspondante.','Le service Admin faisant autorité est indisponible.'),
 de:localized('Enterprise-Mitgliederanfragen','Kursbezogene Anfragen prüfen, ohne Konten, globale Rollen oder Empfängerzustimmung zu erzeugen.','Keine passenden Anfragen.','Der maßgebliche Admin-Anfragedienst ist nicht verfügbar.'),
};
