import type { LocaleDict } from '../dict';

export const ADMIN_PRESENTATION_KEYS = [
  'workspace','signOut','language','primaryNavigation','closeNavigation','menu','operations','admin',
  'overview','courses','bookings','partners','marketing','advertising','exchange','reports',
  'heroTitle','heroLead','boundaries','authority','authorityTitle','authorityLead','courseData','courseDataTitle','courseDataLead',
  'teeTimes','teeTimesTitle','teeTimesLead','areas','loading','error','retry','empty','reviewFlag',
] as const;
export type AdminPresentationKey = typeof ADMIN_PRESENTATION_KEYS[number];

export const ADMIN_PRESENTATION: LocaleDict<AdminPresentationKey> = {
  en:{workspace:'Operations workspace',signOut:'Secure sign out',language:'Language',primaryNavigation:'Primary navigation',closeNavigation:'Close navigation',menu:'Menu',operations:'Golfriend operations',admin:'Admin',overview:'Overview',courses:'Golf courses and booking data',bookings:'Booking communications',partners:'Partners and portal requests',marketing:'Marketing assets',advertising:'Advertising',exchange:'OEM and exchange publishing',reports:'Operational reports',heroTitle:'Keep every round connected.',heroLead:'One operational view for courses, bookings, partners, publishing and accountable reporting. Golfriend manages its own services here.',boundaries:'Operating boundaries',authority:'Authority',authorityTitle:'Server-owned actions',authorityLead:'Existing authorization and service boundaries remain the source of truth.',courseData:'Course data',courseDataTitle:'Protected synchronization',courseDataLead:'Preview, trusted records and manual location safeguards remain intact.',teeTimes:'Tee times',teeTimesTitle:'Communication, not settlement',teeTimesLead:'Golfriend coordinates booking operations and does not confirm external payments.',areas:'Operational areas',loading:'Loading…',error:'This information is unavailable.',retry:'Retry',empty:'Nothing to review yet.',reviewFlag:'Compliance-sensitive copy requires native and legal review.'},
  th:{workspace:'พื้นที่ปฏิบัติการ',signOut:'ออกจากระบบอย่างปลอดภัย',language:'ภาษา',primaryNavigation:'เมนูหลัก',closeNavigation:'ปิดเมนู',menu:'เมนู',operations:'งานปฏิบัติการ Golfriend',admin:'ผู้ดูแลระบบ',overview:'ภาพรวม',courses:'สนามกอล์ฟและข้อมูลการจอง',bookings:'การสื่อสารเรื่องการจอง',partners:'พาร์ตเนอร์และคำขอจากพอร์ทัล',marketing:'สื่อการตลาด',advertising:'โฆษณา',exchange:'การเผยแพร่ OEM และตลาดแลกเปลี่ยน',reports:'รายงานการปฏิบัติงาน',heroTitle:'เชื่อมโยงทุกรอบการเล่นให้ต่อเนื่อง',heroLead:'ดูแลงานสนาม การจอง พาร์ตเนอร์ การเผยแพร่ และรายงานที่ตรวจสอบได้จากที่เดียว โดย Golfriend ดูแลเฉพาะบริการของตน',boundaries:'ขอบเขตการปฏิบัติงาน',authority:'สิทธิ์ดำเนินการ',authorityTitle:'การดำเนินการที่เซิร์ฟเวอร์ควบคุม',authorityLead:'สิทธิ์และขอบเขตบริการที่มีอยู่ยังเป็นแหล่งข้อมูลอ้างอิง',courseData:'ข้อมูลสนาม',courseDataTitle:'ซิงก์ข้อมูลอย่างมีการป้องกัน',courseDataLead:'ยังคงใช้การแสดงตัวอย่าง ข้อมูลที่เชื่อถือได้ และการตรวจตำแหน่งด้วยเจ้าหน้าที่',teeTimes:'เวลาออกรอบ',teeTimesTitle:'สื่อสาร ไม่ใช่ชำระเงิน',teeTimesLead:'Golfriend ประสานงานการจองและไม่ยืนยันการชำระเงินผ่านระบบภายนอก',areas:'พื้นที่ปฏิบัติงาน',loading:'กำลังโหลด…',error:'ไม่สามารถแสดงข้อมูลนี้ได้',retry:'ลองอีกครั้ง',empty:'ยังไม่มีรายการให้ตรวจสอบ',reviewFlag:'ข้อความที่เกี่ยวกับการกำกับดูแลต้องให้เจ้าของภาษาและฝ่ายกฎหมายตรวจทาน'},
  ko:{workspace:'운영 작업 공간',signOut:'안전하게 로그아웃',language:'언어',primaryNavigation:'기본 탐색',closeNavigation:'탐색 닫기',menu:'메뉴',operations:'Golfriend 운영',admin:'관리자',overview:'개요',courses:'골프장 및 예약 데이터',bookings:'예약 커뮤니케이션',partners:'파트너 및 포털 요청',marketing:'마케팅 자료',advertising:'광고',exchange:'OEM 및 교환 게시',reports:'운영 보고서',heroTitle:'모든 라운드를 끊김 없이 연결하세요.',heroLead:'코스, 예약, 파트너, 게시 및 책임 있는 보고를 한곳에서 관리합니다. Golfriend는 자체 서비스만 운영합니다.',boundaries:'운영 범위',authority:'권한',authorityTitle:'서버가 관리하는 작업',authorityLead:'기존 승인 및 서비스 경계가 계속 기준이 됩니다.',courseData:'코스 데이터',courseDataTitle:'보호된 동기화',courseDataLead:'미리보기, 신뢰된 기록 및 수동 위치 보호 절차를 유지합니다.',teeTimes:'티타임',teeTimesTitle:'결제가 아닌 커뮤니케이션',teeTimesLead:'Golfriend는 예약 운영을 조율하며 외부 결제를 확정하지 않습니다.',areas:'운영 영역',loading:'불러오는 중…',error:'이 정보를 사용할 수 없습니다.',retry:'다시 시도',empty:'검토할 항목이 없습니다.',reviewFlag:'규정 관련 문구는 원어민 및 법무 검토가 필요합니다.'},
  ja:{workspace:'運用ワークスペース',signOut:'安全にサインアウト',language:'言語',primaryNavigation:'メインナビゲーション',closeNavigation:'ナビゲーションを閉じる',menu:'メニュー',operations:'Golfriend 運用',admin:'管理者',overview:'概要',courses:'ゴルフ場と予約データ',bookings:'予約連絡',partners:'パートナーとポータル申請',marketing:'マーケティング素材',advertising:'広告',exchange:'OEM・交換掲載',reports:'運用レポート',heroTitle:'すべてのラウンドを確実につなぐ。',heroLead:'コース、予約、パートナー、掲載、説明可能な報告を一か所で管理します。Golfriend は自社サービスのみを運用します。',boundaries:'運用範囲',authority:'権限',authorityTitle:'サーバー管理の操作',authorityLead:'既存の認可とサービス境界を引き続き正とします。',courseData:'コースデータ',courseDataTitle:'保護された同期',courseDataLead:'プレビュー、信頼済み記録、手動の位置確認を維持します。',teeTimes:'ティータイム',teeTimesTitle:'決済ではなく連絡',teeTimesLead:'Golfriend は予約運用を調整しますが、外部決済を確定しません。',areas:'運用エリア',loading:'読み込み中…',error:'この情報は利用できません。',retry:'再試行',empty:'確認する項目はありません。',reviewFlag:'コンプライアンス関連文言はネイティブおよび法務確認が必要です。'},
  zh:{workspace:'运营工作区',signOut:'安全退出',language:'语言',primaryNavigation:'主导航',closeNavigation:'关闭导航',menu:'菜单',operations:'Golfriend 运营',admin:'管理员',overview:'概览',courses:'球场与预订数据',bookings:'预订沟通',partners:'合作伙伴与门户请求',marketing:'营销素材',advertising:'广告',exchange:'OEM 与交换发布',reports:'运营报告',heroTitle:'让每一场球顺畅衔接。',heroLead:'集中管理球场、预订、合作伙伴、发布和可追溯报告。Golfriend 仅管理自身服务。',boundaries:'运营边界',authority:'权限',authorityTitle:'服务器控制的操作',authorityLead:'现有授权和服务边界仍是准确信息来源。',courseData:'球场数据',courseDataTitle:'受保护的同步',courseDataLead:'保留预览、可信记录和人工位置保护措施。',teeTimes:'开球时间',teeTimesTitle:'负责沟通，不处理结算',teeTimesLead:'Golfriend 协调预订运营，但不确认外部付款。',areas:'运营区域',loading:'正在加载…',error:'此信息暂不可用。',retry:'重试',empty:'目前没有待审核项目。',reviewFlag:'合规相关文案仍需母语人士和法务审核。'},
  es:{workspace:'Espacio de operaciones',signOut:'Cerrar sesión de forma segura',language:'Idioma',primaryNavigation:'Navegación principal',closeNavigation:'Cerrar navegación',menu:'Menú',operations:'Operaciones de Golfriend',admin:'Administración',overview:'Resumen',courses:'Campos y datos de reservas',bookings:'Comunicaciones de reservas',partners:'Socios y solicitudes del portal',marketing:'Recursos de marketing',advertising:'Publicidad',exchange:'Publicación OEM e intercambio',reports:'Informes operativos',heroTitle:'Mantén conectada cada ronda.',heroLead:'Gestiona campos, reservas, socios, publicaciones e informes verificables desde un solo lugar. Golfriend administra únicamente sus propios servicios.',boundaries:'Límites operativos',authority:'Autoridad',authorityTitle:'Acciones controladas por el servidor',authorityLead:'Las autorizaciones y los límites de servicio existentes siguen siendo la fuente de referencia.',courseData:'Datos de campos',courseDataTitle:'Sincronización protegida',courseDataLead:'Se mantienen las vistas previas, los registros fiables y las salvaguardas manuales de ubicación.',teeTimes:'Horarios de salida',teeTimesTitle:'Comunicación, no liquidación',teeTimesLead:'Golfriend coordina las reservas y no confirma pagos externos.',areas:'Áreas operativas',loading:'Cargando…',error:'Esta información no está disponible.',retry:'Reintentar',empty:'Aún no hay nada que revisar.',reviewFlag:'El texto de cumplimiento requiere revisión nativa y legal.'},
  fr:{workspace:'Espace des opérations',signOut:'Déconnexion sécurisée',language:'Langue',primaryNavigation:'Navigation principale',closeNavigation:'Fermer la navigation',menu:'Menu',operations:'Opérations Golfriend',admin:'Administration',overview:'Vue d’ensemble',courses:'Parcours et données de réservation',bookings:'Communications de réservation',partners:'Partenaires et demandes du portail',marketing:'Ressources marketing',advertising:'Publicité',exchange:'Publication OEM et échange',reports:'Rapports opérationnels',heroTitle:'Gardez chaque partie bien connectée.',heroLead:'Gérez les parcours, réservations, partenaires, publications et rapports traçables depuis un seul espace. Golfriend gère uniquement ses propres services.',boundaries:'Limites opérationnelles',authority:'Autorité',authorityTitle:'Actions contrôlées par le serveur',authorityLead:'Les autorisations et limites de service existantes restent la référence.',courseData:'Données des parcours',courseDataTitle:'Synchronisation protégée',courseDataLead:'Les aperçus, données fiables et contrôles manuels de localisation sont conservés.',teeTimes:'Départs',teeTimesTitle:'Communication, pas règlement',teeTimesLead:'Golfriend coordonne les réservations sans confirmer les paiements externes.',areas:'Domaines opérationnels',loading:'Chargement…',error:'Ces informations sont indisponibles.',retry:'Réessayer',empty:'Aucun élément à examiner.',reviewFlag:'Le texte de conformité doit être relu par un locuteur natif et le service juridique.'},
  de:{workspace:'Betriebsbereich',signOut:'Sicher abmelden',language:'Sprache',primaryNavigation:'Hauptnavigation',closeNavigation:'Navigation schließen',menu:'Menü',operations:'Golfriend Betrieb',admin:'Administration',overview:'Übersicht',courses:'Golfplätze und Buchungsdaten',bookings:'Buchungskommunikation',partners:'Partner und Portal-Anfragen',marketing:'Marketingmaterialien',advertising:'Werbung',exchange:'OEM- und Börsenveröffentlichung',reports:'Betriebsberichte',heroTitle:'Jede Runde zuverlässig verbinden.',heroLead:'Plätze, Buchungen, Partner, Veröffentlichungen und nachvollziehbare Berichte an einem Ort verwalten. Golfriend betreibt ausschließlich eigene Dienste.',boundaries:'Betriebsgrenzen',authority:'Berechtigung',authorityTitle:'Servergesteuerte Aktionen',authorityLead:'Bestehende Berechtigungen und Dienstgrenzen bleiben maßgeblich.',courseData:'Platzdaten',courseDataTitle:'Geschützte Synchronisierung',courseDataLead:'Vorschau, vertrauenswürdige Datensätze und manuelle Standortprüfungen bleiben erhalten.',teeTimes:'Startzeiten',teeTimesTitle:'Kommunikation statt Abrechnung',teeTimesLead:'Golfriend koordiniert Buchungen und bestätigt keine externen Zahlungen.',areas:'Betriebsbereiche',loading:'Wird geladen…',error:'Diese Informationen sind nicht verfügbar.',retry:'Erneut versuchen',empty:'Derzeit gibt es nichts zu prüfen.',reviewFlag:'Compliance-Texte müssen muttersprachlich und rechtlich geprüft werden.'},
};

export const ADMIN_ANALYTICS_PRESENTATION: LocaleDict<'analytics' | 'tee-analytics'> = {
  en:{analytics:'Country user analytics','tee-analytics':'Tee economy analytics'},
  th:{analytics:'การวิเคราะห์ผู้ใช้ตามประเทศ','tee-analytics':'การวิเคราะห์เศรษฐกิจ Tee'},
  ko:{analytics:'국가별 사용자 분석','tee-analytics':'Tee 경제 분석'},
  ja:{analytics:'国別ユーザー分析','tee-analytics':'Tee エコノミー分析'},
  zh:{analytics:'国家或地区用户分析','tee-analytics':'Tee 经济分析'},
  es:{analytics:'Análisis de usuarios por país','tee-analytics':'Análisis de la economía Tee'},
  fr:{analytics:'Analyse des utilisateurs par pays','tee-analytics':'Analyse de l’économie Tee'},
  de:{analytics:'Nutzeranalyse nach Land','tee-analytics':'Tee-Wirtschaftsanalyse'},
};

export const ADMIN_CONTROL_PRESENTATION: LocaleDict<'economy'> = {
  en:{economy:'Economy master controls'},th:{economy:'การควบคุมเศรษฐกิจหลัก'},ko:{economy:'경제 마스터 제어'},ja:{economy:'エコノミーマスター管理'},zh:{economy:'经济主控'},es:{economy:'Controles maestros de economía'},fr:{economy:'Contrôles maîtres de l’économie'},de:{economy:'Zentrale Wirtschaftssteuerung'},
};
