import {useState} from 'react';import{getFunctions,httpsCallable}from'firebase/functions';
import {LOCALE_CODES,type CanonicalLocale} from '../../../i18n/locales';
const LOCALES=LOCALE_CODES;type Locale=CanonicalLocale;
const COPY:Record<Locale,{title:string;intro:string;course:string;relationship:string;correction:string;evidence:string;contact:string;consent:string;submit:string;sent:string;error:string}>={
en:{title:'Request a course correction',intro:'Your request cannot change the public catalogue. Golfriend Admin reviews the evidence and decides.',course:'Canonical course ID',relationship:'Your relationship to the course',correction:'Proposed correction',evidence:'Evidence reference',contact:'Contact preference',consent:'I consent to Golfriend reviewing this request and evidence.',submit:'Submit correction request',sent:'Request submitted for Admin review.',error:'The request was not accepted. Check the fields and retry.'},
th:{title:'ขอแก้ไขข้อมูลสนาม',intro:'คำขอนี้เปลี่ยนแค็ตตาล็อกสาธารณะไม่ได้ ผู้ดูแล Golfriend จะตรวจหลักฐานและตัดสินใจ',course:'รหัสสนามมาตรฐาน',relationship:'ความสัมพันธ์ของคุณกับสนาม',correction:'ข้อเสนอแก้ไข',evidence:'แหล่งอ้างอิงหลักฐาน',contact:'ช่องทางติดต่อที่ต้องการ',consent:'ฉันยินยอมให้ Golfriend ตรวจคำขอและหลักฐานนี้',submit:'ส่งคำขอแก้ไข',sent:'ส่งคำขอให้ผู้ดูแลตรวจแล้ว',error:'ไม่รับคำขอ โปรดตรวจข้อมูลและลองใหม่'},
ko:{title:'코스 수정 요청',intro:'이 요청은 공개 카탈로그를 변경할 수 없습니다. Golfriend 관리자가 증거를 검토하고 결정합니다.',course:'정규 코스 ID',relationship:'코스와의 관계',correction:'제안 수정',evidence:'증거 참조',contact:'연락 선호',consent:'Golfriend가 요청과 증거를 검토하는 데 동의합니다.',submit:'수정 요청 제출',sent:'관리자 검토용 요청이 제출되었습니다.',error:'요청이 접수되지 않았습니다. 입력을 확인하고 다시 시도하세요.'},
ja:{title:'コース修正を依頼',intro:'この依頼は公開カタログを変更できません。Golfriend Admin が証拠を確認し判断します。',course:'正規コース ID',relationship:'コースとの関係',correction:'修正案',evidence:'証拠参照',contact:'連絡方法',consent:'Golfriend が依頼と証拠を確認することに同意します。',submit:'修正依頼を送信',sent:'Admin 確認用に送信しました。',error:'依頼を受理できませんでした。入力を確認して再試行してください。'},
zh:{title:'申请更正球场资料',intro:'此申请不能修改公开目录。Golfriend 管理员将审核证据并作出决定。',course:'权威球场 ID',relationship:'您与球场的关系',correction:'建议更正',evidence:'证据引用',contact:'联系偏好',consent:'我同意 Golfriend 审核此申请及证据。',submit:'提交更正申请',sent:'申请已提交管理员审核。',error:'申请未被接受，请检查内容后重试。'},
es:{title:'Solicitar corrección de campo',intro:'La solicitud no puede cambiar el catálogo público. Golfriend Admin revisa la prueba y decide.',course:'ID canónico del campo',relationship:'Relación con el campo',correction:'Corrección propuesta',evidence:'Referencia de prueba',contact:'Preferencia de contacto',consent:'Consiento que Golfriend revise la solicitud y la prueba.',submit:'Enviar solicitud',sent:'Solicitud enviada a revisión.',error:'No se aceptó la solicitud. Revisa los campos y reintenta.'},
fr:{title:'Demander une correction',intro:'Cette demande ne peut pas modifier le catalogue public. Golfriend Admin examine les preuves et décide.',course:'ID canonique du parcours',relationship:'Votre lien avec le parcours',correction:'Correction proposée',evidence:'Référence de preuve',contact:'Préférence de contact',consent:'J’accepte que Golfriend examine cette demande et ses preuves.',submit:'Envoyer la demande',sent:'Demande transmise au contrôle Admin.',error:'Demande refusée. Vérifiez les champs et réessayez.'},
de:{title:'Platzkorrektur anfragen',intro:'Diese Anfrage kann den öffentlichen Katalog nicht ändern. Golfriend Admin prüft die Nachweise und entscheidet.',course:'Verbindliche Platz-ID',relationship:'Beziehung zum Platz',correction:'Vorgeschlagene Korrektur',evidence:'Nachweisreferenz',contact:'Kontaktwunsch',consent:'Ich stimme der Prüfung dieser Anfrage und Nachweise durch Golfriend zu.',submit:'Korrekturanfrage senden',sent:'Anfrage zur Admin-Prüfung gesendet.',error:'Anfrage nicht angenommen. Angaben prüfen und erneut versuchen.'}};
export default function CourseCorrectionRequest(){const[locale,setLocale]=useState<Locale>('en'),[course,setCourse]=useState(''),[relationship,setRelationship]=useState(''),[correction,setCorrection]=useState(''),[evidence,setEvidence]=useState(''),[contact,setContact]=useState('email'),[consent,setConsent]=useState(false),[state,setState]=useState<'idle'|'sending'|'sent'|'error'>('idle'),copy=COPY[locale];const submit=async()=>{setState('sending');try{const response=await httpsCallable(getFunctions(),'submitCourseCorrectionRequest')({canonicalCourseId:course,claimedRelationship:relationship,proposedCorrection:correction,evidenceReference:evidence,contactPreference:contact,locale,consent});const value=response.data as Record<string,unknown>;if(value.state!=='submitted'||value.canonicalMutation!==false)throw Error('INVALID');setState('sent');}catch{setState('error');}};return <section style={{background:'#111',border:'1px solid #333',borderRadius:8,padding:20,marginTop:20}} aria-labelledby="course-correction-title"><h3 id="course-correction-title" style={{color:'#d4af37'}}>{copy.title}</h3><p>{copy.intro}</p><label>Language<select value={locale} onChange={e=>setLocale(e.target.value as Locale)}>{LOCALES.map(x=><option key={x}>{x}</option>)}</select></label><label>{copy.course}<input value={course} maxLength={160} onChange={e=>setCourse(e.target.value)}/></label><label>{copy.relationship}<input value={relationship} maxLength={120} onChange={e=>setRelationship(e.target.value)}/></label><label>{copy.correction}<textarea value={correction} maxLength={1000} onChange={e=>setCorrection(e.target.value)}/></label><label>{copy.evidence}<input value={evidence} maxLength={500} onChange={e=>setEvidence(e.target.value)}/></label><label>{copy.contact}<select value={contact} onChange={e=>setContact(e.target.value)}><option value="email">Email</option><option value="portal">Portal</option></select></label><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{copy.consent}</label><button style={{minHeight:48}} disabled={state==='sending'||!consent} onClick={()=>void submit()}>{copy.submit}</button>{state==='sent'&&<p role="status">{copy.sent}</p>}{state==='error'&&<p role="alert">{copy.error}</p>}</section>}
