// @ts-nocheck -- Executed directly by Node's type-stripper.
import assert from "node:assert/strict";import test from "node:test";
import {CourseProfileOperationsService} from "./courseProfileOperationsService.ts";import {COURSE_PROFILE_OPERATIONS_SCHEMA,COURSE_PROFILE_LOCALES} from "./courseProfileOperationsModel.ts";
const context={actorMembershipId:"m1",organizationId:"o1",propertyId:"p1",courseId:"c1",role:"course_manager",scope:{kind:"course",organizationId:"o1",propertyId:"p1",courseId:"c1"},organizationStatus:"active",courseStatus:"active"};
const content=Object.fromEntries(COURSE_PROFILE_LOCALES.map(l=>[l,{name:`Name ${l}`,description:`Description ${l}`} ]));
const projection={schema:COURSE_PROFILE_OPERATIONS_SCHEMA,producerSchema:COURSE_PROFILE_OPERATIONS_SCHEMA,state:"pending",canonicalCourseId:"c1",sourceUpdatedAt:"2026-08-15T00:00:00Z",retryable:false,supportReference:null,approvedProfile:{courseId:"c1",organizationId:"o1",propertyId:"p1",version:4,content,approvedAt:"2026-08-14T00:00:00Z"},editAttempt:{attemptId:"a1",courseId:"c1",organizationId:"o1",propertyId:"p1",baseVersion:4,attemptVersion:1,state:"pending",submittedAt:"2026-08-15T00:00:00Z",content},references:[]};
const producer={schema:COURSE_PROFILE_OPERATIONS_SCHEMA,async read(){return projection},async submit(){return projection}};
test("missing producer fails closed",async()=>assert.equal((await new CourseProfileOperationsService().read(context)).state,"unavailable"));
test("suspension fails closed",async()=>assert.equal((await new CourseProfileOperationsService(producer).read({...context,courseStatus:"suspended"})).state,"suspended"));
test("organization role has no implicit course authority",async()=>assert.equal((await new CourseProfileOperationsService(producer).read({...context,role:"organization_admin",scope:{kind:"organization",organizationId:"o1"}})).supportReference,"COURSE_PROFILE_SCOPE_DENIED"));
test("cross-course projection is rejected",async()=>{const bad={...producer,async read(){return {...projection,canonicalCourseId:"c2"}}};assert.equal((await new CourseProfileOperationsService(bad).read(context)).supportReference,"COURSE_PROFILE_PROJECTION_REJECTED")});
test("approved profile remains present while edit is pending",async()=>{const result=await new CourseProfileOperationsService(producer).read(context);assert.equal(result.approvedProfile.version,4);assert.equal(result.editAttempt.state,"pending")});
test("incomplete eight-locale command is rejected before producer",async()=>{const incomplete={...content,de:{name:"",description:""}};assert.equal((await new CourseProfileOperationsService(producer).submit(context,{commandId:"cmd",canonicalCourseId:"c1",baseVersion:4,attemptVersion:1,content:incomplete})).supportReference,"COURSE_PROFILE_COMMAND_REJECTED")});
test("canonical course id cannot be changed by client",async()=>assert.equal((await new CourseProfileOperationsService(producer).submit(context,{commandId:"cmd",canonicalCourseId:"c2",baseVersion:4,attemptVersion:1,content})).supportReference,"COURSE_PROFILE_COMMAND_REJECTED"));
