// @ts-nocheck -- Executed directly by Node's type-stripper.
import assert from "node:assert/strict"; import test from "node:test";
import {EnterpriseMemberLinkingService} from "./memberLinkingService.ts"; import {MEMBER_LINKING_SCHEMA} from "./memberLinkingModel.ts";
const context={actorMembershipId:"m1",organizationId:"o1",propertyId:"p1",courseId:"c1",role:"course_manager",scope:{kind:"course",organizationId:"o1",propertyId:"p1",courseId:"c1"},organizationStatus:"active",courseStatus:"active"};
const empty={schema:MEMBER_LINKING_SCHEMA,producerSchema:MEMBER_LINKING_SCHEMA,state:"empty",sourceUpdatedAt:"2026-08-15T00:00:00Z",retryable:false,supportReference:null,links:[],receipts:[]};
const producer={schema:MEMBER_LINKING_SCHEMA,supportsDirectorySearch:false,infersAdditionalConsent:false,async read(){return empty},async inviteKnownGolfer(){return empty},async unlink(){return empty}};
test("absent producer is honestly unavailable",async()=>assert.equal((await new EnterpriseMemberLinkingService().read(context)).state,"unavailable"));
test("suspension fails closed",async()=>assert.equal((await new EnterpriseMemberLinkingService(producer).read({...context,organizationStatus:"suspended"})).state,"suspended"));
test("course suspension fails closed",async()=>assert.equal((await new EnterpriseMemberLinkingService(producer).read({...context,courseStatus:"suspended"})).state,"suspended"));
test("organization-wide scope never implies course access",async()=>assert.equal((await new EnterpriseMemberLinkingService(producer).read({...context,scope:{kind:"organization",organizationId:"o1"}})).supportReference,"MEMBER_LINKING_COURSE_SCOPE_DENIED"));
test("directory-search capable producer is rejected",async()=>assert.equal((await new EnterpriseMemberLinkingService({...producer,supportsDirectorySearch:true}).read(context)).state,"unavailable"));
test("producer that infers other consent is rejected",async()=>assert.equal((await new EnterpriseMemberLinkingService({...producer,infersAdditionalConsent:true}).read(context)).state,"unavailable"));
test("known-golfer invitation is exact-scope and version bound",async()=>{assert.equal((await new EnterpriseMemberLinkingService(producer).inviteKnownGolfer(context,{commandId:"cmd",organizationId:"o1",propertyId:"p1",courseId:"c1",knownGolferId:"g1",consentVersion:2})).state,"empty");assert.equal((await new EnterpriseMemberLinkingService(producer).inviteKnownGolfer(context,{commandId:"cmd",organizationId:"o2",propertyId:"p1",courseId:"c1",knownGolferId:"g1",consentVersion:2})).supportReference,"MEMBER_LINKING_COMMAND_REJECTED")});
test("cross-course projection is rejected",async()=>{const bad={...producer,async read(){return {...empty,state:"current",links:[{linkId:"l",organizationId:"o1",propertyId:"p1",courseId:"c2",memberReference:"mem",golferDisplayLabel:"G",state:"accepted",consentVersion:1,expiresAt:null,updatedAt:"2026-08-15T00:00:00Z"}]}}};assert.equal((await new EnterpriseMemberLinkingService(bad).read(context)).supportReference,"MEMBER_LINKING_PROJECTION_SCOPE_REJECTED")});
test("unlink is version-bound and either-party receipts are accepted",async()=>{const withReceipt={...producer,async unlink(){return {...empty,state:"current",receipts:[{receiptId:"r",linkId:"l",organizationId:"o1",propertyId:"p1",courseId:"c1",action:"unlinked",consentVersion:3,actorKind:"verified_golfer",occurredAt:"2026-08-15T00:00:00Z",immutable:true}]}}};assert.equal((await new EnterpriseMemberLinkingService(withReceipt).unlink(context,{commandId:"cmd",organizationId:"o1",propertyId:"p1",courseId:"c1",linkId:"l",consentVersion:3})).receipts[0].actorKind,"verified_golfer")});
test("producer failures become honest unavailable projections",async()=>{const throwing={...producer,async read(){throw new Error("offline")}};assert.equal((await new EnterpriseMemberLinkingService(throwing).read(context)).supportReference,"MEMBER_LINKING_PRODUCER_READ_FAILED")});
test("minimum projection strips undeclared private producer fields",async()=>{const privateProducer={...producer,async read(){return {...empty,state:"current",links:[{linkId:"l",organizationId:"o1",propertyId:"p1",courseId:"c1",memberReference:"mem",golferDisplayLabel:"G",state:"accepted",consentVersion:1,expiresAt:null,updatedAt:"2026-08-15T00:00:00Z",privateNotes:"never retain",bookings:["secret"]}]}}};const result=await new EnterpriseMemberLinkingService(privateProducer).read(context);assert.equal("privateNotes" in result.links[0],false);assert.equal("bookings" in result.links[0],false)});
