export const STAFF_REMOVAL_LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export type StaffRemovalLocale=typeof STAFF_REMOVAL_LOCALES[number];
type Copy={remove:string;confirm:string;removed:string;replayed:string;failed:string;reason:string;reasons:Record<string,string>};
const reasons=(a:string,b:string,c:string,d:string,e:string)=>({left_organization:a,role_no_longer_required:b,access_review:c,requested_by_staff:d,security_concern:e});
export const STAFF_REMOVAL_COPY:Record<StaffRemovalLocale,Copy>={
 en:{remove:"Remove",confirm:"Remove this staff member? An immutable audit receipt will be recorded.",removed:"Staff access removed.",replayed:"Removal already completed.",failed:"Staff removal was not accepted.",reason:"Removal reason",reasons:reasons("Left organization","Role no longer required","Access review","Requested by staff","Security concern")},
 th:{remove:"นำออก",confirm:"นำพนักงานรายนี้ออกหรือไม่ ระบบจะบันทึกหลักฐานตรวจสอบถาวร",removed:"นำสิทธิ์พนักงานออกแล้ว",replayed:"คำขอนำออกนี้เสร็จสิ้นแล้ว",failed:"ระบบไม่ยอมรับการนำพนักงานออก",reason:"เหตุผลในการนำออก",reasons:reasons("ออกจากองค์กร","ไม่จำเป็นต้องใช้บทบาทนี้แล้ว","ทบทวนสิทธิ์เข้าถึง","พนักงานร้องขอ","ข้อกังวลด้านความปลอดภัย")},
 ko:{remove:"제거",confirm:"이 직원을 제거하시겠습니까? 변경 불가 감사 영수증이 기록됩니다.",removed:"직원 접근 권한이 제거되었습니다.",replayed:"제거 요청이 이미 완료되었습니다.",failed:"직원 제거가 승인되지 않았습니다.",reason:"제거 사유",reasons:reasons("조직 퇴사","역할 불필요","접근 권한 검토","직원 요청","보안 우려")},
 ja:{remove:"削除",confirm:"このスタッフを削除しますか。変更不可の監査記録が保存されます。",removed:"スタッフのアクセス権を削除しました。",replayed:"この削除は完了済みです。",failed:"スタッフ削除は受理されませんでした。",reason:"削除理由",reasons:reasons("組織を離れた","役割が不要","アクセス権の確認","スタッフ本人の希望","セキュリティ上の懸念")},
 zh:{remove:"移除",confirm:"要移除此员工吗？系统将记录不可变更的审计凭据。",removed:"员工访问权限已移除。",replayed:"该移除请求已完成。",failed:"员工移除请求未被接受。",reason:"移除原因",reasons:reasons("已离开组织","不再需要该角色","访问权限审查","员工本人请求","安全问题")},
 es:{remove:"Quitar",confirm:"¿Quitar a este miembro? Se registrará un comprobante de auditoría inmutable.",removed:"Acceso del miembro eliminado.",replayed:"La eliminación ya se completó.",failed:"La eliminación no fue aceptada.",reason:"Motivo de eliminación",reasons:reasons("Dejó la organización","Rol ya no necesario","Revisión de acceso","Solicitud del miembro","Problema de seguridad")},
 fr:{remove:"Retirer",confirm:"Retirer ce membre ? Un reçu d’audit immuable sera enregistré.",removed:"Accès du membre retiré.",replayed:"Le retrait est déjà terminé.",failed:"Le retrait du membre n’a pas été accepté.",reason:"Motif du retrait",reasons:reasons("A quitté l’organisation","Rôle devenu inutile","Révision des accès","Demande du membre","Problème de sécurité")},
 de:{remove:"Entfernen",confirm:"Dieses Teammitglied entfernen? Ein unveränderlicher Prüfbeleg wird gespeichert.",removed:"Mitarbeiterzugriff entfernt.",replayed:"Die Entfernung wurde bereits abgeschlossen.",failed:"Die Entfernung wurde nicht angenommen.",reason:"Entfernungsgrund",reasons:reasons("Organisation verlassen","Rolle nicht mehr erforderlich","Zugriffsprüfung","Auf Wunsch des Mitarbeiters","Sicherheitsbedenken")},
};
export function staffRemovalLocale(value:string):StaffRemovalLocale{const key=value.toLowerCase().split("-")[0] as StaffRemovalLocale;return STAFF_REMOVAL_LOCALES.includes(key)?key:"en"}
