// @ts-nocheck -- Executed directly by Node's type-stripper.
import assert from "node:assert/strict";
import test from "node:test";
import {EnterpriseTournamentOperationsService, type EnterpriseTournamentProducer} from "./tournamentOperationsService.ts";
import {TOURNAMENT_OPERATIONS_SCHEMA, type TournamentAuthorityContext} from "./tournamentOperationsModel.ts";

const context: TournamentAuthorityContext = {actorMembershipId:"membership-1",organizationId:"org-1",propertyId:"property-1",courseId:"course-1",role:"tournament_staff",scope:{kind:"course",organizationId:"org-1",propertyId:"property-1",courseId:"course-1"},organizationStatus:"active"};
const empty = {schema:TOURNAMENT_OPERATIONS_SCHEMA,producerSchema:TOURNAMENT_OPERATIONS_SCHEMA,state:"empty" as const,sourceUpdatedAt:"2026-08-15T00:00:00.000Z",retryable:false,supportReference:null,references:[],tournaments:[]};

test("producer absence is honestly unavailable", async()=>assert.equal((await new EnterpriseTournamentOperationsService().read(context)).state,"unavailable"));
test("organization roles have no implicit tournament read access",async()=>{const producer:EnterpriseTournamentProducer={schema:TOURNAMENT_OPERATIONS_SCHEMA,financialAuthority:false,async read(){throw new Error("must not run")}};assert.equal((await new EnterpriseTournamentOperationsService(producer).read({...context,role:"organization_admin",scope:{kind:"organization",organizationId:"org-1"}})).supportReference,"TOURNAMENT_COURSE_SCOPE_DENIED")});
test("suspension removes read authority",async()=>assert.equal((await new EnterpriseTournamentOperationsService().read({...context,organizationStatus:"suspended"})).state,"suspended"));
test("exact scoped empty projection is accepted",async()=>{const producer:EnterpriseTournamentProducer={schema:TOURNAMENT_OPERATIONS_SCHEMA,financialAuthority:false,async read(){return empty}};assert.equal((await new EnterpriseTournamentOperationsService(producer).read(context)).state,"empty")});
test("wrong-scope tournament projection is rejected",async()=>{const producer:EnterpriseTournamentProducer={schema:TOURNAMENT_OPERATIONS_SCHEMA,financialAuthority:false,async read(){return {...empty,state:"current" as const,tournaments:[{tournamentId:"t-2",organizationId:"org-2",propertyId:"p-2",courseId:"c-2",name:"Private",startsAt:"2026-09-01T00:00:00.000Z",capacity:20,participantCount:1,state:"approved" as const,version:1,updatedAt:"2026-08-15T00:00:00.000Z",responsibilityTermsVersion:"v1"}]}}};assert.equal((await new EnterpriseTournamentOperationsService(producer).read(context)).state,"unavailable")});
test("mutable or wrong-scope references are rejected",async()=>{const producer:EnterpriseTournamentProducer={schema:TOURNAMENT_OPERATIONS_SCHEMA,financialAuthority:false,async read(){return {...empty,state:"current" as const,references:[{referenceId:"r",commandId:"c",tournamentId:"t",organizationId:"org-1",propertyId:"property-1",courseId:"course-1",action:"reviewed",authorityVersion:1,occurredAt:"2026-08-15T00:00:00.000Z",immutable:false as true}]}}};assert.equal((await new EnterpriseTournamentOperationsService(producer).read(context)).state,"unavailable")});
test("financial producer capability is rejected",async()=>{const producer={schema:TOURNAMENT_OPERATIONS_SCHEMA,financialAuthority:true,async read(){return empty}} as unknown as EnterpriseTournamentProducer;assert.equal((await new EnterpriseTournamentOperationsService(producer).read(context)).state,"unavailable")});
