import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
const index = readFileSync(resolve(process.cwd(), 'src/index.ts'), 'utf8');
const plan = readFileSync(resolve(process.cwd(), 'src/syncPlan.ts'), 'utf8');
const manifest = readFileSync(resolve(process.cwd(), 'package.json'), 'utf8');
const config = JSON.parse(readFileSync(resolve(process.cwd(), '../firebase.golf-api.json'), 'utf8')) as { functions?: unknown; hosting?: unknown };
assert.match(index, /region: REGION/);
assert.match(index, /REGION = 'asia-southeast1'/);
assert.match(index, /requireStaffOrDirector/);
assert.match(index, /parsePreviewRequest/);
assert.match(index, /parseApplyRequest/);
assert.match(plan, /MONTHLY_PROVIDER_REQUEST_BUDGET = 100/);
assert.match(index, /golfApiUsage/);
assert.match(index, /golf_api_sync_audit/);
assert.match(index, /getGolfApiSyncStatus/);
assert.match(index, /buildGolfApiSyncStatus/);
assert.match(index, /export const runGolfApiIngestion = onSchedule\(\{ region: REGION, schedule: 'every 15 minutes'/);
assert.match(index, /golf_api_ingestion_jobs/);
const previewCallable = index.slice(index.indexOf('export const syncCoursesFromProvider'), index.indexOf('export const getGolfApiSyncStatus'));
const previewBranch = previewCallable.slice(previewCallable.indexOf("if (mode === 'preview')"), previewCallable.indexOf("if (mode !== 'apply')"));
assert.doesNotMatch(previewBranch, /fetchProviderOutcome|usage\.get|usage\.set|\.create\(|\.update\(/);
const applyBranch = previewCallable.slice(previewCallable.indexOf("if (mode !== 'apply')"));
assert.doesNotMatch(applyBranch, /fetchProviderOutcome/);
const worker = index.slice(index.indexOf('export const runGolfApiIngestion'));
assert.match(worker, /fetchProviderOutcome/);
assert.match(worker, /leaseUntil/);
const statusCallable = index.slice(index.indexOf('export const getGolfApiSyncStatus'));
assert.match(statusCallable, /await requireStaffOrDirector\(request\.auth\.uid\)/);
assert.doesNotMatch(index, /stripe|booking|portal|hosting|vision|economy|nightlyCourseHealer|weeklyVaultJanitor/i);
assert.doesNotMatch(manifest, /stripe|vision|booking/i);
assert.equal(config.hosting, undefined);
assert.deepEqual(config.functions, [{ source: 'functions-golf-api', codebase: 'golf-api', disallowLegacyRuntimeConfig: true, ignore: ['node_modules', '.git', 'firebase-debug.log', 'firebase-debug.*.log', '*.local'], predeploy: ['npm --prefix "$RESOURCE_DIR" run build'] }]);
console.log('golf-api isolation: only regional Golf API callable, no unrelated function codebase or Hosting passed.');
