#!/usr/bin/env node
import fs from 'node:fs';
import {createRequire} from 'node:module';

const require=createRequire(import.meta.url),d=require('../../../functions-course-catalogue/domain.js');
const packet=JSON.parse(fs.readFileSync(process.argv[2]||new URL('./packet.json',import.meta.url),'utf8'));
const fail=message=>{throw Error(message);},equal=(actual,expected,message)=>{if(actual!==expected)fail(`${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);},same=(actual,expected,message)=>equal(d.canonicalJson(actual),d.canonicalJson(expected),message);
const payload={...packet};delete payload.packetDigest;equal(d.digest(payload),packet.packetDigest,'PACKET_DIGEST_INVALID');equal(packet.immutable,true,'PACKET_NOT_IMMUTABLE');
equal(packet.deployment.result,'success','DEPLOYMENT_NOT_SUCCESSFUL');equal(packet.deployment.providerRequests,0,'PROVIDER_REQUESTS_NONZERO');equal(packet.deployment.calibrationCalls,0,'CALIBRATION_CALLS_NONZERO');equal(packet.deployment.canaryCalls,0,'CANARY_CALLS_NONZERO');equal(packet.deployment.secretValueAccessed,false,'SECRET_VALUE_ACCESSED');
equal(packet.secretMetadata.name,'GOLF_API_KEY','SECRET_NAME_INVALID');equal(packet.secretMetadata.version,'2','SECRET_VERSION_INVALID');equal(packet.secretMetadata.state,'ENABLED','SECRET_STATE_INVALID');
const activation=packet.activationReceipt;equal(d.activationReceiptMatches(activation.payload,activation.digest),true,'ACTIVATION_DIGEST_INVALID');equal(activation.state,'verified','ACTIVATION_NOT_VERIFIED');equal(activation.bindingState,'current','ACTIVATION_NOT_CURRENT');equal(activation.immutable,true,'ACTIVATION_NOT_IMMUTABLE');
const expectedFunctions=['runGolfApiCalibrationCanary','scheduledGolfApiCatalogueCanary','scheduledGolfApiCatalogueIncremental','scheduledGolfApiCatalogueRetries'];same(Object.keys(packet.providerFunctions).sort(),expectedFunctions,'PROVIDER_FUNCTION_SET_INVALID');const expectedServices=Object.values(packet.providerFunctions).map(item=>item.service).sort();
for(const [name,fn] of Object.entries(packet.providerFunctions)){equal(fn.state,'ACTIVE',`FUNCTION_NOT_ACTIVE:${name}`);equal(fn.secretBinding.version,'2',`FUNCTION_SECRET_VERSION_INVALID:${name}`);const revision=d.normalizeRevisionIdentity(fn.revisionResource,fn.service);if(!revision)fail(`FUNCTION_REVISION_MALFORMED:${name}`);equal(d.activationRevisionBindingsMatch(activation.payload.functionRevisions,expectedServices,fn.service,revision),true,`FUNCTION_REVISION_UNBOUND:${name}`);}
equal(packet.calibrationArmFunction.state,'ACTIVE','CALIBRATION_ARM_NOT_ACTIVE');equal(packet.calibrationArmFunction.service,'armgolfapicalibrationcanary','CALIBRATION_ARM_IDENTITY_INVALID');equal(packet.calibrationArmFunction.secretBindings.length,0,'CALIBRATION_ARM_SECRET_BINDING_UNEXPECTED');equal(d.normalizeRevisionIdentity(packet.calibrationArmFunction.revisionResource,packet.calibrationArmFunction.service)!==null,true,'CALIBRATION_ARM_REVISION_INVALID');
const expectedSchedulers=['scheduledGolfApiCatalogueCanary','scheduledGolfApiCatalogueIncremental','scheduledGolfApiCatalogueRetries'];same(Object.keys(packet.schedulers).sort(),expectedSchedulers,'SCHEDULER_SET_INVALID');for(const [name,job] of Object.entries(packet.schedulers))equal(job.state,'PAUSED',`SCHEDULER_NOT_PAUSED:${name}`);equal(packet.calibrationSchedulerMatches.length,0,'CALIBRATION_SCHEDULER_PRESENT');
const config=packet.closedState.configuration,checkpoint=packet.closedState.checkpoint;equal(config.bindingReceiptId,activation.documentId,'CONFIG_BINDING_INVALID');equal(config.requiredSecretVersion,'2','CONFIG_SECRET_VERSION_INVALID');equal(config.providerRequestsAllowed,false,'PROVIDER_GATE_OPEN');equal(config.canaryRequestsAllowed,false,'CANARY_GATE_OPEN');equal(config.calibrationRequestsAllowed.effectiveValue,false,'CALIBRATION_GATE_OPEN');equal(config.enabled,false,'PIPELINE_ENABLED');equal(checkpoint.state,'blocked','CHECKPOINT_NOT_BLOCKED');equal(checkpoint.providerRequestsAllowed,false,'CHECKPOINT_PROVIDER_GATE_OPEN');equal(checkpoint.leaseToken,null,'CHECKPOINT_LEASE_PRESENT');
const previous=packet.previousActivationReceipt;equal(previous.immutable,true,'PREVIOUS_RECEIPT_NOT_IMMUTABLE');equal(previous.bindingState,'superseded','PREVIOUS_RECEIPT_NOT_SUPERSEDED');equal(previous.supersededByReceiptId,activation.documentId,'PREVIOUS_RECEIPT_SUPERSESSION_INVALID');same(packet.configurationFieldsChanged.sort(),['bindingReceiptId','requiredSecretVersion','updatedAt'],'CONFIGURATION_CHANGE_SET_INVALID');
const serialized=JSON.stringify(packet).toLowerCase();for(const marker of ['access_token','refresh_token','providerresponsebody','rawproviderresponse'])if(serialized.includes(marker))fail(`FORBIDDEN_SECRET_OR_BODY_FIELD:${marker}`);
console.log(JSON.stringify({valid:true,packetDigest:packet.packetDigest,activationReceiptId:activation.documentId,activationDigest:activation.digest,revisions:Object.fromEntries(Object.entries(packet.providerFunctions).map(([name,fn])=>[name,fn.revisionResource.split('/').pop()])),secretVersionState:packet.secretMetadata.state,schedulers:Object.fromEntries(Object.entries(packet.schedulers).map(([name,job])=>[name,job.state])),calibrationSchedulerPresent:false,closedState:{providerRequestsAllowed:config.providerRequestsAllowed,canaryRequestsAllowed:config.canaryRequestsAllowed,calibrationRequestsAllowed:config.calibrationRequestsAllowed.effectiveValue,enabled:config.enabled,checkpoint:checkpoint.state}}));
