import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {COURSE_INTAKE_COPY} from "../../../i18n/partner/courseIntake";
import type {EnterpriseAuthorityLocale} from "../../../i18n/partner/enterpriseAuthority";
import {newAuthorityCommandId,organizationAuthorityService,type CourseIntakeCandidate,type CourseIntakeProjection} from "../enterprise/organizationAuthorityService";

export default function EnterpriseCourseIntake({locale,organizationId,authorityVersion}:{locale:EnterpriseAuthorityLocale;organizationId:string;authorityVersion:number}){
 const copy=COURSE_INTAKE_COPY[locale],[state,setState]=useState<"loading"|"ready"|"error">("loading"),[data,setData]=useState<CourseIntakeProjection|null>(null),[manual,setManual]=useState(""),[plan,setPlan]=useState<number|null>(null),[selected,setSelected]=useState<CourseIntakeCandidate|null>(null),[action,setAction]=useState<"confirm_new"|"reject"|"publish"|null>(null),[notice,setNotice]=useState("");
 const commandId=useRef("");
 const load=useCallback(async()=>{setState("loading");try{setData(await organizationAuthorityService.loadCourseIntake(organizationId));setState("ready")}catch{setState("error")}},[organizationId]);
 useEffect(()=>{void load()},[load]);
 const remaining=useMemo(()=>{const q=data?.quota;return q?q.configuredBudget-q.emergencyReserve-q.reserved-q.completed-q.failed+q.released:null},[data]);
 const canMutate=data?.mutationAllowed===true;
 const run=async()=>{if(!selected||!action||!canMutate)return;const stable=commandId.current||newAuthorityCommandId();commandId.current=stable;try{if(action==="publish"){if(!selected.reviewDecisionId||!selected.reviewDecisionVersion)throw Error("DECISION_VERSION_REQUIRED");await organizationAuthorityService.publishCourseCandidate(organizationId,authorityVersion,selected.candidateId,selected.version,selected.reviewDecisionId,selected.reviewDecisionVersion,stable)}else await organizationAuthorityService.decideCourseCandidate(organizationId,authorityVersion,selected.candidateId,selected.version,action,stable);setNotice(copy.success);commandId.current="";setSelected(null);setAction(null);await load()}catch{setNotice(copy.unavailable)}};
 const choose=(candidate:CourseIntakeCandidate,next:typeof action)=>{commandId.current=newAuthorityCommandId();setSelected(candidate);setAction(next);setNotice("")};
 return <section aria-labelledby="enterprise-course-intake-title" style={card}><h3 id="enterprise-course-intake-title">{copy.title}</h3><p>{copy.intro}</p>{!canMutate&&<p role="note">{copy.notAllowed}</p>}{state==="loading"&&<p role="status" aria-live="polite">{copy.loading}</p>}{state==="error"&&<div role="alert"><p>{copy.unavailable}</p><button type="button" onClick={()=>void load()}>{copy.retry}</button></div>}{state==="ready"&&data&&<><dl><div><dt>{copy.budget}</dt><dd>{data.quota?.configuredBudget??"—"}</dd></div><div><dt>{copy.remaining}</dt><dd>{remaining??"—"}</dd></div></dl><div style={{overflowX:"auto"}}><table><thead><tr><th>{copy.country}</th><th>{copy.canonical}</th><th>{copy.active}</th><th>{copy.fresh}</th><th>{copy.missing}</th></tr></thead><tbody>{data.countries.map(item=><tr key={item.country}><td>{item.country}</td><td>{item.canonical}</td><td>{item.active}</td><td>{item.fresh}</td><td>{item.missingCoordinates}</td></tr>)}</tbody></table></div><h4>{copy.planner}</h4><label htmlFor="course-intake-manual">{copy.manual}<input id="course-intake-manual" value={manual} maxLength={120} placeholder={copy.manualHint} onChange={event=>setManual(event.target.value)}/></label><button type="button" disabled={!canMutate} onClick={async()=>{try{const coverage=data.countries.map(item=>({country:item.country,city:null,missingCoordinates:item.missingCoordinates,stale:Math.max(0,item.canonical-item.fresh),demand:0})),requests=manual.trim()?[{country:manual.trim(),city:null}]:[];setPlan((await organizationAuthorityService.previewCourseIntake(organizationId,authorityVersion,coverage,requests)).estimatedCalls)}catch{setNotice(copy.unavailable)}}}>{copy.plan}</button>{plan!==null&&<p role="status" aria-live="polite">{plan} · 0 provider calls · 0 writes</p>}<h4>{copy.queue}</h4>{data.candidates.length===0?<p>{copy.empty}</p>:<ul>{data.candidates.map(candidate=><li key={candidate.candidateId}><strong>{candidate.name}</strong> · {[candidate.city,candidate.country].filter(Boolean).join(", ")} · v{candidate.version} {candidate.status==="reviewed"&&candidate.reviewDecisionId?<button type="button" disabled={!canMutate} onClick={()=>choose(candidate,"publish")}>{copy.approve}</button>:<><button type="button" disabled={!canMutate} onClick={()=>choose(candidate,"confirm_new")}>{copy.review}</button><button type="button" disabled={!canMutate} onClick={()=>choose(candidate,"reject")}>{copy.reject}</button></>}</li>)}</ul>}</>}{selected&&action&&<div role="dialog" aria-modal="true" aria-labelledby="course-intake-confirm"><h4 id="course-intake-confirm">{copy.confirm}</h4><p>{selected.name} · v{selected.version}</p><button type="button" onClick={()=>void run()}>{copy.confirm}</button><button type="button" onClick={()=>{commandId.current="";setSelected(null);setAction(null)}}>{copy.cancel}</button></div>}{notice&&<p role={notice===copy.success?"status":"alert"} aria-live="polite">{notice}</p>}</section>
}
const card={border:"1px solid #444",borderRadius:8,padding:16,marginBottom:16,background:"#111"};
