import {useRef, useState} from 'react';
import {smallBusinessLabel, smallBusinessWeekday} from '../../i18n/smallBusinessLabels';
import type {SmallBusinessCopy} from '../../i18n/smallBusiness';
import {commandId, type PortalProjection, type SmallBusinessLocale} from './smallBusinessModel';
import type {SmallBusinessProvider} from './smallBusinessProvider';

type Props={data:PortalProjection;provider:SmallBusinessProvider;locale:SmallBusinessLocale;t:SmallBusinessCopy;onReload:()=>Promise<void>;onMessage:(value:string)=>void};

export default function SmallBusinessProfileEditor({data,provider,locale,t,onReload,onMessage}:Props){
 const business=data.business!;
 const [locations,setLocations]=useState(structuredClone(data.locations));
 const [evidence,setEvidence]=useState(structuredClone(data.evidenceReferences||[]));
 const canonicalLocationIds=useRef(new Set(data.locations.map(location=>location.locationId)));
 const [base,setBase]=useState({legalName:business.legalName,publicName:business.displayName,registrationReference:business.registrationReference,category:business.category,serviceDescription:business.serviceDescription,serviceArea:business.serviceArea,supportedLocales:business.supportedLocales.join(',')});
 const [confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),command=useRef(commandId('sb_profile'));
 const save=async()=>{if(!confirmed||busy)return;if(!navigator.onLine){setNotice(t.offline);return}setBusy(true);setNotice(t.loading);const profile={...base,supportedLocales:base.supportedLocales.split(',').map(value=>value.trim()),locations:locations.map(location=>({locationId:location.locationId,name:location.label,address:location.address,city:location.city,countryCode:location.countryCode||location.country,serviceArea:location.serviceArea,operatingHours:location.operatingHours||location.hours})),evidenceReferences:evidence};try{if(['approved','active'].includes(business.status))await provider.submitProfileCorrection({saveCommandId:command.current,submitCommandId:`${command.current}_submit`,expectedBusinessVersion:business.version,profile});else await provider.submitProfile({commandId:command.current,expectedVersion:business.version,profile});command.current=commandId('sb_profile');setConfirmed(false);setNotice(t.refresh);await onReload()}catch(error){const text=String(error),copy=text.includes('STALE')||text.includes('CONFLICT')||text.includes('VERSION')?t.conflict:t.unavailable;setNotice(copy);onMessage(copy)}finally{setBusy(false)}};
 const updateHour=(locationIndex:number,hourIndex:number,patch:Record<string,unknown>)=>setLocations(current=>current.map((location,index)=>index===locationIndex?{...location,hours:(location.operatingHours||location.hours).map((hour,i)=>i===hourIndex?{...hour,...patch}:hour),operatingHours:undefined}:location));
 return <form className="sb-card" aria-busy={busy} onSubmit={event=>{event.preventDefault();void save()}}><h2>{t.profile}</h2><p role={notice===t.unavailable||notice===t.conflict||notice===t.offline?'alert':'status'} aria-live="polite">{notice}</p>
  {Object.entries(base).map(([key,value])=><label key={key}>{key==='serviceArea'?t.serviceArea:key==='supportedLocales'?t.locales:smallBusinessLabel(locale,key)}<input required value={value} onChange={event=>setBase(current=>({...current,[key]:event.target.value}))}/></label>)}
  <h3>{t.locations}</h3>{locations.map((location,locationIndex)=><fieldset key={location.locationId}><legend>{t.locations} {locationIndex+1}</legend>
   {(['locationId','label','address','city','countryCode','serviceArea'] as const).map(key=><label key={key}>{key==='serviceArea'?t.serviceArea:smallBusinessLabel(locale,key==='label'?'locationName':key)}<input required readOnly={key==='locationId'&&canonicalLocationIds.current.has(location.locationId)} aria-readonly={key==='locationId'&&canonicalLocationIds.current.has(location.locationId)} value={String(location[key]||'')} onChange={event=>setLocations(current=>current.map((item,index)=>index===locationIndex?{...item,[key]:event.target.value}:item))}/></label>)}
   <h4>{smallBusinessLabel(locale,'operatingHours')}</h4>{(location.operatingHours||location.hours).map((hour,hourIndex)=><div key={`${hour.day}-${hourIndex}`}><label>{smallBusinessWeekday(locale,hour.day)}<input aria-label={smallBusinessLabel(locale,'day')} type="number" min="0" max="6" value={hour.day} onChange={event=>updateHour(locationIndex,hourIndex,{day:Number(event.target.value)})}/></label><label>{smallBusinessLabel(locale,'opens')}<input type="time" disabled={hour.closed} value={hour.opens||''} onChange={event=>updateHour(locationIndex,hourIndex,{opens:event.target.value})}/></label><label>{smallBusinessLabel(locale,'closes')}<input type="time" disabled={hour.closed} value={hour.closes||''} onChange={event=>updateHour(locationIndex,hourIndex,{closes:event.target.value})}/></label><label><input type="checkbox" checked={hour.closed} onChange={event=>updateHour(locationIndex,hourIndex,{closed:event.target.checked})}/>{smallBusinessLabel(locale,'isClosed')}</label></div>)}
   <button type="button" disabled={locations.length<=1} onClick={()=>setLocations(current=>current.filter((_,index)=>index!==locationIndex))}>{t.withdraw}</button></fieldset>)}
  <button type="button" disabled={busy||locations.length>=50} onClick={()=>setLocations(current=>[...current,{locationId:`new_${current.length+1}`,label:'',address:'',city:'',countryCode:'',country:'',serviceArea:'',hours:Array.from({length:7},(_,day)=>({day,opens:'09:00',closes:'17:00',closed:false}))}])}>{t.prepareDraft} · {t.locations}</button>
  <h3>{t.evidence}</h3>{evidence.map((item,evidenceIndex)=><fieldset key={item.evidenceId}>{(['evidenceId','kind','objectReference','contentDigest'] as const).map(key=><label key={key}>{smallBusinessLabel(locale,key==='kind'?'evidenceKind':key)}<input required value={item[key]} onChange={event=>setEvidence(current=>current.map((value,index)=>index===evidenceIndex?{...value,[key]:event.target.value}:value))}/></label>)}<button type="button" onClick={()=>setEvidence(current=>current.filter((_,index)=>index!==evidenceIndex))}>{t.withdraw}</button></fieldset>)}
  <button type="button" disabled={busy||evidence.length>=30} onClick={()=>setEvidence(current=>[...current,{evidenceId:`evidence_${crypto.randomUUID()}`,kind:'',objectReference:'evidence/',contentDigest:''}])}>{t.prepareDraft} · {t.evidence}</button><label className="sb-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={event=>setConfirmed(event.target.checked)}/>{t.confirm}</label><button disabled={busy||!confirmed}>{busy?t.loading:t.submit}</button>
 </form>
}
