import {useRef,useState,type MutableRefObject} from 'react';
import type {SmallBusinessCopy} from '../../i18n/smallBusiness';
import {smallBusinessLabel} from '../../i18n/smallBusinessLabels';
import {commandId,type PortalProjection,type SmallBusinessLocale} from './smallBusinessModel';
import type {SmallBusinessProvider} from './smallBusinessProvider';
import SmallBusinessProfileEditor from './SmallBusinessProfileEditor';
const digest=/^[a-f0-9]{64}$/;
export default function SmallBusinessPortalForms({data,provider,locale,t,onReload,onMessage}:{data:PortalProjection;provider:SmallBusinessProvider;locale:SmallBusinessLocale;t:SmallBusinessCopy;onReload:()=>Promise<void>;onMessage:(x:string)=>void}){
 const business=data.business!,location=data.locations[0],[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(''),promotionCommand=useRef(commandId('sb_promotion')),[promotion,setPromotion]=useState({promotionId:'',audience:'',jurisdiction:location?.country||'',effectiveAt:'',expiresAt:'',contentDigest:'',frequencyLimit:'1',contentReference:''});
 const execute=async(task:()=>Promise<void>,next:MutableRefObject<string>)=>{if(!navigator.onLine){onMessage('OFFLINE_NO_COMMAND');return}setBusy(true);try{await task();next.current=commandId('sb_retry');setConfirm('');await onReload()}catch(error){onMessage(String(error))}finally{setBusy(false)}};
 return <div className="sb-forms"><SmallBusinessProfileEditor data={data} provider={provider} locale={locale} t={t} onReload={onReload} onMessage={onMessage}/>
  <form className="sb-card" onSubmit={event=>{event.preventDefault();if(!location)return;void execute(()=>provider.preparePromotion({commandId:promotionCommand.current,expectedVersion:0,promotion:{promotionId:promotion.promotionId,businessId:business.businessId,locationIds:[location.locationId],audience:promotion.audience,locales:[locale],jurisdictions:[promotion.jurisdiction],effectiveAt:new Date(promotion.effectiveAt).toISOString(),expiresAt:new Date(promotion.expiresAt).toISOString(),contentDigest:promotion.contentDigest,frequencyLimit:Number(promotion.frequencyLimit),sponsoredDisclosure:true,contentReference:promotion.contentReference}}),promotionCommand)}}><h2>{t.promotionDraft}</h2><p>{t.promotionBoundary}</p>{Object.entries(promotion).map(([key,value])=><label key={key}>{({jurisdiction:t.jurisdiction,effectiveAt:t.effective,expiresAt:t.expires,contentDigest:t.digest} as Record<string,string>)[key]||smallBusinessLabel(locale,key)}<input required type={key.endsWith('At')?'datetime-local':key==='frequencyLimit'?'number':'text'} min={key==='frequencyLimit'?1:undefined} max={key==='frequencyLimit'?20:undefined} value={value} onChange={event=>setPromotion(current=>({...current,[key]:event.target.value}))}/></label>)}<label className="sb-confirm"><input type="checkbox" checked={confirm==='promotion'} onChange={event=>setConfirm(event.target.checked?'promotion':'')}/>{t.confirm}</label><button disabled={busy||confirm!=='promotion'||!location||!digest.test(promotion.contentDigest)}>{t.prepareDraft}</button></form>
 </div>
}
