import{useCallback,useEffect,useRef,useState}from'react';
import{useLocale}from'../../i18n/hooks';
import{commandId,type PlanProjection,type SmallBusinessLocale}from'./smallBusinessModel';
import type{SmallBusinessProvider}from'./smallBusinessProvider';
const COPY:Record<SmallBusinessLocale,Record<string,string>>={
 en:{title:'Subscription',trial_active:'90-day trial active',checkout_pending:'Checkout pending',paid:'Paid',payment_failed:'Payment failed',cancelled:'Cancelled',provider_unavailable:'Payment provider unavailable',action:'Set up monthly billing',retry:'Retry checkout',boundary:'The server selects the approved monthly plan and price. Billing starts after the trial. Tax invoice authority is not yet enabled.',opening:'Opening secure checkout…',unavailable:'Subscription status is temporarily unavailable.'},
 th:{title:'การสมัครสมาชิก',trial_active:'กำลังทดลองใช้ 90 วัน',checkout_pending:'รอชำระเงิน',paid:'ชำระเงินแล้ว',payment_failed:'ชำระเงินไม่สำเร็จ',cancelled:'ยกเลิกแล้ว',provider_unavailable:'ผู้ให้บริการชำระเงินยังไม่พร้อม',action:'ตั้งค่าการเรียกเก็บรายเดือน',retry:'ลองชำระเงินอีกครั้ง',boundary:'เซิร์ฟเวอร์เป็นผู้เลือกแผนและราคาที่อนุมัติ เริ่มเรียกเก็บหลังช่วงทดลองใช้ ยังไม่เปิดสิทธิ์ออกใบกำกับภาษี',opening:'กำลังเปิดหน้าชำระเงินที่ปลอดภัย…',unavailable:'ไม่สามารถดูสถานะการสมัครสมาชิกได้ชั่วคราว'},
 ko:{title:'구독',trial_active:'90일 체험 사용 중',checkout_pending:'결제 대기 중',paid:'결제 완료',payment_failed:'결제 실패',cancelled:'취소됨',provider_unavailable:'결제 제공자를 사용할 수 없음',action:'월간 결제 설정',retry:'결제 다시 시도',boundary:'서버가 승인된 월간 요금제와 가격을 선택합니다. 체험 종료 후 청구되며 세금계산서 권한은 아직 없습니다.',opening:'보안 결제를 여는 중…',unavailable:'구독 상태를 일시적으로 확인할 수 없습니다.'},
 ja:{title:'サブスクリプション',trial_active:'90日間トライアル中',checkout_pending:'決済待ち',paid:'支払い済み',payment_failed:'支払い失敗',cancelled:'キャンセル済み',provider_unavailable:'決済プロバイダーを利用できません',action:'月額請求を設定',retry:'決済を再試行',boundary:'承認済み月額プランと価格はサーバーが選択します。請求はトライアル後に開始し、税務請求書の権限はまだありません。',opening:'安全な決済を開いています…',unavailable:'サブスクリプション状態を一時的に取得できません。'},
 zh:{title:'订阅',trial_active:'90 天试用中',checkout_pending:'等待付款',paid:'已付款',payment_failed:'付款失败',cancelled:'已取消',provider_unavailable:'付款服务商不可用',action:'设置按月计费',retry:'重试付款',boundary:'服务器选择获批的月度套餐和价格。试用期结束后开始计费，目前尚无税务发票权限。',opening:'正在打开安全结账…',unavailable:'暂时无法获取订阅状态。'},
 es:{title:'Suscripción',trial_active:'Prueba de 90 días activa',checkout_pending:'Pago pendiente',paid:'Pagado',payment_failed:'Pago fallido',cancelled:'Cancelado',provider_unavailable:'Proveedor de pagos no disponible',action:'Configurar pago mensual',retry:'Reintentar pago',boundary:'El servidor selecciona el plan mensual y el precio aprobados. La facturación comienza tras la prueba. La factura fiscal aún no está autorizada.',opening:'Abriendo pago seguro…',unavailable:'El estado de la suscripción no está disponible temporalmente.'},
 fr:{title:'Abonnement',trial_active:'Essai de 90 jours actif',checkout_pending:'Paiement en attente',paid:'Payé',payment_failed:'Échec du paiement',cancelled:'Annulé',provider_unavailable:'Prestataire de paiement indisponible',action:'Configurer la facturation mensuelle',retry:'Réessayer le paiement',boundary:'Le serveur choisit le forfait mensuel et le prix approuvés. La facturation commence après l’essai. La facture fiscale n’est pas encore autorisée.',opening:'Ouverture du paiement sécurisé…',unavailable:'Le statut de l’abonnement est temporairement indisponible.'},
 de:{title:'Abonnement',trial_active:'90-Tage-Testphase aktiv',checkout_pending:'Zahlung ausstehend',paid:'Bezahlt',payment_failed:'Zahlung fehlgeschlagen',cancelled:'Gekündigt',provider_unavailable:'Zahlungsanbieter nicht verfügbar',action:'Monatliche Abrechnung einrichten',retry:'Zahlung erneut versuchen',boundary:'Der Server wählt den genehmigten Monatsplan und Preis. Die Abrechnung beginnt nach der Testphase. Eine Steuerrechnung ist noch nicht autorisiert.',opening:'Sichere Kasse wird geöffnet…',unavailable:'Der Abonnementstatus ist vorübergehend nicht verfügbar.'}
};
export default function SmallBusinessSubscription({plans,provider,onMessage}:{plans:PlanProjection[];provider:SmallBusinessProvider;onMessage:(message:string)=>void}){const locale=useLocale(),copy=COPY[locale],planAvailable=plans.some(p=>p.status==='available'),[state,setState]=useState<any>(null),[busy,setBusy]=useState(false),intent=useRef(`intent_${crypto.randomUUID()}`),command=useRef(commandId('sb_checkout'));const load=useCallback(async()=>{try{setState(await provider.subscriptionState())}catch{setState({status:'provider_unavailable'})}},[provider]);useEffect(()=>{void load()},[load]);const checkout=async()=>{if(!planAvailable||!navigator.onLine)return;setBusy(true);onMessage(copy.opening);try{await provider.createSubscriptionIntent({commandId:commandId('sb_intent'),intentId:intent.current});const session=await provider.createSubscriptionCheckout({commandId:command.current,intentId:intent.current});if(!/^https:\/\//.test(session.checkoutUrl))throw Error('INVALID_CHECKOUT_URL');window.location.assign(session.checkoutUrl)}catch{setState({status:'provider_unavailable'});onMessage(copy.unavailable)}finally{setBusy(false)}};const status=String(state?.status||'provider_unavailable'),canCheckout=planAvailable&&['trial_active','checkout_pending','payment_failed','provider_unavailable'].includes(status);return <section className="sb-card" aria-labelledby="small-business-subscription"><h2 id="small-business-subscription">{copy.title}</h2><p>{copy.boundary}</p><p role="status" data-subscription-state={status}><strong>{copy[status]||copy.unavailable}</strong></p>{state?.trial?.endsAt&&<p><time dateTime={state.trial.endsAt}>{new Intl.DateTimeFormat(locale,{dateStyle:'long'}).format(new Date(state.trial.endsAt))}</time></p>}{canCheckout&&<button disabled={busy||!navigator.onLine} onClick={()=>void checkout()}>{status==='payment_failed'?copy.retry:copy.action}</button>}</section>}
