const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key));
const id=/^[A-Za-z0-9_-]{8,200}$/,sha=/^[a-f0-9]{64}$/,statuses=new Set(['course_reviewing','course_confirmed','alternative_proposed','cancellation_requested','cancellation_accepted','cancellation_declined','cancelled','expired','ambiguous_locked']);
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value)}return value};
export function parseEnterpriseBookingCoordinationProjection(raw,now=Date.now()){
 const keys=['schema','projectionVersion','membershipId','role','organizationId','propertyIds','courseIds','delegatedCourseIds','sourceVersion','generatedAt','expiresAt','freshness','permissions','bookings','boundary'];
 if(!exact(raw,keys)||raw.schema!=='golfriend.enterprise-booking-coordination-portal.v2'||raw.projectionVersion!==raw.schema||!id.test(raw.membershipId)||!id.test(raw.organizationId)||!sha.test(raw.sourceVersion)||raw.freshness!=='fresh'||Date.parse(raw.generatedAt)>now+30000||Date.parse(raw.expiresAt)<=now||!Array.isArray(raw.propertyIds)||!Array.isArray(raw.courseIds)||!Array.isArray(raw.delegatedCourseIds)||!Array.isArray(raw.bookings)||!exact(raw.permissions,['confirm','alternative','respondCancellation','readOnly']))throw Error('COORDINATION_PROJECTION_INVALID');
 const scope=new Set(raw.courseIds),properties=new Set(raw.propertyIds),bookings=raw.bookings.map(item=>{
  if(!exact(item,['bookingId','correlationId','courseId','propertyId','version','status','golferRef','authorizedCourseRecipientRef','request','alternative','history','receipts','operation','sourceVersions'])||!id.test(item.bookingId)||!id.test(item.correlationId)||!scope.has(item.courseId)||!properties.has(item.propertyId)||!Number.isSafeInteger(item.version)||item.version<1||!statuses.has(item.status)||!id.test(item.golferRef)||!/^ecr_[a-f0-9]{40}$/.test(item.authorizedCourseRecipientRef)||!exact(item.request,['date','timeWindow','partySize','preferences'])||!exact(item.request.timeWindow,['start','end','timeZone'])||!exact(item.request.preferences,['locale','allowedChannels','shareContact'])||!Number.isSafeInteger(item.request.partySize)||item.request.partySize<1||item.request.partySize>8||!Array.isArray(item.history)||!Array.isArray(item.receipts)||!exact(item.sourceVersions,['booking','course','golfer']))throw Error('COORDINATION_PROJECTION_INVALID');
  for(const event of item.history)if(!exact(event,['eventId','status','version','at'])||!id.test(event.eventId)||!statuses.has(event.status)||!Number.isSafeInteger(event.version)||!Number.isFinite(Date.parse(event.at)))throw Error('COORDINATION_PROJECTION_INVALID');
  if(item.operation&&(!exact(item.operation,['action','state','operationId'])||item.operation.state!=='ambiguous_locked'||!id.test(item.operation.operationId)))throw Error('COORDINATION_PROJECTION_INVALID');
  return item;
 });
 return freeze({...raw,bookings});
}
