import {useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent} from 'react';
import {getFunctions, httpsCallable} from 'firebase/functions';
import {useT} from '../../i18n/hooks.ts';
import {PLAY_BOOKING_DESK, type PlayBookingDeskKey} from '../../i18n/partner/playBookingDesk.ts';
import {parseEnterpriseBookingActionPreview,parseEnterpriseBookingActionResult,parseEnterpriseBookingCoordinationProjection,parseEnterpriseBookingTokenRecovery} from './enterpriseBookingCoordinationProjection.mjs';
import {approvePlayBookingMessageDraft, createPlayBookingMessageDraft, playBookingMessageApprovalDigest, type PlayBookingMessageDraft, type PlayBookingMessageDraftType} from './playBookingMessageDraft.mjs';
import './PlayBookingDesk.css';
import './EnterpriseBookingCoordinationDesk.css';

type Raw = Record<string, any>;
type BookingLocale = 'en'|'th'|'ko'|'ja'|'zh'|'es'|'fr'|'de';
type Action = 'confirm'|'alternative'|'accept_cancellation'|'decline_cancellation';
type Pending = {booking: Raw; action: Action; commandId: string; recoveryCommandId: string; expiresAt: number; operationId?: string; operationDigest?: string};
const call = async (name: string, data: Raw = {}) => (await httpsCallable(getFunctions(), name)(data)).data as Raw;
const service = {load: () => call('getEnterpriseBookingCoordinationPortalV2'), preview: (value: Raw) => call('previewEnterpriseBookingActionV2', value), manage: (value: Raw) => call('manageEnterpriseBookingActionV2', value), recover: (value: Raw) => call('recoverPlayBookingConfirmationV2', value)};
const locales: readonly BookingLocale[] = ['en','th','ko','ja','zh','es','fr','de'];
const locale = (): BookingLocale => {const value = localStorage.getItem('golfriend.locale') as BookingLocale|null; return value && locales.includes(value) ? value : 'en';};
const uuid = () => crypto.randomUUID().replaceAll('-', '_');
const statusKey: Record<string, PlayBookingDeskKey> = {course_reviewing:'statusUnderReview',course_confirmed:'statusConfirmed',alternative_proposed:'statusAlternative',cancellation_requested:'statusCancellationRequested',cancellation_accepted:'statusCancellationAccepted',cancellation_declined:'statusCancellationDeclined',cancelled:'statusCancelled',expired:'statusExpired',ambiguous_locked:'operationAmbiguous'};
const actionKey: Record<Action, PlayBookingDeskKey> = {confirm:'confirm',alternative:'proposeAlternative',accept_cancellation:'statusCancellationAccepted',decline_cancellation:'statusCancellationDeclined'};
const draftKey: Record<PlayBookingMessageDraftType, PlayBookingDeskKey> = {request_received:'draftRequestReceived',information_needed:'draftInformationNeeded',alternative_proposed:'draftAlternativeProposed',confirmed:'draftConfirmed',declined:'draftDeclined',cancellation_received:'draftCancellationReceived',cancellation_accepted:'draftCancellationAccepted',cancellation_declined:'draftCancellationDeclined',manual_support_required:'draftManualSupportRequired'};
const storageKey = (membership: string, booking: string, action: string) => `golfriend.booking.v2.${membership}.${booking}.${action}`;
function restore(key: string): Pending|null {try {const value = JSON.parse(localStorage.getItem(key) || 'null'); if (!value?.booking || !value.commandId || !value.recoveryCommandId || !Number.isSafeInteger(value.expiresAt) || value.expiresAt <= Date.now()) {localStorage.removeItem(key); return null;} return value;} catch {localStorage.removeItem(key); return null;}}
function purgeForeignScopes(membershipId: string) {const prefix = 'golfriend.booking.v2.', keep = `${prefix}${membershipId}.`; for (let index = localStorage.length - 1; index >= 0; index -= 1) {const key = localStorage.key(index); if (key?.startsWith(prefix) && !key.startsWith(keep)) localStorage.removeItem(key);}}

export default function EnterpriseBookingCoordinationDesk() {
  const t = useT(PLAY_BOOKING_DESK) as (key: PlayBookingDeskKey) => string;
  const [projection, setProjection] = useState<Raw|null>(null), [selectedId, setSelectedId] = useState(''), [pending, setPending] = useState<Pending|null>(null), [ack, setAck] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const [slot, setSlot] = useState({slotId:'',date:'',time:'',timeZone:'',slotVersion:'1'}), [draftType, setDraftType] = useState<PlayBookingMessageDraftType>('request_received'), [draftText, setDraftText] = useState(''), [draft, setDraft] = useState<PlayBookingMessageDraft|null>(null);
  const dialog = useRef<HTMLElement|null>(null), returnFocus = useRef<HTMLElement|null>(null);
  const load = useCallback(async () => {setBusy(true); try {const value = parseEnterpriseBookingCoordinationProjection(await service.load()); purgeForeignScopes(value.membershipId); setProjection(value); setSelectedId(id => value.bookings.some((booking: Raw) => booking.bookingId === id) ? id : value.bookings[0]?.bookingId || ''); setNotice('');} catch {setProjection(null); setNotice(t('loadError'));} finally {setBusy(false);}}, [t]);
  useEffect(() => {void load();}, [load]);
  useEffect(() => {pending && dialog.current?.querySelector<HTMLElement>('input,button')?.focus();}, [pending]);
  const selected = projection?.bookings.find((booking: Raw) => booking.bookingId === selectedId) || null, queue = useMemo(() => projection?.bookings || [], [projection]);
  const available = (action: Action) => Boolean(projection && Date.parse(projection.expiresAt) > Date.now() && selected && !selected.operation && (((action === 'confirm' || action === 'alternative') && selected.status === 'course_reviewing') || ((action === 'accept_cancellation' || action === 'decline_cancellation') && selected.status === 'cancellation_requested')) && (action === 'confirm' ? projection.permissions.confirm : action === 'alternative' ? projection.permissions.alternative : projection.permissions.respondCancellation));
  const begin = (action: Action, target: HTMLElement) => {if (!projection || !selected || !available(action)) return; const key = storageKey(projection.membershipId, selected.bookingId, action), saved = restore(key), value = saved?.booking.version === selected.version ? saved : {booking:{bookingId:selected.bookingId,version:selected.version},action,commandId:uuid(),recoveryCommandId:uuid(),expiresAt:Date.now()+86400000}; localStorage.setItem(key, JSON.stringify(value)); returnFocus.current = target; setPending(value); setAck(false); setNotice('');};
  const close = () => {setPending(null); setAck(false); setTimeout(() => returnFocus.current?.focus(), 0);};
  const operation = () => ({schema:'golfriend.enterprise-booking-operation.v2',bookingId:selected!.bookingId,commandId:pending!.commandId,expectedVersion:selected!.version,action:pending!.action,alternativeSlot:pending!.action === 'alternative' ? {slotId:slot.slotId.trim(),date:slot.date,time:slot.time,timeZone:slot.timeZone.trim(),slotVersion:Number(slot.slotVersion)} : null});
  const execute = async () => {
    if (!projection || !pending || !selected || !ack || busy) return;
    setBusy(true); const key = storageKey(projection.membershipId, selected.bookingId, pending.action);
    try {let confirmationToken = '';
      if (pending.operationId && pending.operationDigest) {const recovered = parseEnterpriseBookingTokenRecovery(await service.recover({bookingId:selected.bookingId,operationId:pending.operationId,recoveryCommandId:pending.recoveryCommandId,expectedOperationDigest:pending.operationDigest}),{bookingId:selected.bookingId,operationId:pending.operationId,operationDigest:pending.operationDigest}); confirmationToken = recovered.confirmationToken;}
      else {const preview = parseEnterpriseBookingActionPreview(await service.preview(operation()),{bookingId:selected.bookingId,action:pending.action,version:selected.version}); pending.operationId = preview.operationId; pending.operationDigest = preview.operationDigest; localStorage.setItem(key, JSON.stringify(pending)); confirmationToken = preview.confirmationToken;}
      const result = parseEnterpriseBookingActionResult(await service.manage({...operation(), confirmationToken}),{bookingId:selected.bookingId,action:pending.action,version:selected.version}); localStorage.removeItem(key); setNotice(`${t('actionSucceeded')} · ${result.receiptId}`); close(); await load();
    } catch {setNotice(t(pending.operationId ? 'operationAmbiguous' : 'operationError'));} finally {setBusy(false);}
  };
  const makeDraft = () => {if (!selected || !draftText.trim()) return; try {const value = createPlayBookingMessageDraft({type:draftType,bookingId:selected.bookingId,recipientRef:selected.authorizedCourseRecipientRef,locale:locale(),revision:selected.version,status:selected.status === 'alternative_proposed' ? 'changed' : selected.status === 'course_confirmed' ? 'confirmed' : selected.status === 'cancelled' ? 'cancelled' : 'pending',slot:{slotId:selected.alternative?.slotId || selected.bookingId,courseRef:selected.courseId,date:selected.alternative?.date || selected.request.date,time:selected.alternative?.time || selected.request.timeWindow.start,timeZone:selected.alternative?.timeZone || selected.request.timeWindow.timeZone},message:draftText.trim()}); setDraft(value); setNotice(t('messageDraftOnly'));} catch {setDraft(null); setNotice(t('operationError'));}};
  const dialogKey = (event: KeyboardEvent<HTMLElement>) => {if (event.key === 'Escape' && !busy) {event.preventDefault(); close(); return;} if (event.key !== 'Tab') return; const controls = [...(dialog.current?.querySelectorAll<HTMLElement>('input:not(:disabled),button:not(:disabled)') || [])]; if (!controls.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) {event.preventDefault(); last.focus();} else if (!event.shiftKey && document.activeElement === last) {event.preventDefault(); first.focus();}};
  if (!projection) return <section className="booking-desk-state"><p role="alert">{notice || t('loading')}</p><button disabled={busy} onClick={() => void load()}>{t('retry')}</button></section>;
  return <section className="booking-desk" aria-labelledby="coordination-title"><header className="booking-desk__header"><div><span>{t('sectionLabel')}</span><h2 id="coordination-title">{t('title')}</h2><p>{t('providerBoundary')} {t('privacyBoundary')}</p></div><button disabled={busy || Boolean(pending)} onClick={() => void load()}>{t('reload')}</button></header><p role="status" aria-live="polite">{notice}</p><dl className="booking-desk__scope"><div><dt>{t('projectionVersionLabel')}</dt><dd>{projection.projectionVersion}</dd></div><div><dt>{t('projectionExpiresAtLabel')}</dt><dd>{projection.expiresAt}</dd></div></dl><div className="booking-desk__layout"><nav className="booking-desk__queue" aria-label={t('queueTitle')}><h3>{t('queueTitle')}</h3><ul>{queue.map((booking: Raw) => <li key={booking.bookingId}><button disabled={Boolean(pending)} aria-current={selectedId === booking.bookingId ? 'true' : undefined} onClick={() => setSelectedId(booking.bookingId)}><strong>{booking.golferRef}</strong><span>{booking.request.date} {booking.request.timeWindow.start}–{booking.request.timeWindow.end}</span><i data-status={booking.status}>{t(statusKey[booking.status])}</i></button></li>)}</ul></nav>{selected && <article className="booking-desk__detail" aria-live="polite"><h3>{selected.golferRef}</h3><i data-status={selected.status}>{t(statusKey[selected.status])}</i><dl><div><dt>{t('courseLabel')}</dt><dd>{selected.courseId}</dd></div><div><dt>{t('dateLabel')}</dt><dd>{selected.request.date}</dd></div><div><dt>{t('timeLabel')}</dt><dd>{selected.request.timeWindow.start}–{selected.request.timeWindow.end} {selected.request.timeWindow.timeZone}</dd></div><div><dt>{t('memberLabel')}</dt><dd>{selected.request.partySize}</dd></div><div><dt>{t('versionLabel')}</dt><dd>{selected.version}</dd></div></dl>{selected.alternative && <section aria-label={t('alternativeTitle')}><h4>{t('alternativeTitle')}</h4><dl><div><dt>{t('alternativeSlotLabel')}</dt><dd>{selected.alternative.slotId}</dd></div><div><dt>{t('dateLabel')}</dt><dd>{selected.alternative.date}</dd></div><div><dt>{t('timeLabel')}</dt><dd>{selected.alternative.time} {selected.alternative.timeZone}</dd></div><div><dt>{t('versionLabel')}</dt><dd>{selected.alternative.slotVersion}</dd></div></dl></section>}<section><h4>{t('receiptsTitle')}</h4>{selected.history.map((history: Raw) => <p key={history.eventId}>{t(statusKey[history.status])} · v{history.version} · {history.at}</p>)}{selected.receipts.map((receipt: string) => <code key={receipt}>{receipt}</code>)}</section><div className="booking-desk__actions">{(['confirm','alternative','accept_cancellation','decline_cancellation'] as Action[]).filter(available).map(action => <button key={action} disabled={busy || Boolean(pending)} onClick={event => begin(action, event.currentTarget)}>{t(actionKey[action])}</button>)}</div>
  {pending && <section ref={dialog} role="dialog" aria-modal="true" aria-labelledby="coordination-review" className="booking-desk__confirmation" onKeyDown={dialogKey}><h4 id="coordination-review">{t('previewConfirmationTitle')}</h4><p>{t('previewConfirmationBody')}</p><p>{selected.bookingId} · v{selected.version} · {t(actionKey[pending.action])}</p>{pending.action === 'alternative' && <><label>{t('alternativeSlotLabel')}<input value={slot.slotId} onChange={event => setSlot({...slot,slotId:event.target.value})}/></label><label>{t('dateLabel')}<input type="date" value={slot.date} onChange={event => setSlot({...slot,date:event.target.value})}/></label><label>{t('timeLabel')}<input type="time" value={slot.time} onChange={event => setSlot({...slot,time:event.target.value})}/></label><label>{t('courseLabel')}<input value={slot.timeZone} onChange={event => setSlot({...slot,timeZone:event.target.value})}/></label><label>{t('versionLabel')}<input inputMode="numeric" value={slot.slotVersion} onChange={event => setSlot({...slot,slotVersion:event.target.value})}/></label></>}<label className="booking-desk__ack"><input type="checkbox" checked={ack} onChange={event => setAck(event.target.checked)}/>{t('authorizedAcknowledgement')}</label><button disabled={!ack || busy} onClick={() => void execute()}>{t('submit')}</button><button aria-label={t('dialogCloseLabel')} disabled={busy} onClick={close}>{t('close')}</button></section>}
  <section aria-hidden={pending ? 'true' : undefined}><h4>{t('messageTitle')}</h4><select disabled={Boolean(pending)} value={draftType} onChange={event => setDraftType(event.target.value as PlayBookingMessageDraftType)}>{(Object.keys(draftKey) as PlayBookingMessageDraftType[]).map(type => <option key={type} value={type}>{t(draftKey[type])}</option>)}</select><label>{t('messageLabel')}<textarea disabled={Boolean(pending)} value={draftText} onChange={event => {setDraftText(event.target.value); setDraft(null);}}/></label><button disabled={Boolean(pending)} onClick={makeDraft}>{t('previewConfirmationTitle')}</button>{draft && <><p>{t(draftKey[draft.type])} · {t('messageDraftOnly')}</p><button disabled={Boolean(pending)} onClick={() => {setDraft(approvePlayBookingMessageDraft(draft, playBookingMessageApprovalDigest(draft))); setNotice(t('messageAwaitingTransmitter'));}}>{t('authorizedAcknowledgement')}</button></>}</section></article>}</div></section>;
}
