import {LOCALE_CODES} from '../../i18n/locales.ts';
const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key));
const id=/^[A-Za-z0-9_-]{8,200}$/,sha=/^[a-f0-9]{64}$/,statuses=new Set(['course_reviewing','course_confirmed','alternative_proposed','cancellation_requested','cancellation_accepted','cancellation_declined','cancelled','expired','ambiguous_locked']);
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value)}return value};
const actions=new Set(['confirm','alternative','accept_cancellation','decline_cancellation']);
const resultingStatus={confirm:'course_confirmed',alternative:'alternative_proposed',accept_cancellation:'cancellation_accepted',decline_cancellation:'cancellation_declined'};
const roles=new Set(['organization_owner','organization_admin','course_manager','booking_staff','analyst_viewer']),locales=new Set(LOCALE_CODES),channels=new Set(['course_phone','course_email','provider_redirect']);
const date=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const[y,m,d]=value.split('-').map(Number),parsed=new Date(Date.UTC(y,m-1,d));return parsed.getUTCFullYear()===y&&parsed.getUTCMonth()===m-1&&parsed.getUTCDate()===d};
const time=value=>/^([01]\d|2[0-3]):[0-5]\d$/.test(value),zone=value=>/^([A-Za-z_]+\/[A-Za-z_+-]+|UTC)$/.test(value),uniqueIds=value=>Array.isArray(value)&&new Set(value).size===value.length&&value.every(item=>id.test(item));
export function parseEnterpriseBookingCoordinationProjection(raw,now=Date.now()){
 const keys=['schema','projectionVersion','membershipId','role','organizationId','propertyIds','courseIds','delegatedCourseIds','sourceVersion','generatedAt','expiresAt','freshness','permissions','bookings','boundary'];
 const generated=Date.parse(raw.generatedAt),expires=Date.parse(raw.expiresAt);
 if(!exact(raw,keys)||raw.schema!=='golfriend.enterprise-booking-coordination-portal.v2'||raw.projectionVersion!==raw.schema||!id.test(raw.membershipId)||!roles.has(raw.role)||!id.test(raw.organizationId)||!sha.test(raw.sourceVersion)||raw.freshness!=='fresh'||!Number.isFinite(generated)||!Number.isFinite(expires)||generated>now+30000||expires<=now||expires<=generated||!uniqueIds(raw.propertyIds)||!uniqueIds(raw.courseIds)||!uniqueIds(raw.delegatedCourseIds)||raw.delegatedCourseIds.some(item=>!raw.courseIds.includes(item))||!Array.isArray(raw.bookings)||!exact(raw.permissions,['confirm','alternative','respondCancellation','readOnly'])||Object.values(raw.permissions).some(value=>typeof value!=='boolean')||raw.boundary!=='COURSE_SCOPED_COORDINATION_NO_CONTACT_PROVIDER_OR_FINANCIAL_AUTHORITY')throw Error('COORDINATION_PROJECTION_INVALID');
 const canMutate=raw.role!=='analyst_viewer';if(raw.permissions.confirm!==canMutate||raw.permissions.alternative!==canMutate||raw.permissions.respondCancellation!==canMutate||raw.permissions.readOnly!==!canMutate)throw Error('COORDINATION_PROJECTION_INVALID');
 const scope=new Set(raw.courseIds),properties=new Set(raw.propertyIds),bookings=raw.bookings.map(item=>{
  if(!exact(item,['bookingId','correlationId','courseId','propertyId','version','status','golferRef','authorizedCourseRecipientRef','request','alternative','history','receipts','operation','sourceVersions'])||!id.test(item.bookingId)||!id.test(item.correlationId)||!scope.has(item.courseId)||!properties.has(item.propertyId)||!Number.isSafeInteger(item.version)||item.version<1||!statuses.has(item.status)||!id.test(item.golferRef)||!/^ecr_[a-f0-9]{40}$/.test(item.authorizedCourseRecipientRef)||!exact(item.request,['date','timeWindow','partySize','preferences'])||!exact(item.request.timeWindow,['start','end','timeZone'])||!exact(item.request.preferences,['locale','allowedChannels','shareContact'])||!date(item.request.date)||!time(item.request.timeWindow.start)||!time(item.request.timeWindow.end)||item.request.timeWindow.start>=item.request.timeWindow.end||!zone(item.request.timeWindow.timeZone)||!locales.has(item.request.preferences.locale)||!Array.isArray(item.request.preferences.allowedChannels)||new Set(item.request.preferences.allowedChannels).size!==item.request.preferences.allowedChannels.length||item.request.preferences.allowedChannels.some(channel=>!channels.has(channel))||typeof item.request.preferences.shareContact!=='boolean'||!Number.isSafeInteger(item.request.partySize)||item.request.partySize<1||item.request.partySize>8||!Array.isArray(item.history)||!Array.isArray(item.receipts)||item.receipts.some(receipt=>!id.test(receipt))||!exact(item.sourceVersions,['booking','course','golfer'])||Object.values(item.sourceVersions).some(version=>!Number.isSafeInteger(version)||version<1))throw Error('COORDINATION_PROJECTION_INVALID');
  if(item.alternative!==null&&(!exact(item.alternative,['slotId','date','time','timeZone','slotVersion'])||!id.test(item.alternative.slotId)||!date(item.alternative.date)||!time(item.alternative.time)||!zone(item.alternative.timeZone)||!Number.isSafeInteger(item.alternative.slotVersion)||item.alternative.slotVersion<1))throw Error('COORDINATION_PROJECTION_INVALID');
  for(const event of item.history)if(!exact(event,['eventId','status','version','at'])||!id.test(event.eventId)||!statuses.has(event.status)||!Number.isSafeInteger(event.version)||!Number.isFinite(Date.parse(event.at)))throw Error('COORDINATION_PROJECTION_INVALID');
  if(item.operation&&(!exact(item.operation,['action','state','operationId'])||item.operation.state!=='ambiguous_locked'||!id.test(item.operation.operationId)))throw Error('COORDINATION_PROJECTION_INVALID');
  return item;
 });
 return freeze({...raw,bookings});
}
export function parseEnterpriseBookingActionPreview(raw,expected){
 const keys=['success','schema','operationId','operationDigest','bookingId','action','revision','tokenVersion','expiresAt','confirmationToken','restarted'];
 const expires=Date.parse(raw?.expiresAt);if(!exact(raw,keys)||raw.success!==true||raw.schema!=='golfriend.enterprise-booking-operation-authorization.v2'||!id.test(raw.operationId)||!sha.test(raw.operationDigest)||raw.bookingId!==expected.bookingId||raw.action!==expected.action||!actions.has(raw.action)||raw.revision!==expected.version||!Number.isSafeInteger(raw.tokenVersion)||raw.tokenVersion<1||!Number.isFinite(expires)||expires<=Date.now()||!/^ebct_[A-Za-z0-9_-]{32,200}$/.test(raw.confirmationToken)||typeof raw.restarted!=='boolean')throw Error('COORDINATION_ACTION_PREVIEW_INVALID');
 return freeze({...raw});
}
export function parseEnterpriseBookingTokenRecovery(raw,expected){
 const keys=['success','schema','operationId','operationDigest','bookingId','tokenVersion','confirmationToken','rotationId','restarted'];
 if(!exact(raw,keys)||raw.success!==true||raw.schema!=='golfriend.enterprise-booking-token-rotation-receipt.v2'||raw.operationId!==expected.operationId||raw.operationDigest!==expected.operationDigest||raw.bookingId!==expected.bookingId||!Number.isSafeInteger(raw.tokenVersion)||raw.tokenVersion<2||!/^ebct_[A-Za-z0-9_-]{32,200}$/.test(raw.confirmationToken)||!/^ebtr_[a-f0-9]{40}$/.test(raw.rotationId)||typeof raw.restarted!=='boolean')throw Error('COORDINATION_TOKEN_RECOVERY_INVALID');
 return freeze({...raw});
}
export function parseEnterpriseBookingActionResult(raw,expected){
 const keys=['success','bookingId','status','version','receiptId','eventId','restarted'];
 if(!exact(raw,keys)||raw.success!==true||raw.bookingId!==expected.bookingId||resultingStatus[expected.action]!==raw.status||raw.version!==expected.version+1||!/^ebor_[a-f0-9]{40}$/.test(raw.receiptId)||!/^ebce_[a-f0-9]{40}$/.test(raw.eventId)||typeof raw.restarted!=='boolean')throw Error('COORDINATION_ACTION_RESULT_INVALID');
 return freeze({...raw});
}
