import {useCallback, useEffect, useState} from "react";
import {partnerApplicationService} from "./partnerApplicationService";
import "./PartnerApplicationJourney.css";

const LOCALES = ["en", "th", "ko", "ja", "zh", "es", "fr", "de"] as const;
const EN = {title: "Join Golfriend", lead: "Apply as a golf course or partner. Save now and resume safely after signing in again.", organization: "Organization", type: "Organization type", country: "Country code", region: "Region", contact: "Verified contact", email: "Contact email", phone: "Contact phone", course: "Course name", address: "Course address", website: "Website", consent: "I consent to Golfriend reviewing these details and submitted materials.", terms: "I accept the partner application terms.", save: "Save draft", submit: "Submit for review", evidence: "Documents and media", unavailable: "Secure evidence storage is not configured. Upload fails closed; your draft remains available.", support: "Support conversation", send: "Send message", status: "Application status", materials: "Approved partner materials", loading: "Loading your application…", error: "The partner application service is unavailable. Nothing was submitted.", empty: "No application has been saved yet.", signout: "Sign out"};
const COPY: Record<string, typeof EN> = {
  en: EN,
  th: {...EN, title: "สมัครเข้าร่วม Golfriend", lead: "สมัครในนามสนามกอล์ฟหรือพันธมิตร บันทึกร่างและกลับมาทำต่อได้อย่างปลอดภัย", save: "บันทึกร่าง", submit: "ส่งให้แอดมินตรวจสอบ", support: "สนทนากับทีมสนับสนุน", send: "ส่งข้อความ", status: "สถานะใบสมัคร", loading: "กำลังโหลดใบสมัคร…", error: "ระบบใบสมัครพันธมิตรไม่พร้อมใช้งาน ไม่มีการส่งข้อมูล", unavailable: "ยังไม่ได้ตั้งค่าพื้นที่จัดเก็บเอกสารที่ปลอดภัย ระบบจึงปิดการอัปโหลด แต่ร่างยังคงอยู่"},
  ko: {...EN, title: "Golfriend 파트너 신청", save: "초안 저장", submit: "검토 요청"}, ja: {...EN, title: "Golfriend パートナー申請", save: "下書きを保存", submit: "審査に提出"},
  zh: {...EN, title: "申请成为 Golfriend 合作伙伴", save: "保存草稿", submit: "提交审核"}, es: {...EN, title: "Únete a Golfriend", save: "Guardar borrador", submit: "Enviar a revisión"},
  fr: {...EN, title: "Rejoindre Golfriend", save: "Enregistrer le brouillon", submit: "Soumettre à examen"}, de: {...EN, title: "Golfriend-Partner werden", save: "Entwurf speichern", submit: "Zur Prüfung senden"},
};
const blank: any = {organization: "", organizationType: "golf_course", country: "", region: "", contactName: "", contactEmail: "", contactPhone: "", locale: "en", courseName: "", courseAddress: "", courseWebsite: "", consent: false, terms: false};

export default function PartnerApplicationJourney({onSignOut}: {onSignOut: () => void}) {
  const [locale, setLocale] = useState<string>(localStorage.getItem("golfriend.locale") || "en"); const copy = COPY[locale] || EN;
  const [view, setView] = useState<any>(null); const [draft, setDraft] = useState<any>(blank); const [state, setState] = useState<"loading"|"ready"|"error">("loading"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setState("loading"); try { const next = await partnerApplicationService.load(); setView(next); const app = next.application; if (app) setDraft({organization: app.organization || "", organizationType: app.organizationType || "golf_course", country: app.country || "", region: app.region || "", contactName: app.contactName || "", contactEmail: app.contactEmail || "", contactPhone: app.contactPhone || "", locale: app.locale || locale, courseName: app.course?.name || "", courseAddress: app.course?.address || "", courseWebsite: app.course?.website || "", consent: Boolean(app.consent), terms: Boolean(app.terms)}); setState("ready"); } catch { setState("error"); } }, [locale]);
  useEffect(() => { void load(); }, [load]);
  const run = async (task: () => Promise<any>) => { setBusy(true); setNotice(""); try { const result = await task(); setNotice(`OK · ${result.receipt?.id || result.status || "saved"}`); await load(); } catch (error: any) { setNotice(error?.message?.includes("PROVIDER_UNCONFIGURED") ? copy.unavailable : copy.error); } finally { setBusy(false); } };
  const field = (key: string) => ({value: draft[key], onChange: (event: any) => setDraft({...draft, [key]: event.target.value})});
  if (state === "loading") return <main className="partner-application"><p role="status" aria-live="polite">{copy.loading}</p></main>;
  if (state === "error") return <main className="partner-application"><p role="alert">{copy.error}</p><button onClick={() => void load()}>Retry</button><button onClick={onSignOut}>{copy.signout}</button></main>;
  return <main className="partner-application"><header><div><span>GOLFRIEND · PARTNER PORTAL</span><h1>{copy.title}</h1><p>{copy.lead}</p></div><label>Language<select value={locale} onChange={(event) => {setLocale(event.target.value); localStorage.setItem("golfriend.locale", event.target.value);}}>{LOCALES.map((item) => <option key={item}>{item}</option>)}</select></label><button onClick={onSignOut}>{copy.signout}</button></header>
    <section className="partner-status" aria-label={copy.status}><h2>{copy.status}</h2><strong>{view?.application?.status || copy.empty}</strong>{view?.application?.reviewNote && <p>{view.application.reviewNote}</p>}{(view?.notifications || []).map((item: any) => <p key={item.id}>{item.kind}</p>)}</section>
    <form onSubmit={(event) => {event.preventDefault(); void run(() => partnerApplicationService.save(draft));}}><fieldset disabled={busy || ["submitted", "under_review", "approved"].includes(view?.application?.status)}><legend>1 · Organization and course</legend><label>{copy.organization}<input required {...field("organization")}/></label><label>{copy.type}<select {...field("organizationType")}><option value="golf_course">Golf course</option><option value="operator">Operator</option><option value="brand">Brand / OEM</option></select></label><label>{copy.country}<input required pattern="[A-Za-z]{2}" maxLength={2} {...field("country")}/></label><label>{copy.region}<input {...field("region")}/></label><label>{copy.course}<input required {...field("courseName")}/></label><label>{copy.address}<input {...field("courseAddress")}/></label><label>{copy.website}<input type="url" {...field("courseWebsite")}/></label></fieldset>
      <fieldset disabled={busy || ["submitted", "under_review", "approved"].includes(view?.application?.status)}><legend>2 · {copy.contact}</legend><label>{copy.contact}<input required {...field("contactName")}/></label><label>{copy.email}<input required type="email" {...field("contactEmail")}/></label><label>{copy.phone}<input type="tel" {...field("contactPhone")}/></label><label>Preferred language<select {...field("locale")}>{LOCALES.map((item) => <option key={item}>{item}</option>)}</select></label><label><input type="checkbox" checked={draft.consent} onChange={(event) => setDraft({...draft, consent: event.target.checked})}/>{copy.consent}</label><label><input type="checkbox" checked={draft.terms} onChange={(event) => setDraft({...draft, terms: event.target.checked})}/>{copy.terms}</label></fieldset><div className="partner-actions"><button disabled={busy} type="submit">{copy.save}</button><button disabled={busy || !view?.application || !draft.consent || !draft.terms || !draft.courseName} type="button" onClick={() => void run(partnerApplicationService.submit)}>{copy.submit}</button></div></form>
    <section><h2>{copy.evidence}</h2>{!view.evidenceStorageConfigured && <p role="status">{copy.unavailable}</p>}<input aria-label={copy.evidence} disabled={busy || !view.evidenceStorageConfigured} type="file" accept="application/pdf,image/png,image/jpeg,image/webp,.docx" onChange={(event) => {const file = event.target.files?.[0]; if (file) void run(() => partnerApplicationService.upload(file));}}/><ul>{(view.evidence || []).map((item: any) => <li key={item.evidenceId}>{item.fileName} · {item.sizeBytes} bytes</li>)}</ul></section>
    <section><h2>{copy.materials}</h2>{!view.materials?.length ? <p>{copy.empty}</p> : <ul>{view.materials.map((item: any) => <li key={item.assetId || item.id}>{item.title} · {(item.locales || []).join(", ")}</li>)}</ul>}</section>
    <section><h2>{copy.support}</h2><ol>{(view.messages || []).map((item: any) => <li key={item.id}><strong>{item.sender}</strong>: {item.message}</li>)}</ol><form onSubmit={(event) => {event.preventDefault(); void run(async () => {const result = await partnerApplicationService.message(message); setMessage(""); return result;});}}><label>{copy.support}<textarea required maxLength={2000} value={message} onChange={(event) => setMessage(event.target.value)}/></label><button disabled={busy || !message.trim()}>{copy.send}</button></form></section>
    <section><h2>Immutable audit history</h2><ol>{(view.audits || []).map((item: any) => <li key={item.id}>{item.kind} · {item.id}</li>)}</ol></section>{notice && <p role={notice.startsWith("OK") ? "status" : "alert"} aria-live="polite">{notice}</p>}
  </main>;
}
