export const PLAY_BOOKING_MESSAGE_DRAFT_TYPES=Object.freeze(['request_received','information_needed','alternative_proposed','confirmed','declined','cancellation_received','cancellation_accepted','cancellation_declined','manual_support_required']);
const TYPES=new Set(PLAY_BOOKING_MESSAGE_DRAFT_TYPES),LOCALES=new Set(['en','th','ko','ja','zh','es','fr','de']),STATUSES=new Set(['pending','changed','confirmed','rejected','cancelled','expired']);
const TYPE_STATUS=Object.freeze({request_received:['pending'],information_needed:['pending'],alternative_proposed:['changed'],confirmed:['confirmed'],declined:['rejected'],cancellation_received:['pending','changed','confirmed'],cancellation_accepted:['cancelled'],cancellation_declined:['pending','changed','confirmed'],manual_support_required:['pending','changed','confirmed','rejected','cancelled','expired']});
const ID=/^[A-Za-z0-9][A-Za-z0-9:_-]{1,159}$/,DATE=/^\d{4}-\d{2}-\d{2}$/,TIME=/^([01]\d|2[0-3]):[0-5]\d$/,ZONE=/^(UTC|[A-Za-z_]+\/[A-Za-z0-9_+.-]+)$/;
const PRIVATE=/(?:\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b|(?:\+?\d[\s().-]*){7,}|https?:\/\/)/i;
const record=value=>value!==null&&typeof value==='object'&&!Array.isArray(value);
const exact=(value,keys)=>record(value)&&Object.keys(value).every(key=>keys.has(key));
const text=(value,max)=>typeof value==='string'&&value.trim()===value&&value.length>0&&value.length<=max?value:null;
const identifier=value=>{const clean=text(value,160);return clean&&ID.test(clean)?clean:null};
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value)}return value};

function sha256(value){const bytes=new TextEncoder().encode(value),words=[],bits=bytes.length*8;for(const byte of bytes)words.push(byte);words.push(128);while(words.length%64!==56)words.push(0);for(let shift=56;shift>=0;shift-=8)words.push(Math.floor(bits/2**shift)&255);const constants=[],primes=[];for(let candidate=2;primes.length<64;candidate+=1)if(primes.every(prime=>candidate%prime)){primes.push(candidate);constants.push((Math.cbrt(candidate)%1*0x100000000)>>>0)}let hash=primes.slice(0,8).map(prime=>(Math.sqrt(prime)%1*0x100000000)>>>0),rotate=(word,count)=>(word>>>count)|(word<<(32-count));for(let offset=0;offset<words.length;offset+=64){const schedule=new Array(64);for(let i=0;i<16;i+=1)schedule[i]=((words[offset+i*4]<<24)|(words[offset+i*4+1]<<16)|(words[offset+i*4+2]<<8)|words[offset+i*4+3])>>>0;for(let i=16;i<64;i+=1){const x=schedule[i-15],y=schedule[i-2],s0=rotate(x,7)^rotate(x,18)^(x>>>3),s1=rotate(y,17)^rotate(y,19)^(y>>>10);schedule[i]=(schedule[i-16]+s0+schedule[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=hash;for(let i=0;i<64;i+=1){const s1=rotate(e,6)^rotate(e,11)^rotate(e,25),choose=(e&f)^(~e&g),t1=(h+s1+choose+constants[i]+schedule[i])>>>0,s0=rotate(a,2)^rotate(a,13)^rotate(a,22),majority=(a&b)^(a&c)^(b&c),t2=(s0+majority)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}hash=hash.map((word,i)=>(word+[a,b,c,d,e,f,g,h][i])>>>0)}return hash.map(word=>word.toString(16).padStart(8,'0')).join('')}

function facts(input){
 if(!exact(input,new Set(['type','bookingId','recipientRef','locale','revision','status','slot','message'])))throw new TypeError('Draft fields invalid.');
 const type=input.type,bookingId=identifier(input.bookingId),recipientRef=identifier(input.recipientRef),locale=input.locale,status=input.status,message=text(input.message,1000);
 if(!TYPES.has(type)||!bookingId||!recipientRef||!LOCALES.has(locale)||!Number.isSafeInteger(input.revision)||input.revision<1||!STATUSES.has(status)||!TYPE_STATUS[type].includes(status)||!message||PRIVATE.test(message))throw new TypeError('Draft facts invalid.');
 if(!exact(input.slot,new Set(['slotId','courseRef','date','time','timeZone'])))throw new TypeError('Draft slot invalid.');
 const slotId=identifier(input.slot.slotId),courseRef=identifier(input.slot.courseRef),date=input.slot.date,time=input.slot.time,timeZone=input.slot.timeZone;
 if(!slotId||!courseRef||!DATE.test(date)||!TIME.test(time)||!ZONE.test(timeZone))throw new TypeError('Draft slot invalid.');
 return freeze({type,bookingId,recipientRef,locale,revision:input.revision,status,slot:freeze({slotId,courseRef,date,time,timeZone}),message});
}
const canonical=value=>JSON.stringify([value.type,value.bookingId,value.recipientRef,value.locale,value.revision,value.status,value.slot.slotId,value.slot.courseRef,value.slot.date,value.slot.time,value.slot.timeZone,value.message]);
const inputOf=value=>({type:value?.type,bookingId:value?.bookingId,recipientRef:value?.recipientRef,locale:value?.locale,revision:value?.revision,status:value?.status,slot:value?.slot,message:value?.message});
export function playBookingMessageApprovalDigest(input){return `pbmd_${sha256(canonical(facts(input)))}`}
export function createPlayBookingMessageDraft(input,approvedDigest=null){const value=facts(input),approvalDigest=playBookingMessageApprovalDigest(value),approved=approvedDigest===approvalDigest;return freeze({schema:'golfriend.portal.play-booking-message-draft.v1',...value,deliveryState:'awaiting_delivery_provider',authority:'draft_only',approval:freeze({digest:approvalDigest,approvedDigest:approved?approvedDigest:null,approved}),containsRecipientName:false})}
export function approvePlayBookingMessageDraft(draft,digest){const input=facts(inputOf(draft)),expected=playBookingMessageApprovalDigest(input);if(digest!==expected)throw new TypeError('Draft approval digest mismatch.');return createPlayBookingMessageDraft(input,digest)}
export function validatePlayBookingMessageDraft(value){if(!exact(value,new Set(['schema','type','bookingId','recipientRef','locale','revision','status','slot','message','deliveryState','authority','approval','containsRecipientName'])))return false;try{const input=facts(inputOf(value)),expected=playBookingMessageApprovalDigest(input);return value.schema==='golfriend.portal.play-booking-message-draft.v1'&&value.deliveryState==='awaiting_delivery_provider'&&value.authority==='draft_only'&&value.containsRecipientName===false&&exact(value.approval,new Set(['digest','approvedDigest','approved']))&&value.approval.digest===expected&&value.approval.approved===(value.approval.approvedDigest===expected)&&(value.approval.approved||value.approval.approvedDigest===null)}catch{return false}}
