import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { getFunctions, httpsCallable } from 'firebase/functions';
import { useT } from '../../i18n/hooks.ts';
import { PLAY_BOOKING_DESK, type PlayBookingDeskKey } from '../../i18n/partner/playBookingDesk.ts';
import { classifyPlayBookingDeskError, createBookingAcknowledgementReceipt, parseBookingDeskActionResult, parseBookingDeskMessageResult, parsePlayBookingDeskResponse, validateBookingAcknowledgementReceipt, type BookingAcknowledgementReceipt, type PlayBookingDeskItem, type PlayBookingDeskProjection, type PlayBookingDeskStatus } from './bookingDeskProjection.mjs';
import './PlayBookingDesk.css';

type Action = 'confirm' | 'alternative' | 'cancel';
type Booking = PlayBookingDeskItem;
type ReadyProjection = Extract<PlayBookingDeskProjection,{state:'ready'}>;
type CallableResult = Readonly<Record<string, unknown>>;
type ManageInput = Readonly<{ bookingId:string; action:Action; expectedVersion:number; commandId:string; alternativeSlotId?:string; message?:string }>;

export interface PlayBookingDeskService {
  load():Promise<unknown>;
  manage(input:ManageInput):Promise<CallableResult>;
  sendMessage(input:Readonly<{bookingId:string;message:string;commandId:string}>):Promise<CallableResult>;
}

const call = async(name:string,data:Record<string,unknown>={}) => (await httpsCallable(getFunctions(),name)(data)).data as CallableResult;
export const productionPlayBookingDeskService:PlayBookingDeskService=Object.freeze({
  load:()=>call('getPlayBookingsPortalV2'),
  manage:(input:ManageInput)=>call('managePlayBookingV2',input),
  sendMessage:(input:Readonly<{bookingId:string;message:string;commandId:string}>)=>call('sendPlayBookingMessageV2',input),
});

type StoredReceipt=Readonly<{id:string;kind:Action|'message';recordedAt:string;acknowledgement:BookingAcknowledgementReceipt}>;
const receiptPattern=/^(?:pbr|pbm)_[a-f0-9]{32}$/;
const receiptKey=(admin:boolean)=>`golfriend.play-booking-desk.receipts.${admin?'admin':'portal'}.v1`;
function restoreReceipts(admin:boolean):readonly StoredReceipt[]{try{const value=JSON.parse(localStorage.getItem(receiptKey(admin))||'[]');if(!Array.isArray(value))return[];return Object.freeze(value.filter((x):x is StoredReceipt=>Boolean(x&&receiptPattern.test(String(x.id))&&['confirm','alternative','cancel','message'].includes(String(x.kind))&&typeof x.recordedAt==='string'&&validateBookingAcknowledgementReceipt(x.acknowledgement))).slice(-20).map(x=>Object.freeze({...x,acknowledgement:Object.freeze({...x.acknowledgement})})));}catch{return[]}}
function recordReceipt(admin:boolean,current:readonly StoredReceipt[],result:Readonly<{receiptId?:unknown;messageId?:unknown}>,kind:StoredReceipt['kind'],acknowledgement:BookingAcknowledgementReceipt){const id=String(result.receiptId||result.messageId||'');if(!receiptPattern.test(id))return current;const next=Object.freeze([...current.filter(x=>x.id!==id),Object.freeze({id,kind,recordedAt:new Date().toISOString(),acknowledgement})].slice(-20));try{localStorage.setItem(receiptKey(admin),JSON.stringify(next))}catch{/* Keep the receipt visible for this session. */}return next}
function commandId(){const id=globalThis.crypto?.randomUUID?.();if(!id)throw new Error('SECURE_COMMAND_ID_UNAVAILABLE');return id.replaceAll('-','_')}
// Played/completed evidence is not part of the verified Portal projection. Do not expose that backend action here.
const allowedStates:Record<Action,readonly PlayBookingDeskStatus[]>=Object.freeze({confirm:['pending','changed'],alternative:['pending'],cancel:['pending','changed','confirmed']});
function actionAllowed(projection:ReadyProjection,booking:Booking,action:Action|'message',admin:boolean){if(admin)return false;if(action==='message')return projection.permissions.message===true;return projection.permissions[action]===true&&allowedStates[action].includes(booking.status)}
const statusKey:Record<PlayBookingDeskStatus,PlayBookingDeskKey>={pending:'statusPending',confirmed:'statusConfirmed',rejected:'statusRejected',changed:'statusChanged',cancelled:'statusCancelled',expired:'statusExpired'};

export default function PlayBookingLifecycleV2({admin=false,service=productionPlayBookingDeskService}:{admin?:boolean;service?:PlayBookingDeskService}){
  const t=useT(PLAY_BOOKING_DESK) as (key:PlayBookingDeskKey)=>string;
  const dialogRef=useRef<HTMLElement|null>(null),returnFocusRef=useRef<HTMLElement|null>(null);
  const[projection,setProjection]=useState<PlayBookingDeskProjection|null>(null),[state,setState]=useState<'loading'|'ready'|'error'>('loading'),[selectedId,setSelectedId]=useState<string|null>(null),[pending,setPending]=useState<Readonly<{action:Action;booking:Booking}>|null>(null),[acknowledged,setAcknowledged]=useState(false),[alternativeSlotId,setAlternativeSlotId]=useState(''),[alternativeMessage,setAlternativeMessage]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<'success'|'conflict'|'stale'|'unavailable'|''>(''),[receipts,setReceipts]=useState<readonly StoredReceipt[]>(()=>restoreReceipts(admin));
  const load=useCallback(async()=>{if(admin){setProjection(null);setState('error');return}setState('loading');try{const next=parsePlayBookingDeskResponse(await service.load());setProjection(next);if(next.state==='ready'){setSelectedId(current=>current&&next.bookings.some(x=>x.bookingId===current)?current:next.bookings[0]?.bookingId||null);setState('ready')}else setState('error')}catch(error){setProjection(null);setNotice(classifyPlayBookingDeskError(error));setState('error')}},[admin,service]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{setPending(null);setAcknowledged(false);setReceipts(restoreReceipts(admin))},[admin]);
  useEffect(()=>{if(pending)dialogRef.current?.focus()},[pending]);
  const ready=projection?.state==='ready'?projection as ReadyProjection:null,selected=ready?.bookings.find(x=>x.bookingId===selectedId)||null;
  const queue=useMemo(()=>[...(ready?.bookings||[])].sort((a,b)=>{const rank=(x:PlayBookingDeskStatus)=>x==='pending'?0:x==='changed'?1:x==='confirmed'?2:3;return rank(a.status)-rank(b.status)||a.teeTime.date.localeCompare(b.teeTime.date)||a.teeTime.time.localeCompare(b.teeTime.time)}),[ready]);
  const restoreFocus=()=>{const target=returnFocusRef.current;returnFocusRef.current=null;globalThis.setTimeout(()=>target?.focus(),0)};
  const dismiss=()=>{setPending(null);setAcknowledged(false);restoreFocus()};
  const begin=(action:Action,trigger:HTMLElement)=>{if(!ready||!selected||!actionAllowed(ready,selected,action,admin))return;returnFocusRef.current=trigger;setPending(Object.freeze({action,booking:selected}));setAcknowledged(false);setAlternativeSlotId('');setAlternativeMessage('');setNotice('')};
  const execute=async()=>{if(!pending||!ready||!acknowledged||busy||!actionAllowed(ready,pending.booking,pending.action,admin))return;if(pending.action==='alternative'&&(!alternativeSlotId.trim()||!alternativeMessage.trim()))return;setBusy(true);setNotice('');try{const id=commandId(),raw=await service.manage({bookingId:pending.booking.bookingId,action:pending.action,expectedVersion:pending.booking.version,commandId:id,...(pending.action==='alternative'?{alternativeSlotId:alternativeSlotId.trim(),message:alternativeMessage.trim()}:{})}),result=parseBookingDeskActionResult(raw,{bookingId:pending.booking.bookingId,action:pending.action,commandId:id,currentVersion:pending.booking.version,currentStatus:pending.booking.status});if(result.state!=='verified')throw new Error('ACTION_RESULT_UNVERIFIED');const ack=createBookingAcknowledgementReceipt({bookingId:pending.booking.bookingId,version:pending.booking.version,status:pending.booking.status,action:pending.action,commandId:id});setReceipts(current=>recordReceipt(admin,current,result,pending.action,ack));setPending(null);setAcknowledged(false);setNotice('success');restoreFocus();await load()}catch(error){setNotice(classifyPlayBookingDeskError(error))}finally{setBusy(false)}};
  const send=async()=>{const text=message.trim();if(!ready||!selected||!actionAllowed(ready,selected,'message',admin)||!text||busy)return;setBusy(true);setNotice('');try{const id=commandId(),raw=await service.sendMessage({bookingId:selected.bookingId,message:text,commandId:id}),result=parseBookingDeskMessageResult(raw,{bookingId:selected.bookingId,commandId:id,currentVersion:selected.version,currentStatus:selected.status});if(result.state!=='verified')throw new Error('MESSAGE_RESULT_UNVERIFIED');const ack=createBookingAcknowledgementReceipt({bookingId:selected.bookingId,version:selected.version,status:selected.status,action:'message',commandId:id});setReceipts(current=>recordReceipt(admin,current,result,'message',ack));setMessage('');setNotice('success');await load()}catch(error){setNotice(classifyPlayBookingDeskError(error))}finally{setBusy(false)}};
  if(admin)return <section className="booking-desk-state"><h2>{t('title')}</h2><p role="status">{t('loadError')}</p><p>{t('providerBoundary')} {t('noChange')}</p></section>;
  if(state==='loading')return <p className="booking-desk-state" role="status" aria-live="polite">{t('loading')}</p>;
  if(state==='error'||!ready)return <section className="booking-desk-state"><p role="alert">{t(projection?.state==='delegated_scope_unavailable'?'delegatedScopeUnavailable':projection?.state==='unavailable'?'invalidDataError':'loadError')}</p><button type="button" onClick={()=>void load()}>{t('retry')}</button><p>{t('retryHint')}</p></section>;
  return <section className="booking-desk" aria-labelledby={`play-booking-desk-${admin?'admin':'portal'}`}>
    <header className="booking-desk__header"><div><span>{t('sectionLabel')}</span><h2 id={`play-booking-desk-${admin?'admin':'portal'}`}>{t('title')}</h2><p>{t('subtitle')}</p><p>{t('providerBoundary')} {t('privacyBoundary')}</p></div><button type="button" className="booking-desk__refresh" disabled={busy} onClick={()=>void load()}>{t('reload')}</button></header>
    {!ready.notificationProviderConfigured&&<p className="booking-desk__notice" role="status">{t('notificationUnavailable')}</p>}
    {notice&&<p className={`booking-desk__notice booking-desk__notice--${notice}`} role={notice==='success'?'status':'alert'} aria-live={notice==='success'?'polite':'assertive'}>{t(notice==='success'?'actionSucceeded':notice==='conflict'?'conflictError':notice==='stale'?'staleError':'operationError')}</p>}
    <div className="booking-desk__layout"><nav className="booking-desk__queue" aria-label={t('queueTitle')}><h3>{t('queueTitle')}</h3>
      {!queue.length?<p>{t('empty')}</p>:<ul>{queue.map(booking=><li key={booking.bookingId}><button type="button" aria-current={selectedId===booking.bookingId?'true':undefined} onClick={()=>{setSelectedId(booking.bookingId);setPending(null)}}><strong>{booking.memberDisplayName}</strong><span>{booking.course.name||booking.course.courseId} · {booking.teeTime.date} {booking.teeTime.time}</span><i data-status={booking.status}>{t(statusKey[booking.status])}</i></button></li>)}</ul>}
    </nav><article className="booking-desk__detail" aria-live="polite">{!selected?<p>{t('detailsTitle')}</p>:<>
      <div className="booking-desk__detail-heading"><div><span>{t('referenceLabel')}</span><h3>{selected.bookingId}</h3></div><i data-status={selected.status}>{t(statusKey[selected.status])}</i></div>
      <dl><div><dt>{t('memberLabel')}</dt><dd>{selected.memberDisplayName}</dd></div><div><dt>{t('courseLabel')}</dt><dd>{selected.course.name||selected.course.courseId}</dd></div><div><dt>{t('dateLabel')}</dt><dd>{selected.teeTime.date}</dd></div><div><dt>{t('timeLabel')}</dt><dd>{selected.teeTime.time} · {selected.teeTime.timeZone}</dd></div><div><dt>{t('providerLabel')}</dt><dd>{selected.provider?.displayName||t('unavailableValue')}</dd></div><div><dt>{t('termsLabel')}</dt><dd>{selected.terms||t('unavailableValue')}</dd></div><div><dt>{t('contactLabel')}</dt><dd>{t('unavailableValue')}</dd></div><div><dt>{t('referenceLabel')}</dt><dd>{selected.reference||t('unavailableValue')}</dd></div><div><dt>{t('versionLabel')}</dt><dd>{selected.version}</dd></div></dl>
      <div className="booking-desk__actions" aria-label={t('actionsLabel')}>{(['confirm','alternative','cancel'] as Action[]).map(action=>actionAllowed(ready,selected,action,admin)&&<button type="button" key={action} disabled={busy} onClick={event=>begin(action,event.currentTarget)}>{t(action==='alternative'?'proposeAlternative':action)}</button>)}</div>
      {pending&&<section ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" className="booking-desk__confirmation" aria-labelledby="booking-action-confirmation"><h4 id="booking-action-confirmation">{t(pending.action==='alternative'?'alternativeTitle':pending.action==='cancel'?'cancelReviewTitle':'actionsLabel')}</h4>{pending.action==='cancel'&&<p>{t('cancelReviewBody')}</p>}<p>{t(pending.action==='alternative'?'proposeAlternative':pending.action)} · {pending.booking.bookingId} · v{pending.booking.version}</p>{pending.action==='alternative'&&<div className="booking-desk__form-grid"><label>{t('alternativeSlotLabel')}<input required value={alternativeSlotId} maxLength={160} onChange={e=>setAlternativeSlotId(e.target.value)}/></label><label>{t('alternativeMessageLabel')}<textarea required value={alternativeMessage} maxLength={500} onChange={e=>setAlternativeMessage(e.target.value)}/></label></div>}<label className="booking-desk__ack"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/>{t('authorizedAcknowledgement')}</label><div><button type="button" onClick={()=>void execute()} disabled={busy||!acknowledged||(pending.action==='alternative'&&(!alternativeSlotId.trim()||!alternativeMessage.trim()))}>{busy?t('busy'):t('submit')}</button><button type="button" onClick={dismiss} disabled={busy}>{t('close')}</button></div></section>}
      {!admin&&actionAllowed(ready,selected,'message',admin)&&<form className="booking-desk__message" onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="booking-desk-message">{t('messageLabel')}</label><textarea id="booking-desk-message" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)}/><button type="submit" disabled={busy||!message.trim()}>{t('messageMember')}</button></form>}
    </>}</article></div>
    <section className="booking-desk__receipts" aria-labelledby="booking-desk-receipts"><h3 id="booking-desk-receipts">{t('receiptsTitle')}</h3><p>{t('recoveryTitle')}</p>{!receipts.length?<p>{t('noChange')}</p>:<ol>{[...receipts].reverse().map(receipt=><li key={receipt.id}><code>{receipt.id}</code><code>{receipt.acknowledgement.receiptId}</code><span>{t(receipt.kind==='alternative'?'proposeAlternative':receipt.kind==='message'?'messageMember':receipt.kind)} · <time dateTime={receipt.recordedAt}>{receipt.recordedAt}</time></span></li>)}</ol>}</section>
  </section>
}
