import {useCallback,useEffect,useRef,useState} from 'react';
import {useLocale} from '../../i18n/hooks';
import {SMALL_BUSINESS_COPY} from '../../i18n/smallBusiness';
import {commandId,type PortalProjection} from '../smallBusiness/smallBusinessModel';
import {firebaseSmallBusinessProvider,type SmallBusinessProvider} from '../smallBusiness/smallBusinessProvider';
import '../smallBusiness/smallBusiness.css';
import SmallBusinessPortalForms from '../smallBusiness/SmallBusinessPortalForms';
export default function SmallBusinessDashboard({provider=firebaseSmallBusinessProvider}:{partnerData?:unknown;provider?:SmallBusinessProvider}){
 const locale=useLocale(),t=SMALL_BUSINESS_COPY[locale],[data,setData]=useState<PortalProjection|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false),[action,setAction]=useState<'submit'|'withdraw'>('submit'),stable=useRef(commandId('small_business_portal')),requestGeneration=useRef(0);
 const load=useCallback(async()=>{const generation=++requestGeneration.current;setBusy(true);setMessage('');const next=await provider.portal(locale);if(generation!==requestGeneration.current)return;setData(next);setBusy(false)},[locale,provider]); useEffect(()=>{void load();return()=>{requestGeneration.current++}},[load]);
 const run=async()=>{if(!confirmed||!data?.business)return;if(!navigator.onLine){setMessage(t.offline);return}const generation=++requestGeneration.current;setBusy(true);try{const input={commandId:stable.current,businessId:data.business.businessId,expectedVersion:data.business.version};action==='submit'?await provider.submitApplication(input):await provider.withdraw(input);if(generation!==requestGeneration.current)return;stable.current=commandId('small_business_portal');setConfirmed(false);await load()}catch(error){if(generation===requestGeneration.current)setMessage(String(error).includes('STALE')?t.conflict:t.unavailable)}finally{if(generation===requestGeneration.current)setBusy(false)}};
 if(busy&&!data)return <main className="sb-shell" aria-busy="true"><p role="status">{t.loading}</p></main>;
 return <main className="sb-shell" id="main-content"><header className="sb-header"><div><p className="sb-kicker">GOLFRIEND V2</p><h1>{t.title}</h1><p>{t.lead}</p></div><button onClick={()=>void load()} disabled={busy}>{t.refresh}</button></header><div className="sb-live" role="status" aria-live="polite">{message}</div>
 {data?.state==='unavailable'&&<section className="sb-card sb-alert" role="alert"><h2>{t.unavailable}</h2><code>{data.supportReference}</code><button onClick={()=>void load()}>{t.retry}</button></section>}{data?.state==='empty'&&<section className="sb-card"><p>{t.empty}</p></section>}
 {data?.business&&<><section className="sb-card"><h2>{t.profile}</h2><dl className="sb-facts"><div><dt>{t.status}</dt><dd>{data.business.status}</dd></div><div><dt>{t.category}</dt><dd>{data.business.category}</dd></div><div><dt>{t.serviceArea}</dt><dd>{data.business.serviceArea}</dd></div><div><dt>{t.locales}</dt><dd>{data.business.supportedLocales.join(', ')}</dd></div></dl><div className="sb-actions"><select aria-label={t.decision} value={action} onChange={e=>{setAction(e.target.value as typeof action);setConfirmed(false)}}><option value="submit">{t.submit}</option><option value="withdraw">{t.withdraw}</option></select><label className="sb-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>{action==='submit'?t.confirmSubmit:t.confirmWithdraw}</span></label><button disabled={busy||!confirmed} onClick={()=>void run()}>{action==='submit'?t.submit:t.withdraw}</button></div></section>
 <section className="sb-card"><h2>{t.locations}</h2>{data.locations.length?data.locations.map(location=><article key={location.locationId}><h3>{location.label}</h3><p>{location.city}, {location.country}</p><ul>{location.hours.map(hour=><li key={hour.day}>{hour.day}: {hour.closed?'—':`${hour.opens}–${hour.closes}`}</li>)}</ul></article>):<p>{t.empty}</p>}</section>
 <section className="sb-card"><h2>{t.subscription}</h2><p>{t.subscriptionBoundary}</p>{data.plans.map(plan=><article key={`${plan.planId}:${plan.version}`}><h3>{plan.planId} · v{plan.version}</h3><p>{plan.priceDisplay||t.unavailable}</p><button disabled={plan.status!=='available'} onClick={()=>setMessage(t.subscriptionBoundary)}>{t.prepareIntent}</button></article>)}</section>
 <SmallBusinessPortalForms data={data} provider={provider} locale={locale} t={t} onReload={load} onMessage={setMessage}/><section className="sb-card"><h2>{t.promotions}</h2><p>{t.promotionBoundary}</p>{data.promotions.map(p=><article key={p.promotionId}><h3>{p.status} · {p.locale}</h3><p>{p.jurisdiction} · {p.effectiveAt} → {p.expiresAt}</p><p>{t.sponsored}</p></article>)}</section><section className="sb-card"><h2>{t.history}</h2><ol>{data.receipts.map(r=><li key={r.receiptId}>{r.occurredAt} · {r.action} · v{r.version}</li>)}</ol></section></>}
 </main>;
}
