import {getFunctions,httpsCallable}from"firebase/functions";
export const ENTERPRISE_ONBOARDING_SCHEMA="golfriend.enterprise-course-onboarding.v1";
export const TRIAL_OPTIONS=[30,90]as const;export type TrialDays=typeof TRIAL_OPTIONS[number];
export type Context={membershipId:string;organizationId:string;propertyId:string;courseId:string};
export type CourseOnboardingDraft={context:Context;organizationRequest:{legalName:string;registrationNumber:string;jurisdiction:string;displayName:string};propertyRequest:{displayName:string;address:string};courseRequest:{canonicalCourseId:string;displayName:string;address:string;website:string};representative:{fullName:string;jobTitle:string;authorityDeclaration:boolean;businessEmail:string;phone:string;preferredLanguage:string};profile:{description:string;holes:string;timezone:string;facilities:string;accessibility:string;courseProfileAttemptId:string};disclosures:{dataUse:boolean;memberManagement:boolean;tournamentManagement:boolean;bookingCommission:boolean};requestedTrialDays:TrialDays;trialOfferId:string};
export type OnboardingStatus="draft"|"submitted"|"under_review"|"changes_requested"|"approved_for_trial"|"trial_active"|"trial_expiring"|"trial_expired"|"conversion_review"|"active_partner"|"declined"|"suspended"|"withdrawn"|"unavailable";
export type AgreementPresentation={agreementId:string;version:string;locale:string;canonicalLocale:string;canonicalDigest:string;localizedDigest:string;content:string;canonicalContent:string;commissionPolicyRef:string;commissionBps:number|null;trialTermsRef:string;dataUseTermsRef:string;legalReviewRequired:boolean;coveredOrganizationId:string;coveredPropertyIds:string[];coveredCourseIds:string[]};
export type OnboardingProjection={schema:string;status:OnboardingStatus;version:number;draft?:CourseOnboardingDraft;agreement?:AgreementPresentation;agreementAcceptance?:{receiptId:string;acceptedAt:string;version:string;locale:string};trial?:{durationDays:TrialDays;startsAt:string|null;endsAt:string|null;status:string;activationReceiptId:string|null};review?:{referenceId:string;requirements:string[]};capabilities?:Record<string,"available"|"unavailable">;auditReceipts?:Array<{receiptId:string;kind:string;createdAt:string}>;stale?:boolean;suspended?:boolean};
const call=async<T>(name:string,payload:Record<string,unknown>={})=>(await httpsCallable(getFunctions(),name)(payload)).data as T;
const flatten=(d:CourseOnboardingDraft)=>({legalName:d.organizationRequest.legalName,registrationNumber:d.organizationRequest.registrationNumber,registeredAddress:d.propertyRequest.address,representativeName:d.representative.fullName,representativeTitle:d.representative.jobTitle,representativeAuthorityDeclaration:d.representative.authorityDeclaration?"explicit_authority_declaration":"",contactEmail:d.representative.businessEmail,contactPhone:d.representative.phone,preferredLocale:d.representative.preferredLanguage,courseProfileAttemptId:d.profile.courseProfileAttemptId,requestedTrialDays:d.requestedTrialDays,dataUseAcknowledged:d.disclosures.dataUse,memberPurposeAcknowledged:d.disclosures.memberManagement,tournamentPurposeAcknowledged:d.disclosures.tournamentManagement,bookingCommissionAcknowledged:d.disclosures.bookingCommission});
const projection=(raw:any):OnboardingProjection=>{const a=raw?.application,t=raw?.trial,d=a?.draft,context={membershipId:String(a?.membershipId||a?.actorMembershipId||""),organizationId:String(a?.organizationId||""),propertyId:String(a?.propertyId||""),courseId:String(a?.courseId||"")};const draft=d?{...({context,organizationRequest:{legalName:String(d.legalName||""),registrationNumber:String(d.registrationNumber||""),jurisdiction:"",displayName:""},propertyRequest:{displayName:"",address:String(d.registeredAddress||"")},courseRequest:{canonicalCourseId:context.courseId,displayName:"",address:"",website:""},representative:{fullName:String(d.representativeName||""),jobTitle:String(d.representativeTitle||""),authorityDeclaration:Boolean(d.representativeAuthorityDeclaration),businessEmail:String(d.contactEmail||""),phone:String(d.contactPhone||""),preferredLanguage:String(d.preferredLocale||"en")},profile:{description:"",holes:"",timezone:"",facilities:"",accessibility:"",courseProfileAttemptId:String(d.courseProfileAttemptId||"")},disclosures:{dataUse:d.dataUseAcknowledged===true,memberManagement:d.memberPurposeAcknowledged===true,tournamentManagement:d.tournamentPurposeAcknowledged===true,bookingCommission:d.bookingCommissionAcknowledged===true},requestedTrialDays:Number(d.requestedTrialDays)===90?90:30,trialOfferId:String(a?.trialOfferId||"")}as CourseOnboardingDraft)}:undefined;const acceptance=a?.agreementAcceptance;return{schema:String(raw?.schema||ENTERPRISE_ONBOARDING_SCHEMA),status:(a?.status||(raw?.state==="empty"?"draft":"unavailable"))as OnboardingStatus,version:Number(a?.version||0),draft,agreementAcceptance:acceptance?{receiptId:String(acceptance.receiptId),acceptedAt:String(acceptance.acceptedAt||""),version:String(acceptance.agreementVersion||""),locale:String(acceptance.acceptedLocale||"")}:undefined,trial:t?{durationDays:t.durationDays,startsAt:t.startsAt,endsAt:t.endsAt,status:t.status,activationReceiptId:t.activationReceiptId}:undefined,review:a?.reviewReference||a?.requirements?.length?{referenceId:String(a?.reviewReference||"admin_support_required"),requirements:Array.isArray(a?.requirements)?a.requirements.map(String):[]}:undefined,auditReceipts:Array.isArray(raw?.receipts)?raw.receipts:[],capabilities:raw?.capabilities,suspended:raw?.state==="suspended"}};
export const createCommandId=(kind:string)=>`${kind}_${crypto.randomUUID()}`;
export const enterpriseCourseOnboardingService={
 read:async(context:Context)=>projection(await call<any>("getEnterpriseCourseOnboardingV1",{context})),
 saveDraft:async(context:Context,draft:CourseOnboardingDraft,baseVersion:number,commandId:string)=>projection(await call<any>("saveEnterpriseCourseOnboardingDraftV1",{context,commandId,expectedVersion:baseVersion,draft:flatten(draft)})),
 submit:async(context:Context,baseVersion:number,commandId:string)=>projection(await call<any>("submitEnterpriseCourseOnboardingV1",{context,commandId,expectedVersion:baseVersion})),
 agreement:async(context:Context,locale:string,trialOfferId:string,trialDays:TrialDays)=>{const x=await call<any>("previewEnterpriseAgreementV1",{context,locale,trialOfferId,trialDays});return{agreementId:String(x.agreementId),version:String(x.version),locale:String(x.acceptedLocale),canonicalLocale:"en",canonicalDigest:String(x.canonicalContentDigest),localizedDigest:String(x.contentDigest),content:String(x.content),canonicalContent:String(x.canonicalContent),commissionPolicyRef:String(x.bookingCommissionPolicyVersion),commissionBps:Number(x.bookingCommissionBps),trialTermsRef:String(x.trialPolicyVersion),dataUseTermsRef:String(x.dataUseTermsVersion),legalReviewRequired:x.legalReviewRequired===true,coveredOrganizationId:String(x.organizationId),coveredPropertyIds:[String(x.propertyId)],coveredCourseIds:[String(x.courseId)]};},
 acceptAgreement:(context:Context,a:AgreementPresentation,commandId:string,trialOfferId:string,trialDays:TrialDays)=>call<any>("acceptEnterpriseAgreementV1",{context,commandId,locale:a.locale,trialOfferId,trialDays,contentDigest:a.localizedDigest,explicitlyAccepted:true}),
 withdraw:(context:Context,baseVersion:number,commandId:string)=>call<any>("withdrawEnterpriseCourseOnboardingV1",{context,commandId,expectedVersion:baseVersion}),
};
