import{useCallback,useEffect,useId,useRef,useState}from"react";
import{useLocale}from"../../i18n/hooks";
import{ENTERPRISE_ONBOARDING_COPY,ENTERPRISE_ONBOARDING_LOCALES,type EnterpriseOnboardingLocale}from"../../i18n/partner/enterpriseCourseOnboarding";
import{organizationAuthorityService}from"./enterprise/organizationAuthorityService";
import{courseProfileOperationsService}from"./enterprise/courseProfileOperationsService";
import{createCommandId,enterpriseCourseOnboardingService,type AgreementPresentation,type Context,type CourseOnboardingDraft,type OnboardingProjection}from"./verifiedCourseOnboardingService";

const blank=(locale:string):CourseOnboardingDraft=>({context:{membershipId:"",organizationId:"",propertyId:"",courseId:""},organizationRequest:{legalName:"",registrationNumber:"",jurisdiction:"",displayName:""},propertyRequest:{displayName:"",address:""},courseRequest:{canonicalCourseId:"",displayName:"",address:"",website:""},representative:{fullName:"",jobTitle:"",authorityDeclaration:false,businessEmail:"",phone:"",preferredLanguage:locale},profile:{description:"",holes:"",timezone:"",facilities:"",accessibility:"",courseProfileAttemptId:""},disclosures:{dataUse:false,memberManagement:false,tournamentManagement:false,bookingCommission:false},requestedTrialDays:30,trialOfferId:""});
const locked=new Set(["submitted","under_review","approved_for_trial","trial_active","trial_expiring","trial_expired","conversion_review","active_partner","declined","suspended","withdrawn"]);
const key=(x:Context)=>`${x.membershipId}|${x.organizationId}|${x.propertyId}|${x.courseId}`;

export default function VerifiedCourseOnboarding(){
 const raw=useLocale()as EnterpriseOnboardingLocale,locale=ENTERPRISE_ONBOARDING_LOCALES.includes(raw)?raw:"en",t=ENTERPRISE_ONBOARDING_COPY[locale],id=useId();
 const[draft,setDraft]=useState(()=>blank(locale)),[view,setView]=useState<OnboardingProjection|null>(null),[agreement,setAgreement]=useState<AgreementPresentation|null>(null),[phase,setPhase]=useState<"loading"|"scope"|"ready"|"unavailable">("loading"),[scopes,setScopes]=useState<Context[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[accepted,setAccepted]=useState(false);
 const commands=useRef<Record<string,string>>({}),profileAttempts=useRef<Record<string,string>>({}),command=(kind:string)=>commands.current[kind]??(commands.current[kind]=createCommandId(kind));
 const preview=useCallback(async(next=draft)=>{setAccepted(false);setAgreement(null);if(!next.context.courseId||!next.trialOfferId)return;try{setAgreement(await enterpriseCourseOnboardingService.agreement(next.context,locale,next.trialOfferId,next.requestedTrialDays))}catch{setAgreement(null)}},[draft,locale]);
 const load=useCallback(async(context:Context,profileAttemptId=profileAttempts.current[key(context)]||"")=>{setPhase("loading");try{const current=await enterpriseCourseOnboardingService.read(context);setView(current);const hydrated=current.draft?{...current.draft,context,trialOfferId:current.draft.trialOfferId||draft.trialOfferId}:{...draft,context,profile:{...draft.profile,courseProfileAttemptId:profileAttemptId}};setDraft(hydrated);setPhase("ready");await preview(hydrated)}catch{setPhase("unavailable")}},[draft,preview]);
 useEffect(()=>{void(async()=>{const authority=await organizationAuthorityService.load(),memberships=authority.memberships.filter(x=>x.status==="active"&&x.scope.kind==="course"&&authority.actorMembershipIds.includes(x.membershipId)),available=memberships.map(x=>x.scope.kind==="course"?{membershipId:x.membershipId,organizationId:x.organizationId,propertyId:x.scope.propertyId,courseId:x.scope.courseId}:null).filter((x):x is Context=>x!==null);await Promise.all(available.map(async context=>{const membership=memberships.find(x=>x.membershipId===context.membershipId)!,organization=authority.organizations.find(x=>x.organizationId===context.organizationId),course=organization?.properties.find(x=>x.propertyId===context.propertyId)?.courses.find(x=>x.courseId===context.courseId),profile=await courseProfileOperationsService.read({actorMembershipId:context.membershipId,organizationId:context.organizationId,propertyId:context.propertyId,courseId:context.courseId,role:membership.role,scope:membership.scope,organizationStatus:organization?.status??"unavailable",courseStatus:course?.status??"unavailable"});profileAttempts.current[key(context)]=profile.editAttempt?.attemptId||""}));setScopes(available);setPhase(available.length?"scope":"unavailable")})()},[]);
 useEffect(()=>{if(phase==="ready")void preview({...draft,representative:{...draft.representative,preferredLanguage:locale}})},[locale,draft.requestedTrialDays,draft.trialOfferId,draft.context.courseId]);
 const run=async(kind:string,work:()=>Promise<unknown>)=>{setBusy(true);setNotice("");try{await work();commands.current[kind]="";await load(draft.context);setNotice(t.saved)}catch{setNotice(t.retryNotice)}finally{setBusy(false)}};
 const put=(group:keyof CourseOnboardingDraft,field:string,value:string|boolean)=>setDraft(x=>({...x,[group]:{...(x[group]as object),[field]:value}}));
 const field=(group:keyof CourseOnboardingDraft,name:string,label:string,props:Record<string,unknown>={})=><label htmlFor={`${id}-${group}-${name}`}>{label}<input id={`${id}-${group}-${name}`} value={String((draft[group]as any)[name]??"")} onChange={e=>put(group,name,e.target.value)} {...props}/></label>;
 if(phase==="loading")return <section aria-busy="true"><h2>{t.title}</h2><p role="status" aria-live="polite">{t.loading}</p></section>;
 if(phase==="unavailable")return <section><h2>{t.title}</h2><p role="alert">{t.unavailable}</p><p>{t.adminUnavailable}</p></section>;
 if(phase==="scope")return <section aria-labelledby={`${id}-scope-title`}><h2 id={`${id}-scope-title`}>{t.title}</h2><p>{t.chooseScope}</p><label htmlFor={`${id}-scope`}>{t.courseScope}<select id={`${id}-scope`} defaultValue="" onChange={e=>{const context=scopes[Number(e.target.value)];if(context){setDraft(x=>({...x,context,profile:{...x.profile,courseProfileAttemptId:profileAttempts.current[key(context)]||""}}));setAgreement(null);setAccepted(false);void load(context)}}}><option value="" disabled>{t.selectScope}</option>{scopes.map((x,index)=><option key={key(x)} value={index}>{x.organizationId} · {x.propertyId} · {x.courseId}</option>)}</select></label></section>;
 const status=view?.status??"draft",disabled=busy||locked.has(status)||view?.suspended===true,allDisclosed=Object.values(draft.disclosures).every(Boolean);
 return <section className="partner-application" aria-labelledby={`${id}-title`}>
  <header><h2 id={`${id}-title`}>{t.title}</h2><p>{t.intro}</p></header>
  <nav aria-label={t.steps}><ol>{t.stepLabels.map((x,i)=><li key={x} aria-current={i===0?"step":undefined}>{x}</li>)}</ol></nav>
  <aside role="status" aria-live="polite"><strong>{t.status}: {(t.statuses as Record<string,string>)[status]??status}</strong><p>{t.truth}</p>{["changes_requested","approved_for_trial","conversion_review","declined","suspended"].includes(status)&&<p>{t.adminUnavailable}</p>}</aside>
  <form onSubmit={e=>{e.preventDefault();void run("save",()=>enterpriseCourseOnboardingService.saveDraft(draft.context,draft,view?.version??0,command("save")))}}>
   <fieldset disabled><legend>{t.scope}</legend>{field("context","membershipId",t.membershipId)}{field("context","organizationId",t.organizationId)}{field("context","propertyId",t.propertyId)}{field("context","courseId",t.courseId)}</fieldset>
   <fieldset disabled={disabled}><legend>{t.organization}</legend>{field("organizationRequest","legalName",t.legalName,{required:true})}{field("organizationRequest","registrationNumber",t.registration,{required:true})}{field("propertyRequest","address",t.address,{required:true})}</fieldset>
   <fieldset disabled={disabled}><legend>{t.representative}</legend>{field("representative","fullName",t.fullName,{required:true})}{field("representative","jobTitle",t.jobTitle,{required:true})}{field("representative","businessEmail",t.email,{required:true,type:"email"})}{field("representative","phone",t.phone,{type:"tel"})}<label><input type="checkbox" checked={draft.representative.authorityDeclaration} onChange={e=>put("representative","authorityDeclaration",e.target.checked)}/>{t.authorityDeclaration}</label></fieldset>
   <fieldset disabled><legend>{t.profile}</legend><p><strong>{t.profileAttempt}:</strong> {draft.profile.courseProfileAttemptId||t.profileUnavailable}</p><p>{t.profileHandoff}</p></fieldset>
   <fieldset disabled={disabled}><legend>{t.disclosures}</legend>{(["dataUse","memberManagement","tournamentManagement","bookingCommission"]as const).map(x=><label key={x}><input type="checkbox" checked={draft.disclosures[x]} onChange={e=>put("disclosures",x,e.target.checked)}/>{t[x]}</label>)}</fieldset>
   <fieldset disabled={disabled}><legend>{t.trial}</legend><label htmlFor={`${id}-offer`}>{t.trialOffer}<input id={`${id}-offer`} required value={draft.trialOfferId} onChange={e=>{setDraft(x=>({...x,trialOfferId:e.target.value}));setAgreement(null);setAccepted(false)}}/></label>{([30,90]as const).map(days=><label key={days}><input type="radio" name={`${id}-trial`} checked={draft.requestedTrialDays===days} onChange={()=>{setDraft(x=>({...x,requestedTrialDays:days}));setAgreement(null);setAccepted(false)}}/>{days} {t.days}</label>)}<p>{t.trialNotice}</p></fieldset>
   <button style={{minHeight:48}} disabled={disabled} type="submit">{busy?t.saving:t.save}</button>
  </form>
  <section aria-labelledby={`${id}-agreement`}><h3 id={`${id}-agreement`}>{t.agreement}</h3>{agreement?<><article tabIndex={0} aria-label={`${t.agreement} ${agreement.version}`}><p>{agreement.content}</p><dl><dt>{t.version}</dt><dd>{agreement.version}</dd><dt>{t.digest}</dt><dd><code>{agreement.canonicalDigest}</code></dd><dt>{t.commission}</dt><dd>{agreement.commissionBps==null?t.unavailableRate:`${agreement.commissionBps} bps`}</dd></dl>{agreement.legalReviewRequired&&<p role="note">{t.legalReview}</p>}</article><details><summary>{t.canonicalFallback}</summary><p lang="en">{agreement.canonicalContent}</p></details>{view?.agreementAcceptance?<p role="status">{t.accepted} · {view.agreementAcceptance.receiptId}</p>:<><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>{t.explicitAccept}</label><button style={{minHeight:48}} disabled={busy||!accepted||disabled} onClick={()=>void run("accept",()=>enterpriseCourseOnboardingService.acceptAgreement(draft.context,agreement,command("accept"),draft.trialOfferId,draft.requestedTrialDays))}>{t.accept}</button></>}</>:<p role="status">{t.agreementUnavailable}</p>}</section>
  <div><button style={{minHeight:48}} disabled={disabled||!view?.agreementAcceptance||!allDisclosed} onClick={()=>void run("submit",()=>enterpriseCourseOnboardingService.submit(draft.context,view?.version??0,command("submit")))}>{t.submit}</button><button style={{minHeight:48}} disabled={busy||["withdrawn","active_partner"].includes(status)} onClick={()=>void run("withdraw",()=>enterpriseCourseOnboardingService.withdraw(draft.context,view?.version??0,command("withdraw")))}>{t.withdraw}</button></div>
  {view?.review&&<section><h3>{t.adminReview}</h3><p>{view.review.referenceId}</p><ul>{view.review.requirements.map(x=><li key={x}>{x}</li>)}</ul><p>{t.adminHandoff}</p></section>}
  {view?.trial&&<section><h3>{t.trial}</h3><p>{view.trial.status} · {view.trial.durationDays} {t.days}</p><p>{view.trial.startsAt??t.activationPending} — {view.trial.endsAt??t.activationPending}</p></section>}
  {view?.auditReceipts?.length?<section><h3>{t.receipts}</h3><ol>{view.auditReceipts.map(x=><li key={x.receiptId}>{x.kind} · {x.receiptId}</li>)}</ol></section>:null}
  {notice&&<p role={notice===t.saved?"status":"alert"} aria-live="assertive">{notice}</p>}
 </section>;
}
