// Read-only Director projection of canonical V2 Economy collections. This
// module receives documents already read by the callable and has no write path.
export type EconomyDocument = { id: string; data: Record<string, unknown> };

const number = (value: unknown): number | null => Number.isFinite(value) ? Number(value) : null;
const text = (value: unknown): string | null => typeof value === 'string' && value.trim() ? value : null;
const sum = (values: Array<number | null>): number => values.reduce<number>((total, value) => total + (value ?? 0), 0);
const balance = (data: Record<string, unknown>) => data.balance && typeof data.balance === 'object' ? data.balance as Record<string, unknown> : {};

const policyRecord = ({ id, data }: EconomyDocument) => ({ id, policyVersion: text(data.policyVersion) ?? 'unrecorded', state: text(data.state) ?? 'unrecorded', purpose: text(data.purpose) ?? 'unrecorded', amountTee: Number.isInteger(data.amountTee) ? Number(data.amountTee) : null, greenFeeIncluded: typeof data.greenFeeIncluded === 'boolean' ? data.greenFeeIncluded : null, effectiveAt: text(data.effectiveAt) ?? text(data.effectiveFrom), effectiveTo: text(data.effectiveTo), digest: text(data.policyDigestSha256) ?? text(data.checksum), createdAt: text(data.createdAt), activatedAt: text(data.activatedAt) });

export function buildV2EconomyMasterSnapshot(input: { policies: EconomyDocument[]; lots: EconomyDocument[]; journals: EconomyDocument[]; reconciliationCases: EconomyDocument[]; policyAudit: EconomyDocument[] }) {
  const policyHistory = input.policies.filter(({ data }) => data.schema === 'golfriend.economy-policy-version.v1' || data.schema === 'golfriend.economy-policy-version.v2').map(policyRecord).sort((left, right) => String(right.effectiveAt ?? right.createdAt ?? '').localeCompare(String(left.effectiveAt ?? left.createdAt ?? '')));
  const activePolicies = policyHistory.filter((policy) => policy.state === 'active');
  const lotRows = input.lots.filter(({ data }) => data.schema === 'golfriend.tee-lot.v1' || data.lotType === 'tee_lot_v1').map(({ id, data }) => ({ id, lotId: text(data.lotId) ?? id, liabilityClass: text(data.liabilityClass) ?? 'unrecorded', issuedQuantity: number(data.issuedQuantity), remainingQuantity: number(data.remainingQuantity), reservedQuantity: number(data.reservedQuantity), settledQuantity: number(data.settledQuantity), releasedQuantity: number(data.releasedQuantity), expiredQuantity: number(data.expiredQuantity), issuedAt: text(data.issuedAt), expiresAt: text(data.expiresAt) })).sort((left, right) => String(right.issuedAt ?? '').localeCompare(String(left.issuedAt ?? '')));
  const lotTotals = { issued: sum(lotRows.map((lot) => lot.issuedQuantity)), remaining: sum(lotRows.map((lot) => lot.remainingQuantity)), reserved: sum(lotRows.map((lot) => lot.reservedQuantity)), settled: sum(lotRows.map((lot) => lot.settledQuantity)), released: sum(lotRows.map((lot) => lot.releasedQuantity)), expired: sum(lotRows.map((lot) => lot.expiredQuantity)) };
  const recentEntries = input.journals.filter(({ data }) => data.entryType === 'journal_entry_v1').map(({ id, data }) => ({ entryId: text(data.entryId) ?? id, commandType: text(data.commandType) ?? 'unrecorded', createdAt: text(data.createdAt), policyVersion: text(data.policyVersion) ?? 'not recorded by canonical journal', debitTee: number(balance(data).debitTotalTee), creditTee: number(balance(data).creditTotalTee), balanced: balance(data).isBalanced === true })).sort((left, right) => String(right.createdAt ?? '').localeCompare(String(left.createdAt ?? ''))).slice(0, 25);
  const countryRows = new Map<string, { countryCode: string; journalCount: number; teeVolume: number }>();
  for (const { data } of input.journals) { const countryCode = text(data.countryCode); if (!countryCode) continue; const row = countryRows.get(countryCode) ?? { countryCode, journalCount: 0, teeVolume: 0 }; row.journalCount += 1; row.teeVolume += number(balance(data).debitTotalTee) ?? 0; countryRows.set(countryCode, row); }
  const auditEntries = input.policyAudit.map(({ id, data }) => ({ id, policyVersion: text(data.policyVersion) ?? 'unrecorded', actionType: text(data.actionType) ?? 'unrecorded', reason: text(data.reason), createdAt: text(data.createdAt), diffHash: text(data.diffHash) }));
  return { schema: 'golfriend.admin.v2-economy-master.v2', readOnly: true, policies: activePolicies, policyHistory, teeLots: { status: lotRows.length ? 'available' : 'empty', totals: lotTotals, rows: lotRows }, teeInventory: { issued: lotTotals.issued, remaining: lotTotals.remaining, reserved: lotTotals.reserved, available: lotTotals.remaining - lotTotals.reserved, byAction: [] }, ledger: { entriesReviewed: recentEntries.length, debitTotalTee: sum(recentEntries.map((entry) => entry.debitTee)), creditTotalTee: sum(recentEntries.map((entry) => entry.creditTee)), balancedEntries: recentEntries.filter((entry) => entry.balanced).length, unbalancedEntries: recentEntries.filter((entry) => !entry.balanced).length, pendingReconciliationCases: input.reconciliationCases.filter(({ data }) => data.state === 'pending').length, recentEntries }, countryUsage: countryRows.size ? { status: 'available', rows: [...countryRows.values()].sort((left, right) => right.teeVolume - left.teeVolume) } : { status: 'unavailable', rows: [], reason: 'Canonical V2 journals do not currently record a countryCode.' }, policyAudit: auditEntries.length ? { status: 'available', entries: auditEntries } : { status: 'unavailable', entries: [], reason: 'No canonical V2 policy-change audit records are available.' } } as const;
}
