'use strict';
const fs = require('node:fs');
const source = fs.readFileSync(require.resolve('./index.js'), 'utf8');
const exportsFound = [...new Set([...source.matchAll(/exports\.([A-Za-z0-9_]+)\s*=/g)].map((match) => match[1]))];
const prohibited = ['acquireCourseCandidates', 'syncCoursesFromProvider', 'nightlyCourseHealer', 'queryGolfApi', 'fetch(', 'defineSecret', '.set(', '.update(', '.create(', '.delete('];
if (exportsFound.length !== 4 || !exportsFound.includes('getCourseCoverageByCountry') || !exportsFound.includes('planCourseCountryIngestion') || !exportsFound.includes('getCourseCountryIngestionProjection') || !exportsFound.includes('getCourseOperationsProjection')) throw Error(`EXPORT_SELECTION_INVALID:${exportsFound.join(',')}`);
for (const name of prohibited) if (source.includes(name)) throw Error(`PROHIBITED_FUNCTION_PRESENT:${name}`);
if (!source.includes("enforceAppCheck: true") || !source.includes("collection('admin_users')") || !source.includes("collection('courses')")) throw Error('AUTHORITATIVE_READ_BOUNDARY_MISSING');
if (!source.includes('projectCoverageByCountry') || !source.includes('course_country_ingestion_receipts') || !source.includes("collection('clubhouses')")) throw Error('COVERAGE_PROJECTION_MISSING');
if (!source.includes("collection('course_acquisition_requests')") || !source.includes("collection('course_acquisition_receipts')") || source.includes("collection('golf_api_quota').orderBy")) throw Error('MEMBER_REQUEST_PROJECTION_BOUNDARY_MISSING');
console.log('course-read selection proof PASS: staff-gated aggregate and Firebase-only plan/projection, zero provider capability and zero course writes');
