'use strict';
const fs = require('node:fs');
const source = fs.readFileSync(require.resolve('./index.js'), 'utf8');
const exportsFound = [...source.matchAll(/exports\.([A-Za-z0-9_]+)\s*=/g)].map((match) => match[1]);
const prohibited = ['acquireCourseCandidates', 'syncCoursesFromProvider', 'nightlyCourseHealer', 'queryGolfApi'];
if (exportsFound.length !== 1 || exportsFound[0] !== 'getCourseAcquisitionDashboard') throw Error(`EXPORT_SELECTION_INVALID:${exportsFound.join(',')}`);
for (const name of prohibited) if (source.includes(name)) throw Error(`PROHIBITED_FUNCTION_PRESENT:${name}`);
if (/defineSecret|golfapi|https?:\/\/|\.collection\(|\.get\(/i.test(source)) throw Error('DATA_OR_PROVIDER_CAPABILITY_PRESENT');
if (!source.includes('FULL_COLLECTION_DASHBOARD_RETIRED_USE_CATALOGUE_STATUS')) throw Error('DASHBOARD_NOT_FAIL_CLOSED');
console.log('course-read selection proof PASS: one fail-closed compatibility export, zero data or provider capability');
