import * as admin from "firebase-admin";
import { HttpsError, onCall } from "firebase-functions/v2/https";
import { isActiveStaff } from "./authority.js";
import { adminPermission, messageRequest, recordId, resolutionRequest, transition } from "./domain.js";

export const BOOKING_COMMUNICATIONS_REGION = "asia-southeast1";
export const BOOKING_COMMUNICATIONS_OPTIONS = Object.freeze({ region: BOOKING_COMMUNICATIONS_REGION, enforceAppCheck: true });
if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore(), now = () => admin.firestore.FieldValue.serverTimestamp();
const deniedFields = ["price", "amount", "fee", "payment", "wallet", "ledger", "settlement", "refund", "payout", "escrow"];
const assertNonFinancial = (input: any) => { if (Object.keys(input || {}).some((key) => deniedFields.some((field) => key.toLowerCase().includes(field)))) throw new HttpsError("invalid-argument", "Financial fields prohibited."); };
const only = (input: any, keys: string[]) => Object.keys(input || {}).every((key) => keys.includes(key));
const clean = (value: unknown, max: number) => typeof value === "string" ? value.replace(/[\u0000-\u001f\u007f]/g, "").trim().slice(0, max) : "";
const iso = (value: any) => { const date = value?.toDate?.() || value; return date instanceof Date && Number.isFinite(date.getTime()) ? date.toISOString() : null; };
async function staff(request: any, action: "read" | "message" | "resolve") { if (!request.auth?.uid) throw new HttpsError("unauthenticated", "Sign in required."); const document = await db.collection("admin_users").doc(request.auth.uid).get(), role = document.data()?.role; if (!document.exists || !isActiveStaff(document.data()) || !adminPermission(role, action)) throw new HttpsError("permission-denied", action === "resolve" ? "Director authorization required." : "Active staff authorization required."); return { uid: request.auth.uid as string, role: String(role) }; }
function booking(document: FirebaseFirestore.DocumentSnapshot | FirebaseFirestore.QueryDocumentSnapshot) { const value = document.data() || {}, status = clean(value.status, 32); if (!/^[A-Za-z0-9_-]{3,200}$/.test(document.id) || !["pending", "confirmed", "rejected", "cancelled"].includes(status)) return null; return { id: document.id, slotId: clean(value.slotId, 200), courseId: clean(value.courseId, 160), courseName: clean(value.courseName, 160) || clean(value.courseId, 160) || "Unknown course", date: clean(value.date, 10), time: clean(value.time, 8), playerUid: clean(value.playerUid || value.memberUid, 160), playerName: clean(value.playerName || value.memberDisplayName, 120) || "Golfriend member", status, createdAt: iso(value.createdAt), updatedAt: iso(value.updatedAt), lastMessageAt: iso(value.lastMessageAt) }; }
async function detail(bookingId: string) { const document = await db.collection("bookings").doc(bookingId).get(), projection = document.exists ? booking(document) : null; if (!projection) throw new HttpsError("not-found", "Booking unavailable."); const [audits, messages] = await Promise.all([db.collection("admin_booking_communication_audits").where("bookingId", "==", bookingId).limit(100).get(), document.ref.collection("messages").orderBy("createdAt", "asc").limit(100).get()]); return { booking: projection, audits: audits.docs.map((item) => ({ id: item.id, action: clean(item.data().kind, 80), byRole: clean(item.data().actorRole, 80), at: iso(item.data().createdAt), immutable: item.data().immutable === true })), messages: messages.docs.map((item) => ({ id: item.id, senderRole: clean(item.data().senderRole, 80), text: clean(item.data().message, 2000), locale: clean(item.data().locale, 8), createdAt: iso(item.data().createdAt), deliveryStatus: "unavailable" })) }; }
export const getAdminBookingStreamV2 = onCall(BOOKING_COMMUNICATIONS_OPTIONS, async (request) => { await staff(request, "read"); if (!only(request.data, ["bookingId"])) throw new HttpsError("invalid-argument", "Booking stream fields invalid."); const bookingId = clean(request.data?.bookingId, 200); if (bookingId) { const value = await detail(bookingId); return { schema: "golfriend.admin.booking-communications-stream.v2", source: "server", availability: "confirmed", bookings: [value.booking], audits: value.audits, messages: value.messages, providerDelivery: "unavailable", financialSettlement: "unavailable" }; } const documents = await db.collection("bookings").limit(500).get(); return { schema: "golfriend.admin.booking-communications-stream.v2", source: "server", availability: "confirmed", bookings: documents.docs.map(booking).filter((value): value is NonNullable<typeof value> => value !== null), audits: [], messages: [], providerDelivery: "unavailable", financialSettlement: "unavailable" }; });
export const adminResolveBooking = onCall(BOOKING_COMMUNICATIONS_OPTIONS, async (request) => { const actor = await staff(request, "resolve"); if (!only(request.data, ["bookingId", "resolution", "idempotencyKey"])) throw new HttpsError("invalid-argument", "Booking resolution fields invalid."); assertNonFinancial(request.data); let input: ReturnType<typeof resolutionRequest>; try { input = resolutionRequest(request.data); } catch (error) { throw new HttpsError("invalid-argument", error instanceof Error ? error.message : "Resolution invalid."); } const operationId = recordId("resolve", input.bookingId, input.idempotencyKey); return db.runTransaction(async (tx) => { const operationRef = db.collection("admin_booking_communication_operations").doc(operationId), bookingRef = db.collection("bookings").doc(input.bookingId), [operation, current] = await Promise.all([tx.get(operationRef), tx.get(bookingRef)]); if (operation.exists) { const prior = operation.data(); if (prior?.bookingId !== input.bookingId || prior?.resolution !== input.resolution || prior?.actorUid !== actor.uid) throw new HttpsError("already-exists", "Idempotency key reuse conflict."); return { accepted: true, bookingId: input.bookingId, status: prior?.status, auditEventId: prior?.auditEventId, idempotent: true, providerDelivery: "unavailable" }; } if (!current.exists) throw new HttpsError("not-found", "Booking not found."); let next: ReturnType<typeof transition>; try { next = transition(current.data()?.status, input.resolution); } catch { throw new HttpsError("failed-precondition", "Booking transition denied."); } if (next.releaseSeat) { const slotRef = db.collection("tee_time_slots").doc(String(current.data()?.slotId || "")), slot = await tx.get(slotRef); if (slot.exists) tx.update(slotRef, { bookedCount: Math.max(0, Number(slot.data()?.bookedCount || 0) - 1), updatedAt: now() }); } const auditEventId = recordId(`audit_${input.resolution}`, input.bookingId, input.idempotencyKey); tx.update(bookingRef, { status: next.status, userStatusKey: `booking_${next.status}`, resolvedByUid: actor.uid, resolvedByRole: actor.role, resolvedAt: now(), updatedAt: now() }); tx.create(db.collection("admin_booking_communication_audits").doc(auditEventId), { schema: "golfriend.admin.booking-communication-audit.v2", auditEventId, bookingId: input.bookingId, kind: `admin_${next.status}`, actorUid: actor.uid, actorRole: actor.role, immutable: true, financialFields: false, providerDelivery: "unavailable", createdAt: now() }); tx.create(operationRef, { schema: "golfriend.admin.booking-communication-operation.v2", kind: "resolve", bookingId: input.bookingId, resolution: input.resolution, actorUid: actor.uid, actorRole: actor.role, status: next.status, auditEventId, immutable: true, createdAt: now() }); return { accepted: true, bookingId: input.bookingId, status: next.status, auditEventId, idempotent: false, providerDelivery: "unavailable" }; }); });
export const sendBookingMessage = onCall(BOOKING_COMMUNICATIONS_OPTIONS, async (request) => { const actor = await staff(request, "message"); if (!only(request.data, ["bookingId", "locale", "message", "idempotencyKey"])) throw new HttpsError("invalid-argument", "Booking message fields invalid."); assertNonFinancial(request.data); let input: ReturnType<typeof messageRequest>; try { input = messageRequest(request.data); } catch (error) { throw new HttpsError("invalid-argument", error instanceof Error ? error.message : "Message invalid."); } const operationId = recordId("message", input.bookingId, input.idempotencyKey), messageId = recordId("message_record", input.bookingId, input.idempotencyKey), auditEventId = recordId("message_audit", input.bookingId, input.idempotencyKey); return db.runTransaction(async (tx) => { const bookingRef = db.collection("bookings").doc(input.bookingId), operationRef = db.collection("admin_booking_communication_operations").doc(operationId), [current, operation] = await Promise.all([tx.get(bookingRef), tx.get(operationRef)]); if (operation.exists) { const prior = operation.data(); if (prior?.bookingId !== input.bookingId || prior?.actorUid !== actor.uid || prior?.messageId !== messageId) throw new HttpsError("already-exists", "Idempotency key reuse conflict."); return { accepted: true, bookingId: input.bookingId, messageId, auditEventId: prior?.auditEventId, idempotent: true, deliveryStatus: "unavailable" }; } if (!current.exists) throw new HttpsError("not-found", "Booking not found."); if (!["pending", "confirmed"].includes(String(current.data()?.status))) throw new HttpsError("failed-precondition", "Messaging unavailable for this booking status."); tx.create(bookingRef.collection("messages").doc(messageId), { messageId, senderRole: "staff", actorUid: actor.uid, actorRole: actor.role, locale: input.locale, message: input.message, createdAt: now(), providerDelivery: "unavailable", financialFields: false }); tx.update(bookingRef, { lastMessageAt: now(), updatedAt: now() }); tx.create(db.collection("admin_booking_communication_audits").doc(auditEventId), { schema: "golfriend.admin.booking-communication-audit.v2", auditEventId, bookingId: input.bookingId, kind: "admin_message_created", actorUid: actor.uid, actorRole: actor.role, messageId, locale: input.locale, immutable: true, financialFields: false, providerDelivery: "unavailable", createdAt: now() }); tx.create(operationRef, { schema: "golfriend.admin.booking-communication-operation.v2", kind: "message", bookingId: input.bookingId, actorUid: actor.uid, actorRole: actor.role, messageId, auditEventId, immutable: true, createdAt: now() }); return { accepted: true, bookingId: input.bookingId, messageId, auditEventId, idempotent: false, deliveryStatus: "unavailable" }; }); });
