'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),d=require('./domain'),c=require('./calibration');

const digest='a'.repeat(64),baseCounts={courses:3348,retries:38129,quarantine:1};
function harness(mode,overrides={}){const state={providerCalls:0,claims:0,relocks:0,receipts:[],proposals:[],writes:{courses:0,retries:0,quarantine:0},path:null};const prior=Object.hasOwn(overrides,'prior')?overrides.prior:{evidenceId:mode==='detail_only'?'e-list_only':'e-prior',providerRemaining:mode==='detail_only'?99.9:100,observedAt:'2026-08-19T03:14:00.000Z',responseDigest:digest,immutable:true};const after=mode==='detail_only'?98.9:99.9;const options={mode,runId:`calibration-${mode}`,projectId:'golfriend-v2',bindingReceiptId:'rotation-2',now:()=> '2026-08-19T03:15:00.000Z',nowMs:()=>Date.parse('2026-08-19T03:15:00.000Z'),loadPriorEvidence:async()=>prior,selectDetailTarget:async()=>({documentId:'course-1',providerCourseId:'course-1',providerClubId:'club-1',schema:'golfriend.v2.course.v2',needsReview:false}),claim:async()=>{state.claims++;},countRecords:async()=>({...baseCounts}),executeProvider:async input=>{state.providerCalls++;state.path=input.path;if(overrides.executeError)throw overrides.executeError;return{body:mode==='list_only'?{clubs:[],apiRequestsLeft:after,numAllClubs:0}:{courses:[{courseID:'course-1'}],apiRequestsLeft:after},providerRemaining:after,responseDigest:mode==='list_only'?'b'.repeat(64):'c'.repeat(64),reservationId:`reservation-${mode}`,providerEvidenceId:`e-${mode}`,retrievedAt:'2026-08-19T03:15:01.000Z',settlementState:'completed',measuredCost:input.measureCost({providerRemaining:after})};},validateResponse:overrides.validateResponse??(({mode:kind,body,target,pageSize})=>kind==='list_only'?{valid:Array.isArray(body.clubs)&&pageSize===200,requestedPageSize:pageSize,clubCount:body.clubs.length}:{valid:Array.isArray(body.courses)&&body.courses.some(item=>item.courseID===target.providerCourseId),providerCourseId:target.providerCourseId}),writeReceipt:async value=>{state.receipts.push(value);},loadMeasurements:async receipt=>overrides.measurements?.(receipt)??(mode==='list_only'?{listOnly:receipt,detailOnly:null}:{listOnly:null,detailOnly:receipt}),writeProposal:async value=>{state.proposals.push(value);},relock:async()=>{state.relocks++;},refreshSlo:d.REFRESH_SLO};return{state,options};}

test('list_only makes exactly one pageSize 200 request and measures only list cost',async()=>{const h=harness('list_only'),result=await c.runCalibration(h.options);assert.equal(h.state.providerCalls,1);assert.equal(h.state.path,'/api/v2.3/clubs?pageSize=200');assert.equal(result.receipt.measuredCost,.1);assert.equal(result.receipt.detailsPerRun,undefined);assert.equal(result.receipt.endpoint.details,0);assert.equal(result.receipt.requestCount,1);assert.equal(result.proposal,null);assert.equal(h.state.relocks,1);assert.equal(c.receiptMatches(result.receipt),true);});
test('detail_only makes one server-selected detail request and measures only detail cost',async()=>{const h=harness('detail_only'),result=await c.runCalibration(h.options);assert.equal(h.state.providerCalls,1);assert.equal(h.state.path,'/api/v2.3/clubs/club-1');assert.equal(result.receipt.measuredCost,1);assert.equal(result.receipt.endpoint.target.providerCourseId,'course-1');assert.equal(result.receipt.requestCount,1);assert.equal(h.state.relocks,1);});
test('both modes prove zero catalogue retry and quarantine writes',async()=>{for(const selected of ['list_only','detail_only']){const h=harness(selected),result=await c.runCalibration(h.options);assert.deepEqual(result.receipt.recordCountsBefore,baseCounts);assert.deepEqual(result.receipt.recordCountsAfter,baseCounts);assert.equal(result.receipt.zeroCatalogueWrites,true);assert.deepEqual(h.state.writes,{courses:0,retries:0,quarantine:0});}});
test('missing or stale immutable prior evidence blocks before provider and still relocks',async()=>{for(const prior of [null,{evidenceId:'old',providerRemaining:100,observedAt:'2026-08-19T02:00:00.000Z',responseDigest:digest,immutable:true}]){const h=harness('list_only',{prior});await assert.rejects(c.runCalibration(h.options),/CALIBRATION_PRIOR_EVIDENCE_MISSING_OR_STALE/);assert.equal(h.state.providerCalls,0);assert.equal(h.state.claims,0);assert.equal(h.state.relocks,1);}});
test('response validation failure preserves settled observation as recoverable and never retries',async()=>{const h=harness('list_only',{validateResponse:()=>({valid:false,reason:'UNEXPECTED_PAGE_SHAPE'})});await assert.rejects(c.runCalibration(h.options),/UNEXPECTED_PAGE_SHAPE/);assert.equal(h.state.providerCalls,1);assert.equal(h.state.receipts.length,1);assert.equal(h.state.receipts[0].recoverable,true);assert.equal(h.state.receipts[0].settlementState,'completed');assert.equal(h.state.receipts[0].afterObservation.responseDigest,'b'.repeat(64));assert.equal(h.state.relocks,1);});
test('post-response settlement failure preserves pending evidence as recoverable and never retries',async()=>{const error=Error('COMPLETED_SETTLEMENT_PENDING');error.classification='COMPLETED_SETTLEMENT_PENDING';error.observation={reservationId:'reservation-pending',providerEvidenceId:'golf_api_pending_settlements/reservation-pending',providerRemaining:99.9,responseDigest:'d'.repeat(64),observedAt:'2026-08-19T03:15:01.000Z',settlementState:'pending_reconciliation'};const h=harness('list_only',{executeError:error});await assert.rejects(c.runCalibration(h.options),/COMPLETED_SETTLEMENT_PENDING/);assert.equal(h.state.providerCalls,1);assert.equal(h.state.receipts[0].recoverable,true);assert.equal(h.state.receipts[0].settlementState,'pending_reconciliation');assert.equal(h.state.receipts[0].reservationId,'reservation-pending');assert.equal(h.state.relocks,1);});
test('proposal fails closed until separate successive list and detail measurements exist',async()=>{const listHarness=harness('list_only'),list=(await c.runCalibration(listHarness.options)).receipt;assert.throws(()=>c.buildCalibrationProposal(list,null),/DETAIL_ONLY_MEASUREMENT_MISSING/);const detailHarness=harness('detail_only'),detail=(await c.runCalibration(detailHarness.options)).receipt,proposal=c.buildCalibrationProposal(list,detail);assert.deepEqual(proposal.measuredWeights,{list:.1,detail:1});assert.equal(proposal.refreshSlo.maxDailyWeight,2.8);assert.equal(proposal.refreshSlo.maxMonthlyWeight,86.8);assert.equal(proposal.validated,true);});
test('calibration is callable-only and cannot enable a schedule',()=>{const source=fs.readFileSync(path.join(__dirname,'index.js'),'utf8'),start=source.indexOf('exports.runGolfApiCalibrationCanary'),calibrationSource=source.slice(start,source.indexOf('exports.scheduledGolfApiCatalogueIncremental',start));assert.match(calibrationSource,/onCall/);assert.doesNotMatch(calibrationSource,/onSchedule/);assert.doesNotMatch(calibrationSource,/schedule\s*:/);assert.doesNotMatch(calibrationSource,/providerRequestsAllowed:true/);});
