'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {mergeCanonicalCourse}=require('./canonicalCourseMerge');

function fakeDb(){const data=new Map(),ref=path=>({path});return{data,collection:name=>({doc:id=>ref(`${name}/${id}`)}),runTransaction:async work=>work({get:async item=>({exists:data.has(item.path),data:()=>data.get(item.path)}),set:(item,value,options={})=>data.set(item.path,options.merge?{...(data.get(item.path)||{}),...value}:value)})};}
const mergeCurated=(_existing,incoming)=>incoming;
const record=(courseId,clubId)=>({courseID:courseId,providerCourseId:courseId,providerClubId:clubId,clubName:'Shared venue',country:'THAILAND',coordinateValidity:'valid',latitude:13.7563,longitude:100.5018,provider:'golf-api',provenance:'golf-api',importRunId:'run-1',source:{provider:'golf-api',jobId:'run-1',sourceCourseId:courseId,sourceClubId:clubId},sourceUpdatedAt:1});
const write=(db,item)=>mergeCanonicalCourse({db,record:item,sourceContext:{provenance:'golf-api',sourceId:item.providerCourseId,runId:'run-1',sameRecord:(existing,incoming)=>existing.providerCourseId===incoming.providerCourseId&&existing.providerClubId===incoming.providerClubId&&existing.sourceUpdatedAt===incoming.sourceUpdatedAt},mergeCurated,stamp:()=> '2026-08-31T00:00:00.000Z'});

test('one clubhouse retains multiple playable layouts',async()=>{const db=fakeDb();await write(db,record('layout-a','club-a'));await write(db,record('layout-b','club-a'));assert.equal(db.data.get('clubhouses/club-a').courseLayoutCount,2);assert.equal(db.data.get('courses/layout-a').clubhouseId,'club-a');assert.equal(db.data.get('courses/layout-b').clubhouseId,'club-a');});
test('provider club identities never merge from matching venue names',async()=>{const db=fakeDb();await write(db,record('layout-a','club-a'));await write(db,record('layout-b','club-b'));assert.equal(db.data.get('clubhouses/club-a').courseLayoutCount,1);assert.equal(db.data.get('clubhouses/club-b').courseLayoutCount,1);});
test('an idempotent replay cannot increment the derived clubhouse count',async()=>{const db=fakeDb(),item=record('layout-a','club-a');await write(db,item);const result=await write(db,item);assert.equal(result.state,'unchanged');assert.equal(db.data.get('clubhouses/club-a').courseLayoutCount,1);});
test('a missing provider club ID remains review-only and creates no clubhouse',async()=>{const db=fakeDb(),item=record('layout-a',null);item.source.sourceClubId=null;await write(db,item);assert.equal(db.data.get('courses/layout-a').needsClubhouseIdentityReview,true);assert.equal(db.data.has('clubhouses/null'),false);});
test('canonical merge derives and stores the IANA timezone from its final coordinates',async()=>{const db=fakeDb();await write(db,record('layout-a','club-a'));const course=db.data.get('courses/layout-a');assert.equal(course.courseTimeZone,'Asia/Bangkok');assert.equal(course.courseTimeZoneResolver,'geo-tz@8.1.8/all');assert.equal(course.courseTimeZoneSource,'coordinates');assert.equal(course.courseTimeZoneResolvedAt,'2026-08-31T00:00:00.000Z');});
