'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),s=require('./countrySchedule');
const now=Date.parse('2026-08-27T00:00:00Z'),coverage={country:'TH',totalCourses:20,coursesMissingCoordinates:8,providerEvidenceMissingCount:4,latestGolfriendFetchTime:'2026-06-01T00:00:00Z'},quota={allowed:true,providerReportedRemaining:100};
test('completed country receives a durable priority and next due time',()=>{const value=s.nextCycle({cycle:2},coverage,quota,now);assert.equal(value.state,'completed');assert.equal(value.cycle,2);assert(value.priorityScore>0);assert(value.nextDueAtMs>now);assert.match(value.nextDueAt,/Z$/);});
test('completed jobs requeue only when due and quota remains authoritative',()=>{const job={state:'completed',country:'TH',nextDueAtMs:now-1};assert.equal(s.eligibility(job,quota,now).eligible,true);assert.equal(s.eligibility(job,{allowed:false,providerReportedRemaining:0},now).eligible,false);});
test('admin pause and permanent failure never auto-requeue',()=>{assert.equal(s.eligibility({state:'paused',country:'TH',pauseReason:'ADMIN_PAUSED',retryAtMs:now-1},quota,now).eligible,false);assert.equal(s.eligibility({state:'failed',country:'TH',nextDueAtMs:now-1},quota,now).eligible,false);});
test('429 uses its exact retry time and only resumes when due',()=>{const job={state:'paused',country:'TH',pauseReason:'PROVIDER_429',retryAtMs:now+45000};assert.equal(s.eligibility(job,quota,now).eligible,false);assert.equal(s.eligibility(job,quota,now+45000).eligible,true);});
test('cycle receipt identity is immutable across cycles',()=>{assert.equal(s.receiptId({jobId:'country-th',cycle:1}),'country-th-cycle-1');assert.equal(s.receiptId({jobId:'country-th',cycle:2}),'country-th-cycle-2');});
test('higher-priority stale coverage is scheduled ahead of fresher low-priority coverage',()=>{const urgent=s.nextDue({...coverage,coursesMissingCoordinates:20,latestGolfriendFetchTime:'2025-01-01T00:00:00Z'},quota,now),fresh=s.nextDue({...coverage,coursesMissingCoordinates:0,providerEvidenceMissingCount:0,latestGolfriendFetchTime:'2026-08-26T00:00:00Z'},quota,now);assert(urgent.priorityScore>fresh.priorityScore);assert(urgent.nextDueAtMs<fresh.nextDueAtMs);});
