'use strict';
const crypto=require('node:crypto');
const IMPORT_VERSION='golfriend.golf-api-catalogue.v3',MAX_RPS=5,PAGE_SIZE=200,MONTHLY_BUDGET=500,EMERGENCY_RESERVE=100;
const REFRESH_SLO=Object.freeze({schedule:'every day 02:20',pagesPerRun:8,detailsPerRun:2,refreshAfterDays:30,maxDailyWeight:3,maxMonthlyWeight:90});
const canonicalize=value=>Array.isArray(value)?value.map(canonicalize):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonicalize(value[key])])):value;
const canonicalJson=value=>JSON.stringify(canonicalize(value));
const digest=value=>crypto.createHash('sha256').update(typeof value==='string'?value:canonicalJson(value)).digest('hex');
const activationReceiptDigest=payload=>digest(payload);
const activationReceiptMatches=(payload,expectedDigest)=>typeof expectedDigest==='string'&&activationReceiptDigest(payload)===expectedDigest;
const canaryReceiptPayload=receipt=>({schema:receipt.schema,projectId:receipt.projectId,runId:receipt.runId,bindingReceiptId:receipt.bindingReceiptId,requestedPath:receipt.requestedPath,detailsPerRun:receipt.detailsPerRun,providerRequestCount:receipt.providerRequestCount,weightedAmount:receipt.weightedAmount,responseValidation:receipt.responseValidation,providerRemaining:receipt.providerRemaining,responseDigest:receipt.responseDigest,providerEvidenceId:receipt.providerEvidenceId,quotaBefore:receipt.quotaBefore,quotaAfter:receipt.quotaAfter,recordCountsBefore:receipt.recordCountsBefore,recordCountsAfter:receipt.recordCountsAfter,zeroCourseWrites:receipt.zeroCourseWrites,startedAt:receipt.startedAt,completedAt:receipt.completedAt,failure:receipt.failure});
const canaryReceiptMatches=receipt=>typeof receipt?.digest==='string'&&digest(canaryReceiptPayload(receipt))===receipt.digest;
function assessCanaryAccountingEvidence(receipt){const reasons=[],remaining=receipt?.providerRemaining,hasRemaining=remaining!==null&&remaining!==undefined&&remaining!==''&&Number.isFinite(Number(remaining));if(!canaryReceiptMatches(receipt))reasons.push('CANARY_RECEIPT_DIGEST_INVALID');if(receipt?.providerRequestCount!==1||receipt?.weightedAmount!==.1)reasons.push('REQUEST_WEIGHT_NOT_PROVEN');if(receipt?.responseValidation?.valid!==true)reasons.push('RESPONSE_VALIDATION_NOT_CONFIRMED');if(!/^[a-f0-9]{64}$/.test(String(receipt?.responseDigest||'')))reasons.push('RESPONSE_DIGEST_MISSING');if(!hasRemaining)reasons.push('PROVIDER_REMAINING_MISSING');if(!receipt?.providerEvidenceId)reasons.push('PROVIDER_EVIDENCE_ID_MISSING');if(receipt?.failure)reasons.push('CANARY_FAILURE_RECORDED');return{eligible:reasons.length===0,reasons,weight:receipt?.weightedAmount===.1?.1:null,providerRemaining:hasRemaining?Number(remaining):null};}
function normalizeRevisionIdentity(value,expectedService){if(typeof value!=='string'||typeof expectedService!=='string'||!/^[a-z][a-z0-9-]{0,62}$/.test(expectedService))return null;let revision=value;if(value.includes('/')){const match=/^projects\/[^/]+\/locations\/[^/]+\/services\/([^/]+)\/revisions\/([^/]+)$/.exec(value);if(!match||match[1]!==expectedService)return null;revision=match[2];}return /^[a-z][a-z0-9-]{0,61}[a-z0-9]$/.test(revision)?revision:null;}
function activationRevisionBindingsMatch(bindings,expectedServices,currentService,currentRevision){if(!bindings||typeof bindings!=='object'||Array.isArray(bindings)||!Array.isArray(expectedServices)||!expectedServices.includes(currentService))return false;const expected=[...expectedServices].sort(),actual=Object.keys(bindings).sort();if(new Set(expected).size!==expected.length||JSON.stringify(actual)!==JSON.stringify(expected))return false;const normalized={};for(const service of expected){const revision=normalizeRevisionIdentity(bindings[service],service);if(!revision)return false;normalized[service]=revision;}const live=normalizeRevisionIdentity(currentRevision,currentService);return live!==null&&normalized[currentService]===live;}
const text=value=>String(value??'').trim().normalize('NFC')||null;
const identifier=value=>{const result=text(value);return result&&result.length<=160&&/^[A-Za-z0-9_-]+$/.test(result)?result:null;};
const number=value=>{const result=Number(value);return Number.isFinite(result)?result:null;};
const epochMilliseconds=value=>{if(typeof value==='number'&&Number.isFinite(value))return Math.abs(value)<100000000000?Math.trunc(value*1000):Math.trunc(value);const raw=text(value);if(!raw)return null;const numeric=Number(raw);if(Number.isFinite(numeric))return Math.abs(numeric)<100000000000?Math.trunc(numeric*1000):Math.trunc(numeric);const parsed=Date.parse(raw);return Number.isFinite(parsed)?parsed:null;};
function quotaDecision({providerRemaining,internalUsed,internalReserved,cost}){const p=number(providerRemaining),used=number(internalUsed),reserved=number(internalReserved),weight=number(cost);if([p,used,reserved,weight].some(value=>value===null)||weight<=0)return{allowed:false,state:'paused',reason:'QUOTA_EVIDENCE_UNCONFIRMED'};if(p-weight<EMERGENCY_RESERVE)return{allowed:false,state:'paused',reason:'PROVIDER_RESERVE_REACHED'};if(MONTHLY_BUDGET-used-reserved-weight<EMERGENCY_RESERVE)return{allowed:false,state:'deferred',reason:'INTERNAL_BUDGET_RESERVE_REACHED'};return{allowed:true,state:'reserved',providerAfter:p-weight,internalAfter:used+reserved+weight};}
function leaseDecision(checkpoint,now,token){if(checkpoint?.state!=='running')return{claim:true,recovered:false};const expiry=number(checkpoint?.leaseExpiresAtMs);if(expiry!==null&&expiry<=now)return{claim:true,recovered:true,previousTokenDigest:digest(String(checkpoint.leaseToken||'')).slice(0,24)};if(checkpoint?.leaseToken===token)return{claim:true,recovered:false};return{claim:false,recovered:false,reason:'ACTIVE_LEASE'};}
function validatePage(body){if(!body||typeof body!=='object'||!Array.isArray(body.clubs)||body.clubs.length>PAGE_SIZE||number(body.apiRequestsLeft)===null||number(body.numAllClubs)===null)return{valid:false,reason:'UNEXPECTED_PAGE_SHAPE'};const valid=[],quarantine=[],seenClubs=new Set(),seenCourses=new Map();body.clubs.forEach((club,index)=>{const clubID=identifier(club?.clubID);if(!clubID){quarantine.push({level:'club',index,reason:'MISSING_OR_INVALID_CLUB_ID',sourceDigest:digest(club)});return;}if(seenClubs.has(clubID)){quarantine.push({level:'club',clubID,index,reason:'DUPLICATE_CLUB_ID',sourceDigest:digest(club)});return;}seenClubs.add(clubID);const courses=[];for(const [courseIndex,course] of (Array.isArray(club?.courses)?club.courses:[]).entries()){const courseID=identifier(course?.courseID);if(!courseID){quarantine.push({level:'course',clubID,index:courseIndex,reason:'MISSING_OR_INVALID_COURSE_ID',sourceDigest:digest(course)});continue;}const prior=seenCourses.get(courseID);if(prior){quarantine.push({level:'course',clubID,courseID,index:courseIndex,reason:prior===clubID?'DUPLICATE_COURSE_ID':'COURSE_ID_CLUB_CONFLICT',conflictingClubID:prior,sourceDigest:digest(course)});continue;}seenCourses.set(courseID,clubID);courses.push({courseID,sourceUpdatedAt:text(course?.timestampUpdated??course?.updatedAt),sourceDigest:digest(course)});}valid.push({clubID,clubName:text(club?.clubName??club?.name),sourceUpdatedAt:text(club?.timestampUpdated??club?.updatedAt),sourceDigest:digest(club),courses});});const next=body?.pagination?.next??body?.links?.next??body?.next??null;return{valid:true,clubs:valid,quarantine,apiRequestsLeft:number(body.apiRequestsLeft),numAllClubs:number(body.numAllClubs),next:typeof next==='string'&&next.startsWith('/api/v2.3/clubs')?next:null};}
function nextCataloguePath(decoded,currentPath){if(decoded.next)return withPageSize(decoded.next);const current=new URL(currentPath,'https://provider.invalid'),page=Math.max(1,Number(current.searchParams.get('page'))||1);return decoded.clubs.length===PAGE_SIZE&&page*PAGE_SIZE<decoded.numAllClubs?withPageSize(`/api/v2.3/clubs?page=${page+1}`):null;}
function withPageSize(path){const value=new URL(path,'https://provider.invalid');value.searchParams.set('pageSize',String(PAGE_SIZE));return `${value.pathname}?${value.searchParams.toString()}`;}
function classifyMapping(existing,club,course,nowMs=Date.now(),refreshAfterDays=REFRESH_SLO.refreshAfterDays){if(!existing)return'detail_new';const existingCourse=identifier(existing.providerCourseId??existing.courseID),existingClub=identifier(existing.providerClubId??existing.clubID);if(existingCourse&&existingCourse!==course.courseID)return'conflict';if(existingClub&&existingClub!==club.clubID)return'conflict';if(!existingClub||!existingCourse)return'backfill';if(existing.needsReview===true||existing.migrationState==='incomplete'||(existing.coordinatesStatus??existing.coordinateValidity)!=='valid')return'detail_incomplete';const providerTime=epochMilliseconds(course.sourceUpdatedAt??club.sourceUpdatedAt),storedTime=epochMilliseconds(existing.sourceUpdatedAt);if(providerTime!==null&&(storedTime===null||providerTime>storedTime))return'detail_changed';const fetched=epochMilliseconds(existing.providerFetchedAt);if(fetched===null||nowMs-fetched>=refreshAfterDays*86400000)return'detail_stale';return'unchanged';}
function mergeCurated(existing,incoming){const protectedFields=['manualLock','gpsTrusted','curated','curatedFields','heroAsset','description','bookingUrl','operator','verified','isActive','publicationVersion','publicationDigest','createdAt','createdBy','directConfirmed','directConfirmation'],result={...(existing||{}),...incoming};for(const field of protectedFields)if(existing&&Object.hasOwn(existing,field))result[field]=existing[field];if(existing&&(existing.manualLock===true||existing.gpsTrusted===true))for(const field of ['latitude','longitude','lat','lng','coordinateValidity','coordinatesStatus','needsReview'])if(Object.hasOwn(existing,field))result[field]=existing[field];return result;}
function normalizeCursor(clubs,clubOffset,courseOffset){let c=Math.max(0,Number(clubOffset)||0),k=Math.max(0,Number(courseOffset)||0);while(c<clubs.length&&k>=clubs[c].courses.length){c++;k=0;}return{clubOffset:c,courseOffset:k,pageComplete:c>=clubs.length};}
function advanceCursor(clubs,clubOffset,courseOffset){return normalizeCursor(clubs,clubOffset,courseOffset+1);}
function cursorItem(clubs,clubOffset,courseOffset){const cursor=normalizeCursor(clubs,clubOffset,courseOffset),club=clubs[cursor.clubOffset],course=club?.courses?.[cursor.courseOffset];return club&&course?{club,course,cursor}:null;}
function countIdentity(documents){const canonical=documents.filter(({id,data})=>data.schema==='golfriend.v2.course.v2'&&identifier(data.CourseID??data.courseID)===id),providerIds=canonical.map(({data})=>identifier(data.providerCourseId)).filter(Boolean),clubIds=canonical.map(({data})=>identifier(data.providerClubId??data.ClubID??data.clubID)).filter(Boolean),frequencies=providerIds.reduce((map,id)=>(map.set(id,(map.get(id)||0)+1),map),new Map());return{canonical:canonical.length,usable:canonical.filter(({data})=>data.needsReview!==true).length,uniqueCourseIDs:new Set(canonical.map(({id})=>id)).size,uniqueProviderCourseIds:new Set(providerIds).size,uniqueClubIDs:new Set(clubIds).size,missingCourseID:documents.length-canonical.length,missingProviderCourseId:canonical.length-providerIds.length,missingClubID:canonical.length-clubIds.length,duplicateProviderCourseIds:[...frequencies.values()].reduce((sum,count)=>sum+Math.max(0,count-1),0)};}
function createLimiter(now=()=>Date.now(),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms))){let starts=[];return async()=>{const current=now();starts=starts.filter(value=>current-value<1000);if(starts.length>=MAX_RPS){await wait(1000-(current-starts[0]));starts=starts.filter(value=>now()-value<1000);}starts.push(now());};}
module.exports={EMERGENCY_RESERVE,IMPORT_VERSION,MAX_RPS,MONTHLY_BUDGET,PAGE_SIZE,REFRESH_SLO,activationReceiptDigest,activationReceiptMatches,activationRevisionBindingsMatch,advanceCursor,assessCanaryAccountingEvidence,canaryReceiptMatches,canaryReceiptPayload,canonicalJson,canonicalize,classifyMapping,countIdentity,createLimiter,cursorItem,digest,epochMilliseconds,identifier,leaseDecision,mergeCurated,nextCataloguePath,normalizeCursor,normalizeRevisionIdentity,quotaDecision,text,validatePage,withPageSize};
