'use strict';
const crypto=require('node:crypto');
const IMPORT_VERSION='golfriend.golf-api-catalogue.v2',MAX_RPS=5;
const digest=value=>crypto.createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
const text=value=>String(value??'').trim().normalize('NFC')||null;
const identifier=value=>{const result=text(value);return result&&result.length<=160&&/^[A-Za-z0-9_-]+$/.test(result)?result:null;};
const number=value=>{const result=Number(value);return Number.isFinite(result)?result:null;};
function quotaDecision(remaining,reserve,cost){const left=number(remaining),floor=number(reserve),weight=number(cost);if(left===null||floor===null||weight===null||floor<0||weight<=0)return{allowed:false,reason:'PROVIDER_QUOTA_UNCONFIRMED'};return left-weight>=floor?{allowed:true,remainingAfter:left-weight}:{allowed:false,reason:'PROVIDER_QUOTA_RESERVE_REACHED'};}
function leaseDecision(checkpoint,now,token){if(checkpoint?.state!=='running')return{claim:true,recovered:false};const expiry=number(checkpoint?.leaseExpiresAtMs);if(expiry!==null&&expiry<=now)return{claim:true,recovered:true,previousTokenDigest:digest(String(checkpoint.leaseToken||'')).slice(0,24)};if(checkpoint?.leaseToken===token)return{claim:true,recovered:false};return{claim:false,recovered:false,reason:'ACTIVE_LEASE'};}
function decodePage(body){const clubs=Array.isArray(body?.clubs)?body.clubs:[],valid=[],quarantine=[],seenClubs=new Set(),seenCourses=new Map();clubs.forEach((club,index)=>{const clubID=identifier(club?.clubID);if(!clubID){quarantine.push({level:'club',index,reason:'MISSING_OR_INVALID_CLUB_ID',sourceDigest:digest(club)});return;}if(seenClubs.has(clubID)){quarantine.push({level:'club',clubID,index,reason:'DUPLICATE_CLUB_ID',sourceDigest:digest(club)});return;}seenClubs.add(clubID);const courses=[];for(const [courseIndex,course] of (Array.isArray(club?.courses)?club.courses:[]).entries()){const courseID=identifier(course?.courseID);if(!courseID){quarantine.push({level:'course',clubID,index:courseIndex,reason:'MISSING_OR_INVALID_COURSE_ID',sourceDigest:digest(course)});continue;}const prior=seenCourses.get(courseID);if(prior&&prior!==clubID){quarantine.push({level:'course',clubID,courseID,index:courseIndex,reason:'COURSE_ID_CLUB_CONFLICT',conflictingClubID:prior,sourceDigest:digest(course)});continue;}if(prior===clubID){quarantine.push({level:'course',clubID,courseID,index:courseIndex,reason:'DUPLICATE_COURSE_ID',sourceDigest:digest(course)});continue;}seenCourses.set(courseID,clubID);courses.push({courseID,sourceUpdatedAt:text(course?.timestampUpdated??course?.updatedAt),sourceDigest:digest(course)});}valid.push({clubID,clubName:text(club?.clubName??club?.name),sourceUpdatedAt:text(club?.timestampUpdated??club?.updatedAt),sourceDigest:digest(club),courses});});const next=body?.pagination?.next??body?.links?.next??body?.next??null;return{clubs:valid,quarantine,apiRequestsLeft:number(body?.apiRequestsLeft),next:typeof next==='string'&&next.startsWith('/api/v2.3/clubs')?next:null,numAllClubs:number(body?.numAllClubs)};}
function nextCataloguePath(decoded,currentPath){if(decoded.next)return decoded.next;const current=new URL(currentPath,'https://www.golfapi.io'),page=Math.max(1,Number(current.searchParams.get('page'))||1),returned=decoded.clubs.length,total=decoded.numAllClubs;if(returned===200&&Number.isFinite(total)&&page*200<total)return`/api/v2.3/clubs?page=${page+1}`;return null;}
function classifyMapping(existing,club,course){if(!existing)return'detail_new';const existingClub=identifier(existing.providerClubId??existing.clubID);if(existingClub&&existingClub!==club.clubID)return'conflict';if(!existingClub)return'backfill';if(existing.needsReview===true||existing.migrationState==='incomplete'||existing.coordinateValidity!=='valid')return'detail_incomplete';const providerTime=Date.parse(course.sourceUpdatedAt||club.sourceUpdatedAt||''),storedTime=Date.parse(existing.sourceUpdatedAt||'');if(Number.isFinite(providerTime)&&(!Number.isFinite(storedTime)||providerTime>storedTime))return'detail_changed';return'unchanged';}
function mergeCurated(existing,incoming){const protectedFields=['manualLock','gpsTrusted','curated','curatedFields','heroAsset','description','bookingUrl','operator','verified','isActive','publicationVersion','publicationDigest','createdAt','createdBy'],result={...(existing||{}),...incoming};for(const field of protectedFields)if(existing&&Object.hasOwn(existing,field))result[field]=existing[field];if(existing&&(existing.manualLock===true||existing.gpsTrusted===true))for(const field of ['latitude','longitude','lat','lng','coordinateValidity','needsReview'])if(Object.hasOwn(existing,field))result[field]=existing[field];return result;}
function createLimiter(now=()=>Date.now(),wait=ms=>new Promise(resolve=>setTimeout(resolve,ms))){let starts=[];return async()=>{const current=now();starts=starts.filter(value=>current-value<1000);if(starts.length>=MAX_RPS){await wait(1000-(current-starts[0]));starts=starts.filter(value=>now()-value<1000);}starts.push(now());};}
module.exports={IMPORT_VERSION,MAX_RPS,classifyMapping,createLimiter,decodePage,digest,identifier,leaseDecision,mergeCurated,nextCataloguePath,quotaDecision,text};
