'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),p=require('./provider-lifecycle');

function harness(options={}){const cost=options.cost??.1,state={reservations:0,providerCalls:0,releases:0,ledger:{reserved:cost,completed:0,failed:0,released:0},reservation:{status:'reserved'},pending:null,evidence:null};const observation=()=>({apiRequestsLeft:options.providerRemaining??3907.6,clubs:[]});return{state,ports:{cost,measureCost:options.measureCost,runId:'run-1',path:'/api/v2.3/clubs?pageSize=200',digest:()=> 'response-digest',now:()=> '2026-08-19T03:00:00.000Z',reserve:async()=>{state.reservations++;return options.deferred?{reserved:false,state:'paused',reason:'QUOTA_EXHAUSTED'}:{reserved:true,reservationId:'reservation-1'};},markInFlight:async()=>{state.reservation.status='in_flight';},releaseReservation:async(_r,value)=>{state.releases++;state.ledger.reserved-=value.cost;state.ledger.released+=value.cost;state.reservation={...state.reservation,status:'released',reason:value.reason};},limit:async()=>{if(options.limitFailure)throw Error('LIMITER_FAILED');},transport:async()=>{state.providerCalls++;if(options.transportFailure)throw Error('NETWORK_FAILED');if(options.status)return{ok:false,status:options.status,headers:{get:name=>name==='retry-after'?options.retryAfter??null:null},text:async()=>'{"error":"failed"}'};return{ok:true,status:200,headers:{get:()=>null},text:async()=>JSON.stringify(observation())};},recordObservation:async(_r,value)=>{if(options.observationFailure)throw Error('OBSERVATION_WRITE_FAILED');state.reservation={...state.reservation,...value,status:'response_observed'};},settleCompleted:async(_r,value)=>{if(options.settlementFailure)throw Error('SETTLEMENT_WRITE_FAILED');if(state.reservation.status==='completed')return{idempotent:true};state.ledger.reserved-=value.reservedCost;state.ledger.completed+=value.cost;state.reservation.status='completed';state.evidence=value;return{idempotent:false};},persistPending:async(_r,value,classification)=>{if(options.fallbackFailure)throw Error('PENDING_WRITE_FAILED');state.reservation={...state.reservation,...value,status:'pending_settlement'};state.pending={...value,state:'pending',classification};},settleTransportFailure:async(_r,value)=>{state.ledger.reserved-=value.cost;state.ledger.failed+=value.cost;state.reservation.status='failed';}}};}

test('transport failure books one attempted reservation as failed',async()=>{const h=harness({transportFailure:true});await assert.rejects(p.executeProviderRequest(h.ports),/NETWORK_FAILED/);assert.deepEqual(h.state.ledger,{reserved:0,completed:0,failed:.1,released:0});assert.equal(h.state.reservations,1);assert.equal(h.state.reservation.status,'failed');assert.equal(h.state.providerCalls,1);});
test('one successful request makes one reservation and settles completed evidence',async()=>{const h=harness(),result=await p.executeProviderRequest(h.ports);assert.equal(result.settlementState,'completed');assert.deepEqual(h.state.ledger,{reserved:0,completed:.1,failed:0,released:0});assert.equal(h.state.reservations,1);assert.equal(result.reservationId,'reservation-1');assert.equal(h.state.evidence.responseDigest,'response-digest');assert.equal(h.state.evidence.providerRemaining,3907.6);});
test('429 settles its one actual attempt and preserves Retry-After for the job',async()=>{const h=harness({status:429,retryAfter:'45'});await assert.rejects(p.executeProviderRequest(h.ports),error=>error.status===429&&error.retryAfterSeconds===45&&error.providerAttempted===true);assert.equal(h.state.reservations,1);assert.equal(h.state.providerCalls,1);assert.deepEqual(h.state.ledger,{reserved:0,completed:0,failed:.1,released:0});});
test('a failure before the request starts releases the unused reservation',async()=>{const h=harness({limitFailure:true});await assert.rejects(p.executeProviderRequest(h.ports),/LIMITER_FAILED/);assert.equal(h.state.providerCalls,0);assert.equal(h.state.releases,1);assert.deepEqual(h.state.ledger,{reserved:0,completed:0,failed:0,released:.1});});
test('quota exhaustion makes no in-flight request or second reservation',async()=>{const h=harness({deferred:true}),result=await p.executeProviderRequest(h.ports);assert.deepEqual(result,{deferred:true,state:'paused',reason:'QUOTA_EXHAUSTED'});assert.equal(h.state.reservations,1);assert.equal(h.state.providerCalls,0);});
test('validated response plus primary settlement failure becomes pending and never failed',async()=>{const h=harness({settlementFailure:true});await assert.rejects(p.executeProviderRequest(h.ports),error=>error instanceof p.PostResponseSettlementError&&error.classification==='COMPLETED_SETTLEMENT_PENDING');assert.deepEqual(h.state.ledger,{reserved:.1,completed:0,failed:0,released:0});assert.equal(h.state.pending.state,'pending');assert.equal(h.state.pending.responseDigest,'response-digest');});
test('fallback failure retains observed reservation without false failure',async()=>{const h=harness({settlementFailure:true,fallbackFailure:true});await assert.rejects(p.executeProviderRequest(h.ports),error=>error instanceof p.PostResponseSettlementError&&error.fallbackRetained===true);assert.deepEqual(h.state.ledger,{reserved:.1,completed:0,failed:0,released:0});assert.equal(h.state.reservation.status,'response_observed');});
test('pending reconciliation is idempotent and performs no second provider call',async()=>{const h=harness({settlementFailure:true});await assert.rejects(p.executeProviderRequest(h.ports));h.ports.settleCompleted=async(_r,value)=>{if(h.state.reservation.status==='completed')return{idempotent:true};h.state.ledger.reserved-=value.cost;h.state.ledger.completed+=value.cost;h.state.reservation.status='completed';h.state.pending.state='completed';return{idempotent:false};};const reconcile=()=>p.reconcilePendingSettlement({pendingId:'reservation-1',loadPending:async()=>h.state.pending,settlePending:value=>h.ports.settleCompleted(null,value)});assert.deepEqual(await reconcile(),{state:'completed',idempotent:false,providerRequests:0});assert.deepEqual(await reconcile(),{state:'completed',idempotent:true,providerRequests:0});assert.equal(h.state.providerCalls,1);assert.deepEqual(h.state.ledger,{reserved:0,completed:.1,failed:0,released:0});});
test('calibration reserves conservatively and settles only the measured provider delta',async()=>{const h=harness({cost:1,providerRemaining:99.9,measureCost:({providerRemaining})=>Number((100-providerRemaining).toFixed(6))}),result=await p.executeProviderRequest(h.ports);assert.equal(result.measuredCost,.1);assert.equal(result.reservedCost,1);assert.deepEqual(h.state.ledger,{reserved:0,completed:.1,failed:0,released:0});assert.equal(h.state.evidence.reservedCost,1);assert.equal(h.state.evidence.cost,.1);assert.equal(h.state.providerCalls,1);});
test('unmeasurable post-response calibration retains the reservation without inventing cost',async()=>{const h=harness({cost:1,measureCost:()=>{throw Error('NO_FRESH_DELTA');}});await assert.rejects(p.executeProviderRequest(h.ports),error=>error instanceof p.PostResponseSettlementError&&error.classification==='COST_MEASUREMENT_PENDING');assert.deepEqual(h.state.ledger,{reserved:1,completed:0,failed:0,released:0});assert.equal(h.state.pending.cost,null);assert.equal(h.state.pending.reservedCost,1);assert.equal(h.state.pending.responseDigest,'response-digest');assert.equal(h.state.providerCalls,1);let settlements=0;assert.deepEqual(await p.reconcilePendingSettlement({pendingId:'reservation-1',loadPending:async()=>h.state.pending,settlePending:async()=>{settlements++;}}),{state:'blocked',reason:'PENDING_EVIDENCE_INVALID',providerRequests:0});assert.equal(settlements,0);});
