'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const source=fs.readFileSync(path.join(__dirname,'index.js'),'utf8');
test('every provider request reserves settles and records immutable quota evidence',()=>{assert.match(source,/async function provider[\s\S]*reserveProvider[\s\S]*settleProvider/);assert.match(source,/golf_api_quota_evidence/);assert.match(source,/providerEvidenceAt/);});
test('expired reservations are released transactionally',()=>{assert.match(source,/reconcileExpiredReservations/);assert.match(source,/RESERVATION_EXPIRED/);assert.match(source,/weightedReleased/);});
test('quota pause and defer do not increment failure or attempts',()=>{const retry=source.slice(source.indexOf('async function consumeRetries'),source.indexOf('async function writeCountReceipt'));assert.match(retry,/if\(detail\.deferred\)\{deferred\+\+;break;\}/);assert(retry.indexOf('const attempts=')>retry.indexOf('if(detail.deferred)'));});
test('within-page cursor is persisted after each mapping',()=>{assert.match(source,/persistCursor\(runId,token,cursor,checkpoint\.progress/);assert.match(source,/clubOffset/);assert.match(source,/courseOffset/);assert.match(source,/pageCacheId/);});
test('zero-course traversal normalizes before mapping and budget deferral retains the current cursor',()=>{assert.match(source,/d\.normalizeCursor\(page\.clubs,checkpoint\.clubOffset,checkpoint\.courseOffset\)/);assert.match(source,/PAGE_CACHE_EXPIRED_REPLAY_FROM_PAGE_START/);const budget=source.slice(source.indexOf("if(detailCounter>=config.detailsPerRun)"),source.indexOf("const detail=await provider"));assert.match(budget,/DETAIL_BUDGET_DEFERRED/);assert.match(budget,/clubOffset:position\.clubOffset/);assert.doesNotMatch(budget,/course_catalogue_failures/);});
test('page-cache TTL cleanup is bounded and activation receipts use the shared verifier',()=>{assert.match(source,/cleanupExpiredPageCaches/);assert.match(source,/where\('expiresAt','<=',admin\.firestore\.Timestamp\.now\(\)\)\.limit\(100\)/);assert.match(source,/d\.activationReceiptMatches\(payload,receipt\.digest\)/);});
test('list contract requests 200 and validates shape before cache',()=>{assert.match(source,/withPageSize\(checkpoint\.pagePath/);assert.match(source,/validatePage\(response\.body\)/);assert.match(source,/if\(!decoded\.valid\)throw Error\(decoded\.reason\)/);});
test('rotation requires digest and deployed revision binding',()=>{assert.match(source,/ROTATION_BINDING_DIGEST_INVALID/);assert.match(source,/DEPLOYED_REVISION_NOT_BOUND/);assert.match(source,/process\.env\.K_REVISION/);});
