'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),d=require('./domain'),q=require('./thailandQuotaCalibration');
const fs=require('node:fs'),path=require('node:path');
const binding=()=>{const x={receiptId:'binding-1',projectId:'golfriend-v2-production-2ee34',workerService:'scheduledcoursecountryingestionworker',workerRevision:'scheduledcoursecountryingestionworker-00001-abc',secretName:'GOLF_API_KEY',secretVersion:'2',secretVersionState:'ENABLED',verifiedAt:'2026-08-28T00:00:00.000Z',immutable:true};return{...x,digest:d.digest(q.bindingPayload(x))}};
const config={enabled:false,providerRequestsAllowed:false,canaryRequestsAllowed:false,calibrationRequestsAllowed:false};
test('Thailand initial-evidence arm is explicit, Director-gated by its callable, and cannot enable global authority',()=>{assert.equal(q.arm({country:'TH',confirmed:true,config,policy:{enabled:false},binding:binding(),runId:'r'}).country,'TH');for(const input of [{country:'JP',confirmed:true},{country:'TH',confirmed:false}])assert.throws(()=>q.arm({...input,config,policy:{},binding:binding(),runId:'r'}),/THAILAND_EXPLICIT_APPROVAL_REQUIRED/);assert.throws(()=>q.arm({country:'TH',confirmed:true,config:{...config,providerRequestsAllowed:true},policy:{},binding:binding(),runId:'r'}),/GLOBAL_PROVIDER_AUTHORITY/);assert.throws(()=>q.arm({country:'TH',confirmed:true,config,policy:{enabled:true,enrollmentComplete:true},binding:binding(),runId:'r'}),/GLOBAL_REFRESH/);});
test('claim is one Thailand list request and rejects altered or replayed authority',()=>{const armed={...config,thailandQuotaEvidenceAllowed:true,thailandQuotaEvidenceState:'armed',thailandQuotaEvidenceCountry:'TH',thailandQuotaEvidenceRunId:'r'};assert.deepEqual(q.claim({config:armed,binding:binding(),runId:'r'}),{country:'TH',runId:'r',requestCount:1,weight:.1,endpoint:'/api/v2.3/clubs?country=TH&pageSize=200'});assert.throws(()=>q.claim({config:{...armed,thailandQuotaEvidenceState:'consumed'},binding:binding(),runId:'r'}),/CLAIM_REJECTED/);});
test('immutable receipt preserves HTTP, quota observation, binding revision, and zero course writes',()=>{const r=q.receipt({binding:binding(),runId:'r',requestIdentity:'reserve-1',httpStatus:200,providerRemaining:444,responseDigest:'a'.repeat(64),quotaBefore:{weightedReserved:0},quotaAfter:{weightedCompleted:.1},failure:null});assert.equal(r.immutable,true);assert.equal(r.courseWrites,0);assert.equal(r.globalRefreshEnabled,false);assert.equal(r.workerRevision,'scheduledcoursecountryingestionworker-00001-abc');assert.equal(d.digest({...r,digest:undefined,immutable:undefined}),r.digest);});
test('server callables are Director-only, bind the live worker and secret metadata, and cannot start ingestion or refresh',()=>{const s=fs.readFileSync(path.join(__dirname,'index.js'),'utf8'),slice=s.slice(s.indexOf('async function armThailandQuotaEvidence'),s.indexOf('exports.startCourseCountryIngestion'));assert.match(slice,/await director\(request\)/);assert.match(s,/functions\/scheduledCourseCountryIngestionWorker/);assert.match(s,/secretEnvironmentVariables/);assert.match(s,/secretVersionState:'ENABLED'/);assert.match(slice,/providerRequestsAllowed:false/);assert.match(slice,/country:'TH'/);assert.match(slice,/golf_api_quota_evidence/);assert.match(slice,/thailand_quota_calibration_receipts/);assert.doesNotMatch(slice,/countryJobCommand\(/);assert.doesNotMatch(slice,/setCourseCountryAutoRefresh/);assert.doesNotMatch(slice,/mergeCanonicalCourse/);});
