import {createHash} from "node:crypto";
export const PROVIDER_PUBLICATION_SCHEMA="golfriend.provider-neutral-booking-publication.v1";
export const PROVIDER_PUBLICATION_KINDS=["availability","booking","status","message","reconciliation"] as const;
const FORBIDDEN=["payment","price","fee","wallet","ledger","settlement","escrow","refund","payout","trip","memberuid","email","phone"];
const hash=(x:string)=>createHash("sha256").update(x).digest("hex");
export const publicationId=(organizationId:string,courseId:string,sourceVersion:string)=>`bpp_${hash(`${organizationId}|${courseId}|${sourceVersion}`).slice(0,32)}`;
export const publicationReceiptId=(id:string,commandId:string,kind:string)=>`bpr_${hash(`${id}|${commandId}|${kind}`).slice(0,32)}`;
export function assertProviderNeutral(value:unknown,path="root"){if(Array.isArray(value)){value.forEach((x,i)=>assertProviderNeutral(x,`${path}.${i}`));return}if(!value||typeof value!=="object")return;for(const[k,v]of Object.entries(value as Record<string,unknown>)){const key=k.toLowerCase();if(FORBIDDEN.some(x=>key.includes(x)))throw new Error(`FORBIDDEN_FIELD:${path}.${k}`);assertProviderNeutral(v,`${path}.${k}`)}}
export function buildProviderPublication(input:any){const organizationId=String(input.organizationId||""),courseId=String(input.courseId||""),sourceVersion=String(input.sourceVersion||"");if(!/^[A-Za-z0-9_-]{2,160}$/.test(organizationId)||!/^[A-Za-z0-9_-]{2,160}$/.test(courseId)||!/^[a-f0-9]{32,64}$/.test(sourceVersion))throw new Error("PUBLICATION_IDENTITY_INVALID");const availability=(input.availability||[]).map((x:any)=>({slotId:String(x.slotId),date:String(x.date),time:String(x.time),timeZone:String(x.timeZone),capacity:Number(x.capacity),bookedCount:Number(x.bookedCount),status:String(x.status),version:Number(x.version)}));const bookings=(input.bookings||[]).map((x:any)=>({bookingId:String(x.bookingId),slotId:String(x.slotId),courseId:String(x.courseId),date:String(x.date),time:String(x.time),timeZone:String(x.timeZone),status:String(x.status),version:Number(x.version),alternativeSlotId:x.alternative?.slotId?String(x.alternative.slotId):null}));const messages=(input.messages||[]).map((x:any)=>({messageId:String(x.messageId),bookingId:String(x.bookingId),senderRole:String(x.senderRole),status:String(x.status||"recorded"),createdAt:String(x.createdAt||"")}));const reconciliation={sourceVersion,counts:input.reconciliation?.counts||{},anomalies:(input.reconciliation?.anomalies||[]).map((x:any)=>({code:String(x.code),bookingId:x.bookingId?String(x.bookingId):null,slotId:x.slotId?String(x.slotId):null,courseId:x.courseId?String(x.courseId):null}))};const payload={schema:PROVIDER_PUBLICATION_SCHEMA,publicationId:publicationId(organizationId,courseId,sourceVersion),organizationId,courseId,sourceVersion,timeZone:String(input.timeZone||"UTC"),availability,bookings,messages,reconciliation,limitations:["Provider-neutral booking coordination only","No payment, fee, wallet, ledger, settlement or Golfriend Trip behavior"]};assertProviderNeutral(payload);return payload}
export interface BookingPublicationAdapter{configured:boolean;publish(payload:ReturnType<typeof buildProviderPublication>,idempotencyKey:string):Promise<{providerReceiptId:string}>}
export const unconfiguredBookingPublicationAdapter=():BookingPublicationAdapter=>({configured:false,async publish(){throw new Error("PROVIDER_UNCONFIGURED")}});
export async function publishWithAdapter(adapter:BookingPublicationAdapter,payload:ReturnType<typeof buildProviderPublication>,key:string){if(!adapter.configured)throw new Error("PROVIDER_UNCONFIGURED");assertProviderNeutral(payload);return adapter.publish(payload,key)}
