import * as admin from "firebase-admin";
import {HttpsError,onCall} from "firebase-functions/v2/https";
import {isActiveStaff} from "./authority.js";
import {buildBookingReport,exportReceiptId,privacySafeExport,reconciliationReceiptId} from "./bookingReportingDomain.js";
import {validateCommand} from "./partnerActivationDomain.js";
if(!admin.apps.length)admin.initializeApp();
const db=admin.firestore(),stamp=()=>admin.firestore.FieldValue.serverTimestamp();
function uid(r:any){if(!r.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");return String(r.auth.uid)}
async function context(r:any,global=false){const id=uid(r);if(global){const s=await db.collection("admin_users").doc(id).get();if(!s.exists||!isActiveStaff(s.data()))throw new HttpsError("permission-denied","Admin required.");return {uid:id,organizationId:"GLOBAL",role:String(s.data()?.role||"staff"),courseIds:[] as string[],admin:true};}const b=await db.collection("partner_identity_bindings").doc(id).get(),organizationId=String(b.data()?.organizationId||""),m=await db.collection("partner_memberships").doc(`${organizationId}_${id}`).get();if(!b.exists||!m.exists||m.data()?.status!=="active")throw new HttpsError("permission-denied","Active membership required.");return {uid:id,organizationId,role:String(m.data()?.role||"viewer"),courseIds:Array.isArray(m.data()?.courseIds)?m.data()!.courseIds.map(String):[],admin:false};}
async function collect(organizationId:string,filters:any,courseIds:string[]=[]){const read=async(name:string)=>{let q:any=db.collection(name);if(organizationId!=="GLOBAL"&&name!=="play_booking_audits")q=q.where("organizationId","==",organizationId);const snap=await q.limit(1000).get();return snap.docs.map((d:any)=>({id:d.id,...d.data()}));};let [bookings,slots,claims,receipts]=await Promise.all([read("bookings"),read("tee_time_slots"),read("course_operators"),read("play_booking_audits")]);if(courseIds.length){bookings=bookings.filter((x:any)=>courseIds.includes(String(x.courseId)));slots=slots.filter((x:any)=>courseIds.includes(String(x.courseId)));claims=claims.filter((x:any)=>courseIds.includes(String(x.courseId||x.id)));}const scopedReceipts=organizationId==="GLOBAL"?receipts:receipts.filter((x:any)=>bookings.some((b:any)=>b.bookingId===x.bookingId));return buildBookingReport(bookings as any,slots.map((x:any)=>({...x,slotId:x.slotId||x.id})) as any,claims.map((x:any)=>({...x,courseId:x.courseId||x.id})) as any,scopedReceipts as any,{...filters,organizationId:organizationId==="GLOBAL"?filters?.organizationId:organizationId},new Date().toISOString());}
async function get(r:any,adminView:boolean){const c=await context(r,adminView),scope=c.role==="course_staff"?c.courseIds:[],report=await collect(c.organizationId,r.data?.filters||{},scope);await db.collection("booking_report_access_audits").add({schema:"golfriend.booking-report-access.v1",actorUid:c.uid,actorRole:c.role,organizationId:c.organizationId,sourceVersion:report.sourceVersion,createdAt:stamp()});return {...report,permissions:{read:true,reconcile:c.admin||["primary_owner","manager"].includes(c.role),export:true}};}
export const getBookingOperationsPortalV2=onCall({enforceAppCheck:true},r=>get(r,false));
export const getBookingOperationsAdminV2=onCall({enforceAppCheck:true},r=>get(r,true));
export const reconcileBookingOperationsV2=onCall({enforceAppCheck:true},async r=>{const c=await context(r,Boolean(r.data?.admin)),cmd=validateCommand(r.data?.commandId);if(!c.admin&&!["primary_owner","manager"].includes(c.role))throw new HttpsError("permission-denied","Owner or manager required.");const report=await collect(c.organizationId,r.data?.filters||{});if(r.data?.expectedSourceVersion&&r.data.expectedSourceVersion!==report.sourceVersion)throw new HttpsError("aborted","SOURCE_VERSION_CONFLICT");const id=reconciliationReceiptId(c.organizationId,cmd),ref=db.collection("booking_reconciliation_receipts").doc(id);try{await ref.create({receiptId:id,schema:"golfriend.booking-reconciliation-receipt.v1",organizationId:c.organizationId,actorUid:c.uid,actorRole:c.role,sourceVersion:report.sourceVersion,anomalies:report.anomalies,counts:report.statuses,createdAt:stamp(),immutable:true});}catch(e:any){if(e?.code!==6&&e?.code!=="already-exists")throw e;}return {success:true,receiptId:id,sourceVersion:report.sourceVersion,anomalies:report.anomalies,restarted:(await ref.get()).exists};});
export const exportBookingOperationsV2=onCall({enforceAppCheck:true},async r=>{const c=await context(r,Boolean(r.data?.admin)),cmd=validateCommand(r.data?.commandId),format=r.data?.format==="json"?"json":"csv",scope=c.role==="course_staff"?c.courseIds:[],report=await collect(c.organizationId,r.data?.filters||{},scope),id=exportReceiptId(c.organizationId,cmd),ref=db.collection("booking_report_export_receipts").doc(id);try{await ref.create({receiptId:id,schema:"golfriend.booking-report-export-receipt.v1",organizationId:c.organizationId,actorUid:c.uid,actorRole:c.role,sourceVersion:report.sourceVersion,format,createdAt:stamp(),immutable:true,privacySafe:true});}catch(e:any){if(e?.code!==6&&e?.code!=="already-exists")throw e;}return {success:true,receiptId:id,sourceVersion:report.sourceVersion,...privacySafeExport(report,format)};});
export const getBookingOperationsReceiptV2=onCall({enforceAppCheck:true},async r=>{const c=await context(r,Boolean(r.data?.admin)),id=String(r.data?.receiptId||"");if(!/^br[re]_[a-f0-9]{32}$/.test(id))throw new HttpsError("invalid-argument","Receipt ID invalid.");const collection=id.startsWith("bre_")?"booking_report_export_receipts":"booking_reconciliation_receipts",snap=await db.collection(collection).doc(id).get();if(!snap.exists)throw new HttpsError("not-found","Receipt not found.");if(!c.admin&&snap.data()?.organizationId!==c.organizationId)throw new HttpsError("permission-denied","Receipt outside organization.");const x=snap.data()||{};return {receiptId:id,schema:x.schema,organizationId:x.organizationId,sourceVersion:x.sourceVersion,format:x.format||null,counts:x.counts||null,anomalies:x.anomalies||null,immutable:true,createdAt:x.createdAt||null};});
