import { createHash } from "node:crypto";

export const BOOKING_REPORT_SCHEMA = "golfriend.booking-operations-report.v1";
export const REPORT_STATUSES = ["pending", "alternative_proposed", "awaiting_partner", "confirmed", "completed", "cancelled", "expired"] as const;
export type ReportStatus = typeof REPORT_STATUSES[number];
export type BookingFact = {bookingId:string; organizationId:string; courseId:string; slotId:string; date:string; time:string; timeZone:string; status:string; version:number; alternative?:{slotId?:string}|null};
export type SlotFact = {slotId:string; organizationId:string; courseId:string; date:string; time:string; timeZone:string; capacity:number; bookedCount:number};
export type ClaimFact = {courseId:string; organizationId:string; status:string};
export type ReceiptFact = {receiptId:string; bookingId:string};
export type Filters = {organizationId?:string;courseId?:string;dateFrom?:string;dateTo?:string;status?:string;cursor?:string;pageSize?:number};
export type Anomaly = {code:"OVER_CAPACITY"|"ORPHANED_BOOKING"|"STALE_ALTERNATIVE"|"DUPLICATE_RECEIPT"|"MISSING_COURSE_CLAIM"|"STATUS_DIVERGENCE"; bookingId?:string;slotId?:string;courseId?:string};
const digest=(value:string)=>createHash("sha256").update(value).digest("hex");
export const reconciliationReceiptId=(organizationId:string,commandId:string)=>`brr_${digest(`${organizationId}|${commandId}`).slice(0,32)}`;
export const exportReceiptId=(organizationId:string,commandId:string)=>`bre_${digest(`${organizationId}|${commandId}`).slice(0,32)}`;
export function normalizeFilters(input:any):Filters { const pageSize=Math.min(100,Math.max(1,Number(input?.pageSize||25))); const date=(v:any)=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||""))?String(v):undefined; const status=REPORT_STATUSES.includes(input?.status)?input.status:undefined; return {organizationId:String(input?.organizationId||"")||undefined,courseId:String(input?.courseId||"")||undefined,dateFrom:date(input?.dateFrom),dateTo:date(input?.dateTo),status,cursor:String(input?.cursor||"")||undefined,pageSize}; }
export function effectiveStatus(b:BookingFact, nowIso:string):ReportStatus { if((b.status==="pending"||b.status==="alternative_proposed"||b.status==="awaiting_partner")&&`${b.date}T${b.time}:00`<nowIso.slice(0,19))return "expired"; return REPORT_STATUSES.includes(b.status as ReportStatus)?b.status as ReportStatus:"pending"; }
export function buildBookingReport(bookings:BookingFact[],slots:SlotFact[],claims:ClaimFact[],receipts:ReceiptFact[],rawFilters:any,nowIso:string){
 const f=normalizeFilters(rawFilters), slotBy=new Map(slots.map(s=>[s.slotId,s])), claimBy=new Map(claims.map(c=>[c.courseId,c]));
 let rows=bookings.map(b=>({...b,status:effectiveStatus(b,nowIso)})).filter(b=>(!f.organizationId||b.organizationId===f.organizationId)&&(!f.courseId||b.courseId===f.courseId)&&(!f.dateFrom||b.date>=f.dateFrom)&&(!f.dateTo||b.date<=f.dateTo)&&(!f.status||b.status===f.status)).sort((a,b)=>`${a.date}|${a.time}|${a.bookingId}`.localeCompare(`${b.date}|${b.time}|${b.bookingId}`));
 if(f.cursor)rows=rows.filter(x=>x.bookingId>f.cursor!); const page=rows.slice(0,f.pageSize), nextCursor=rows.length>page.length?page[page.length-1]?.bookingId:null;
 const statuses=Object.fromEntries(REPORT_STATUSES.map(s=>[s,0])) as Record<ReportStatus,number>; for(const b of rows)statuses[b.status]++;
 const byCourse=new Map<string,{organizationId:string;courseId:string;timeZone:string;capacity:number;pending:number;confirmed:number;completed:number;cancelled:number;expired:number}>();
 for(const s of slots){if((f.organizationId&&s.organizationId!==f.organizationId)||(f.courseId&&s.courseId!==f.courseId)||(f.dateFrom&&s.date<f.dateFrom)||(f.dateTo&&s.date>f.dateTo))continue;const key=`${s.organizationId}|${s.courseId}`,v=byCourse.get(key)||{organizationId:s.organizationId,courseId:s.courseId,timeZone:s.timeZone,capacity:0,pending:0,confirmed:0,completed:0,cancelled:0,expired:0};v.capacity+=s.capacity;byCourse.set(key,v)}
 for(const b of rows){const key=`${b.organizationId}|${b.courseId}`,v=byCourse.get(key)||{organizationId:b.organizationId,courseId:b.courseId,timeZone:b.timeZone,capacity:0,pending:0,confirmed:0,completed:0,cancelled:0,expired:0}; if(b.status==="alternative_proposed")v.pending++; else if(b.status in v)(v as any)[b.status]++;byCourse.set(key,v)}
 const anomalies:Anomaly[]=[]; const activeBySlot=new Map<string,number>(); for(const b of bookings){const st=effectiveStatus(b,nowIso);if(["pending","alternative_proposed","awaiting_partner","confirmed"].includes(st))activeBySlot.set(b.slotId,(activeBySlot.get(b.slotId)||0)+1);const s=slotBy.get(b.slotId);if(!s)anomalies.push({code:"ORPHANED_BOOKING",bookingId:b.bookingId,slotId:b.slotId});const c=claimBy.get(b.courseId);if(!c||c.status!=="active"||c.organizationId!==b.organizationId)anomalies.push({code:"MISSING_COURSE_CLAIM",bookingId:b.bookingId,courseId:b.courseId});if(b.status==="alternative_proposed"&&(!b.alternative?.slotId||!slotBy.has(b.alternative.slotId)))anomalies.push({code:"STALE_ALTERNATIVE",bookingId:b.bookingId});}
 for(const s of slots){const active=activeBySlot.get(s.slotId)||0;if(s.bookedCount>s.capacity||active>s.capacity)anomalies.push({code:"OVER_CAPACITY",slotId:s.slotId,courseId:s.courseId});if(active!==s.bookedCount)anomalies.push({code:"STATUS_DIVERGENCE",slotId:s.slotId,courseId:s.courseId});}
 const receiptCounts=new Map<string,number>();for(const r of receipts)receiptCounts.set(r.receiptId,(receiptCounts.get(r.receiptId)||0)+1);for(const [id,n]of receiptCounts)if(n>1)anomalies.push({code:"DUPLICATE_RECEIPT",bookingId:receipts.find(r=>r.receiptId===id)?.bookingId});
 const safeRows=page.map(({bookingId,organizationId,courseId,slotId,date,time,timeZone,status,version})=>({bookingId,organizationId,courseId,slotId,date,time,timeZone,status,version}));
 const sourceVersion=digest(JSON.stringify({bookings:bookings.map(x=>[x.bookingId,x.version]),slots:slots.map(x=>[x.slotId,x.bookedCount,x.capacity]),receipts:receipts.map(x=>x.receiptId).sort()}));
 return {schema:BOOKING_REPORT_SCHEMA,generatedAt:nowIso,sourceVersion,filters:f,statuses,total:rows.length,summaries:[...byCourse.values()].sort((a,b)=>a.courseId.localeCompare(b.courseId)),rows:safeRows,nextCursor,anomalies:anomalies.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))};
}
export function privacySafeExport(report:ReturnType<typeof buildBookingReport>,format:"csv"|"json"){const body=format==="json"?JSON.stringify({schema:report.schema,generatedAt:report.generatedAt,sourceVersion:report.sourceVersion,filters:report.filters,statuses:report.statuses,summaries:report.summaries,rows:report.rows,anomalies:report.anomalies},null,2):["bookingId,organizationId,courseId,slotId,date,time,timeZone,status,version",...report.rows.map(r=>[r.bookingId,r.organizationId,r.courseId,r.slotId,r.date,r.time,r.timeZone,r.status,r.version].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(","))].join("\n");return {format,contentType:format==="json"?"application/json":"text/csv",body};}
