export const COUNTRY_USER_ANALYTICS_SCHEMA="golfriend.country-user-analytics/v1";
export const COUNTRY_DAILY_SOURCE_SCHEMA="golfriend.country-analytics-daily/v1";
export const COUNTRY_ANALYTICS_MIN_COHORT=10;
export const COUNTRY_ANALYTICS_MAX_DAYS=31;
const DATE=/^\d{4}-\d{2}-\d{2}$/;
export function validateDateRange(startDate:unknown,endDate:unknown):{startDate:string;endDate:string;days:number}{const start=String(startDate||""),end=String(endDate||"");if(!DATE.test(start)||!DATE.test(end))throw new Error("DATE_RANGE_INVALID");const startMs=Date.parse(`${start}T00:00:00Z`),endMs=Date.parse(`${end}T00:00:00Z`),days=Math.floor((endMs-startMs)/86400000)+1;if(!Number.isFinite(days)||days<1||days>COUNTRY_ANALYTICS_MAX_DAYS)throw new Error("DATE_RANGE_INVALID");return{startDate:start,endDate:end,days};}
export function analyticsCountry(value:unknown):string{const country=String(value||"").normalize("NFC").trim().replace(/\s+/g," ").toUpperCase();return country&&country.length<=64&&!/[<>\x00-\x1F]/.test(country)?country:"UNKNOWN";}
const count=(value:unknown)=>Number.isInteger(Number(value))&&Number(value)>=0?Number(value):0;
const privateCount=(value:unknown):number|null=>{const valueCount=count(value);return valueCount>0&&valueCount<COUNTRY_ANALYTICS_MIN_COHORT?null:valueCount;};
export type DailyCountryMetric={date:string;country:string;suppressed:boolean;activeUsers:number|null;newUsers:number|null;returningUsers:number|null;generatedAt:string|null};
export function projectDailyCountryAnalytics(documents:any[]):{days:DailyCountryMetric[];countries:Array<{country:string;activeUserDays:number;newUsers:number;returningUserDays:number;observedDays:number}>;freshestGeneratedAt:string|null;limitations:string[]}{const days:DailyCountryMetric[]=[];const limitations=new Set<string>();let freshest:string|null=null;
 for(const source of documents){if(source?.schemaVersion!==COUNTRY_DAILY_SOURCE_SCHEMA){limitations.add("INVALID_SOURCE_SCHEMA_OMITTED");continue;}const date=String(source.date||"");if(!DATE.test(date)){limitations.add("INVALID_DATE_OMITTED");continue;}const country=analyticsCountry(source.country),activeUsers=privateCount(source.activeUsers),newUsers=privateCount(source.newUsers),returningUsers=privateCount(source.returningUsers),suppressed=activeUsers===null;const generatedAt=typeof source.generatedAt==="string"&&Number.isFinite(Date.parse(source.generatedAt))?source.generatedAt:null;if(generatedAt&&(!freshest||generatedAt>freshest))freshest=generatedAt;if(suppressed||newUsers===null||returningUsers===null)limitations.add("MINIMUM_COHORT_10");days.push({date,country,suppressed,activeUsers,newUsers,returningUsers,generatedAt});}
 days.sort((a,b)=>a.date.localeCompare(b.date)||a.country.localeCompare(b.country));const grouped=new Map<string,{country:string;activeUserDays:number;newUsers:number;returningUserDays:number;observedDays:number}>();for(const day of days){if(day.suppressed)continue;const row=grouped.get(day.country)||{country:day.country,activeUserDays:0,newUsers:0,returningUserDays:0,observedDays:0};row.activeUserDays+=day.activeUsers||0;row.newUsers+=day.newUsers||0;row.returningUserDays+=day.returningUsers||0;row.observedDays++;grouped.set(day.country,row);}return{days,countries:[...grouped.values()].sort((a,b)=>a.country.localeCompare(b.country)),freshestGeneratedAt:freshest,limitations:[...limitations].sort()};}
