export const COUNTRY_USER_ANALYTICS_SCHEMA="golfriend.country-user-analytics-interop/v1";
export const BACKEND_COUNTRY_ANALYTICS_SCHEMA="golfriend.v2.country-analytics.v1";
export const COUNTRY_ANALYTICS_MIN_COHORT=10;
export const COUNTRY_ANALYTICS_MAX_DAYS=31;
export const COUNTRY_ANALYTICS_STALE_MS=45*24*60*60*1000;
const DATE=/^\d{4}-\d{2}-\d{2}$/;
export function validateDateRange(startDate:unknown,endDate:unknown):{startDate:string;endDate:string;startPeriod:string;endPeriod:string;days:number}{const start=String(startDate||""),end=String(endDate||"");if(!DATE.test(start)||!DATE.test(end))throw new Error("DATE_RANGE_INVALID");const startMs=Date.parse(`${start}T00:00:00Z`),endMs=Date.parse(`${end}T00:00:00Z`),days=Math.floor((endMs-startMs)/86400000)+1;if(!Number.isFinite(days)||days<1||days>COUNTRY_ANALYTICS_MAX_DAYS)throw new Error("DATE_RANGE_INVALID");return{startDate:start,endDate:end,startPeriod:start.slice(0,7),endPeriod:end.slice(0,7),days};}
export function frozenCountry(value:unknown):string{const country=String(value||"").trim().toUpperCase();return /^[A-Z]{2}$/.test(country)||country==="UNKNOWN"?country:"UNKNOWN";}
function generatedAtIso(value:any):string|null{if(typeof value==="number"&&Number.isFinite(value))return new Date(value).toISOString();if(typeof value==="string"&&Number.isFinite(Date.parse(value)))return new Date(value).toISOString();const millis=value?.toMillis?.();return Number.isFinite(millis)?new Date(millis).toISOString():null;}
export type FrozenCountryRow={period:string;country:string;distinctMembers:number|null;suppressed:boolean;generatedAt:string|null};
export function adaptFrozenCountryAggregates(documents:any[],nowMs=Date.now()):{rows:FrozenCountryRow[];countries:Array<{country:string;currentDistinctMembers:number|null;currentPeriod:string;suppressed:boolean;observedPeriods:number}>;freshestGeneratedAt:string|null;stale:boolean;metricAvailability:{distinctMembers:"available";activeUsers:"unavailable";newUsers:"unavailable";returningUsers:"unavailable"};limitations:string[]}{const rows:FrozenCountryRow[]=[],limitations=new Set<string>(["ACTIVE_NEW_RETURNING_UNAVAILABLE_IN_FROZEN_V1"]);let freshest:string|null=null;
 for(const source of documents){if(source?.schema!==BACKEND_COUNTRY_ANALYTICS_SCHEMA||source?.authority!=="server"||source?.minCohort!==COUNTRY_ANALYTICS_MIN_COHORT||source?.coarseCountryOnly!==true||source?.unknownBucket!=="UNKNOWN"){limitations.add("INVALID_FROZEN_AGGREGATE_OMITTED");continue;}const period=String(source.period||"");if(!/^\d{4}-\d{2}$/.test(period)){limitations.add("INVALID_PERIOD_OMITTED");continue;}const generatedAt=generatedAtIso(source.generatedAt);if(generatedAt&&(!freshest||generatedAt>freshest))freshest=generatedAt;for(const bucket of Array.isArray(source.memberCountryBuckets)?source.memberCountryBuckets:[]){const country=frozenCountry(bucket?.country),raw=Number(bucket?.count),mustSuppress=bucket?.suppressed===true||!Number.isInteger(raw)||raw<COUNTRY_ANALYTICS_MIN_COHORT;rows.push({period,country,distinctMembers:mustSuppress?null:raw,suppressed:mustSuppress,generatedAt});}}
 rows.sort((a,b)=>a.period.localeCompare(b.period)||a.country.localeCompare(b.country));const latest=new Map<string,FrozenCountryRow>();for(const row of rows)latest.set(row.country,row);const countries=[...latest.values()].map(row=>({country:row.country,currentDistinctMembers:row.distinctMembers,currentPeriod:row.period,suppressed:row.suppressed,observedPeriods:rows.filter(item=>item.country===row.country).length})).sort((a,b)=>a.country.localeCompare(b.country));const stale=!freshest||nowMs-Date.parse(freshest)>COUNTRY_ANALYTICS_STALE_MS;if(stale)limitations.add("SOURCE_STALE_OR_MISSING");return{rows,countries,freshestGeneratedAt:freshest,stale,metricAvailability:{distinctMembers:"available",activeUsers:"unavailable",newUsers:"unavailable",returningUsers:"unavailable"},limitations:[...limitations].sort()};}
