import assert from'node:assert/strict';import{canonicalize,correctionRequest,createGolfApiPort,duplicateSignals,planAcquisition,publishCanonical,quotaDecision,reconcileQuota,reviewDecision,validateQuotaState}from'./courseAcquisitionDomain.js';let passed=0;const check=async(name:string,fn:()=>unknown|Promise<unknown>)=>{await fn();passed++;console.log(`ok ${passed} - ${name}`)};const raw={providerCourseId:'p1',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,providerRequestId:'r1',sourceVersion:'v1',sourceUpdatedAt:'2026-08-14T00:00:00Z'},quotaState:any={schema:'golfriend.golf-api-quota.v2',enabled:true,month:'2026-08',configuredBudget:500,emergencyReserve:25,reserved:0,completed:0,failed:0,released:0,dailyLimit:30,weeklyLimit:120,daily:{key:'2026-08-15',used:0},weekly:{key:'2026-W33',used:0},maxOverrideCalls:10,maxOverridesPerMonth:2,overridesUsed:0,reservationTtlMinutes:15,version:1};void(async()=>{
await check('provider adapter is injected bounded and credential required',async()=>{assert.throws(()=>createGolfApiPort({apiKey:'',request:async()=>({status:200,headers:{},body:{}})}),/UNCONFIGURED/);let path='';const port=createGolfApiPort({apiKey:'fixture-secret',request:async p=>(path=p,{status:200,headers:{'x-request-id':'r1'},body:{courses:[{courseID:'p1',courseName:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,updatedAt:'2026-08-14T00:00:00Z'}]}})});assert.equal((await port.search({country:'Thailand'})).items.length,1);assert.match(path,/country=Thailand/);});
await check('quota is configurable replay-ready paced and reconcilable',()=>{const input={commandId:'c1',estimatedCost:5,dayKey:'2026-08-15',weekKey:'2026-W33',now:Date.parse('2026-08-15T00:00:00Z')},r=quotaDecision(quotaState,input);assert.equal(r.remainingAfter,470);assert.equal(quotaDecision({...quotaState,configuredBudget:100,weeklyLimit:100},input).remainingAfter,70);const reserved={...quotaState,reserved:5,daily:{...quotaState.daily,used:5},weekly:{...quotaState.weekly,used:5}},next=reconcileQuota(reserved,{estimatedCost:5,dayKey:input.dayKey,weekKey:input.weekKey},'completed',3);assert.equal(next.released,2);assert.equal(next.completed,3);assert.equal(next.daily.used,3);assert.throws(()=>quotaDecision(quotaState,{...input,commandId:'x',estimatedCost:31}),/PACING/);});
await check('planner is a true zero-call zero-write dry run',()=>{const p=planAcquisition({coverage:[{country:'TH',city:'Phuket',missingCoordinates:2,stale:0,demand:0}],manual:[],remainingBudget:50});assert.equal(p.providerCalls,0);assert.equal(p.writes,0);assert.equal(p.estimatedCalls,1);});
await check('canonicalization detects duplicates and never auto merges',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),signals:any=duplicateSignals(c,[{courseID:'existing',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7.001,longitude:98.001,source:{sourceCourseId:'other'}}]);assert.equal(signals[0].automaticMerge,false);assert.ok(signals[0].reasons.includes('name_city_country'));});
await check('publication requires separation of duties and exact reviewed digest',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),d=reviewDecision({candidate:c,action:'confirm_new',reviewerId:'reviewer',commandId:'cmd1'});assert.throws(()=>publishCanonical(c,d,{uid:'reviewer',role:'course_catalogue_approver'},Date.now()),/DENIED/);const out=publishCanonical(c,d,{uid:'approver',role:'course_catalogue_approver'},Date.parse('2026-08-15T00:00:00Z'));assert.equal(out.schema,'golfriend.v2.course.v2');assert.equal(out.verified,true);assert.equal(out.needsReview,false);});
await check('portal correction is request-only and cannot mutate canonical data',()=>{const r:any=correctionRequest({canonicalCourseId:'c1',claimedRelationship:'operator',proposedCorrection:'Correct city',evidenceReference:'evidence-1',locale:'en',consent:true});assert.equal(r.state,'submitted');assert.equal(r.canonicalMutation,false);assert.equal(correctionRequest({...r,consent:false}).state,'rejected');});
await check('hostile provider fields and secrets never enter a candidate',async()=>{const port=createGolfApiPort({apiKey:'fixture-secret',request:async()=>({status:200,headers:{'x-request-id':'safe-request'},body:{courses:[{courseID:'p1',courseName:'Alpha',country:'Thailand',latitude:7,longitude:98,updatedAt:'2026-08-14T00:00:00Z',staffNote:'private',signedUrl:'https://private',apiKey:'leak'}]}})}),item=(await port.search({})).items[0]!,candidate:any=canonicalize(item,'job',Date.parse('2026-08-15T00:00:00Z')),serialized=JSON.stringify(candidate);assert.doesNotMatch(serialized,/staffNote|signedUrl|fixture-secret|apiKey/);assert.deepEqual(Object.keys(item).sort(),['city','country','latitude','longitude','name','providerCourseId','providerRequestId','sourceUpdatedAt','sourceVersion'].sort());});
await check('coordinate poisoning and bidi controls fail closed',async()=>{const bad=createGolfApiPort({apiKey:'fixture',request:async()=>({status:200,headers:{'x-request-id':'r'},body:{courses:[{courseID:'p',courseName:'Bad',country:'T\u202eH',latitude:91,longitude:1}]}})});await assert.rejects(()=>bad.search({}),/INVALID/);});
await check('quota replay identity is deterministic and override needs bounded audit evidence',()=>{const state:any={...quotaState,configuredBudget:100,emergencyReserve:10,completed:89,dailyLimit:1,weeklyLimit:100,daily:{...quotaState.daily,used:1},weekly:{...quotaState.weekly,used:89}},input={commandId:'same',estimatedCost:2,dayKey:'2026-08-15',weekKey:'2026-W33',now:1000,override:{approved:true,approvalId:'audit-1',maxCalls:2,expiresAt:2000}},a=quotaDecision(state,input),b=quotaDecision(state,input);assert.equal(a.payloadDigest,b.payloadDigest);assert.equal(a.approvalId,'audit-1');assert.throws(()=>quotaDecision(state,{...input,commandId:'x',override:{...input.override,approvalId:''}}),/PACING/);});
await check('malformed contradictory disabled and wrong-period quota fails closed',()=>{for(const bad of[{...quotaState,enabled:false},{...quotaState,reserved:-1},{...quotaState,emergencyReserve:500},{...quotaState,month:'2026-07'},{...quotaState,daily:{key:'2026-08-15',used:Number.NaN}},{...quotaState,version:0}])assert.throws(()=>validateQuotaState(bad as any,'2026-08','2026-08-15','2026-W33'),/QUOTA/);});
await check('reconciliation cannot exceed or underflow an outstanding reservation',()=>{assert.throws(()=>reconcileQuota(quotaState,{estimatedCost:1,dayKey:'2026-08-15',weekKey:'2026-W33'},'completed',1),/RECONCILIATION/);const reserved={...quotaState,reserved:1,daily:{...quotaState.daily,used:1},weekly:{...quotaState.weekly,used:1}};assert.throws(()=>reconcileQuota(reserved,{estimatedCost:1,dayKey:'2026-08-15',weekKey:'2026-W33'},'released',1),/RECONCILIATION/);});
await check('disable switch blocks new reservations but preserves exact reconciliation',()=>{const disabled={...quotaState,enabled:false,reserved:1,daily:{...quotaState.daily,used:1},weekly:{...quotaState.weekly,used:1}};assert.throws(()=>quotaDecision(disabled,{commandId:'new',estimatedCost:1,dayKey:'2026-08-15',weekKey:'2026-W33',now:1}),/QUOTA/);const next=reconcileQuota(disabled,{estimatedCost:1,dayKey:'2026-08-15',weekKey:'2026-W33'},'released',0);assert.equal(next.enabled,false);assert.equal(next.reserved,0);});
await check('review workflow metadata does not invalidate a distinct approver publication',()=>{const c:any=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),d=reviewDecision({candidate:c,action:'confirm_new',reviewerId:'reviewer',commandId:'review-cmd'}),stored={...c,workflowStatus:'reviewed',reviewDecisionId:d.commandId};assert.equal(publishCanonical(stored,d,{uid:'approver',role:'course_catalogue_approver'},Date.parse('2026-08-15T00:00:00Z')).verified,true);});
await check('publication contains only reviewed canonical authority and unknown commercial facts',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),d=reviewDecision({candidate:c,action:'confirm_new',reviewerId:'reviewer',commandId:'cmd1'}),out:any=publishCanonical(c,d,{uid:'approver',role:'course_catalogue_approver'},Date.parse('2026-08-15T00:00:00Z')),s=JSON.stringify(out);assert.equal(out.schema,'golfriend.v2.course.v2');assert.doesNotMatch(s,/price|rating|weather|teeTime|amenit|commission|booking/);});
console.log(`1..${passed}`);})();
