import {defineSecret} from "firebase-functions/params";
import {HttpsError, onCall} from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import {isActiveStaff} from "./authority.js";
import {acquisitionWriteDecision, canonicalize, createGolfApiPort, digest, duplicateSignals, planAcquisition, publishCanonical, quotaDecision, reconcileQuota, reviewDecision, correctionRequest, validateProviderAttemptEvidence, validateQuotaOverride, validateQuotaState, type QuotaState} from "./courseAcquisitionDomain.js";

if (!admin.apps.length) admin.initializeApp();
const db=admin.firestore();
const GOLF_API_KEY=defineSecret("GOLF_API_KEY");
const PROVIDER_BASE="https://www.golfapi.io/api/v2.3";
const BASE_OPTIONS={enforceAppCheck:true,region:"asia-southeast1" as const,memory:"512MiB" as const,timeoutSeconds:120};
const ROLE={viewer:"course_catalogue_viewer",operator:"course_acquisition_operator",reviewer:"course_catalogue_reviewer",approver:"course_catalogue_approver",override:"course_quota_override_approver"} as const;
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value as object).some((key)=>!keys.includes(key)))throw new HttpsError("invalid-argument","REQUEST_INVALID");return value as Record<string,unknown>;};
async function staff(uid:string,allowed:string[]){const snap=await db.collection("admin_users").doc(uid).get(),data=snap.data();if(!snap.exists||!isActiveStaff(data)||data?.status!=="Active"||!allowed.includes(String(data?.role)))throw new HttpsError("permission-denied","STAFF_REQUIRED");return data as {role:string};}
function context(request:any){if(!request.auth?.uid)throw new HttpsError("unauthenticated","AUTH_REQUIRED");if(typeof request.app?.appId!=="string"||!request.app.appId.trim())throw new HttpsError("failed-precondition","APP_CHECK_REQUIRED");return request.auth.uid as string;}
function month(at=new Date()){return at.toISOString().slice(0,7);}
function dayKey(at=new Date()){return at.toISOString().slice(0,10);}function weekKey(at=new Date()){const d=new Date(Date.UTC(at.getUTCFullYear(),at.getUTCMonth(),at.getUTCDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=new Date(Date.UTC(d.getUTCFullYear(),0,1)),w=Math.ceil((((d.getTime()-y.getTime())/86400000)+1)/7);return `${d.getUTCFullYear()}-W${String(w).padStart(2,"0")}`;}
type Reservation={month:string;receiptId:string;estimatedCost:number;dayKey:string;weekKey:string;replay:boolean;result?:unknown};
async function reserve(uid:string,commandId:string,estimatedCost:number,payload:unknown,overrideApprovalId?:string):Promise<Reservation>{const now=Date.now(),m=month(),day=dayKey(),week=weekKey(),ref=db.collection("golf_api_quota").doc(m),receiptId=digest([m,commandId]).slice(0,40),receipt=db.collection("golf_api_quota_receipts").doc(receiptId),actorDigest=digest(["course-acquisition-actor",uid]),payloadDigest=digest({payload,overrideApprovalId:overrideApprovalId??null}),overrideRef=overrideApprovalId?db.collection("golf_api_quota_overrides").doc(overrideApprovalId):null;return db.runTransaction(async tx=>{const reads=[tx.get(receipt),tx.get(ref),...(overrideRef?[tx.get(overrideRef)]:[])],values=await Promise.all(reads),prior=values[0],snap=values[1],overrideSnap=overrideRef?values[2]:null;if(prior.exists){const data=prior.data()!;if(data.commandId!==commandId||data.estimatedCost!==estimatedCost||data.actorDigest!==actorDigest||data.operationPayloadDigest!==payloadDigest)throw new HttpsError("already-exists","COMMAND_REUSED");if(["completed","failed"].includes(data.state))return{month:m,receiptId,estimatedCost,dayKey:data.dayKey,weekKey:data.weekKey,replay:true,result:data.result};throw new HttpsError("aborted",data.expiresAt<=now?"RESERVATION_RECONCILIATION_REQUIRED":"COMMAND_IN_PROGRESS");}if(!snap.exists)throw new HttpsError("failed-precondition","QUOTA_UNCONFIGURED");const state=snap.data() as QuotaState;let override;if(overrideRef&&overrideSnap?.exists){try{override=validateQuotaOverride(overrideSnap.data(),{approvalId:overrideApprovalId!,month:m,operatorDigest:actorDigest,now,maxCalls:state.maxOverrideCalls});}catch{throw new HttpsError("failed-precondition","OVERRIDE_INVALID");}}let decision;try{decision=quotaDecision(validateQuotaState(state,m,day,week),{commandId,estimatedCost,dayKey:day,weekKey:week,override,now});}catch(e){throw new HttpsError("resource-exhausted",e instanceof Error?e.message:"QUOTA_DENIED");}const next={...state,reserved:state.reserved+estimatedCost,daily:{key:day,used:state.daily.used+estimatedCost},weekly:{key:week,used:state.weekly.used+estimatedCost},overridesUsed:state.overridesUsed+(decision.override?1:0),version:state.version+1};const value={schema:"golfriend.golf-api-quota-receipt.v2",commandId,estimatedCost,state:"reserved",actorDigest,operationPayloadDigest:payloadDigest,quotaDecisionDigest:decision.payloadDigest,month:m,dayKey:day,weekKey:week,overrideApprovalId:decision.approvalId,createdAt:now,expiresAt:now+state.reservationTtlMinutes*60000};tx.set(ref,next);tx.create(receipt,value);if(decision.override&&overrideRef)tx.update(overrideRef,{state:"consumed",consumedAt:now,receiptId});return{month:m,receiptId,estimatedCost,dayKey:day,weekKey:week,replay:false};});}
async function settle(reservation:Reservation,outcome:"completed"|"failed",actualCost:number,result:unknown){const qref=db.collection("golf_api_quota").doc(reservation.month),rref=db.collection("golf_api_quota_receipts").doc(reservation.receiptId);await db.runTransaction(async tx=>{const [q,r]=await Promise.all([tx.get(qref),tx.get(rref)]);if(!q.exists||!r.exists)throw new HttpsError("failed-precondition","RESERVATION_MISSING");const receipt=r.data()!;if(receipt.state!=="reserved")return;const next=reconcileQuota(q.data() as QuotaState,{estimatedCost:receipt.estimatedCost,dayKey:receipt.dayKey,weekKey:receipt.weekKey},outcome,actualCost);tx.set(qref,next);tx.update(rref,{state:outcome,actualCost,result,settledAt:Date.now()});});}
async function provider(onAttempt:()=>void){const key=GOLF_API_KEY.value();if(Buffer.byteLength(key,"utf8")<24)throw new HttpsError("failed-precondition","PROVIDER_UNCONFIGURED");return createGolfApiPort({apiKey:key,request:async(path,headers)=>{onAttempt();const response=await fetch(`${PROVIDER_BASE}${path}`,{headers});let body:unknown=null;try{body=await response.json();}catch{body=null;}return{status:response.status,headers:{"x-request-id":response.headers.get("x-request-id")||undefined,"x-ratelimit-limit":response.headers.get("x-ratelimit-limit")||undefined,"x-ratelimit-remaining":response.headers.get("x-ratelimit-remaining")||undefined,"x-ratelimit-reset":response.headers.get("x-ratelimit-reset")||undefined},body};}});}

export const getCourseAcquisitionDashboard=onCall(BASE_OPTIONS,async request=>{const uid=context(request);await staff(uid,Object.values(ROLE));const [quota,candidates,courses]=await Promise.all([db.collection("golf_api_quota").doc(month()).get(),db.collection("course_acquisition_candidates").limit(100).get(),db.collection("courses").limit(500).get()]);const coverage=new Map<string,{country:string;canonical:number;active:number;fresh:number;missingCoordinates:number}>();courses.docs.forEach(doc=>{const c=doc.data();if(c.schema!=="golfriend.v2.course.v2")return;const country=String(c.country||"Unknown"),row=coverage.get(country)||{country,canonical:0,active:0,fresh:0,missingCoordinates:0};row.canonical++;if(c.verified===true&&c.needsReview!==true)row.active++;if(Number(c.updatedAt)>Date.now()-90*86400000)row.fresh++;if(!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude))row.missingCoordinates++;coverage.set(country,row);});const q=quota.data();return{schema:"golfriend.course-acquisition-dashboard.v1",quota:quota.exists?{schema:q?.schema,month:q?.month,configuredBudget:q?.configuredBudget,emergencyReserve:q?.emergencyReserve,reserved:q?.reserved,completed:q?.completed,failed:q?.failed,released:q?.released,dailyLimit:q?.dailyLimit,weeklyLimit:q?.weeklyLimit,version:q?.version}:null,candidateCounts:candidates.docs.reduce((a,d)=>{const s=String(d.data().workflowStatus||d.data().status||"unknown");a[s]=(a[s]||0)+1;return a;},{} as Record<string,number>),countries:[...coverage.values()].sort((a,b)=>a.country.localeCompare(b.country)),candidates:candidates.docs.map(d=>{const c=d.data();return{candidateId:d.id,status:c.workflowStatus??c.status,name:c.name,city:c.city??null,country:c.country,coordinatesStatus:c.coordinatesStatus,sourceUpdatedAt:c.sourceUpdatedAt,reviewRequired:c.reviewRequired,reviewDecisionId:c.reviewDecisionId??null};})};});

export const previewCourseAcquisitionPlan=onCall(BASE_OPTIONS,async request=>{const uid=context(request);await staff(uid,[ROLE.viewer,ROLE.operator,ROLE.reviewer,ROLE.approver]);const data=exact(request.data??{},["coverage","manual"]);const quota=await db.collection("golf_api_quota").doc(month()).get();if(!quota.exists)throw new HttpsError("failed-precondition","QUOTA_UNCONFIGURED");const raw=quota.data() as QuotaState,state=validateQuotaState({...raw,enabled:true},month(),dayKey(),weekKey());return planAcquisition({coverage:Array.isArray(data.coverage)?data.coverage as any[]:[],manual:Array.isArray(data.manual)?data.manual as any[]:[],remainingBudget:state.configuredBudget-state.emergencyReserve-state.reserved-state.completed-state.failed});});

export const acquireCourseCandidates=onCall({...BASE_OPTIONS,secrets:[GOLF_API_KEY]},async request=>{
  const uid=context(request);await staff(uid,[ROLE.operator]);
  const data=exact(request.data,["commandId","country","city","approved","overrideApprovalId"]);
  if(data.approved!==true)throw new HttpsError("failed-precondition","EXPLICIT_APPROVAL_REQUIRED");
  const commandId=String(data.commandId||""),operation={country:String(data.country||"").normalize("NFKC").trim(),city:data.city?String(data.city).normalize("NFKC").trim():null},reservation=await reserve(uid,commandId,1,operation,data.overrideApprovalId?String(data.overrideApprovalId):undefined);
  if(reservation.replay)return reservation.result;
  const attemptRef=db.collection("course_provider_attempts").doc(reservation.receiptId);let attempted=false;
  try{
    await attemptRef.create({schema:"golfriend.course-provider-attempt.v1",receiptId:reservation.receiptId,month:reservation.month,state:"dispatching",createdAt:Date.now()});
    const providerPort=await provider(()=>{attempted=true;});await attemptRef.update({state:"provider_attempted",dispatchAt:Date.now()});attempted=true;
    const providerResult=await providerPort.search({country:operation.country,city:operation.city??undefined});
    const canonical=await db.collection("courses").limit(500).get();
    for(const raw of providerResult.items){
      const candidate=canonicalize(raw,commandId,Date.now()),candidateRef=db.collection("course_acquisition_candidates").doc(candidate.candidateId),evidenceRef=db.collection("course_provider_evidence").doc(candidate.candidateId),duplicate=duplicateSignals(candidate,canonical.docs.map(d=>({courseID:d.id,...d.data()})));
      await db.runTransaction(async tx=>{const [priorCandidate,priorEvidence]=await Promise.all([tx.get(candidateRef),tx.get(evidenceRef)]);let decision;try{decision=acquisitionWriteDecision(priorCandidate.data(),priorEvidence.data(),candidate);}catch{throw new HttpsError("already-exists","CANDIDATE_ID_CONFLICT");}if(decision.state==='replay')return;tx.create(candidateRef,{...candidate,candidateAuthorityDigest:decision.candidateDigest,duplicateSignals:duplicate,createdAt:Date.now(),createdByDigest:digest(["course-acquisition-actor",uid])});tx.create(evidenceRef,{schema:"golfriend.course-provider-evidence.v1",candidateId:candidate.candidateId,evidenceDigest:candidate.providerEvidenceDigest,providerRequestDigest:digest(raw.providerRequestId),recordedAt:Date.now()});});
    }
    const result={schema:"golfriend.course-acquisition-result.v1",state:"candidate_created",count:providerResult.items.length,quota:providerResult.quota};
    await attemptRef.update({state:"result_persisted",candidateCount:providerResult.items.length,completedAt:Date.now()});await settle(reservation,"completed",1,result);return result;
  }catch(error){const result={schema:"golfriend.course-acquisition-result.v1",state:"failed"},remove=admin.firestore.FieldValue.delete();await attemptRef.set({schema:"golfriend.course-provider-attempt.v1",receiptId:reservation.receiptId,month:reservation.month,state:attempted?"provider_attempted":"not_dispatched",dispatchAt:attempted?Date.now():remove,candidateCount:remove,completedAt:remove,updatedAt:Date.now()},{merge:true});await settle(reservation,"failed",attempted?1:0,result);throw new HttpsError("unavailable",error instanceof Error?error.message:"PROVIDER_FAILED");}
});

export const decideCourseCandidate=onCall(BASE_OPTIONS,async request=>{const uid=context(request),actor=await staff(uid,[ROLE.reviewer]);const data=exact(request.data,["candidateId","action","fieldChoices","commandId"]),candidateRef=db.collection("course_acquisition_candidates").doc(String(data.candidateId||"")),reviewRef=db.collection("course_acquisition_reviews").doc(String(data.commandId||""));await db.runTransaction(async tx=>{const [candidateSnap,prior]=await Promise.all([tx.get(candidateRef),tx.get(reviewRef)]);if(!candidateSnap.exists)throw new HttpsError("not-found","CANDIDATE_UNAVAILABLE");const decision=reviewDecision({candidate:candidateSnap.data(),action:data.action as any,fieldChoices:data.fieldChoices as any,reviewerId:uid,commandId:String(data.commandId||"")});if(prior.exists){if(prior.data()?.requestDigest!==decision.requestDigest)throw new HttpsError("already-exists","COMMAND_REUSED");return;}tx.create(reviewRef,{...decision,reviewerRole:actor.role,createdAt:Date.now()});tx.update(candidateRef,{workflowStatus:data.action==="reject"?"rejected":"reviewed",reviewDecisionId:decision.commandId});});return{schema:"golfriend.course-review-result.v1",state:"recorded",candidateId:data.candidateId};});

export const publishCourseCandidate=onCall(BASE_OPTIONS,async request=>{const uid=context(request),actor=await staff(uid,[ROLE.approver]);const data=exact(request.data,["candidateId","decisionId","commandId","confirmed"]);if(data.confirmed!==true)throw new HttpsError("failed-precondition","EXPLICIT_CONFIRMATION_REQUIRED");const actorDigest=digest(["course-publication-actor",uid]),requestDigest=digest({candidateId:data.candidateId,decisionId:data.decisionId,commandId:data.commandId,confirmed:true,actorDigest}),candidateRef=db.collection("course_acquisition_candidates").doc(String(data.candidateId)),decisionRef=db.collection("course_acquisition_reviews").doc(String(data.decisionId)),receiptRef=db.collection("course_publication_receipts").doc(String(data.commandId));let result:any=null;await db.runTransaction(async tx=>{const [candidateSnap,decisionSnap,prior]=await Promise.all([tx.get(candidateRef),tx.get(decisionRef),tx.get(receiptRef)]);if(!candidateSnap.exists||!decisionSnap.exists)throw new HttpsError("not-found","REVIEW_UNAVAILABLE");const canonical=publishCanonical(candidateSnap.data(),decisionSnap.data(),{uid,role:actor.role},Date.now());if(prior.exists){if(prior.data()?.requestDigest!==requestDigest)throw new HttpsError("already-exists","COMMAND_REUSED");result={schema:"golfriend.course-publication-result.v1",state:"published",courseId:prior.data()?.courseId,publicationDigest:prior.data()?.publicationDigest};return;}const courseRef=db.collection("courses").doc(canonical.courseID),existing=await tx.get(courseRef);if(existing.exists)throw new HttpsError("failed-precondition","CANONICAL_TARGET_EXISTS");const versioned={...canonical,publicationVersion:1,publicationDigest:digest([canonical,1,null])};tx.create(courseRef,versioned);tx.create(receiptRef,{schema:"golfriend.course-publication-receipt.v1",commandId:data.commandId,candidateId:data.candidateId,decisionId:data.decisionId,actorDigest,requestDigest,courseId:versioned.courseID,publicationVersion:1,beforeDigest:null,publicationDigest:versioned.publicationDigest,createdAt:Date.now()});tx.update(candidateRef,{workflowStatus:"published",publicationDigest:versioned.publicationDigest});result={schema:"golfriend.course-publication-result.v1",state:"published",courseId:versioned.courseID,publicationDigest:versioned.publicationDigest};});return result;});

export const submitCourseCorrectionRequest=onCall(BASE_OPTIONS,async request=>{const uid=context(request),partner=await db.collection("b2b_partners").doc(uid).get();if(!partner.exists||partner.data()?.status!=="active_partner")throw new HttpsError("permission-denied","ACTIVE_PARTNER_REQUIRED");const data=exact(request.data,["canonicalCourseId","claimedRelationship","proposedCorrection","evidenceReference","locale","consent","contactPreference","commandId"]),value=correctionRequest(data);if(value.state!=="submitted")throw new HttpsError("invalid-argument","CORRECTION_INVALID");const commandId=String(data.commandId||""),requestId=`corr_${digest(["course-correction",uid,commandId]).slice(0,32)}`,ref=db.collection("course_correction_requests").doc(requestId),payloadDigest=digest(value);await db.runTransaction(async tx=>{const prior=await tx.get(ref);if(prior.exists){if(prior.data()?.payloadDigest!==payloadDigest)throw new HttpsError("already-exists","COMMAND_REUSED");return;}tx.create(ref,{...value,requestId,payloadDigest,createdAt:Date.now()});});return{schema:value.schema,state:value.state,requestId,canonicalMutation:false};});

export const approveCourseQuotaOverride=onCall(BASE_OPTIONS,async request=>{const uid=context(request);await staff(uid,[ROLE.override]);const data=exact(request.data,["approvalId","maxCalls","reason","expiresAt"]),approvalId=String(data.approvalId||"").normalize("NFKC").trim(),reason=String(data.reason||"").normalize("NFKC").trim(),maxCalls=Number(data.maxCalls),expiresAt=Number(data.expiresAt),now=Date.now(),quota=await db.collection("golf_api_quota").doc(month()).get();if(!quota.exists)throw new HttpsError("failed-precondition","QUOTA_UNCONFIGURED");const state=validateQuotaState(quota.data() as QuotaState,month(),dayKey(),weekKey());if(!/^[A-Za-z0-9_-]{8,120}$/.test(approvalId)||!reason||reason.length>500||/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/.test(reason)||!Number.isInteger(maxCalls)||maxCalls<1||maxCalls>state.maxOverrideCalls||!Number.isFinite(expiresAt)||expiresAt<=now||expiresAt>now+60*60000)throw new HttpsError("invalid-argument","OVERRIDE_INVALID");const ref=db.collection("golf_api_quota_overrides").doc(approvalId),value={schema:"golfriend.golf-api-quota-override.v1",state:"approved",approvalId,maxCalls,reasonDigest:digest(reason),approvedByDigest:digest(["course-acquisition-actor",uid]),createdAt:now,expiresAt,month:month()};await ref.create(value);return{schema:value.schema,state:value.state,approvalId,maxCalls,expiresAt};});

export const reconcileExpiredCourseReservation=onCall(BASE_OPTIONS,async request=>{const uid=context(request);await staff(uid,[ROLE.override]);const data=exact(request.data,["month","commandId","confirmed"]);if(data.confirmed!==true)throw new HttpsError("failed-precondition","EXPLICIT_CONFIRMATION_REQUIRED");const m=String(data.month||""),commandId=String(data.commandId||""),receiptId=digest([m,commandId]).slice(0,40),qref=db.collection("golf_api_quota").doc(m),rref=db.collection("golf_api_quota_receipts").doc(receiptId),attemptRef=db.collection("course_provider_attempts").doc(receiptId);await db.runTransaction(async tx=>{const [q,r,attempt]=await Promise.all([tx.get(qref),tx.get(rref),tx.get(attemptRef)]);if(!q.exists||!r.exists||r.data()?.state!=="reserved"||Number(r.data()?.expiresAt)>Date.now())throw new HttpsError("failed-precondition","RESERVATION_NOT_RECONCILABLE");const receipt=r.data()!;let evidence={state:"absent",actualCost:0};if(attempt.exists){try{evidence=validateProviderAttemptEvidence(attempt.data(),{receiptId,month:m});}catch{throw new HttpsError("failed-precondition","PROVIDER_EVIDENCE_MALFORMED");}}const actualCost=evidence.actualCost,outcome=actualCost===0?"released":"failed",next=reconcileQuota(q.data() as QuotaState,{estimatedCost:receipt.estimatedCost,dayKey:receipt.dayKey,weekKey:receipt.weekKey},outcome,actualCost);tx.set(qref,next);tx.update(rref,{state:outcome,actualCost,providerEvidenceState:evidence.state,reconciledByDigest:digest(["course-acquisition-actor",uid]),reconciledAt:Date.now()});});return{schema:"golfriend.golf-api-quota-reconciliation.v1",state:"reconciled",receiptId};});
