import {defineSecret} from "firebase-functions/params";
import {HttpsError, onCall} from "firebase-functions/v2/https";
import * as admin from "firebase-admin";
import {isActiveStaff} from "./authority.js";
import {canonicalize, createGolfApiPort, digest, duplicateSignals, planAcquisition, publishCanonical, quotaDecision, reconcileQuota, reviewDecision, correctionRequest, type QuotaState} from "./courseAcquisitionDomain.js";

if (!admin.apps.length) admin.initializeApp();
const db=admin.firestore();
const GOLF_API_KEY=defineSecret("GOLF_API_KEY");
const PROVIDER_BASE="https://www.golfapi.io/api/v2.3";
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=="object"||Array.isArray(value)||Object.keys(value as object).some((key)=>!keys.includes(key)))throw new HttpsError("invalid-argument","REQUEST_INVALID");return value as Record<string,unknown>;};
async function staff(uid:string){const snap=await db.collection("admin_users").doc(uid).get();if(!snap.exists||!isActiveStaff(snap.data()))throw new HttpsError("permission-denied","STAFF_REQUIRED");return snap.data() as {role:string};}
function context(request:any){if(!request.auth?.uid)throw new HttpsError("unauthenticated","AUTH_REQUIRED");if(typeof request.app?.appId!=="string"||!request.app.appId.trim())throw new HttpsError("failed-precondition","APP_CHECK_REQUIRED");return request.auth.uid as string;}
function month(at=new Date()){return at.toISOString().slice(0,7);}
async function reserve(uid:string,commandId:string,estimatedCost:number){const ref=db.collection("golf_api_quota").doc(month());const receipt=db.collection("golf_api_quota_receipts").doc(digest([month(),commandId]).slice(0,40));return db.runTransaction(async tx=>{const prior=await tx.get(receipt);if(prior.exists){const data=prior.data()!;if(data.commandId!==commandId||data.estimatedCost!==estimatedCost)throw new HttpsError("already-exists","COMMAND_REUSED");return data;}const snap=await tx.get(ref),state=snap.data() as QuotaState|undefined;if(!state)throw new HttpsError("failed-precondition","QUOTA_UNCONFIGURED");let decision;try{decision=quotaDecision(state,{commandId,estimatedCost,dailyUsed:Number(state.completed)||0,weeklyUsed:Number(state.completed)||0});}catch(e){throw new HttpsError("resource-exhausted",e instanceof Error?e.message:"QUOTA_DENIED");}const next={...state,reserved:state.reserved+estimatedCost,version:state.version+1};const value={schema:"golfriend.golf-api-quota-receipt.v1",commandId,estimatedCost,state:"reserved",actorDigest:digest(uid).slice(0,24),payloadDigest:decision.payloadDigest,createdAt:Date.now()};tx.set(ref,next);tx.create(receipt,value);return value;});}
async function settle(commandId:string,outcome:"completed"|"failed",actualCost:number){const qref=db.collection("golf_api_quota").doc(month()),rref=db.collection("golf_api_quota_receipts").doc(digest([month(),commandId]).slice(0,40));await db.runTransaction(async tx=>{const [q,r]=await Promise.all([tx.get(qref),tx.get(rref)]);if(!q.exists||!r.exists)throw new HttpsError("failed-precondition","RESERVATION_MISSING");const receipt=r.data()!;if(receipt.state!=="reserved")return;const next=reconcileQuota(q.data() as QuotaState,{estimatedCost:receipt.estimatedCost},outcome,actualCost);tx.set(qref,next);tx.update(rref,{state:outcome,actualCost,settledAt:Date.now()});});}
async function provider(onAttempt:()=>void){const key=GOLF_API_KEY.value();return createGolfApiPort({apiKey:key,request:async(path,headers)=>{onAttempt();const response=await fetch(`${PROVIDER_BASE}${path}`,{headers});let body:unknown=null;try{body=await response.json();}catch{body=null;}return{status:response.status,headers:{"x-request-id":response.headers.get("x-request-id")||undefined,"x-ratelimit-limit":response.headers.get("x-ratelimit-limit")||undefined,"x-ratelimit-remaining":response.headers.get("x-ratelimit-remaining")||undefined,"x-ratelimit-reset":response.headers.get("x-ratelimit-reset")||undefined},body};}});}

export const getCourseAcquisitionDashboard=onCall({enforceAppCheck:true},async request=>{const uid=context(request);await staff(uid);const [quota,candidates,courses]=await Promise.all([db.collection("golf_api_quota").doc(month()).get(),db.collection("course_acquisition_candidates").limit(100).get(),db.collection("courses").limit(500).get()]);const coverage=new Map<string,{country:string;canonical:number;active:number;fresh:number;missingCoordinates:number}>();courses.docs.forEach(doc=>{const c=doc.data();if(c.schema!=="golfriend.v2.course.v2")return;const country=String(c.country||"Unknown"),row=coverage.get(country)||{country,canonical:0,active:0,fresh:0,missingCoordinates:0};row.canonical++;if(c.verified===true&&c.needsReview!==true)row.active++;if(Number(c.updatedAt)>Date.now()-90*86400000)row.fresh++;if(!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude))row.missingCoordinates++;coverage.set(country,row);});const q=quota.data();return{schema:"golfriend.course-acquisition-dashboard.v1",quota:quota.exists?{schema:q?.schema,month:q?.month,configuredBudget:q?.configuredBudget,emergencyReserve:q?.emergencyReserve,reserved:q?.reserved,completed:q?.completed,failed:q?.failed,released:q?.released,dailyLimit:q?.dailyLimit,weeklyLimit:q?.weeklyLimit,version:q?.version}:null,candidateCounts:candidates.docs.reduce((a,d)=>{const s=String(d.data().status||"unknown");a[s]=(a[s]||0)+1;return a;},{} as Record<string,number>),countries:[...coverage.values()].sort((a,b)=>a.country.localeCompare(b.country)),candidates:candidates.docs.map(d=>{const c=d.data();return{candidateId:d.id,status:c.status,name:c.name,city:c.city??null,country:c.country,coordinatesStatus:c.coordinatesStatus,sourceUpdatedAt:c.sourceUpdatedAt,reviewRequired:c.reviewRequired,reviewDecisionId:c.reviewDecisionId??null};})};});

export const previewCourseAcquisitionPlan=onCall({enforceAppCheck:true},async request=>{const uid=context(request);await staff(uid);const data=exact(request.data??{},["coverage","manual"]);const quota=await db.collection("golf_api_quota").doc(month()).get();if(!quota.exists)throw new HttpsError("failed-precondition","QUOTA_UNCONFIGURED");const state=quota.data() as QuotaState;return planAcquisition({coverage:Array.isArray(data.coverage)?data.coverage as any[]:[],manual:Array.isArray(data.manual)?data.manual as any[]:[],remainingBudget:state.configuredBudget-state.emergencyReserve-state.reserved-state.completed-state.failed+state.released});});

export const acquireCourseCandidates=onCall({enforceAppCheck:true,secrets:[GOLF_API_KEY]},async request=>{const uid=context(request);await staff(uid);const data=exact(request.data,["commandId","country","city","approved"]);if(data.approved!==true)throw new HttpsError("failed-precondition","EXPLICIT_APPROVAL_REQUIRED");const commandId=String(data.commandId||"");await reserve(uid,commandId,1);let attempted=false;try{const result=await(await provider(()=>{attempted=true;})).search({country:String(data.country||""),city:data.city?String(data.city):undefined});const canonical=await db.collection("courses").limit(500).get();const batch=db.batch();for(const raw of result.items){const candidate=canonicalize(raw,commandId,Date.now());const duplicate=duplicateSignals(candidate,canonical.docs.map(d=>({courseID:d.id,...d.data()})));batch.set(db.collection("course_acquisition_candidates").doc(candidate.candidateId),{...candidate,duplicateSignals:duplicate,createdAt:Date.now(),createdByDigest:digest(uid).slice(0,24)});batch.set(db.collection("course_provider_evidence").doc(candidate.candidateId),{schema:"golfriend.course-provider-evidence.v1",candidateId:candidate.candidateId,evidenceDigest:candidate.providerEvidenceDigest,providerRequestDigest:digest(raw.providerRequestId),recordedAt:Date.now()});}await batch.commit();await settle(commandId,"completed",1);return{schema:"golfriend.course-acquisition-result.v1",state:"candidate_created",count:result.items.length,quota:result.quota};}catch(error){await settle(commandId,"failed",attempted?1:0);throw new HttpsError("unavailable",error instanceof Error?error.message:"PROVIDER_FAILED");}});

export const decideCourseCandidate=onCall({enforceAppCheck:true},async request=>{const uid=context(request),actor=await staff(uid);const data=exact(request.data,["candidateId","action","fieldChoices","commandId"]),candidateRef=db.collection("course_acquisition_candidates").doc(String(data.candidateId||"")),reviewRef=db.collection("course_acquisition_reviews").doc(String(data.commandId||""));await db.runTransaction(async tx=>{const [candidateSnap,prior]=await Promise.all([tx.get(candidateRef),tx.get(reviewRef)]);if(!candidateSnap.exists)throw new HttpsError("not-found","CANDIDATE_UNAVAILABLE");const decision=reviewDecision({candidate:candidateSnap.data(),action:data.action as any,fieldChoices:data.fieldChoices as any,reviewerId:uid,commandId:String(data.commandId||"")});if(prior.exists){if(prior.data()?.candidateDigest!==decision.candidateDigest||prior.data()?.action!==decision.action)throw new HttpsError("already-exists","COMMAND_REUSED");return;}tx.create(reviewRef,{...decision,reviewerRole:actor.role,createdAt:Date.now()});tx.update(candidateRef,{status:data.action==="reject"?"rejected":"reviewed",reviewDecisionId:decision.commandId});});return{schema:"golfriend.course-review-result.v1",state:"recorded",candidateId:data.candidateId};});

export const publishCourseCandidate=onCall({enforceAppCheck:true},async request=>{const uid=context(request),actor=await staff(uid);const data=exact(request.data,["candidateId","decisionId","commandId","confirmed"]);if(data.confirmed!==true)throw new HttpsError("failed-precondition","EXPLICIT_CONFIRMATION_REQUIRED");const candidateRef=db.collection("course_acquisition_candidates").doc(String(data.candidateId)),decisionRef=db.collection("course_acquisition_reviews").doc(String(data.decisionId)),receiptRef=db.collection("course_publication_receipts").doc(String(data.commandId));let result:any=null;await db.runTransaction(async tx=>{const [candidateSnap,decisionSnap,prior]=await Promise.all([tx.get(candidateRef),tx.get(decisionRef),tx.get(receiptRef)]);if(!candidateSnap.exists||!decisionSnap.exists)throw new HttpsError("not-found","REVIEW_UNAVAILABLE");const canonical=publishCanonical(candidateSnap.data(),decisionSnap.data(),{uid,role:actor.role},Date.now());if(prior.exists){if(prior.data()?.candidateId!==data.candidateId)throw new HttpsError("already-exists","COMMAND_REUSED");result={schema:"golfriend.course-publication-result.v1",state:"published",courseId:prior.data()?.courseId,publicationDigest:prior.data()?.publicationDigest};return;}const courseRef=db.collection("courses").doc(canonical.courseID),existing=await tx.get(courseRef);if(existing.exists&&Number(existing.data()?.sourceUpdatedAt)>=canonical.sourceUpdatedAt)throw new HttpsError("failed-precondition","STALE_SOURCE_OVERWRITE_DENIED");const version=(Number(existing.data()?.publicationVersion)||0)+1,beforeDigest=existing.exists?digest(existing.data()):null,versioned={...canonical,publicationVersion:version,publicationDigest:digest([canonical,version,beforeDigest])};tx.set(courseRef,versioned);tx.create(receiptRef,{schema:"golfriend.course-publication-receipt.v1",commandId:data.commandId,candidateId:data.candidateId,courseId:versioned.courseID,publicationVersion:version,beforeDigest,publicationDigest:versioned.publicationDigest,createdAt:Date.now()});tx.update(candidateRef,{status:"published",publicationDigest:versioned.publicationDigest});result={schema:"golfriend.course-publication-result.v1",state:"published",courseId:versioned.courseID,publicationDigest:versioned.publicationDigest};});return result;});

export const submitCourseCorrectionRequest=onCall({enforceAppCheck:true},async request=>{const uid=context(request);const value=correctionRequest(exact(request.data,["canonicalCourseId","claimedRelationship","proposedCorrection","evidenceReference","locale","consent","contactPreference"]));if(value.state!=="submitted")throw new HttpsError("invalid-argument","CORRECTION_INVALID");await db.collection("course_correction_requests").doc(value.requestId).create({...value,submitterDigest:digest(uid).slice(0,24),createdAt:Date.now()});return{schema:value.schema,state:value.state,requestId:value.requestId,canonicalMutation:false};});
