import assert from "node:assert";
import {readFileSync} from "node:fs";
import {distanceKm, inspectClubRegion, MAX_INSPECTED_CLUBS, MAX_INSPECTED_COURSES, normalizeClubInspectionInput} from "./courseInspection.js";

let passed=0;
async function check(name:string, run:()=>void|Promise<void>){await run();passed++;console.log(`  ✓ ${name}`);}
const input=normalizeClubInspectionInput({latitude:12.9236,longitude:100.8825,radiusKm:50,searchText:"Siam"});

async function main(){
  await check("invalid coordinates and radius are refused",()=>{assert.throws(()=>normalizeClubInspectionInput({latitude:91,longitude:100,radiusKm:50}),/INVALID_COORDINATES/);assert.throws(()=>normalizeClubInspectionInput({latitude:12,longitude:100,radiusKm:201}),/INVALID_RADIUS/);});
  await check("returns only explicit bounded club authority facts",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club"}]}:{data:{clubID:"club_1",clubName:"Siam Provider Club",address:"1 Fairway",address2:"Building B",postalCode:"20150",city:"Pattaya",country:"Thailand",phone:"123",mobile:"456",email:"book@example.test",website:"https://club.example.test",bookingUrl:"https://club.example.test/book",teeTimeUrl:"https://club.example.test/tee-times",propertyID:"property_1",isBookable:true,booking:{url:"https://club.example.test/book",email:"booking@example.test",phone:"789",providerId:"booking_1",token:"hidden"},latitude:12.93,longitude:100.88,courses:[{courseID:"layout_1",courseName:"Layout One",clubID:"club_1",geometry:{type:"Polygon"}}]}});const club:any=result.clubs[0];assert.equal(club.providerClubId,"club_1");assert.equal(club.providerClubName,"Siam Provider Club");assert.equal(club.address,"1 Fairway");assert.equal(club.address2,"Building B");assert.equal(club.postalCode,"20150");assert.equal(club.bookingUrl,"https://club.example.test/book");assert.equal(club.teeTimeUrl,"https://club.example.test/tee-times");assert.equal(club.providerBookingStructures.booking.email,"booking@example.test");assert.equal(club.providerPropertyId,"property_1");assert.equal(club.providerBookable,true);assert.equal(club.phone,"123");assert.equal(club.courses[0].providerClubId,"club_1");assert.equal(club.courses[0].providerCourseName,"Layout One");assert.equal(club.courses[0].geometryAvailable,true);});
  await check("missing authority and parent fields are null rather than synthesized",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club"}]}:{data:{clubID:"club_1",clubName:"Siam Provider Club",courses:[{courseID:"layout_1",courseName:"Sugar Cane"}]}});const club:any=result.clubs[0];assert.equal(club.address,null);assert.equal(club.reservationUrl,null);assert.equal(club.providerParentId,null);assert.equal(club.courses[0].providerParentId,null);assert.equal(club.courses[0].providerClubId,"club_1");assert.doesNotMatch(JSON.stringify(club),/Plantation/);});
  await check("course rows cannot override club booking authority",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club"}]}:{data:{clubID:"club_1",clubName:"Siam Provider Club",bookingUrl:"https://club.example.test/book",courses:[{courseID:"layout_1",courseName:"Layout One",bookingUrl:"https://layout.example.test/book",reservationEmail:"layout@example.test"}]}});const club:any=result.clubs[0];assert.equal(club.bookingUrl,"https://club.example.test/book");assert.doesNotMatch(JSON.stringify(club.courses[0]),/layout\.example|layout@example/);});
  await check("list shell expands provider layouts without name-based hierarchy inference",async()=>{const paths:string[]=[];const result=await inspectClubRegion(input,async path=>{paths.push(path);return path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club"}]}:{data:{clubID:"club_1",clubName:"Siam Provider Club",courses:[{courseID:"layout_1",courseName:"Sugar Cane"},{courseID:"layout_2",courseName:"Tapioca"}]}};});assert.deepEqual(paths,["/clubs?lat=12.9236&lng=100.8825&radius=50","/clubs/club_1"]);assert.deepEqual((result.clubs[0].detailAddedCourseIDs as unknown[]),["layout_1","layout_2"]);assert.deepEqual((result.clubs[0].courses as Array<{providerCourseId:string}>).map(course=>course.providerCourseId),["layout_1","layout_2"]);});
  await check("independent Haversine filtering rejects Seoul-distance coordinates",async()=>{const seoulDistance=distanceKm(input,14.733029,101.409471);assert.ok(seoulDistance!==null&&seoulDistance>50);const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_seoul",clubName:"Siam Remote",latitude:14.733029,longitude:101.409471}]}:{data:{clubID:"club_seoul",clubName:"Siam Remote",latitude:14.733029,longitude:101.409471,courses:[]}});assert.equal(result.clubs[0].withinRequestedRadius,false);assert.equal(result.clubs[0].within50Km,false);});
  await check("independent Haversine filtering accepts Pattaya-distance coordinates",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_pattaya",clubName:"Siam Local",latitude:12.909432,longitude:101.008623}]}:{data:{clubID:"club_pattaya",clubName:"Siam Local",latitude:12.909432,longitude:101.008623,courses:[]}});assert.equal(result.clubs[0].withinRequestedRadius,true);assert.equal(result.clubs[0].within50Km,true);assert.ok(Number(result.clubs[0].distanceKm)<50);});
  await check("provider absence creates no synthetic row",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club"}]}:{data:{clubID:"club_1",courses:[]}});assert.deepEqual(result.clubs[0].courses,[]);assert.deepEqual(result.clubs[0].detailAddedCourseIDs,[]);});
  await check("result caps provider dump",async()=>{const result=await inspectClubRegion(normalizeClubInspectionInput({latitude:1,longitude:2,radiusKm:1}),async path=>path.startsWith("/clubs?")?{clubs:Array.from({length:MAX_INSPECTED_CLUBS+2},(_,i)=>({clubID:`club_${i}`,clubName:`Club ${i}`}))}:{courses:Array.from({length:MAX_INSPECTED_COURSES+2},(_,i)=>({courseID:`course_${i}`}))});assert.equal(result.clubs.length,MAX_INSPECTED_CLUBS);assert.equal(result.summary.coursesReturned,MAX_INSPECTED_COURSES);assert.equal((result.clubs[0].detailAddedCourseIDs as unknown[]).length,MAX_INSPECTED_COURSES);assert.equal((result.clubs.slice(1).flatMap(club=>(club.detailAddedCourseIDs as unknown[]))).length,0);});
  await check("callable refuses unauthenticated and unauthorized callers, enables App Check, binds the secret, and has no Firestore write",()=>{const source=readFileSync("src/courseIngestion.ts","utf8");const start=source.indexOf("export const inspectGolfApiClubRegion");const body=source.slice(start,source.indexOf("export const previewCourseClubhouseReconciliation",start));assert.match(body,/unauthenticated/);assert.match(body,/enforceAppCheck:\s*true/);assert.match(body,/secrets:\s*\[GOLF_API_KEY\]/);assert.match(body,/requireCoordinator\(request\.auth\.uid\)/);assert.doesNotMatch(body,/\.set\(|\.create\(|\.update\(|\.batch\(|runTransaction|collection\("courses"/);});
  await check("inspection result excludes secret-like provider fields",async()=>{const result=await inspectClubRegion(input,async path=>path.startsWith("/clubs?")?{clubs:[{clubID:"club_1",clubName:"Siam Provider Club",authorization:"Bearer hidden",apiKey:"hidden"}]}:{data:{clubID:"club_1",booking:{token:"hidden",secret:"hidden"},courses:[{courseID:"layout_1",token:"hidden",secret:"hidden"}]}});assert.doesNotMatch(JSON.stringify(result),/authorization|bearer|token|secret|api.?key/i);});
  console.log(`course inspection: ${passed} checks passed.`);
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
