import assert from'node:assert/strict';import{canonicalize,correctionRequest,createGolfApiPort,duplicateSignals,planAcquisition,publishCanonical,quotaDecision,reconcileQuota,reviewDecision}from'./courseAcquisitionDomain.js';let passed=0;const check=async(name:string,fn:()=>unknown|Promise<unknown>)=>{await fn();passed++;console.log(`ok ${passed} - ${name}`)};const raw={providerCourseId:'p1',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,providerRequestId:'r1',sourceVersion:'v1',sourceUpdatedAt:'2026-08-14T00:00:00Z'};void(async()=>{
await check('provider adapter is injected bounded and credential required',async()=>{assert.throws(()=>createGolfApiPort({apiKey:'',request:async()=>({status:200,headers:{},body:{}})}),/UNCONFIGURED/);let path='';const port=createGolfApiPort({apiKey:'fixture-secret',request:async p=>(path=p,{status:200,headers:{'x-request-id':'r1'},body:{courses:[{courseID:'p1',courseName:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,updatedAt:'2026-08-14T00:00:00Z'}]}})});assert.equal((await port.search({country:'Thailand'})).items.length,1);assert.match(path,/country=Thailand/);});
await check('quota is configurable replay-ready paced and reconcilable',()=>{const state:any={schema:'golfriend.golf-api-quota.v1',month:'2026-08',configuredBudget:500,emergencyReserve:25,reserved:0,completed:0,failed:0,released:0,dailyLimit:30,weeklyLimit:120,version:1},r=quotaDecision(state,{commandId:'c1',estimatedCost:5,dailyUsed:0,weeklyUsed:0});assert.equal(r.remainingAfter,470);assert.equal(quotaDecision({...state,configuredBudget:100},{commandId:'c1',estimatedCost:5,dailyUsed:0,weeklyUsed:0}).remainingAfter,70);assert.equal(reconcileQuota({...state,reserved:5},r,'completed',3).released,2);assert.throws(()=>quotaDecision(state,{commandId:'x',estimatedCost:31,dailyUsed:0,weeklyUsed:0}),/PACING/);});
await check('planner is a true zero-call zero-write dry run',()=>{const p=planAcquisition({coverage:[{country:'TH',city:'Phuket',missingCoordinates:2,stale:0,demand:0}],manual:[],remainingBudget:50});assert.equal(p.providerCalls,0);assert.equal(p.writes,0);assert.equal(p.estimatedCalls,1);});
await check('canonicalization detects duplicates and never auto merges',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),signals:any=duplicateSignals(c,[{courseID:'existing',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7.001,longitude:98.001,source:{sourceCourseId:'other'}}]);assert.equal(signals[0].automaticMerge,false);assert.ok(signals[0].reasons.includes('name_city_country'));});
await check('publication requires separation of duties and exact reviewed digest',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),d=reviewDecision({candidate:c,action:'confirm_new',reviewerId:'reviewer',commandId:'cmd1'});assert.throws(()=>publishCanonical(c,d,{uid:'reviewer',role:'course_catalogue_approver'},Date.now()),/DENIED/);const out=publishCanonical(c,d,{uid:'approver',role:'course_catalogue_approver'},Date.parse('2026-08-15T00:00:00Z'));assert.equal(out.schema,'golfriend.v2.course.v2');assert.equal(out.verified,true);assert.equal(out.needsReview,false);});
await check('portal correction is request-only and cannot mutate canonical data',()=>{const r:any=correctionRequest({canonicalCourseId:'c1',claimedRelationship:'operator',proposedCorrection:'Correct city',evidenceReference:'evidence-1',locale:'en',consent:true});assert.equal(r.state,'submitted');assert.equal(r.canonicalMutation,false);assert.equal(correctionRequest({...r,consent:false}).state,'rejected');});
await check('hostile provider fields and secrets never enter a candidate',async()=>{const port=createGolfApiPort({apiKey:'fixture-secret',request:async()=>({status:200,headers:{'x-request-id':'safe-request'},body:{courses:[{courseID:'p1',courseName:'Alpha',country:'Thailand',latitude:7,longitude:98,updatedAt:'2026-08-14T00:00:00Z',staffNote:'private',signedUrl:'https://private',apiKey:'leak'}]}})}),item=(await port.search({})).items[0]!,candidate:any=canonicalize(item,'job',Date.parse('2026-08-15T00:00:00Z')),serialized=JSON.stringify(candidate);assert.doesNotMatch(serialized,/staffNote|signedUrl|fixture-secret|apiKey/);assert.deepEqual(Object.keys(item).sort(),['city','country','latitude','longitude','name','providerCourseId','providerRequestId','sourceUpdatedAt','sourceVersion'].sort());});
await check('coordinate poisoning and bidi controls fail closed',async()=>{const bad=createGolfApiPort({apiKey:'fixture',request:async()=>({status:200,headers:{'x-request-id':'r'},body:{courses:[{courseID:'p',courseName:'Bad',country:'T\u202eH',latitude:91,longitude:1}]}})});await assert.rejects(()=>bad.search({}),/INVALID/);});
await check('quota replay identity is deterministic and override needs audit evidence',()=>{const state:any={schema:'golfriend.golf-api-quota.v1',month:'2026-08',configuredBudget:100,emergencyReserve:10,reserved:0,completed:89,failed:0,released:0,dailyLimit:1,weeklyLimit:1,version:1};const input={commandId:'same',estimatedCost:2,dailyUsed:50,weeklyUsed:50,override:{approved:true,approvalId:'audit-1'}},a=quotaDecision(state,input),b=quotaDecision(state,input);assert.equal(a.payloadDigest,b.payloadDigest);assert.equal(a.approvalId,'audit-1');assert.throws(()=>quotaDecision(state,{commandId:'x',estimatedCost:2,dailyUsed:50,weeklyUsed:50,override:{approved:true,approvalId:''}}),/PACING/);});
await check('publication contains only reviewed canonical authority and unknown commercial facts',()=>{const c=canonicalize(raw,'job1',Date.parse('2026-08-15T00:00:00Z')),d=reviewDecision({candidate:c,action:'confirm_new',reviewerId:'reviewer',commandId:'cmd1'}),out:any=publishCanonical(c,d,{uid:'approver',role:'course_catalogue_approver'},Date.parse('2026-08-15T00:00:00Z')),s=JSON.stringify(out);assert.equal(out.schema,'golfriend.v2.course.v2');assert.doesNotMatch(s,/price|rating|weather|teeTime|amenit|commission|booking/);});
console.log(`1..${passed}`);})();
