import assert from 'node:assert/strict';
import {acquisitionWriteDecision,canonicalize,reviewDecision,validateProviderAttemptEvidence,validateQuotaOverride} from './courseAcquisitionDomain.js';
let passed=0;const check=(name:string,fn:()=>void)=>{fn();passed++;console.log(`ok ${passed} - ${name}`)};
check('candidate acquisition is create-or-exact-replay and never revives workflow',()=>{const candidate:any=canonicalize({providerCourseId:'p1',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,providerRequestId:'r1',sourceVersion:'v1',sourceUpdatedAt:'2026-08-14T00:00:00Z'},'job1',Date.parse('2026-08-15T00:00:00Z')),created=acquisitionWriteDecision(null,null,candidate),stored={...candidate,candidateAuthorityDigest:created.candidateDigest,workflowStatus:'published',publicationDigest:'immutable'},evidence={evidenceDigest:candidate.providerEvidenceDigest};assert.equal(acquisitionWriteDecision(stored,evidence,candidate).state,'replay');assert.equal(stored.workflowStatus,'published');assert.throws(()=>acquisitionWriteDecision(stored,evidence,{...candidate,name:'Changed'}),/CONFLICT/);assert.throws(()=>acquisitionWriteDecision(stored,null,candidate),/CONFLICT/);});
check('quota override authority is exact month-bound and distinct',()=>{const now=1000,value={schema:'golfriend.golf-api-quota-override.v1',state:'approved',approvalId:'override-1',maxCalls:2,reasonDigest:'a'.repeat(64),approvedByDigest:'approver',createdAt:900,expiresAt:1500,month:'2026-08'};assert.equal(validateQuotaOverride(value,{approvalId:'override-1',month:'2026-08',operatorDigest:'operator',now,maxCalls:10}).approved,true);for(const bad of[{...value,month:'2026-09'},{...value,approvedByDigest:'operator'},{...value,extra:true},{...value,maxCalls:'2'}])assert.throws(()=>validateQuotaOverride(bad,{approvalId:'override-1',month:'2026-08',operatorDigest:'operator',now,maxCalls:10}),/OVERRIDE/);});
check('provider attempt evidence is exact and crash states reconcile conservatively',()=>{const common={schema:'golfriend.course-provider-attempt.v1',receiptId:'receipt-1',month:'2026-08',createdAt:100};assert.equal(validateProviderAttemptEvidence({...common,state:'dispatching'},{receiptId:'receipt-1',month:'2026-08'}).actualCost,0);assert.equal(validateProviderAttemptEvidence({...common,state:'provider_attempted',dispatchAt:110},{receiptId:'receipt-1',month:'2026-08'}).actualCost,1);assert.equal(validateProviderAttemptEvidence({...common,state:'result_persisted',dispatchAt:110,completedAt:120,candidateCount:1},{receiptId:'receipt-1',month:'2026-08'}).actualCost,1);for(const bad of [{...common,state:'not_dispatched'},{...common,state:'dispatching',receiptId:'other'},{...common,state:'dispatching',extra:true},{...common,state:'provider_attempted'}])assert.throws(()=>validateProviderAttemptEvidence(bad,{receiptId:'receipt-1',month:'2026-08'}),/MALFORMED/);});
check('provider evidence rejects contradictory known fields',()=>{const common={schema:'golfriend.course-provider-attempt.v1',receiptId:'receipt-1',month:'2026-08',createdAt:100};for(const bad of [{...common,state:'dispatching',dispatchAt:110},{...common,state:'not_dispatched',updatedAt:110,dispatchAt:105},{...common,state:'provider_attempted',dispatchAt:110,completedAt:120},{...common,state:'provider_attempted',dispatchAt:110,candidateCount:1}])assert.throws(()=>validateProviderAttemptEvidence(bad,{receiptId:'receipt-1',month:'2026-08'}),/MALFORMED/);});
check('review choices are merge-only bounded and exactly projected',()=>{const candidate:any=canonicalize({providerCourseId:'p1',name:'Alpha',city:'Phuket',country:'Thailand',latitude:7,longitude:98,providerRequestId:'r1',sourceVersion:'v1',sourceUpdatedAt:'2026-08-14T00:00:00Z'},'job1',Date.parse('2026-08-15T00:00:00Z')),merge=reviewDecision({candidate,action:'merge',fieldChoices:{name:'candidate',city:'canonical'},reviewerId:'reviewer',commandId:'merge-1'});assert.deepEqual(Object.keys(merge.fieldChoices),['city','name']);for(const fieldChoices of [{staffNote:'candidate'},{name:{nested:true}},{name:'other'},Object.fromEntries(Array.from({length:20},(_,i)=>[`x${i}`,'candidate']))])assert.throws(()=>reviewDecision({candidate,action:'merge',fieldChoices:fieldChoices as any,reviewerId:'reviewer',commandId:'merge-2'}));assert.throws(()=>reviewDecision({candidate,action:'confirm_new',fieldChoices:{} as any,reviewerId:'reviewer',commandId:'confirm-1'}));});
console.log(`1..${passed}`);
