import assert from"node:assert/strict";import test from"node:test";import{activeCourseAuthority,authorityReceiptId,resolveAuthority,resolveBookingCourseAuthority}from"./enterpriseAuthorityDomain.js";
const now="2026-08-15T00:00:00.000Z",org={organizationId:"org_1",displayName:"One",status:"active",version:1,propertyIds:["prop_1"]},property={propertyId:"prop_1",organizationId:"org_1",displayName:"P",status:"active",version:1,courseIds:["course_1"]},course={courseId:"course_1",propertyId:"prop_1",organizationId:"org_1",displayName:"C",status:"active",version:1},hierarchy={organizations:[org],properties:[property],courses:[course]};
const membership={membershipId:"mem_1",bindingUid:"user_1",organizationId:"org_1",role:"course_manager",scope:{kind:"course",organizationId:"org_1",propertyId:"prop_1",courseId:"course_1"},status:"active",effectiveAt:"2026-01-01T00:00:00Z",expiresAt:"2027-01-01T00:00:00Z",version:1,grantIds:["grant_1"]};
const grant={grantId:"grant_1",membershipId:"mem_1",organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",capabilities:["course_profile","member_linking"],status:"active",effectiveAt:"2026-01-01T00:00:00Z",expiresAt:"2027-01-01T00:00:00Z",version:1};
test("single organization exact course grant",()=>{const r=resolveAuthority("user_1",[membership],[grant],hierarchy,now);assert(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"))});
test("multi organization memberships remain isolated",()=>{const o2={...org,organizationId:"org_2"},p2={...property,propertyId:"prop_2",organizationId:"org_2"},c2={...course,courseId:"course_2",propertyId:"prop_2",organizationId:"org_2"},m2={...membership,membershipId:"mem_2",organizationId:"org_2",scope:{kind:"course",organizationId:"org_2",propertyId:"prop_2",courseId:"course_2"},grantIds:["grant_2"]},g2={...grant,grantId:"grant_2",membershipId:"mem_2",organizationId:"org_2",propertyId:"prop_2",courseId:"course_2"};const r=resolveAuthority("user_1",[membership,m2],[grant,g2],{organizations:[org,o2],properties:[property,p2],courses:[course,c2]},now);assert.equal(r.memberships.length,2)});
for(const state of["pending","suspended","expired","revoked"]){test(`${state} membership denied`,()=>{const r=resolveAuthority("user_1",[{...membership,status:state}],[grant],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)})}
test("expired timestamp denied",()=>{const r=resolveAuthority("user_1",[{...membership,expiresAt:"2026-01-02T00:00:00Z"}],[grant],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)});
for(const level of["organizations","properties","courses"] as const){test(`suspended ${level} denied`,()=>{const h={...hierarchy,[level]:hierarchy[level].map(x=>({...x,status:"suspended"}))};const r=resolveAuthority("user_1",[membership],[grant],h,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,h,now,"course_profile"),false)})}
test("cross-course grant denied",()=>{const r=resolveAuthority("user_1",[membership],[{...grant,courseId:"course_2"}],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)});
test("forged uid denied",()=>assert.throws(()=>resolveAuthority("attacker",[membership],[grant],hierarchy,now),/BINDING_UID/));
test("duplicate memberships denied",()=>assert.throws(()=>resolveAuthority("user_1",[membership,membership],[grant],hierarchy,now),/DUPLICATE/));
test("missing hierarchy denied",()=>assert.throws(()=>resolveAuthority("user_1",[membership],[grant],{...hierarchy,courses:[]},now)));
test("malformed role denied",()=>assert.throws(()=>resolveAuthority("user_1",[{...membership,role:"owner"}],[grant],hierarchy,now)));
test("receipt deterministic",()=>assert.equal(authorityReceiptId("u","read","v"),authorityReceiptId("u","read","v")));
const bookingGrant={...grant,capabilities:["booking"]};
for(const role of["course_manager","booking_staff"] as const)test(`${role} exact course booking grant mutates`,()=>assert.equal(resolveBookingCourseAuthority("user_1",[{...membership,role}],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"mutate"},now).canMutate,true));
for(const role of["organization_owner","organization_admin"] as const)test(`${role} organization scope requires exact child grant`,()=>{const m={...membership,role,scope:{kind:"organization",organizationId:"org_1"}};assert.equal(resolveBookingCourseAuthority("user_1",[m],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"mutate"},now).role,role);assert.throws(()=>resolveBookingCourseAuthority("user_1",[m],[{...bookingGrant,courseId:"course_2"}],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"mutate"},now),/DENIED/)});
test("analyst is exact-grant read-only",()=>{const m={...membership,role:"analyst_viewer"};assert.equal(resolveBookingCourseAuthority("user_1",[m],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now).canMutate,false);assert.throws(()=>resolveBookingCourseAuthority("user_1",[m],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"mutate"},now),/DENIED/)});
test("unrelated role cannot read bookings",()=>assert.throws(()=>resolveBookingCourseAuthority("user_1",[{...membership,role:"tournament_staff"}],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/DENIED/));
for(const state of["suspended","revoked","expired"] as const)test(`${state} booking authority fails closed`,()=>{assert.throws(()=>resolveBookingCourseAuthority("user_1",[{...membership,status:state}],[bookingGrant],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/DENIED/);assert.throws(()=>resolveBookingCourseAuthority("user_1",[membership],[{...bookingGrant,status:state}],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/DENIED/)});
test("expired grant and inactive hierarchy fail closed",()=>{assert.throws(()=>resolveBookingCourseAuthority("user_1",[membership],[{...bookingGrant,expiresAt:"2026-01-01T00:00:00Z"}],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/DENIED/);assert.throws(()=>resolveBookingCourseAuthority("user_1",[membership],[bookingGrant],{...hierarchy,courses:[{...course,status:"suspended"}]},{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/HIERARCHY/)});
test("multiple matching memberships are ambiguous",()=>{const m2={...membership,membershipId:"mem_2",grantIds:["grant_2"]},g2={...bookingGrant,grantId:"grant_2",membershipId:"mem_2"};assert.throws(()=>resolveBookingCourseAuthority("user_1",[membership,m2],[bookingGrant,g2],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/AMBIGUOUS/)});
test("hierarchy relationship cannot be bypassed",()=>assert.throws(()=>resolveBookingCourseAuthority("user_1",[membership],[bookingGrant],{...hierarchy,properties:[{...property,courseIds:[]}]},{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/HIERARCHY/));
test("foreign referenced grant poisons the complete authority decision",()=>{const m={...membership,grantIds:["grant_1","grant_2"]},foreign={...bookingGrant,grantId:"grant_2",membershipId:"mem_foreign"};assert.throws(()=>resolveBookingCourseAuthority("user_1",[m],[bookingGrant,foreign],hierarchy,{organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",mode:"read"},now),/DENIED/)});
