import {createHash} from "node:crypto";
export const ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA="golfriend.enterprise-booking-golfer-binding.v1" as const;
export const ENTERPRISE_BOOKING_GOLFER_PROJECTION_SCHEMA="golfriend.enterprise-booking-golfer-projection.v1" as const;
const GOLFER=/^gfr_[A-Za-z0-9_-]{24,160}$/,ID=/^[A-Za-z0-9_-]{8,200}$/,hash=(value:string)=>createHash("sha256").update(value).digest("hex");
export type GolferClaim=Readonly<{golferRef:string;version:number}>;
export type GolferBinding=Readonly<{schema:typeof ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA;bindingId:string;golferRef:string;golferRefVersion:number;producerId:string;correlationId:string;bookingId:string;f7RequestId:string;f7RequestVersion:number;intakeDigest:string;immutable:true}>;
export function serverIssuedGolferClaim(token:Record<string,unknown>):GolferClaim{const golferRef=String(token.bookingGolferRef||""),version=Number(token.bookingGolferRefVersion);if(!GOLFER.test(golferRef)||!Number.isSafeInteger(version)||version!==1)throw new Error("GOLFER_IDENTITY_AUTHORITY_UNAVAILABLE");return Object.freeze({golferRef,version})}
export function buildEnterpriseBookingGolferBinding(input:Readonly<{golferRef:string;golferRefVersion:number;producerId:string;correlationId:string;bookingId:string;f7RequestId:string;f7RequestVersion:number;intakeDigest:string}>):GolferBinding{if(!GOLFER.test(input.golferRef)||input.golferRefVersion!==1||![input.producerId,input.correlationId,input.bookingId,input.f7RequestId].every(x=>ID.test(x))||!Number.isSafeInteger(input.f7RequestVersion)||input.f7RequestVersion<1||!/^[a-f0-9]{64}$/.test(input.intakeDigest))throw new Error("GOLFER_BINDING_INVALID");return Object.freeze({schema:ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA,bindingId:`ebgb_${hash(input.correlationId).slice(0,40)}`,...input,immutable:true})}
export function assertEnterpriseBookingGolferBinding(binding:unknown,claim:GolferClaim,expected:Readonly<{correlationId:string;bookingId:string;intakeDigest:string}>):GolferBinding{const value=binding as GolferBinding;if(!value||value.schema!==ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA||value.immutable!==true||value.bindingId!==`ebgb_${hash(expected.correlationId).slice(0,40)}`||value.golferRef!==claim.golferRef||value.golferRefVersion!==claim.version||value.correlationId!==expected.correlationId||value.bookingId!==expected.bookingId||value.intakeDigest!==expected.intakeDigest)throw new Error("GOLFER_BINDING_UNAVAILABLE");return value}
export function golferOwnedBookingProjection(input:Readonly<{binding:GolferBinding;correlation:Record<string,unknown>;booking:Record<string,unknown>}>){const{binding,correlation,booking}=input;if(correlation.correlationId!==binding.correlationId||correlation.bookingId!==binding.bookingId||correlation.intakeDigest!==binding.intakeDigest||booking.bookingId!==binding.bookingId||booking.correlationId!==binding.correlationId)throw new Error("GOLFER_BOOKING_BINDING_MISMATCH");return Object.freeze({schema:ENTERPRISE_BOOKING_GOLFER_PROJECTION_SCHEMA,bookingId:binding.bookingId,correlationId:binding.correlationId,status:String(booking.status||""),version:Number(booking.version),courseId:String(booking.courseId||""),courseVersion:Number(booking.courseVersion),request:correlation.request,sourceVersion:Object.freeze({f7RequestVersion:binding.f7RequestVersion,enterpriseBookingVersion:Number(booking.version)}),boundary:"PRIVACY_MINIMIZED_OWN_BOOKING_ONLY" as const})}
