import * as admin from "firebase-admin";
import {defineSecret} from "firebase-functions/params";
import {HttpsError,onCall} from "firebase-functions/v2/https";
import {bookingScope,transactionBookingAuthority} from "./partnerBookingRuntime.js";
import {buildEnterpriseBookingOutbox,enterpriseBookingTransitionDigest,enterpriseBookingTransitionReceiptId,validateEnterpriseBookingTransition} from "./enterpriseBookingOutbox.js";
import {verifyEnterpriseCorrelationEvent} from "./enterpriseBookingCorrelation.js";
if(!admin.apps.length)admin.initializeApp();
const db=admin.firestore(),secret=defineSecret("ENTERPRISE_BOOKING_OUTBOX_HMAC_V1"),roles=new Set(["organization_owner","organization_admin","course_manager","booking_staff"]);
export const transitionEnterpriseCorrelatedBookingV2=onCall({enforceAppCheck:true,secrets:[secret]},async request=>{
 if(!request.auth)throw new HttpsError("unauthenticated","Authentication required.");let command;try{command=validateEnterpriseBookingTransition(request.data)}catch{throw new HttpsError("invalid-argument","Transition invalid.")}
 const signingKey=secret.value();if(!signingKey)throw new HttpsError("unavailable","booking_outbox_authority_unavailable");const scope=await bookingScope(request.auth.uid),bookingRef=db.collection("bookings").doc(command.bookingId),first=await bookingRef.get();if(!first.exists||first.data()?.schema!=="golfriend.enterprise-correlated-booking.v2")throw new HttpsError("permission-denied","Booking unavailable.");
 const caller=request.auth.uid,courseId=String(first.data()?.courseId||""),correlationRef=db.collection("enterprise_booking_correlations").doc(String(first.data()?.correlationId||"")),receiptId=enterpriseBookingTransitionReceiptId(command.bookingId,command.commandId),receiptRef=db.collection("enterprise_booking_transition_receipts").doc(receiptId);
 return db.runTransaction(async tx=>{
  const authority=await transactionBookingAuthority(tx,caller,scope,courseId,"mutate");if(!roles.has(authority.role))throw new HttpsError("permission-denied","Booking unavailable.");const[booking,correlation,prior,currentCourse]=await Promise.all([tx.get(bookingRef),tx.get(correlationRef),tx.get(receiptRef),tx.get(db.collection("enterprise_courses").doc(courseId))]);if(!booking.exists||!correlation.exists||!currentCourse.exists||booking.data()?.courseId!==courseId||booking.data()?.organizationId!==scope.organizationId||Number(booking.data()?.courseVersion)!==Number(currentCourse.data()?.version))throw new HttpsError("permission-denied","Booking unavailable.");
  const digest=enterpriseBookingTransitionDigest(command);if(prior.exists){const p=prior.data()||{},priorOutbox=await tx.get(db.collection("enterprise_booking_correlation_outbox").doc(String(p.eventId||""))),o=priorOutbox.data()||{};try{const verified=verifyEnterpriseCorrelationEvent(o,signingKey);if(p.digest!==digest||p.bookingId!==command.bookingId||p.receiptId!==receiptId||p.immutable!==true||!priorOutbox.exists||o.immutable!==true||verified.eventId!==p.eventId||verified.integrityDigest!==p.eventDigest||(verified.enterpriseBooking as any).bookingId!==command.bookingId||(verified.command as any).commandId!==command.commandId)throw new Error()}catch{throw new HttpsError("already-exists","Transition command conflict.")}return{success:true,bookingId:command.bookingId,status:p.status,version:p.version,receiptId,eventId:p.eventId,restarted:true}}
  const nowMs=Date.now(),at=new Date(nowMs).toISOString(),planned=buildEnterpriseBookingOutbox({request:command,booking:booking.data()!,correlation:correlation.data()!,occurredAt:at,expiresAt:new Date(nowMs+300_000).toISOString(),secret:signingKey}),outboxRef=db.collection("enterprise_booking_correlation_outbox").doc(planned.event.eventId),stamp=admin.firestore.FieldValue.serverTimestamp();tx.update(bookingRef,{status:command.state,version:planned.nextVersion,alternativeSlot:command.alternativeSlot,updatedAt:stamp});tx.update(correlationRef,{status:command.state,version:planned.nextVersion,alternativeSlot:command.alternativeSlot,generatedAt:stamp});tx.create(outboxRef,{...planned.event,immutable:true,deliveryState:"awaiting_golfer_consumer",createdAt:stamp});tx.create(receiptRef,{schema:"golfriend.enterprise-booking-transition-receipt.v2",receiptId,bookingId:command.bookingId,status:command.state,version:planned.nextVersion,eventId:planned.event.eventId,eventDigest:planned.event.integrityDigest,digest:planned.digest,immutable:true,createdAt:stamp});return{success:true,bookingId:command.bookingId,status:command.state,version:planned.nextVersion,receiptId,eventId:planned.event.eventId,restarted:false};
 });
});
