import { createHash, createHmac, timingSafeEqual } from "node:crypto";

export const ENTERPRISE_CORRELATION_INTAKE_SCHEMA = "golfriend.enterprise-booking-correlation-intake.v1" as const;
export const ENTERPRISE_CORRELATION_SCHEMA = "golfriend.enterprise-booking-correlation.v1" as const;
export const ENTERPRISE_CORRELATION_EVENT_SCHEMA = "golfriend.enterprise-booking-correlation-event.v1" as const;
export const ENTERPRISE_CORRELATION_STATES = ["course_reviewing","course_confirmed","alternative_proposed","cancellation_accepted","cancellation_declined","cancelled","expired"] as const;
type State = typeof ENTERPRISE_CORRELATION_STATES[number];
type Json = Record<string, unknown>;
const ID=/^[A-Za-z0-9_-]{8,200}$/, CORRELATION=/^ebc_[A-Za-z0-9_-]{24,160}$/, GOLFER=/^gfr_[A-Za-z0-9_-]{24,160}$/, DATE=/^\d{4}-\d{2}-\d{2}$/, TIME=/^([01]\d|2[0-3]):[0-5]\d$/, ZONE=/^[A-Za-z_]+(?:\/[A-Za-z_+-]+)+$/, SHA=/^[a-f0-9]{64}$/;
const exact=(v:Json,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>Object.prototype.hasOwnProperty.call(v,k));
const integer=(v:unknown,min=1,max=Number.MAX_SAFE_INTEGER)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max;
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
const validDate=(v:string)=>{if(!DATE.test(v))return false;const [y,m,d]=v.split("-").map(Number),date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d};
const stable=(v:unknown):string=>Array.isArray(v)?`[${v.map(stable).join(",")}]`:v&&typeof v==="object"?`{${Object.keys(v as Json).sort().map(k=>`${JSON.stringify(k)}:${stable((v as Json)[k])}`).join(",")}}`:JSON.stringify(v);
const forbidden=(v:unknown):boolean=>{if(Array.isArray(v))return v.some(forbidden);if(!v||typeof v!=="object")return false;return Object.entries(v as Json).some(([k,x])=>/(memberUid|email|phone|contactValue|providerEvidence|price|currency|payment|refund|commission|invoice|checkIn|played|firstTee|openRound)/i.test(k)||forbidden(x))};

export function canonicalEnterpriseCorrelationEnvelope(raw:Json, nowMs:number){
 if(forbidden(raw)||!exact(raw,["schema","correlationId","f7Request","golferRef","course","request","sourceEvent","issuedAt","expiresAt","integrityDigest"])||raw.schema!==ENTERPRISE_CORRELATION_INTAKE_SCHEMA||!CORRELATION.test(String(raw.correlationId))||!GOLFER.test(String(raw.golferRef))||!SHA.test(String(raw.integrityDigest)))throw new Error("CORRELATION_ENVELOPE_INVALID");
 const f7=raw.f7Request as Json,course=raw.course as Json,request=raw.request as Json,event=raw.sourceEvent as Json;
 if(!exact(f7,["requestId","version"])||!ID.test(String(f7.requestId))||!integer(f7.version)||!exact(course,["courseId","version"])||!ID.test(String(course.courseId))||!integer(course.version)||!exact(request,["date","timeWindow","partySize","preferences"])||!validDate(String(request.date))||!integer(request.partySize,1,8)||!exact(event,["eventId","version"])||!ID.test(String(event.eventId))||!integer(event.version))throw new Error("CORRELATION_ENVELOPE_INVALID");
 const window=request.timeWindow as Json,prefs=request.preferences as Json;
 if(!exact(window,["start","end","timeZone"])||!TIME.test(String(window.start))||!TIME.test(String(window.end))||String(window.end)<=String(window.start)||!ZONE.test(String(window.timeZone))||!exact(prefs,["locale","allowedChannels","shareContact"])||!["en","th","ko","ja","zh","es","fr","de"].includes(String(prefs.locale))||!Array.isArray(prefs.allowedChannels)||prefs.allowedChannels.length>3||prefs.allowedChannels.some(x=>!["course_phone","course_email","provider_redirect"].includes(String(x)))||new Set(prefs.allowedChannels).size!==prefs.allowedChannels.length||typeof prefs.shareContact!=="boolean")throw new Error("CORRELATION_ENVELOPE_INVALID");
 const issued=Date.parse(String(raw.issuedAt)),expires=Date.parse(String(raw.expiresAt));if(!Number.isFinite(issued)||!Number.isFinite(expires)||issued>nowMs+30_000||issued<nowMs-300_000||expires<=nowMs||expires<=issued||expires-issued>300_000)throw new Error("CORRELATION_ENVELOPE_EXPIRED");
 const {integrityDigest,...unsigned}=raw;return Object.freeze({unsigned:Object.freeze(unsigned),integrityDigest:String(integrityDigest),canonical:stable(unsigned)});
}
export function signEnterpriseCorrelationEnvelope(unsigned:Json,secret:string){if(secret.length<32)throw new Error("CORRELATION_SIGNER_UNAVAILABLE");return createHmac("sha256",secret).update(stable(unsigned)).digest("hex")}
export function verifyEnterpriseCorrelationEnvelope(raw:Json,secret:string,nowMs:number){const parsed=canonicalEnterpriseCorrelationEnvelope(raw,nowMs),expected=signEnterpriseCorrelationEnvelope(parsed.unsigned,secret),a=Buffer.from(parsed.integrityDigest,"hex"),b=Buffer.from(expected,"hex");if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error("CORRELATION_INTEGRITY_INVALID");return parsed}
export function correlationIntakeDigest(raw:Json){const {integrityDigest,...unsigned}=raw;return hash(stable(unsigned))}
export function buildEnterpriseCorrelationIntake(raw:Json){const digest=correlationIntakeDigest(raw),correlationId=String(raw.correlationId),receiptId=`ebcir_${hash(`${correlationId}|${digest}`).slice(0,40)}`,bookingId=`ebk_${hash(correlationId).slice(0,40)}`;return Object.freeze({correlation:Object.freeze({schema:ENTERPRISE_CORRELATION_SCHEMA,correlationId,bookingId,version:1,status:"course_reviewing" as const,f7Request:Object.freeze({...raw.f7Request as Json}),golferRef:String(raw.golferRef),course:Object.freeze({...raw.course as Json}),request:Object.freeze({...raw.request as Json}),sourceEvent:Object.freeze({...raw.sourceEvent as Json}),intakeDigest:digest,boundary:"ENTERPRISE_ONLY_NO_GOLFER_AGGREGATE_WRITE" as const}),receipt:Object.freeze({schema:"golfriend.enterprise-booking-correlation-intake-receipt.v1",receiptId,correlationId,bookingId,intakeDigest:digest,immutable:true as const})})}
export function replayEnterpriseCorrelationIntake(existing:ReturnType<typeof buildEnterpriseCorrelationIntake>,raw:Json){const next=buildEnterpriseCorrelationIntake(raw);if(existing.correlation.correlationId!==next.correlation.correlationId||existing.correlation.intakeDigest!==next.correlation.intakeDigest||existing.receipt.receiptId!==next.receipt.receiptId)throw new Error("CORRELATION_REPLAY_CONFLICT");return existing}

export function buildEnterpriseCorrelationEvent(input:Readonly<{correlationId:string;bookingId:string;bookingVersion:number;f7RequestId:string;f7Version:number;courseId:string;courseVersion:number;state:State;commandId:string;sourceEventVersion:number;occurredAt:string;issuedAt:string;expiresAt:string;alternativeSlot:null|Readonly<{slotId:string;date:string;time:string;timeZone:string;slotVersion:number}>;integritySecret:string}>){
 const occurred=Date.parse(input.occurredAt),issued=Date.parse(input.issuedAt),expires=Date.parse(input.expiresAt),slot=input.alternativeSlot;if(!CORRELATION.test(input.correlationId)||![input.bookingId,input.f7RequestId,input.courseId,input.commandId].every(x=>ID.test(x))||![input.bookingVersion,input.f7Version,input.courseVersion,input.sourceEventVersion].every(x=>integer(x))||!ENTERPRISE_CORRELATION_STATES.includes(input.state)||!Number.isFinite(occurred)||!Number.isFinite(issued)||!Number.isFinite(expires)||occurred>issued||expires<=issued||expires-issued>300_000||input.integritySecret.length<32)throw new Error("CORRELATION_EVENT_INVALID");if((input.state==="alternative_proposed")!==!!slot||slot&&(!ID.test(slot.slotId)||!validDate(slot.date)||!TIME.test(slot.time)||!ZONE.test(slot.timeZone)||!integer(slot.slotVersion)))throw new Error("CORRELATION_EVENT_INVALID");const commandDigest=hash(stable({commandId:input.commandId,state:input.state,bookingVersion:input.bookingVersion,sourceEventVersion:input.sourceEventVersion,alternativeSlot:input.alternativeSlot})),eventId=`ebce_${hash(`${input.correlationId}|${input.bookingVersion}|${input.state}|${input.commandId}`).slice(0,40)}`,unsigned={schema:ENTERPRISE_CORRELATION_EVENT_SCHEMA,eventId,correlationId:input.correlationId,enterpriseBooking:Object.freeze({bookingId:input.bookingId,version:input.bookingVersion}),f7Request:Object.freeze({requestId:input.f7RequestId,version:input.f7Version}),course:Object.freeze({courseId:input.courseId,version:input.courseVersion}),state:input.state,alternativeSlot:slot?Object.freeze({...slot}):null,command:Object.freeze({commandId:input.commandId,digest:commandDigest}),sourceEventVersion:input.sourceEventVersion,occurredAt:input.occurredAt,issuedAt:input.issuedAt,expiresAt:input.expiresAt,boundary:"OUTBOX_ONLY_NO_GOLFER_AGGREGATE_WRITE" as const};return Object.freeze({...unsigned,integrityDigest:createHmac("sha256",input.integritySecret).update(stable(unsigned)).digest("hex")})}
