import*as admin from'firebase-admin';import{createHash,randomBytes}from'node:crypto';import{defineSecret}from'firebase-functions/params';import{HttpsError,onCall}from'firebase-functions/v2/https';import{bookingScope,transactionBookingAuthority}from'./partnerBookingRuntime.js';import{buildEnterpriseBookingOutbox,validateEnterpriseBookingTransition}from'./enterpriseBookingOutbox.js';import{verifyEnterpriseCorrelationEvent}from'./enterpriseBookingCorrelation.js';import{validateSlotCapacity}from'./partnerBookingReplay.js';import{buildEnterpriseBookingOperationIntent,deriveEnterpriseBookingToken,enterpriseBookingOperationId,enterpriseBookingOperationState,exactEnterpriseBookingOperationReplay,validateEnterpriseBookingOperation,validateStoredEnterpriseBookingAuthorization,ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA,ENTERPRISE_BOOKING_TOKEN_SCHEMA}from'./enterpriseBookingV2Operation.js';
if(!admin.apps.length)admin.initializeApp();const db=admin.firestore(),TOKEN=defineSecret('BOOKING_CONFIRMATION_HMAC_V2'),OUTBOX=defineSecret('ENTERPRISE_BOOKING_OUTBOX_HMAC_V1'),roles=new Set(['organization_owner','organization_admin','course_manager','booking_staff']),hash=(value:string)=>createHash('sha256').update(value).digest('hex'),exact=(value:any,keys:string[])=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key)),stamp=()=>admin.firestore.FieldValue.serverTimestamp(),SIGNER_KEY_VERSION=1;
const denied=()=>new HttpsError('permission-denied','Booking unavailable.');
function parseOperation(data:any){try{return validateEnterpriseBookingOperation(data)}catch{throw new HttpsError('invalid-argument','Booking operation invalid.')}}
function transitionRequest(operation:any){return validateEnterpriseBookingTransition({schema:'golfriend.enterprise-booking-transition.v2',bookingId:operation.bookingId,commandId:operation.commandId,expectedVersion:operation.expectedVersion,state:enterpriseBookingOperationState(operation.action),alternativeSlot:operation.alternativeSlot})}
function intentFor(caller:string,authority:any,operation:any){return buildEnterpriseBookingOperationIntent({actorUid:caller,membershipId:authority.membershipId,organizationId:authority.organizationId,propertyId:authority.propertyId,courseId:authority.courseId,authoritySourceVersion:authority.sourceVersion,operation})}
function authorizationMatches(a:any,intent:any){try{validateStoredEnterpriseBookingAuthorization(a);return a.operationId===intent.operationId&&a.intentDigest===intent.intentDigest&&a.actorUid===intent.actorUid&&a.membershipId===intent.membershipId&&a.organizationId===intent.organizationId&&a.propertyId===intent.propertyId&&a.courseId===intent.courseId&&a.bookingId===intent.bookingId&&a.action===intent.action&&a.commandId===intent.commandId&&a.expectedVersion===intent.expectedVersion&&a.payloadDigest===intent.payloadDigest&&a.authoritySourceVersion===intent.authoritySourceVersion&&a.signerKeyVersion===SIGNER_KEY_VERSION}catch{return false}}
function hasAmbiguousLock(booking:any){return Object.values(booking?.operationLocks||{}).some((lock:any)=>['ambiguous','ambiguous_locked'].includes(String(lock?.state)))}
async function authoritativeTransition(tx:any,operation:any,authority:any){
 if(operation.action!=='alternative')return transitionRequest(operation);const slotRef=db.collection('tee_time_slots').doc(operation.alternativeSlot.slotId),slot=await tx.get(slotRef),s=slot.data()||{};let capacity=null;try{capacity=validateSlotCapacity(s.bookedCount,s.capacity)}catch{capacity=null}
 if(!slot.exists||s.schema!=='golfriend.course-availability.v2'||s.organizationId!==authority.organizationId||s.courseId!==authority.courseId||s.status!=='open'||s.publishToApp!==false||s.version!==operation.alternativeSlot.slotVersion||s.date!==operation.alternativeSlot.date||s.time!==operation.alternativeSlot.time||s.timeZone!==operation.alternativeSlot.timeZone||!capacity?.available)throw new HttpsError('failed-precondition','Alternative slot unavailable.');
 return validateEnterpriseBookingTransition({schema:'golfriend.enterprise-booking-transition.v2',bookingId:operation.bookingId,commandId:operation.commandId,expectedVersion:operation.expectedVersion,state:'alternative_proposed',alternativeSlot:{slotId:slot.id,date:s.date,time:s.time,timeZone:s.timeZone,slotVersion:s.version}})
}

export const previewEnterpriseBookingActionV2=onCall({enforceAppCheck:true,secrets:[TOKEN]},async request=>{
 if(!request.auth)throw new HttpsError('unauthenticated','Authentication required.');const secret=TOKEN.value();if(!secret)throw new HttpsError('unavailable','booking_confirmation_authority_unavailable');const operation=parseOperation(request.data),caller=request.auth.uid,scope=await bookingScope(caller),bookingRef=db.collection('bookings').doc(operation.bookingId),initial=await bookingRef.get();if(!initial.exists||initial.data()?.schema!=='golfriend.enterprise-correlated-booking.v2')throw denied();const courseId=String(initial.data()?.courseId||''),authorizationId=enterpriseBookingOperationId(caller,operation),authorizationRef=db.collection('enterprise_booking_operation_authorizations_v2').doc(authorizationId);
 return db.runTransaction(async tx=>{const authority=await transactionBookingAuthority(tx,caller,scope,courseId,'mutate');if(!roles.has(authority.role))throw denied();const[booking,prior]=await Promise.all([tx.get(bookingRef),tx.get(authorizationRef)]),b=booking.data()||{};if(!booking.exists||b.schema!=='golfriend.enterprise-correlated-booking.v2'||b.organizationId!==authority.organizationId||b.propertyId!==authority.propertyId||b.courseId!==authority.courseId||b.version!==operation.expectedVersion||hasAmbiguousLock(b))throw denied();await authoritativeTransition(tx,operation,authority);const intent=intentFor(caller,authority,operation),nowMs=Date.now();if(prior.exists){const a=prior.data()||{};if(!authorizationMatches(a,intent)||a.state!=='active'||a.recoverableUntilMs<=nowMs)throw new HttpsError('already-exists','Booking operation conflict.');if(a.tokenExpiresAtMs<=nowMs)throw new HttpsError('failed-precondition','Booking confirmation recovery required.');const token=deriveEnterpriseBookingToken(intent.intentDigest,a.tokenVersion,String(a.currentNonce),secret);if(token.tokenDigest!==a.currentTokenDigest)throw new HttpsError('failed-precondition','Booking confirmation unavailable.');return{success:true,schema:ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA,operationId:intent.operationId,operationDigest:intent.intentDigest,bookingId:intent.bookingId,action:intent.action,revision:intent.expectedVersion,tokenVersion:token.tokenVersion,expiresAt:new Date(a.tokenExpiresAtMs).toISOString(),confirmationToken:token.token,restarted:true}}
 const nonce=randomBytes(32).toString('hex'),token=deriveEnterpriseBookingToken(intent.intentDigest,1,nonce,secret),tokenExpiresAtMs=nowMs+120_000,recoverableUntilMs=nowMs+24*60*60*1000,tokenRef=db.collection('enterprise_booking_confirmation_tokens_v2').doc(token.tokenDigest),createdAt=stamp();tx.create(authorizationRef,{schema:ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA,...intent,signerKeyVersion:SIGNER_KEY_VERSION,tokenVersion:1,currentTokenDigest:token.tokenDigest,currentNonce:nonce,tokenExpiresAtMs,recoverableUntilMs,state:'active',version:1,createdAt,updatedAt:createdAt});tx.create(tokenRef,{schema:ENTERPRISE_BOOKING_TOKEN_SCHEMA,operationId:intent.operationId,operationDigest:intent.intentDigest,signerKeyVersion:SIGNER_KEY_VERSION,tokenVersion:1,tokenDigest:token.tokenDigest,state:'active',issuedAtMs:nowMs,expiresAtMs:tokenExpiresAtMs,createdAt});return{success:true,schema:ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA,operationId:intent.operationId,operationDigest:intent.intentDigest,bookingId:intent.bookingId,action:intent.action,revision:intent.expectedVersion,tokenVersion:1,expiresAt:new Date(tokenExpiresAtMs).toISOString(),confirmationToken:token.token,restarted:false}});
});

export const manageEnterpriseBookingActionV2=onCall({enforceAppCheck:true,secrets:[TOKEN,OUTBOX]},async request=>{
 if(!request.auth)throw new HttpsError('unauthenticated','Authentication required.');if(!exact(request.data,['schema','bookingId','commandId','expectedVersion','action','alternativeSlot','confirmationToken'])||typeof request.data.confirmationToken!=='string')throw new HttpsError('invalid-argument','Booking operation invalid.');const secret=TOKEN.value(),outboxSecret=OUTBOX.value();if(!secret||!outboxSecret)throw new HttpsError('unavailable','booking_operation_authority_unavailable');const{confirmationToken,...raw}=request.data,operation=parseOperation(raw),caller=request.auth.uid,scope=await bookingScope(caller),bookingRef=db.collection('bookings').doc(operation.bookingId),initial=await bookingRef.get();if(!initial.exists||initial.data()?.schema!=='golfriend.enterprise-correlated-booking.v2')throw denied();const courseId=String(initial.data()?.courseId||''),correlationRef=db.collection('enterprise_booking_correlations').doc(String(initial.data()?.correlationId||''));
 return db.runTransaction(async tx=>{const authority=await transactionBookingAuthority(tx,caller,scope,courseId,'mutate');if(!roles.has(authority.role))throw denied();const intent=intentFor(caller,authority,operation),authorizationRef=db.collection('enterprise_booking_operation_authorizations_v2').doc(intent.operationId),receiptId=`ebor_${hash(intent.operationId).slice(0,40)}`,receiptRef=db.collection('enterprise_booking_operation_receipts_v2').doc(receiptId),tokenDigest=hash(confirmationToken),tokenRef=db.collection('enterprise_booking_confirmation_tokens_v2').doc(tokenDigest),[booking,correlation,authorization,token,prior,currentCourse]=await Promise.all([tx.get(bookingRef),tx.get(correlationRef),tx.get(authorizationRef),tx.get(tokenRef),tx.get(receiptRef),tx.get(db.collection('enterprise_courses').doc(courseId))]),b=booking.data()||{},c=correlation.data()||{},a=authorization.data()||{},t=token.data()||{},nowMs=Date.now();
  if(!booking.exists||!correlation.exists||!currentCourse.exists||b.schema!=='golfriend.enterprise-correlated-booking.v2'||c.schema!=='golfriend.enterprise-booking-correlation.v1'||b.correlationId!==c.correlationId||b.organizationId!==authority.organizationId||b.propertyId!==authority.propertyId||b.courseId!==authority.courseId||b.courseVersion!==currentCourse.data()?.version||c.bookingId!==b.bookingId||String(c.course?.courseId)!==b.courseId||!authorization.exists||!authorizationMatches(a,intent)||a.currentTokenDigest!==tokenDigest||!token.exists||t.schema!==ENTERPRISE_BOOKING_TOKEN_SCHEMA||t.operationId!==intent.operationId||t.operationDigest!==intent.intentDigest||t.tokenVersion!==a.tokenVersion||t.signerKeyVersion!==SIGNER_KEY_VERSION)throw new HttpsError('failed-precondition','Booking operation unavailable.');
  if(prior.exists){try{const p=exactEnterpriseBookingOperationReplay(prior.data()||{},{operationId:intent.operationId,intentDigest:intent.intentDigest,bookingId:intent.bookingId,action:intent.action,commandId:intent.commandId}),outbox=await tx.get(db.collection('enterprise_booking_correlation_outbox').doc(String(p.eventId||''))),verified=verifyEnterpriseCorrelationEvent(outbox.data()||{},outboxSecret);if(a.state!=='consumed'||t.state!=='used'||!outbox.exists||outbox.data()?.immutable!==true||verified.eventId!==p.eventId||verified.state!==p.status||(verified.enterpriseBooking as any).bookingId!==p.bookingId||(verified.enterpriseBooking as any).version!==p.version||(verified.command as any).commandId!==p.commandId||b.version!==p.version||c.version!==p.version||b.status!==p.status||c.status!==p.status)throw new Error();return{success:true,bookingId:p.bookingId,status:p.status,version:p.version,receiptId:p.receiptId,eventId:p.eventId,restarted:true}}catch{throw new HttpsError('already-exists','Booking operation conflict.')}}
  if(b.version!==operation.expectedVersion||c.version!==operation.expectedVersion||a.state!=='active'||a.tokenExpiresAtMs<=nowMs||t.state!=='active'||t.expiresAtMs<=nowMs||hasAmbiguousLock(b))throw new HttpsError('failed-precondition','Booking operation unavailable.');const derived=deriveEnterpriseBookingToken(intent.intentDigest,a.tokenVersion,String(a.currentNonce),secret);if(derived.token!==confirmationToken||derived.tokenDigest!==tokenDigest)throw new HttpsError('failed-precondition','Booking operation unavailable.');
  const transition=await authoritativeTransition(tx,operation,authority),at=new Date(nowMs).toISOString(),planned=buildEnterpriseBookingOutbox({request:transition,booking:b,correlation:c,occurredAt:at,expiresAt:new Date(nowMs+300_000).toISOString(),secret:outboxSecret}),outboxRef=db.collection('enterprise_booking_correlation_outbox').doc(planned.event.eventId),createdAt=stamp();tx.update(bookingRef,{status:transition.state,version:planned.nextVersion,alternativeSlot:transition.alternativeSlot,updatedAt:createdAt});tx.update(correlationRef,{status:transition.state,version:planned.nextVersion,alternativeSlot:transition.alternativeSlot,generatedAt:createdAt});tx.create(outboxRef,{...planned.event,immutable:true,deliveryState:'awaiting_golfer_consumer',createdAt});tx.update(authorizationRef,{state:'consumed',consumedAt:createdAt,updatedAt:createdAt});tx.update(tokenRef,{state:'used',usedAt:createdAt});tx.create(receiptRef,{schema:'golfriend.enterprise-booking-operation-receipt.v2',receiptId,operationId:intent.operationId,intentDigest:intent.intentDigest,bookingId:intent.bookingId,action:intent.action,commandId:intent.commandId,status:transition.state,version:planned.nextVersion,eventId:planned.event.eventId,immutable:true,createdAt});return{success:true,bookingId:intent.bookingId,status:transition.state,version:planned.nextVersion,receiptId,eventId:planned.event.eventId,restarted:false}});
});
