import assert from"node:assert/strict";import test from"node:test";import{activeCourseAuthority,authorityReceiptId,resolveAuthority}from"./enterpriseAuthorityDomain.js";
const now="2026-08-15T00:00:00.000Z",org={organizationId:"org_1",displayName:"One",status:"active",version:1},property={propertyId:"prop_1",organizationId:"org_1",displayName:"P",status:"active",version:1},course={courseId:"course_1",propertyId:"prop_1",organizationId:"org_1",displayName:"C",status:"active",version:1},hierarchy={organizations:[org],properties:[property],courses:[course]};
const membership={membershipId:"mem_1",bindingUid:"user_1",organizationId:"org_1",role:"course_manager",scope:{kind:"course",organizationId:"org_1",propertyId:"prop_1",courseId:"course_1"},status:"active",effectiveAt:"2026-01-01T00:00:00Z",expiresAt:"2027-01-01T00:00:00Z",version:1,grantIds:["grant_1"]};
const grant={grantId:"grant_1",membershipId:"mem_1",organizationId:"org_1",propertyId:"prop_1",courseId:"course_1",capabilities:["course_profile","member_linking"],status:"active",effectiveAt:"2026-01-01T00:00:00Z",expiresAt:"2027-01-01T00:00:00Z",version:1};
test("single organization exact course grant",()=>{const r=resolveAuthority("user_1",[membership],[grant],hierarchy,now);assert(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"))});
test("multi organization memberships remain isolated",()=>{const o2={...org,organizationId:"org_2"},p2={...property,propertyId:"prop_2",organizationId:"org_2"},c2={...course,courseId:"course_2",propertyId:"prop_2",organizationId:"org_2"},m2={...membership,membershipId:"mem_2",organizationId:"org_2",scope:{kind:"course",organizationId:"org_2",propertyId:"prop_2",courseId:"course_2"},grantIds:["grant_2"]},g2={...grant,grantId:"grant_2",membershipId:"mem_2",organizationId:"org_2",propertyId:"prop_2",courseId:"course_2"};const r=resolveAuthority("user_1",[membership,m2],[grant,g2],{organizations:[org,o2],properties:[property,p2],courses:[course,c2]},now);assert.equal(r.memberships.length,2)});
for(const state of["pending","suspended","expired","revoked"]){test(`${state} membership denied`,()=>{const r=resolveAuthority("user_1",[{...membership,status:state}],[grant],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)})}
test("expired timestamp denied",()=>{const r=resolveAuthority("user_1",[{...membership,expiresAt:"2026-01-02T00:00:00Z"}],[grant],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)});
for(const level of["organizations","properties","courses"] as const){test(`suspended ${level} denied`,()=>{const h={...hierarchy,[level]:hierarchy[level].map(x=>({...x,status:"suspended"}))};const r=resolveAuthority("user_1",[membership],[grant],h,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,h,now,"course_profile"),false)})}
test("cross-course grant denied",()=>{const r=resolveAuthority("user_1",[membership],[{...grant,courseId:"course_2"}],hierarchy,now);assert.equal(activeCourseAuthority(r.memberships[0],r.grants,hierarchy,now,"course_profile"),false)});
test("forged uid denied",()=>assert.throws(()=>resolveAuthority("attacker",[membership],[grant],hierarchy,now),/BINDING_UID/));
test("duplicate memberships denied",()=>assert.throws(()=>resolveAuthority("user_1",[membership,membership],[grant],hierarchy,now),/DUPLICATE/));
test("missing hierarchy denied",()=>assert.throws(()=>resolveAuthority("user_1",[membership],[grant],{...hierarchy,courses:[]},now)));
test("malformed role denied",()=>assert.throws(()=>resolveAuthority("user_1",[{...membership,role:"owner"}],[grant],hierarchy,now)));
test("receipt deterministic",()=>assert.equal(authorityReceiptId("u","read","v"),authorityReceiptId("u","read","v")));
