import * as admin from "firebase-admin";
import { defineSecret } from "firebase-functions/params";
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { buildEnterpriseCorrelationIntake, replayEnterpriseCorrelationIntake, verifyEnterpriseCorrelationEnvelope } from "./enterpriseBookingCorrelation.js";
if(!admin.apps.length)admin.initializeApp();const db=admin.firestore();
const F7_CORRELATION_HMAC_KEY=defineSecret("F7_BOOKING_CORRELATION_HMAC_KEY");
export const GOLFER_CORRELATION_AUTHORITY_COMMISSIONED=false as const;

export const intakeEnterpriseBookingCorrelationV2=onCall({enforceAppCheck:true,secrets:[F7_CORRELATION_HMAC_KEY]},async request=>{
 if(!request.auth)throw new HttpsError("unauthenticated","Authentication required.");
 if(!GOLFER_CORRELATION_AUTHORITY_COMMISSIONED)throw new HttpsError("unavailable","golfer_correlation_authority_unavailable");
 const producer=String(request.auth.token.bookingCorrelationProducer||""),secret=F7_CORRELATION_HMAC_KEY.value();
 if(producer!=="f7-booking-publisher-v1"||!secret)throw new HttpsError("unavailable","golfer_correlation_authority_unavailable");
 let envelope;try{envelope=verifyEnterpriseCorrelationEnvelope(request.data,secret,Date.now())}catch{throw new HttpsError("invalid-argument","Correlation envelope invalid.")}
 const planned=buildEnterpriseCorrelationIntake(request.data),courseId=String((envelope.unsigned.course as Record<string,unknown>).courseId),courseVersion=Number((envelope.unsigned.course as Record<string,unknown>).version),eventId=String((envelope.unsigned.sourceEvent as Record<string,unknown>).eventId),eventVersion=Number((envelope.unsigned.sourceEvent as Record<string,unknown>).version),correlationRef=db.collection("enterprise_booking_correlations").doc(planned.correlation.correlationId),receiptRef=db.collection("enterprise_booking_correlation_receipts").doc(planned.receipt.receiptId),operationRef=db.collection("enterprise_booking_correlation_intake_operations").doc(eventId),courseRef=db.collection("enterprise_courses").doc(courseId);
 return db.runTransaction(async tx=>{const[course,correlation,receipt,operation]=await Promise.all([tx.get(courseRef),tx.get(correlationRef),tx.get(receiptRef),tx.get(operationRef)]);if(!course.exists||course.data()?.status!=="active"||Number(course.data()?.version)!==courseVersion)throw new HttpsError("failed-precondition","golfer_correlation_authority_unavailable");if(operation.exists){try{const replay=replayEnterpriseCorrelationIntake({correlation:correlation.data(),receipt:receipt.data()} as ReturnType<typeof buildEnterpriseCorrelationIntake>,request.data);if(operation.data()?.eventVersion!==eventVersion||operation.data()?.intakeDigest!==replay.correlation.intakeDigest)throw new Error();return{success:true,correlationId:replay.correlation.correlationId,bookingId:replay.correlation.bookingId,version:replay.correlation.version,receiptId:replay.receipt.receiptId,restarted:true}}catch{throw new HttpsError("already-exists","Correlation command conflict.")}}if(correlation.exists||receipt.exists)throw new HttpsError("already-exists","Correlation command conflict.");tx.create(correlationRef,{...planned.correlation,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.create(receiptRef,{...planned.receipt,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.create(operationRef,{eventId,eventVersion,correlationId:planned.correlation.correlationId,intakeDigest:planned.correlation.intakeDigest,receiptId:planned.receipt.receiptId,producerId:producer,immutable:true,createdAt:admin.firestore.FieldValue.serverTimestamp()});return{success:true,correlationId:planned.correlation.correlationId,bookingId:planned.correlation.bookingId,version:planned.correlation.version,receiptId:planned.receipt.receiptId,restarted:false}})
});
