import*as admin from"firebase-admin";import{HttpsError,onCall}from"firebase-functions/v2/https";import{AUTHORITY_SCHEMA,activeCourseAuthority,authorityReceiptId,resolveAuthority,stableId}from"./enterpriseAuthorityDomain.js";
if(!admin.apps.length)admin.initializeApp();const db=admin.firestore(),stamp=()=>admin.firestore.FieldValue.serverTimestamp();
const iso=(v:any)=>v?.toDate instanceof Function?v.toDate().toISOString():typeof v==="string"?v:null;
const cleanStatus=(v:any)=>["pending","active","suspended","unavailable"].includes(v)?v:"unavailable";
function unavailable(){return{schema:AUTHORITY_SCHEMA,selectedOrganizationId:null,actorMembershipIds:[],organizations:[],memberships:[],invitations:[],ownershipTransfers:[],receipts:[],producerStatus:"unavailable"}}
function authUid(r:any){if(!r.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");return String(r.auth.uid)}
async function load(uid:string){
 const binding=await db.collection("enterprise_authority_bindings").doc(uid).collection("memberships").limit(100).get();if(binding.empty)return null;
 const ids=binding.docs.map(d=>String(d.data()?.membershipId||d.id));if(new Set(ids).size!==ids.length)throw new Error("CONFLICTING_BINDINGS");
 const membershipSnaps=await db.getAll(...ids.map(id=>db.collection("enterprise_authority_memberships").doc(stableId(id,"MEMBERSHIP"))));if(membershipSnaps.some(x=>!x.exists))throw new Error("MISSING_MEMBERSHIP");
 const rawMemberships=membershipSnaps.map(x=>{const d=x.data()||{};return{...d,membershipId:x.id,effectiveAt:iso(d.effectiveAt),expiresAt:d.expiresAt==null?null:iso(d.expiresAt)}});
 const grantIds=[...new Set(rawMemberships.flatMap((x:any)=>Array.isArray(x.grantIds)?x.grantIds.map(String):[]))];const grantSnaps=grantIds.length?await db.getAll(...grantIds.map(id=>db.collection("enterprise_authority_grants").doc(stableId(id,"GRANT")))):[];if(grantSnaps.some(x=>!x.exists))throw new Error("MISSING_GRANT");
 const rawGrants=grantSnaps.map(x=>{const d=x.data()||{};return{...d,grantId:x.id,effectiveAt:iso(d.effectiveAt),expiresAt:d.expiresAt==null?null:iso(d.expiresAt)}});
 const orgIds=[...new Set(rawMemberships.map((x:any)=>String(x.organizationId)))],orgSnaps=await db.getAll(...orgIds.map(id=>db.collection("enterprise_organizations").doc(stableId(id,"ORGANIZATION"))));if(orgSnaps.some(x=>!x.exists))throw new Error("MISSING_ORGANIZATION");
 const orgs=orgSnaps.map(x=>({organizationId:x.id,...x.data()}));const propertyIds=[...new Set(orgs.flatMap((x:any)=>Array.isArray(x.propertyIds)?x.propertyIds.map(String):[]).concat(rawMemberships.flatMap((x:any)=>x.scope?.propertyId?[String(x.scope.propertyId)]:[])))];
 const propertySnaps=propertyIds.length?await db.getAll(...propertyIds.map(id=>db.collection("enterprise_properties").doc(stableId(id,"PROPERTY")))):[];if(propertySnaps.some(x=>!x.exists))throw new Error("MISSING_PROPERTY");const properties=propertySnaps.map(x=>({propertyId:x.id,...x.data()}));
 const courseIds=[...new Set(properties.flatMap((x:any)=>Array.isArray(x.courseIds)?x.courseIds.map(String):[]).concat(rawMemberships.flatMap((x:any)=>x.scope?.courseId?[String(x.scope.courseId)]:[])))];const courseSnaps=courseIds.length?await db.getAll(...courseIds.map(id=>db.collection("enterprise_courses").doc(stableId(id,"COURSE")))):[];if(courseSnaps.some(x=>!x.exists))throw new Error("MISSING_COURSE");const courses=courseSnaps.map(x=>({courseId:x.id,...x.data()}));
 const hierarchy={organizations:orgs,properties,courses},resolved=resolveAuthority(uid,rawMemberships,rawGrants,hierarchy,new Date().toISOString());return{...resolved,hierarchy};
}
export async function resolveEnterpriseCourseAuthority(uid:string,membershipId:string,organizationId:string,propertyId:string,courseId:string,capability:string){const loaded=await load(uid);if(!loaded)throw new HttpsError("permission-denied","Authoritative membership unavailable.");const m=loaded.memberships.find(x=>x.membershipId===membershipId);if(!m||m.organizationId!==organizationId||m.scope.kind!=="course"||m.scope.propertyId!==propertyId||m.scope.courseId!==courseId||!activeCourseAuthority(m,loaded.grants,loaded.hierarchy,new Date().toISOString(),capability))throw new HttpsError("permission-denied","Exact active course authority required.");return{membership:m,grants:loaded.grants,hierarchy:loaded.hierarchy,sourceVersion:loaded.sourceVersion}}
export const getEnterpriseOrganizationAuthorityV2=onCall({enforceAppCheck:true},async r=>{const uid=authUid(r);try{const loaded:any=await load(uid);if(!loaded)return unavailable();const active=loaded.memberships.filter((m:any)=>{if(m.status!=="active"||Date.parse(m.effectiveAt)>Date.now()||m.expiresAt&&Date.parse(m.expiresAt)<=Date.now())return false;if(m.scope.kind==="organization")return loaded.hierarchy.organizations.some((x:any)=>x.organizationId===m.organizationId&&x.status==="active");return loaded.grants.some((g:any)=>m.grantIds.includes(g.grantId)&&g.status==="active"&&Date.parse(g.effectiveAt)<=Date.now()&&(!g.expiresAt||Date.parse(g.expiresAt)>Date.now()))});
 const selectedHint=typeof r.data?.selectedOrganizationId==="string"?r.data.selectedOrganizationId:null,selectedOrganizationId=selectedHint&&active.some((x:any)=>x.organizationId===selectedHint)?selectedHint:active[0]?.organizationId||null;
 const receiptId=authorityReceiptId(uid,"projection_read",loaded.sourceVersion),receiptRef=db.collection("enterprise_authority_receipts").doc(receiptId);await receiptRef.create({schema:"golfriend.enterprise-authority-receipt.v1",receiptId,decision:"projection_read",sourceVersion:loaded.sourceVersion,immutable:true,createdAt:stamp()}).catch((e:any)=>{if(e?.code!==6&&e?.code!=="already-exists")throw e});
 const organizations=loaded.hierarchy.organizations.map((o:any)=>({organizationId:o.organizationId,displayName:String(o.displayName||""),status:cleanStatus(o.status),version:Number(o.version||0),properties:loaded.hierarchy.properties.filter((p:any)=>p.organizationId===o.organizationId).map((p:any)=>({propertyId:p.propertyId,organizationId:o.organizationId,displayName:String(p.displayName||""),status:cleanStatus(p.status),courses:loaded.hierarchy.courses.filter((c:any)=>c.organizationId===o.organizationId&&c.propertyId===p.propertyId).map((c:any)=>({courseId:c.courseId,propertyId:p.propertyId,organizationId:o.organizationId,displayName:String(c.displayName||""),status:cleanStatus(c.status)}))}))}));
 return{schema:AUTHORITY_SCHEMA,selectedOrganizationId,actorMembershipIds:active.map((x:any)=>x.membershipId),organizations,memberships:loaded.memberships.map((m:any)=>({membershipId:m.membershipId,organizationId:m.organizationId,verifiedStaffId:m.bindingUid,role:m.role,scope:m.scope,status:m.status,version:m.version})),invitations:[],ownershipTransfers:[],receipts:[{receiptId,commandId:`read_${loaded.sourceVersion}`,organizationId:selectedOrganizationId||"none",action:"projection_read",actorMembershipId:active[0]?.membershipId||"none",occurredAt:new Date().toISOString(),authorityVersion:1,immutable:true}],producerStatus:"available"};}catch(e:any){if(e instanceof HttpsError)throw e;return unavailable()}});
