import *as admin from "firebase-admin";
import {HttpsError, onCall} from "firebase-functions/v2/https";
import {resolveEnterpriseCourseAuthority} from "./enterpriseAuthorityRuntime.js";
import {ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, MEMBER_STATES, commandId, invitationTransition, memberDigest, minimumMember, minimumReceipt, minimumRequest, normalizeChange, normalizeInvitation, page, previewCsv, receiptId, requireMemberChangeSource, scopeId, strictCommand, strictVersion} from "./enterpriseMemberManagementDomain.js";
if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore(), stamp = () => admin.firestore.FieldValue.serverTimestamp();
const fail = (e: any): never => {if (e instanceof HttpsError) throw e;
const m = String(e?.message || e);
throw new HttpsError(m.includes("REPLAY") ? "already-exists" : "invalid-argument", m)};
function context(x: any) {const allowed = new Set(["actorMembershipId", "organizationId", "propertyId", "courseId"]);
if (!x || Object.keys(x).some(k => !allowed.has(k))) throw Error("CONTEXT_INVALID");
const out: any = {};
for (const k of allowed) {const v = String(x[k] || "");
if (!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(v)) throw Error("CONTEXT_INVALID");
out[k] = v} return {...out, membershipId: out.actorMembershipId}}
function actor(r: any) {if (!r.auth?.uid) throw new HttpsError("unauthenticated", "Authentication required.");
return r.auth.uid as string}
async function scoped(r: any) {try {const uid = actor(r), scope = context(r.data?.context), authority = await resolveEnterpriseCourseAuthority(uid, scope.membershipId, scope.organizationId, scope.propertyId, scope.courseId, "member_management"), sid = scopeId(scope.organizationId, scope.propertyId, scope.courseId), applicationId = `eoa_${memberDigest([scope.organizationId, scope.propertyId, scope.courseId]).slice(0, 32)}`;
const [app, trial] = await Promise.all([db.collection("enterprise_onboarding_applications").doc(applicationId).get(), db.collection("enterprise_trials").doc(applicationId).get()]), a = app.data() || {}, t = trial.data() || {}, now = Date.now(), start = t.startsAt?.toMillis?.() ?? NaN, end = t.endsAt?.toMillis?.() ?? NaN;
if (!app.exists || a.organizationId !== scope.organizationId || a.propertyId !== scope.propertyId || a.courseId !== scope.courseId || a.actorMembershipId !== scope.membershipId || !a.agreementAcceptanceReceiptId || a.status === "suspended") throw new HttpsError("permission-denied", "Verified representative binding required.");
const activePartner = a.status === "active_partner", activeTrial = trial.exists && t.organizationId === scope.organizationId && t.propertyId === scope.propertyId && t.courseId === scope.courseId && t.activationReceiptId && Number.isFinite(start) && start <= now && Number.isFinite(end) && end > now && !t.suspendedAt && !t.revokedAt;
if (!activePartner && !activeTrial) throw new HttpsError("failed-precondition", "Member Management unavailable for this course.");
if (!Number.isSafeInteger(a.version) || a.version < 1) throw new HttpsError("unavailable", "Authoritative course version unavailable.");
return {uid, scope, authority, sid, courseVersion: a.version, entitlement: activePartner ? "active" : "active_trial"}} catch (e) {return fail(e)} }
const members = (sid: string) => db.collection("enterprise_course_member_scopes").doc(sid).collection("members"), requestRef = (sid: string, id: string) => db.collection("enterprise_course_member_scopes").doc(sid).collection("requests").doc(id);
async function projection(s:any,items:any[],nextCursor:string|null){const[requests,receipts]=await Promise.all([db.collection("enterprise_course_member_scopes").doc(s.sid).collection("requests").limit(100).get(),db.collection("enterprise_member_management_receipts").where("courseId","==",s.scope.courseId).limit(100).get()]);const exact=(x:any)=>x.organizationId===s.scope.organizationId&&x.propertyId===s.scope.propertyId&&x.courseId===s.scope.courseId&&x.representativeMembershipId===s.scope.membershipId;return{schema:ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA,context:{actorMembershipId:s.scope.actorMembershipId,organizationId:s.scope.organizationId,propertyId:s.scope.propertyId,courseId:s.scope.courseId},state:items.length?"current":"empty",entitlement:s.entitlement,courseVersion:s.courseVersion,members:items,nextCursor,requests:requests.docs.filter(d=>exact(d.data())).map(d=>minimumRequest(d.data())),receipts:receipts.docs.filter(d=>exact(d.data())).map(d=>minimumReceipt(d.data(),d.id)),deliveryProviderStatus:"unavailable",policy:{invitationExpiryDays:7,previewExpiryMinutes:15,roles:["member","junior_member","honorary_member","guest_member"]}}}
async function listing(s: any, r: any) {const raw = await members(s.sid).limit(501).get();
if (raw.size > 500) throw new HttpsError("resource-exhausted", "Directory requires narrower filtering.");
try {let items = raw.docs.map(d => {const x = d.data();
if (x.schema !== ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA || x.organizationId !== s.scope.organizationId || x.propertyId !== s.scope.propertyId || x.courseId !== s.scope.courseId || x.memberReference !== d.id) throw Error("MEMBER_MALFORMED");
return minimumMember(x)}), f = r.data?.filter || {};
if (Object.keys(f).some(k => !["search", "state", "role"].includes(k))) throw Error("FILTER_INVALID");
if (f.state && !MEMBER_STATES.includes(f.state)) throw Error("FILTER_INVALID");
if (f.role && (typeof f.role !== "string" || f.role.length > 80)) throw Error("FILTER_INVALID");
if (f.search && (typeof f.search !== "string" || f.search.trim().length < 2 || f.search.length > 80)) throw Error("FILTER_INVALID");
const q = String(f.search || "").trim().toLocaleLowerCase("en");
items = items.filter(x => (!f.state || x.state === f.state) && (!f.role || x.role === f.role) && (!q || x.displayName.toLocaleLowerCase("en").includes(q) || x.memberReference.toLocaleLowerCase("en") === q));
const binding = memberDigest({scope: s.sid, filter: {search: q, state: f.state || null, role: f.role || null}, sort: "displayName:en,memberReference", courseVersion: s.courseVersion});
return page(items, r.data?.limit ?? 25, binding, r.data?.cursor)} catch (e) {return fail(e)} }
export const getEnterpriseCourseMembersV1 = onCall({enforceAppCheck: true}, async r => {const s = await scoped(r);
const x=await listing(s,r);return projection(s,x.items,x.nextCursor)});
export const getEnterpriseCourseMemberV1 = onCall({enforceAppCheck: true}, async r => {const s = await scoped(r);
try {const id = String(r.data?.memberReference || ""), doc = await members(s.sid).doc(id).get(), x = doc.data();
if (!doc.exists || x?.organizationId !== s.scope.organizationId || x?.propertyId !== s.scope.propertyId || x?.courseId !== s.scope.courseId || x?.memberReference !== id) throw new HttpsError("not-found", "Member unavailable.");
return projection(s,[minimumMember(x)],null)} catch (e) {return fail(e)} });
async function writeRequest(r: any, action: "invitation" | "resend" | "change") {const s = await scoped(r);
try {const cid = strictCommand(r.data?.commandId), payload = action === "change" ? normalizeChange(r.data?.request) : normalizeInvitation(r.data?.request);
if (payload.currentCourseVersion !== s.courseVersion) throw new HttpsError("aborted", "STALE_COURSE_VERSION");
const reqId = `emmq_${memberDigest([s.sid, cid, action]).slice(0, 32)}`, cmdRef = db.collection("enterprise_member_management_commands").doc(commandId(s.uid, cid, action)), rid = receiptId(s.sid, cid, action), digest = memberDigest({action, payload, scope: s.scope, authority: s.authority.sourceVersion}), memberRef = members(s.sid).doc(payload.memberReference);
let replayed = false;
await db.runTransaction(async tx => {const [prior, member] = await Promise.all([tx.get(cmdRef), tx.get(memberRef)]);
if (prior.exists) {if (prior.data()?.digest !== digest) throw Error("COMMAND_REPLAY_CONFLICT");
replayed = true;
return } const m = member.data() || {};
if (member.exists && (m.organizationId !== s.scope.organizationId || m.propertyId !== s.scope.propertyId || m.courseId !== s.scope.courseId)) throw new HttpsError("not-found", "Member unavailable.");
if (action === "invitation" && member.exists) throw new HttpsError("already-exists", "Existing member requires conflict review.");
if (action === "resend" && (!member.exists || !["awaiting_delivery_provider", "invited"].includes(m.state))) throw new HttpsError("failed-precondition", "Reminder unavailable.");
if (action === "change" && (!member.exists || m.version !== (payload as any).currentMemberVersion)) throw new HttpsError("aborted", "STALE_MEMBER_VERSION");
if (action === "change") {try {requireMemberChangeSource((payload as any).type,m.state)} catch {throw new HttpsError("failed-precondition","MEMBER_STATE_TRANSITION_DENIED")}}
const expires = admin.firestore.Timestamp.fromMillis(Date.now() + 7 * 86400000), status = action === "invitation" || action === "resend" ? "awaiting_delivery_provider" : "change_requested";
tx.create(requestRef(s.sid, reqId), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId: reqId, action, ...payload, organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, authoritySourceVersion: s.authority.sourceVersion, status, version: 1, commandDigest: digest, expiresAt: expires, createdAt: stamp(), immutableSubmission: true});
tx.create(db.collection("enterprise_member_management_receipts").doc(rid), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, receiptId: rid, requestId: reqId, action, status, organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, locale: payload.locale, purpose: payload.purpose, commandDigest: digest, occurredAt: stamp(), immutable: true});
tx.create(cmdRef, {commandId: cid, digest, action, result: {requestId: reqId, receiptId: rid, status}, createdAt: stamp(), immutable: true})});
return {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId: reqId, receiptId: rid, status: action === "change" ? "change_requested" : "awaiting_delivery_provider", replayed, delivery: {status: "unavailable", sent: false}}} catch (e) {return fail(e)} }
async function draftRequest(r: any, action: "invitation" | "resend") {const s = await scoped(r);
try {const cid = strictCommand(r.data?.commandId), payload = normalizeInvitation(r.data?.request), requestId = `emmq_${memberDigest([s.sid, cid, action]).slice(0, 32)}`, digest = memberDigest({action, payload, scope: s.scope, authority: s.authority.sourceVersion}), cmdRef = db.collection("enterprise_member_management_commands").doc(commandId(s.uid, cid, `${action}_draft`)), member = await members(s.sid).doc(payload.memberReference).get();
if (payload.currentCourseVersion !== s.courseVersion) throw new HttpsError("aborted", "STALE_COURSE_VERSION");
if (action === "invitation" && member.exists) throw new HttpsError("already-exists", "Existing member requires conflict review.");
if (action === "resend" && (!member.exists || !["awaiting_delivery_provider", "invited"].includes(member.data()?.state))) throw new HttpsError("failed-precondition", "Reminder unavailable.");
let replayed = false;
await db.runTransaction(async tx => {const prior = await tx.get(cmdRef);
if (prior.exists) {if (prior.data()?.digest !== digest) throw Error("COMMAND_REPLAY_CONFLICT");
replayed = true;
return } tx.create(requestRef(s.sid, requestId), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId, action, ...payload, organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, authoritySourceVersion: s.authority.sourceVersion, status: "invitation_draft", version: 1, commandDigest: digest, expiresAt: admin.firestore.Timestamp.fromMillis(Date.now() + 7 * 86400000), createdAt: stamp()});
tx.create(cmdRef, {commandId: cid, digest, action: `${action}_draft`, result: {requestId, status: "invitation_draft", version: 1}, createdAt: stamp(), immutable: true})});
return {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId, status: "invitation_draft", version: 1, replayed, delivery: {status: "unavailable", sent: false}}} catch (e) {return fail(e)} }
export const createEnterpriseMemberInvitationDraftV1 = onCall({enforceAppCheck: true}, r => draftRequest(r, "invitation"));
export const createEnterpriseMemberResendDraftV1 = onCall({enforceAppCheck: true}, r => draftRequest(r, "resend"));
export const submitEnterpriseMemberChangeRequestV1 = onCall({enforceAppCheck: true}, r => writeRequest(r, "change"));
export const submitEnterpriseMemberInvitationRequestV1 = onCall({enforceAppCheck: true}, async r => {const s = await scoped(r);
try {const cid = strictCommand(r.data?.commandId), requestId = String(r.data?.requestId || ""), expected = strictVersion(r.data?.expectedVersion), ref = requestRef(s.sid, requestId), cmdRef = db.collection("enterprise_member_management_commands").doc(commandId(s.uid, cid, "submit_member_draft")), rid = receiptId(s.sid, cid, "submit_member_draft");
let replayed = false;
let submittedAction: "invitation" | "resend" = "invitation";
await db.runTransaction(async tx => {const [prior, doc] = await Promise.all([tx.get(cmdRef), tx.get(ref)]);
const x: any = doc.data();
if (!doc.exists || x.organizationId !== s.scope.organizationId || x.propertyId !== s.scope.propertyId || x.courseId !== s.scope.courseId || x.representativeMembershipId !== s.scope.membershipId) throw new HttpsError("not-found", "Draft unavailable.");
if (!["invitation", "resend"].includes(x.action) || typeof x.commandDigest !== "string") throw new HttpsError("failed-precondition", "Draft action unavailable.");
submittedAction = x.action;
const digest = memberDigest({requestId, expected, action: x.action, draftDigest: x.commandDigest, scope: s.scope, courseVersion: s.courseVersion});
if (prior.exists) {if (prior.data()?.digest !== digest) throw Error("COMMAND_REPLAY_CONFLICT");
replayed = true;
return }
const next = invitationTransition(x.status, x.version, expected, x.expiresAt?.toMillis?.() <= Date.now());
tx.update(ref, {...next, submittedAt: stamp()});
tx.create(db.collection("enterprise_member_management_receipts").doc(rid), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, receiptId: rid, requestId, action: `${x.action}_submitted`, draftCommandDigest: x.commandDigest, status: next.status, organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, commandDigest: digest, occurredAt: stamp(), immutable: true});
tx.create(cmdRef, {commandId: cid, digest, action: "submit_member_draft", result: {requestId, receiptId: rid, submittedAction: x.action, status: next.status, version: next.version}, createdAt: stamp(), immutable: true})});
return {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId, receiptId: rid, submittedAction, status: "awaiting_delivery_provider", version: expected + 1, replayed, delivery: {status: "unavailable", sent: false}}} catch (e) {return fail(e)} });
export const previewEnterpriseMemberCsvImportV1 = onCall({enforceAppCheck: true}, async r => {const s = await scoped(r);
try {const cid = strictCommand(r.data?.commandId), expected = strictVersion(r.data?.currentCourseVersion);
if (expected !== s.courseVersion) throw new HttpsError("aborted", "STALE_COURSE_VERSION");
const preview = previewCsv(r.data?.csv), existing = await members(s.sid).get(), byMember = new Set(existing.docs.map(d => d.id.toLowerCase())), byContact = new Set(existing.docs.map(d => String(d.data()?.contactReferenceHash || ""))), rows = preview.rows.map(x => {const contactHash = memberDigest(x.contactReference), result = byMember.has(x.memberReference.toLowerCase()) || byContact.has(contactHash) ? "conflict" : "valid";
return {...x, contactReference: `ref_${contactHash.slice(0, 12)}`, result}}), previewId = `emmp_${memberDigest([s.sid, cid, preview.digest]).slice(0, 32)}`, expiresAt = admin.firestore.Timestamp.fromMillis(Date.now() + 15 * 60000);
await db.collection("enterprise_member_import_previews").doc(previewId).create({schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, previewId, organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, authoritySourceVersion: s.authority.sourceVersion, courseVersion: s.courseVersion, rowCount: preview.rowCount, rowDigest: preview.digest, rows, expiresAt, createdAt: stamp(), immutable: true});
return {...await projection(s,[],null),state:"current",previewId,rows,expiresAt:expiresAt.toDate().toISOString(),createsAuthAccounts:false,sendsInvitations:false,requiresConfirmation:true}} catch (e) {return fail(e)} });
export const submitEnterpriseMemberCsvImportRequestV1 = onCall({enforceAppCheck: true}, async r => {const s = await scoped(r);
try {const cid = strictCommand(r.data?.commandId), expected = strictVersion(r.data?.currentCourseVersion), previewId = String(r.data?.previewId || "");
if (expected !== s.courseVersion || r.data?.confirmed !== true) throw new HttpsError("aborted", "STALE_OR_UNCONFIRMED_IMPORT");
const digest = memberDigest({scope: s.scope, courseVersion: expected, previewId, confirmed: true}), rid = receiptId(s.sid, cid, "import"), reqId = `emmq_${memberDigest([s.sid, cid, "import"]).slice(0, 32)}`, cmdRef = db.collection("enterprise_member_management_commands").doc(commandId(s.uid, cid, "import"));
const priorCommand = await cmdRef.get();
if (priorCommand.exists) {if (priorCommand.data()?.digest !== digest) throw Error("COMMAND_REPLAY_CONFLICT");
return {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, ...priorCommand.data()?.result, replayed: true, createsAuthAccounts: false, sendsInvitations: false}}
const previewRef = db.collection("enterprise_member_import_previews").doc(previewId), previewDoc = await previewRef.get(), preview: any = previewDoc.data();
if (!previewDoc.exists || preview.organizationId !== s.scope.organizationId || preview.propertyId !== s.scope.propertyId || preview.courseId !== s.scope.courseId || preview.representativeMembershipId !== s.scope.membershipId || preview.courseVersion !== s.courseVersion || preview.expiresAt?.toMillis?.() <= Date.now() || preview.consumedAt) throw new HttpsError("failed-precondition", "PREVIEW_UNAVAILABLE");
let replayed = false;
await db.runTransaction(async tx => {const [prior, currentPreview] = await Promise.all([tx.get(cmdRef), tx.get(previewRef)]);
if (prior.exists) {if (prior.data()?.digest !== digest) throw Error("COMMAND_REPLAY_CONFLICT");
replayed = true;
return } const px: any = currentPreview.data();
if (!currentPreview.exists || px.consumedAt || px.expiresAt?.toMillis?.() <= Date.now() || px.rowDigest !== preview.rowDigest) throw new HttpsError("failed-precondition", "PREVIEW_UNAVAILABLE");
tx.create(requestRef(s.sid, reqId), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId: reqId, action: "csv_import", organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, authoritySourceVersion: s.authority.sourceVersion, status: "conflict_review", version: 1, rowCount: px.rowCount, rowDigest: px.rowDigest, previewId, createdAt: stamp(), immutableSubmission: true});
tx.update(previewRef, {consumedAt: stamp(), consumedByRequestId: reqId});
tx.create(db.collection("enterprise_member_management_receipts").doc(rid), {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, receiptId: rid, requestId: reqId, action: "csv_import", status: "conflict_review", organizationId: s.scope.organizationId, propertyId: s.scope.propertyId, courseId: s.scope.courseId, representativeMembershipId: s.scope.membershipId, rowCount: px.rowCount, rowDigest: px.rowDigest, commandDigest: digest, occurredAt: stamp(), immutable: true});
tx.create(cmdRef, {commandId: cid, digest, action: "import", result: {requestId: reqId, receiptId: rid, status: "conflict_review", rowCount: px.rowCount}, createdAt: stamp(), immutable: true})});
return {schema: ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA, requestId: reqId, receiptId: rid, status: "conflict_review", rowCount: preview.rowCount, replayed, createsAuthAccounts: false, sendsInvitations: false}} catch (e) {return fail(e)} });
