import {createHash,createHmac} from 'node:crypto';

export const ENTERPRISE_BOOKING_OPERATION_SCHEMA='golfriend.enterprise-booking-operation.v2' as const;
export const ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA='golfriend.enterprise-booking-operation-authorization.v2' as const;
export const ENTERPRISE_BOOKING_TOKEN_SCHEMA='golfriend.enterprise-booking-confirmation-token.v2' as const;
export const ENTERPRISE_BOOKING_ACTIONS=['confirm','alternative','accept_cancellation','decline_cancellation'] as const;
export type EnterpriseBookingAction=typeof ENTERPRISE_BOOKING_ACTIONS[number];
type Raw=Record<string,unknown>;
const ID=/^[A-Za-z0-9_-]{8,200}$/,SHA=/^[a-f0-9]{64}$/;
const exact=(value:Raw,keys:string[])=>Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key));
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value as Raw).sort().map(key=>`${JSON.stringify(key)}:${stable((value as Raw)[key])}`).join(',')}}`:JSON.stringify(value);
const validDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const[y,m,d]=value.split('-').map(Number),date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d};

export function validateEnterpriseBookingOperation(raw:Raw){
 if(!exact(raw,['schema','bookingId','commandId','expectedVersion','action','alternativeSlot'])||raw.schema!==ENTERPRISE_BOOKING_OPERATION_SCHEMA||!ID.test(String(raw.bookingId))||!ID.test(String(raw.commandId))||!Number.isSafeInteger(raw.expectedVersion)||Number(raw.expectedVersion)<1||!ENTERPRISE_BOOKING_ACTIONS.includes(raw.action as EnterpriseBookingAction))throw new Error('BOOKING_OPERATION_INVALID');
 const alternative=raw.alternativeSlot as Raw|null;if((raw.action==='alternative')!==!!alternative)throw new Error('BOOKING_OPERATION_INVALID');
 if(alternative&&(!exact(alternative,['slotId','date','time','timeZone','slotVersion'])||!ID.test(String(alternative.slotId))||!validDate(String(alternative.date))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(alternative.time))||!/^([A-Za-z_]+\/[A-Za-z_+-]+|UTC)$/.test(String(alternative.timeZone))||!Number.isSafeInteger(alternative.slotVersion)||Number(alternative.slotVersion)<1))throw new Error('BOOKING_OPERATION_INVALID');
 return Object.freeze({schema:ENTERPRISE_BOOKING_OPERATION_SCHEMA,bookingId:String(raw.bookingId),commandId:String(raw.commandId),expectedVersion:Number(raw.expectedVersion),action:raw.action as EnterpriseBookingAction,alternativeSlot:alternative?Object.freeze({slotId:String(alternative.slotId),date:String(alternative.date),time:String(alternative.time),timeZone:String(alternative.timeZone),slotVersion:Number(alternative.slotVersion)}):null});
}
export const enterpriseBookingOperationState=(action:EnterpriseBookingAction)=>({confirm:'course_confirmed',alternative:'alternative_proposed',accept_cancellation:'cancellation_accepted',decline_cancellation:'cancellation_declined'} as const)[action];
export const enterpriseBookingOperationPayloadDigest=(operation:ReturnType<typeof validateEnterpriseBookingOperation>)=>hash(stable({action:operation.action,alternativeSlot:operation.alternativeSlot}));
export const enterpriseBookingOperationId=(actorUid:string,operation:ReturnType<typeof validateEnterpriseBookingOperation>)=>`ebop_${hash(`${actorUid}|${operation.bookingId}|${operation.action}|${operation.commandId}`).slice(0,40)}`;
export function buildEnterpriseBookingOperationIntent(input:Readonly<{actorUid:string;membershipId:string;organizationId:string;propertyId:string;courseId:string;authoritySourceVersion:string;operation:ReturnType<typeof validateEnterpriseBookingOperation>}>){
 if(![input.actorUid,input.membershipId,input.organizationId,input.propertyId,input.courseId].every(value=>ID.test(value))||!/^[a-f0-9]{32,64}$/.test(input.authoritySourceVersion))throw new Error('BOOKING_OPERATION_AUTHORITY_INVALID');
 const operationId=enterpriseBookingOperationId(input.actorUid,input.operation),payloadDigest=enterpriseBookingOperationPayloadDigest(input.operation),unsigned={operationId,actorUid:input.actorUid,membershipId:input.membershipId,organizationId:input.organizationId,propertyId:input.propertyId,courseId:input.courseId,bookingId:input.operation.bookingId,action:input.operation.action,commandId:input.operation.commandId,expectedVersion:input.operation.expectedVersion,payloadDigest,authoritySourceVersion:input.authoritySourceVersion},intentDigest=hash(stable(unsigned));return Object.freeze({...unsigned,intentDigest});
}
export function deriveEnterpriseBookingToken(intentDigest:string,tokenVersion:number,nonce:string,secret:string){if(!SHA.test(intentDigest)||!Number.isSafeInteger(tokenVersion)||tokenVersion<1||!SHA.test(nonce)||secret.length<32)throw new Error('BOOKING_TOKEN_SIGNER_UNAVAILABLE');const token=`ebct_${createHmac('sha256',secret).update(`${intentDigest}|${tokenVersion}|${nonce}`).digest('base64url')}`;return Object.freeze({token,tokenDigest:hash(token),tokenVersion});}
export function validateStoredEnterpriseBookingAuthorization(raw:Raw){if(raw.schema!==ENTERPRISE_BOOKING_AUTHORIZATION_SCHEMA||!ID.test(String(raw.operationId))||!SHA.test(String(raw.intentDigest))||!ENTERPRISE_BOOKING_ACTIONS.includes(raw.action as EnterpriseBookingAction)||!Number.isSafeInteger(raw.tokenVersion)||Number(raw.tokenVersion)<1||!SHA.test(String(raw.currentTokenDigest))||!['active','consumed','ambiguous_locked','revoked'].includes(String(raw.state)))throw new Error('BOOKING_AUTHORIZATION_INVALID');return raw;}
export function exactEnterpriseBookingOperationReplay(stored:Raw,expected:Readonly<{operationId:string;intentDigest:string;bookingId:string;action:EnterpriseBookingAction;commandId:string}>){if(!exact(stored,['schema','receiptId','operationId','intentDigest','bookingId','action','commandId','status','version','eventId','immutable','createdAt'])||stored.schema!=='golfriend.enterprise-booking-operation-receipt.v2'||stored.immutable!==true||stored.operationId!==expected.operationId||stored.intentDigest!==expected.intentDigest||stored.bookingId!==expected.bookingId||stored.action!==expected.action||stored.commandId!==expected.commandId||!ID.test(String(stored.receiptId))||!ID.test(String(stored.eventId))||!Number.isSafeInteger(stored.version)||Number(stored.version)<1)throw new Error('BOOKING_OPERATION_REPLAY_CONFLICT');return stored;}
