import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{join}from"node:path";import{createFailClosedEnterpriseBookingPorts,createTestEnterpriseBookingHmacProvider,ENTERPRISE_BOOKING_MONDAY_PINNED_DIGEST,mondayWorldDigest,privacyMinimizedMondayProjection,resetEnterpriseMondayWorld,runtimeSeedEnterpriseMondayWorld,seedEnterpriseMondayWorld,verifyMondayWorldManifest}from"./enterpriseBookingMondayCommissioning.js";import{createEnterpriseMondayHarness}from"./enterpriseBookingMondayHarness.js";import{validateEnterpriseBookingProducer,ENTERPRISE_BOOKING_PRODUCER_SCHEMA}from"./enterpriseBookingProducerRegistry.js";
const raw=JSON.parse(readFileSync(join(__dirname,"..","..","fixtures","monday-booking-world.v1.json"),"utf8"));let count=0;const check=async(name:string,fn:()=>unknown|Promise<unknown>)=>{await fn();console.log(`ok ${++count} - ${name}`)};const now=Date.parse(raw.fixedNow);
void(async()=>{
 await check("manifest seed reset and digest are deterministic",()=>{const verified=verifyMondayWorldManifest(raw),seed=seedEnterpriseMondayWorld(verified,{projectId:"demo-monday",host:"127.0.0.1"}),reset=resetEnterpriseMondayWorld(verified,{projectId:"demo-monday",host:"localhost"});assert.equal(seed.digest,reset.digest);assert.equal(seed.digest,mondayWorldDigest(verified));assert.equal(seed.digest,ENTERPRISE_BOOKING_MONDAY_PINNED_DIGEST);assert.equal(seed.writes+seed.transmissions,0);assert.throws(()=>runtimeSeedEnterpriseMondayWorld(),/RUNTIME_SEED_DISABLED/)});
 await check("producer registry accepts exact HMAC versions one and two",()=>{const base={schema:ENTERPRISE_BOOKING_PRODUCER_SCHEMA,producerId:"ebcp_monday_publisher_0001",authenticatedUid:"service_monday_publisher_0001",allowedContracts:["golfriend.enterprise-booking-correlation-intake.v1"],organizationIds:["org_monday_riverbend"],courseIds:["ex_course_riverbend"],hmacKeyVersion:1,status:"active",effectiveAt:"2026-08-17T00:00:00Z",expiresAt:"2026-08-18T00:00:00Z",version:1},input={authenticatedUid:base.authenticatedUid,claimProducerId:base.producerId,contract:base.allowedContracts[0],courseId:base.courseIds[0],organizationId:base.organizationIds[0],nowMs:now};assert.equal(validateEnterpriseBookingProducer(base,input).hmacKeyVersion,1);assert.equal(validateEnterpriseBookingProducer({...base,hmacKeyVersion:2,version:2},input).hmacKeyVersion,2);for(const changed of[{status:"revoked"},{expiresAt:"2026-08-16T00:00:00Z"},{courseIds:["ex_course_pineview"]},{hmacKeyVersion:3}])assert.throws(()=>validateEnterpriseBookingProducer({...base,...changed}as never,input),/PRODUCER_AUTHORITY_UNAVAILABLE/)});
 await check("test-only HMAC key rotation verifies exact versions",()=>{const provider=createTestEnterpriseBookingHmacProvider({mode:"local_test",keys:{1:"enterprise-monday-v1-00000000000000000000",2:"enterprise-monday-v2-00000000000000000000"}}),event={eventId:"evt"},v1=provider.sign(1,event),v2=provider.sign(2,event);assert.notEqual(v1,v2);assert.equal(provider.verify(1,event,v1),true);assert.equal(provider.verify(2,event,v2),true);assert.equal(provider.verify(1,event,v2),false)});
 await check("production ports fail closed with zero effects",async()=>{const ports=createFailClosedEnterpriseBookingPorts();assert.equal(ports.writes+ports.transmissions+ports.providerCalls,0);for(const port of[ports.producerRegistry,ports.hmac.sign,ports.hmac.verify,ports.memberAuthority,ports.bookingSource,ports.outboxConsumer,ports.messageTransmitter,ports.schedulerEvidence])await assert.rejects(port(),/BOOKING_COMMISSIONING_UNAVAILABLE/);assert.equal(ports.writes+ports.transmissions+ports.providerCalls,0)});
 await check("privacy projection contains no identity contact or economy facts",()=>{const projection=privacyMinimizedMondayProjection(raw),text=JSON.stringify(projection);assert.match(projection.golferRef,/^gfr_/);assert.doesNotMatch(text,/personaId|memberUid|displayName|email|phone|price|payment|refund|commission|invoice|played|check.?in/i)});
 await check("scenario matrix covers isolated outbox replay recovery and no transmission",()=>{const ids=new Set(raw.scenarios.map((item:Raw)=>item.id));for(const id of["course_duplicate_replay","course_changed_action_reuse","course_token_rotation","course_old_token_revoked","course_lost_response_recovery","course_outbox_pending","course_hmac_v1","course_hmac_v2_test_provider","course_hmac_unknown","course_aggregate_isolation","golfer_no_transmission"])assert.ok(ids.has(id));assert.equal(raw.services.every((service:Raw)=>service.transmissionIncluded===false),true)});
 await check("deterministic Enterprise scenario model covers every declared outcome",()=>{const provider=createTestEnterpriseBookingHmacProvider({mode:"local_test",keys:{1:"enterprise-monday-v1-00000000000000000000",2:"enterprise-monday-v2-00000000000000000000"}}),harness=createEnterpriseMondayHarness(raw,provider),scenarios=raw.scenarios.filter((item:Raw)=>item.surface==="enterprise");for(const scenario of scenarios)assert.equal(harness.run(scenario.id),scenario.expected,scenario.id);const snapshot=harness.snapshot();assert.equal(snapshot.transmissions,0);assert.equal(snapshot.writes,0);assert.equal(snapshot.tokenVersion,2)});
 console.log(`enterprise booking Monday world: ${count} checks passed.`);
})().catch(error=>{console.error(error);process.exitCode=1});
type Raw=Record<string,unknown>;
