import test from'node:test';import assert from'node:assert/strict';import{adjudicateDispute,invoiceAdjustment,paymentEvent,reconcilePayment,safeCollectionState,signedDocumentDeliveryAdapter,unavailableDeliveryAdapter,verifySignedProviderEvent}from'./enterpriseReceivablesDomain.js';
const line={lineId:'line_001',organizationId:'org_001',commissionMinor:300,currency:'USD'},dispute={disputeId:'dispute_001',lineId:'line_001',organizationId:'org_001',status:'open'},policy={status:'approved',responseDeadlineAt:'2027-01-31T00:00:00.000Z'},invoice={invoiceId:'invoice_001',invoiceNumber:'ECI-001',organizationId:'org_001',currency:'USD',totalMinor:321};
test('dispute approve reject and partial resolutions are immutable and deadline aware',()=>{for(const[outcome,resolved]of[['approved',0],['rejected',300],['partial_resolution',125]]as const){const d=adjudicateDispute(dispute,line,{outcome,resolvedCommissionMinor:resolved,evidenceRefs:['evidence_001'],reason:'Reviewed evidence',commandId:`command_${outcome}`,decidedAt:'2027-01-15T00:00:00.000Z'},policy);assert.equal(d.resolvedCommissionMinor,resolved);assert.equal(d.deadlineState,'within_deadline');assert.ok(Object.isFrozen(d))}});
test('missing policy evidence and invalid partial resolution fail closed',()=>{assert.throws(()=>adjudicateDispute(dispute,line,{outcome:'approved',evidenceRefs:[],reason:'x',commandId:'command_001',decidedAt:'2027-01-01T00:00:00.000Z'},policy));assert.throws(()=>adjudicateDispute(dispute,line,{outcome:'partial_resolution',resolvedCommissionMinor:300,evidenceRefs:['evidence_001'],reason:'x',commandId:'command_001',decidedAt:'2027-01-01T00:00:00.000Z'},policy))});
test('delivery adapter fails closed and sends only signed document boundary',async()=>{await assert.rejects(unavailableDeliveryAdapter().deliver({},'key_001'),/UNAVAILABLE/);let headers:any;const adapter=signedDocumentDeliveryAdapter({endpoint:'https://sandbox.example.test',secret:'x'.repeat(32),fetchImpl:async(_u:any,i:any)=>{headers=i.headers;return{ok:true,json:async()=>({providerReceiptId:'delivery_receipt_001',deliveredAt:'2027-01-01T00:00:00.000Z'})}as any}});assert.equal((await adapter.deliver({invoiceId:'invoice_001'},'key_001')).providerReceiptId,'delivery_receipt_001');assert.match(headers['x-golfriend-signature'],/^[a-f0-9]{64}$/)});
test('payment settlement failure refund and overpayment reconcile only from evidence',()=>{const e=(kind:string,amountMinor:number,eventId:string)=>paymentEvent({kind,amountMinor,eventId,invoiceId:'invoice_001',currency:'USD',providerEvidenceRef:`provider_${eventId}`,occurredAt:'2027-01-01T00:00:00.000Z'},invoice);assert.equal(reconcilePayment(invoice,[e('payment_succeeded',321,'event_paid'),e('settlement_confirmed',321,'event_settled')]).status,'settled');assert.equal(reconcilePayment(invoice,[e('payment_succeeded',400,'event_over')]).status,'overpaid');assert.equal(reconcilePayment(invoice,[e('payment_failed',0,'event_fail')]).status,'failed');assert.equal(reconcilePayment(invoice,[e('payment_succeeded',321,'event_paid'),e('refund_confirmed',100,'event_refund')]).netPaidMinor,221)});
test('credit note refund cancellation overpayment return and write-off link immutably to invoice',()=>{for(const kind of['credit_note','refund','cancellation','overpayment_return','write_off']){const a=invoiceAdjustment(invoice,{kind,amountMinor:kind==='overpayment_return'?400:100,providerEvidenceRef:`provider_${kind}`,reason:'Approved evidence',commandId:`command_${kind}`,createdAt:'2027-01-01T00:00:00.000Z'});assert.equal(a.invoiceId,'invoice_001');assert.equal(a.automaticEntitlementMutation,false);assert.equal(a.automaticFinancialMutation,false)}});
test('overdue and failed states never trigger destructive action',()=>{const state=safeCollectionState(invoice,{status:'failed'},'2027-02-01T00:00:00.000Z',{status:'approved',dueAt:'2027-01-01T00:00:00.000Z'});assert.equal(state.status,'overdue_failed');assert.equal(state.destructiveAction,false);assert.equal('writeOffRequiresDirector'in state&&state.writeOffRequiresDirector,true)});
test('signed payment events reject stale or altered signatures',async()=>{const body=Buffer.from('{}'),secret='x'.repeat(32),timestamp=2000000000,{createHmac}=await import('node:crypto'),signature=createHmac('sha256',secret).update(`${timestamp}.`).update(body).digest('hex');assert.equal(verifySignedProviderEvent(secret,timestamp,body,signature,timestamp),true);assert.throws(()=>verifySignedProviderEvent(secret,timestamp-301,body,signature,timestamp))});
