import {createHash} from "node:crypto";
import {buildEnterpriseCorrelationEvent,ENTERPRISE_CORRELATION_STATES} from "./enterpriseBookingCorrelation.js";
type Raw=Record<string,unknown>;const ID=/^[A-Za-z0-9_-]{8,200}$/;const exact=(v:Raw,k:string[])=>Object.keys(v).length===k.length&&k.every(x=>Object.prototype.hasOwnProperty.call(v,x));
export const ENTERPRISE_BOOKING_TRANSITION_SCHEMA="golfriend.enterprise-booking-transition.v2" as const;
export const COURSE_TRANSITION_STATES=["course_confirmed","alternative_proposed","cancellation_accepted","cancellation_declined"] as const;
export function validateEnterpriseBookingTransition(raw:Raw){
 if(!exact(raw,["schema","bookingId","commandId","expectedVersion","state","alternativeSlot"])||raw.schema!==ENTERPRISE_BOOKING_TRANSITION_SCHEMA||!ID.test(String(raw.bookingId))||!ID.test(String(raw.commandId))||!Number.isSafeInteger(raw.expectedVersion)||Number(raw.expectedVersion)<1||!COURSE_TRANSITION_STATES.includes(raw.state as never))throw new Error("TRANSITION_INVALID");
 if((raw.state==="alternative_proposed")!==!!raw.alternativeSlot)throw new Error("TRANSITION_INVALID");const slot=raw.alternativeSlot as Raw|null;if(slot&&!exact(slot,["slotId","date","time","timeZone","slotVersion"]))throw new Error("TRANSITION_INVALID");
 return Object.freeze({bookingId:String(raw.bookingId),commandId:String(raw.commandId),expectedVersion:Number(raw.expectedVersion),state:raw.state as typeof COURSE_TRANSITION_STATES[number],alternativeSlot:slot?Object.freeze({slotId:String(slot.slotId),date:String(slot.date),time:String(slot.time),timeZone:String(slot.timeZone),slotVersion:Number(slot.slotVersion)}):null});
}
export function enterpriseBookingTransitionDigest(value:ReturnType<typeof validateEnterpriseBookingTransition>){return createHash("sha256").update(JSON.stringify(value)).digest("hex")}
export function enterpriseBookingTransitionReceiptId(bookingId:string,commandId:string){return`ebctr_${createHash("sha256").update(`${bookingId}|${commandId}`).digest("hex").slice(0,40)}`}
export function buildEnterpriseBookingOutbox(input:Readonly<{request:ReturnType<typeof validateEnterpriseBookingTransition>;booking:Raw;correlation:Raw;occurredAt:string;expiresAt:string;secret:string}>){
 const b=input.booking,c=input.correlation;if(b.schema!=="golfriend.enterprise-correlated-booking.v2"||c.schema!=="golfriend.enterprise-booking-correlation.v1"||b.correlationId!==c.correlationId||b.bookingId!==input.request.bookingId||b.version!==input.request.expectedVersion||c.version!==b.version||c.status!==b.status||String((c.course as Raw)?.courseId)!==String(b.courseId)||!ENTERPRISE_CORRELATION_STATES.includes(String(b.status) as never))throw new Error("TRANSITION_SOURCE_INVALID");
 const allowed:Record<string,string[]>= {course_reviewing:["course_confirmed","alternative_proposed"],cancellation_requested:["cancellation_accepted","cancellation_declined"]};if(!allowed[String(b.status)]?.includes(input.request.state))throw new Error("TRANSITION_STATE_INVALID");
 const nextVersion=Number(b.version)+1,event=buildEnterpriseCorrelationEvent({correlationId:String(c.correlationId),bookingId:String(b.bookingId),bookingVersion:nextVersion,f7RequestId:String((c.f7Request as Raw).requestId),f7Version:Number((c.f7Request as Raw).version),courseId:String(b.courseId),courseVersion:Number(b.courseVersion),state:input.request.state,commandId:input.request.commandId,sourceEventVersion:Number(c.version)+1,occurredAt:input.occurredAt,issuedAt:input.occurredAt,expiresAt:input.expiresAt,alternativeSlot:input.request.alternativeSlot,integritySecret:input.secret,hmacKeyVersion:1});
 return Object.freeze({digest:enterpriseBookingTransitionDigest(input.request),nextVersion,event,receiptId:enterpriseBookingTransitionReceiptId(String(b.bookingId),input.request.commandId)});
}
