import{createHash}from"node:crypto";
export const ENTERPRISE_MEMBER_MANAGEMENT_SCHEMA="golfriend.enterprise-course-member-management.v1" as const;
export const MEMBER_STATES=["invitation_draft","awaiting_delivery_provider","invited","joined","active","inactive","change_requested","conflict_review","unavailable"]as const;
export const MEMBER_LOCALES=["en","th","ko","ja","zh","es","fr","de"]as const;
export const CHANGE_TYPES=["deactivate","reactivate","role_change"]as const;
export const COURSE_MEMBER_ROLES=["member","junior_member","honorary_member","guest_member"]as const;
export const CSV_HEADER="memberReference,displayName,contactReference,locale,purpose";
export const MAX_IMPORT_ROWS=100,MAX_CSV_BYTES=65536;
const id=(v:unknown,label:string)=>{const x=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw Error(`${label}_INVALID`);return x};
const text=(v:unknown,label:string,max:number)=>{const x=String(v||"").trim();if(!x||x.length>max||/[\u0000-\u001f\u007f]/.test(x))throw Error(`${label}_INVALID`);return x};
export const memberDigest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export const scopeId=(o:string,p:string,c:string)=>`emms_${memberDigest([o,p,c]).slice(0,32)}`;
export const commandId=(uid:string,command:string,action:string)=>`emmc_${memberDigest([uid,command,action]).slice(0,32)}`;
export const receiptId=(scope:string,command:string,action:string)=>`emmr_${memberDigest([scope,command,action]).slice(0,32)}`;
export function strictCommand(v:unknown){return id(v,"COMMAND")}
export function strictVersion(v:unknown){if(!Number.isSafeInteger(v)||Number(v)<0)throw Error("VERSION_INVALID");return Number(v)}
export function normalizeLocale(v:unknown){const x=String(v||"");if(!MEMBER_LOCALES.includes(x as any))throw Error("LOCALE_INVALID");return x}
export function normalizePurpose(v:unknown){return text(v,"PURPOSE",500)}
export function normalizeInvitation(raw:any):any{if(raw&&raw.currentMemberVersion!==undefined)return normalizeResend(raw);const allowed=new Set(["memberReference","displayName","contactReference","locale","purpose","currentCourseVersion"]);if(!raw||Object.keys(raw).some(k=>!allowed.has(k)))throw Error("UNDECLARED_FIELD");return{memberReference:id(raw.memberReference,"MEMBER_REFERENCE"),displayName:text(raw.displayName,"DISPLAY_NAME",120),contactReference:id(raw.contactReference,"CONTACT_REFERENCE"),locale:normalizeLocale(raw.locale),purpose:normalizePurpose(raw.purpose),currentCourseVersion:strictVersion(raw.currentCourseVersion)}}
export function normalizeResend(raw:any){const allowed=new Set(["memberReference","locale","purpose","currentCourseVersion","currentMemberVersion"]);if(!raw||Object.keys(raw).some(k=>!allowed.has(k)))throw Error("UNDECLARED_FIELD");return{memberReference:id(raw.memberReference,"MEMBER_REFERENCE"),locale:normalizeLocale(raw.locale),purpose:normalizePurpose(raw.purpose),currentCourseVersion:strictVersion(raw.currentCourseVersion),currentMemberVersion:strictVersion(raw.currentMemberVersion)}}
export function normalizeChange(raw:any){const allowed=new Set(["type","memberReference","requestedRole","locale","purpose","currentCourseVersion","currentMemberVersion"]);if(!raw||Object.keys(raw).some(k=>!allowed.has(k)))throw Error("UNDECLARED_FIELD");const type=String(raw.type||"");if(!CHANGE_TYPES.includes(type as any))throw Error("CHANGE_TYPE_INVALID");const role=raw.requestedRole==null?null:String(raw.requestedRole);if(type==="role_change"&&!COURSE_MEMBER_ROLES.includes(role as any)||type!=="role_change"&&role)throw Error("ROLE_INVALID");return{type,memberReference:id(raw.memberReference,"MEMBER_REFERENCE"),requestedRole:role,locale:normalizeLocale(raw.locale),purpose:normalizePurpose(raw.purpose),currentCourseVersion:strictVersion(raw.currentCourseVersion),currentMemberVersion:strictVersion(raw.currentMemberVersion)}}
function cells(line:string){const out:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(ch===","&&!quoted){out.push(value);value=""}else value+=ch}if(quoted)throw Error("CSV_QUOTE_INVALID");out.push(value);return out}
function safeCell(v:string,label:string,max:number){const x=text(v,label,max);if(/^[=+@-]/.test(x)||/<script|javascript:|data:/i.test(x))throw Error("CSV_EXECUTABLE_REJECTED");return x}
export function previewCsv(raw:unknown){if(typeof raw!=="string"||Buffer.byteLength(raw,"utf8")>MAX_CSV_BYTES)throw Error("CSV_SIZE_INVALID");const lines=raw.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.shift()!==CSV_HEADER)throw Error("CSV_SCHEMA_INVALID");if(!lines.length||lines.length>MAX_IMPORT_ROWS)throw Error("CSV_ROW_LIMIT");const seen=new Set<string>(),contacts=new Set<string>(),rows=lines.map((line,index)=>{const c=cells(line);if(c.length!==5)throw Error("CSV_SHAPE_INVALID");const memberReference=id(safeCell(c[0],"MEMBER_REFERENCE",128),"MEMBER_REFERENCE"),displayName=safeCell(c[1],"DISPLAY_NAME",120),contactReference=id(safeCell(c[2],"CONTACT_REFERENCE",128),"CONTACT_REFERENCE"),locale=normalizeLocale(c[3].trim()),purpose=safeCell(c[4],"PURPOSE",500),key=memberReference.toLowerCase(),contact=contactReference.toLowerCase();if(seen.has(key)||contacts.has(contact))throw Error("CSV_DUPLICATE_IDENTITY");seen.add(key);contacts.add(contact);return{row:index+1,memberReference,displayName,contactReference,locale,purpose}});return{schema:CSV_HEADER,rowCount:rows.length,rows,digest:memberDigest(rows)}}
export function minimumMember(raw:any){if(!raw||!MEMBER_STATES.includes(raw.state)||!Number.isSafeInteger(raw.version)||raw.version<1)throw Error("MEMBER_MALFORMED");return{memberReference:id(raw.memberReference,"MEMBER_REFERENCE"),displayName:text(raw.displayName,"DISPLAY_NAME",120),role:raw.role?text(raw.role,"ROLE",80):null,state:raw.state,locale:normalizeLocale(raw.locale),version:raw.version,updatedAt:raw.updatedAt?.toDate?.()?.toISOString?.()??null}}
export function minimumRequest(raw:any){if(!raw||!MEMBER_STATES.includes(raw.status)||!Number.isSafeInteger(raw.version)||raw.version<1||!["invitation","resend","change","csv_import"].includes(raw.action))throw Error("REQUEST_MALFORMED");return{requestId:id(raw.requestId,"REQUEST"),action:raw.action,status:raw.status,version:raw.version,memberReference:raw.memberReference?id(raw.memberReference,"MEMBER_REFERENCE"):null,locale:raw.locale?normalizeLocale(raw.locale):null,purpose:raw.purpose?text(raw.purpose,"PURPOSE",500):null,expiresAt:raw.expiresAt?.toDate?.()?.toISOString?.()??null}}
export function minimumReceipt(raw:any,receiptDocumentId:string){if(!raw||raw.immutable!==true||typeof raw.action!=="string"||!raw.action||raw.action.length>80)throw Error("RECEIPT_MALFORMED");return{receiptId:id(receiptDocumentId,"RECEIPT"),action:raw.action,occurredAt:raw.occurredAt?.toDate?.()?.toISOString?.()??null,immutable:true as const}}
export function page(items:any[],limit:number,binding:string,cursor?:string){if(!Number.isInteger(limit)||limit<1||limit>50||!/^[a-f0-9]{64}$/.test(binding))throw Error("LIMIT_INVALID");const sorted=[...items].sort((a,b)=>String(a.displayName).localeCompare(String(b.displayName),"en")||String(a.memberReference).localeCompare(String(b.memberReference)));let start=0;if(cursor){const i=Array.from({length:sorted.length},(_,n)=>n).find(n=>memberDigest([binding,n+1])===cursor);if(i==null)throw Error("CURSOR_INVALID");start=i+1}const result=sorted.slice(start,start+limit),next=start+limit;return{items:result,nextCursor:next<sorted.length?memberDigest([binding,next]):null}}
export function invitationTransition(status:unknown,version:unknown,expected:unknown,expired:boolean){if(status!=="invitation_draft"||strictVersion(version)!==strictVersion(expected)||expired)throw Error(expired?"DRAFT_EXPIRED":"DRAFT_STALE");return{status:"awaiting_delivery_provider"as const,version:Number(version)+1}}
