import {createHash,createHmac,timingSafeEqual} from "node:crypto";

export const ENTERPRISE_BOOKING_MONDAY_PORTS_SCHEMA="golfriend.enterprise-booking-commissioning-ports.v1" as const;
export const ENTERPRISE_BOOKING_MONDAY_PINNED_DIGEST="243013439066e863f6db23d98045e029164a2952647cbd958c456ca97e421380" as const;
type KeyVersion=1|2;type Raw=Record<string,unknown>;
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.keys(value as Raw).sort().map(key=>`${JSON.stringify(key)}:${stable((value as Raw)[key])}`).join(",")}}`:JSON.stringify(value);
const unavailable=():never=>{throw new Error("BOOKING_COMMISSIONING_UNAVAILABLE")};
const exact=(value:unknown,keys:string[])=>!!value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key));
const hex=(value:string)=>/^[a-f0-9]{64}$/.test(value);
const hasForbiddenKey=(value:unknown):boolean=>Array.isArray(value)?value.some(hasForbiddenKey):!!value&&typeof value==="object"&&Object.entries(value as Raw).some(([key,nested])=>/^(memberUid|displayName|nickname|email|phone|stripeCustomer|paymentIntent)$/i.test(key)||hasForbiddenKey(nested));

export function createFailClosedEnterpriseBookingPorts(){const deny=async()=>unavailable();return Object.freeze({schema:ENTERPRISE_BOOKING_MONDAY_PORTS_SCHEMA,state:"uncommissioned",producerRegistry:deny,hmac:Object.freeze({sign:deny,verify:deny}),memberAuthority:deny,bookingSource:deny,outboxConsumer:deny,messageTransmitter:deny,schedulerEvidence:deny,writes:0,transmissions:0,providerCalls:0});}

export function createTestEnterpriseBookingHmacProvider(input:{mode:string;keys:Readonly<Record<string,string>>}){
 if(input.mode!=="local_test"||!exact(input.keys as Raw,["1","2"])||!Object.values(input.keys).every(value=>typeof value==="string"&&value.length>=32))unavailable();
 const secret=(version:KeyVersion)=>{const value=input.keys[String(version)];if(!value)unavailable();return value};
 return Object.freeze({schema:"golfriend.enterprise-booking-hmac-provider.test.v1",versions:Object.freeze([1,2]as const),sign(version:KeyVersion,value:unknown){return createHmac("sha256",secret(version)).update(stable(value)).digest("hex")},verify(version:KeyVersion,value:unknown,signature:string){if(!hex(signature))return false;const expected=this.sign(version,value);return timingSafeEqual(Buffer.from(expected,"hex"),Buffer.from(signature,"hex"))}});
}

export function mondayWorldDigest(value:unknown){return createHash("sha256").update(stable(value)).digest("hex")}

export function verifyMondayWorldManifest(raw:Raw){
 const keys=["schema","fixtureId","seed","fixedNow","sourceIdentityCommit","mappingAuthority","courseCompatibility","runtime","identities","services","courses","bookingRequest","economicTruth","commissioningPorts","locales","scenarios"];
 if(!exact(raw,keys)||raw.schema!=="golfriend.booking-monday-world.v1"||raw.sourceIdentityCommit!=="ce37bf542d771520198695450b7bab3ac3e78c16"||!Number.isFinite(Date.parse(String(raw.fixedNow)))||!Array.isArray(raw.identities)||raw.identities.length!==11||new Set(raw.identities.map((item:Raw)=>item.role)).size!==11||!Array.isArray(raw.courses)||raw.courses.length!==11||new Set(raw.courses.map((item:Raw)=>item.courseId)).size!==11||!Array.isArray(raw.scenarios)||raw.scenarios.length!==52||new Set(raw.scenarios.map((item:Raw)=>item.id)).size!==52||raw.scenarios.some((item:Raw)=>!exact(item,["id","surface","expected"])||!["golfer","enterprise","economy"].includes(String(item.surface)))||JSON.stringify(raw.locales)!==JSON.stringify(["en","th","ko","ja","zh","es","fr","de"]))throw new Error("MONDAY_WORLD_INVALID");
 const runtime=raw.runtime as Raw,economy=raw.economicTruth as Raw,mapping=raw.mappingAuthority as Raw,identities=raw.identities as Raw[],courses=raw.courses as Raw[],identityMapping=identities.map(item=>({role:item.role,personaId:item.personaId,golferRef:item.golferRef??null,staffRef:item.staffRef??null})),courseMapping=courses.map(item=>({courseId:item.courseId,fixture:item.fixture,version:item.version})),mappedCourses=[...((mapping.existingCanonicalCourseIds as string[])??[]),...((mapping.fixtureOnlyCourseIds as string[])??[])],request=raw.bookingRequest as Raw,consent=request.contactConsent as Raw;
 const alias=mapping.courseAlias as Raw;
 const identityInvalid=identities.some(item=>{const keys=item.golferRef?(item.role==="stale_golfer_authority"?["role","personaId","golferRef","memberState","bindingState","authorityVersion","currentAuthorityVersion","teeBalance"]:["role","personaId","golferRef","memberState","bindingState","authorityVersion","teeBalance"]):["role","personaId","staffRef","authorityState","courseIds"];return!exact(item,keys)||typeof item.personaId!=="string"||(!item.golferRef&&!item.staffRef)||(Array.isArray(item.courseIds)&&item.courseIds.some(courseId=>!mappedCourses.includes(String(courseId))))});
 const courseInvalid=courses.some(item=>!exact(item,["courseId","fixture","version","status","country","timeZone","coordinates","providerState","contactPreferences","thirdPartyBookingUrl","profileCorrectionOfVersion"])||!/^ex_course_[a-z0-9_]+$/.test(String(item.courseId))||!Number.isSafeInteger(item.version)||Number(item.version)<1);
 if(!exact(mapping,["schema","version","identityGraphCommit","courseSeedCommit","courseAlias","identityMappingDigest","courseMappingDigest","existingCanonicalCourseIds","fixtureOnlyCourseIds","catalogueCommissioned","heuristicInference"])||!exact(alias,["sourceAlias","canonicalCourseId","sourceCommit"])||mapping.schema!=="golfriend.booking-monday-world-mapping.v1"||mapping.version!==1||alias.sourceAlias!=="course-ew-burapha-01"||alias.canonicalCourseId!=="ex_course_riverbend"||alias.sourceCommit!==mapping.courseSeedCommit||new Set(mappedCourses).size!==courses.length||courses.some(item=>!mappedCourses.includes(String(item.courseId)))||identityInvalid||courseInvalid||!exact(consent,["granted","scope","contactValueStored"])||consent.granted!==true||consent.scope!==request.contactPreference||consent.contactValueStored!==false)throw new Error("MONDAY_WORLD_MAPPING_INVALID");
 if(runtime.localTestOnly!==true||runtime.allowedProjectPrefix!=="demo-"||runtime.loopbackOnly!==true||runtime.runtimeSeedingEnabled!==false||runtime.productionWrites!==0||runtime.providerTransmissions!==0||runtime.credentialsIncluded!==false||economy.golfriendBookingPayment!==false||economy.stripe!==false||economy.escrow!==false||economy.refundProcessing!==false||economy.bookingCommissionRecognized!==false||economy.messageRevenue!==false||economy.coursePricePayableTo!=="course"||economy.separateTeeActionAuthority!=="EconomyConfig"||economy.separateTeeActionIsCoursePayment!==false||economy.cancellationCreatesRefund!==false||mapping.identityGraphCommit!==raw.sourceIdentityCommit||mapping.courseSeedCommit!=="1df39a958dc82244b879ac50f3d616db2fe66ae1"||mapping.identityMappingDigest!==mondayWorldDigest(identityMapping)||mapping.courseMappingDigest!==mondayWorldDigest(courseMapping)||mapping.catalogueCommissioned!==false||mapping.heuristicInference!==false)throw new Error("MONDAY_WORLD_BOUNDARY_INVALID");
 const price=request.coursePrice as Raw;if(!exact(price,["amountMinor","currency","authority","payableTo","golfriendRevenue"])||price.authority!=="course_or_provider"||price.payableTo!=="course"||price.golfriendRevenue!==false||JSON.stringify(economy.commissionPrerequisites)!==JSON.stringify(["signed_partner_contract","independently_verified_played_evidence"]))throw new Error("MONDAY_WORLD_ECONOMIC_BOUNDARY_INVALID");
 if(hasForbiddenKey(raw)||/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|\+\d{7,}|sk_live|sk_test|PRIVATE KEY/i.test(JSON.stringify(raw)))throw new Error("MONDAY_WORLD_PRIVATE_OR_SECRET_FACT");return Object.freeze(JSON.parse(JSON.stringify(raw)) as Raw);
}

export function seedEnterpriseMondayWorld(raw:Raw,input:{projectId:string;host:string}){if(!input.projectId.startsWith("demo-")||!["127.0.0.1","localhost","::1"].includes(input.host))unavailable();const manifest=verifyMondayWorldManifest(raw),manifestDigest=mondayWorldDigest(manifest);if(manifestDigest!==ENTERPRISE_BOOKING_MONDAY_PINNED_DIGEST)throw new Error("MONDAY_WORLD_PINNED_DIGEST_MISMATCH");return Object.freeze({schema:"golfriend.enterprise-booking-monday-seed.v1",mode:"memory_only",digest:manifestDigest,manifest,writes:0,transmissions:0})}
export function resetEnterpriseMondayWorld(raw:Raw,input:{projectId:string;host:string}){const reseeded=seedEnterpriseMondayWorld(raw,input);return Object.freeze({schema:"golfriend.enterprise-booking-monday-reset.v1",reset:"memory_only",reseeded,digest:reseeded.digest,writes:0,transmissions:0})}
export function runtimeSeedEnterpriseMondayWorld():never{throw new Error("MONDAY_WORLD_RUNTIME_SEED_DISABLED")}

export function privacyMinimizedMondayProjection(raw:Raw){const manifest=verifyMondayWorldManifest(raw),request=manifest.bookingRequest as Raw,identity=(manifest.identities as Raw[])[0];return Object.freeze({schema:"golfriend.enterprise-booking-monday-projection.v1",correlationId:String(request.correlationId),golferRef:String(identity.golferRef),courseId:String(request.courseId),courseVersion:Number(request.courseVersion),state:"course_reviewing",privacy:"opaque_only"})}
