import*as admin from"firebase-admin";import{createHash}from"node:crypto";import{HttpsError,onCall}from"firebase-functions/v2/https";import{resolveEnterpriseCourseAuthority}from"./enterpriseAuthorityRuntime.js";import{acceptanceIsCurrent,agreementDigest,commandDocumentId,deriveTrialState,ENTERPRISE_AGREEMENT_SCHEMA,ENTERPRISE_ONBOARDING_SCHEMA,ENTERPRISE_REVIEW_SCHEMA,normalizeContext,normalizeDraft,receiptDocumentId,requireSubmitReady,validateEconomyConfig,validateTrialOffer}from"./enterpriseOnboardingDomain.js";
if(!admin.apps.length)admin.initializeApp();const db=admin.firestore(),server=()=>admin.firestore.FieldValue.serverTimestamp();
const uid=(r:any)=>{if(!r.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");return String(r.auth.uid)},command=(v:any)=>{const x=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,127}$/.test(x))throw new HttpsError("invalid-argument","Command ID invalid.");return x},hash=(v:any)=>createHash("sha256").update(JSON.stringify(v)).digest("hex"),contentHash=(v:string)=>createHash("sha256").update(v,"utf8").digest("hex");
async function scoped(r:any,capability="enterprise_onboarding"){const actor=uid(r),context=normalizeContext(r.data?.context);const authority=await resolveEnterpriseCourseAuthority(actor,context.membershipId,context.organizationId,context.propertyId,context.courseId,capability);return{actor,context,authority,applicationId:`eoa_${hash([context.organizationId,context.propertyId,context.courseId]).slice(0,32)}`}}
async function policy(){const[e,a]=await Promise.all([db.collection("enterprise_economy_config").doc("current").get(),db.collection("enterprise_agreement_policies").doc("current").get()]);if(!e.exists||!a.exists)throw new HttpsError("unavailable","Authoritative agreement configuration unavailable.");let economy;try{economy=validateEconomyConfig(e.data())}catch{throw new HttpsError("unavailable","Economy configuration unavailable.")}const agreement=a.data()||{},localized=agreement.localizedContent;if(agreement.schema!==ENTERPRISE_AGREEMENT_SCHEMA||agreement.status!=="active"||!localized||!["en","th","ko","ja","zh","es","fr","de"].every(x=>typeof localized[x]==="string"&&localized[x].trim())||contentHash(localized.en)!==agreement.canonicalContentDigest)throw new HttpsError("unavailable","Agreement configuration unavailable.");return{economy,agreement}}
const appRef=(id:string)=>db.collection("enterprise_onboarding_applications").doc(id);const receiptRef=(id:string)=>db.collection("enterprise_onboarding_receipts").doc(id);const iso=(v:any)=>v?.toDate?.().toISOString()||null;
// @ts-expect-error Firestore data() does not narrow through the compact exists branch below.
async function projection(a:any){const[p,trial]=await Promise.all([appRef(a.applicationId).get(),db.collection("enterprise_trials").doc(a.applicationId).get()]),x=p.data();if(!p.exists)return{schema:ENTERPRISE_ONBOARDING_SCHEMA,state:"empty",application:null,trial:null};if(x?.applicationId!==a.applicationId||x?.organizationId!==a.context.organizationId||x?.propertyId!==a.context.propertyId||x?.courseId!==a.context.courseId||x?.actorMembershipId!==a.context.membershipId||!Number.isSafeInteger(x?.version)||x.version<1)return{schema:ENTERPRISE_ONBOARDING_SCHEMA,state:"unavailable",application:null,trial:null};const publicApp={applicationId:a.applicationId,organizationId:x.organizationId,propertyId:x.propertyId,courseId:x.courseId,status:x.status,version:x.version,preferredLocale:x.preferredLocale,requestedTrialDays:x.requestedTrialDays,agreementAcceptanceReceiptId:x.agreementAcceptanceReceiptId||null,reviewReference:x.reviewReference||null,updatedAt:iso(x.updatedAt)};const t=trial.data();if(trial.exists&&(t?.applicationId!==a.applicationId||t?.organizationId!==a.context.organizationId||t?.propertyId!==a.context.propertyId||t?.courseId!==a.context.courseId||![30,90].includes(t?.durationDays)||!t?.activationReceiptId))return{schema:ENTERPRISE_ONBOARDING_SCHEMA,state:"unavailable",application:publicApp,trial:null};return{schema:ENTERPRISE_ONBOARDING_SCHEMA,state:x.status==="suspended"?"suspended":"current",application:publicApp,trial:trial.exists?{trialId:trial.id,status:deriveTrialState(t,Date.now()),durationDays:t?.durationDays,startsAt:iso(t?.startsAt),endsAt:iso(t?.endsAt),policyVersion:t?.policyVersion,activationReceiptId:t?.activationReceiptId}:null}}
export const getEnterpriseCourseOnboardingV1=onCall({enforceAppCheck:true},async r=>projection(await scoped(r)));
export const saveEnterpriseCourseOnboardingDraftV1=onCall({enforceAppCheck:true},async r=>{const a=await scoped(r),cid=command(r.data?.commandId),draft=normalizeDraft(r.data?.draft),expected=Number(r.data?.expectedVersion||0),digest=hash({context:a.context,draft,expected}),cmdRef=db.collection("enterprise_onboarding_commands").doc(commandDocumentId(a.actor,cid,"save"));await db.runTransaction(async tx=>{const[current,prior,profileAttempt]=await Promise.all([tx.get(appRef(a.applicationId)),tx.get(cmdRef),tx.get(db.collection("enterprise_course_profile_attempts").doc(draft.courseProfileAttemptId))]);if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");return}const profile=profileAttempt.data()||{};if(!profileAttempt.exists||profile.organizationId!==a.context.organizationId||profile.propertyId!==a.context.propertyId||profile.courseId!==a.context.courseId||!['pending','approved'].includes(profile.state))throw new HttpsError("failed-precondition","Authoritative course profile attempt unavailable.");if(Number(current.data()?.version||0)!==expected)throw new HttpsError("aborted","STALE_VERSION");if(current.exists&&!['draft','changes_requested'].includes(current.data()?.status))throw new HttpsError("failed-precondition","Application locked.");const next=expected+1;tx.set(appRef(a.applicationId),{schema:ENTERPRISE_ONBOARDING_SCHEMA,applicationId:a.applicationId,...a.context,...draft,status:current.data()?.status||"draft",version:next,actorMembershipId:a.context.membershipId,agreementAcceptanceReceiptId:null,updatedAt:server(),createdAt:current.data()?.createdAt||server()},{merge:false});tx.create(cmdRef,{commandId:cid,digest,action:"save",applicationId:a.applicationId,resultVersion:next,immutable:true,createdAt:server()})});return projection(a)});
async function buildPreview(a:any,data:any){const{economy,agreement}=await policy(),offerId=String(data?.trialOfferId||""),days=Number(data?.trialDays),offer=await db.collection("enterprise_trial_offers").doc(offerId).get();let trial;try{trial=validateTrialOffer(offer.data(),a.context.organizationId,days as any,Date.now())}catch{throw new HttpsError("failed-precondition","Authorized trial offer unavailable.")}const input={agreementId:String(agreement.agreementId),version:Number(agreement.version),canonicalContentDigest:String(agreement.canonicalContentDigest),organizationId:a.context.organizationId,propertyId:a.context.propertyId,courseId:a.context.courseId,representativeMembershipId:a.context.membershipId,acceptedLocale:String(data?.locale),bookingCommissionPolicyVersion:economy.policyVersion,bookingCommissionBps:economy.bookingCommissionBps,trialPolicyVersion:trial.policyVersion,trialDays:days,dataUseTermsVersion:String(agreement.dataUseTermsVersion),memberObligationsVersion:String(agreement.memberObligationsVersion),tournamentObligationsVersion:String(agreement.tournamentObligationsVersion),effectiveAt:String(agreement.effectiveAt)};if(!agreement.localizedContent[input.acceptedLocale])throw new HttpsError("invalid-argument","Locale unavailable.");return{schema:ENTERPRISE_AGREEMENT_SCHEMA,previewOnly:true,...input,content:agreement.localizedContent[input.acceptedLocale],canonicalContent:agreement.localizedContent.en,contentDigest:agreementDigest(input),legalReviewRequired:true,trialOfferId:offerId}}
export const previewEnterpriseAgreementV1=onCall({enforceAppCheck:true},async r=>buildPreview(await scoped(r),r.data));
export const acceptEnterpriseAgreementV1=onCall({enforceAppCheck:true},async r=>{const a=await scoped(r),cid=command(r.data?.commandId),preview=await buildPreview(a,r.data);if(r.data?.explicitlyAccepted!==true||r.data?.contentDigest!==preview.contentDigest)throw new HttpsError("failed-precondition","Explicit current agreement acceptance required.");const digest=hash(preview),rid=receiptDocumentId(a.applicationId,cid,"agreement_accept"),cmdRef=db.collection("enterprise_onboarding_commands").doc(commandDocumentId(a.actor,cid,"agreement_accept"));await db.runTransaction(async tx=>{const[app,prior]=await Promise.all([tx.get(appRef(a.applicationId)),tx.get(cmdRef)]);if(!app.exists)throw new HttpsError("failed-precondition","Draft required.");if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");return}tx.create(receiptRef(rid),{receiptId:rid,applicationId:a.applicationId,...a.context,actorUid:a.actor,actorMembershipId:a.context.membershipId,agreementId:preview.agreementId,agreementVersion:preview.version,acceptedLocale:preview.acceptedLocale,canonicalContentDigest:preview.canonicalContentDigest,contentDigest:preview.contentDigest,bookingCommissionPolicyVersion:preview.bookingCommissionPolicyVersion,bookingCommissionBps:preview.bookingCommissionBps,trialOfferId:preview.trialOfferId,trialPolicyVersion:preview.trialPolicyVersion,trialDays:preview.trialDays,acceptanceServerTimestamp:server(),immutable:true});tx.update(appRef(a.applicationId),{agreementAcceptanceReceiptId:rid,requestedTrialDays:preview.trialDays,trialOfferId:preview.trialOfferId,updatedAt:server()});tx.create(cmdRef,{commandId:cid,digest,action:"agreement_accept",receiptId:rid,immutable:true,createdAt:server()})});return{success:true,receiptId:rid,restarted:false}});
export const submitEnterpriseCourseOnboardingV1=onCall({enforceAppCheck:true},async r=>{
 const a=await scoped(r),cid=command(r.data?.commandId),digest=hash({applicationId:a.applicationId}),cmdRef=db.collection("enterprise_onboarding_commands").doc(commandDocumentId(a.actor,cid,"submit")),rid=receiptDocumentId(a.applicationId,cid,"submitted");
 await db.runTransaction(async tx=>{
  const app=await tx.get(appRef(a.applicationId)),x=app.data();if(!app.exists)throw new HttpsError("failed-precondition","Draft required.");
  const acceptanceId=String(x?.agreementAcceptanceReceiptId||""),offerId=String(x?.trialOfferId||"");
  const[prior,acceptance,economySnap,agreementSnap,offer]=await Promise.all([tx.get(cmdRef),tx.get(receiptRef(acceptanceId)),tx.get(db.collection("enterprise_economy_config").doc("current")),tx.get(db.collection("enterprise_agreement_policies").doc("current")),tx.get(db.collection("enterprise_trial_offers").doc(offerId))]);
  if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");return}
  try{requireSubmitReady(x)}catch{throw new HttpsError("failed-precondition","Application incomplete.")}
  if(!acceptance.exists||!economySnap.exists||!agreementSnap.exists)throw new HttpsError("failed-precondition","Current agreement evidence unavailable.");
  let economy;try{economy=validateEconomyConfig(economySnap.data())}catch{throw new HttpsError("failed-precondition","Current economy policy unavailable.")}
  const accepted=acceptance.data()||{},agreement=agreementSnap.data()||{};
  let trial;try{trial=validateTrialOffer(offer.data(),a.context.organizationId,Number(x?.requestedTrialDays)as any,Date.now())}catch{throw new HttpsError("failed-precondition","Current trial offer unavailable.")}
  const currentAcceptance={agreementId:String(agreement.agreementId),version:Number(agreement.version),canonicalContentDigest:String(agreement.canonicalContentDigest),organizationId:a.context.organizationId,propertyId:a.context.propertyId,courseId:a.context.courseId,representativeMembershipId:a.context.membershipId,acceptedLocale:String(accepted.acceptedLocale),bookingCommissionPolicyVersion:economy.policyVersion,bookingCommissionBps:economy.bookingCommissionBps,trialPolicyVersion:trial.policyVersion,trialDays:Number(x?.requestedTrialDays),dataUseTermsVersion:String(agreement.dataUseTermsVersion),memberObligationsVersion:String(agreement.memberObligationsVersion),tournamentObligationsVersion:String(agreement.tournamentObligationsVersion),effectiveAt:String(agreement.effectiveAt)};
  if(!acceptanceIsCurrent(accepted,{...currentAcceptance,applicationId:a.applicationId,trialOfferId:offerId}))throw new HttpsError("failed-precondition","Agreement acceptance is stale.");
  tx.update(db.collection("enterprise_trial_offers").doc(offerId),{status:"consumed",usedAt:server(),usedByApplicationId:a.applicationId});tx.update(appRef(a.applicationId),{status:"submitted",version:Number(x?.version)+1,submittedAt:server(),updatedAt:server()});tx.create(receiptRef(rid),{receiptId:rid,applicationId:a.applicationId,...a.context,action:"submitted",agreementAcceptanceReceiptId:acceptanceId,trialOfferId:offerId,actorMembershipId:a.context.membershipId,immutable:true,occurredAt:server()});tx.create(cmdRef,{commandId:cid,digest,action:"submit",receiptId:rid,immutable:true,createdAt:server()});
 });return projection(a)
});
export const withdrawEnterpriseCourseOnboardingV1=onCall({enforceAppCheck:true},async r=>{const a=await scoped(r),cid=command(r.data?.commandId),digest=hash({applicationId:a.applicationId}),rid=receiptDocumentId(a.applicationId,cid,"withdrawn"),cmdRef=db.collection("enterprise_onboarding_commands").doc(commandDocumentId(a.actor,cid,"withdraw"));await db.runTransaction(async tx=>{const[app,prior]=await Promise.all([tx.get(appRef(a.applicationId)),tx.get(cmdRef)]);if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");return}const x=app.data();if(!app.exists||!['draft','submitted','under_review','changes_requested'].includes(x?.status))throw new HttpsError("failed-precondition","Withdrawal unavailable.");tx.update(appRef(a.applicationId),{status:"withdrawn",version:Number(x?.version)+1,updatedAt:server()});tx.create(receiptRef(rid),{receiptId:rid,applicationId:a.applicationId,...a.context,action:"withdrawn",actorMembershipId:a.context.membershipId,immutable:true,occurredAt:server()});tx.create(cmdRef,{commandId:cid,digest,action:"withdraw",receiptId:rid,immutable:true,createdAt:server()})});return projection(a)});
export const getEnterpriseApplicationReviewProjectionV1=onCall({enforceAppCheck:true},async r=>{const actor=uid(r),adminUser=await db.collection("admin_users").doc(actor).get();if(!adminUser.exists||!['super_admin','operations_admin','partner_reviewer'].includes(String(adminUser.data()?.role)))throw new HttpsError("permission-denied","Admin review authority required.");const id=String(r.data?.applicationId||""),app=await appRef(id).get();if(!app.exists)throw new HttpsError("not-found","Application unavailable.");const x=app.data()||{};return{schema:ENTERPRISE_REVIEW_SCHEMA,applicationId:id,status:x.status,organization:{organizationId:x.organizationId,legalName:x.legalName,registrationNumber:x.registrationNumber},propertyId:x.propertyId,course:{courseId:x.courseId,courseProfileAttemptId:x.courseProfileAttemptId},representative:{membershipId:x.actorMembershipId,name:x.representativeName,title:x.representativeTitle,authorityDeclaration:x.representativeAuthorityDeclaration,contactEmail:x.contactEmail,contactPhone:x.contactPhone,preferredLocale:x.preferredLocale},agreement:{accepted:Boolean(x.agreementAcceptanceReceiptId),receiptId:x.agreementAcceptanceReceiptId||null},trialRequest:{days:x.requestedTrialDays,offerId:x.trialOfferId||null},outstandingRequirements:[]}});
