import {createHash} from "node:crypto";

export const ENTERPRISE_ONBOARDING_SCHEMA="golfriend.enterprise-course-onboarding.v1" as const;
export const ENTERPRISE_AGREEMENT_SCHEMA="golfriend.enterprise-agreement.v1" as const;
export const ENTERPRISE_ECONOMY_SCHEMA="golfriend.economy.configuration.v1" as const;
export const ENTERPRISE_ECONOMY_POINTER_SCHEMA="golfriend.economy.configuration-pointer.v1" as const;
export const ENTERPRISE_REVIEW_SCHEMA="golfriend.enterprise-application-review.v1" as const;
export const ONBOARDING_LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export const TRIAL_DAYS=[30,90] as const;
export type TrialDays=typeof TRIAL_DAYS[number];
export type ApplicationState="draft"|"submitted"|"under_review"|"changes_requested"|"approved_for_trial"|"trial_active"|"trial_expiring"|"trial_expired"|"conversion_review"|"active_partner"|"declined"|"suspended"|"withdrawn";
const id=(v:unknown,label:string)=>{const x=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw new Error(`${label}_INVALID`);return x};
const text=(v:unknown,label:string,max=500)=>{const x=String(v||"").trim();if(!x||x.length>max||/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(x))throw new Error(`${label}_INVALID`);return x};
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export const materialDraftDigest=(draft:any)=>digest(normalizeDraft(draft));
export function strictVersion(value:unknown,label="VERSION"){if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0)throw new Error(`${label}_INVALID`);return value}
export const commandDocumentId=(uid:string,commandId:string,action:string)=>`eoc_${digest([uid,commandId,action]).slice(0,32)}`;
export const receiptDocumentId=(applicationId:string,commandId:string,action:string)=>`eor_${digest([applicationId,commandId,action]).slice(0,32)}`;
export function normalizeContext(raw:any){return{membershipId:id(raw?.membershipId,"MEMBERSHIP"),organizationId:id(raw?.organizationId,"ORGANIZATION"),propertyId:id(raw?.propertyId,"PROPERTY"),courseId:id(raw?.courseId,"COURSE")}}
export function normalizeDraft(raw:any){
 const locale=String(raw?.preferredLocale||"");if(!ONBOARDING_LOCALES.includes(locale as any))throw new Error("LOCALE_INVALID");
 const trialDays=Number(raw?.requestedTrialDays);if(!TRIAL_DAYS.includes(trialDays as any))throw new Error("TRIAL_INVALID");
 const allowed=new Set(["legalName","registrationNumber","registeredAddress","representativeName","representativeTitle","representativeAuthorityDeclaration","contactEmail","contactPhone","preferredLocale","courseProfileAttemptId","requestedTrialDays","dataUseAcknowledged","memberPurposeAcknowledged","tournamentPurposeAcknowledged","bookingCommissionAcknowledged"]);
 for(const key of Object.keys(raw||{}))if(!allowed.has(key))throw new Error("UNDECLARED_FIELD");
 return{legalName:text(raw.legalName,"LEGAL_NAME",200),registrationNumber:text(raw.registrationNumber,"REGISTRATION_NUMBER",100),registeredAddress:text(raw.registeredAddress,"REGISTERED_ADDRESS",500),representativeName:text(raw.representativeName,"REPRESENTATIVE_NAME",150),representativeTitle:text(raw.representativeTitle,"REPRESENTATIVE_TITLE",120),representativeAuthorityDeclaration:text(raw.representativeAuthorityDeclaration,"AUTHORITY_DECLARATION",500),contactEmail:text(raw.contactEmail,"CONTACT_EMAIL",254).toLowerCase(),contactPhone:text(raw.contactPhone,"CONTACT_PHONE",40),preferredLocale:locale,courseProfileAttemptId:id(raw.courseProfileAttemptId,"PROFILE_ATTEMPT"),requestedTrialDays:trialDays as TrialDays,dataUseAcknowledged:raw.dataUseAcknowledged===true,memberPurposeAcknowledged:raw.memberPurposeAcknowledged===true,tournamentPurposeAcknowledged:raw.tournamentPurposeAcknowledged===true,bookingCommissionAcknowledged:raw.bookingCommissionAcknowledged===true};
}
export const economyConfigurationDigest=(raw:any)=>digest({schema:raw.schema,configurationId:raw.configurationId,policyVersion:raw.policyVersion,version:raw.version,status:raw.status,bookingCommissionBps:raw.bookingCommissionBps,authorizedMaximumBps:raw.authorizedMaximumBps,effectiveAt:raw.effectiveAt?.toMillis?.()??raw.effectiveAt,approvalReceiptId:raw.approvalReceiptId});
export function validateEconomyPointer(raw:any){if(raw?.schema!==ENTERPRISE_ECONOMY_POINTER_SCHEMA||raw?.status!=="active"||!/^ecc_[A-Za-z0-9_.:-]{3,120}$/.test(String(raw?.configurationId||""))||!Number.isSafeInteger(raw?.version)||raw.version<1||!/^ecr_[A-Za-z0-9_.:-]{3,120}$/.test(String(raw?.approvalReceiptId||""))||!/^([a-f0-9]{64})$/.test(String(raw?.configurationDigest||"")))throw new Error("ECONOMY_POINTER_INVALID");return{configurationId:String(raw.configurationId),version:raw.version,approvalReceiptId:String(raw.approvalReceiptId),configurationDigest:String(raw.configurationDigest)}}
export function validateEconomyConfig(raw:any,pointer?:any,nowMs=Date.now()){const effectiveAt=raw?.effectiveAt?.toDate?.().toISOString?.()||String(raw?.effectiveAt||""),configurationDigest=economyConfigurationDigest(raw);if(raw?.schema!==ENTERPRISE_ECONOMY_SCHEMA||raw?.status!=="active"||!Number.isSafeInteger(raw?.bookingCommissionBps)||!Number.isSafeInteger(raw?.authorizedMaximumBps)||raw.bookingCommissionBps<=0||raw.bookingCommissionBps!==raw.authorizedMaximumBps||raw.authorizedMaximumBps>10000||!/^ecp_[A-Za-z0-9_.:-]{3,120}$/.test(String(raw?.policyVersion||""))||!/^ecr_[A-Za-z0-9_.:-]{3,120}$/.test(String(raw?.approvalReceiptId||""))||!Number.isFinite(Date.parse(effectiveAt))||Date.parse(effectiveAt)>nowMs||!Number.isSafeInteger(raw?.version)||raw.version<1||pointer&&(raw.configurationId!==pointer.configurationId||raw.version!==pointer.version||raw.approvalReceiptId!==pointer.approvalReceiptId||configurationDigest!==pointer.configurationDigest))throw new Error("ECONOMY_CONFIG_INVALID");return{configurationId:String(raw.configurationId),bookingCommissionBps:raw.bookingCommissionBps,authorizedMaximumBps:raw.authorizedMaximumBps,policyVersion:`${raw.policyVersion}@${raw.configurationId}@${configurationDigest}@${raw.approvalReceiptId}`,effectiveAt,version:Number(raw.version),approvalReceiptId:String(raw.approvalReceiptId),configurationDigest}}
export const trialOfferDigest=(raw:any)=>digest({offerId:raw.offerId,organizationId:raw.organizationId,propertyId:raw.propertyId,courseId:raw.courseId,durationDays:raw.durationDays,policyVersion:raw.policyVersion,version:raw.version,effectiveAt:raw.effectiveAt?.toMillis?.()??raw.effectiveAt,expiresAt:raw.expiresAt?.toMillis?.()??raw.expiresAt});
export function validateTrialOffer(raw:any,documentId:string,scope:{organizationId:string;propertyId:string;courseId:string},days:TrialDays,nowMs:number,applicationId?:string){const effective=raw?.effectiveAt?.toMillis?.(),expires=raw?.expiresAt?.toMillis?.(),reusable=raw?.status==="offered"&&!raw?.usedAt||raw?.status==="consumed"&&raw?.usedByApplicationId===applicationId;if(!raw||raw.offerId!==documentId||raw.organizationId!==scope.organizationId||raw.propertyId!==scope.propertyId||raw.courseId!==scope.courseId||!reusable||raw.durationDays!==days||raw.revokedAt||!Number.isSafeInteger(raw.version)||raw.version<1||!Number.isFinite(effective)||effective>nowMs||!Number.isFinite(expires)||expires<=nowMs||raw.authorizationDigest!==trialOfferDigest(raw))throw new Error("TRIAL_OFFER_INVALID");return{id:id(raw.offerId,"TRIAL_OFFER"),policyVersion:id(raw.policyVersion,"TRIAL_POLICY"),version:raw.version,authorizationDigest:raw.authorizationDigest}}
export function agreementDigest(input:any){return digest({schema:ENTERPRISE_AGREEMENT_SCHEMA,agreementId:input.agreementId,version:input.version,canonicalLocale:"en",canonicalContentDigest:input.canonicalContentDigest,organizationId:input.organizationId,propertyId:input.propertyId,courseId:input.courseId,representativeMembershipId:input.representativeMembershipId,acceptedLocale:input.acceptedLocale,bookingCommissionPolicyVersion:input.bookingCommissionPolicyVersion,bookingCommissionBps:input.bookingCommissionBps,trialPolicyVersion:input.trialPolicyVersion,trialOfferVersion:input.trialOfferVersion,trialOfferDigest:input.trialOfferDigest,trialDays:input.trialDays,dataUseTermsVersion:input.dataUseTermsVersion,memberObligationsVersion:input.memberObligationsVersion,tournamentObligationsVersion:input.tournamentObligationsVersion,effectiveAt:input.effectiveAt,applicationVersion:input.applicationVersion,materialDraftDigest:input.materialDraftDigest,authoritySourceVersion:input.authoritySourceVersion});}
export function acceptanceIsCurrent(receipt:any,current:any){return!!receipt&&receipt.applicationId===current.applicationId&&receipt.organizationId===current.organizationId&&receipt.propertyId===current.propertyId&&receipt.courseId===current.courseId&&receipt.actorMembershipId===current.representativeMembershipId&&receipt.trialOfferId===current.trialOfferId&&receipt.contentDigest===agreementDigest(current)}
export function requireSubmitReady(app:any){if(app.status!=="draft"&&app.status!=="changes_requested")throw new Error("STATE_INVALID");if(!app.agreementAcceptanceReceiptId)throw new Error("AGREEMENT_REQUIRED");if(!app.dataUseAcknowledged||!app.memberPurposeAcknowledged||!app.tournamentPurposeAcknowledged||!app.bookingCommissionAcknowledged)throw new Error("DISCLOSURE_REQUIRED")}
export function trialWindow(startMs:number,days:TrialDays){return{startsAtMs:startMs,endsAtMs:startMs+days*86400000}}
export function deriveTrialState(trial:any,nowMs:number):"approved_for_trial"|"trial_active"|"trial_expiring"|"trial_expired"{if(!trial?.startsAt?.toMillis)return"approved_for_trial";const start=trial.startsAt.toMillis(),end=trial.endsAt.toMillis();if(nowMs<start)return"approved_for_trial";if(nowMs>=end)return"trial_expired";return end-nowMs<=7*86400000?"trial_expiring":"trial_active"}
