import {createHash} from "node:crypto";
export const AUTHORITY_SCHEMA="golfriend.enterprise-organization-authority.v1" as const;
export const AUTHORITY_COMMAND_SCHEMA="golfriend.enterprise-organization-authority.command.v1" as const;
export const ROLES=["organization_owner","organization_admin","course_manager","booking_staff","tournament_staff","marketing_content_staff","analyst_viewer"] as const;
export const STATUSES=["pending","active","suspended","expired","revoked"] as const;
export type EnterpriseRole=typeof ROLES[number];
export type AuthorityStatus=typeof STATUSES[number];
export type AuthorityScope={kind:"organization";organizationId:string}|{kind:"course";organizationId:string;propertyId:string;courseId:string};
export type AuthorityRecord={membershipId:string;bindingUid:string;organizationId:string;role:EnterpriseRole;scope:AuthorityScope;status:AuthorityStatus;effectiveAt:string;expiresAt:string|null;version:number;grantIds:string[]};
export type GrantRecord={grantId:string;membershipId:string;organizationId:string;propertyId:string|null;courseId:string|null;capabilities:string[];status:AuthorityStatus;effectiveAt:string;expiresAt:string|null;version:number};
export type Hierarchy={organizations:any[];properties:any[];courses:any[]};
export type BookingAuthorityMode="read"|"mutate";
export type BookingCourseAuthority={membershipId:string;organizationId:string;propertyId:string;courseId:string;role:EnterpriseRole;mode:BookingAuthorityMode;canMutate:boolean;sourceVersion:string};
const digest=(...parts:string[])=>createHash("sha256").update(parts.join("|")).digest("hex").slice(0,32);
export const authorityReceiptId=(uid:string,kind:string,sourceVersion:string)=>`ear_${digest(uid,kind,sourceVersion)}`;
export const authorityDecisionVersion=(memberships:AuthorityRecord[],grants:GrantRecord[])=>digest(JSON.stringify(memberships.map(x=>[x.membershipId,x.version,x.status])),JSON.stringify(grants.map(x=>[x.grantId,x.version,x.status])));
export function stableId(value:unknown,label="ID"){const v=String(value||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(v))throw new Error(`${label}_INVALID`);return v}
const instant=(value:unknown,label:string)=>{const v=typeof value==="string"?value:"";if(!v||!Number.isFinite(Date.parse(v)))throw new Error(`${label}_INVALID`);return v};
const status=(v:unknown)=>{if(!STATUSES.includes(v as any))throw new Error("STATUS_INVALID");return v as AuthorityStatus};
const role=(v:unknown)=>{if(!ROLES.includes(v as any))throw new Error("ROLE_INVALID");return v as EnterpriseRole};
export function normalizeMembership(raw:any):AuthorityRecord{
 if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("MEMBERSHIP_MALFORMED");
 const organizationId=stableId(raw.organizationId,"ORGANIZATION"),kind=raw.scope?.kind;
 const scope:AuthorityScope=kind==="organization"?{kind,organizationId}:kind==="course"?{kind,organizationId,propertyId:stableId(raw.scope.propertyId,"PROPERTY"),courseId:stableId(raw.scope.courseId,"COURSE")}:(()=>{throw new Error("SCOPE_INVALID")})();
 if(raw.scope.organizationId!==organizationId)throw new Error("SCOPE_ORGANIZATION_MISMATCH");
 const grantIds=Array.isArray(raw.grantIds)?raw.grantIds.map((x:unknown)=>stableId(x,"GRANT")):[];
 if(new Set(grantIds).size!==grantIds.length)throw new Error("DUPLICATE_GRANT");
 const version=Number(raw.version);if(!Number.isSafeInteger(version)||version<1)throw new Error("VERSION_INVALID");
 return{membershipId:stableId(raw.membershipId,"MEMBERSHIP"),bindingUid:stableId(raw.bindingUid,"UID"),organizationId,role:role(raw.role),scope,status:status(raw.status),effectiveAt:instant(raw.effectiveAt,"EFFECTIVE_AT"),expiresAt:raw.expiresAt==null?null:instant(raw.expiresAt,"EXPIRES_AT"),version,grantIds};
}
export function normalizeGrant(raw:any):GrantRecord{if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("GRANT_MALFORMED");const capabilities=Array.isArray(raw.capabilities)?raw.capabilities.map(String):[];if(!capabilities.length||new Set(capabilities).size!==capabilities.length)throw new Error("CAPABILITIES_INVALID");const version=Number(raw.version);if(!Number.isSafeInteger(version)||version<1)throw new Error("VERSION_INVALID");return{grantId:stableId(raw.grantId,"GRANT"),membershipId:stableId(raw.membershipId,"MEMBERSHIP"),organizationId:stableId(raw.organizationId,"ORGANIZATION"),propertyId:raw.propertyId==null?null:stableId(raw.propertyId,"PROPERTY"),courseId:raw.courseId==null?null:stableId(raw.courseId,"COURSE"),capabilities,status:status(raw.status),effectiveAt:instant(raw.effectiveAt,"EFFECTIVE_AT"),expiresAt:raw.expiresAt==null?null:instant(raw.expiresAt,"EXPIRES_AT"),version};}
export function effective(statusValue:AuthorityStatus,effectiveAt:string,expiresAt:string|null,now:string){const t=Date.parse(now);return statusValue==="active"&&Date.parse(effectiveAt)<=t&&(!expiresAt||Date.parse(expiresAt)>t)}
export function hierarchyEffective(x:any,now:string){const time=(v:any)=>v?.toMillis instanceof Function?v.toMillis():Date.parse(v);return!!x&&x.status==="active"&&!x.suspendedAt&&!x.revokedAt&&(!x.effectiveAt||time(x.effectiveAt)<=Date.parse(now))&&(!x.expiresAt||time(x.expiresAt)>Date.parse(now))}
export function activeCourseAuthority(m:AuthorityRecord,g:GrantRecord[],hierarchy:Hierarchy,now:string,capability:string){
 if(m.scope.kind!=="course"||!effective(m.status,m.effectiveAt,m.expiresAt,now))return false;
 const scope=m.scope,org=hierarchy.organizations.find(x=>x.organizationId===m.organizationId),property=hierarchy.properties.find(x=>x.propertyId===scope.propertyId&&x.organizationId===m.organizationId),course=hierarchy.courses.find(x=>x.courseId===scope.courseId&&x.propertyId===scope.propertyId&&x.organizationId===m.organizationId);
 if(!hierarchyEffective(org,now)||!hierarchyEffective(property,now)||!hierarchyEffective(course,now))return false;
 const matched=g.filter(x=>m.grantIds.includes(x.grantId));if(matched.length!==m.grantIds.length)return false;
 return matched.some(x=>x.membershipId===m.membershipId&&x.organizationId===m.organizationId&&x.propertyId===scope.propertyId&&x.courseId===scope.courseId&&effective(x.status,x.effectiveAt,x.expiresAt,now)&&x.capabilities.includes(capability));
}
export function resolveAuthority(uid:string,rawMemberships:any[],rawGrants:any[],hierarchy:Hierarchy,now:string){
 const memberships=rawMemberships.map(normalizeMembership);if(memberships.some(x=>x.bindingUid!==uid))throw new Error("BINDING_UID_MISMATCH");
 if(new Set(memberships.map(x=>x.membershipId)).size!==memberships.length)throw new Error("DUPLICATE_MEMBERSHIP");
 const grants=rawGrants.map(normalizeGrant);if(new Set(grants.map(x=>x.grantId)).size!==grants.length)throw new Error("DUPLICATE_GRANT_RECORD");
 for(const m of memberships){if(!hierarchy.organizations.some(x=>x.organizationId===m.organizationId))throw new Error("MISSING_ORGANIZATION");if(m.scope.kind==="course"){const scope=m.scope;if(!hierarchy.properties.some(x=>x.propertyId===scope.propertyId&&x.organizationId===m.organizationId)||!hierarchy.courses.some(x=>x.courseId===scope.courseId&&x.propertyId===scope.propertyId&&x.organizationId===m.organizationId))throw new Error("MISSING_HIERARCHY")}}
 return{memberships,grants,sourceVersion:authorityDecisionVersion(memberships,grants)};
}
const BOOKING_MUTATION_ROLES=new Set<EnterpriseRole>(["organization_owner","organization_admin","course_manager","booking_staff"]);
const BOOKING_READ_ROLES=new Set<EnterpriseRole>([...BOOKING_MUTATION_ROLES,"analyst_viewer"]);
function bookingHierarchyEffective(value:any,now:string){const instant=(candidate:any)=>candidate?.toMillis instanceof Function?candidate.toMillis():Date.parse(candidate),at=Date.parse(now);return!!value&&value.status==="active"&&!value.suspendedAt&&!value.revokedAt&&(!value.effectiveAt||instant(value.effectiveAt)<=at)&&(!value.expiresAt||instant(value.expiresAt)>at);}
function exactActiveBookingGrant(m:AuthorityRecord,grants:GrantRecord[],organizationId:string,propertyId:string,courseId:string,now:string){const referenced=grants.filter(g=>m.grantIds.includes(g.grantId));if(referenced.length!==m.grantIds.length||referenced.some(g=>g.membershipId!==m.membershipId||g.organizationId!==organizationId))return false;return referenced.some(g=>g.propertyId===propertyId&&g.courseId===courseId&&g.capabilities.includes("booking")&&effective(g.status,g.effectiveAt,g.expiresAt,now));}
function exactActiveHierarchy(hierarchy:Hierarchy,organizationId:string,propertyId:string,courseId:string,now:string){const organization=hierarchy.organizations.find(x=>x.organizationId===organizationId),property=hierarchy.properties.find(x=>x.propertyId===propertyId&&x.organizationId===organizationId),course=hierarchy.courses.find(x=>x.courseId===courseId&&x.propertyId===propertyId&&x.organizationId===organizationId);return bookingHierarchyEffective(organization,now)&&bookingHierarchyEffective(property,now)&&bookingHierarchyEffective(course,now)&&Array.isArray(organization.propertyIds)&&organization.propertyIds.includes(propertyId)&&Array.isArray(property.courseIds)&&property.courseIds.includes(courseId);}
export function resolveBookingCourseAuthority(uid:string,rawMemberships:any[],rawGrants:any[],hierarchy:Hierarchy,target:{organizationId:string;propertyId:string;courseId:string;mode:BookingAuthorityMode},now:string):BookingCourseAuthority{const organizationId=stableId(target?.organizationId,"ORGANIZATION"),propertyId=stableId(target?.propertyId,"PROPERTY"),courseId=stableId(target?.courseId,"COURSE"),mode=target?.mode;if(mode!=="read"&&mode!=="mutate")throw new Error("BOOKING_AUTHORITY_MODE_INVALID");const resolved=resolveAuthority(uid,rawMemberships,rawGrants,hierarchy,now);if(!exactActiveHierarchy(hierarchy,organizationId,propertyId,courseId,now))throw new Error("BOOKING_HIERARCHY_INACTIVE");const matches=resolved.memberships.filter(m=>{if(m.organizationId!==organizationId||!effective(m.status,m.effectiveAt,m.expiresAt,now)||!BOOKING_READ_ROLES.has(m.role))return false;if(mode==="mutate"&&!BOOKING_MUTATION_ROLES.has(m.role))return false;if(m.scope.kind==="course"&&(m.scope.propertyId!==propertyId||m.scope.courseId!==courseId))return false;return exactActiveBookingGrant(m,resolved.grants,organizationId,propertyId,courseId,now);});if(matches.length!==1)throw new Error(matches.length?"BOOKING_AUTHORITY_AMBIGUOUS":"BOOKING_AUTHORITY_DENIED");const membership=matches[0];return Object.freeze({membershipId:membership.membershipId,organizationId,propertyId,courseId,role:membership.role,mode,canMutate:BOOKING_MUTATION_ROLES.has(membership.role),sourceVersion:resolved.sourceVersion});}
export function resolveTournamentCourseAuthority(uid:string,rawMemberships:any[],rawGrants:any[],hierarchy:Hierarchy,target:{membershipId:string;organizationId:string;propertyId:string;courseId:string},now:string){const membershipId=stableId(target?.membershipId,"MEMBERSHIP"),organizationId=stableId(target?.organizationId,"ORGANIZATION"),propertyId=stableId(target?.propertyId,"PROPERTY"),courseId=stableId(target?.courseId,"COURSE"),resolved=resolveAuthority(uid,rawMemberships,rawGrants,hierarchy,now),m=resolved.memberships.find(x=>x.membershipId===membershipId);if(!exactActiveHierarchy(hierarchy,organizationId,propertyId,courseId,now)||!m||m.organizationId!==organizationId||!["organization_owner","course_manager","tournament_staff"].includes(m.role)||!effective(m.status,m.effectiveAt,m.expiresAt,now)||m.scope.kind==="organization"&&m.role!=="organization_owner"||m.scope.kind==="course"&&(m.scope.propertyId!==propertyId||m.scope.courseId!==courseId))throw new Error("TOURNAMENT_AUTHORITY_DENIED");const grants=resolved.grants.filter(x=>m.grantIds.includes(x.grantId));if(grants.length!==m.grantIds.length||!grants.some(x=>x.membershipId===m.membershipId&&x.organizationId===organizationId&&x.propertyId===propertyId&&x.courseId===courseId&&effective(x.status,x.effectiveAt,x.expiresAt,now)&&x.capabilities.includes("tournament")))throw new Error("TOURNAMENT_AUTHORITY_DENIED");return Object.freeze({membership:m,grants:resolved.grants,hierarchy,sourceVersion:resolved.sourceVersion})}
