import test from"node:test";import assert from"node:assert/strict";import{agreementDigest,deriveTrialState,normalizeDraft,trialWindow,validateEconomyConfig,validateTrialOffer}from"./enterpriseOnboardingDomain.js";
const draft={legalName:"Course Co",registrationNumber:"R1",registeredAddress:"Bangkok",representativeName:"A",representativeTitle:"Owner",representativeAuthorityDeclaration:"Authorized owner",contactEmail:"A@EXAMPLE.COM",contactPhone:"1",preferredLocale:"en",courseProfileAttemptId:"attempt_1",requestedTrialDays:30,dataUseAcknowledged:true,memberPurposeAcknowledged:true,tournamentPurposeAcknowledged:true,bookingCommissionAcknowledged:true};
test("only explicit 30 or 90 day trial is accepted",()=>{assert.equal(normalizeDraft(draft).requestedTrialDays,30);assert.throws(()=>normalizeDraft({...draft,requestedTrialDays:60}))});
test("private undeclared fields are rejected",()=>assert.throws(()=>normalizeDraft({...draft,privateNotes:"x"})));
test("economy rate is consumed from versioned active config",()=>assert.equal(validateEconomyConfig({schema:"golfriend.enterprise-economy-config.v1",status:"active",bookingCommissionBps:300,authorizedMaximumBps:300,policyVersion:"ecp_founder_v1",effectiveAt:"2026-08-15T00:00:00Z",version:1}).bookingCommissionBps,300));
test("malformed or excessive commission fails",()=>assert.throws(()=>validateEconomyConfig({schema:"golfriend.enterprise-economy-config.v1",status:"active",bookingCommissionBps:301,authorizedMaximumBps:300,policyVersion:"ecp_xxx",effectiveAt:"2026-08-15T00:00:00Z",version:1})));
test("trial offers are exact, organization bound and unexpired",()=>{const offer={offerId:"offer_1",organizationId:"org_1",status:"offered",durationDays:90,policyVersion:"trial_v1",expiresAt:{toMillis:()=>200}};assert.equal(validateTrialOffer(offer,"org_1",90,100).id,"offer_1");assert.throws(()=>validateTrialOffer(offer,"org_2",90,100))});
test("server trial window is exact and state is derived",()=>{const w=trialWindow(0,30);assert.equal(w.endsAtMs,2592000000);assert.equal(deriveTrialState({startsAt:{toMillis:()=>0},endsAt:{toMillis:()=>w.endsAtMs}},w.endsAtMs),"trial_expired")});
test("agreement digest changes with locale scope rate and trial",()=>{const x:any={agreementId:"a",version:1,canonicalContentDigest:"d",organizationId:"o",propertyId:"p",courseId:"c",representativeMembershipId:"m",acceptedLocale:"en",bookingCommissionPolicyVersion:"e",bookingCommissionBps:300,trialPolicyVersion:"t",trialDays:30,dataUseTermsVersion:"d1",memberObligationsVersion:"m1",tournamentObligationsVersion:"t1",effectiveAt:"now"};assert.notEqual(agreementDigest(x),agreementDigest({...x,acceptedLocale:"th"}));assert.notEqual(agreementDigest(x),agreementDigest({...x,trialDays:90}))});
