import * as admin from "firebase-admin";
import {createHash} from "node:crypto";
import {HttpsError,onCall} from "firebase-functions/v2/https";
import {resolveEnterpriseCourseAuthority} from "./enterpriseAuthorityRuntime.js";
import {assertSupportDocument,ENTERPRISE_SUPPORT_SCHEMA,normalizeEvidence,normalizeReply,normalizeSupportDraft,requireTransition,supportCommandId,supportDigest,supportReceiptId,supportRequestId} from "./enterpriseSupportDomain.js";

if(!admin.apps.length)admin.initializeApp();
const db=admin.firestore(),stamp=()=>admin.firestore.FieldValue.serverTimestamp(),iso=(v:any)=>v?.toDate?.().toISOString?.()||null;
const safeId=(v:unknown,label:string)=>{const x=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw new HttpsError("invalid-argument",`${label} invalid.`);return x};
const version=(v:unknown)=>{if(!Number.isSafeInteger(v)||Number(v)<1)throw new HttpsError("invalid-argument","Expected version invalid.");return Number(v)};
function exactData(raw:any,keys:string[]){if(!raw||Object.keys(raw).some(k=>!keys.includes(k)))throw new HttpsError("invalid-argument","Request shape invalid.")}
function context(raw:any){const value={membershipId:safeId(raw?.actorMembershipId,"Membership"),organizationId:safeId(raw?.organizationId,"Organization"),propertyId:safeId(raw?.propertyId,"Property"),courseId:safeId(raw?.courseId,"Course")};if(Object.keys(raw||{}).some(k=>!["actorMembershipId","organizationId","propertyId","courseId"].includes(k)))throw new HttpsError("invalid-argument","Context shape invalid.");return value}
function actor(request:any){if(!request.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");return String(request.auth.uid)}
const requestRef=(id:string)=>db.collection("enterprise_support_requests").doc(id),receiptRef=(id:string)=>db.collection("enterprise_support_receipts").doc(id);

async function scoped(request:any){
 if(!request.data?.commandId)exactData(request.data,["context"]);else if(request.data?.evidence!==undefined)exactData(request.data,["context","commandId","requestId","expectedVersion","evidence"]);else if(request.data?.type!==undefined)exactData(request.data,["context","commandId","type","subject","body","locale","notificationPreferences"]);
 const uid=actor(request),scope=context(request.data?.context),authority=await resolveEnterpriseCourseAuthority(uid,scope.membershipId,scope.organizationId,scope.propertyId,scope.courseId,"partner_support");
 const applicationId=`eoa_${createHash("sha256").update(JSON.stringify([scope.organizationId,scope.propertyId,scope.courseId])).digest("hex").slice(0,32)}`,application=await db.collection("enterprise_onboarding_applications").doc(applicationId).get(),a=application.data()||{};
 if(!application.exists||a.organizationId!==scope.organizationId||a.propertyId!==scope.propertyId||a.courseId!==scope.courseId||a.actorMembershipId!==scope.membershipId||!["draft","submitted","under_review","changes_requested","approved_for_trial","trial_active","trial_expiring","trial_expired","conversion_review","active_partner","suspended","withdrawn"].includes(a.status))throw new HttpsError("permission-denied","Verified representative authority unavailable.");
 if(a.agreementAcceptanceReceiptId){const acceptance=await db.collection("enterprise_onboarding_receipts").doc(String(a.agreementAcceptanceReceiptId)).get(),ad=acceptance.data()||{};if(!acceptance.exists||ad.applicationId!==applicationId||ad.organizationId!==scope.organizationId||ad.propertyId!==scope.propertyId||ad.courseId!==scope.courseId||ad.actorMembershipId!==scope.membershipId)throw new HttpsError("permission-denied","Verified representative evidence unavailable.")}
 const trial=await db.collection("enterprise_trials").doc(applicationId).get(),t=trial.data()||{};if(trial.exists&&(t.organizationId!==scope.organizationId||t.propertyId!==scope.propertyId||t.courseId!==scope.courseId))throw new HttpsError("unavailable","Authoritative trial state unavailable.");
 return{uid,scope,authority,applicationId,applicationState:String(a.status),trialState:trial.exists?String(t.status||"active"):null};
}
function publicMessage(m:any){return{messageId:String(m.messageId),author:m.author==="admin"?"admin":"representative",body:String(m.body),createdAt:iso(m.createdAt),receiptId:m.receiptId?String(m.receiptId):null}}
async function projection(s:any){
 const snap=await db.collection("enterprise_support_requests").where("organizationId","==",s.scope.organizationId).limit(100).get();const requests:any[]=[];
 const context={actorMembershipId:s.scope.membershipId,organizationId:s.scope.organizationId,propertyId:s.scope.propertyId,courseId:s.scope.courseId};
 for(const d of snap.docs){const x=d.data();if(x.propertyId!==s.scope.propertyId||x.courseId!==s.scope.courseId||x.representativeMembershipId!==s.scope.membershipId)continue;try{assertSupportDocument(x,s.scope)}catch{return{schema:ENTERPRISE_SUPPORT_SCHEMA,state:"unavailable",context,adminCommandStatus:"unavailable",requests:[]}}const receiptSnap=await db.collection("enterprise_support_receipts").where("requestId","==",d.id).limit(100).get(),receipts:any[]=[];for(const r of receiptSnap.docs){const z=r.data();if(z.schema!=="golfriend.enterprise-support-receipt.v1"||z.requestId!==d.id||z.organizationId!==s.scope.organizationId||z.propertyId!==s.scope.propertyId||z.courseId!==s.scope.courseId||z.representativeMembershipId!==s.scope.membershipId||z.immutable!==true)return{schema:ENTERPRISE_SUPPORT_SCHEMA,state:"unavailable",context,adminCommandStatus:"unavailable",requests:[]};receipts.push({receiptId:r.id,action:String(z.action),occurredAt:iso(z.createdAt),immutable:true})}requests.push({requestId:d.id,scope:{...context,applicationId:s.applicationId},type:x.type,subject:x.subject,status:x.status,version:x.version,locale:x.locale,applicationState:x.applicationState,trialState:x.trialState||null,createdAt:iso(x.createdAt),updatedAt:iso(x.updatedAt),messages:Array.isArray(x.messages)?x.messages.filter((m:any)=>m.author==="representative"||m.author==="admin"&&m.public===true).map(publicMessage):[],evidence:Array.isArray(x.evidence)?x.evidence.map((e:any)=>({type:e.type,referenceId:e.referenceId,label:e.label})):[],notificationPreferences:{locale:x.notificationPreferences?.locale,email:x.notificationPreferences?.email===true,sms:x.notificationPreferences?.sms===true,push:x.notificationPreferences?.push===true},receipts})}
 return{schema:ENTERPRISE_SUPPORT_SCHEMA,state:s.applicationState==="suspended"?"suspended":requests.length?"current":"empty",context,adminCommandStatus:"unavailable",requests};
}
function cmd(request:any,action:string){return{commandId:safeId(request.data?.commandId,"Command"),action}}
async function mutate(request:any,action:"submit"|"reply"|"withdraw"|"reopen"|"close"){
 exactData(request.data,action==="reply"?["context","commandId","requestId","expectedVersion","body"]:["context","commandId","requestId","expectedVersion"]);
 const s=await scoped(request),c=cmd(request,action),requestId=safeId(request.data?.requestId,"Request"),expected=version(request.data?.expectedVersion),reply=action==="reply"?normalizeReply({body:request.data?.body}):null,digest=supportDigest({requestId,action,expected,reply,scope:s.scope,source:s.authority.sourceVersion}),commandRef=db.collection("enterprise_support_commands").doc(supportCommandId(s.uid,c.commandId,action)),rid=supportReceiptId(requestId,c.commandId,action);let replayed=false;
 await db.runTransaction(async tx=>{const[doc,prior]=await Promise.all([tx.get(requestRef(requestId)),tx.get(commandRef)]);if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");replayed=true;return}let x:any;try{x=assertSupportDocument(doc.data(),s.scope)}catch{throw new HttpsError("not-found","Support request unavailable.")}if(x.version!==expected)throw new HttpsError("aborted","STALE_VERSION");let next;try{next=requireTransition(x.status,action,{resolvedAtMs:x.resolvedAt?.toMillis?.(),nowMs:Date.now(),reopenCount:Number(x.reopenCount||0)})}catch{throw new HttpsError("failed-precondition","Support transition unavailable.")}const receipt={schema:"golfriend.enterprise-support-receipt.v1",receiptId:rid,requestId,action,organizationId:s.scope.organizationId,propertyId:s.scope.propertyId,courseId:s.scope.courseId,representativeMembershipId:s.scope.membershipId,requestVersion:expected+1,immutable:true,createdAt:stamp()};const update:any={status:next,version:expected+1,updatedAt:stamp()};if(reply)update.messages=admin.firestore.FieldValue.arrayUnion({messageId:`esm_${supportDigest([requestId,c.commandId]).slice(0,32)}`,author:"representative",body:reply.body,receiptId:rid,createdAt:stamp()});if(action==="reopen")update.reopenCount=Number(x.reopenCount||0)+1;tx.update(requestRef(requestId),update);tx.create(receiptRef(rid),receipt);tx.create(commandRef,{commandId:c.commandId,digest,action,requestId,receiptId:rid,immutable:true,createdAt:stamp()})});return{...(await projection(s)),replayed};
}

export const getEnterprisePartnerSupportV1=onCall({enforceAppCheck:true},async r=>projection(await scoped(r)));
export const createEnterpriseSupportDraftV1=onCall({enforceAppCheck:true},async r=>{const s=await scoped(r),c=cmd(r,"create"),draft=normalizeSupportDraft({type:r.data?.type,subject:r.data?.subject,body:r.data?.body,locale:r.data?.locale,notificationPreferences:r.data?.notificationPreferences}),requestId=supportRequestId(s.scope.organizationId,s.scope.propertyId,s.scope.courseId,c.commandId),digest=supportDigest({draft,scope:s.scope,source:s.authority.sourceVersion}),commandRef=db.collection("enterprise_support_commands").doc(supportCommandId(s.uid,c.commandId,"create"));let replayed=false;await db.runTransaction(async tx=>{const prior=await tx.get(commandRef);if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");replayed=true;return}tx.create(requestRef(requestId),{schema:ENTERPRISE_SUPPORT_SCHEMA,requestId,organizationId:s.scope.organizationId,propertyId:s.scope.propertyId,courseId:s.scope.courseId,representativeMembershipId:s.scope.membershipId,representativeAuthoritySourceVersion:s.authority.sourceVersion,applicationId:s.applicationId,applicationState:s.applicationState,trialState:s.trialState,...draft,status:"draft",version:1,messages:[{messageId:`esm_${supportDigest([requestId,"initial"]).slice(0,32)}`,author:"representative",body:draft.body,createdAt:stamp()}],evidence:[],reopenCount:0,createdAt:stamp(),updatedAt:stamp()});tx.create(commandRef,{commandId:c.commandId,digest,action:"create",requestId,immutable:true,createdAt:stamp()})});return{...(await projection(s)),requestId,replayed}});
export const attachEnterpriseSupportEvidenceV1=onCall({enforceAppCheck:true},async r=>{const s=await scoped(r),c=cmd(r,"evidence"),requestId=safeId(r.data?.requestId,"Request"),expected=version(r.data?.expectedVersion),evidence=normalizeEvidence(r.data?.evidence),digest=supportDigest({requestId,expected,evidence,scope:s.scope,source:s.authority.sourceVersion}),commandRef=db.collection("enterprise_support_commands").doc(supportCommandId(s.uid,c.commandId,"evidence")),registry=db.collection("enterprise_support_evidence_registry").doc(evidence.referenceId);let replayed=false;await db.runTransaction(async tx=>{const[doc,prior,ref]=await Promise.all([tx.get(requestRef(requestId)),tx.get(commandRef),tx.get(registry)]);if(prior.exists){if(prior.data()?.digest!==digest)throw new HttpsError("already-exists","COMMAND_REPLAY_CONFLICT");replayed=true;return}let x:any;try{x=assertSupportDocument(doc.data(),s.scope)}catch{throw new HttpsError("not-found","Support request unavailable.")}const e=ref.data()||{};if(!ref.exists||e.type!==evidence.type||e.organizationId!==s.scope.organizationId||e.propertyId!==s.scope.propertyId||e.courseId!==s.scope.courseId||e.applicationId!==s.applicationId||e.ownerMembershipId!==s.scope.membershipId||e.status!=="available")throw new HttpsError("failed-precondition","Evidence reference unavailable.");if(x.version!==expected||x.status!=="draft")throw new HttpsError("aborted","Draft version unavailable.");if((x.evidence?.length||0)>=10)throw new HttpsError("resource-exhausted","Evidence limit reached.");if((x.evidence||[]).some((item:any)=>item.referenceId===evidence.referenceId))throw new HttpsError("already-exists","Evidence already attached.");tx.update(requestRef(requestId),{evidence:admin.firestore.FieldValue.arrayUnion(evidence),version:expected+1,updatedAt:stamp()});tx.create(commandRef,{commandId:c.commandId,digest,action:"evidence",requestId,immutable:true,createdAt:stamp()})});return{...(await projection(s)),replayed}});
export const submitEnterpriseSupportRequestV1=onCall({enforceAppCheck:true},r=>mutate(r,"submit"));
export const replyEnterpriseSupportRequestV1=onCall({enforceAppCheck:true},r=>mutate(r,"reply"));
export const withdrawEnterpriseSupportRequestV1=onCall({enforceAppCheck:true},r=>mutate(r,"withdraw"));
export const reopenEnterpriseSupportRequestV1=onCall({enforceAppCheck:true},r=>mutate(r,"reopen"));
export const closeEnterpriseSupportRequestV1=onCall({enforceAppCheck:true},r=>mutate(r,"close"));
