import {createHash} from "node:crypto";
export const ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA="golfriend.enterprise-booking-golfer-binding.v2" as const;
export const ENTERPRISE_BOOKING_GOLFER_PROJECTION_SCHEMA="golfriend.enterprise-booking-golfer-projection.v2" as const;
export const ENTERPRISE_BOOKING_GOLFER_AUTHORITY_SCHEMA="golfriend.enterprise-booking-golfer-authority.v2" as const;
const GOLFER=/^gfr_[A-Za-z0-9_-]{24,160}$/,ID=/^[A-Za-z0-9_-]{8,200}$/,hash=(value:string)=>createHash("sha256").update(value).digest("hex");
export type GolferClaim=Readonly<{golferRef:string;version:number}>;
export type GolferBinding=Readonly<{schema:typeof ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA;bindingId:string;golferRef:string;golferRefVersion:number;producerId:string;correlationId:string;bookingId:string;f7RequestId:string;f7RequestVersion:number;intakeDigest:string;immutable:true}>;
export function serverIssuedGolferClaim(token:Record<string,unknown>):GolferClaim{const golferRef=String(token.bookingGolferRef||""),version=Number(token.bookingGolferRefVersion);if(!GOLFER.test(golferRef)||!Number.isSafeInteger(version)||version!==1)throw new Error("GOLFER_IDENTITY_AUTHORITY_UNAVAILABLE");return Object.freeze({golferRef,version})}
export const enterpriseBookingGolferBindingId=(correlationId:string)=>`ebgb_${hash(correlationId).slice(0,40)}`;
export const enterpriseBookingGolferAuthorityId=(golferRef:string)=>`ebga_${hash(golferRef).slice(0,40)}`;
export function buildEnterpriseBookingGolferAuthority(golferRef:string,producerId:string){if(!GOLFER.test(golferRef)||!ID.test(producerId))throw new Error("GOLFER_AUTHORITY_INVALID");return Object.freeze({schema:ENTERPRISE_BOOKING_GOLFER_AUTHORITY_SCHEMA,authorityId:enterpriseBookingGolferAuthorityId(golferRef),golferRef,producerId,status:"active" as const,version:1,immutableIdentity:true as const})}
export function assertEnterpriseBookingGolferAuthority(raw:unknown,claim:GolferClaim){const value=raw as ReturnType<typeof buildEnterpriseBookingGolferAuthority>;if(!value||value.schema!==ENTERPRISE_BOOKING_GOLFER_AUTHORITY_SCHEMA||value.authorityId!==enterpriseBookingGolferAuthorityId(claim.golferRef)||value.golferRef!==claim.golferRef||value.status!=="active"||value.version!==claim.version||value.immutableIdentity!==true)throw new Error("GOLFER_IDENTITY_AUTHORITY_UNAVAILABLE");return value}
export function buildEnterpriseBookingGolferBinding(input:Readonly<{golferRef:string;golferRefVersion:number;producerId:string;correlationId:string;bookingId:string;f7RequestId:string;f7RequestVersion:number;intakeDigest:string}>):GolferBinding{if(!GOLFER.test(input.golferRef)||input.golferRefVersion!==1||![input.producerId,input.correlationId,input.bookingId,input.f7RequestId].every(x=>ID.test(x))||!Number.isSafeInteger(input.f7RequestVersion)||input.f7RequestVersion<1||!/^[a-f0-9]{64}$/.test(input.intakeDigest))throw new Error("GOLFER_BINDING_INVALID");return Object.freeze({schema:ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA,bindingId:enterpriseBookingGolferBindingId(input.correlationId),...input,immutable:true})}
export function assertEnterpriseBookingGolferBinding(binding:unknown,claim:GolferClaim,expected:Readonly<{correlationId:string;bookingId:string;intakeDigest:string}>):GolferBinding{const value=binding as GolferBinding;if(!value||value.schema!==ENTERPRISE_BOOKING_GOLFER_BINDING_SCHEMA||value.immutable!==true||value.bindingId!==enterpriseBookingGolferBindingId(expected.correlationId)||value.golferRef!==claim.golferRef||value.golferRefVersion!==claim.version||value.correlationId!==expected.correlationId||value.bookingId!==expected.bookingId||value.intakeDigest!==expected.intakeDigest)throw new Error("GOLFER_BINDING_UNAVAILABLE");return value}
function safeRequest(raw:unknown){const request=raw as Record<string,unknown>,window=request?.timeWindow as Record<string,unknown>,preferences=request?.preferences as Record<string,unknown>,exact=(value:Record<string,unknown>,keys:string[])=>value&&Object.keys(value).length===keys.length&&keys.every(key=>Object.prototype.hasOwnProperty.call(value,key));if(!exact(request,["date","timeWindow","partySize","preferences"])||!/^\d{4}-\d{2}-\d{2}$/.test(String(request.date))||!Number.isSafeInteger(request.partySize)||Number(request.partySize)<1||Number(request.partySize)>8||!exact(window,["start","end","timeZone"])||!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(window.start))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(window.end))||String(window.start)>=String(window.end)||!/^([A-Za-z_]+\/[A-Za-z_+-]+|UTC)$/.test(String(window.timeZone))||!exact(preferences,["locale","allowedChannels","shareContact"])||!["en","th","ko","ja","zh","es","fr","de"].includes(String(preferences.locale))||!Array.isArray(preferences.allowedChannels)||preferences.allowedChannels.some(value=>!["course_phone","course_email","provider_redirect"].includes(String(value)))||typeof preferences.shareContact!=="boolean")throw new Error("GOLFER_BOOKING_REQUEST_INVALID");return Object.freeze({date:String(request.date),timeWindow:Object.freeze({start:String(window.start),end:String(window.end),timeZone:String(window.timeZone)}),partySize:Number(request.partySize),preferences:Object.freeze({locale:String(preferences.locale),allowedChannels:Object.freeze(preferences.allowedChannels.map(String)),shareContact:preferences.shareContact})})}
function safeAlternative(raw:unknown){if(raw==null)return null;const value=raw as Record<string,unknown>,keys=["slotId","date","time","timeZone","slotVersion"];if(Object.keys(value).length!==keys.length||keys.some(key=>!Object.prototype.hasOwnProperty.call(value,key))||!ID.test(String(value.slotId))||!/^\d{4}-\d{2}-\d{2}$/.test(String(value.date))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(String(value.time))||!/^([A-Za-z_]+\/[A-Za-z_+-]+|UTC)$/.test(String(value.timeZone))||!Number.isSafeInteger(value.slotVersion)||Number(value.slotVersion)<1)throw new Error("GOLFER_BOOKING_ALTERNATIVE_INVALID");return Object.freeze({slotId:String(value.slotId),date:String(value.date),time:String(value.time),timeZone:String(value.timeZone),slotVersion:Number(value.slotVersion)})}
export function golferOwnedBookingProjection(input:Readonly<{binding:GolferBinding;correlation:Record<string,unknown>;booking:Record<string,unknown>}>){const{binding,correlation,booking}=input,status=String(booking.status||""),statuses=["course_reviewing","course_confirmed","alternative_proposed","cancellation_requested","cancellation_accepted","cancellation_declined","cancelled","expired","ambiguous_locked"];if(correlation.schema!=="golfriend.enterprise-booking-correlation.v1"||booking.schema!=="golfriend.enterprise-correlated-booking.v2"||correlation.correlationId!==binding.correlationId||correlation.bookingId!==binding.bookingId||correlation.intakeDigest!==binding.intakeDigest||booking.bookingId!==binding.bookingId||booking.correlationId!==binding.correlationId||correlation.version!==booking.version||correlation.status!==status||!statuses.includes(status)||!Number.isSafeInteger(booking.version)||Number(booking.version)<1||!Number.isSafeInteger(booking.courseVersion)||Number(booking.courseVersion)<1)throw new Error("GOLFER_BOOKING_BINDING_MISMATCH");return Object.freeze({schema:ENTERPRISE_BOOKING_GOLFER_PROJECTION_SCHEMA,bookingId:binding.bookingId,correlationId:binding.correlationId,status,version:Number(booking.version),courseId:String(booking.courseId||""),courseVersion:Number(booking.courseVersion),request:safeRequest(correlation.request),alternativeSlot:safeAlternative(booking.alternativeSlot),sourceVersion:Object.freeze({f7RequestVersion:binding.f7RequestVersion,enterpriseBookingVersion:Number(booking.version)}),boundary:"PRIVACY_MINIMIZED_OWN_BOOKING_ONLY" as const})}
