import assert from "node:assert/strict";
import {buildEnterpriseBookingCoordinationItem, buildEnterpriseBookingCoordinationProjection} from "./enterpriseBookingCoordinationProjection.js";

const now = Date.parse("2027-01-01T00:00:00Z"), booking = {schema: "golfriend.enterprise-correlated-booking.v2", bookingId: "booking_12345678", correlationId: `ebc_${"a".repeat(32)}`, organizationId: "org_12345678", propertyId: "property_12345678", courseId: "course_12345678", courseVersion: 2, f7SourceVersion: 3, version: 1, status: "course_reviewing", operationLocks: {}}, correlation = {schema: "golfriend.enterprise-booking-correlation.v1", bookingId: booking.bookingId, correlationId: booking.correlationId, course: {courseId: booking.courseId}, golferRef: `gfr_${"b".repeat(32)}`, version: 1, status: "course_reviewing", request: {date: "2027-02-01", timeWindow: {start: "08:00", end: "10:00", timeZone: "Asia/Bangkok"}, partySize: 4, preferences: {locale: "th", allowedChannels: ["course_email"], shareContact: false}}, alternativeSlot: null}, outbox = [{eventId: "event_12345678", state: "course_reviewing", enterpriseBooking: {version: 1}, occurredAt: "2027-01-01T00:00:00Z"}], scope: any = {projectionVersion: "golfriend.enterprise-booking-scope.v1", membershipId: "membership_12345678", role: "booking_staff", organizationId: booking.organizationId, propertyIds: [booking.propertyId], courseIds: [booking.courseId], delegatedCourseIds: [booking.courseId], sourceVersion: "a".repeat(64), generatedAt: new Date(now).toISOString(), expiresAt: new Date(now + 300000).toISOString(), freshness: "fresh"};
let count = 0; const check = (name: string, fn: () => void) => {fn(); console.log(`ok ${++count} - ${name}`);};
check("privacy-minimal request history and recipient are projected", () => {const item = buildEnterpriseBookingCoordinationItem({booking, correlation, outbox, receipts: [{receiptId: "receipt_12345678"}]}); assert.equal(item.request.partySize, 4); assert.match(item.authorizedCourseRecipientRef, /^ecr_[a-f0-9]{40}$/); assert.equal(item.history[0].status, "course_reviewing"); assert.doesNotMatch(JSON.stringify(item), /memberUid|displayName|"email":|"phone":|"price":|"payment":|"refund":|"commission":|"invoice":/i);});
check("ambiguous lock overrides display without clearing source", () => {const item = buildEnterpriseBookingCoordinationItem({booking: {...booking, operationLocks: {confirm: {state: "ambiguous_locked", operationId: "operation_12345678"}}}, correlation, outbox, receipts: []}); assert.equal(item.status, "ambiguous_locked"); assert.equal(item.operation?.operationId, "operation_12345678");});
check("foreign course and malformed source fail closed", () => {const item = buildEnterpriseBookingCoordinationItem({booking, correlation, outbox, receipts: []}); assert.throws(() => buildEnterpriseBookingCoordinationProjection({...scope, courseIds: ["course_foreign"]}, [item], now), /SCOPE_INVALID/); assert.throws(() => buildEnterpriseBookingCoordinationItem({booking: {...booking, status: "confirmed"}, correlation, outbox, receipts: []}), /SOURCE_INVALID/);});
check("role ceiling and freshness are server bound", () => {const item = buildEnterpriseBookingCoordinationItem({booking, correlation, outbox, receipts: []}), projection = buildEnterpriseBookingCoordinationProjection(scope, [item], now); assert.equal(projection.permissions.confirm, true); assert.equal(projection.permissions.readOnly, false); assert.throws(() => buildEnterpriseBookingCoordinationProjection({...scope, expiresAt: new Date(now - 1).toISOString()}, [item], now), /SCOPE_INVALID/);});
console.log(`enterprise booking coordination projection: ${count} checks passed.`);
