import {createHash} from "node:crypto";

export const ENTERPRISE_OPERATIONS_SCHEMA="golfriend.enterprise-operations.v2" as const;
export const ENTERPRISE_LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export const CAMPAIGN_STATES=["draft","review","active","paused","archived"] as const;
export const DAY_STATES=["planning","review","ready","in_progress","complete"] as const;
const id=(value:unknown,label:string)=>{const out=String(value||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(out))throw new Error(`${label}_INVALID`);return out};
const text=(value:unknown,label:string,max:number)=>{const out=String(value||"").trim();if(!out||out.length>max||/[\u0000-\u0008]/.test(out))throw new Error(`${label}_INVALID`);return out};
const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
export const operationalId=(kind:string,scope:string,command:string)=>`${kind}_${digest([kind,scope,command]).slice(0,28)}`;

export function campaignInput(raw:any){
 const locales=Array.isArray(raw?.locales)?[...new Set(raw.locales.map(String))].sort():[];
 if(!locales.length||locales.some(x=>!ENTERPRISE_LOCALES.includes(x as any)))throw new Error("CAMPAIGN_LOCALES_INVALID");
 const startsAt=new Date(raw?.startsAt).toISOString(),endsAt=new Date(raw?.endsAt).toISOString();if(Date.parse(endsAt)<=Date.parse(startsAt))throw new Error("CAMPAIGN_WINDOW_INVALID");
 return Object.freeze({title:text(raw.title,"TITLE",160),organizationId:id(raw.organizationId,"ORGANIZATION"),courseId:id(raw.courseId,"COURSE"),mediaAssetId:id(raw.mediaAssetId,"MEDIA"),locales,startsAt,endsAt,entitlementKey:id(raw.entitlementKey,"ENTITLEMENT"),sponsoredDisclosure:raw.sponsoredDisclosure===true});
}
export function campaignTransition(state:unknown,action:unknown){const map:Record<string,Record<string,string>>={draft:{submit:"review",archive:"archived"},review:{activate:"active",return:"draft",archive:"archived"},active:{pause:"paused",archive:"archived"},paused:{resume:"active",archive:"archived"}};const next=map[String(state)]?.[String(action)];if(!next)throw new Error("CAMPAIGN_TRANSITION_DENIED");return next}
export function validateAttachment(raw:any){const type=String(raw?.contentType||"").toLowerCase(),size=Number(raw?.sizeBytes),name=text(raw?.fileName,"FILE_NAME",180);if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(type)||!Number.isSafeInteger(size)||size<1||size>8*1024*1024||/[/\\]|\.\./.test(name))throw new Error("ATTACHMENT_INVALID");return Object.freeze({fileName:name,contentType:type,sizeBytes:size,sha256:text(raw.sha256,"SHA256",64).toLowerCase()})}
export function deterministicFlights(roster:any[],size=4){if(!Number.isSafeInteger(size)||size<2||size>5)throw new Error("FLIGHT_SIZE_INVALID");const rows=roster.map(x=>({participantId:id(x.participantId,"PARTICIPANT"),seed:Number.isFinite(Number(x.seed))?Number(x.seed):Number.MAX_SAFE_INTEGER,displayLabel:text(x.displayLabel,"DISPLAY",120)}));if(new Set(rows.map(x=>x.participantId)).size!==rows.length)throw new Error("ROSTER_DUPLICATE");rows.sort((a,b)=>a.seed-b.seed||a.participantId.localeCompare(b.participantId));return Object.freeze(rows.reduce<any[][]>((out,row,index)=>{const flight=Math.floor(index/size);(out[flight]||=[]).push(Object.freeze(row));return out},[]).map((members,index)=>Object.freeze({flightNumber:index+1,members:Object.freeze(members),reviewRequired:true})))}
export function tvProjection(publication:any,certified:any){if(!publication||publication.state!=="published"||publication.visibility!=="public"||publication.tournamentId!==certified?.tournamentId||certified?.state!=="certified")return Object.freeze({state:"unavailable",tournament:null,results:[]});const results=Array.isArray(certified.results)?certified.results.map((x:any)=>({position:Number(x.position),displayLabel:text(x.displayLabel,"DISPLAY",120),scoreLabel:text(x.scoreLabel,"SCORE",20),throughLabel:text(x.throughLabel,"THROUGH",20)})).filter((x:any)=>Number.isSafeInteger(x.position)&&x.position>0).sort((a:any,b:any)=>a.position-b.position):[];return Object.freeze({state:results.length?"ready":"empty",tournament:{tournamentId:id(publication.tournamentId,"TOURNAMENT"),name:text(publication.name,"NAME",160),startsAt:new Date(publication.startsAt).toISOString(),publicationRevision:Number(publication.publicationRevision)},results:Object.freeze(results)})}
export function unifiedInventory(campaigns:any[],tournaments:any[]){return Object.freeze([...campaigns.map(x=>({kind:"campaign",id:id(x.campaignId,"CAMPAIGN"),title:text(x.title,"TITLE",160),status:String(x.state),ownerId:id(x.organizationId,"OWNER"),nextAction:String(x.nextAction||"review"),href:`#campaign:${encodeURIComponent(x.campaignId)}`})),...tournaments.map(x=>({kind:"tournament",id:id(x.tournamentId,"TOURNAMENT"),title:text(x.name,"NAME",160),status:String(x.state),ownerId:id(x.organizationId,"OWNER"),nextAction:String(x.nextAction||"review"),href:`#tournament:${encodeURIComponent(x.tournamentId)}`}))].sort((a,b)=>a.title.localeCompare(b.title)))}
