import {createHash} from "node:crypto";
import {deriveEnterpriseBookingToken,ENTERPRISE_BOOKING_ACTIONS,type EnterpriseBookingAction} from "./enterpriseBookingV2Operation.js";
export const BOOKING_TOKEN_RECOVERY_SCHEMA="golfriend.enterprise-booking-token-rotation-receipt.v2" as const;
export const BOOKING_TOKEN_RECOVERY_KEY_VERSION=1 as const;
export type BookingRecoveryIntent=Readonly<{operationId:string;intentDigest:string;actorUid:string;membershipId:string;organizationId:string;propertyId:string;courseId:string;bookingId:string;action:EnterpriseBookingAction;commandId:string;expectedVersion:number;payloadDigest:string;authoritySourceVersion:string}>;
export type BookingTokenRecoveryRequest=Readonly<{bookingId:string;operationId:string;recoveryCommandId:string;expectedOperationDigest:string}>;
const ID=/^[A-Za-z0-9_-]{8,200}$/,SHA=/^[a-f0-9]{64}$/;
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
export const bookingTokenRotationId=(operationId:string,recoveryCommandId:string)=>{if(!ID.test(operationId)||!ID.test(recoveryCommandId))throw new Error("RECOVERY_COMMAND_INVALID");return `ebtr_${hash(`${operationId}|${recoveryCommandId}`).slice(0,40)}`};
const stable=(v:unknown):string=>v&&typeof v==="object"?`{${Object.keys(v as Record<string,unknown>).sort().map(k=>`${JSON.stringify(k)}:${stable((v as Record<string,unknown>)[k])}`).join(",")}}`:JSON.stringify(v);
export function validateBookingRecoveryIntent(raw:Record<string,unknown>):BookingRecoveryIntent{const v=raw as Partial<BookingRecoveryIntent>;if(![v.operationId,v.actorUid,v.membershipId,v.organizationId,v.propertyId,v.courseId,v.bookingId,v.commandId].every(x=>ID.test(String(x||"")))||!SHA.test(String(v.intentDigest||""))||!SHA.test(String(v.payloadDigest||""))||!/^[a-f0-9]{32,64}$/.test(String(v.authoritySourceVersion||""))||!ENTERPRISE_BOOKING_ACTIONS.includes(v.action as EnterpriseBookingAction)||!Number.isSafeInteger(v.expectedVersion)||Number(v.expectedVersion)<1)throw new Error("RECOVERY_INTENT_INVALID");return Object.freeze({operationId:String(v.operationId),intentDigest:String(v.intentDigest),actorUid:String(v.actorUid),membershipId:String(v.membershipId),organizationId:String(v.organizationId),propertyId:String(v.propertyId),courseId:String(v.courseId),bookingId:String(v.bookingId),action:v.action as EnterpriseBookingAction,commandId:String(v.commandId),expectedVersion:Number(v.expectedVersion),payloadDigest:String(v.payloadDigest),authoritySourceVersion:String(v.authoritySourceVersion)})}
export function validateBookingTokenRecoveryRequest(raw:Record<string,unknown>):BookingTokenRecoveryRequest{const keys=Object.keys(raw);if(keys.length!==4||!["bookingId","operationId","recoveryCommandId","expectedOperationDigest"].every(k=>keys.includes(k))||!ID.test(String(raw.bookingId||""))||!ID.test(String(raw.operationId||""))||!ID.test(String(raw.recoveryCommandId||""))||!SHA.test(String(raw.expectedOperationDigest||"")))throw new Error("RECOVERY_COMMAND_INVALID");return Object.freeze({bookingId:String(raw.bookingId),operationId:String(raw.operationId),recoveryCommandId:String(raw.recoveryCommandId),expectedOperationDigest:String(raw.expectedOperationDigest)})}
export function deriveBookingRecoveryToken(intentDigest:string,tokenVersion:number,nonce:string,signerKeyVersion:number,secret:string){if(signerKeyVersion!==BOOKING_TOKEN_RECOVERY_KEY_VERSION)throw new Error("RECOVERY_SIGNER_UNAVAILABLE");const token=deriveEnterpriseBookingToken(intentDigest,tokenVersion,nonce,secret);return Object.freeze({...token,signerKeyVersion,intentDigest})}
export function buildBookingTokenRotation(input:Readonly<{intent:BookingRecoveryIntent;request:BookingTokenRecoveryRequest;previousTokenDigest:string;previousTokenVersion:number;nextTokenVersion:number;nonce:string;signerKeyVersion:number;secret:string}>){const intent=validateBookingRecoveryIntent(input.intent as unknown as Record<string,unknown>),request=validateBookingTokenRecoveryRequest(input.request as unknown as Record<string,unknown>);if(request.bookingId!==intent.bookingId||request.operationId!==intent.operationId||request.expectedOperationDigest!==intent.intentDigest||!SHA.test(input.previousTokenDigest)||input.nextTokenVersion!==input.previousTokenVersion+1)throw new Error("RECOVERY_IDENTITY_CONFLICT");const next=deriveBookingRecoveryToken(intent.intentDigest,input.nextTokenVersion,input.nonce,input.signerKeyVersion,input.secret),recoveryDigest=hash(stable({request,previousTokenDigest:input.previousTokenDigest,previousTokenVersion:input.previousTokenVersion,nextTokenVersion:input.nextTokenVersion,nonce:input.nonce,signerKeyVersion:input.signerKeyVersion})),receipt=Object.freeze({schema:BOOKING_TOKEN_RECOVERY_SCHEMA,rotationId:bookingTokenRotationId(intent.operationId,request.recoveryCommandId),operationId:intent.operationId,operationDigest:intent.intentDigest,bookingId:intent.bookingId,action:intent.action,commandId:intent.commandId,recoveryCommandId:request.recoveryCommandId,recoveryDigest,previousTokenDigest:input.previousTokenDigest,tokenDigest:next.tokenDigest,previousTokenVersion:input.previousTokenVersion,tokenVersion:next.tokenVersion,nonce:input.nonce,signerKeyVersion:next.signerKeyVersion,immutable:true as const});return Object.freeze({token:next.token,receipt})}
export function replayBookingTokenRotation(stored:unknown,input:Parameters<typeof buildBookingTokenRotation>[0]){const expected=buildBookingTokenRotation(input),v=stored as typeof expected.receipt|null;if(!v||v.schema!==BOOKING_TOKEN_RECOVERY_SCHEMA||v.immutable!==true||v.rotationId!==expected.receipt.rotationId||v.recoveryDigest!==expected.receipt.recoveryDigest||v.operationId!==expected.receipt.operationId||v.operationDigest!==expected.receipt.operationDigest||v.previousTokenDigest!==expected.receipt.previousTokenDigest||v.tokenDigest!==expected.receipt.tokenDigest||v.previousTokenVersion!==expected.receipt.previousTokenVersion||v.tokenVersion!==expected.receipt.tokenVersion||v.signerKeyVersion!==expected.receipt.signerKeyVersion)throw new Error("RECOVERY_REPLAY_CONFLICT");return Object.freeze({token:expected.token,receipt:v})}
