import * as admin from "firebase-admin";
import {createHash,randomBytes} from "node:crypto";
import {defineSecret} from "firebase-functions/params";
import {HttpsError,onCall} from "firebase-functions/v2/https";
import {bookingScope,transactionBookingAuthority} from "./partnerBookingRuntime.js";
import {bookingOperationIntentDigest,buildBookingTokenRotation,replayBookingTokenRotation} from "./partnerBookingTokenRecovery.js";
if(!admin.apps.length)admin.initializeApp();
const db=admin.firestore(),signer=defineSecret("BOOKING_CONFIRMATION_HMAC_V2"),AUTH_SCHEMA="golfriend.partner-booking-operation-authorization.v2",TOKEN_SCHEMA="golfriend.partner-booking-confirmation-token.v2",ID=/^[A-Za-z0-9_-]{2,200}$/,SHA=/^[a-f0-9]{64}$/;
const exact=(v:any,k:string[])=>v&&typeof v==="object"&&Object.keys(v).length===k.length&&k.every(x=>Object.prototype.hasOwnProperty.call(v,x));
export const BOOKING_TOKEN_RECOVERY_COMMISSIONED=false as const;
export const recoverPlayBookingConfirmationV2=onCall({enforceAppCheck:true,secrets:[signer]},async request=>{
 if(!request.auth)throw new HttpsError("unauthenticated","Authentication required.");
 if(!BOOKING_TOKEN_RECOVERY_COMMISSIONED)throw new HttpsError("unavailable","booking_token_recovery_authority_unavailable");
 if(!exact(request.data,["bookingId","operationId","recoveryCommandId","expectedOperationDigest"])||![request.data.bookingId,request.data.operationId,request.data.recoveryCommandId].every((x:any)=>ID.test(String(x)))||!SHA.test(String(request.data.expectedOperationDigest)))throw new HttpsError("invalid-argument","Recovery request invalid.");
 const secret=signer.value();if(!secret)throw new HttpsError("unavailable","booking_token_recovery_authority_unavailable");
 const caller=request.auth.uid,scope=await bookingScope(caller),authorizationRef=db.collection("play_booking_operation_authorizations_v2").doc(String(request.data.operationId)),bookingRef=db.collection("bookings").doc(String(request.data.bookingId)),rotationRef=db.collection("play_booking_token_rotation_receipts_v2").doc(`pbtr_${createHash("sha256").update(`${request.data.operationId}|${request.data.recoveryCommandId}`).digest("hex").slice(0,40)}`),nonce=randomBytes(32).toString("hex");
 return db.runTransaction(async tx=>{
  const[authorization,booking,prior]=await Promise.all([tx.get(authorizationRef),tx.get(bookingRef),tx.get(rotationRef)]),a=authorization.data()||{},b=booking.data()||{};
  if(!authorization.exists||a.schema!==AUTH_SCHEMA||a.operationId!==request.data.operationId||a.bookingId!==request.data.bookingId||a.actorUid!==caller||a.membershipId!==scope.membershipId||a.organizationId!==scope.organizationId||a.state!=="active"||a.recoverableUntilMs<=Date.now()||a.intentDigest!==request.data.expectedOperationDigest||!Number.isSafeInteger(a.tokenVersion)||a.tokenVersion<1||!SHA.test(String(a.currentTokenDigest)))throw new HttpsError("failed-precondition","Recovery unavailable.");
  const authority=await transactionBookingAuthority(tx,caller,scope,String(a.courseId),"mutate");
  if(authority.membershipId!==a.membershipId||authority.organizationId!==a.organizationId||authority.propertyId!==a.propertyId||authority.courseId!==a.courseId||authority.sourceVersion!==a.authorityVersion||!booking.exists||b.bookingId!==a.bookingId||b.organizationId!==a.organizationId||b.propertyId!==a.propertyId||b.courseId!==a.courseId||Number(b.version)!==Number(a.expectedVersion)||["ambiguous","ambiguous_locked"].includes(String(b.operationLocks?.[a.action]?.state)))throw new HttpsError("failed-precondition","Recovery unavailable.");
  const intent={actorUid:caller,membershipId:String(a.membershipId),organizationId:String(a.organizationId),propertyId:String(a.propertyId),courseId:String(a.courseId),bookingId:String(a.bookingId),action:a.action,commandId:String(a.commandId),expectedVersion:Number(a.expectedVersion),payloadDigest:String(a.payloadDigest),authorityVersion:String(a.authorityVersion)} as const;
  if(bookingOperationIntentDigest(intent)!==a.intentDigest)throw new HttpsError("failed-precondition","Recovery unavailable.");
  if(prior.exists){try{const storedReceipt=prior.data()?.receipt,previousTokenVersion=Number(storedReceipt?.previousTokenVersion),input={intent,recoveryCommandId:String(request.data.recoveryCommandId),previousTokenVersion,nonce:String(prior.data()?.nonce),secret},rotation=buildBookingTokenRotation(input);if(a.tokenVersion!==rotation.receipt.tokenVersion||a.currentTokenDigest!==rotation.receipt.tokenDigest)throw new Error();return{success:true,...replayBookingTokenRotation({token:rotation.token,receipt:storedReceipt},input)}}catch{throw new HttpsError("already-exists","Recovery command conflict.")}}
  const input={intent,recoveryCommandId:String(request.data.recoveryCommandId),previousTokenVersion:Number(a.tokenVersion),nonce,secret},rotation=buildBookingTokenRotation(input);
  const oldTokenRef=db.collection("play_booking_confirmation_tokens_v2").doc(String(a.currentTokenDigest)),oldToken=await tx.get(oldTokenRef);
  if(!oldToken.exists||oldToken.data()?.schema!==TOKEN_SCHEMA||oldToken.data()?.operationId!==a.operationId||oldToken.data()?.tokenVersion!==a.tokenVersion||oldToken.data()?.state!=="active")throw new HttpsError("failed-precondition","Recovery unavailable.");
  const nextTokenRef=db.collection("play_booking_confirmation_tokens_v2").doc(rotation.receipt.tokenDigest),stamp=admin.firestore.FieldValue.serverTimestamp();
  tx.update(oldTokenRef,{state:"revoked",revokedAt:stamp,rotationId:rotation.receipt.rotationId});tx.create(nextTokenRef,{schema:TOKEN_SCHEMA,operationId:a.operationId,operationDigest:a.intentDigest,tokenVersion:rotation.receipt.tokenVersion,tokenDigest:rotation.receipt.tokenDigest,state:"active",issuedAt:stamp,expiresAtMs:Date.now()+120_000});tx.update(authorizationRef,{tokenVersion:rotation.receipt.tokenVersion,currentTokenDigest:rotation.receipt.tokenDigest,updatedAt:stamp});tx.create(rotationRef,{schema:"golfriend.partner-booking-token-rotation-receipt.v2",rotationId:rotation.receipt.rotationId,operationId:a.operationId,operationDigest:a.intentDigest,recoveryCommandId:request.data.recoveryCommandId,nonce,receipt:rotation.receipt,immutable:true,createdAt:stamp});return{success:true,...rotation};
 });
});
