import*as admin from"firebase-admin";import{defineString}from"firebase-functions/params";import{HttpsError,onCall}from"firebase-functions/v2/https";import{isActiveStaff}from"./authority.js";import{ACTIVATION_SCHEMA,canManage,claimId,identityHash,immutableReceipt,invitationId,nextVersion,organizationId,transitionClaim,validateCommand,validateRole,validateVersion}from"./partnerActivationDomain.js";import{buildFirstTrialStatement,resolveFinalTier,statementId,verifyStoredStatement}from"./partnerFirstStatementDomain.js";
if(!admin.apps.length)admin.initializeApp();const db=admin.firestore(),notificationProvider=defineString("PARTNER_NOTIFICATION_PROVIDER",{default:""}),now=()=>admin.firestore.FieldValue.serverTimestamp(),docs=(s:FirebaseFirestore.QuerySnapshot)=>s.docs.map(d=>({id:d.id,...d.data()}));function auth(r:any){if(!r.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");return r.auth.uid as string}function cmd(r:any){try{return validateCommand(r.data?.commandId)}catch{throw new HttpsError("invalid-argument","Command id invalid.")}}async function staff(id:string){const s=await db.collection("admin_users").doc(id).get();if(!s.exists||!isActiveStaff(s.data()))throw new HttpsError("permission-denied","Active Admin role required.");return String(s.data()?.role)}async function member(id:string){const b=await db.collection("partner_identity_bindings").doc(id).get();if(!b.exists)throw new HttpsError("permission-denied","Approved partner required.");const m=await db.collection("partner_memberships").doc(`${b.data()?.organizationId}_${id}`).get();if(!m.exists||m.data()?.status!=="active")throw new HttpsError("permission-denied","Active membership required.");return m.data()as any}async function audit(scope:string,commandId:string,kind:string,role:string){const value=immutableReceipt(scope,commandId,kind);await db.collection("partner_authority_audits").doc(value.receiptId).create({...value,actorRole:role,createdAt:now()}).catch((e:any)=>{if(e?.code!==6)throw e});return value}
export const activatePartner=onCall({enforceAppCheck:true},async r=>{const role=await staff(auth(r)),commandId=cmd(r),appId=String(r.data?.applicationId||""),courseId=String(r.data?.courseId||""),adminTierDecision=String(r.data?.tier||""),appRef=db.collection("partner_applications_v2").doc(appId),candidateRef=db.collection("course_growth_candidates").doc(appId),orgId=organizationId(appId),orgRef=db.collection("partner_organizations").doc(orgId);if(!appId||!courseId||(adminTierDecision&&!["small_business","enterprise"].includes(adminTierDecision)))throw new HttpsError("invalid-argument","Activation invalid.");return db.runTransaction(async tx=>{const[app,candidate,course,org]=await Promise.all([tx.get(appRef),tx.get(candidateRef),tx.get(db.collection("courses").doc(courseId)),tx.get(orgRef)]);if(!app.exists||app.data()?.status!=="approved")throw new HttpsError("failed-precondition","Approved application and candidate required.");if(!course.exists)throw new HttpsError("not-found","Course missing.");const owner=String(app.data()?.applicantUid||"");if(!owner)throw new HttpsError("failed-precondition","Verified identity missing.");
    // Restart is decided BEFORE the candidate-state gate. A first activation moves the candidate to
    // "activation_ready", so checking the candidate first made this branch unreachable and turned every
    // retry into "Approved application and candidate required." The organization is still proven to
    // belong to THIS application and course, so a conflicting reuse is still refused.
    if(org.exists){if(org.data()?.sourceApplicationId!==appId||!org.data()?.authorizedCourseIds?.includes(courseId))throw new HttpsError("already-exists","Conflicting activation.");return{success:true,organizationId:orgId,restarted:true}}
    if(!candidate.exists||candidate.data()?.status!=="admin_review_required")throw new HttpsError("failed-precondition","Approved application and candidate required.");
    // Final tier is derived from server-held application and contract records. The applicant's
    // selected intent never reaches this decision; an Admin may override only with an explicit
    // valid value, which is recorded on the receipt.
    const tier=resolveFinalTier({applicationOrganizationType:app.data()?.organizationType,contractApproved:app.data()?.contract?.contractuallyApproved,contractCommissionBps:app.data()?.contract?.commissionBps,adminTierDecision});
    const agreement=app.data()?.agreement;
    if(!agreement?.version||!agreement?.digest)throw new HttpsError("failed-precondition","Accepted agreement evidence is required before activation.");
    const activatedAt=new Date().toISOString();
    let firstStatement;
    try{firstStatement=buildFirstTrialStatement({organizationId:orgId,applicationId:appId,tier,activatedAt,agreementVersion:String(agreement.version),agreementDigest:String(agreement.digest),jurisdiction:String(app.data()?.country||"")});}
    catch{throw new HttpsError("failed-precondition","First trial statement could not be issued from the current records.");}const rec=immutableReceipt(orgId,commandId,"partner_activated");tx.create(orgRef,{schema:ACTIVATION_SCHEMA,organizationId:orgId,sourceApplicationId:appId,name:app.data()?.organization,country:app.data()?.country,status:"active",tier,primaryOwnerUid:owner,authorizedCourseIds:[courseId],version:1,createdAt:now()});tx.create(db.collection("partner_identity_bindings").doc(owner),{organizationId:orgId,verifiedAuthUid:owner,createdAt:now()});tx.create(db.collection("partner_memberships").doc(`${orgId}_${owner}`),{organizationId:orgId,uid:owner,role:"primary_owner",status:"active",version:1,createdAt:now()});tx.set(db.collection("b2b_partners").doc(owner),{uid:owner,organizationId:orgId,status:"active_partner",tier,sourceApplicationId:appId,updatedAt:now()},{merge:false});// Exactly one immutable 90-day trial and exactly one sealed first statement. Both use
    // tx.create with deterministic ids, so a concurrent or retried activation fails rather
    // than minting a second trial or a second receipt.
    tx.create(db.collection("partner_trials").doc(orgId),{schema:"golfriend.partner-trial.v1",organizationId:orgId,sourceApplicationId:appId,tier,startsAt:firstStatement.trialStartsAt,endsAt:firstStatement.trialEndsAt,days:firstStatement.trialDays,immutable:true,cancelledAt:null,createdAt:now()});
    tx.create(db.collection("partner_statements").doc(firstStatement.statementId),{...firstStatement,createdAt:now()});
    tx.update(candidateRef,{courseId,status:"activation_ready",publishToApp:false,activatedOrganizationId:orgId,updatedAt:now()});tx.create(db.collection("partner_authority_audits").doc(rec.receiptId),{...rec,actorRole:role,createdAt:now()});return{success:true,organizationId:orgId,restarted:false,tier,statementNumber:firstStatement.statementNumber,statementId:firstStatement.statementId,receipt:rec,publishedToApp:false,notificationStatus:notificationProvider.value()?"configured":"PROVIDER_UNCONFIGURED"}})});
export const claimCourseOperator=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),commandId=cmd(r),m=await member(caller),courseId=String(r.data?.courseId||""),expected=validateVersion(r.data?.expectedVersion),orgRef=db.collection("partner_organizations").doc(m.organizationId),id=claimId(m.organizationId,courseId),ref=db.collection("partner_course_claims").doc(id);if(!canManage(m.role))throw new HttpsError("permission-denied","Owner or manager required.");return db.runTransaction(async tx=>{const[org,course,current,operator]=await Promise.all([tx.get(orgRef),tx.get(db.collection("courses").doc(courseId)),tx.get(ref),tx.get(db.collection("course_operators").doc(courseId))]);if(!org.exists||org.data()?.status!=="active"||!org.data()?.authorizedCourseIds?.includes(courseId))throw new HttpsError("permission-denied","Course outside approved organization.");if(!course.exists)throw new HttpsError("not-found","Course missing.");if(operator.exists&&operator.data()?.organizationId!==m.organizationId)throw new HttpsError("already-exists","Course already claimed.");if(current.exists){if(current.data()?.commandId===commandId)return{success:true,claimId:id,status:current.data()?.status,restarted:true};throw new HttpsError("already-exists","Claim exists.")}const version=nextVersion(0,expected),rec=immutableReceipt(id,commandId,"claim_requested");tx.create(ref,{schema:ACTIVATION_SCHEMA,claimId:id,organizationId:m.organizationId,courseId,status:"pending_admin",requesterUid:caller,commandId,version,publishToApp:false,createdAt:now()});tx.create(db.collection("partner_authority_audits").doc(rec.receiptId),{...rec,actorRole:m.role,createdAt:now()});return{success:true,claimId:id,status:"pending_admin",version,restarted:false,publishedToApp:false}})});
export const reviewCourseOperatorClaim=onCall({enforceAppCheck:true},async r=>{const role=await staff(auth(r)),commandId=cmd(r),id=String(r.data?.claimId||""),to=String(r.data?.status||""),expected=validateVersion(r.data?.expectedVersion),ref=db.collection("partner_course_claims").doc(id);return db.runTransaction(async tx=>{const claim=await tx.get(ref);if(!claim.exists||!transitionClaim(String(claim.data()?.status),to,role))throw new HttpsError("failed-precondition","Transition denied.");const version=nextVersion(Number(claim.data()?.version||0),expected),rec=immutableReceipt(id,commandId,`claim_${to}`),courseId=String(claim.data()?.courseId),orgId=String(claim.data()?.organizationId),org=await tx.get(db.collection("partner_organizations").doc(orgId));if(!org.exists)throw new HttpsError("failed-precondition","Organization missing.");tx.update(ref,{status:to,version,updatedAt:now()});if(to==="approved")tx.set(db.collection("course_operators").doc(courseId),{courseId,organizationId:orgId,operatorUid:org.data()?.primaryOwnerUid,status:"active",claimId:id,publishToApp:false,version,updatedAt:now()},{merge:false});if(to==="suspended")tx.update(db.collection("course_operators").doc(courseId),{status:"suspended",version,updatedAt:now()});tx.create(db.collection("partner_authority_audits").doc(rec.receiptId),{...rec,actorRole:role,createdAt:now()});return{success:true,status:to,version,receipt:rec,publishedToApp:false}})});
export const managePartnerStaff=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),commandId=cmd(r),m=await member(caller),action=String(r.data?.action||"");if(!canManage(m.role))throw new HttpsError("permission-denied","Owner or manager required.");if(action==="invite"){const email=String(r.data?.email||"").trim().toLowerCase(),role=validateRole(r.data?.role);if(!/^\S+@\S+\.\S+$/.test(email))throw new HttpsError("invalid-argument","Email invalid.");const id=invitationId(m.organizationId,email),rec=await audit(id,commandId,"staff_invited",m.role);await db.collection("partner_staff_invitations").doc(id).set({invitationId:id,organizationId:m.organizationId,emailHash:identityHash(email),role,status:"pending",commandId,version:1,notificationStatus:notificationProvider.value()?"queued":"PROVIDER_UNCONFIGURED",createdAt:now()},{merge:false});return{success:true,invitationId:id,receipt:rec,notificationStatus:notificationProvider.value()?"queued":"PROVIDER_UNCONFIGURED"}}if(action==="revoke"){const target=String(r.data?.targetUid||""),ref=db.collection("partner_memberships").doc(`${m.organizationId}_${target}`),snap=await ref.get();if(!snap.exists||snap.data()?.role==="primary_owner")throw new HttpsError("failed-precondition","Cannot revoke membership.");const version=nextVersion(Number(snap.data()?.version||0),validateVersion(r.data?.expectedVersion));await ref.update({status:"revoked",version,updatedAt:now()});return{success:true,version,receipt:await audit(ref.id,commandId,"staff_revoked",m.role)}}throw new HttpsError("invalid-argument","Unsupported action.")});
export const acceptPartnerInvitation=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),commandId=cmd(r),email=r.auth?.token?.email_verified===true?String(r.auth.token.email||"").toLowerCase():"",id=String(r.data?.invitationId||""),ref=db.collection("partner_staff_invitations").doc(id);if(!email)throw new HttpsError("failed-precondition","Verified email required.");return db.runTransaction(async tx=>{const invite=await tx.get(ref);if(!invite.exists||invite.data()?.status!=="pending"||invite.data()?.emailHash!==identityHash(email))throw new HttpsError("permission-denied","Invitation invalid.");const orgId=String(invite.data()?.organizationId),binding=db.collection("partner_identity_bindings").doc(caller),existing=await tx.get(binding);if(existing.exists&&existing.data()?.organizationId!==orgId)throw new HttpsError("already-exists","Cross-organization identity conflict.");const rec=immutableReceipt(id,commandId,"invitation_accepted");tx.set(binding,{organizationId:orgId,verifiedAuthUid:caller,createdAt:now()},{merge:false});tx.create(db.collection("partner_memberships").doc(`${orgId}_${caller}`),{organizationId:orgId,uid:caller,role:invite.data()?.role,status:"active",version:1,createdAt:now()});tx.update(ref,{status:"accepted",acceptedByUid:caller,updatedAt:now()});tx.create(db.collection("partner_authority_audits").doc(rec.receiptId),{...rec,actorRole:invite.data()?.role,createdAt:now()});return{success:true,organizationId:orgId,receipt:rec}})});
export const transferPartnerOwnership=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),commandId=cmd(r),m=await member(caller),target=String(r.data?.targetUid||"");if(m.role!=="primary_owner"||String(r.data?.confirmation||"")!==`TRANSFER ${m.organizationId}`)throw new HttpsError("permission-denied","Confirmed primary owner required.");const orgRef=db.collection("partner_organizations").doc(m.organizationId),targetRef=db.collection("partner_memberships").doc(`${m.organizationId}_${target}`),selfRef=db.collection("partner_memberships").doc(`${m.organizationId}_${caller}`);return db.runTransaction(async tx=>{const[o,t]=await Promise.all([tx.get(orgRef),tx.get(targetRef)]);if(!t.exists||t.data()?.status!=="active")throw new HttpsError("failed-precondition","Target must be active.");const version=nextVersion(Number(o.data()?.version||0),validateVersion(r.data?.expectedVersion)),rec=immutableReceipt(m.organizationId,commandId,"ownership_transferred");tx.update(orgRef,{primaryOwnerUid:target,version,updatedAt:now()});tx.update(targetRef,{role:"primary_owner",version:admin.firestore.FieldValue.increment(1)});tx.update(selfRef,{role:"manager",version:admin.firestore.FieldValue.increment(1)});tx.create(db.collection("partner_authority_audits").doc(rec.receiptId),{...rec,actorRole:"primary_owner",createdAt:now()});return{success:true,version,receipt:rec}})});
export const raisePartnerClaimDispute=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),commandId=cmd(r),m=await member(caller),id=String(r.data?.claimId||""),reason=String(r.data?.reason||"").trim().slice(0,1000),claim=await db.collection("partner_course_claims").doc(id).get();if(!canManage(m.role)||!reason||!claim.exists||claim.data()?.organizationId!==m.organizationId)throw new HttpsError("permission-denied","Dispute denied.");const disputeId=`dispute_${id}`;await db.collection("partner_claim_disputes").doc(disputeId).set({disputeId,claimId:id,organizationId:m.organizationId,reason,status:"open",createdAt:now()},{merge:false});return{success:true,disputeId,receipt:await audit(id,commandId,"dispute_opened",m.role)}});
export const setPartnerOrganizationStatus=onCall({enforceAppCheck:true},async r=>{const role=await staff(auth(r)),commandId=cmd(r),orgId=String(r.data?.organizationId||""),status=String(r.data?.status||""),ref=db.collection("partner_organizations").doc(orgId),snap=await ref.get();if(!snap.exists||!["suspended","active"].includes(status))throw new HttpsError("invalid-argument","Status invalid.");const version=nextVersion(Number(snap.data()?.version||0),validateVersion(r.data?.expectedVersion));await ref.update({status,version,updatedAt:now()});await db.collection("b2b_partners").doc(String(snap.data()?.primaryOwnerUid)).update({status:status==="active"?"active_partner":"suspended",updatedAt:now()});return{success:true,status,version,receipt:await audit(orgId,commandId,`organization_${status}`,role)}});
export const getPartnerAuthorityState=onCall({enforceAppCheck:true},async r=>{const caller=auth(r),m=await member(caller),[org,claims,members,materials]=await Promise.all([db.collection("partner_organizations").doc(m.organizationId).get(),db.collection("partner_course_claims").where("organizationId","==",m.organizationId).limit(100).get(),db.collection("partner_memberships").where("organizationId","==",m.organizationId).limit(100).get(),db.collection("marketing_assets").where("state","==","approved").limit(50).get()]);return{schema:ACTIVATION_SCHEMA,organization:org.data(),membership:m,claims:docs(claims),members:docs(members),materials:docs(materials).filter((x:any)=>["course_letter","partner_letter","oem_asset"].includes(x.category)),notificationProviderConfigured:Boolean(notificationProvider.value()),storageConfigured:false}});
export const listPartnerAuthorityAdmin=onCall({enforceAppCheck:true},async r=>{await staff(auth(r));const[organizations,claims,disputes]=await Promise.all([db.collection("partner_organizations").limit(100).get(),db.collection("partner_course_claims").limit(200).get(),db.collection("partner_claim_disputes").limit(100).get()]);return{schema:ACTIVATION_SCHEMA,organizations:docs(organizations),claims:docs(claims),disputes:docs(disputes),notificationProviderConfigured:Boolean(notificationProvider.value())}});

// Portal and Admin read the SAME stored receipt. Neither recalculates a presentation value:
// the statement was sealed once inside the activation transaction, and these callables return
// it verbatim alongside a digest verification so tampering surfaces instead of rendering.
async function storedTrialReceipt(orgId:string){
  const[trial,statement]=await Promise.all([
    db.collection("partner_trials").doc(orgId).get(),
    db.collection("partner_statements").doc(statementId(orgId)).get(),
  ]);
  if(!trial.exists||!statement.exists)return{schema:"golfriend.partner-trial-receipt.v1",state:"unavailable",reason:"no_activated_trial_for_organization",trial:null,statement:null,verification:null};
  const stored=statement.data() as any;const{createdAt,...sealed}=stored;
  const verification=verifyStoredStatement(sealed);
  const trialData=trial.data() as any;
  return{
    schema:"golfriend.partner-trial-receipt.v1",
    state:verification.valid?"ready":"unavailable",
    reason:verification.valid?null:verification.reason,
    trial:{organizationId:trialData.organizationId,tier:trialData.tier,startsAt:trialData.startsAt,endsAt:trialData.endsAt,days:trialData.days,cancelledAt:trialData.cancelledAt??null},
    statement:verification.valid?sealed:null,
    verification,
  };
}

/** Partner-side: an active member reads only its OWN organization's receipt. */
export const getPartnerTrialReceiptV1=onCall({enforceAppCheck:true},async r=>{
  const uid=auth(r),membership=await member(uid);
  const requested=String(r.data?.organizationId||"");
  const orgId=String(membership.organizationId||"");
  if(requested&&requested!==orgId)throw new HttpsError("permission-denied","Cross-organization access denied.");
  return storedTrialReceipt(orgId);
});

/** Admin-side: active staff read any organization's receipt — the same stored document. */
export const getAdminPartnerTrialReceiptV1=onCall({enforceAppCheck:true},async r=>{
  await staff(auth(r));
  const orgId=String(r.data?.organizationId||"");
  if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(orgId))throw new HttpsError("invalid-argument","Organization id invalid.");
  return storedTrialReceipt(orgId);
});
