import test from"node:test";import assert from"node:assert/strict";import{createStripeSubscriptionProvider}from"./smallBusinessStripeAdapter.js";
const request={organizationId:"org_001",intentId:"intent_001",idempotencyKey:"sb_checkout:org_001:intent_001:command_001",policyVersion:"2026-08-18.v1",pricingDigest:"a".repeat(64),amountMinor:2900,currency:"USD",period:"monthly"as const,trialEndsAt:"2099-01-01T00:00:00.000Z",successUrl:"https://example.com/success",cancelUrl:"https://example.com/cancel"};
test("missing Stripe configuration fails closed before a provider call",async()=>{const p=createStripeSubscriptionProvider({});assert.equal(p.configured,false);await assert.rejects(p.createCheckout(request),/UNCONFIGURED/)});
test("checkout uses one server price and forwards the exact idempotency key",async()=>{let args:any,options:any;const stripe:any={prices:{retrieve:async(id:string)=>{assert.equal(id,"price_authoritative");return{active:true,type:"recurring",unit_amount:2900,currency:"usd",recurring:{interval:"month",interval_count:1}}}},checkout:{sessions:{create:async(a:any,o:any)=>{args=a;options=o;return{id:"cs_001",url:"https://checkout.stripe.test/session",subscription:null,expires_at:null}}}},webhooks:{constructEvent(){throw Error("unused")}}},p=createStripeSubscriptionProvider({secretKey:"configured_secret",webhookSecret:"configured_webhook_secret",priceId:"price_authoritative",stripe});const out=await p.createCheckout(request);assert.equal(out.sessionId,"cs_001");assert.equal(options.idempotencyKey,request.idempotencyKey);assert.equal(args.line_items[0].price,"price_authoritative");assert.equal(args.subscription_data.metadata.organizationId,request.organizationId);assert.equal(args.subscription_data.trial_end,Math.floor(Date.parse(request.trialEndsAt)/1000));assert.equal(JSON.stringify(args).includes("2900"),false)});
test("provider price mismatch rejects checkout before session creation",async()=>{let called=false;const stripe:any={prices:{retrieve:async()=>({active:true,type:"recurring",unit_amount:19900,currency:"usd",recurring:{interval:"month",interval_count:1}})},checkout:{sessions:{create:async()=>{called=true}}},webhooks:{constructEvent(){}}},p=createStripeSubscriptionProvider({secretKey:"configured_secret",webhookSecret:"configured_webhook_secret",priceId:"price_authoritative",stripe});await assert.rejects(p.createCheckout(request),/PRICE_MISMATCH/);assert.equal(called,false)});
test("signed webhook construction enforces tolerance and maps every required lifecycle event",()=>{let selected:any,tolerance=0,secret="";const stripe:any={prices:{},checkout:{sessions:{}},webhooks:{constructEvent(_body:Buffer,signature:string,s:string,t:number){assert.equal(signature,"signed");secret=s;tolerance=t;return selected}}},p=createStripeSubscriptionProvider({secretKey:"configured_secret",webhookSecret:"configured_webhook_secret",priceId:"price_authoritative",stripe}),metadata={organizationId:"org_001",intentId:"intent_001"},subscription={object:"subscription",id:"sub_001",customer:"cus_001",currency:"usd",metadata,items:{data:[{current_period_start:4000000000,current_period_end:4002678400}]}};const fixtures=[
 ["customer.subscription.created",subscription,"subscription_created"],
 ["invoice.paid",{object:"invoice",id:"in_first",customer:"cus_001",subscription:"sub_001",currency:"usd",amount_paid:2900,billing_reason:"subscription_create",parent:{subscription_details:{metadata}},lines:{data:[{period:{start:4000000000,end:4002678400}}]}},"invoice_paid"],
 ["invoice.paid",{object:"invoice",id:"in_renew",customer:"cus_001",subscription:"sub_001",currency:"usd",amount_paid:2900,billing_reason:"subscription_cycle",parent:{subscription_details:{metadata}},lines:{data:[{period:{start:4002678400,end:4005356800}}]}},"subscription_renewed"],
 ["invoice.payment_failed",{object:"invoice",id:"in_fail",customer:"cus_001",subscription:"sub_001",currency:"usd",amount_due:2900,parent:{subscription_details:{metadata}},lines:{data:[{period:{start:4002678400,end:4005356800}}]}},"payment_failed"],
 ["customer.subscription.deleted",subscription,"subscription_cancelled"],
 ["charge.refunded",{object:"charge",id:"ch_001",customer:"cus_001",currency:"usd",amount_refunded:2900,metadata:{...metadata,subscriptionId:"sub_001"},refunds:{data:[{id:"re_001"}]}},"refund_issued"]
 ];for(const[type,object,kind]of fixtures){selected={id:`evt_${kind}`,type,created:4000000000,data:{object}};assert.equal(p.verifyWebhook(Buffer.from("{}"),"signed",300).kind,kind)}assert.equal(tolerance,300);assert.equal(secret,"configured_webhook_secret")});
test("missing signature and unsupported webhook types fail closed",()=>{const stripe:any={prices:{},checkout:{sessions:{}},webhooks:{constructEvent(){return{id:"evt_unknown",type:"customer.created",created:4000000000,data:{object:{object:"customer"}}}}}},p=createStripeSubscriptionProvider({secretKey:"configured_secret",webhookSecret:"configured_webhook_secret",priceId:"price_authoritative",stripe});assert.throws(()=>p.verifyWebhook(Buffer.from("{}"),"",300),/SIGNATURE_REQUIRED/);assert.throws(()=>p.verifyWebhook(Buffer.from("{}"),"signed",300),/UNSUPPORTED/)});
