import*as admin from"firebase-admin";
import{defineSecret,defineString}from"firebase-functions/params";
import{HttpsError,onCall,onRequest}from"firebase-functions/v2/https";
import{onSchedule}from"firebase-functions/v2/scheduler";
import{applyProviderEvent,authoritativeSmallBusinessPrice,digest,entitlementAt,failClosedSubscriptionProvider,postTrialStatement,SIGNATURE_TOLERANCE_SECONDS,verifyImmutableEventReplay,type ProviderEvent,type SubscriptionProvider}from"./smallBusinessSubscriptionDomain.js";
import{createStripeSubscriptionProvider}from"./smallBusinessStripeAdapter.js";
if(!admin.apps.length)admin.initializeApp();
const db=admin.firestore(),stripeSecret=defineSecret("SMALL_BUSINESS_STRIPE_SECRET_KEY"),stripeWebhookSecret=defineSecret("SMALL_BUSINESS_STRIPE_WEBHOOK_SECRET"),stripePriceId=defineString("SMALL_BUSINESS_STRIPE_PRICE_ID",{default:""}),checkoutSuccessUrl=defineString("SMALL_BUSINESS_CHECKOUT_SUCCESS_URL",{default:""}),checkoutCancelUrl=defineString("SMALL_BUSINESS_CHECKOUT_CANCEL_URL",{default:""}),providerMode=defineString("SMALL_BUSINESS_SUBSCRIPTION_PROVIDER",{default:"disabled"});
const stamp=()=>admin.firestore.FieldValue.serverTimestamp(),nowIso=()=>new Date().toISOString();
function provider():SubscriptionProvider{return providerMode.value()==="stripe"?createStripeSubscriptionProvider({secretKey:stripeSecret.value(),webhookSecret:stripeWebhookSecret.value(),priceId:stripePriceId.value()}):failClosedSubscriptionProvider()}
function safeUrl(value:string,label:string){let u:URL;try{u=new URL(value)}catch{throw new HttpsError("failed-precondition",`${label}_UNCONFIGURED`)}if(u.protocol!=="https:"||u.username||u.password)throw new HttpsError("failed-precondition",`${label}_INVALID`);return u.toString()}
async function authority(r:any){if(!r.auth?.uid)throw new HttpsError("unauthenticated","Sign in required.");const account=await admin.auth().getUser(r.auth.uid).catch(()=>null);if(!account||account.disabled)throw new HttpsError("permission-denied","Active account required.");const binding=await db.collection("partner_identity_bindings").doc(r.auth.uid).get(),organizationId=String(binding.data()?.organizationId||"");if(!binding.exists||binding.data()?.status!=="active"||!organizationId)throw new HttpsError("permission-denied","Approved partner required.");const membership=await db.collection("partner_memberships").doc(`${organizationId}_${r.auth.uid}`).get(),m=membership.data();if(!membership.exists||m?.status!=="active"||!["primary_owner","manager"].includes(String(m?.role)))throw new HttpsError("permission-denied","Owner or manager required.");const business=await db.collection("small_businesses").doc(organizationId).get();if(!business.exists||business.data()?.organizationId!==organizationId||!["approved","active"].includes(String(business.data()?.status)))throw new HttpsError("failed-precondition","Active Small Business required.");return{uid:r.auth.uid,organizationId,business:business.data() as any}}

export const createSmallBusinessSubscriptionCheckoutV1=onCall({enforceAppCheck:true,secrets:[stripeSecret,stripeWebhookSecret]},async r=>{
 const a=await authority(r),intentId=String(r.data?.intentId||""),commandId=String(r.data?.commandId||"");if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{2,159}$/.test(intentId)||!/^[-A-Za-z0-9_:.]{8,160}$/.test(commandId))throw new HttpsError("invalid-argument","Command invalid.");
 if(Object.keys(r.data||{}).some(k=>["amount","amountMinor","currency","price","priceId","tier","entitlement","paymentStatus","organizationId"].includes(k)))throw new HttpsError("invalid-argument","Server authority fields are not accepted.");
 const [intent,trial]=await Promise.all([db.collection("small_business_subscription_intents").doc(intentId).get(),db.collection("partner_trials").doc(a.organizationId).get()]);if(!intent.exists||intent.data()?.businessId!==a.organizationId||intent.data()?.state!=="prepared"||!trial.exists||trial.data()?.tier!=="small_business"||trial.data()?.cancelledAt)throw new HttpsError("failed-precondition","Checkout is unavailable.");
 const price=authoritativeSmallBusinessPrice(),p=provider();if(!p.configured)throw new HttpsError("unavailable","PROVIDER_UNAVAILABLE");const idempotencyKey=`sb_checkout:${a.organizationId}:${intentId}:${commandId}`,commandRef=db.collection("small_business_checkout_commands").doc(digest({organizationId:a.organizationId,intentId,commandId})),prior=await commandRef.get();if(prior.exists)return{...prior.data()?.result,replayed:true};
 let session;try{session=await p.createCheckout({organizationId:a.organizationId,intentId,idempotencyKey,policyVersion:price.policyVersion,pricingDigest:price.pricingDigest,amountMinor:price.amountMinor,currency:price.currency,period:price.period,trialEndsAt:String(trial.data()?.endsAt),successUrl:safeUrl(checkoutSuccessUrl.value(),"SUCCESS_URL"),cancelUrl:safeUrl(checkoutCancelUrl.value(),"CANCEL_URL")})}catch(e){const code=String((e as Error)?.message||"");throw new HttpsError(code.includes("PRICE")||code.includes("TRIAL_EXPIRED")?"failed-precondition":"unavailable",code.includes("PRICE")?"PROVIDER_PRICE_MISMATCH":code.includes("TRIAL_EXPIRED")?"TRIAL_EXPIRED":"PROVIDER_UNAVAILABLE")}
 const result={schema:"golfriend.small-business.checkout-session.v1",organizationId:a.organizationId,intentId,provider:"stripe",sessionId:session.sessionId,checkoutUrl:session.checkoutUrl,expiresAt:session.expiresAt,status:"checkout_pending",policyVersion:price.policyVersion,pricingDigest:price.pricingDigest};await db.runTransaction(async tx=>{const existing=await tx.get(commandRef);if(existing.exists)return;tx.create(commandRef,{organizationId:a.organizationId,intentId,commandId,idempotencyKey,result,immutable:true,createdAt:stamp()});tx.set(db.collection("small_business_provider_subscriptions").doc(a.organizationId),{schema:"golfriend.small-business.provider-subscription.v1",organizationId:a.organizationId,intentId,provider:"stripe",providerCustomerId:null,providerSubscriptionId:session.providerSubscriptionId,status:"checkout_pending",policyVersion:price.policyVersion,pricingDigest:price.pricingDigest,amountMinor:price.amountMinor,currency:price.currency,period:price.period,entitlementState:"not_granted",revenueState:"not_recognized",version:1,updatedAt:stamp()},{merge:true})});return{...result,replayed:false}
});

async function persistEvent(event:ProviderEvent){const receiptRef=db.collection("small_business_subscription_event_receipts").doc(event.providerEventId),subscriptionRef=db.collection("small_business_provider_subscriptions").doc(event.organizationId),trialRef=db.collection("partner_trials").doc(event.organizationId),intentRef=db.collection("small_business_subscription_intents").doc(event.intentId);return db.runTransaction(async tx=>{const[receipt,current,trial,intent]=await Promise.all([tx.get(receiptRef),tx.get(subscriptionRef),tx.get(trialRef),tx.get(intentRef)]),eventDigest=digest(event);if(receipt.exists)return verifyImmutableEventReplay(receipt.data()?.eventDigest,event);if(!trial.exists||!intent.exists||intent.data()?.businessId!==event.organizationId||current.data()?.intentId!==event.intentId)throw Error("WEBHOOK_AUTHORITY_MISMATCH");const next=applyProviderEvent(current.exists?current.data():null,event,trial.data());tx.create(receiptRef,{schema:"golfriend.small-business.subscription-event-receipt.v1",provider:"stripe",providerEventId:event.providerEventId,eventKind:event.kind,eventDigest,organizationId:event.organizationId,intentId:event.intentId,occurredAt:event.occurredAt,immutable:true,receivedAt:stamp()});tx.set(subscriptionRef,{...next,updatedAt:stamp()},{merge:false});const entitlement=entitlementAt(next,trial.data(),event.occurredAt);tx.set(db.collection("small_business_entitlements").doc(event.organizationId),{schema:"golfriend.small-business.entitlement.v1",organizationId:event.organizationId,...entitlement,paidThrough:next.paidThrough??null,sourceProviderEventId:event.providerEventId,updatedAt:stamp()},{merge:false});if(event.kind==="invoice_paid"||event.kind==="subscription_renewed"){const statement=postTrialStatement(event,next,trial.data());tx.create(db.collection("small_business_post_trial_statements").doc(statement.statementId),{...statement,createdAt:stamp()})}return{accepted:true,replayed:false}})}

export const smallBusinessStripeWebhookV1=onRequest({secrets:[stripeSecret,stripeWebhookSecret]},async(req,res)=>{if(req.method!=="POST"){res.status(405).send("method_not_allowed");return}try{const raw=Buffer.isBuffer(req.rawBody)?req.rawBody:Buffer.from(req.rawBody||""),signature=String(req.get("stripe-signature")||""),event=provider().verifyWebhook(raw,signature,SIGNATURE_TOLERANCE_SECONDS),result=await persistEvent(event);res.status(200).json(result)}catch(e){const code=String((e as Error)?.message||"");res.status(code.includes("REPLAY_CONFLICT")?409:code.includes("UNSUPPORTED")?202:400).json({accepted:false,reason:"WEBHOOK_REJECTED"})}});

export const reconcileExpiredSmallBusinessTrialsV1=onSchedule("every 24 hours",async()=>{const now=nowIso(),snap=await db.collection("partner_trials").where("tier","==","small_business").where("endsAt","<=",now).limit(500).get();for(const trial of snap.docs){await db.runTransaction(async tx=>{const[sub,entitlement]=await Promise.all([tx.get(db.collection("small_business_provider_subscriptions").doc(trial.id)),tx.get(db.collection("small_business_entitlements").doc(trial.id))]),projection=entitlementAt(sub.exists?sub.data():null,trial.data(),now);if(entitlement.exists&&entitlement.data()?.state===projection.state&&entitlement.data()?.active===projection.active)return;tx.set(db.collection("small_business_entitlements").doc(trial.id),{schema:"golfriend.small-business.entitlement.v1",organizationId:trial.id,...projection,paidThrough:sub.data()?.paidThrough??null,sourceProviderEventId:sub.data()?.lastProviderEventId??null,updatedAt:stamp()},{merge:false})})}});

export const getSmallBusinessSubscriptionStateV1=onCall({enforceAppCheck:true},async r=>{const a=await authority(r),[trial,subscription,entitlement,statements]=await Promise.all([db.collection("partner_trials").doc(a.organizationId).get(),db.collection("small_business_provider_subscriptions").doc(a.organizationId).get(),db.collection("small_business_entitlements").doc(a.organizationId).get(),db.collection("small_business_post_trial_statements").where("organizationId","==",a.organizationId).limit(24).get()]);if(!trial.exists)throw new HttpsError("failed-precondition","Trial unavailable.");const status=trial.data()?.cancelledAt?"cancelled":subscription.exists?subscription.data()?.status:(Date.parse(String(trial.data()?.endsAt))>Date.now()?"trial_active":"provider_unavailable");return{schema:"golfriend.small-business.subscription-state.v1",organizationId:a.organizationId,status,trial:{startsAt:trial.data()?.startsAt,endsAt:trial.data()?.endsAt,cancelledAt:trial.data()?.cancelledAt??null},subscription:subscription.exists?{status:subscription.data()?.status,paidThrough:subscription.data()?.paidThrough??null,policyVersion:subscription.data()?.policyVersion}:null,entitlement:entitlement.exists?{active:entitlement.data()?.active,state:entitlement.data()?.state}:entitlementAt(null,trial.data(),nowIso()),statements:statements.docs.map(d=>{const x=d.data();return{statementId:x.statementId,periodStart:x.periodStart,periodEnd:x.periodEnd,currency:x.currency,paidMinor:x.paidMinor,status:x.status,taxInvoiceAuthorized:false,taxStatus:x.taxStatus,statementDigest:x.statementDigest}})}});
