import {createHash} from "node:crypto";

export const SMALL_BUSINESS_SCHEMA="golfriend.small-business.v1" as const;
export const SMALL_BUSINESS_COMMAND_SCHEMA="golfriend.small-business.command.v1" as const;
export const SMALL_BUSINESS_RECEIPT_SCHEMA="golfriend.small-business.approval-receipt.v1" as const;
export const SMALL_BUSINESS_SUBSCRIPTION_SCHEMA="golfriend.small-business.subscription-intent.v1" as const;
export const SMALL_BUSINESS_PROMOTION_SCHEMA="golfriend.small-business.promotion.v1" as const;
export const SMALL_BUSINESS_REPORT_SCHEMA="golfriend.small-business.report-event.v1" as const;
export const SMALL_BUSINESS_JHCC_SCHEMA="golfriend.small-business.jhcc-report.v1" as const;
export const SMALL_BUSINESS_CORRECTION_SCHEMA="golfriend.small-business.profile-correction.v1" as const;
export const ECONOMY_SCHEMA="golfriend.economy.configuration.v1" as const;
export const ECONOMY_POINTER_SCHEMA="golfriend.economy.configuration-pointer.v1" as const;
export const LOCALES=["en","th","ko","ja","zh","es","fr","de"] as const;
export const CATEGORIES=["golf_cafe","restaurant","coach","fitter","repair_shop","retailer","other"] as const;
export const STATUSES=["draft","submitted","changes_requested","approved","active","suspended","expired","rejected","closed"] as const;
export type SmallBusinessStatus=typeof STATUSES[number];
const forbidden=new Set(["role","approval","approvedBy","verified","verificationState","representativeUid","adminUid","price","amount","currency","entitlement","revenue","memberId","memberEmail","memberPhone","targetMemberIds","rawLocation","latitude","longitude"]);
export const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
/** The one derivation of a representative actor reference. Activation and the Small Business
 * runtime must agree on it exactly, or an activated partner would authenticate as a different
 * actor than the one recorded on its own business record. */
export const representativeActorRef=(uid:string)=>`actor_${digest(uid).slice(0,32)}`;
export function strictId(v:unknown,label="ID"){const x=String(v||"");if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw new Error(`${label}_INVALID`);return x}
export function strictVersion(v:unknown,label="VERSION"){if(!Number.isSafeInteger(v)||Number(v)<0)throw new Error(`${label}_INVALID`);return Number(v)}
const txt=(v:unknown,label:string,max=500)=>{const x=String(v||"").trim();if(!x||x.length>max||/[\u0000-\u001f]/.test(x))throw new Error(`${label}_INVALID`);return x};
const iso=(v:unknown,label:string)=>{const x=String(v||""),n=Date.parse(x);if(!Number.isFinite(n))throw new Error(`${label}_INVALID`);return new Date(n).toISOString()};
const exact=(raw:any,allowed:string[],rejectAuthority=true)=>{for(const k of Object.keys(raw||{}))if(!allowed.includes(k)||rejectAuthority&&forbidden.has(k))throw new Error("CALLER_AUTHORITY_FIELD")};
export function normalizeProfile(raw:any){
 exact(raw,["legalName","publicName","registrationReference","category","serviceDescription","serviceArea","supportedLocales","locations","evidenceReferences"]);
 const category=String(raw?.category);if(!CATEGORIES.includes(category as any))throw new Error("CATEGORY_INVALID");
 const locales=[...new Set((raw?.supportedLocales||[]).map(String))];if(!locales.length||locales.some(x=>!LOCALES.includes(x as any)))throw new Error("LOCALES_INVALID");
 if(!Array.isArray(raw?.locations)||raw.locations.length<1||raw.locations.length>50)throw new Error("LOCATIONS_INVALID");
 const locationIds=new Set<string>();const locations=raw.locations.map((x:any)=>{exact(x,["locationId","name","address","city","countryCode","serviceArea","operatingHours"]);const locationId=strictId(x.locationId,"LOCATION");if(locationIds.has(locationId))throw new Error("LOCATION_DUPLICATE");locationIds.add(locationId);if(!Array.isArray(x.operatingHours)||x.operatingHours.length>14)throw new Error("HOURS_INVALID");return{locationId,name:txt(x.name,"LOCATION_NAME",160),address:txt(x.address,"ADDRESS",500),city:txt(x.city,"CITY",100),countryCode:String(x.countryCode||"").toUpperCase().match(/^[A-Z]{2}$/)?.[0]||(()=>{throw new Error("COUNTRY_INVALID")})(),serviceArea:txt(x.serviceArea,"SERVICE_AREA",300),operatingHours:x.operatingHours.map((h:any)=>{exact(h,["day","opens","closes","closed"]);if(!Number.isInteger(h.day)||h.day<0||h.day>6)throw new Error("DAY_INVALID");if(h.closed===true)return{day:h.day,closed:true};if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(h.opens)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(h.closes)||h.opens>=h.closes)throw new Error("HOURS_INVALID");return{day:h.day,opens:h.opens,closes:h.closes,closed:false}})} });
 if(!Array.isArray(raw.evidenceReferences)||raw.evidenceReferences.length>30)throw new Error("EVIDENCE_INVALID");const evidenceReferences=raw.evidenceReferences.map((x:any)=>{exact(x,["evidenceId","kind","objectReference","contentDigest"]);if(!/^[a-f0-9]{64}$/.test(String(x.contentDigest||""))||!/^evidence\/[A-Za-z0-9_.:\/-]{3,300}$/.test(String(x.objectReference||"")))throw new Error("EVIDENCE_INVALID");return{evidenceId:strictId(x.evidenceId,"EVIDENCE"),kind:txt(x.kind,"EVIDENCE_KIND",80),objectReference:String(x.objectReference),contentDigest:String(x.contentDigest)}});
 return{legalName:txt(raw.legalName,"LEGAL_NAME",200),publicName:txt(raw.publicName,"PUBLIC_NAME",160),registrationReference:txt(raw.registrationReference,"REGISTRATION",120),category,serviceDescription:txt(raw.serviceDescription,"SERVICE_DESCRIPTION",2000),serviceArea:txt(raw.serviceArea,"SERVICE_AREA",500),supportedLocales:locales.sort(),locations,evidenceReferences};
}
export const profileDigest=(raw:any)=>digest(normalizeProfile(raw));
export function canonicalizeLocationIdentity(current:any[],proposed:any[],businessId:unknown,commandId:unknown){const business=strictId(businessId,"BUSINESS"),command=strictId(commandId,"COMMAND"),existing=new Map((current||[]).map((x:any)=>[strictId(x.locationId,"LOCATION"),x]));const seen=new Set<string>();return proposed.map((x:any,index:number)=>{const supplied=String(x.locationId||"");let locationId;if(existing.has(supplied))locationId=supplied;else if(/^new_[0-9]{1,3}$/.test(supplied))locationId=`sbl_${digest([business,command,index]).slice(0,32)}`;else throw new Error("CROSS_BUSINESS_OR_FORGED_LOCATION");if(seen.has(locationId))throw new Error("LOCATION_DUPLICATE");seen.add(locationId);return{...x,locationId}})}
export function correctionTransition(status:string,action:string){const map:Record<string,Record<string,string>>={draft:{submit:"submitted",withdraw:"withdrawn"},changes_requested:{submit:"submitted",withdraw:"withdrawn"},submitted:{approve:"approved",request_changes:"changes_requested",reject:"rejected",withdraw:"withdrawn"}};const next=map[status]?.[action];if(!next)throw new Error("CORRECTION_STATE_INVALID");return next}
export function transition(status:SmallBusinessStatus,action:string){const map:Record<string,Partial<Record<string,SmallBusinessStatus>>>={submit:{draft:"submitted",changes_requested:"submitted"},correct:{changes_requested:"draft"},withdraw:{draft:"closed",submitted:"closed",changes_requested:"closed"},request_changes:{submitted:"changes_requested"},approve:{submitted:"approved"},reject:{submitted:"rejected"},activate:{approved:"active",suspended:"active"},suspend:{active:"suspended"},expire:{approved:"expired",active:"expired",suspended:"expired"},close:{draft:"closed",submitted:"closed",changes_requested:"closed",approved:"closed",active:"closed",suspended:"closed",expired:"closed",rejected:"closed"}};const next=map[action]?.[status];if(!next)throw new Error("STATE_TRANSITION_INVALID");return next}
export function commandKey(actorRef:string,commandId:string,action:string){return`sb_${digest([strictId(actorRef),strictId(commandId),action]).slice(0,40)}`}
export function replay(current:any,payloadDigest:string){if(!current)return"new" as const;if(current.payloadDigest!==payloadDigest)throw new Error("REPLAY_PAYLOAD_CHANGED");return"exact" as const}
export function requireSeparation(app:any,actorRef:string){if(app.representativeRef===actorRef||app.createdByRef===actorRef)throw new Error("SEPARATION_OF_DUTIES")}
export function validateEconomyPointer(raw:any){if(raw?.schema!==ECONOMY_POINTER_SCHEMA||raw.status!=="active"||!Number.isSafeInteger(raw.version)||raw.version<1||!/^([a-f0-9]{64})$/.test(String(raw.configurationDigest||"")))throw new Error("ECONOMY_POINTER_INVALID");return{configurationId:strictId(raw.configurationId,"CONFIGURATION"),version:raw.version,configurationDigest:String(raw.configurationDigest),approvalReceiptId:strictId(raw.approvalReceiptId,"APPROVAL_RECEIPT")}}
export const economyDigest=(raw:any)=>digest({schema:raw.schema,configurationId:raw.configurationId,policyVersion:raw.policyVersion,version:raw.version,status:raw.status,bookingCommissionBps:raw.bookingCommissionBps,authorizedMaximumBps:raw.authorizedMaximumBps,effectiveAt:raw.effectiveAt?.toMillis?.()??raw.effectiveAt,expiresAt:raw.expiresAt??null,approvalReceiptId:raw.approvalReceiptId,smallBusinessPlans:raw.smallBusinessPlans,teeActionCosts:raw.teeActionCosts,teeRewards:raw.teeRewards,businessRates:raw.businessRates});
export function resolvePlan(raw:any,pointer:any,planId:unknown,jurisdiction:unknown,atMs=Date.now()){
 const p=validateEconomyPointer(pointer);if(raw?.schema!==ECONOMY_SCHEMA||raw.status!=="active"||raw.configurationId!==p.configurationId||raw.version!==p.version||raw.approvalReceiptId!==p.approvalReceiptId||economyDigest(raw)!==p.configurationDigest)throw new Error("ECONOMY_CONFIG_INVALID");
 const configStart=Date.parse(iso(raw.effectiveAt,"CONFIG_EFFECTIVE")),configEnd=raw.expiresAt?Date.parse(iso(raw.expiresAt,"CONFIG_EXPIRY")):Infinity;if(configStart>atMs||configEnd<=atMs)throw new Error("ECONOMY_CONFIG_INACTIVE");if(!Array.isArray(raw.smallBusinessPlans))throw new Error("PLANS_MISSING");const found=raw.smallBusinessPlans.filter((x:any)=>x.planId===planId);if(found.length!==1)throw new Error("PLAN_UNAVAILABLE");const x=found[0];exact(x,["planId","version","status","effectiveAt","expiresAt","jurisdictions","features","providerAuthorityRef","priceRuleRef"],false);const start=Date.parse(iso(x.effectiveAt,"PLAN_EFFECTIVE")),end=x.expiresAt?Date.parse(iso(x.expiresAt,"PLAN_EXPIRY")):Infinity;if(x.status!=="active"||!Number.isSafeInteger(x.version)||x.version<1||start>atMs||end<=atMs||!Array.isArray(x.jurisdictions)||!x.jurisdictions.includes(jurisdiction)||!x.providerAuthorityRef||!x.priceRuleRef||!Array.isArray(x.features))throw new Error("PLAN_UNAVAILABLE");return{planId:strictId(x.planId,"PLAN"),version:x.version,configurationId:raw.configurationId,configurationVersion:raw.version,effectiveAt:new Date(start).toISOString(),expiresAt:end===Infinity?null:new Date(end).toISOString(),jurisdiction:String(jurisdiction),features:x.features.map((v:any)=>txt(v,"FEATURE",100)),providerAuthorityRef:strictId(x.providerAuthorityRef,"PROVIDER_AUTHORITY"),priceRuleRef:strictId(x.priceRuleRef,"PRICE_RULE"),planDigest:digest(x)};
}
export function subscriptionIntent(input:any,plan:any,business:any){if(business.status!=="approved"&&business.status!=="active")throw new Error("BUSINESS_NOT_ELIGIBLE");if(business.countryCode!==plan.jurisdiction)throw new Error("JURISDICTION_MISMATCH");return{schema:SMALL_BUSINESS_SUBSCRIPTION_SCHEMA,intentId:strictId(input.intentId,"INTENT"),businessId:strictId(business.businessId,"BUSINESS"),planId:plan.planId,planVersion:plan.version,planEffectiveFrom:plan.effectiveAt,planFeatures:[...plan.features],economyConfigurationId:plan.configurationId,economyConfigurationVersion:plan.configurationVersion,planDigest:plan.planDigest,providerAuthorityRef:plan.providerAuthorityRef,state:"prepared",accountingState:"no_provider_evidence",entitlementState:"not_granted",revenueState:"not_recognized"}}
export function normalizePromotion(raw:any){exact(raw,["promotionId","businessId","locationIds","audience","locales","jurisdictions","effectiveAt","expiresAt","contentDigest","frequencyLimit","sponsoredDisclosure","contentReference"]);const effectiveAt=iso(raw.effectiveAt,"EFFECTIVE"),expiresAt=iso(raw.expiresAt,"EXPIRY");if(Date.parse(expiresAt)<=Date.parse(effectiveAt)||!Array.isArray(raw.locales)||raw.locales.some((x:any)=>!LOCALES.includes(x))||!raw.locales.length||!Array.isArray(raw.jurisdictions)||!raw.jurisdictions.length||!Array.isArray(raw.locationIds)||!raw.locationIds.length||!/^([a-f0-9]{64})$/.test(raw.contentDigest)||raw.sponsoredDisclosure!==true||!Number.isSafeInteger(raw.frequencyLimit)||raw.frequencyLimit<1||raw.frequencyLimit>20)throw new Error("PROMOTION_INVALID");return{promotionId:strictId(raw.promotionId,"PROMOTION"),businessId:strictId(raw.businessId,"BUSINESS"),locationIds:raw.locationIds.map((x:any)=>strictId(x,"LOCATION")),audience:txt(raw.audience,"AUDIENCE",120),locales:[...new Set(raw.locales)].sort(),jurisdictions:[...new Set(raw.jurisdictions)].sort(),effectiveAt,expiresAt,contentDigest:raw.contentDigest,frequencyLimit:raw.frequencyLimit,sponsoredDisclosure:true,contentReference:strictId(raw.contentReference,"CONTENT")}}
export function promotionTransition(status:string,decision:string){const transitions:Record<string,Record<string,string>>={draft:{approve:"approved",request_changes:"changes_requested",retire:"retired"},changes_requested:{approve:"approved",retire:"retired"},approved:{publish:"published",request_changes:"changes_requested",retire:"retired"},published:{retire:"retired"}};const next=transitions[status]?.[decision];if(!next)throw new Error("PROMOTION_STATE_INVALID");return next}
export function publicationAllowed(p:any,b:any,nowMs=Date.now()){const policy=p.policyApprovalReceipt,contract=p.contractApprovalReceipt;if(p.status!=="approved"||b.status!=="active"||Date.parse(p.effectiveAt)>nowMs||Date.parse(p.expiresAt)<=nowMs||p.sponsoredDisclosure!==true||policy?.schema!=="golfriend.small-business.promotion-policy-approval.v1"||contract?.schema!=="golfriend.small-business.contract-approval.v1"||policy.immutable!==true||contract.immutable!==true||policy.businessId!==p.businessId||contract.businessId!==p.businessId||policy.promotionId!==p.promotionId||contract.promotionId!==p.promotionId||policy.contentDigest!==p.contentDigest||contract.contentDigest!==p.contentDigest||policy.status!=="approved"||contract.status!=="approved")throw new Error("PROMOTION_NOT_PUBLISHABLE");return true}
export function discoveryCard(b:any){if(b.status!=="active")throw new Error("BUSINESS_NOT_ACTIVE");return{businessId:b.businessId,publicName:b.publicName,category:b.category,city:b.city,countryCode:b.countryCode,serviceDescription:b.serviceDescription,availability:b.availabilityAuthority?b.availability:"unknown",partner:true,sponsored:b.sponsored===true,disclosure:b.sponsored===true?"sponsored_partner":"partner",returnRoute:"/lounge"}}
export function reportEvent(raw:any){exact(raw,["eventId","businessId","countryCode","category","status","planId","metric","count","evidenceClass","sourceReceiptId","occurredAt"]);const metrics=["impression","engagement","subscription_intent","provider_confirmed_subscription","golfriend_revenue","external_commission","promotion_zero_revenue"],evidence=["operational_receipt","provider_subscription_evidence","provider_accounting_evidence","external_non_golfriend","promotion_no_value"];if(!metrics.includes(raw.metric)||!evidence.includes(raw.evidenceClass)||!Number.isSafeInteger(raw.count)||raw.count<0||!CATEGORIES.includes(raw.category)||!STATUSES.includes(raw.status)||!/^([A-Z]{2}|ZZ)$/.test(String(raw.countryCode||""))||raw.metric==="provider_confirmed_subscription"&&raw.evidenceClass!=="provider_subscription_evidence"||raw.metric==="golfriend_revenue"&&raw.evidenceClass!=="provider_accounting_evidence"||raw.metric==="external_commission"&&raw.evidenceClass!=="external_non_golfriend"||raw.metric==="promotion_zero_revenue"&&(raw.count!==0||raw.evidenceClass!=="promotion_no_value"))throw new Error("REPORT_EVENT_INVALID");return{schema:SMALL_BUSINESS_REPORT_SCHEMA,eventId:strictId(raw.eventId,"EVENT"),businessId:strictId(raw.businessId,"BUSINESS"),countryCode:String(raw.countryCode),category:String(raw.category),status:String(raw.status),planId:raw.planId?strictId(raw.planId,"PLAN"):null,metric:raw.metric,count:raw.count,evidenceClass:String(raw.evidenceClass),sourceReceiptId:strictId(raw.sourceReceiptId,"SOURCE_RECEIPT"),occurredAt:iso(raw.occurredAt,"OCCURRED")}}
export function prepareJhcc(events:any[],batchId:unknown){const normalized=requireUniqueReportEvidence(events),ids=new Set(normalized.map(x=>x.eventId));if(ids.size!==normalized.length||normalized.length>500)throw new Error("REPORT_REPLAY_OR_LIMIT");return{schema:SMALL_BUSINESS_JHCC_SCHEMA,batchId:strictId(batchId,"BATCH"),transmission:"disabled",privacy:"aggregated_minimum_necessary",eventCount:normalized.length,eventDigest:digest(normalized),events:normalized}}
export function requireUniqueReportEvidence(events:any[]){const normalized=events.map(reportEvent),sources=new Set(normalized.map(x=>x.sourceReceiptId));if(sources.size!==normalized.length)throw new Error("REPORT_SOURCE_REPLAY");return normalized}
