export const TEE_ANALYTICS_SCHEMA="golfriend.admin.tee-economy-analytics.v1";
export const F3_LEDGER_SCHEMA="golfriend.v2.ledger-entry.v1";
export const F3_AUDIT_SCHEMA="golfriend.v2.audit-event.v1";
export const TEE_ANALYTICS_MIN_COHORT=10;
export const TEE_ANALYTICS_MAX_DAYS=31;
export const TEE_ANALYTICS_STALE_MS=48*60*60*1000;
const TYPES=new Set(["CREDIT","DEBIT","RESERVE","SETTLE","RELEASE","REFUND","REVERSAL","ADJUSTMENT"]);
const DATE=/^\d{4}-\d{2}-\d{2}$/;
export function validateTeeRange(startDate:unknown,endDate:unknown){const start=String(startDate||""),end=String(endDate||"");if(!DATE.test(start)||!DATE.test(end))throw new Error("DATE_RANGE_INVALID");const startMs=Date.parse(`${start}T00:00:00Z`),endMs=Date.parse(`${end}T00:00:00Z`),days=Math.floor((endMs-startMs)/86400000)+1;if(!Number.isFinite(days)||days<1||days>TEE_ANALYTICS_MAX_DAYS)throw new Error("DATE_RANGE_INVALID");return{startDate:start,endDate:end,days,startMs,endExclusiveMs:endMs+86400000};}
function millis(value:any){if(typeof value==="number"&&Number.isFinite(value))return value;if(typeof value==="string")return Date.parse(value);const result=value?.toMillis?.();return Number.isFinite(result)?result:NaN;}
function amount(entry:any){if(entry.type==="REVERSAL"||entry.type==="ADJUSTMENT")return Number(entry.delta);return Number(entry.amount);}
function movement(entry:any){const value=amount(entry);switch(entry.type){case"CREDIT":case"REFUND":return{earned:value,burned:0};case"DEBIT":case"SETTLE":return{earned:0,burned:value};case"REVERSAL":case"ADJUSTMENT":return value>=0?{earned:value,burned:0}:{earned:0,burned:-value};default:return{earned:0,burned:0};}}
type Acc={key:string;day:string;action:string;destination:"UNKNOWN";country:"UNKNOWN";members:Set<string>;earned:number;burned:number;failed:number;reversed:number;events:number};
const freshAcc=(key:string,day:string,action:string):Acc=>({key,day,action,destination:"UNKNOWN",country:"UNKNOWN",members:new Set(),earned:0,burned:0,failed:0,reversed:0,events:0});
export function projectTeeEconomy(entries:any[],audits:any[],range:{startMs:number;endExclusiveMs:number},nowMs=Date.now()){const buckets=new Map<string,Acc>();const seenEntries=new Set<string>();const seenAudits=new Set<string>();let latest=0,omitted=0;
 const get=(day:string,action:string)=>{const key=`${day}|${action}|UNKNOWN|UNKNOWN`;let row=buckets.get(key);if(!row){row=freshAcc(key,day,action);buckets.set(key,row);}return row;};
 for(const entry of entries){const at=millis(entry?.at),uid=String(entry?.memberUid||""),type=String(entry?.type||"");const id=`${uid}:${entry?.seq}`;if(entry?.schema!==F3_LEDGER_SCHEMA||!uid||!Number.isInteger(entry?.seq)||!TYPES.has(type)||!Number.isFinite(at)||at<range.startMs||at>=range.endExclusiveMs||seenEntries.has(id)){omitted++;continue;}const value=amount(entry);if(!Number.isFinite(value)){omitted++;continue;}seenEntries.add(id);latest=Math.max(latest,at);const row=get(new Date(at).toISOString().slice(0,10),type);const delta=movement(entry);row.members.add(uid);row.earned+=delta.earned;row.burned+=delta.burned;row.reversed+=type==="REVERSAL"?1:0;row.events++;}
 for(const audit of audits){const at=millis(audit?.at),command=String(audit?.commandType||""),uid=String(audit?.refs?.memberRef||"");const type=command.startsWith("economy.")?command.slice(8):"";const id=String(audit?.id||`${audit?.idempotencyKey||""}:${audit?.correlationId||""}:${at}:${type}`);if(audit?.schema!==F3_AUDIT_SCHEMA||audit?.domain!=="economy"||audit?.outcome!=="rejected"||!uid||!TYPES.has(type)||!Number.isFinite(at)||at<range.startMs||at>=range.endExclusiveMs||seenAudits.has(id)){continue;}seenAudits.add(id);latest=Math.max(latest,at);const row=get(new Date(at).toISOString().slice(0,10),type);row.members.add(uid);row.failed++;}
 const rows=[...buckets.values()].sort((a,b)=>a.key.localeCompare(b.key)).map(row=>{const uniqueUsers=row.members.size,suppressed=uniqueUsers<TEE_ANALYTICS_MIN_COHORT;return{day:row.day,action:row.action,destination:row.destination,country:row.country,suppressed,uniqueUsers:suppressed?null:uniqueUsers,totalEarned:suppressed?null:row.earned,totalBurned:suppressed?null:row.burned,net:suppressed?null:row.earned-row.burned,averagePerUser:suppressed?null:(row.earned+row.burned)/uniqueUsers,burnEarnRatio:suppressed||row.earned===0?null:row.burned/row.earned,failedActions:suppressed?null:row.failed,reversedActions:suppressed?null:row.reversed,eventCount:suppressed?null:row.events};});
 const visible=rows.filter(row=>!row.suppressed);const totals={earned:visible.reduce((s,r)=>s+(r.totalEarned||0),0),burned:visible.reduce((s,r)=>s+(r.totalBurned||0),0),failed:visible.reduce((s,r)=>s+(r.failedActions||0),0),reversed:visible.reduce((s,r)=>s+(r.reversedActions||0),0)};const days=[...new Set(rows.map(r=>r.day))].sort();const trend=days.map((day,index)=>{const current=visible.filter(r=>r.day===day).reduce((s,r)=>s+(r.net||0),0),previous=index?visible.filter(r=>r.day===days[index-1]).reduce((s,r)=>s+(r.net||0),0):null;return{day,net:current,change:previous===null?null:current-previous};});
 return{schemaVersion:TEE_ANALYTICS_SCHEMA,source:{ledgerCollection:"tee_ledger",failureAuditCollection:"v2_audit",ledgerSchema:F3_LEDGER_SCHEMA,producerCommit:"15efe98",authority:"server",countrySemantics:"UNKNOWN because F3 v1 has no country",destinationSemantics:"UNKNOWN because F3 v1 has no destination"},privacy:{minimumCohort:TEE_ANALYTICS_MIN_COHORT,aggregateOnly:true},rows,totals:{...totals,net:totals.earned-totals.burned,burnEarnRatio:totals.earned===0?null:totals.burned/totals.earned},trend,freshestEventAt:latest?new Date(latest).toISOString():null,stale:!latest||nowMs-latest>TEE_ANALYTICS_STALE_MS,limitations:["COUNTRY_UNAVAILABLE_IN_F3_LEDGER_V1","DESTINATION_UNAVAILABLE_IN_F3_LEDGER_V1","FAILED_ACTIONS_FROM_F3_APPEND_ONLY_AUDIT"],omittedInvalidOrDuplicateEntries:omitted};}
