import {createHash} from "node:crypto";

export const TOURNAMENT_GOVERNANCE_SCHEMA="golfriend.tournament-governance.v1" as const;
export type TournamentState="draft"|"pending_review"|"changes_requested"|"approved"|"rejected"|"published"|"unpublished"|"cancelled";
export type TournamentAction="create"|"update"|"submit"|"request_changes"|"approve"|"reject"|"publish"|"unpublish"|"cancel";
const transitions:Record<TournamentAction,readonly TournamentState[]>={create:[],update:["draft","changes_requested"],submit:["draft","changes_requested"],request_changes:["pending_review"],approve:["pending_review"],reject:["pending_review"],publish:["approved","unpublished"],unpublish:["published"],cancel:["draft","pending_review","changes_requested","approved","published","unpublished"]};
const targets:Partial<Record<TournamentAction,TournamentState>>={submit:"pending_review",request_changes:"changes_requested",approve:"approved",reject:"rejected",publish:"published",unpublish:"unpublished",cancel:"cancelled"};
export const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function identifier(value:unknown,label:string){const x=String(value||"").trim();if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw Error(`${label}_INVALID`);return x}
export function revision(value:unknown){if(!Number.isSafeInteger(value)||Number(value)<0)throw Error("REVISION_INVALID");return Number(value)}
export function requireRevision(current:unknown,expected:unknown){const a=revision(current),b=revision(expected);if(a!==b)throw Error("STALE_REVISION");return a+1}
export function requireReplay(priorDigest:unknown,currentDigest:string){if(priorDigest!==undefined&&priorDigest!==currentDigest)throw Error("COMMAND_REPLAY_CONFLICT");return priorDigest===currentDigest}
export function nextState(current:TournamentState|undefined,action:TournamentAction){if(action==="create"){if(current)throw Error("STATE_INVALID");return"draft"}if(!current||!transitions[action].includes(current))throw Error("STATE_INVALID");return action==="update"?current:targets[action]!}
export function validatePartnerAction(action:TournamentAction){if(!["create","update","submit","cancel"].includes(action))throw Error("PARTNER_ACTION_DENIED")}
export function validatePartnerTransition(action:TournamentAction,current:TournamentState|undefined){validatePartnerAction(action);if(action==="cancel"&&!(["draft","pending_review","changes_requested"]as const).includes(current as any))throw Error("PARTNER_CANCEL_DENIED")}
export function validateAdminAction(action:TournamentAction){if(!["request_changes","approve","reject","publish","unpublish","cancel"].includes(action))throw Error("ADMIN_ACTION_DENIED")}
const OFFSET_INSTANT=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?(?:Z|[+-]\d{2}:\d{2})$/;
export function normalizeInstant(value:unknown,label:string){const raw=String(value||"");if(!OFFSET_INSTANT.test(raw)||!Number.isFinite(Date.parse(raw)))throw Error(`${label}_INVALID`);return new Date(raw).toISOString()}
export function requireTimeZone(value:unknown){const zone=String(value||"");try{new Intl.DateTimeFormat("en",{timeZone:zone}).format(0)}catch{throw Error("TIME_ZONE_INVALID")}if(!zone.includes("/"))throw Error("TIME_ZONE_INVALID");return zone}
export function validateTournamentFields(value:any){const name=String(value?.name||"").trim(),startsAt=normalizeInstant(value?.startsAt,"STARTS_AT"),endsAt=value?.endsAt?normalizeInstant(value.endsAt,"ENDS_AT"):null,timeZone=requireTimeZone(value?.timeZone),capacity=Number(value?.capacity);if(!name||name.length>160||!Number.isInteger(capacity)||capacity<1||capacity>10000||endsAt&&Date.parse(endsAt)<=Date.parse(startsAt))throw Error("TOURNAMENT_FIELDS_INVALID");return{name,description:String(value?.description||"").trim().slice(0,2000),startsAt,endsAt,timeZone,location:String(value?.location||"").trim().slice(0,300),capacity}}
export function partnerOrganizationAuthority(record:any,requestedOrganizationId:string|undefined,now=Date.now()){const rawExpiry=record?.accessExpiresAt??record?.trialEndsAt,expiry=rawExpiry?.toMillis instanceof Function?rawExpiry.toMillis():typeof rawExpiry==="string"?Date.parse(rawExpiry):Infinity,tier=String(record?.tier||record?.partnerTier||"");if(record?.status!=="active_partner"||record?.disabled===true||(rawExpiry!==undefined&&(!Number.isFinite(expiry)||expiry<=now)))throw Error("PARTNER_INACTIVE");if(!["small_business","enterprise","master_host","Product & Service Promotion"].includes(tier))throw Error("PARTNER_TIER_INVALID");const organizationId=identifier(record.organizationId,"ORGANIZATION");if(requestedOrganizationId&&requestedOrganizationId!==organizationId)throw Error("ORGANIZATION_SCOPE_DENIED");return{organizationId,tier:tier==="small_business"?"small_business":"enterprise"as const}}
export function publicProjection(record:any){if(record.state!=="published")throw Error("NOT_PUBLISHED");const fields=validateTournamentFields(record),courseId=identifier(record.courseId,"COURSE");return Object.freeze({schema:"golfriend.app-tournament-publication.v1",tournamentId:record.tournamentId,organizationId:record.organizationId,courseId,...fields,state:"published",revision:Number(record.revision),publicationRevision:Number(record.publicationRevision),publishedAt:record.publishedAt||null,cancelled:false,organizerMoneyBoundary:"external_organizer_only"})}
export function rejectPrivateProjection(value:any){const forbidden=["creatorUid","actorUid","adminUid","reviewNotes","rejectionReason","entryFee","prize","bank","payment","escrow","ledger","commission"];for(const key of forbidden)if(Object.prototype.hasOwnProperty.call(value,key))throw Error("PRIVATE_FIELD_EXPOSED");return value}
