import {createHash} from "node:crypto";

export const TOURNAMENT_GOVERNANCE_SCHEMA="golfriend.tournament-governance.v1" as const;
export type TournamentState="draft"|"pending_review"|"changes_requested"|"approved"|"rejected"|"published"|"unpublished"|"cancelled";
export type TournamentAction="create"|"update"|"submit"|"request_changes"|"approve"|"reject"|"publish"|"unpublish"|"cancel";
const transitions:Record<TournamentAction,readonly TournamentState[]>={create:[],update:["draft","changes_requested"],submit:["draft","changes_requested"],request_changes:["pending_review"],approve:["pending_review"],reject:["pending_review"],publish:["approved","unpublished"],unpublish:["published"],cancel:["draft","pending_review","changes_requested","approved","published","unpublished"]};
const targets:Partial<Record<TournamentAction,TournamentState>>={submit:"pending_review",request_changes:"changes_requested",approve:"approved",reject:"rejected",publish:"published",unpublish:"unpublished",cancel:"cancelled"};
export const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function identifier(value:unknown,label:string){const x=String(value||"").trim();if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,127}$/.test(x))throw Error(`${label}_INVALID`);return x}
export function revision(value:unknown){if(!Number.isSafeInteger(value)||Number(value)<0)throw Error("REVISION_INVALID");return Number(value)}
export function requireRevision(current:unknown,expected:unknown){const a=revision(current),b=revision(expected);if(a!==b)throw Error("STALE_REVISION");return a+1}
export function requireReplay(priorDigest:unknown,currentDigest:string){if(priorDigest!==undefined&&priorDigest!==currentDigest)throw Error("COMMAND_REPLAY_CONFLICT");return priorDigest===currentDigest}
export function nextState(current:TournamentState|undefined,action:TournamentAction){if(action==="create"){if(current)throw Error("STATE_INVALID");return"draft"}if(!current||!transitions[action].includes(current))throw Error("STATE_INVALID");return action==="update"?current:targets[action]!}
export function validatePartnerAction(action:TournamentAction){if(!["create","update","submit","cancel"].includes(action))throw Error("PARTNER_ACTION_DENIED")}
export function validateAdminAction(action:TournamentAction){if(!["request_changes","approve","reject","publish","unpublish","cancel"].includes(action))throw Error("ADMIN_ACTION_DENIED")}
export function partnerOrganizationAuthority(record:any,requestedOrganizationId:string|undefined,now=Date.now()){const rawExpiry=record?.accessExpiresAt??record?.trialEndsAt,expiry=rawExpiry?.toMillis instanceof Function?rawExpiry.toMillis():typeof rawExpiry==="string"?Date.parse(rawExpiry):Infinity,tier=String(record?.tier||record?.partnerTier||"");if(record?.status!=="active_partner"||record?.disabled===true||(rawExpiry!==undefined&&(!Number.isFinite(expiry)||expiry<=now)))throw Error("PARTNER_INACTIVE");if(!["small_business","enterprise","master_host","Product & Service Promotion"].includes(tier))throw Error("PARTNER_TIER_INVALID");const organizationId=identifier(record.organizationId,"ORGANIZATION");if(requestedOrganizationId&&requestedOrganizationId!==organizationId)throw Error("ORGANIZATION_SCOPE_DENIED");return{organizationId,tier:tier==="small_business"?"small_business":"enterprise"as const}}
export function publicProjection(record:any){if(record.state!=="published")throw Error("NOT_PUBLISHED");return Object.freeze({schema:"golfriend.app-tournament-publication.v1",tournamentId:record.tournamentId,organizationId:record.organizationId,courseId:record.courseId||null,name:record.name,description:record.description||"",startsAt:record.startsAt,endsAt:record.endsAt||null,location:record.location||"",capacity:Number(record.capacity||0),state:"published",revision:Number(record.revision),publicationRevision:Number(record.publicationRevision),publishedAt:record.publishedAt||null,cancelled:false,organizerMoneyBoundary:"external_organizer_only"})}
export function rejectPrivateProjection(value:any){const forbidden=["creatorUid","actorUid","adminUid","reviewNotes","rejectionReason","entryFee","prize","bank","payment","escrow","ledger","commission"];for(const key of forbidden)if(Object.prototype.hasOwnProperty.call(value,key))throw Error("PRIVATE_FIELD_EXPOSED");return value}
