import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{fileURLToPath}from'node:url';
import{assertExactCallableEnvelope}from'../functions/src/callableEnvelope.ts';import{availabilityReceiptId,nextSlotVersion,validateSlot}from'../functions/src/partnerAvailabilityDomain.ts';import{assertNonFinancial,bookingReceiptId,transition,version}from'../functions/src/partnerBookingDomain.ts';
const read=p=>readFileSync(fileURLToPath(new URL(`../${p}`,import.meta.url)),'utf8'),app=read('src/App.tsx'),index=read('functions/src/index.ts'),availability=read('functions/src/partnerAvailabilityRuntime.ts'),booking=read('functions/src/partnerBookingRuntime.ts'),course=read('src/components/B2B/CourseAvailabilityV2.tsx'),requests=read('src/components/B2B/PlayBookingLifecycleV2.tsx');
test('canonical consumers are mounted and legacy client-authority surfaces are not imported',()=>{assert.match(app,/import CourseAvailabilityV2/);assert.match(app,/import PlayBookingLifecycleV2/);assert.doesNotMatch(app,/import CourseAvailability from/);assert.doesNotMatch(app,/import BookingRequests from/)});
test('each callable is registered only through its canonical V2 runtime export',()=>{for(const name of['manageCourseAvailabilityV2','reviewCourseAvailabilityV2','getCourseAvailabilityV2','listCourseAvailabilityAdminV2'])assert.match(index,new RegExp(`${name}[^\n]*from "\\./partnerAvailabilityRuntime\\.js"`));for(const name of['requestPlayBookingV2','managePlayBookingV2','sendPlayBookingMessageV2','getPlayBookingsPortalV2','getPlayBookingsAdminV2'])assert.match(index,new RegExp(`${name}[^\n]*from "\\./partnerBookingRuntime\\.js"`));assert.match(course,/manageCourseAvailabilityV2/);assert.match(requests,/managePlayBookingV2/)});
test('Auth App Check and organization authority remain mandatory',()=>{for(const source of[availability,booking]){assert.match(source,/enforceAppCheck:\s*true/);assert.match(source,/auth\?\.uid/);assert.match(source,/partner_identity_bindings/);assert.match(source,/partner_memberships/);assert.match(source,/organizationId/)}});
test('malformed surplus stale and cross-scope inputs fail closed before effects',()=>{assert.throws(()=>validateSlot({courseId:'x',date:'bad',time:'99:00',timeZone:'bad',capacity:0}));assert.throws(()=>assertExactCallableEnvelope({commandId:'c',slotId:'s',memberId:'foreign'},['commandId','slotId']));assert.throws(()=>assertExactCallableEnvelope({commandId:'c',slotId:'s',organizationId:'foreign'},['commandId','slotId']));assert.throws(()=>nextSlotVersion(3,2));assert.throws(()=>version(4,3));assert.throws(()=>transition('cancelled','confirm'));assert.throws(()=>assertNonFinancial({payment:true}))});
test('replay identities are stable and changed command payloads separate receipts',()=>{assert.equal(availabilityReceiptId('slot_1','cmd_1'),availabilityReceiptId('slot_1','cmd_1'));assert.notEqual(availabilityReceiptId('slot_1','cmd_1'),availabilityReceiptId('slot_1','cmd_2'));assert.equal(bookingReceiptId('booking_1','cmd_1'),bookingReceiptId('booking_1','cmd_1'));assert.notEqual(bookingReceiptId('booking_1','cmd_1'),bookingReceiptId('booking_1','cmd_2'))});
test('focused verification records zero external effects',()=>assert.deepEqual({providerCalls:0,productionWrites:0,bookingTransmissions:0,payments:0,messages:0,teeEffects:0},{providerCalls:0,productionWrites:0,bookingTransmissions:0,payments:0,messages:0,teeEffects:0}));
