import assert from "node:assert/strict";
import { validateFrozenAliases } from "./functions-godmode-alias-contract.mjs";
const availability = `export const manageCourseAvailabilityV2=onCall({enforceAppCheck:true},async r=>{const caller=uid(r),m=await membership(caller);db.collection("course_operators")});`;
const booking = `export const managePlayBookingV2=onCall({enforceAppCheck:true},async r=>{const caller=uid(r),scope=await bookingScope(caller);await exactBookingAuthority(caller,scope,"course","mutate");permissions(scope.role)});\nexport const sendPlayBookingMessageV2=onCall({enforceAppCheck:true},async r=>{const caller=uid(r),scope=await bookingScope(caller);await exactBookingAuthority(caller,scope,"course","mutate");permissions(scope.role).message});`;
const validIndex = `export {manageCourseAvailabilityV2 as manageTeeTimeSlot} from "./partnerAvailabilityRuntime.js";\nexport {managePlayBookingV2 as respondBooking,managePlayBookingV2 as cancelBooking,sendPlayBookingMessageV2 as sendBookingMessage} from "./partnerBookingRuntime.js";`;
const valid = { indexSource: validIndex, moduleSources: { "./partnerAvailabilityRuntime.js": availability, "./partnerBookingRuntime.js": booking }, rulesSource: `match /availability_audits/{d=**}{allow read, write: if false;} match /play_booking_audits/{d=**}{allow read, write: if false;}`, authorityGateSource: `const AUTH_COLLECTIONS=['tee_time_slots','bookings'];` };
let count = 0;
const rejects = (name, change) => { const failures = validateFrozenAliases(change(valid)); assert(failures.length > 0, name); count++; console.log(`PASS ${name}`); };
assert.deepEqual(validateFrozenAliases(valid), []); count++; console.log("PASS valid frozen aliases");
rejects("forged alias fails", (x) => ({...x,indexSource:x.indexSource.replace("manageCourseAvailabilityV2 as manageTeeTimeSlot","forgedCallable as manageTeeTimeSlot")}));
rejects("duplicate alias fails", (x) => ({...x,indexSource:`${x.indexSource}\nexport {manageCourseAvailabilityV2 as manageTeeTimeSlot} from "./partnerAvailabilityRuntime.js";`}));
rejects("mismatched module fails", (x) => ({...x,indexSource:x.indexSource.replace('manageCourseAvailabilityV2 as manageTeeTimeSlot} from "./partnerAvailabilityRuntime.js"','manageCourseAvailabilityV2 as manageTeeTimeSlot} from "./partnerBookingRuntime.js"')}));
rejects("missing authority fails", (x) => ({...x,moduleSources:{...x.moduleSources,"./partnerBookingRuntime.js":booking.replaceAll("exactBookingAuthority(caller,scope", "unscopedBookingAuthority(caller,scope")}}));
rejects("missing App Check fails", (x) => ({...x,moduleSources:{...x.moduleSources,"./partnerAvailabilityRuntime.js":availability.replace("enforceAppCheck:true","")}}));
rejects("dead export fails", (x) => ({...x,deadExports:["managePlayBookingV2"]}));
rejects("dead callable body fails", (x) => ({...x,moduleSources:{...x.moduleSources,"./partnerAvailabilityRuntime.js":availability.replace("db.collection",'throw new HttpsError("unavailable");db.collection')}}));
rejects("missing primary authority gate fails", (x) => ({...x,authorityGateSource:x.authorityGateSource.replace("'bookings'", "'other'")}));
rejects("missing audit deny rule fails", (x) => ({...x,rulesSource:x.rulesSource.replace("match /play_booking_audits/","match /other/")}));
console.log(`${count}/${count} frozen alias regression tests PASS`);
