import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';const ui=readFileSync(new URL('../src/components/B2B/PlayBookingLifecycleV2.tsx',import.meta.url),'utf8'),css=readFileSync(new URL('../src/components/B2B/PlayBookingDesk.css',import.meta.url),'utf8');
test('mounted desk uses scoped server projection and exact operation APIs',()=>{for(const x of['getPlayBookingsPortalV2','previewPlayBookingActionV2','managePlayBookingV2','getPlayBookingOperationV2','reconcilePlayBookingOperationV2','parsePlayBookingDeskResponse'])assert.match(ui,new RegExp(x));assert.doesNotMatch(ui,/getPlayBookingsAdminV2|sendPlayBookingMessageV2|collection\(|onSnapshot\(/)});
test('confirmation is obtained after explicit review and bound to stable journal command',()=>{assert.match(ui,/if\(!pending\|\|!ack\|\|busy\)return/);assert.ok(ui.indexOf('const preview=await service.preview')<ui.indexOf('journal.prepare'));assert.ok(ui.indexOf('journal.prepare')<ui.indexOf('service.manage'));for(const x of['confirmationToken:preview.confirmationToken','journal.markInFlight','journal.markAmbiguous','journal.markCompleted','retrySameCommand'])assert.match(ui,new RegExp(x))});
test('successful actions require the immutable backend result and ambiguous errors surface recovery identity',()=>{assert.match(ui,/parseBookingDeskActionResult\(raw/);assert.match(ui,/result\.state!==['"]verified['"]/);assert.match(ui,/result\.receiptId/);assert.match(ui,/errorOperationId\(error\)/);assert.match(ui,/setOperationRef\(operationId\)/)});
test('projection freshness scope and truthful unavailable facts are rendered',()=>{for(const x of['projectionVersionLabel','projectionGeneratedAtLabel','projectionExpiresAtLabel','delegatedCourseIds','providerLabel','termsLabel','contactLabel','unavailableValue'])assert.match(ui,new RegExp(x))});
test('messages remain explicit privacy-minimized approved drafts',()=>{for(const x of['createPlayBookingMessageDraft','playBookingMessageApprovalDigest','approvePlayBookingMessageDraft','messageDraftOnly','messagePrivacyBoundary','messageAwaitingTransmitter'])assert.match(ui,new RegExp(x));for(const type of['request_received','information_needed','alternative_proposed','confirmed','declined','cancellation_received','cancellation_accepted','cancellation_declined','manual_support_required'])assert.match(ui,new RegExp(type));assert.doesNotMatch(ui,/delivered successfully|message sent/i)});
test('ambiguous manager reconciliation exposes only fixed evidence outcomes and confirmation',()=>{for(const x of['organization_owner','organization_admin','failed_no_effect','released_without_execution','completed_verified_receipt','external_review','reconciliationToken','reconcileAck'])assert.match(ui,new RegExp(x));assert.match(ui,/operation\.mayReconcile&&reconciler/)});
test('support and analyst are naturally read only through projected permissions',()=>{assert.match(ui,/p\.permissions\[a\]&&states\[a\]/);assert.doesNotMatch(ui,/support.*true|analyst.*true/)});
test('dialog remains keyboard accessible and controls meet target baseline',()=>{assert.match(ui,/role="dialog" aria-modal="true"/);assert.match(ui,/e\.key==='Escape'/);assert.match(ui,/e\.key!=='Tab'/);assert.match(ui,/returnFocus/);assert.match(ui,/aria-live="polite"/);assert.match(css,/min-height:44px/);assert.match(css,/:focus-visible/);assert.match(css,/@media\(max-width:760px\)/)});
