import test from'node:test';import assert from'node:assert/strict';import{webcrypto}from'node:crypto';import{createPlayBookingOperationJournal}from'../src/components/B2B/playBookingOperationJournal.mjs';
const storage=()=>{const values=new Map;return{values,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}};
const make=(store,scope='scope_opaque_1')=>{const journal=createPlayBookingOperationJournal({storage:store,randomUUID:()=> '11111111-2222-4333-8444-555555555555',digest:value=>webcrypto.subtle.digest('SHA-256',value),now:()=>1000});return journal.activateScope(scope).then(()=>journal)};
test('persists a stable privacy-minimal command before the call and exact retry reuses it',async()=>{const store=storage(),journal=await make(store),input={bookingId:'booking_1',action:'confirm',revision:3,payload:{expectedVersion:3}};const first=await journal.prepare(input);assert.equal(first.state,'prepared');assert.equal((await journal.prepare(input)).commandId,first.commandId);const raw=[...store.values.values()].join(' ');assert.doesNotMatch(raw,/booking_1|member|contact|email|phone/);assert.match(raw,/payloadDigest/);assert.equal(journal.markInFlight(first.commandId),true)});
test('changed payload or revision conflicts under the same booking action slot',async()=>{const journal=await make(storage());await journal.prepare({bookingId:'booking_1',action:'confirm',revision:3,payload:{expectedVersion:3}});assert.equal((await journal.prepare({bookingId:'booking_1',action:'confirm',revision:3,payload:{expectedVersion:4}})).state,'conflict');assert.equal((await journal.prepare({bookingId:'booking_1',action:'confirm',revision:4,payload:{expectedVersion:3}})).state,'conflict')});
test('restart converts an in-flight network outcome to ambiguity and never issues a new command',async()=>{const store=storage(),first=await make(store),prepared=await first.prepare({bookingId:'booking_1',action:'message',revision:2,payload:{templateId:'arrival'}});first.markInFlight(prepared.commandId);const restarted=await make(store);assert.deepEqual(restarted.recover(),[{commandId:prepared.commandId,action:'message',revision:2}]);assert.equal((await restarted.prepare({bookingId:'booking_1',action:'message',revision:2,payload:{templateId:'arrival'}})).state,'ambiguous')});
test('destructive actions require unexpired confirmation metadata but persist no token',async()=>{const store=storage(),journal=await make(store);assert.equal((await journal.prepare({bookingId:'booking_1',action:'cancel',revision:2,payload:{expectedVersion:2}})).state,'invalid');const result=await journal.prepare({bookingId:'booking_1',action:'cancel',revision:2,payload:{expectedVersion:2},confirmation:{slot:'cancel_slot_1',expiresAt:2000}});assert.equal(result.state,'prepared');const raw=[...store.values.values()].join(' ');assert.match(raw,/cancel_slot_1/);assert.doesNotMatch(raw,/confirmationToken|booking_1/)});
test('private payload facts fail closed',async()=>{const journal=await make(storage());for(const payload of[{memberId:'m1'},{contactEmail:'x@y.z'},{message:'private'}])assert.equal((await journal.prepare({bookingId:'booking_1',action:'message',revision:1,payload})).state,'invalid')});
test('authority scope change purges prior operations',async()=>{const store=storage(),journal=await make(store),prepared=await journal.prepare({bookingId:'booking_1',action:'confirm',revision:1,payload:{expectedVersion:1}});await journal.activateScope('scope_opaque_2');assert.equal([...store.values.values()].join(' ').includes(prepared.commandId),false);assert.deepEqual(journal.recover(),[])});
